force-app/main/default/objects/Campaign/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Source_Salesforce;Integrity_Accurate</complianceGroup>
    <description>Campaign Code i.e BP17404</description>
    <externalId>true</externalId>
    <label>Campaign Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Campaign/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Only ANZ Commercial bank is applicable for CCRM. Mulesoft will filter the other campaigns.</description>
    <label>Organization</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ANZ Commercial Bank</fullName>
            </value>
            <value>
                <fullName>Default Organization - Retail</fullName>
            </value>
            <value>
                <fullName>ANZ Private Bank</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Data source name</description>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCM</fullName>
                <default>true</default>
                <label>CCM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Business_ID__c.field-meta.xml
<CustomField>
    <fullName>Business_ID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Customer CAPSIS ID (Business), provided by UNICA</description>
    <label>Business ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <defaultValue>IF(
    NOT(
        CONTAINS( 
            $User.Username,&apos;unica.integration@anzx.com&apos;
        )
    ),
    CASE( 
        $RecordType.Name ,&apos;Commercial CRM Lead&apos;, 
            IF((WEEKDAY(DATEVALUE(NOW() + VALUE($Label.CCRM_ExpiryDateDays))) = 1)
                , NOW() + (VALUE($Label.CCRM_ExpiryDateDays) + 1),
                IF((WEEKDAY(DATEVALUE(NOW() + VALUE($Label.CCRM_ExpiryDateDays))) = 7)
                    , NOW() + VALUE($Label.CCRM_ExpiryDateDays) + 2
                    , NOW() + (VALUE($Label.CCRM_ExpiryDateDays))
                )
            ),
            &apos;Referral&apos;,
            IF((WEEKDAY(DATEVALUE(NOW() + VALUE($Label.Referral_ExpiryDateDays))) = 1)
                , NOW() + (VALUE($Label.Referral_ExpiryDateDays) + 1),
                IF((WEEKDAY(DATEVALUE(NOW() + VALUE($Label.Referral_ExpiryDateDays))) = 7)
                    , NOW() + VALUE($Label.Referral_ExpiryDateDays) + 2
                    , NOW() + (VALUE($Label.Referral_ExpiryDateDays))
                )
            ),
            NULL

    )
    ,NULL
)</defaultValue>
    <description>Expiry date of the lead.</description>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FinServ__ExpressedInterest__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ExpressedInterest__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Source_Salesforce;Integrity_Accurate</complianceGroup>
    <label>Expressed Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FinServ__ProductList</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/FinServ__PotentialValue__c.field-meta.xml
<CustomField>
    <fullName>FinServ__PotentialValue__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <label>Potential Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Originator__c.field-meta.xml
<CustomField>
    <fullName>Lead_Originator__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Lead originating system name</description>
    <label>Lead Originator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adobe</fullName>
            </value>
            <value>
                <fullName>CCRM</fullName>
                <default>true</default>
                <label>CCRM</label>
            </value>
            <value>
                <fullName>UNICA</fullName>
            </value>
            <value>
                <fullName>MLCRM</fullName>
            </value>
            <value>
                <fullName>Lender Engage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/New_to_Bank__c.field-meta.xml
<CustomField>
    <fullName>New_to_Bank__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Salesforce</complianceGroup>
    <description>New to Bank flag</description>
    <inlineHelpText>Customer is new to ANZ</inlineHelpText>
    <label>New to Bank</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the Territory</description>
    <label>Territory</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Territory__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>$User.User_Role__c</field>
            <operation>equals</operation>
            <value>Mobile_Lending_Franchise_Users</value>
        </filterItems>
        <filterItems>
            <field>$User.User_Role__c</field>
            <operation>notEqual</operation>
            <value>Mobile_Lending_Franchise_Users</value>
        </filterItems>
        <filterItems>
            <field>Territory__c.Status__c</field>
            <operation>equals</operation>
            <value>Active, Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/New_to_Bank__c.field-meta.xml
<CustomField>
    <fullName>New_to_Bank__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Personal_Information;Source_Salesforce</complianceGroup>
    <description>New to Bank flag that denotes whether the customer is an existing customer or a new to bank prospect</description>
    <label>New to Bank</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the Territory</description>
    <label>Territory</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Territory__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>$User.User_Role__c</field>
            <operation>equals</operation>
            <value>Mobile_Lending_Franchise_Users</value>
        </filterItems>
        <filterItems>
            <field>$User.User_Role__c</field>
            <operation>notEqual</operation>
            <value>Mobile_Lending_Franchise_Users</value>
        </filterItems>
        <filterItems>
            <field>Territory__c.Status__c</field>
            <operation>equals</operation>
            <value>Active, Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response_Type__c/Response_Type__c.object-meta.xml
<CustomObject>
    <description>Custom Object to store Response Type information.</description>
    <label>Response Type</label>
    <nameField>
        <label>Response Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Response Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Response_Type__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campaign Code to identify the record with the related Campaign parent record.</description>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Response Types</relationshipLabel>
    <relationshipName>Response_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response_Type__c/fields/Create_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Create_Opportunity__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>This flag will determine whether user can click Create Opportunity button along with Division Group</description>
    <label>Create Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Response_Type__c/fields/Create_To_Do_Activities__c.field-meta.xml
<CustomField>
    <fullName>Create_To_Do_Activities__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>This flag will determine whether activities to be created based on response status and outcome reason value in the response record.</description>
    <label>Create To-Do Activities</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Response_Type__c/fields/Display_Order__c.field-meta.xml
<CustomField>
    <fullName>Display_Order__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The order in which outcome reason values will be displayed</description>
    <label>Display Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Response_Type__c/fields/Follow_Up_State__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_State__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Based on the outcome reason value set in the response record, the Follow-Up Date will be set Read Only /Optional /Mandatory</description>
    <label>Follow-Up State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>R</fullName>
                <label>Readonly</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Mandatory</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Optional</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Response_Type__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>This flag decides whether this record is active</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Response_Type__c/fields/Outcome_Reason__c.field-meta.xml
<CustomField>
    <fullName>Outcome_Reason__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Outcome Reason for the response status of the corresponding campaign</description>
    <label>Outcome Reason</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Response_Type__c/fields/Response_Status__c.field-meta.xml
<CustomField>
    <fullName>Response_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Response status for the corresponding campaign</description>
    <label>Response Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/FinServ__ProductList.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Term Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Overdraft</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>Asset Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Merchant</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Foreign Exchange</fullName>
    </customValue>
    <customValue>
        <fullName>Wealth</fullName>
    </customValue>
    <customValue>
        <fullName>Indemnity Guarantee</fullName>
    </customValue>
    <customValue>
        <fullName>Home Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Home Loan - Bridging Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Home Loan - Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Home Loan - Refinance + Purchase</fullName>
    </customValue>
    <customValue>
        <fullName>Home Loan - Purchase</fullName>
    </customValue>
    <customValue>
        <fullName>Home Loan - Refinance</fullName>
    </customValue>
    <customValue>
        <fullName>Home Loan - Maintenance</fullName>
    </customValue>
    <customValue>
        <fullName>Home Loan - Increase</fullName>
    </customValue>
    <customValue>
        <fullName>Home Loan - Other</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Other Loans</fullName>
    </customValue>
    <customValue>
        <fullName>Purchasing Property</fullName>
    </customValue>
    <customValue>
        <fullName>Purchasing Vacant Land</fullName>
    </customValue>
    <customValue>
        <fullName>Purchasing an existing Business</fullName>
    </customValue>
    <customValue>
        <fullName>Purchasing a new Business</fullName>
    </customValue>
    <customValue>
        <fullName>Purchasing equipment (inc. vehicles and fit out)</fullName>
    </customValue>
    <customValue>
        <fullName>Set up a new Business (Start Up)</fullName>
    </customValue>
    <customValue>
        <fullName>Assist with Business Working Capital/Temporary Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Refinance from Other Financial Institutions</fullName>
    </customValue>
    <customValue>
        <fullName>Construction and Renovation</fullName>
    </customValue>
    <masterLabel>Product List</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ccrm/CCRMTaskActionsTest.cls
/**
 * @author Sahil
 * @since  12/2021
 * @description Test class for CCRM Task Action Class.
 */
@IsTest
public with sharing class CCRMTaskActionsTest {
  // Public Declaration

  @TestSetup
  static void setup() {
    User ccrmUser = CCRMTestDataFactory.createCCRMBaseUser();
    User mlUser = MLCRMTestDataFactory.createMLCRMBaseUser();
    // CCRM Test Data Setup
    System.runAs(ccrmUser) {
      CCRMTestDataFactory.createLeadRecords(
        Integer.valueOf(Label.Test_Bulk_Size),
        new User()
      );
      CCRMTestDataFactory.createLeadWithBusinessAccount(new User());
      List<Campaign> campaignRecord = CCRMTestDataFactory.createCCRMCampaignRecord(
        1
      );
      CCRMTestDataFactory.createResponseTypeRecords(campaignRecord[0]);
    }

    System.runAs(mlUser) {
      List<Territory__c> lstOfTerritory = MLCRMTestDataFactory.createTerritoryRecords(
        10,
        mlUser,
        true
      );
      MLCRMTestDataFactory.createUserTerritoryRecords(
        10,
        mlUser.Id,
        lstOfTerritory[0].Id
      );
      MLCRMTestDataFactory.createLeadRecords(10, mlUser);
    }
  }

  @isTest
  static void testExpiryDateLogResponseAddedWithoutFollowupDate() {
    System.runAs(CCRMTestDataFactory.getCCRMBaseUser()) {
      Test.startTest();
      //GIVEN leads
      List<Lead> leads = [SELECT Id FROM Lead LIMIT 1];

      Response_Type__c rtAccepted = [
        SELECT Id, Name, Campaign__c, Response_Status__c, Create_Opportunity__c
        FROM Response_Type__c
        WHERE Response_Status__c = 'Accepted'
        LIMIT 1
      ];

      CCRMTestDataFactory.createCampaignMemberRecord(
        leads,
        rtAccepted.Campaign__c
      );

      Task task = new Task();
      task.Response_Status__c = 'Accepted';
      task.Status = CCRMConstants.STATUS_COMPLETED;
      task.Outcome_Reason__c = 'Happy with the offer';
      task.Subject = 'Accepted' + ': ' + 'Happy with the offer';
      task.Description = 'Test expiry date';
      task.recordTypeId = CCRMConstants.LEAD_RESPONSE_RT_ID;
      task.WhoId = leads[0].Id;
      task.ActivityDate = null;
      task.Response_Type__c = rtAccepted.Id;

      //WHEN
      insert task;
      Test.stopTest();

      //THEN
      Date todaysDate = Date.valueOf(
        System.today() + Integer.valueOf(System.Label.CCRM_Today_Date)
      );
      Date newExpiryDate = DateTimeUtils.getWeekday(
        todaysDate.addDays(5),
        false,
        true
      );
      Lead[] updatedlead = [
        SELECT Id, Expiry_Date__c
        FROM Lead
        WHERE Id = :leads
      ];
      System.assertEquals(
        updatedlead[0].Expiry_Date__c,
        newExpiryDate,
        'Expiry date updated correctly'
      );
    }
  }

  @IsTest
  static void testDeleteResponse() {
    Task task;
    System.runAs(CCRMTestDataFactory.getCCRMBaseUser()) {
      Test.startTest();
      //GIVEN a response is logged against lead
      List<Lead> leads = [SELECT Id FROM Lead LIMIT 1];

      Response_Type__c rtAccepted = [
        SELECT Id, Name, Campaign__c, Response_Status__c, Create_Opportunity__c
        FROM Response_Type__c
        WHERE Response_Status__c = 'Accepted'
        LIMIT 1
      ];
      task = new Task();
      task.Response_Status__c = 'Accepted';
      task.Status = CCRMConstants.STATUS_COMPLETED;
      task.Outcome_Reason__c = 'Happy with the offer';
      task.Subject = 'Accepted' + ': ' + 'Happy with the offer';
      task.Description = 'Test delete response';
      task.recordTypeId = CCRMConstants.LEAD_RESPONSE_RT_ID;
      task.WhoId = leads[0].Id;
      task.Response_Type__c = rtAccepted.Id;
      insert task;

      //WHEN the response is deleted
      CCRMTaskActions.preventDelete(new List<Task>{ task });
      Test.stopTest();
    }

    //THEN the delete action will fail
    System.assert(
      task.hasErrors() &&
      task.getErrors()[0]
        .getMessage()
        .contains(CCRMTaskActions.RESPONSE_DELETE_ERROR_MESSAGE),
      'Must not be able to delete response'
    );
  }

  @IsTest
  static void testMLStatusLogResponse() {
    User objUser = [SELECT Id FROM User WHERE LastName = 'MLCRM' LIMIT 1];
    System.runAs(ObjUser) {
      List<Lead> lstOfLead = [
        SELECT Id
        FROM Lead
        WHERE RecordTypeId = :MLCRMConstants.MLCRM_LEAD_RT_ID
        LIMIT 1
      ];

      Response_Type__c rtAccepted = [
        SELECT Id, Name, Campaign__c, Response_Status__c, Create_Opportunity__c
        FROM Response_Type__c
        WHERE Response_Status__c = 'Accepted'
        LIMIT 1
      ];
      Test.startTest();
      Task task = new Task();
      task.Response_Status__c = 'Accepted';
      task.Status = CCRMConstants.STATUS_COMPLETED;
      task.Outcome_Reason__c = 'Happy with the offer';
      task.Subject = 'Accepted' + ': ' + 'Happy with the offer';
      task.Description = 'Test delete response';
      task.recordTypeId = CCRMConstants.LEAD_RESPONSE_RT_ID;
      task.WhoId = lstOfLead[0].Id;
      task.Response_Type__c = rtAccepted.Id;
      insert task;
      Test.stopTest();
      List<Lead> lstOfUpdatedLead = [
        SELECT Id, Status
        FROM Lead
        WHERE RecordTypeId = :MLCRMConstants.MLCRM_LEAD_RT_ID
        LIMIT 1
      ];
      Assert.areEqual(
        'Opportunity Identified',
        lstOfUpdatedLead[0].status,
        'stage is not opportunity identified!'
      );
    }
  }

  @IsTest
  static void validateLeadExpiryDatePreponed() {
    List<Lead> lstOfLead = new List<Lead>();
    Map<String, Task> mapLeadResponses = new Map<String, Task>();
    Map<Id, Response_Type__c> mapResponseTypeMeta = new Map<Id, Response_Type__c>();
    Map<Id, Date> mapOfCampaign = new Map<Id, Date>();
    Lead leadRecord = new Lead();
    leadRecord.Email = 'sam@test.com';
    leadRecord.RecordTypeId = MLCRMConstants.MLCRM_LEAD_RT_ID;
    leadRecord.Description = 'Need a new Credit Card';
    leadRecord.Expiry_Date__c = System.today() + 10;
    leadRecord.FinServ__ExpressedInterest__c = 'Personal Loan';
    leadRecord.FinServ__PotentialValue__c = 12000;
    leadRecord.FirstName = 'Sam';
    leadRecord.LastName = 'Jacob';
    leadRecord.LeadSource = 'Partner';
    leadRecord.New_to_Bank__c = 'Yes';
    leadRecord.Lead_Originator__c = 'Adobe';
    leadRecord.Business_ID__c = '012345';
    leadRecord.Status = CCRMConstants.STATUS_NEW;
    leadRecord.Id = Lib_FakeIdGenerator.getMockId(Lead.SObjectType);
    lstOfLead.add(leadRecord);

    Task task = new Task();
    task.Response_Status__c = 'Accepted';
    task.Status = CCRMConstants.STATUS_COMPLETED;
    task.Outcome_Reason__c = 'Happy with the offer';
    task.Subject = 'Accepted' + ': ' + 'Happy with the offer';
    task.Description = 'Test delete response';
    task.recordTypeId = CCRMConstants.LEAD_RESPONSE_RT_ID;
    task.WhoId = lstOfLead[0].Id;

    mapLeadResponses.put(task.WhoId, task);

    Campaign campaignRecord = new Campaign();
    campaignRecord.Name = 'CRM Manual Leads';
    campaignRecord.Code__c = System.Label.Commercial_DefaultCampaign;
    campaignRecord.Type = 'Targeted Offer';
    campaignRecord.StartDate = System.today();
    campaignRecord.EndDate = campaignRecord.StartDate.addMonths(1);
    campaignRecord.Source__c = 'CCM';
    campaignRecord.Organization__c = 'ANZ Commercial Bank';
    campaignRecord.Description = 'Manual Leads created by bankers in CRM';
    campaignRecord.Id = Lib_FakeIdGenerator.getMockId(Campaign.SObjectType);

    mapOfCampaign.put(campaignRecord.Id, campaignRecord.EndDate);

    Response_Type__c responseTypeRecord1 = new Response_Type__c();
    responseTypeRecord1.Campaign__c = campaignRecord.Id;
    responseTypeRecord1.Name = 'Flex Field Test Data';
    responseTypeRecord1.Display_Order__c = 1;
    responseTypeRecord1.Response_Status__c = 'Accepted';
    responseTypeRecord1.Outcome_Reason__c = 'Happy with the Offer.';
    responseTypeRecord1.Create_Opportunity__c = true;
    responseTypeRecord1.Create_To_Do_Activities__c = true;
    responseTypeRecord1.Follow_Up_State__c = 'R';
    responseTypeRecord1.Is_Active__c = true;
    responseTypeRecord1.UNICA_Lead_SubStatus__c = 'RPC';
    responseTypeRecord1.Id = Lib_FakeIdGenerator.getMockId(
      Response_Type__c.SObjectType
    );

    mapResponseTypeMeta.put(responseTypeRecord1.Id, responseTypeRecord1);

    CCRMTaskActions.calculateExpiryDate(
      lstOfLead,
      mapLeadResponses,
      mapResponseTypeMeta,
      mapOfCampaign
    );
    System.assertEquals(
      leadRecord.Expiry_Date__c,
      lstOfLead[0].Expiry_Date__c,
      'Expiry date cannot be preposned'
    );
  }
}