force-app/main/default/objects/Case/fields/Assessment_Id__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Id__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <description>Id of the latest assessment. Needed while finalising the assessment</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Assessment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_First_Contacted__c.field-meta.xml
<CustomField>
    <fullName>Customer_First_Contacted__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Date and time when the Customer contacted for this case and Status of the Case updated to &apos;Customer update pending&apos;</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer First Contacted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/OnboardingVerificationFailedReason__c.field-meta.xml
<CustomField>
    <fullName>OnboardingVerificationFailedReason__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The reason why customer verification failed during the Onboarding/ TrustMe process</description>
    <label>Verification Failed Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Selfie fail - selfie image is not clear enough to match</fullName>
                <label>Selfie - Unusable for matching</label>
            </value>
            <value>
                <fullName>Selfie fail - document image is not clear enough to match</fullName>
                <label>ID Document - Poor quality document photo</label>
            </value>
            <value>
                <fullName>Selfie fail - selfie image is clear, but not the same person</fullName>
                <label>Selfie - Facial comparison failed</label>
            </value>
            <value>
                <fullName>Doc fail - document is a picture of a picture</fullName>
                <label>ID Document - Picture of Picture</label>
            </value>
            <value>
                <fullName>Doc fail - document is expired</fullName>
                <label>ID Document - Expired</label>
            </value>
            <value>
                <fullName>Doc fail - document is ineligible type</fullName>
                <label>ID Document - Type not acceptable</label>
            </value>
            <value>
                <fullName>Doc fail - suspected fraud, based on document</fullName>
                <label>ID Document - Suspect fraud</label>
            </value>
            <value>
                <fullName>Doc fail - document details unreadable</fullName>
                <label>ID Document - Data unreadable</label>
            </value>
            <value>
                <fullName>EV Fail - DVS has given fail response</fullName>
                <label>DVS - Fail response</label>
            </value>
            <value>
                <fullName>EV Fail - DVS Data error</fullName>
                <label>DVS - Data error</label>
            </value>
            <value>
                <fullName>Confirmed Fraud - Selfie Watchlist</fullName>
            </value>
            <value>
                <fullName>Confirmed Fraud</fullName>
            </value>
            <value>
                <fullName>Doc fail - doc details are outside of fixable threshold</fullName>
                <isActive>false</isActive>
                <label>Doc fail - doc details are outside of fixable threshold</label>
            </value>
            <value>
                <fullName>EV fail - retries exhausted on customer name variations</fullName>
                <isActive>false</isActive>
                <label>EV fail - retries exhausted on customer name variations</label>
            </value>
            <value>
                <fullName>Selfie fail - selfie image is clear, but a picture of a picture</fullName>
                <isActive>false</isActive>
                <label>Selfie fail - selfie image is clear, but a picture of a picture</label>
            </value>
            <value>
                <fullName>Selfie fail - suspected fraud, based on selfie</fullName>
                <isActive>false</isActive>
                <label>Selfie fail - suspected fraud, based on selfie</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Determines the status of a case with greater granularity</description>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Defect</fullName>
            </value>
            <value>
                <fullName>No Longer Required</fullName>
            </value>
            <value>
                <fullName>Customer Not Responding</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Opt-In</fullName>
            </value>
            <value>
                <fullName>Opt-Out</fullName>
            </value>
            <value>
                <fullName>By Coach</fullName>
            </value>
            <value>
                <fullName>By Customer</fullName>
            </value>
            <value>
                <fullName>Fraud Check Pending</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting Support Coach Action</fullName>
            </value>
            <value>
                <fullName>Customer Servicing</fullName>
            </value>
            <value>
                <fullName>Transfer Completed</fullName>
            </value>
            <value>
                <fullName>Customer request withdrawn</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Fraud.recordType-meta.xml
<RecordType>
    <fullName>Fraud</fullName>
    <active>true</active>
    <businessProcess>Fraud Support Process</businessProcess>
    <description>Record a new fraud case for an existing ANZx customer</description>
    <label>Fraud</label>
</RecordType>

force-app/main/default/classes/GetHelpCaseActionsTest.cls
/**
 * @author shawg2
 * @since Jan 2024
 * @description Test class for GetHelpCaseActions
 */
@IsTest
private class GetHelpCaseActionsTest {
  @IsTest
  static void checkCustomerUpdatePendingStatus() {
    Account oAccount = TestDataFactory.createAccount(true);

    Datetime dtYesterday = Datetime.now().addDays(-1);

    List<Case> lstCases = new List<Case>{
      new Case(
        Id = Lib_FakeIdGenerator.getMockId(Case.SObjectType),
        AccountId = oAccount.Id,
        RecordTypeId = GetHelpConstants.idrtProfileUpdate,
        Type = GetHelpConstants.RESIDENTIAL_ADDRESS_QA,
        Status = GetHelpConstants.CUSTOMER_UPDATE_PENDING
      ),
      new Case(
        Id = Lib_FakeIdGenerator.getMockId(Case.SObjectType),
        AccountId = oAccount.Id,
        RecordTypeId = GetHelpConstants.idrtProfileUpdate,
        Type = GetHelpConstants.RESIDENTIAL_ADDRESS_QA,
        Status = GetHelpConstants.CUSTOMER_UPDATE_PENDING,
        Customer_First_Contacted__c = dtYesterday,
        Assessment_Id__c = 'Just for testing'
      ),
      new Case(
        Id = Lib_FakeIdGenerator.getMockId(Case.SObjectType),
        AccountId = oAccount.Id,
        RecordTypeId = GetHelpConstants.GENERAL_INQUIRY_RT_ID
      )
    };
    Map<Id, Case> mpOldCases = new Map<Id, Case>();
    for (Case oCase : lstCases) {
      mpOldCases.put(
        oCase.Id,
        new Case(Id = oCase.Id, Status = GetHelpConstants.OPEN_STATUS)
      );
    }

    Test.startTest();

    GetHelpCaseActions.checkCustomerUpdatePendingStatus(lstCases, mpOldCases);

    Test.stopTest();

    for (Case oCase : lstCases) {
      if (oCase.RecordTypeId == GetHelpConstants.idrtProfileUpdate) {
        Assert.areNotEqual(
          null,
          oCase.Customer_First_Contacted__c,
          'Customer First Contacted should be initialised.'
        );
        if (oCase.Assessment_Id__c == 'Just for testing') {
          Assert.areEqual(
            dtYesterday,
            oCase.Customer_First_Contacted__c,
            'Customer First Contacted should not be changed.'
          );
        }
      } else {
        Assert.areEqual(
          null,
          oCase.Customer_First_Contacted__c,
          'Other record types should not have a Customer First Contacted value.'
        );
      }
    }
  }

  @IsTest
  static void onlyAllowOneOpenProfileUpdateCase() {
    Account oAccount = TestDataFactory.createAccount(true);

    List<Case> lstCases = new List<Case>{
      new Case(
        AccountId = oAccount.Id,
        RecordTypeId = GetHelpConstants.idrtProfileUpdate,
        Type = GetHelpConstants.RESIDENTIAL_ADDRESS_QA,
        Status = GetHelpConstants.OPEN_STATUS
      ),
      new Case(
        AccountId = oAccount.Id,
        RecordTypeId = GetHelpConstants.idrtProfileUpdate,
        Type = GetHelpConstants.MANUAL_ADDRESS_UPDATE_TYPE,
        Status = GetHelpConstants.WITHDRAWN_STATUS
      )
    };
    insert lstCases;

    Test.startTest();
    // Test using the same inserted Cases as if they were new again
    for (Case oCase : lstCases) {
      oCase.Id = null;
    }
    GetHelpCaseActions.onlyAllowOneOpenProfileUpdateCase(lstCases);

    Test.stopTest();

    lstCases = [
      SELECT Id, AccountId, Status, Sub_Status__c
      FROM Case
      WHERE Status = 'Closed'
    ];
    Assert.areEqual(1, lstCases.size(), 'Should have exactly 1 Closed Case.');
    Assert.areEqual(
      'No Longer Required',
      lstCases[0].Sub_Status__c,
      'Closed Case should be Sub Status: No Longer Required'
    );
  }

  @IsTest
  static void setOwnerToIDOpsQueue() {
    Account oAccount = TestDataFactory.createAccount(true);

    List<Case> lstCases = new List<Case>{
      new Case(
        AccountId = oAccount.Id,
        RecordTypeId = GetHelpConstants.idrtProfileUpdate,
        Type = GetHelpConstants.RESIDENTIAL_ADDRESS_QA,
        Status = GetHelpConstants.OPEN_STATUS
      ),
      new Case(
        AccountId = oAccount.Id,
        RecordTypeId = GetHelpConstants.GENERAL_INQUIRY_RT_ID
      )
    };

    Test.startTest();

    GetHelpCaseActions.setOwnerToIDOpsQueue(lstCases);

    Test.stopTest();

    for (Case oCase : lstCases) {
      if (oCase.RecordTypeId == GetHelpConstants.idrtProfileUpdate) {
        Assert.areEqual(
          GetHelpCaseActions.idOpsQueue.Id,
          oCase.OwnerId,
          'Profile Update cases should be assigned to the ID Ops Queue on insert'
        );
      } else {
        Assert.areNotEqual(
          GetHelpCaseActions.idOpsQueue.Id,
          oCase.OwnerId,
          'Non-Profile Update cases should not be assigned to ID Ops Queue on insert'
        );
      }
    }
  }

  @IsTest
  static void updateIDOpsWatchlistOnboardingReason() {
    List<Case> records = new List<Case>();

    //ID Ops Case with Child Case
    Case idOpsCaseWithChild = new Case(
      Id = Lib_FakeIdGenerator.getMockId(Case.SObjectType),
      RecordTypeId = GetHelpConstants.ID_OPS_ASSISTANCE_RT_ID,
      Status = GetHelpConstants.COB_DAON_FAILED_STATUS,
      Subject = 'ID Ops Assistance - ' +
        GetHelpConstants.COB_DAON_FAILED_SUBJECT_WATCHLIST_HIT
    );
    records.add(idOpsCaseWithChild);

    //Child Fraud Case of idOpsCaseWithChild
    Case fraudCheckCase = new Case(
      Id = Lib_FakeIdGenerator.getMockId(Case.SObjectType),
      RecordTypeId = GetHelpConstants.FRAUD_CHECK_RT_ID,
      Status = GetHelpConstants.COB_DAON_FAILED_STATUS,
      ParentId = idOpsCaseWithChild.Id
    );
    records.add(fraudCheckCase);

    //ID Ops Case with NO Child case
    Case idOpsCaseWithNoChild = new Case(
      Id = Lib_FakeIdGenerator.getMockId(Case.SObjectType),
      RecordTypeId = GetHelpConstants.ID_OPS_ASSISTANCE_RT_ID,
      Status = GetHelpConstants.COB_DAON_FAILED_STATUS,
      Subject = 'ID Ops Assistance - ' +
        GetHelpConstants.COB_DAON_FAILED_SUBJECT_WATCHLIST_HIT
    );
    records.add(idOpsCaseWithNoChild);

    Map<Id, Case> oldMap = new Map<Id, Case>(
      records.deepClone(true, true, true)
    );

    //update the status for trigger to run
    idOpsCaseWithNoChild.Status = GetHelpConstants.COB_CONFIRMED_FRAUD_STATUS;
    idOpsCaseWithChild.Status = GetHelpConstants.COB_CONFIRMED_FRAUD_STATUS;

    GetHelpCaseActionsHelper.getChildCaseListMock = new Set<Id>{
      idOpsCaseWithChild.Id
    };

    Test.startTest();
    GetHelpCaseActions.updateIDOpsWatchlistOnboardingReason(records, oldMap);
    Test.stopTest();

    //Case's OnboardingVerificationFailedReason__c with child should not get updated
    Assert.isNull(
      idOpsCaseWithChild.OnboardingVerificationFailedReason__c,
      'The OnboardingVerificationFailedReason__c should not get updated'
    );

    //Case's OnboardingVerificationFailedReason__c Subject should be updated
    Assert.areEqual(
      GetHelpConstants.ONBOARDING_FAILED_REASON_CONFIRMED_FRAUD_WATCHLIST,
      idOpsCaseWithNoChild.OnboardingVerificationFailedReason__c,
      'The Onboarding Verification Failed Reason should be: ' +
      GetHelpConstants.ONBOARDING_FAILED_REASON_CONFIRMED_FRAUD_WATCHLIST
    );
  }
}