force-app/main/default/objects/Case/fields/Auto_matched_Chat_Topic_IDs__c.field-meta.xml
<CustomField>
    <fullName>Auto_matched_Chat_Topic_IDs__c</fullName>
    <complianceGroup>Integrity_Accurate</complianceGroup>
    <description>List of &apos;|&apos; separated IDs of auto-matched Chat Topics that are possibly related to this Case. Populated by &apos;New&apos; Case button override logic, while trying to auto-link a Chat Topic to a Case. This will be helpful in troubleshooting activities to understand why Chat - Case auto-link might not have happened. This will only be populated in the extremely rare case where a customer might have more than one active Chat session at the same time.</description>
    <inlineHelpText>List of &apos;|&apos; separated IDs of auto-matched Chat Topics that are possibly related to this Case. This will be helpful in troubleshooting activities to understand why Chat - Case auto-link might not have happened.</inlineHelpText>
    <label>Auto-matched Chat Topic IDs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Chat_Topic__c.field-meta.xml
<CustomField>
    <fullName>Chat_Topic__c</fullName>
    <complianceGroup>Source - Twilio;Integrity - Accurate</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to a Chat Topic which resulted this particular Case</description>
    <inlineHelpText>Link to a Chat Topic which resulted this particular Case</inlineHelpText>
    <label>Chat Topic</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Chat_Topic__c.Related_Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <infoMessage>Can only choose Chat Topics related to this customer</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Chat_Topic__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chat_Topic__c/Chat_Topic__c.object-meta.xml
<CustomObject>
    <description>This will be used to cache Twilio Channel information in Salesforce. 
The intention is to use this cached Channel info (e.g. ID) to view/fetch chat transcripts in the future.</description>
    <label>Chat Topic</label>
    <nameField>
        <label>Chat Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chat Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chat_Topic__c/fields/Related_Customer__c.field-meta.xml
<CustomField>
    <fullName>Related_Customer__c</fullName>
    <complianceGroup>Integrity_Accurate;Source_Twilio</complianceGroup>
    <deleteConstraint>Cascade</deleteConstraint>
    <description>Link to the related customer record</description>
    <label>Related Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chat Topics</relationshipLabel>
    <relationshipName>Chat_Topics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chat_Topic__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the current status of a particular chat topic</description>
    <inlineHelpText>Indicates the current status of a particular chat topic</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/idr/NewCaseFlowWrapperController.cls
/**
 * @author saiero
 * @since 2020
 * @group IDR(Internal Dispute Resolution)
 * @description Controller for the lightning component wrapping the Case creation flow, currently only for Complaints.
 */
public with sharing class NewCaseFlowWrapperController {
  /**
   * @description Get the Developer Name of a Case record type based on its Id
   * @param id Record Type ID
   * @return The RT's Dev Name
   */
  @AuraEnabled
  public static String getCaseRecordTypeDevNameById(Id id) {
    return Schema.SObjectType.Case.getRecordTypeInfosById()
      .get(id)
      .getDeveloperName();
  }

  /**
   * @description Get the active Chat Topic ID (if any) by the Account ID (customer)
   * @param accountID Account ID related to the customer
   * @return String having the Active Chat Topic ID
   */
  @AuraEnabled
  public static string getActiveChatTopicIDsByCustomer(Id accountID) {
    String activeChatTopicID = '';
    List<Chat_Topic__c> chatTopics = new List<Chat_Topic__c>();

    if (Chat_Topic__c.sObjectType.getDescribe().isQueryable()) {
      chatTopics = [
        SELECT Id
        FROM Chat_Topic__c
        WHERE Related_Customer__c = :accountID AND Status__c = 'Active'
        ORDER BY LastModifiedDate DESC
      ];
    }

    if (!chatTopics.isEmpty()) {
      if (chatTopics.size() == 1) {
        activeChatTopicID = chatTopics[0].Id;
      } else {
        // Return '|' seperated string of all returned Chat Topic IDs, and save it on a custom field on Case object (not visible on Page Layout) ?
        for (Chat_Topic__c topic : chatTopics) {
          activeChatTopicID += !String.isBlank(activeChatTopicID)
            ? '|' + topic.Id
            : topic.Id;
        }

        //Log an Application Log entry including the '|' seperated string of all returned Chat Topic IDs
        lib_systemLog.createSingleLog(
          NewCaseFlowWrapperController.class.getName(),
          'getActiveChatTopicIDsByCustomer',
          'MORE_THAN_ONE_ACTIVE_CHAT_TOPIC',
          'More than one "Acitve" Chat Topics found while trying to auto-link to a Case.' +
          ' - ' +
          'Chat Topic IDs :' +
          activeChatTopicID +
          ' - Account ID:' +
          accountID +
          ' - ' +
          'If user decides to save the Case (with or without a linked Chat Topic), the custom field "Auto_matched_Chat_Topic_IDs__c" on the particular Case record will me marked with auto-matched Chat Topic IDs to help troubleshooting.',
          lib_systemLog.Severity.WARNING
        );
      }
    }

    return activeChatTopicID;
  }
}