force-app/main/default/objects/Case/fields/CaseNumber__c.field-meta.xml
<CustomField>
    <fullName>CaseNumber__c</fullName>
    <complianceGroup>Integrity - Trusted</complianceGroup>
    <description>Case Number, copied on insertion. Useful if we had to restore as the standard field is an auto-number.</description>
    <externalId>true</externalId>
    <label>Original Case Number</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Determines the status of a case with greater granularity</description>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Defect</fullName>
            </value>
            <value>
                <fullName>No Longer Required</fullName>
            </value>
            <value>
                <fullName>Customer Not Responding</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Opt-In</fullName>
            </value>
            <value>
                <fullName>Opt-Out</fullName>
            </value>
            <value>
                <fullName>By Coach</fullName>
            </value>
            <value>
                <fullName>By Customer</fullName>
            </value>
            <value>
                <fullName>Fraud Check Pending</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting Support Coach Action</fullName>
            </value>
            <value>
                <fullName>Customer Servicing</fullName>
            </value>
            <value>
                <fullName>Transfer Completed</fullName>
            </value>
            <value>
                <fullName>Customer request withdrawn</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/Quality_Assessment__c.object-meta.xml
<CustomObject>
    <label>Quality Assessment</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Quality Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Assessment__c/fields/Case_Manager__c.field-meta.xml
<CustomField>
    <fullName>Case_Manager__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>stores case manager details</description>
    <label>Case Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quality_Assessments2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The original case being assessed</description>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Quality Assessments</relationshipLabel>
    <relationshipName>Quality_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The different status the QA progresses through</description>
    <inlineHelpText>Status of Quality Evaluation</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
                <default>true</default>
                <label>Unassigned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>A dependent picklist based on status for &quot;referred and complete&quot;</description>
    <label>Sub-Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compliance Review</fullName>
            </value>
            <value>
                <fullName>Evaluation Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn/Not Required</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Team_Manager__c.field-meta.xml
<CustomField>
    <fullName>Team_Manager__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>stores case manager&apos;s line manager details</description>
    <label>Team Manager</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Quality Assessments (Team Manager)</relationshipLabel>
    <relationshipName>Quality_Assessments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/TeamManager__c.field-meta.xml
<CustomField>
    <fullName>TeamManager__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>stores case manager's line manager details</description>
    <label>Team Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quality_Assessments3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/idr/IDRQualityAssessmentTaskActions.cls
/**
 * @author Greg Shaw
 * @since 09/2023
 * @description Quality Assessment task related actions for CMOS
 */

public with sharing class IDRQualityAssessmentTaskActions {
  public static void createComplianceTasks(
    List<Quality_Assessment__c> lstAssessments,
    Map<Id, Quality_Assessment__c> mpOldAssessments
  ) {
    Quality_Assessment__c oOldAssessment;
    Set<Id> stCompletedIds = new Set<Id>();
    for (Quality_Assessment__c oAssessment : lstAssessments) {
      if (
        (oAssessment.RecordTypeId == IDRConstants.idrtCQ_QUALITY_ASSESSMENT ||
        oAssessment.RecordTypeId ==
        IDRConstants.idrtCALL_LETTER_REVIEW_QUALITY_ASSESSMENT) &&
        oAssessment.Status__c == QualityAssessmentActions.STATUS_COMPLETE &&
        oAssessment.Sub_Status__c ==
        QualityAssessmentActions.SUB_STATUS_EVALUATION_COMPLETED &&
        (mpOldAssessments == null ||
        (oOldAssessment = mpOldAssessments.get(oAssessment.Id)) == null ||
        oAssessment.Status__c != oOldAssessment.Status__c ||
        oAssessment.Sub_Status__c != oOldAssessment.Sub_Status__c)
      ) {
        stCompletedIds.add(oAssessment.Id);
      }
    }
    if (
      stCompletedIds.size() > 0 &&
      Task.SObjectType.getDescribe().isCreateable() &&
      Schema.SObjectType.Task.fields.ActivityDate.isCreateable() &&
      Schema.SObjectType.Task.fields.OwnerId.isCreateable() &&
      Schema.SObjectType.Task.fields.RecordTypeId.isCreateable() &&
      Schema.SObjectType.Task.fields.Subject.isCreateable() &&
      Schema.SObjectType.Task.fields.WhatId.isCreateable()
    ) {
      List<Quality_Assessment__c> lstCompletedAssessments = [
        SELECT
          Id,
          TeamManager__c,
          TeamManager__r.Name, Case_Manager__c,
          Related_Case__r.CaseNumber__c
        FROM Quality_Assessment__c
        WHERE
          Id IN :stCompletedIds
          AND TeamManager__c != NULL
          AND Case_Manager__c != NULL
      ];
      List<Task> lstComplianceTasks = new List<Task>();
      for (Quality_Assessment__c oAssessment : lstCompletedAssessments) {
        lstComplianceTasks.add(
          new Task(
            RecordTypeId = GetHelpConstants.TASK_COMPLIANCE_RT_ID,
            OwnerId = oAssessment.TeamManager__c,
            WhatId = oAssessment.Id,
            //            Subject = IDRConstants.TASK_QA_COMPLIANCE_SUBJECT + oAssessment.Team_Manager__r.Name + ' : case ' + oAssessment.Related_Case__r.CaseNumber__c,
            ActivityDate = Date.today().addDays(7),
            Status = 'Open',
            Priority = 'Normal'
          )
        );
      }
      if (lstComplianceTasks.size() > 0) {
        insert lstComplianceTasks;
      }
    }
  }
}