force-app/main/default/objects/Case/fields/Credit_Id__c.field-meta.xml
<CustomField>
    <fullName>Credit_Id__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Loan Domain</complianceGroup>
    <description>Id of the Credit Assessment</description>
    <externalId>true</externalId>
    <label>Credit Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code__c</fullName>
    <complianceGroup>Source_Salesforce;Integrity_Trusted;Privacy_Non_Personal_Information</complianceGroup>
    <description>NPP reason code for the case.</description>
    <formula>IF(RecordType.DeveloperName = &quot;NPP_Dispute&quot; &amp;&amp; ISPICKVAL(Dispute_Reason__c, &quot;Incorrect Amount Transferred&quot;), &quot;DUPL&quot;,
IF(RecordType.DeveloperName = &quot;NPP_Dispute&quot; &amp;&amp; ISPICKVAL(Dispute_Reason__c, &quot;Incorrect Account Details&quot;), &quot;CUST&quot;,
IF(RecordType.DeveloperName = &quot;NPP_Dispute&quot; &amp;&amp; ISPICKVAL(Dispute_Reason__c, &quot;Duplicate Transaction&quot;), &quot;DUPL&quot;,
IF(RecordType.DeveloperName = &quot;NPP_Dispute&quot; &amp;&amp; ISPICKVAL(Dispute_Reason__c, &quot;Return money received from an unknown person&quot;), &quot;MD06&quot;,
IF(RecordType.DeveloperName = &quot;IMT_Dispute&quot; &amp;&amp; ISPICKVAL(Dispute_Reason__c, &quot;Cancel Transfer&quot;), &quot;CB_Cance_Out&quot;,
IF(RecordType.DeveloperName = &quot;IMT_Dispute&quot; &amp;&amp; ISPICKVAL(Dispute_Reason__c, &quot;Payee has not received funds&quot;), &quot;CB_BCNR&quot;,
IF(RecordType.DeveloperName = &quot;IMT_Dispute&quot; &amp;&amp; ISPICKVAL(Dispute_Reason__c, &quot;Amendment Request&quot;), &quot;AmendBen&quot;,
IF(RecordType.DeveloperName = &quot;IMT_Dispute&quot; &amp;&amp; ISPICKVAL(Dispute_Reason__c, &quot;Suspected fraud&quot;), &quot;CB_Cance_Out&quot;,&quot;&quot;))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reason Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Reason__c/Referral_Reason__c.object-meta.xml
<CustomObject>
    <label>Referral Reason</label>
    <nameField>
        <label>Referral Reason Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Reasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Reason__c/fields/Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <description>Credit assessment outcome reason code</description>
    <externalId>true</externalId>
    <label>Reason Code</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ResidentialLoanApplication/fields/Credit_ID__c.field-meta.xml
<CustomField>
    <fullName>Credit_ID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <description>A unique ID that identifies a credit enquiry against the home loan application</description>
    <label>Credit ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreditAssessmentControllerTest.cls
/**
 * @author cruzb
 * @since May 2023
 * @description Controller test class for Apex remote CreditAssessmentController
 * @group Services
 */
@isTest
public with sharing class CreditAssessmentControllerTest {
  /**
   * @description This setup method creates the record(s) required for the test classes
   */
  @testSetup
  public static void setup() {
    insert new Referral_Reason__c(Reason_Code__c = 'RE202');
    ResidentialLoanApplication[] newRLA = new List<ResidentialLoanApplication>();
    Account rlaCustomer = TestDataFactory.createAccount('CustomerRLA', true);
    for (Integer i = 0; i < Integer.valueOf(Label.Test_Bulk_Size); i++) {
      ResidentialLoanApplication rla = TestDataFactory.createTestResidentialLoanApplication(
        String.valueOf(i)
      );
      rla.Credit_ID__c = '000-000-000-00' + String.valueOf(i);
      rla.AccountId = rlaCustomer.Id;

      newRLA.add(rla);
    }
    insert newRLA;
  }

  @isTest
  static void testGetCreditAssessments() {
    Account acc = [SELECT Id FROM Account WHERE Name = 'CustomerRLA' LIMIT 1];

    Case c = new Case(
      RecordTypeID = GetHelpConstants.CREDIT_REFERRAL_RT_ID,
      Subject = 'Test Credit Referral',
      Status = 'Open',
      AccountId = acc.Id,
      Credit_Id__c = '000-000-000-001'
    );
    insert c;
    Map<String, Object> objectMap = new Map<String, Object>();
    CreditAssessmentController crAssessment = new CreditAssessmentController();
    Map<String, Object> inputMap = new Map<String, Object>();
    inputMap.put('creditId', '1231');
    inputMap.put('recordId', c.Id);
    inputMap.put('ocvId', '123123');
    Boolean isInvoked = crAssessment.invokeMethod(
      'getCreditAssessments',
      inputMap,
      objectMap,
      new Map<String, Object>()
    );
    Object payload = objectMap.get('object');
    System.assert(isInvoked, 'Method not invoked');
    System.assertNotEquals(payload, null, 'Empty JSON');
    System.assertNotEquals(
      ((Map<String, Object>) payload).get('current'),
      null,
      'Missing `current` node'
    );
    System.assertNotEquals(
      ((Map<String, Object>) payload).get('history'),
      null,
      'Missing `history` node'
    );
    CreditReferralModel model = CreditReferralModel.parse(
      json.serialize(((Map<String, Object>) payload).get('current'))
    );
    System.assert(
      !model.assessments[0].outcome.contains('_'),
      'Outcome not transformed'
    );
  }

  @isTest
  static void testgetAssessmentOutcome() {
    Account customer = TestDataFactory.createAccount('test customer', true);
    ResidentialLoanApplication r = TestDataFactory.createTestResidentialLoanApplication(
      '1'
    );
    r.accountId = customer.Id;
    r.Status = 'STATE_DECLINED';
    insert r;
    system.debug(r.id);
    Map<String, Object> objectMap = new Map<String, Object>();
    CreditAssessmentController crAssessment = new CreditAssessmentController();
    Map<String, Object> inputMap = new Map<String, Object>();
    inputMap.put('ApplicationId', r.Id);
    Boolean isInvoked = crAssessment.invokeMethod(
      'getAssessmentOutcome',
      inputMap,
      objectMap,
      new Map<String, Object>()
    );
    Object payload = objectMap.get('object');
    System.assert(isInvoked, 'Method not invoked');
    System.assertNotEquals(payload, null, 'Empty JSON');
    System.assertNotEquals(
      ((Map<String, Object>) payload).get('lastModified'),
      null,
      'Missing `lastModified` node'
    );
    System.assertNotEquals(
      ((Map<String, Object>) payload).get('rows'),
      null,
      'Missing `rows` node'
    );
  }
}