force-app/main/default/objects/Case/fields/CustomerOnboardingApplication__c.field-meta.xml
<CustomField>
    <fullName>CustomerOnboardingApplication__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup relationship field that looks up to the Customer Onboarding Application object</description>
    <label>Customer Onboarding Application</label>
    <referenceTo>CustomerOnboardingApplication__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/OnboardingVerificationFailedReason__c.field-meta.xml
<CustomField>
    <fullName>OnboardingVerificationFailedReason__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The reason why customer verification failed during the Onboarding/ TrustMe process</description>
    <label>Verification Failed Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Selfie fail - selfie image is not clear enough to match</fullName>
                <label>Selfie - Unusable for matching</label>
            </value>
            <value>
                <fullName>Selfie fail - document image is not clear enough to match</fullName>
                <label>ID Document - Poor quality document photo</label>
            </value>
            <value>
                <fullName>Selfie fail - selfie image is clear, but not the same person</fullName>
                <label>Selfie - Facial comparison failed</label>
            </value>
            <value>
                <fullName>Doc fail - document is a picture of a picture</fullName>
                <label>ID Document - Picture of Picture</label>
            </value>
            <value>
                <fullName>Doc fail - document is expired</fullName>
                <label>ID Document - Expired</label>
            </value>
            <value>
                <fullName>Doc fail - document is ineligible type</fullName>
                <label>ID Document - Type not acceptable</label>
            </value>
            <value>
                <fullName>Doc fail - suspected fraud, based on document</fullName>
                <label>ID Document - Suspect fraud</label>
            </value>
            <value>
                <fullName>Doc fail - document details unreadable</fullName>
                <label>ID Document - Data unreadable</label>
            </value>
            <value>
                <fullName>EV Fail - DVS has given fail response</fullName>
                <label>DVS - Fail response</label>
            </value>
            <value>
                <fullName>EV Fail - DVS Data error</fullName>
                <label>DVS - Data error</label>
            </value>
            <value>
                <fullName>Confirmed Fraud - Selfie Watchlist</fullName>
            </value>
            <value>
                <fullName>Confirmed Fraud</fullName>
            </value>
            <value>
                <fullName>Doc fail - doc details are outside of fixable threshold</fullName>
                <isActive>false</isActive>
                <label>Doc fail - doc details are outside of fixable threshold</label>
            </value>
            <value>
                <fullName>EV fail - retries exhausted on customer name variations</fullName>
                <isActive>false</isActive>
                <label>EV fail - retries exhausted on customer name variations</label>
            </value>
            <value>
                <fullName>Selfie fail - selfie image is clear, but a picture of a picture</fullName>
                <isActive>false</isActive>
                <label>Selfie fail - selfie image is clear, but a picture of a picture</label>
            </value>
            <value>
                <fullName>Selfie fail - suspected fraud, based on selfie</fullName>
                <isActive>false</isActive>
                <label>Selfie fail - suspected fraud, based on selfie</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PersonaId__c.field-meta.xml
<CustomField>
    <fullName>PersonaId__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>The ForgeRock-minted UUID identifying the persona attempting to onboard</description>
    <externalId>true</externalId>
    <label>Persona Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Fraud.recordType-meta.xml
<RecordType>
    <fullName>Fraud</fullName>
    <active>true</active>
    <businessProcess>Fraud Support Process</businessProcess>
    <description>Record a new fraud case for an existing ANZx customer</description>
    <label>Fraud</label>
</RecordType>

force-app/main/default/objects/CustomerOnboardingApplication__c/CustomerOnboardingApplication__c.object-meta.xml
<CustomObject>
    <label>Customer Onboarding Application</label>
    <nameField>
        <displayFormat>COB-{00000000}</displayFormat>
        <label>Customer Onboarding Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Onboarding Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerOnboardingApplication__c/fields/PersonaId__c.field-meta.xml
<CustomField>
    <fullName>PersonaId__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>The ForgeRock-minted UUID identifying the persona attempting to onboard</description>
    <externalId>true</externalId>
    <label>Persona Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/COBCaseActionsTest.cls
/**
 * @description Test class for {@link COBCaseActions}
 * @author Karen Valeriano
 * @since 08/2023
 */
@isTest
private class COBCaseActionsTest {
  static final Faker FAKER = new Faker('en-AU');

  static Lib_MockProvider dmlRepoMock;
  static Lib_MockProvider cobCaseRepoMock;

  static Id idOpsId = Lib_FakeIdGenerator.getMockId(Case.SObjectType);

  static Case idOpsCase = new Case(
    Id = idOpsId,
    RecordTypeId = RTCase.idOpsAssistance,
    Status = COBCaseConstants.COB_POTENTIAL_FRAUD_STATUS,
    CustomerOnboardingApplication__c = Lib_FakeIdGenerator.getMockId(
      CustomerOnboardingApplication__c.SObjectType
    ),
    PersonaId__c = FAKER.randomString(10)
  );

  static Case fraudCheckCase = new Case(
    Id = Lib_FakeIdGenerator.getMockId(Case.SObjectType),
    RecordTypeId = RTCase.fraudCheck,
    Status = COBCaseConstants.COB_DAON_FALLOUT_STATUS,
    ParentId = idOpsId
  );

  static Map<Id, Case> oldFraudCheckMap = new Map<Id, Case>{
    fraudCheckCase.Id => fraudCheckCase
  };

  static void registerMocks() {
    dmlRepoMock = Lib_MockProvider.forType(DmlRepository.class);
    cobCaseRepoMock = Lib_MockProvider.forType(COBCaseRepository.class);
  }

  @isTest
  static void testCreateFraudCheckCase() {
    registerMocks();

    //Create Id Ops Case to be used as Old Map record
    Case oldIdOpsCase = idOpsCase.clone(true);
    oldIdOpsCase.Status = COBCaseConstants.COB_DAON_FALLOUT_STATUS;

    Map<Id, Case> oldIdOpsMap = new Map<Id, Case>{ idOpsId => oldIdOpsCase };

    Test.startTest();
    COBCaseActions.createFraudCheckCase(
      new List<Case>{ idOpsCase },
      oldIdOpsMap
    );
    Test.stopTest();

    Assert.isNotNull(
      dmlRepoMock.getHistory('doInsert'),
      'doInsert should have been invoked'
    );

    List<Case> insertedRecords = (List<Case>) dmlRepoMock.getHistory('doInsert')
      .getParam('records');

    Assert.areEqual(
      new Case(
        RecordTypeId = RTCase.fraudCheck,
        OwnerId = QueryQueue.cobFraudCheckQueue.Id,
        Status = oldIdOpsCase.Status,
        ParentId = oldIdOpsCase.Id,
        Subject = 'Fraud Check Case',
        CustomerOnboardingApplication__c = idOpsCase.CustomerOnboardingApplication__c,
        PersonaId__c = idOpsCase.PersonaId__c
      ),
      insertedRecords[0],
      'New Fraud Check Case record should be created with the correct field values'
    );
  }

  @isTest
  static void testSetIDOpsCaseStatusConfirmedFraud() {
    registerMocks();

    //Update the Fraud Check Case status and OnboardingVerificationFailedReason__c
    fraudCheckCase.Status = COBCaseConstants.COB_CONFIRMED_FRAUD_STATUS;
    fraudCheckCase.OnboardingVerificationFailedReason__c = COBCaseConstants.COB_CONFIRMED_FRAUD_STATUS;

    List<Case> idOpsCases = new List<Case>{ idOpsCase };
    cobCaseRepoMock.mock('getCasesByIds', idOpsCases);

    //Create Map of ParentId and updated Child Case
    Map<Id, Case> parentIdAndChildCaseMap = new Map<Id, Case>{
      fraudCheckCase.ParentId => fraudCheckCase
    };

    Test.startTest();
    idOpsCases = COBCaseActions.setIDOpsCaseStatus(
      parentIdAndChildCaseMap,
      oldFraudCheckMap
    );
    Test.stopTest();

    Assert.isFalse(
      cobCaseRepoMock.getHistories('getCasesByIds').isEmpty(),
      'getCasesByIds should have been called'
    );

    Assert.areEqual(
      fraudCheckCase.Status,
      idOpsCases[0].Status,
      'Status should be ' + fraudCheckCase.Status
    );

    Assert.areEqual(
      fraudCheckCase.OnboardingVerificationFailedReason__c,
      idOpsCases[0].OnboardingVerificationFailedReason__c,
      'OnboardingVerificationFailedReason__c should be ' +
      fraudCheckCase.OnboardingVerificationFailedReason__c
    );
  }

  @isTest
  static void testSetIDOpsCaseStatusToDaonFallout() {
    registerMocks();

    //Clone existing Fraud Case record to preserve the one that's in oldFraudCheckMap
    Case newFraudCase = fraudCheckCase.clone(true);

    //Update the Fraud Check Case status
    newFraudCase.Status = COBCaseConstants.COB_NOT_A_FRAUD_STATUS;

    //Create Map of ParentId and updated Child Case
    Map<Id, Case> newParentIdAndChildCaseMap = new Map<Id, Case>{
      newFraudCase.ParentId => newFraudCase
    };

    List<Case> idOpsCases = new List<Case>{ idOpsCase };
    cobCaseRepoMock.mock('getCasesByIds', idOpsCases);

    Test.startTest();
    idOpsCases = COBCaseActions.setIDOpsCaseStatus(
      newParentIdAndChildCaseMap,
      oldFraudCheckMap
    );
    Test.stopTest();

    Assert.isFalse(
      cobCaseRepoMock.getHistories('getCasesByIds').isEmpty(),
      'getCasesByIds should have been called'
    );

    Assert.areEqual(
      COBCaseConstants.COB_DAON_FALLOUT_STATUS,
      idOpsCases[0].Status,
      'Status should be ' + COBCaseConstants.COB_DAON_FALLOUT_STATUS
    );

    Assert.isTrue(
      String.isBlank(idOpsCases[0].OnboardingVerificationFailedReason__c),
      'OnboardingVerificationFailedReason__c should be blank'
    );
  }

  @isTest
  static void testSetIDOpsCaseStatusToEquifaxFallout() {
    registerMocks();

    fraudCheckCase.Status = COBCaseConstants.COB_EQUIFAX_FALLOUT_STATUS;
    //Clone existing Fraud Case record to preserve the one that's in oldFraudCheckMap
    Case newFraudCase = fraudCheckCase.clone(true);

    //Update the Fraud Check Case status
    newFraudCase.Status = COBCaseConstants.COB_NOT_A_FRAUD_STATUS;

    //Map of ParentId and updated Child Case
    Map<Id, Case> newParentIdAndChildCaseMap = new Map<Id, Case>{
      newFraudCase.ParentId => newFraudCase
    };

    List<Case> idOpsCases = new List<Case>{ idOpsCase };
    cobCaseRepoMock.mock('getCasesByIds', idOpsCases);

    Test.startTest();
    idOpsCases = COBCaseActions.setIDOpsCaseStatus(
      newParentIdAndChildCaseMap,
      oldFraudCheckMap
    );
    Test.stopTest();

    Assert.isFalse(
      cobCaseRepoMock.getHistories('getCasesByIds').isEmpty(),
      'getCasesByIds should have been called'
    );

    Assert.areEqual(
      COBCaseConstants.COB_EQUIFAX_FALLOUT_STATUS,
      idOpsCases[0].Status,
      'Status should be ' + COBCaseConstants.COB_EQUIFAX_FALLOUT_STATUS
    );

    Assert.isTrue(
      String.isBlank(idOpsCases[0].OnboardingVerificationFailedReason__c),
      'OnboardingVerificationFailedReason__c should be blank'
    );
  }

  @isTest
  static void testUpdateIDOpsCaseStatus() {
    registerMocks();
    cobCaseRepoMock.mock('getCasesByIds', new List<Case>{ idOpsCase });

    //Clone existing Fraud Case record to preserve the one that's in oldFraudCheckMap
    Case childFraudCase = fraudCheckCase.clone(true);

    //Update the Fraud Check Case status
    childFraudCase.Status = COBCaseConstants.COB_CONFIRMED_FRAUD_STATUS;

    Test.startTest();
    COBCaseActions.updateIdOpsCaseStatus(
      new List<Case>{ childFraudCase },
      oldFraudCheckMap
    );
    Test.stopTest();

    Assert.isFalse(
      cobCaseRepoMock.getHistories('getCasesByIds').isEmpty(),
      'getCasesByIds should have been called'
    );

    Assert.isNotNull(
      dmlRepoMock.getHistory('doUpdate'),
      'doUpdate should have been invoked'
    );

    List<Case> parentIdOpsRecords = (List<Case>) dmlRepoMock.getHistory(
        'doUpdate'
      )
      .getParam('records');

    Assert.areEqual(
      childFraudCase.Status,
      parentIdOpsRecords[0].Status,
      'The ID Ops Case record should have been updated with ' +
      childFraudCase.Status
    );
  }
}