force-app/main/default/objects/Case/fields/CustomerOnboardingApplication__c.field-meta.xml
<CustomField>
    <fullName>CustomerOnboardingApplication__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup relationship field that looks up to the Customer Onboarding Application object</description>
    <label>Customer Onboarding Application</label>
    <referenceTo>CustomerOnboardingApplication__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_Address_Valid__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Address_Valid__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Check: 

The residential address populated in the customer profile in Fenergo can be reasonably understood to be a place where the person resides</description>
    <inlineHelpText>Check: 

The residential address populated in the customer profile in Fenergo can be reasonably understood to be a place where the person resides</inlineHelpText>
    <label>Residential address is valid</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_Customer_Details__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Customer_Details__c</fullName>
    <complianceGroup>Integrity - Trusted;Source - Salesforce;Privacy - Non Personal Information</complianceGroup>
    <description>Check: 

The following customer information in Fenergo matches the details on the ID Document: 
first &amp; last name; middle name (per framework); date of birth; ID document number, expiry date (if required), and issue state/country</description>
    <inlineHelpText>Check: 

The following customer information in Fenergo matches the details on the ID Document: 
first &amp; last name; middle name (per framework); date of birth; ID document number, expiry date (if required), and issue state/country</inlineHelpText>
    <label>KYC Information is a Match &amp; Complete</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_Customer_Photo_Modified__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Customer_Photo_Modified__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Trusted;Source - Salesforce</complianceGroup>
    <description>Confirm:

Customer&apos;s photograph on the identity document is not superimposed or replaced with another person&apos;s photograph.</description>
    <inlineHelpText>Confirm:

Customer&apos;s photograph on the identity document is not superimposed or replaced with another person&apos;s photograph.</inlineHelpText>
    <label>Customer&apos;s Photo is Not Modified</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_Defects_Rectified__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Defects_Rectified__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Trusted;Source - Salesforce</complianceGroup>
    <description>Have all identified defects been rectified either in the customer profile or by obtaining a new image of the identity document if required?</description>
    <inlineHelpText>Have all identified defects been rectified either in the customer profile or by obtaining a new image of the identity document if required?</inlineHelpText>
    <label>Have All Defects Been Rectified</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Customer Has Failed to Respond</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_ID_Legible__c.field-meta.xml
<CustomField>
    <fullName>Fraud_ID_Legible__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>The customer&apos;s photograph on the identity document is legible and can be relied upon for selfie comparison.</description>
    <inlineHelpText>The customer&apos;s photograph on the identity document is legible and can be relied upon for selfie comparison.</inlineHelpText>
    <label>Customer Photo on ID Legibility Check</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_ID_Not_Picture__c.field-meta.xml
<CustomField>
    <fullName>Fraud_ID_Not_Picture__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Trusted;Source - Salesforce</complianceGroup>
    <description>Confirm:

The image provided by customer does not look like a image of a picture of an actual identity document.</description>
    <inlineHelpText>Confirm:

The image provided by customer does not look like a image of a picture of an actual identity document.</inlineHelpText>
    <label>Image is not a Picture of ID Document</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_MiddleNameCheck__c.field-meta.xml
<CustomField>
    <fullName>Fraud_MiddleNameCheck__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Check: 

That the middle name present on the document is recorded correctly per the framework</description>
    <inlineHelpText>Check: 

That the middle name present on the document is recorded correctly per the framework</inlineHelpText>
    <label>Middle Name Check</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_PO_Box__c.field-meta.xml
<CustomField>
    <fullName>Fraud_PO_Box__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Trusted;Source - Salesforce</complianceGroup>
    <description>Check:

The residential address populated in customer profile in SalesForce is not a Post Office Box address or an ANZ Head Office Address.</description>
    <inlineHelpText>Check:

The residential address populated in customer profile in SalesForce is not a Post Office Box address or an ANZ Head Office Address.</inlineHelpText>
    <label>Residential Address is Not a PO Box</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_Restraint_Status__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Restraint_Status__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>What is the current state of restraint on the customer&apos;s account?</description>
    <inlineHelpText>What is the current state of restraint on the customer&apos;s account?</inlineHelpText>
    <label>Restraint Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Customer requested closure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_Security_Features__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Security_Features__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>The image of the identity document shows holographic features or any other security features under reasonable level of lighting. Note: Judgement needs to be exercised, as holographic features may not appear under low light.</description>
    <inlineHelpText>The image of the identity document shows holographic features or any other security features under reasonable level of lighting. Note: Judgement needs to be exercised, as holographic features may not appear under low light.</inlineHelpText>
    <label>ID Document Security Features Check</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_Selfie_Comparison_Match__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Selfie_Comparison_Match__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Check: 

The person in the selfie image is the same person as photographed on the ID document image.</description>
    <inlineHelpText>Check: 

The person in the selfie image is the same person as photographed on the ID document image.</inlineHelpText>
    <label>Selfie Comparison Match</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_Date_Received__c.field-meta.xml
<CustomField>
    <fullName>IDR_Date_Received__c</fullName>
    <complianceGroup>Integrity - Accurate</complianceGroup>
    <defaultValue>NOW()</defaultValue>
    <description>Datetime received, may not be the record&apos;s created date in SF (data import, replication delays, ...). Leave blank for TODAY.</description>
    <inlineHelpText>Datetime received, may not be the record&apos;s created date in SF (data import, replication delays, ...). Leave blank for TODAY.</inlineHelpText>
    <label>Date Received</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Determines the status of a case with greater granularity</description>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Defect</fullName>
            </value>
            <value>
                <fullName>No Longer Required</fullName>
            </value>
            <value>
                <fullName>Customer Not Responding</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Opt-In</fullName>
            </value>
            <value>
                <fullName>Opt-Out</fullName>
            </value>
            <value>
                <fullName>By Coach</fullName>
            </value>
            <value>
                <fullName>By Customer</fullName>
            </value>
            <value>
                <fullName>Fraud Check Pending</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting Support Coach Action</fullName>
            </value>
            <value>
                <fullName>Customer Servicing</fullName>
            </value>
            <value>
                <fullName>Transfer Completed</fullName>
            </value>
            <value>
                <fullName>Customer request withdrawn</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Twilio_Channel_SID__c.field-meta.xml
<CustomField>
    <fullName>Twilio_Channel_SID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Twilio</complianceGroup>
    <description>Would store Twilio Channel SID related to the Chat Topic which originated current Case record</description>
    <externalId>true</externalId>
    <inlineHelpText>Twilio Channel SID related to the Chat Topic which originated this Case record</inlineHelpText>
    <label>Chat Topic ID</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/cloudEventModels/AutoKYCQACaseCloudEventModel.cls
/**
 * @author Batya Aisnman Sufrin
 * @since  08/2023
 * @description Wrapper Class for AutoKYCQA metadata and data
 */
@SuppressWarnings(
  'PMD.ApexDoc, PMD.ExcessivePublicCount, PMD.PropertyNamingConventions, PMD.ExcessiveParameterList'
)
public with sharing class AutoKYCQACaseCloudEventModel extends CaseCloudEventModel {
  private static final Integer RECORD_TYPE_AUTOKYC_QA = 1;
  private static final String AUTO_KYC_QA_SCHEMA = '#AutoKYCQA';

  public AutoKYCQACaseCloudEventModel(
    Case theCase,
    Account theAccount,
    String action,
    User theUser,
    UserModel theOwner,
    CustomerOnboardingApplication__c theCOB
  ) {
    super(theCase, theAccount);
    ce_type = System.Label.ANZX_AutoKYCQA_Event_ce_type + action;
    ce_dataschema =
      System.Label.ANZX_CustomerValidation_Event_Proto_Data_Schema +
      AUTO_KYC_QA_SCHEMA;
    this.ce_data = new AutoKYCQACaseCloudEventDataModel(
      theCase,
      theAccount,
      theOwner,
      theCOB
    );
    this.systemData = new CloudEventSystemModel(
      theCase.LastModifiedDate,
      theUser
    );
  }

  /**
   * @description the model for AutoKYCQA Case cloud event data part
   */
  public class AutoKYCQACaseCloudEventDataModel extends CaseCloudEventModel.CaseCloudEventDataModel {
    public CustomerOnboardingApplicationModel customerOnboardingApplication {
      get;
      set;
    }
    public String parentCase { get; set; }
    public Datetime dateReceived { get; set; }
    public String chatTopicId { get; set; }
    public String subStatus { get; set; }
    public String contactId { get; set; }
    public String contactMobile { get; set; }
    public String fraudCustomerDetails { get; set; }
    public String fraudMiddleNameCheck { get; set; }
    public String fraudSelfieComparisonMatch { get; set; }
    public String fraudPOBox { get; set; }
    public String fraudAddressValid { get; set; }
    public String fraudRestraintStatus { get; set; }
    public String fraudIDLegible { get; set; }
    public String fraudIDNotPicture { get; set; }
    public String fraudCustomerPhotoModified { get; set; }
    public String fraudSecurityFeatures { get; set; }
    public String fraudDefectsRectified { get; set; }
    public String suppliedEmail { get; set; }
    public Integer recordType { get; set; }

    public AutoKYCQACaseCloudEventDataModel(
      Case theCase,
      Account theAccount,
      UserModel theOwner,
      CustomerOnboardingApplication__c theCOB
    ) {
      super(theCase, theAccount, theOwner);
      this.customerOnboardingApplication = new CustomerOnboardingApplicationModel(
        theCOB
      );
      this.parentCase = theCase.ParentId;
      this.dateReceived = theCase.IDR_Date_Received__c;
      this.chatTopicId = theCase.Twilio_Channel_SID__c;
      this.subStatus = theCase.Sub_Status__c;
      this.contactId = theCase.ContactId;
      this.contactMobile = theCase.ContactMobile;
      this.fraudCustomerDetails = theCase.Fraud_Customer_Details__c;
      this.fraudMiddleNameCheck = theCase.Fraud_MiddleNameCheck__c;
      this.fraudSelfieComparisonMatch = theCase.Fraud_Selfie_Comparison_Match__c;
      this.fraudPOBox = theCase.Fraud_PO_Box__c;
      this.fraudAddressValid = theCase.Fraud_Address_Valid__c;
      this.fraudRestraintStatus = theCase.Fraud_Restraint_Status__c;
      this.fraudIDLegible = theCase.Fraud_ID_Legible__c;
      this.fraudIDNotPicture = theCase.Fraud_ID_Not_Picture__c;
      this.fraudCustomerPhotoModified = theCase.Fraud_Customer_Photo_Modified__c;
      this.fraudSecurityFeatures = theCase.Fraud_Security_Features__c;
      this.fraudDefectsRectified = theCase.Fraud_Defects_Rectified__c;
      this.suppliedEmail = theCase.SuppliedEmail;
      this.recordType = RECORD_TYPE_AUTOKYC_QA;
    }
  }

  /**
   * @description Inner Wrapper Class for the CustomerOnboardingApplication of KYC QA Case
   */
  public class CustomerOnboardingApplicationModel {
    public String personaId { get; set; }

    /**
     * @description get an instance of CustomerOnboardingApplicationModel
     * @param theCOB the CustomerOnboardingApplication record
     */
    public CustomerOnboardingApplicationModel(
      CustomerOnboardingApplication__c theCOB
    ) {
      this.personaId = theCOB?.PersonaId__c;
    }
  }
}