force-app/main/default/objects/Case/fields/Dispute_Reason__c.field-meta.xml
<CustomField>
    <fullName>Dispute_Reason__c</fullName>
    <complianceGroup>Source_Salesforce;Integrity_Trusted;Privacy_Non_Personal_Information</complianceGroup>
    <description>To select dispute reason related to the ATM transaction</description>
    <inlineHelpText>Please select dispute reason</inlineHelpText>
    <label>Dispute Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amount not received by payee</fullName>
            </value>
            <value>
                <fullName>Cancellation of regular payment arrangement was unsuccessful</fullName>
            </value>
            <value>
                <fullName>Duplicate Transaction</fullName>
            </value>
            <value>
                <fullName>Unauthorised Transaction</fullName>
            </value>
            <value>
                <fullName>Trace Request</fullName>
            </value>
            <value>
                <fullName>Cash Dispensing Error</fullName>
            </value>
            <value>
                <fullName>Urgent Dishonour Request</fullName>
            </value>
            <value>
                <fullName>Don&apos;t recognise the transaction</fullName>
            </value>
            <value>
                <fullName>Didn&apos;t authorise transaction</fullName>
            </value>
            <value>
                <fullName>Duplicate Transactions</fullName>
            </value>
            <value>
                <fullName>Charged more than once</fullName>
            </value>
            <value>
                <fullName>Charged Incorrect Amount</fullName>
            </value>
            <value>
                <fullName>Charged for a cancelled payment</fullName>
            </value>
            <value>
                <fullName>Refund error</fullName>
            </value>
            <value>
                <fullName>Product Didn&apos;t Arrive</fullName>
            </value>
            <value>
                <fullName>Product Defective or Unsatisfactory</fullName>
            </value>
            <value>
                <fullName>Incorrect BSB/ Account number</fullName>
            </value>
            <value>
                <fullName>Incorrect Amount</fullName>
            </value>
            <value>
                <fullName>Payee has not received funds</fullName>
            </value>
            <value>
                <fullName>Fraudulent transaction</fullName>
            </value>
            <value>
                <fullName>Payment debited after debit authority cancelled</fullName>
            </value>
            <value>
                <fullName>Payment Duplicated</fullName>
            </value>
            <value>
                <fullName>Payment Overdrawn</fullName>
            </value>
            <value>
                <fullName>Unsolicited</fullName>
            </value>
            <value>
                <fullName>Incorrect Account Details</fullName>
            </value>
            <value>
                <fullName>Incorrect Amount Transferred</fullName>
            </value>
            <value>
                <fullName>Confirm Payee Name (Only for Salesforce)</fullName>
            </value>
            <value>
                <fullName>Return money received from an unknown person</fullName>
            </value>
            <value>
                <fullName>Claim not for value</fullName>
            </value>
            <value>
                <fullName>Incorrect Biller Code</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PegaExternalCaseStatuses__mdt/PegaExternalCaseStatuses__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata created to identify Pega External Case Statuses</description>
    <label>Pega External Case Statuses</label>
    <pluralLabel>Pega External Case Statuses</pluralLabel>
</CustomObject>

force-app/main/default/objects/PegaExternalCaseStatuses__mdt/fields/DisputeReason__c.field-meta.xml
<CustomField>
    <fullName>DisputeReason__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Required dispute reason(s) in salesforce</description>
    <label>Dispute Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PegaExternalCaseStatuses__mdt/fields/DisputeStatus__c.field-meta.xml
<CustomField>
    <fullName>DisputeStatus__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Required dispute case status in salesforce</description>
    <label>Dispute Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>To be Worked</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Review Required</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PegaExternalCaseStatuses__mdt/fields/ExternalStatus__c.field-meta.xml
<CustomField>
    <fullName>ExternalStatus__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>External Status of dispute in external system</description>
    <label>External Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open-InitiateGoodFaithOutbound</fullName>
            </value>
            <value>
                <fullName>Open-InitiatePreArbOutbound</fullName>
            </value>
            <value>
                <fullName>Open-InitiatePreCompOutbound</fullName>
            </value>
            <value>
                <fullName>Open-PreArbOutboundResponse</fullName>
            </value>
            <value>
                <fullName>Open-PreCompOutboundResponse</fullName>
            </value>
            <value>
                <fullName>Open-ProcessLiability</fullName>
            </value>
            <value>
                <fullName>Open-RecalledDispute</fullName>
            </value>
            <value>
                <fullName>Open-RecalledPrearbitration</fullName>
            </value>
            <value>
                <fullName>Open-ReviewArbitration</fullName>
            </value>
            <value>
                <fullName>Open-ReviewAssociatedTransaction</fullName>
            </value>
            <value>
                <fullName>Open-ReviewDisputeResponse</fullName>
            </value>
            <value>
                <fullName>Open-ReviewInboundPreComp</fullName>
            </value>
            <value>
                <fullName>Open-ReviewPreArbInbound</fullName>
            </value>
            <value>
                <fullName>Open-ReviewValidations</fullName>
            </value>
            <value>
                <fullName>Pending-AdjustAccountEntry</fullName>
            </value>
            <value>
                <fullName>Pending-AdjustCHAccount</fullName>
            </value>
            <value>
                <fullName>Pending-AncillaryQuestions</fullName>
            </value>
            <value>
                <fullName>Pending-ArbitrationInboundRuling</fullName>
            </value>
            <value>
                <fullName>Pending-ArbOutboundRuling</fullName>
            </value>
            <value>
                <fullName>Pending-AssessCHLiable</fullName>
            </value>
            <value>
                <fullName>Pending-AssessDuplicateAuth</fullName>
            </value>
            <value>
                <fullName>Pending-AssessEFT</fullName>
            </value>
            <value>
                <fullName>Pending-AssessFraud</fullName>
            </value>
            <value>
                <fullName>Pending-AssessFraudCount</fullName>
            </value>
            <value>
                <fullName>Pending-AssistIdentification</fullName>
            </value>
            <value>
                <fullName>Pending-AwaitingDocuments</fullName>
            </value>
            <value>
                <fullName>Pending-CardholderLiable</fullName>
            </value>
            <value>
                <fullName>Pending-ChargebackDocUpload</fullName>
            </value>
            <value>
                <fullName>Pending-CheckBlockedCard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PegaExternalCaseStatuses__mdt/fields/QueueName__c.field-meta.xml
<CustomField>
    <fullName>QueueName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Queue to be assigned to in salesforce</description>
    <label>Queue Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TobeWorkedFraudDisputes</fullName>
            </value>
            <value>
                <fullName>TobeWorkedSchemeDisputes</fullName>
            </value>
            <value>
                <fullName>CardDisputesAwaitingContact</fullName>
            </value>
            <value>
                <fullName>ReviewRequiredDisputes</fullName>
            </value>
            <value>
                <fullName>TechnicalErrorDisputes</fullName>
            </value>
            <value>
                <fullName>UnderInvestigationPendingDisputes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PegaExternalCaseStatuses__mdt/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Record Type of the dispute</description>
    <label>Record Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Card_Dispute</fullName>
                <default>true</default>
                <label>Card_Dispute</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PegaExternalCaseStatuses__mdt/fields/SLADaysInStatus__c.field-meta.xml
<CustomField>
    <fullName>SLADaysInStatus__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Number of SLA Days in Status</description>
    <label>SLA Days In Status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PegaExternalCaseStatuses__mdt/fields/SLAQueueName__c.field-meta.xml
<CustomField>
    <fullName>SLAQueueName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Queue to be assigned to in salesforce for SLA</description>
    <label>SLA Queue Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TobeWorkedFraudDisputes</fullName>
            </value>
            <value>
                <fullName>TobeWorkedSchemeDisputes</fullName>
            </value>
            <value>
                <fullName>CardDisputesAwaitingContact</fullName>
            </value>
            <value>
                <fullName>ReviewRequiredDisputes</fullName>
            </value>
            <value>
                <fullName>TechnicalErrorDisputes</fullName>
            </value>
            <value>
                <fullName>UnderInvestigationPendingDisputes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DisputeExternalCaseStatusRepository.cls
/**
 * @author Tan Phan
 * @since 05/2024
 * @description This class provides SOQL and DML helpers for classes related DisputeExternalCaseStatus.
 * @runTests DisputeExternalCaseStatusActionsTest
 */
public with sharing class DisputeExternalCaseStatusRepository {
  /**
   * @description Retrieves custom metadata PegaExternalCaseStatuses__mdt records.
   * @return A list of PegaExternalCaseStatuses__mdt records
   */
  public List<PegaExternalCaseStatuses__mdt> queryMappings() {
    if (!Schema.SObjectType.PegaExternalCaseStatuses__mdt.isQueryable()) {
      return new List<PegaExternalCaseStatuses__mdt>();
    }
    return [
      SELECT
        MasterLabel,
        DisputeReason__c,
        DisputeStatus__c,
        ExternalStatus__c,
        QueueName__c,
        RecordType__c,
        SLADaysInStatus__c,
        SLAQueueName__c
      FROM PegaExternalCaseStatuses__mdt
    ];
  }

  /**
   * @description Queries the External_Case_Status__c records based on the provided query and bind map.
   * @param query The SOQL query string.
   * @param bindMap The map of bind variables used in the query.
   * @return A list of External_Case_Status__c records that match the query.
   */
  public List<External_Case_Status__c> queryCaseStatuses(
    String query,
    Map<String, Object> bindMap
  ) {
    return Database.queryWithBinds(query, bindMap, AccessLevel.USER_MODE);
  }

  /**
   * @description Retrieves a list of Case records with their latest External Case Statuses.
   * @param caseIds A set of Case record IDs to query.
   * @return A list of Case records with their latest External Case Statuses.
   */
  public List<Case> queryCasesWithLatestStatus(Set<Id> caseIds) {
    return [
      SELECT
        Id,
        Dispute_Reason__c,
        OwnerId,
        Status,
        RecordType.DeveloperName,
        (
          SELECT External_Status__c, Status_TimeStamp__c
          FROM External_Case_Statuses__r
          ORDER BY Status_TimeStamp__c DESC, Name DESC
          LIMIT 1
        )
      FROM Case
      WHERE Id IN :caseIds
    ];
  }

  /**
   * @description getRelatedCasesByCaseId is to query case Id based on relatedCaseIds
   * @param relatedCaseIds Set of related Case ids to be queried
   * @return A list of Case records
   */
  public List<Case> getRelatedCasesByCaseId(Set<Id> relatedCaseIds) {
    // Check if relatedCaseIds is null or empty
    if (relatedCaseIds == null || relatedCaseIds.isEmpty()) {
      return new List<Case>(); // Return empty list if no IDs are provided
    }

    // Perform the SOQL query to retrieve the related cases
    return [
      SELECT
        Id,
        CaseNumber,
        Dispute_Reason__c,
        RecordTypeId,
        Account.OCV_ID__c,
        Transaction_UUID__c,
        OCV_ID__c,
        LastModifiedDate,
        AccountId,
        Account.Source_System_Name__c,
        Account.Source_System_ID__c,
        Account.PersonEmail,
        Account.PersonMobilePhone,
        Account.FirstName,
        Account.LastName
      FROM Case
      WHERE Id IN :relatedCaseIds
    ];
  }

  /**
   * @description getRelatedUsersByUserId is to query User list based on relatedUserIds
   * @param relatedUserIds Set of related User ids to be queried
   * @return A list of users related to Case records
   */
  public List<User> getRelatedUsersByUserId(Set<Id> relatedUserIds) {
    // Check if relatedCaseIds is not null and not empty
    if (relatedUserIds == null || relatedUserIds.isEmpty()) {
      return new List<User>();
    }

    return [SELECT Id, Email, UserName FROM User WHERE Id IN :relatedUserIds];
  }
}