force-app/main/default/objects/Case/fields/ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>ExpiryDate__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Expiry Date of the Passport / Driving Licence if provided by the Customer.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/LicenceCardNumber__c.field-meta.xml
<CustomField>
    <fullName>LicenceCardNumber__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Licence Card Number Tokenised and stored in Salesforce.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Licence Card Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/LicenceNumber__c.field-meta.xml
<CustomField>
    <fullName>LicenceNumber__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Licence Number Tokenised and stored in Salesforce.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Licence Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PersonaId__c.field-meta.xml
<CustomField>
    <fullName>PersonaId__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>The ForgeRock-minted UUID identifying the persona attempting to onboard</description>
    <externalId>true</externalId>
    <label>Persona Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/COBPrimaryIDDocument__c.object-meta.xml
<CustomObject>
    <description>The details submitted for a primary document (licence or passport), including the original OCR extractions which may have been edited</description>
    <label>COB Primary ID Document</label>
    <nameField>
        <displayFormat>COBPID-{00000000}</displayFormat>
        <label>COB Primary ID Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>COB Primary ID Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/DateOfBirth__c.field-meta.xml
<CustomField>
    <fullName>DateOfBirth__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Temporal</complianceGroup>
    <description>Date of birth as submitted by the user</description>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>ExpiryDate__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>The expiry date as submitted by the user</description>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Temporal</complianceGroup>
    <description>First name as submitted by the user</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/IdDocumentType__c.field-meta.xml
<CustomField>
    <fullName>IdDocumentType__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>The primary form of ID chosen (licence, passport etc)</description>
    <label>Id Document Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Temporal</complianceGroup>
    <description>Last name as submitted by the user</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/LicenceCardNumber__c.field-meta.xml
<CustomField>
    <fullName>LicenceCardNumber__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>The unique card number as submitted by the user (TOKENISED)</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Licence Card Number (Tokenised)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/LicenceCardNumberOCRClient__c.field-meta.xml
<CustomField>
    <fullName>LicenceCardNumberOCRClient__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>OCR values for Licence Card Number</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Licence Card Number OCR Client</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/LicenceCardNumberOCRServer__c.field-meta.xml
<CustomField>
    <fullName>LicenceCardNumberOCRServer__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Sensitive_Personal_Information;Source_Temporal</complianceGroup>
    <description>OCR values for Licence Card Number</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Licence Card Number OCR Server</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/LicenceNumber__c.field-meta.xml
<CustomField>
    <fullName>LicenceNumber__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Sensitive Personal Information;Source - Temporal</complianceGroup>
    <description>Licence number as submitted by the user (TOKENISED)</description>
    <label>Licence Number (Tokenised)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/LicenceNumberOCRClient__c.field-meta.xml
<CustomField>
    <fullName>LicenceNumberOCRClient__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Sensitive_Personal_Information;Source_Temporal</complianceGroup>
    <description>OCR values for Licence Number</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Licence Number OCR Client</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/LicenceNumberOCRServer__c.field-meta.xml
<CustomField>
    <fullName>LicenceNumberOCRServer__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>OCR values for Licence Number</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Licence Number OCR Server</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/MiddleNames__c.field-meta.xml
<CustomField>
    <fullName>MiddleNames__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Temporal</complianceGroup>
    <description>Middle name(s) or initial as submitted by the user</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Middle Names</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/StateOfIssue__c.field-meta.xml
<CustomField>
    <fullName>StateOfIssue__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>The state where the licence was issued, as submitted by the user</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>State of Issue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBTaxResidency__c/COBTaxResidency__c.object-meta.xml
<CustomObject>
    <description>The details of a single tax residency in a country/region</description>
    <label>COB Tax Residency</label>
    <nameField>
        <displayFormat>COBTR-{00000000}</displayFormat>
        <label>COB Tax Residency Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>COB Tax Residencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/COBTaxResidency__c/fields/TaxIdentificationNumber__c.field-meta.xml
<CustomField>
    <fullName>TaxIdentificationNumber__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Sensitive_Personal_Information;Source_Temporal</complianceGroup>
    <description>Tax identification number (TIN), i.e. an Australian TFN or international equivalent (TOKENISED)</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Tax Identification Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/services/StravinskyServiceTest.cls
/**
 * @author Paul Boyington
 * @since May 2022
 * @description Test class for {@link StravinskyService}
 * @group Services
 */
@isTest
public inherited sharing class StravinskyServiceTest {
  private static final String SUCCESS_CLOSE_PACKAGE_RESPONSE =
    '{' +
    '   \"accountsClosed\": "1"' +
    '   \"cardsClosed\": "0"' +
    '   \"packagesClosed\": "0"' +
    '   \"errorInfo\": "null" ' +
    '}';

  private static final String FAILURE_CLOSE_PACKAGE_RESPONSE =
    '{' +
    '   \"accountsClosed\": "1"' +
    '   \"cardsClosed\": "0"' +
    '   \"packagesClosed\": "0"' +
    '  \"errorInfo\": { \"errorCode\": 500, \"reason\": \"some reason here\" },' +
    '}';

  private static final String TEMPORAL_CASE_WORKFLOW_TRIGGER_RESPONSE_SUCCESS = '{}';

  private static final String TEMPORAL_CASE_WORKFLOW_TRIGGER_RESPONSE_FAILURE =
    '{' +
    '   \"code\": 100,' +
    '   \"message\": \"WorkflowId is not set on request.\"' +
    '}';

  private static final String ACCOUNT_CLOSURE_DETAILS =
    '{' +
    '   \"ocv_ids\": [103245756],' +
    '   \"items\":[' +
    '{\"account_resource\":"accounts/111111111",' +
    '{\"account_resource\":"accounts/000000000",' +
    '{\"package_resource\":"jfhfhjfjhfjhf",' +
    ']' +
    '}';

  @isTest
  static void getRealService() {
    Test.startTest();
    Service stravinskyService = (Service) ServiceProvider.getService(
      StravinskyService.class
    );
    Test.stopTest();
    System.assert(
      stravinskyService instanceof StravinskyServiceMock,
      'Service should be instance of StravinskyServiceMock.'
    );
  }

  @isTest
  static void testClosePackageSuccess() {
    Faker faker = new Faker('AU');
    String ocvId = faker.randomString(10);

    Test.setMock(HttpCalloutMock.class, new MockClosePackageSuccess());
    //load forge staff token
    Cache.Session.put(
      AuthTokenCacheUtil.STAFFPART + 'forgeJWTToken' + ocvId,
      AuthServiceTest.IDTESTVALUE
    );

    Test.startTest();
    StravinskyService stravinskyService = new StravinskyService();
    HttpCalloutResponse response = stravinskyService.closePackage(
      ocvId,
      ACCOUNT_CLOSURE_DETAILS
    );
    Test.stopTest();

    System.assertNotEquals(
      null,
      response.body,
      'Response body should not be null.'
    );
  }

  @isTest
  static void testClosePackageWithFailure() {
    Faker faker = new Faker('AU');

    String ocvId = faker.randomString(10);

    //load forge staff token
    Cache.Session.put(
      AuthTokenCacheUtil.STAFFPART + 'forgeJWTToken' + ocvId,
      AuthServiceTest.IDTESTVALUE
    );
    Test.setMock(HttpCalloutMock.class, new MockClosePackageFailure());

    Test.startTest();
    StravinskyService stravinskyService = new StravinskyService();
    HttpCalloutResponse response = stravinskyService.closePackage(
      ocvId,
      ACCOUNT_CLOSURE_DETAILS
    );
    Test.stopTest();

    System.assertEquals(null, response.body, 'Response body should be null.');
  }

  @isTest
  static void testTriggerTemporalCaseWorkflowSuccess() {
    Faker faker = new Faker('AU');
    Case newCase = new Case(
      Id = Lib_FakeIdGenerator.getMockId(Case.getSObjectType()),
      RecordTypeId = GetHelpConstants.ID_OPS_ASSISTANCE_RT_ID,
      PersonaId__c = faker.randomString(15),
      Status = GetHelpConstants.COB_ID_OPS_DAON_APPROVED_STATUS
    );

    //load forge staff token
    Cache.Session.put(
      AuthTokenCacheUtil.STAFFPART + 'forgeJWTToken' + newCase.PersonaId__c,
      AuthServiceTest.IDTESTVALUE
    );

    Test.setMock(HttpCalloutMock.class, new MockTemporalCaseWorkflowSuccess());

    Test.startTest();
    StravinskyService temporalCaseWorkflowAPI = new StravinskyService();
    HttpCalloutResponse response = temporalCaseWorkflowAPI.triggerTemporalCaseWorkflow(
      newCase
    );

    Test.stopTest();

    Assert.areEqual(200, response.statusCode, 'Status code should be 200.');
  }

  @isTest
  static void testTriggerTemporalCaseWorkflowFailure() {
    Faker faker = new Faker('AU');
    Case newCase = new Case(
      Id = Lib_FakeIdGenerator.getMockId(Case.getSObjectType()),
      RecordTypeId = GetHelpConstants.ID_OPS_ASSISTANCE_RT_ID,
      PersonaId__c = faker.randomString(15),
      Status = GetHelpConstants.COB_ID_OPS_DAON_APPROVED_STATUS
    );

    //load forge staff token
    Cache.Session.put(
      AuthTokenCacheUtil.STAFFPART + 'forgeJWTToken' + newCase.PersonaId__c,
      AuthServiceTest.IDTESTVALUE
    );

    Test.setMock(HttpCalloutMock.class, new MockTemporalCaseWorkflowFailure());

    Test.startTest();
    StravinskyService temporalCaseWorkflowAPI = new StravinskyService();
    HttpCalloutResponse response = temporalCaseWorkflowAPI.triggerTemporalCaseWorkflow(
      newCase
    );
    Test.stopTest();

    Assert.areEqual(400, response.statusCode, 'Status code should be 400.');
  }

  @isTest
  static void testGetCaseWorkflowPayloadIdOpsDaonApproved() {
    Faker faker = new Faker('AU');
    Id mockId = Lib_FakeIdGenerator.getMockId(Case.getSObjectType());
    Case newCase = new Case(
      Id = mockId,
      RecordTypeId = GetHelpConstants.ID_OPS_ASSISTANCE_RT_ID,
      Status = GetHelpConstants.COB_ID_OPS_DAON_APPROVED_STATUS
    );

    Test.startTest();
    StravinskyService temporalCaseWorkflowAPI = new StravinskyService();
    String payload = temporalCaseWorkflowAPI.getCaseWorkflowPayload(newCase);
    Test.stopTest();

    Assert.isFalse(String.isBlank(payload), 'Payload should not be empty.');
    Assert.areEqual(
      '{\"caseId\":\"' + mockId + '\"}',
      payload,
      'Payload is not correct.'
    );
  }

  @isTest
  static void testGetCaseWorkflowPayloadIdOpsEmpty() {
    Faker faker = new Faker('AU');
    Case newCase = new Case(
      ParentId = Lib_FakeIdGenerator.getMockId(Case.getSObjectType()),
      RecordTypeId = GetHelpConstants.ID_OPS_ASSISTANCE_RT_ID,
      Status = GetHelpConstants.COB_EQUIFAX_PASSED_STATUS
    );

    Test.startTest();
    StravinskyService temporalCaseWorkflowAPI = new StravinskyService();
    String payload = temporalCaseWorkflowAPI.getCaseWorkflowPayload(newCase);
    Test.stopTest();

    Assert.areEqual(
      StravinskyService.EMPTY_BODY,
      payload,
      'Payload should be empty body {}.'
    );
  }

  @isTest
  static void testGetCaseWorkflowPayloadFraudCheckDaonApproved() {
    Faker faker = new Faker('AU');
    Id mockId = Lib_FakeIdGenerator.getMockId(Case.getSObjectType());
    Case newCase = new Case(
      ParentId = mockId,
      RecordTypeId = GetHelpConstants.FRAUD_CHECK_RT_ID,
      Status = GetHelpConstants.COB_FRAUD_CHECK_DAON_APPROVED_STATUS
    );

    Test.startTest();
    StravinskyService temporalCaseWorkflowAPI = new StravinskyService();
    String payload = temporalCaseWorkflowAPI.getCaseWorkflowPayload(newCase);
    Test.stopTest();

    Assert.isFalse(String.isBlank(payload), 'Payload should not be empty.');
    Assert.areEqual(
      '{\"caseId\":\"' + mockId + '\"}',
      payload,
      'Payload is not correct.'
    );
  }

  @isTest
  static void testGetCaseWorkflowPayloadFraudCheckEmpty() {
    Faker faker = new Faker('AU');
    Case newCase = new Case(
      ParentId = Lib_FakeIdGenerator.getMockId(Case.getSObjectType()),
      RecordTypeId = GetHelpConstants.FRAUD_CHECK_RT_ID,
      Status = GetHelpConstants.COB_EQUIFAX_PASSED_STATUS
    );

    Test.startTest();
    StravinskyService temporalCaseWorkflowAPI = new StravinskyService();
    String payload = temporalCaseWorkflowAPI.getCaseWorkflowPayload(newCase);
    Test.stopTest();

    Assert.areEqual(
      StravinskyService.EMPTY_BODY,
      payload,
      'Payload should be empty body {}.'
    );
  }

  @isTest
  static void testGetCaseWorkflowPayloadIdOpsWatchlistConfirmedFraud() {
    Faker faker = new Faker('AU');
    Id mockId = Lib_FakeIdGenerator.getMockId(Case.getSObjectType());
    Case newCase = new Case(
      Id = mockId,
      RecordTypeId = GetHelpConstants.ID_OPS_ASSISTANCE_RT_ID,
      Status = GetHelpConstants.COB_CONFIRMED_FRAUD_STATUS,
      Subject = 'ID Ops Assistance - Daon Fallout: WATCHLIST_HIT'
    );

    Test.startTest();
    StravinskyService temporalCaseWorkflowAPI = new StravinskyService();
    String payload = temporalCaseWorkflowAPI.getCaseWorkflowPayload(newCase);
    Test.stopTest();

    Assert.isFalse(String.isBlank(payload), 'Payload should not be empty.');
    Assert.areEqual(
      '{\"reason\":\"' +
        GetHelpConstants.ONBOARDING_FAILED_REASON_CONFIRMED_FRAUD_WATCHLIST +
        '\"}',
      payload,
      'Payload is not correct.'
    );
  }

  @isTest
  static void testGetCaseWorkflowPayloadFraudCheckConfirmedFraud() {
    Faker faker = new Faker('AU');
    Id mockId = Lib_FakeIdGenerator.getMockId(Case.getSObjectType());
    Case newCase = new Case(
      Id = mockId,
      RecordTypeId = GetHelpConstants.FRAUD_CHECK_RT_ID,
      Status = GetHelpConstants.COB_CONFIRMED_FRAUD_STATUS
    );

    Test.startTest();
    StravinskyService temporalCaseWorkflowAPI = new StravinskyService();
    String payload = temporalCaseWorkflowAPI.getCaseWorkflowPayload(newCase);
    Test.stopTest();

    Assert.isFalse(String.isBlank(payload), 'Payload should not be empty.');
    Assert.areEqual(
      '{\"reason\":\"' + GetHelpConstants.COB_CONFIRMED_FRAUD_STATUS + '\"}',
      payload,
      'Payload is not correct.'
    );
  }

  @isTest
  static void testRetrieveDetokenizedCOBPIDSuccess() {
    Faker faker = new Faker('AU');
    String personaId = faker.randomString(10);

    COBPrimaryIDDocument__c cobPid = new COBPrimaryIDDocument__c(
      PersonaId__c = personaId,
      IdDocumentType__c = 'Licence',
      LicenceNumber__c = '123123',
      LicenceNumberOCRClient__c = '123123',
      LicenceNumberOCRServer__c = '123123',
      LicenceCardNumber__c = '456456',
      LicenceCardNumberOCRClient__c = '456456',
      LicenceCardNumberOCRServer__c = '456456'
    );

    List<COBPrimaryIDDocumentModel.TokenizedValue> tokenizedValues = COBPrimaryIDDocumentModel.buildTokenizedValues(
      cobPid,
      COBPIDViewAndEditController.LICENCE_TOKENIZED_FIELDS
    );

    //load forge staff token
    Cache.Session.put(
      AuthTokenCacheUtil.STAFFPART + 'forgeJWTToken' + personaId,
      AuthServiceTest.IDTESTVALUE
    );

    Test.setMock(
      HttpCalloutMock.class,
      new MockRetrieveDetokenizedCOBPIDSuccess()
    );

    Test.startTest();
    StravinskyService stravinskyService = new StravinskyService();
    HttpCalloutResponse response = stravinskyService.detokenizeCOBPID(
      personaId,
      tokenizedValues
    );
    Test.stopTest();

    Assert.areNotEqual(
      null,
      response.body,
      'Response body should not be null.'
    );
  }

  @isTest
  static void testRetrieveDetokenizedCOBPIDFailure() {
    Faker faker = new Faker('AU');
    String personaId = faker.randomString(10);

    COBPrimaryIDDocument__c cobPid = new COBPrimaryIDDocument__c(
      PersonaId__c = personaId,
      IdDocumentType__c = 'Licence',
      LicenceNumber__c = '123123',
      LicenceNumberOCRClient__c = '123123',
      LicenceNumberOCRServer__c = '123123',
      LicenceCardNumber__c = '456456',
      LicenceCardNumberOCRClient__c = '456456',
      LicenceCardNumberOCRServer__c = '456456'
    );

    List<COBPrimaryIDDocumentModel.TokenizedValue> tokenizedValues = COBPrimaryIDDocumentModel.buildTokenizedValues(
      cobPid,
      COBPIDViewAndEditController.LICENCE_TOKENIZED_FIELDS
    );

    //load forge staff token
    Cache.Session.put(
      AuthTokenCacheUtil.STAFFPART + 'forgeJWTToken' + personaId,
      AuthServiceTest.IDTESTVALUE
    );

    Test.setMock(
      HttpCalloutMock.class,
      new MockRetrieveDetokenizedCOBPIDFailure()
    );

    Test.startTest();
    StravinskyService stravinskyService = new StravinskyService();
    HttpCalloutResponse response = stravinskyService.detokenizeCOBPID(
      personaId,
      tokenizedValues
    );
    Test.stopTest();

    Assert.areEqual(401, response.statusCode, 'Status code should be 401.');
  }

  @isTest
  static void testTokenizeCOBPIDSuccess() {
    Faker faker = new Faker('AU');
    String personaId = faker.randomString(10);

    COBPrimaryIDDocument__c cobPid = new COBPrimaryIDDocument__c(
      PersonaId__c = '000000000',
      IdDocumentType__c = 'Licence',
      FirstName__c = 'firstName',
      MiddleNames__c = 'middle names',
      LastName__c = 'lastName',
      DateOfBirth__c = Date.today(),
      LicenceNumber__c = '123123',
      LicenceNumberOCRClient__c = '123123',
      LicenceNumberOCRServer__c = '123123',
      LicenceCardNumber__c = '456456',
      LicenceCardNumberOCRClient__c = '456456',
      LicenceCardNumberOCRServer__c = '456456',
      ExpiryDate__c = Date.today(),
      StateOfIssue__c = 'AU'
    );

    COBPrimaryIDDocumentModel requestBody = COBPrimaryIDDocumentModel.buildUpdateRequestBody(
      cobPid
    );

    //load forge staff token
    Cache.Session.put(
      AuthTokenCacheUtil.STAFFPART + 'forgeJWTToken' + personaId,
      AuthServiceTest.IDTESTVALUE
    );

    Test.setMock(HttpCalloutMock.class, new MockTokenizeCOBPIDSuccess());

    Test.startTest();
    StravinskyService stravinskyService = new StravinskyService();
    HttpCalloutResponse response = stravinskyService.tokenizeCOBPID(
      personaId,
      requestBody
    );
    Test.stopTest();

    Assert.areNotEqual(
      null,
      response.body,
      'Response body should not be null.'
    );
  }

  @isTest
  static void testTokenizeCOBPIDFailure() {
    Faker faker = new Faker('AU');
    String personaId = faker.randomString(10);

    COBPrimaryIDDocument__c cobPid = new COBPrimaryIDDocument__c(
      PersonaId__c = '000000000',
      IdDocumentType__c = 'Licence',
      FirstName__c = 'firstName',
      MiddleNames__c = 'middle names',
      LastName__c = 'lastName',
      DateOfBirth__c = Date.today(),
      LicenceNumber__c = '123123',
      LicenceNumberOCRClient__c = '123123',
      LicenceNumberOCRServer__c = '123123',
      LicenceCardNumber__c = '456456',
      LicenceCardNumberOCRClient__c = '456456',
      LicenceCardNumberOCRServer__c = '456456',
      ExpiryDate__c = Date.today(),
      StateOfIssue__c = 'AU'
    );

    COBPrimaryIDDocumentModel requestBody = COBPrimaryIDDocumentModel.buildUpdateRequestBody(
      cobPid
    );

    //load forge staff token
    Cache.Session.put(
      AuthTokenCacheUtil.STAFFPART + 'forgeJWTToken' + personaId,
      AuthServiceTest.IDTESTVALUE
    );

    Test.setMock(HttpCalloutMock.class, new MockTokenizeCOBPIDFailure());

    Test.startTest();
    StravinskyService stravinskyService = new StravinskyService();
    HttpCalloutResponse response = stravinskyService.tokenizeCOBPID(
      personaId,
      requestBody
    );
    Test.stopTest();

    Assert.areEqual(401, response.statusCode, 'Status code should be 401.');
  }

  @isTest
  static void testRetrieveDetokenizedCOBTaxResidencySuccess() {
    Faker faker = new Faker('AU');
    String personaId = faker.randomString(10);

    COBTaxResidency__c taxResidency = new COBTaxResidency__c(
      PersonaId__c = personaId,
      TaxIdentificationNumber__c = '123456789'
    );

    //load forge staff token
    Cache.Session.put(
      AuthTokenCacheUtil.STAFFPART + 'forgeJWTToken' + personaId,
      AuthServiceTest.IDTESTVALUE
    );

    Test.setMock(
      HttpCalloutMock.class,
      new MockRetrieveDetokenizedCOBTaxResidencySuccess()
    );

    Test.startTest();
    StravinskyService stravinskyService = new StravinskyService();
    HttpCalloutResponse response = stravinskyService.detokenizeCOBTaxResidency(
      taxResidency
    );
    Test.stopTest();

    Assert.areNotEqual(
      null,
      response.body,
      'Response body should not be null.'
    );

    Assert.areEqual(
      StravinskyServiceMock.DETOKENIZED_COB_TAX_RESIDENCY_SUCCESS_RESPONSE,
      response.body,
      'Response is not correct.'
    );
  }

  @isTest
  static void testRetrieveDetokenizedCOBTaxResidencyFailure() {
    Faker faker = new Faker('AU');
    String personaId = faker.randomString(10);

    COBTaxResidency__c taxResidency = new COBTaxResidency__c(
      PersonaId__c = personaId,
      TaxIdentificationNumber__c = '123456789'
    );

    //load forge staff token
    Cache.Session.put(
      AuthTokenCacheUtil.STAFFPART + 'forgeJWTToken' + personaId,
      AuthServiceTest.IDTESTVALUE
    );

    Test.setMock(
      HttpCalloutMock.class,
      new MockRetrieveDetokenizedCOBTaxResidencyFailure()
    );

    Test.startTest();
    StravinskyService stravinskyService = new StravinskyService();
    HttpCalloutResponse response = stravinskyService.detokenizeCOBTaxResidency(
      taxResidency
    );
    Test.stopTest();

    Assert.areEqual(401, response.statusCode, 'Status code should be 401.');
  }

  @isTest
  static void testGetDetokenizePayload() {
    COBTaxResidency__c taxResidency = new COBTaxResidency__c(
      TaxIdentificationNumber__c = '123456789'
    );

    StravinskyService stravinskyService = new StravinskyService();
    String payload = stravinskyService.getDetokenizePayload(taxResidency);

    Assert.isFalse(String.isBlank(payload), 'Payload should not be empty.');
    Assert.areEqual(
      '{' +
        '\"values\":[' +
        '{' +
        '\"transform\":\"' +
        COBTaxResidencyModel.TIN_TRANSFORM +
        '",' +
        '\"tokenized":\"' +
        taxResidency.TaxIdentificationNumber__c +
        '"}' +
        ']' +
        '}',
      payload,
      'Payload is not correct.'
    );
  }

  class MockClosePackageSuccess implements HttpCalloutMock {
    /**
     * @description mock response for callout
     * @param req incoming request
     * @return HTTPResponse success response
     */
    public HTTPResponse respond(HTTPRequest req) {
      HTTPResponse res = new HTTPResponse();

      res.setStatusCode(200);
      res.setBody(SUCCESS_CLOSE_PACKAGE_RESPONSE);

      res.setHeader('Content-Type', 'application/json');

      return res;
    }
  }

  class MockClosePackageFailure implements HttpCalloutMock {
    /**
     * @description mock response for callout
     * @param req incoming request
     * @return HTTPResponse invalid response
     */
    public HTTPResponse respond(HTTPRequest req) {
      HTTPResponse res = new HTTPResponse();

      res.setStatusCode(500);
      res.setHeader('Content-Type', 'application/json');
      res.setBody(FAILURE_CLOSE_PACKAGE_RESPONSE);

      return res;
    }
  }

  class MockTemporalCaseWorkflowSuccess implements HttpCalloutMock {
    /**
     * @description mock response for callout
     * @param req incoming request
     * @return HTTPResponse success response
     */
    public HTTPResponse respond(HTTPRequest req) {
      HTTPResponse res = new HTTPResponse();

      res.setStatusCode(200);
      res.setBody(TEMPORAL_CASE_WORKFLOW_TRIGGER_RESPONSE_SUCCESS);

      res.setHeader('Content-Type', 'application/json');

      return res;
    }
  }

  class MockTemporalCaseWorkflowFailure implements HttpCalloutMock {
    /**
     * @description mock response for callout
     * @param req incoming request
     * @return HTTPResponse invalid response
     */
    public HTTPResponse respond(HTTPRequest req) {
      HTTPResponse res = new HTTPResponse();

      res.setStatusCode(400);
      res.setHeader('Content-Type', 'application/json');
      res.setBody(TEMPORAL_CASE_WORKFLOW_TRIGGER_RESPONSE_FAILURE);

      return res;
    }
  }

  class MockRetrieveDetokenizedCOBPIDSuccess implements HttpCalloutMock {
    /**
     * @description mock response for callout
     * @param req incoming request
     * @return HTTPResponse success response
     */
    public HTTPResponse respond(HTTPRequest req) {
      HTTPResponse res = new HTTPResponse();

      res.setStatusCode(200);
      res.setHeader('Content-Type', 'application/json');
      res.setBody(
        StravinskyServiceMock.SUCCESS_RETRIEVE_DETOKENIZED_COBPID_RESPONSE
      );

      return res;
    }
  }

  class MockRetrieveDetokenizedCOBPIDFailure implements HttpCalloutMock {
    /**
     * @description mock response for callout
     * @param req incoming request
     * @return HTTPResponse invalid response
     */
    public HTTPResponse respond(HTTPRequest req) {
      HTTPResponse res = new HTTPResponse();

      res.setStatusCode(401);
      res.setHeader('Content-Type', 'application/json');
      res.setBody(
        StravinskyServiceMock.FAILURE_RETRIEVE_DETOKENIZED_COBPID_RESPONSE
      );

      return res;
    }
  }

  class MockTokenizeCOBPIDSuccess implements HttpCalloutMock {
    /**
     * @description mock response for callout
     * @param req incoming request
     * @return HTTPResponse success response
     */
    public HTTPResponse respond(HTTPRequest req) {
      HTTPResponse res = new HTTPResponse();

      res.setStatusCode(200);
      res.setHeader('Content-Type', 'application/json');
      res.setBody(StravinskyServiceMock.SUCCESS_TOKENIZING_COBPID_RESPONSE);

      return res;
    }
  }

  class MockTokenizeCOBPIDFailure implements HttpCalloutMock {
    /**
     * @description mock response for callout
     * @param req incoming request
     * @return HTTPResponse invalid response
     */
    public HTTPResponse respond(HTTPRequest req) {
      HTTPResponse res = new HTTPResponse();

      res.setStatusCode(401);
      res.setHeader('Content-Type', 'application/json');
      res.setBody(StravinskyServiceMock.FAILURE_TOKENIZING_COBPID_RESPONSE);

      return res;
    }
  }

  class MockRetrieveDetokenizedCOBTaxResidencySuccess implements HttpCalloutMock {
    /**
     * @description mock response for callout
     * @param req incoming request
     * @return HTTPResponse success response
     */
    public HTTPResponse respond(HTTPRequest req) {
      HTTPResponse res = new HTTPResponse();

      res.setStatusCode(200);
      res.setHeader('Content-Type', 'application/json');
      res.setBody(
        StravinskyServiceMock.DETOKENIZED_COB_TAX_RESIDENCY_SUCCESS_RESPONSE
      );

      return res;
    }
  }

  class MockRetrieveDetokenizedCOBTaxResidencyFailure implements HttpCalloutMock {
    /**
     * @description mock response for callout
     * @param req incoming request
     * @return HTTPResponse invalid response
     */
    public HTTPResponse respond(HTTPRequest req) {
      HTTPResponse res = new HTTPResponse();

      res.setStatusCode(401);
      res.setHeader('Content-Type', 'application/json');
      res.setBody(
        StravinskyServiceMock.DETOKENIZED_COB_TAX_RESIDENCY_FAILURE_RESPONSE
      );

      return res;
    }
  }
}