force-app/main/default/objects/Case/fields/FinServ__FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccount__c</fullName>
    <complianceGroup>Integrity - Accurate</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/KYC_QA.recordType-meta.xml
<RecordType>
    <fullName>KYC_QA</fullName>
    <active>true</active>
    <businessProcess>KYC QA Support Process</businessProcess>
    <description>Record a new KYC QA case for an existing ANZx customer</description>
    <label>KYC QA</label>
</RecordType>

force-app/main/default/objects/Customer_Profile_Updates__c/Customer_Profile_Updates__c.object-meta.xml
<CustomObject>
    <description>This custom object is a staging object which will store the changes made by the bankers on Account and all Contact Point objects.</description>
    <label>Pending Updates to Customer Details</label>
    <nameField>
        <label>Customer Profile Updates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pending Updates to Customer Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Action of the Update.</description>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Add</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Case</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pending Updates to Customer Details</relationshipLabel>
    <relationshipName>Customer_Profile_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will be a lookup on Customer&apos;s Profile (Accounts).</description>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pending Updates to Customer Details</relationshipLabel>
    <relationshipName>Customer_Profile_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/NewValue__c.field-meta.xml
<CustomField>
    <fullName>NewValue__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Personal Information;Source - Salesforce</complianceGroup>
    <description>JSON formatted body structure of New values.</description>
    <label>New Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>To identify object where this update is happening. Eg Account, Contact, ContactPointXXXX.</description>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/ToBeValue__c.field-meta.xml
<CustomField>
    <fullName>ToBeValue__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Personal Information;Source - Salesforce</complianceGroup>
    <description>JSON formatted body structure of New values.This is a back end field which will be used in the payloads pushed by the platform event subscribed by Mulesoft</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>ToBeValue</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/TriggeredFrom__c.field-meta.xml
<CustomField>
    <fullName>TriggeredFrom__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>To identify object where this update is happening.Eg Account, Contact, ContactPointXXXX. This is a back end field which will be used in the payloads pushed by the platform event subscribed by Mulesoft</description>
    <encryptionScheme>None</encryptionScheme>
    <label>TriggeredFrom</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__FinancialAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccountNumber__c</fullName>
    <complianceGroup>Source_CTM;Integrity_Trusted</complianceGroup>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Account Master Product type received from OCV at financial account level</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Product Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/FinServ__FinancialAccountRole__c.object-meta.xml
<CustomObject>
    <description>Represents the role occupied by a person or organizational entity that is involved with a financial account, such as a beneficiary or trustee.</description>
    <label>Financial Account Role</label>
    <nameField>
        <displayFormat>FAR-{000000000}</displayFormat>
        <label>Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy - Personal Information</complianceGroup>
    <description>Financial account that this role is related to.</description>
    <label>Financial Account</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelatedAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the organizational entity that is involved with the financial account.</description>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AutoKYCQARestraintHandler.cls
/**
 * @author Tan Phan
 * @since 06/2024
 * @description This class represents the profile staging handler for the AutoKYCQA restraint event.
 */
public with sharing class AutoKYCQARestraintHandler {
  private static final String RESTRAINTS_EXPIRYDATE = '9999-12-31';
  private static final AutoKYCQACaseRepository REPOSITORY = (AutoKYCQACaseRepository) Lib_InstanceProvider.forType(
    AutoKYCQACaseRepository.class
  );
  private static final ProfileStagingHandler HANDLER = (ProfileStagingHandler) Lib_InstanceProvider.forType(
    ProfileStagingHandler.class
  );

  /**
   * @description Processes the records for AutoKYCQA restraint.
   * @param records The list of Account records.
   * @param mapAccIdToCase The map of Account Id to Case.
   */
  public void process(List<Account> records, Map<Id, Case> mapAccIdToCase) {
    if (REPOSITORY.isRestraintEnabled() == false) {
      return;
    }
    List<Customer_Profile_Updates__c> updates = this.generateUpdates(
      records,
      mapAccIdToCase
    );
    HANDLER.process(updates);
  }

  @TestVisible
  private List<Customer_Profile_Updates__c> generateUpdates(
    List<Account> records,
    Map<Id, Case> mapAccIdToCase
  ) {
    List<Customer_Profile_Updates__c> updates = new List<Customer_Profile_Updates__c>();
    for (Account acc : records) {
      for (
        FinServ__FinancialAccountRole__c far : acc.FinServ__FinancialAccountRoles__r
      ) {
        FinServ__FinancialAccount__c fa = far.FinServ__FinancialAccount__r;
        Case kycCase = mapAccIdToCase.get(acc.Id);
        updates.add(this.generateUpdate(fa, kycCase, 60));
        updates.add(this.generateUpdate(fa, kycCase, 61));
      }
    }
    return updates;
  }

  @TestVisible
  private Customer_Profile_Updates__c generateUpdate(
    FinServ__FinancialAccount__c fa,
    Case kycCase,
    Integer type
  ) {
    Customer_Profile_Updates__c cpu = HANDLER.templateCpu;
    cpu.Action__c = 'Update';
    cpu.Object_Name__c = 'Case';
    cpu.Customer_Name__c = kycCase.AccountId;
    cpu.Case__c = kycCase.Id;
    cpu.TriggeredFrom__c = 'Case.KYC_QA.AddRestraints';
    cpu.NewValue__c = 'Apply Restraints Type ' + type + ' of Class Hard Hold';
    cpu.Name = String.format(
      'KYC QA Case {0} Add Type {1} Restraint on {2}',
      new List<String>{
        kycCase.CaseNumber,
        String.valueOf(type),
        fa.FinServ__FinancialAccountNumber__c
      }
    );
    cpu.ToBeValue__c = createRestraintPayload(fa, type);
    return cpu;
  }

  @TestVisible
  private String createRestraintPayload(
    FinServ__FinancialAccount__c fa,
    Integer restraintType
  ) {
    CustomerRestraintModel model = new CustomerRestraintModel();
    model.accountNumber = fa.FinServ__FinancialAccountNumber__c;
    model.productCode = fa.Product_Type__c.split(':')[1];
    model.restraints.restraintClass = 1;
    model.restraints.restraintType = restraintType;
    model.restraints.dateExpires = RESTRAINTS_EXPIRYDATE;
    model.restraints.specialComment1 = getSepcialCommentByIndex(0, 30);
    model.restraints.specialComment2 = getSepcialCommentByIndex(30, 60);
    model.restraints.specialComment3 = getSepcialCommentByIndex(60, 90);
    return JSON.serialize(model, true);
  }
  @TestVisible
  private string getSepcialCommentByIndex(
    Integer startIndex,
    Integer endIndex
  ) {
    String comment = Label.CustomerRestraintComment;
    if (startIndex < 0 || endIndex < 0 || startIndex > comment.length()) {
      return '';
    }
    if (endIndex > comment.length()) {
      return comment.substring(startIndex, comment.length());
    }
    return comment.substring(startIndex, endIndex);
  }
}