force-app/main/default/objects/Case/fields/Fraud_Total_Fraud_Received__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Total_Fraud_Received__c</fullName>
    <complianceGroup>Source_Salesforce;Integrity - Accurate</complianceGroup>
    <description>Total Fraud Received</description>
    <label>Total Fraud Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_Total_Fraud_Value__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Total_Fraud_Value__c</fullName>
    <complianceGroup>Integrity_Accurate</complianceGroup>
    <label>Total Fraud Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_Total_Recovered__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Total_Recovered__c</fullName>
    <complianceGroup>Integrity_Accurate</complianceGroup>
    <label>Total Recovered</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_Total_Scam_Value__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Total_Scam_Value__c</fullName>
    <complianceGroup>Integrity - Accurate</complianceGroup>
    <description>Total Scam Value</description>
    <label>Total Scam Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Fraud.recordType-meta.xml
<RecordType>
    <fullName>Fraud</fullName>
    <active>true</active>
    <businessProcess>Fraud Support Process</businessProcess>
    <description>Record a new fraud case for an existing ANZx customer</description>
    <label>Fraud</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Scam.recordType-meta.xml
<RecordType>
    <fullName>Scam</fullName>
    <active>true</active>
    <businessProcess>Scam Support Process</businessProcess>
    <description>Record a new scam case for an existing ANZx customer</description>
    <label>Scam</label>
</RecordType>

force-app/main/default/objects/Dispute/fields/TotalRecoveryAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalRecoveryAmount__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Sum Total of Recovery Amount in the DisputeItem records. Recovery Amounts are the recovered  amount entered by the Agent which is actually recovered.</description>
    <label>Total Recovery Amount</label>
    <summarizedField>DisputeItem.RecoveryAmount__c</summarizedField>
    <summaryForeignKey>DisputeItem.DisputeId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Dispute/fields/TotalTransactionAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalTransactionAmount__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Sum Total of Amount in the DisputeItem records. Transaction Amounts are the actual amount for which the transactions are raised.</description>
    <label>Total Transaction Amount</label>
    <summarizedField>DisputeItem.TransactionAmount</summarizedField>
    <summaryFilterItems>
        <field>DisputeItem.RecoveryStatus__c</field>
        <operation>notEqual</operation>
        <value>Pending OFI Response</value>
    </summaryFilterItems>
    <summaryForeignKey>DisputeItem.DisputeId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/DisputeItem/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Cases to show associated linked Transactions to Agents.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Dispute Items</relationshipLabel>
    <relationshipName>Dispute_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DisputeItem/fields/RecoveryAmount__c.field-meta.xml
<CustomField>
    <fullName>RecoveryAmount__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Amount Recovered by the Customer</description>
    <label>Recovery Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/DisputedTransactionActionsTest.cls
/**
 * @author Karen Valeriano
 * @since August 2025
 * @description tests for {@link DisputedTransactionActions}
 */
@isTest
private with sharing class DisputedTransactionActionsTest {
  static Lib_MockProvider repoMock;
  static Lib_MockProvider dmlRepoMock;
  static final Faker FAKER = new Faker('en-AU');
  static Case theCase = new Case(
    Id = Lib_FakeIdGenerator.getMockId(Case.SObjectType)
  );
  static Dispute disputeRec = new Dispute(
    Id = Lib_FakeIdGenerator.getMockId(Dispute.SObjectType),
    RecordTypeId = RTDispute.disputedTransaction,
    ReceivedDate = Date.today(),
    CaseId = theCase.Id
  );
  static DisputeItem disputeItemRec = new DisputeItem(
    Id = Lib_FakeIdGenerator.getMockId(DisputeItem.SObjectType),
    RecordTypeId = RTDisputeItem.disputedTransaction,
    TransactionAmount = FAKER.randomDecimal(3, 2),
    TransactionDate = FAKER.randomPastDate(),
    TransactionIdentifier = FAKER.randomString(10),
    RecoveryAmount__c = FAKER.randomDecimal(2, 2),
    DisputeId = disputeRec.Id,
    Case__c = theCase.Id
  );
  static DisputeItem disputeItemRec2 = new DisputeItem(
    Id = Lib_FakeIdGenerator.getMockId(DisputeItem.SObjectType),
    RecordTypeId = RTDisputeItem.disputedTransaction,
    TransactionAmount = FAKER.randomDecimal(3, 2),
    TransactionDate = FAKER.randomPastDate(),
    TransactionIdentifier = FAKER.randomString(10),
    RecoveryAmount__c = FAKER.randomDecimal(2, 2),
    DisputeId = disputeRec.Id,
    Case__c = theCase.Id
  );

  static void registerMocks() {
    repoMock = Lib_MockProvider.forType(DisputedTransactionRepository.class);
    dmlRepoMock = Lib_MockProvider.forType(DmlRepository.class);
  }

  static Map<String, Object> generateMockResult(Id caseRecordTypeId) {
    return new Map<String, Object>{
      'CaseId' => theCase.Id,
      'RecordTypeId' => caseRecordTypeId,
      'TotalRecoveryAmount__c' => disputeItemRec.RecoveryAmount__c,
      'TotalTransactionAmount__c' => disputeItemRec.TransactionAmount
    };
  }

  static void mockRepos(Map<String, Object> mockResult) {
    repoMock.mock(
      'getRelatedAggregatedDisputes',
      new List<Map<String, Object>>{ mockResult }
    );
    dmlRepoMock.mock(
      'doUpdate',
      new List<Database.SaveResult>{
        TestUtil.getMockSaveResult('{"success":true}')
      }
    );
  }

  static void assertCommonFields(Case caseRec, Map<String, Object> mockResult) {
    Assert.areEqual(
      mockResult.get('TotalRecoveryAmount__c'),
      caseRec.Fraud_Total_Recovered__c,
      'The total recovery amount should be rolled up to the Case'
    );
    Assert.areEqual(
      disputeRec.CaseId,
      caseRec.Id,
      'The Case record associated with the Dispute should be updated'
    );
  }

  @isTest
  static void testCalculateDisputeTotalAmountsRecipientMule() {
    registerMocks();
    Map<String, Object> mockResult = generateMockResult(RTCase.recipientMule);
    mockRepos(mockResult);

    Test.startTest();
    DisputedTransactionActions.calculateDisputeTotalAmounts(
      new List<Dispute>{ disputeRec }
    );
    Test.stopTest();

    List<Case> caseRec = (List<Case>) dmlRepoMock.getHistory('doUpdate')
      .getParam('records');

    Assert.areEqual(
      mockResult.get('TotalTransactionAmount__c'),
      caseRec[0].Fraud_Total_Fraud_Received__c,
      'The total transaction amount should be rolled up to the Case'
    );
    assertCommonFields(caseRec[0], mockResult);
  }

  @isTest
  static void testCalculateDisputeTotalAmountsScam() {
    registerMocks();
    Map<String, Object> mockResult = generateMockResult(RTCase.scam);
    mockRepos(mockResult);

    Test.startTest();
    DisputedTransactionActions.calculateDisputeTotalAmounts(
      new List<Dispute>{ disputeRec }
    );
    Test.stopTest();

    List<Case> caseRec = (List<Case>) dmlRepoMock.getHistory('doUpdate')
      .getParam('records');

    Assert.areEqual(
      mockResult.get('TotalTransactionAmount__c'),
      caseRec[0].Fraud_Total_Scam_Value__c,
      'The total transaction amount should be rolled up to the Case'
    );
    assertCommonFields(caseRec[0], mockResult);
  }

  @isTest
  static void testCalculateDisputeTotalAmountsFraud() {
    registerMocks();
    Map<String, Object> mockResult = generateMockResult(RTCase.fraud);
    mockRepos(mockResult);

    Test.startTest();
    DisputedTransactionActions.calculateDisputeTotalAmounts(
      new List<Dispute>{ disputeRec }
    );
    Test.stopTest();

    List<Case> caseRec = (List<Case>) dmlRepoMock.getHistory('doUpdate')
      .getParam('records');

    Assert.areEqual(
      mockResult.get('TotalTransactionAmount__c'),
      caseRec[0].Fraud_Total_Fraud_Value__c,
      'The total transaction amount should be rolled up to the Case'
    );
    assertCommonFields(caseRec[0], mockResult);
  }

  @isTest
  static void testGetCasesForRollupUpdates() {
    Map<String, Object> mockResult = generateMockResult(RTCase.fraud);

    Test.startTest();
    List<Case> cases = DisputedTransactionActions.getCasesForRollupUpdates(
      new List<Map<String, Object>>{ mockResult }
    );
    Test.stopTest();

    Assert.areEqual(
      mockResult.get('TotalRecoveryAmount__c'),
      cases[0].Fraud_Total_Recovered__c,
      'The total recovery amount should be reflected to the Case'
    );
    Assert.areEqual(
      mockResult.get('TotalTransactionAmount__c'),
      cases[0].Fraud_Total_Fraud_Value__c,
      'The total transaction amount should be reflected to the Case'
    );
  }

  @isTest
  static void testProcessCaseComments() {
    registerMocks();
    repoMock.mock(
      'getDisputedTransactionItems',
      new List<DisputeItem>{ disputeItemRec, disputeItemRec2 }
    );

    Test.startTest();
    DisputedTransactionActions.processCaseComments(
      new List<Dispute>{ disputeRec }
    );
    Test.stopTest();

    Assert.isNotNull(
      dmlRepoMock.getHistory('doInsert'),
      'doInsert should have been invoked'
    );

    List<CaseComment> insertedComments = (List<CaseComment>) dmlRepoMock.getHistory(
        'doInsert'
      )
      .getParam('records');

    List<String> transactionIds = new List<String>{
      disputeItemRec.TransactionIdentifier,
      disputeItemRec2.TransactionIdentifier
    };
    String expectedComment = String.format(
      DisputedTransactionItemActions.CASE_COMMENT,
      new List<String>{ String.join(transactionIds, ', ') }
    );

    Assert.areEqual(
      expectedComment,
      insertedComments[0].CommentBody,
      'The CaseComment should match and contain all the TransactionIdentifiers'
    );
    Assert.areEqual(
      theCase.Id,
      insertedComments[0].ParentId,
      'The CaseComment should be posted to the correct Case record.'
    );
  }
}