force-app/main/default/objects/Case/fields/Fraud_Address_Valid__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Address_Valid__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Check: 

The residential address populated in the customer profile in Fenergo can be reasonably understood to be a place where the person resides</description>
    <inlineHelpText>Check: 

The residential address populated in the customer profile in Fenergo can be reasonably understood to be a place where the person resides</inlineHelpText>
    <label>Residential address is valid</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_Customer_Details__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Customer_Details__c</fullName>
    <complianceGroup>Integrity - Trusted;Source - Salesforce;Privacy - Non Personal Information</complianceGroup>
    <description>Check: 

The following customer information in Fenergo matches the details on the ID Document: 
first &amp; last name; middle name (per framework); date of birth; ID document number, expiry date (if required), and issue state/country</description>
    <inlineHelpText>Check: 

The following customer information in Fenergo matches the details on the ID Document: 
first &amp; last name; middle name (per framework); date of birth; ID document number, expiry date (if required), and issue state/country</inlineHelpText>
    <label>KYC Information is a Match &amp; Complete</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_Customer_Photo_Modified__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Customer_Photo_Modified__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Trusted;Source - Salesforce</complianceGroup>
    <description>Confirm:

Customer&apos;s photograph on the identity document is not superimposed or replaced with another person&apos;s photograph.</description>
    <inlineHelpText>Confirm:

Customer&apos;s photograph on the identity document is not superimposed or replaced with another person&apos;s photograph.</inlineHelpText>
    <label>Customer&apos;s Photo is Not Modified</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_ID_Legible__c.field-meta.xml
<CustomField>
    <fullName>Fraud_ID_Legible__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>The customer&apos;s photograph on the identity document is legible and can be relied upon for selfie comparison.</description>
    <inlineHelpText>The customer&apos;s photograph on the identity document is legible and can be relied upon for selfie comparison.</inlineHelpText>
    <label>Customer Photo on ID Legibility Check</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_ID_Not_Picture__c.field-meta.xml
<CustomField>
    <fullName>Fraud_ID_Not_Picture__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Trusted;Source - Salesforce</complianceGroup>
    <description>Confirm:

The image provided by customer does not look like a image of a picture of an actual identity document.</description>
    <inlineHelpText>Confirm:

The image provided by customer does not look like a image of a picture of an actual identity document.</inlineHelpText>
    <label>Image is not a Picture of ID Document</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_MiddleNameCheck__c.field-meta.xml
<CustomField>
    <fullName>Fraud_MiddleNameCheck__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Check: 

That the middle name present on the document is recorded correctly per the framework</description>
    <inlineHelpText>Check: 

That the middle name present on the document is recorded correctly per the framework</inlineHelpText>
    <label>Middle Name Check</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_Security_Features__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Security_Features__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>The image of the identity document shows holographic features or any other security features under reasonable level of lighting. Note: Judgement needs to be exercised, as holographic features may not appear under low light.</description>
    <inlineHelpText>The image of the identity document shows holographic features or any other security features under reasonable level of lighting. Note: Judgement needs to be exercised, as holographic features may not appear under low light.</inlineHelpText>
    <label>ID Document Security Features Check</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_Selfie_Comparison_Match__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Selfie_Comparison_Match__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Check: 

The person in the selfie image is the same person as photographed on the ID document image.</description>
    <inlineHelpText>Check: 

The person in the selfie image is the same person as photographed on the ID document image.</inlineHelpText>
    <label>Selfie Comparison Match</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/TestedDate__c.field-meta.xml
<CustomField>
    <fullName>TestedDate__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Captures the Data and Time the very first time  all of the KYC QA tests have any values (either yes or no, not blank)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Tested Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/tfm/TrustMeCaseActions.cls
/**
 *
 * @author Shivraj Kadam
 * @since 02/2025
 * @description TrustMeCaseActions class is to handle all the action taken for TrustMe eIDV Cases
 */
public with sharing class TrustMeCaseActions {
  private static final IDOpsQueryRepository REPOSITORY = (IDOpsQueryRepository) Lib_InstanceProvider.forType(
    IDOpsQueryRepository.class
  );
  private static final DmlRepository DML = (DmlRepository) Lib_InstanceProvider.forType(
    DmlRepository.class
  );

  private static final String MSG_ERROR_GENERIC_CHECK_COMPLETION = 'Error performing the checks completion. Please contact your System Administrator.';

  public static final Set<SObjectField> TEST_FIELDS = new Set<SObjectField>{
    Case.Fraud_Customer_Details__c,
    Case.Fraud_MiddleNameCheck__c,
    Case.Fraud_Selfie_Comparison_Match__c,
    Case.Fraud_Address_Valid__c,
    Case.Fraud_ID_Legible__c,
    Case.Fraud_ID_Not_Picture__c,
    Case.Fraud_Customer_Photo_Modified__c,
    Case.Fraud_Security_Features__c
  };
  /**
   * @description Update Tested Date
   * @param cases List of Cases
   */
  public static void updateTestedDate(List<Case> cases) {
    List<Case> validCases = ListUtil.filter(cases)
      .isNull(Case.TestedDate__c)
      .allNotNull(TEST_FIELDS)
      .toList();
    ListUtil.setField(validCases, Case.TestedDate__c, System.now());
  }

  /**
   * @description method invoked in lwc.
   * @param recordId The TrustMe QA Case & ReKYC QA Case records to update.
   */
  @AuraEnabled
  public static void completeChecksAsYes(String recordId) {
    try {
      List<Case> cases = REPOSITORY.queryQAChecksByIds(new Set<Id>{ recordId });

      ListUtil.setFieldIfNull(cases, TEST_FIELDS, 'Yes');
      DML.doUpdate(cases);
    } catch (Exception ex) {
      CommonUtil.logAuraExceptionInfo(
        MSG_ERROR_GENERIC_CHECK_COMPLETION,
        recordId,
        ex
      );
      throw new AuraHandledException(MSG_ERROR_GENERIC_CHECK_COMPLETION);
    }
  }
}