force-app/main/default/objects/Case/fields/IDR_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>IDR_Customer_Number__c</fullName>
    <complianceGroup>Integrity - Trusted</complianceGroup>
    <externalId>true</externalId>
    <inlineHelpText>Also known as Customer CAP CIS ID. Copy and paste this from MAUD</inlineHelpText>
    <label>Customer Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/Quality_Assessment__c.object-meta.xml
<CustomObject>
    <label>Quality Assessment</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Quality Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Assessment__c/fields/Assessment_Outcome_Status__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Outcome_Status__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Assessment Outcome Status</description>
    <label>Assessment Outcome Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Response</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Disputed - C&amp;Q review overturned</fullName>
            </value>
            <value>
                <fullName>Disputed - C&amp;Q review upheld</fullName>
            </value>
            <value>
                <fullName>Disputed - C&amp;Q review final</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>C&amp;Q Manager amended original review</fullName>
            </value>
            <value>
                <fullName>C&amp;Q Manager upheld original review</fullName>
            </value>
            <value>
                <fullName>C&amp;Q Manager&apos;s view not accepted</fullName>
            </value>
            <value>
                <fullName>C&amp;Q Manager&apos;s view accepted</fullName>
            </value>
            <value>
                <fullName>C&amp;Q Lead upholds C&amp;Q Manager&apos;s review</fullName>
            </value>
            <value>
                <fullName>C&amp;Q Lead disagrees with C&amp;Q Manager&apos;s review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Business_score__c.field-meta.xml
<CustomField>
    <fullName>Business_score__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Stores Business  score</description>
    <label>BUSINESS  SCORE (%)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/C_Q_Specialist__c.field-meta.xml
<CustomField>
    <fullName>C_Q_Specialist__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>stores Assessor details</description>
    <label>C&amp;Q Specialist</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quality_Assessments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Case_Manager_Score__c.field-meta.xml
<CustomField>
    <fullName>Case_Manager_Score__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Stores Case manager score</description>
    <label>CASE MANAGER SCORE (%)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Evaluation_Type__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Type__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>What type of  assessment is done</description>
    <label>Evaluation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compliance Only</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Simple</fullName>
                <label>No Advice Interactions</label>
            </value>
            <value>
                <fullName>Complex</fullName>
            </value>
            <value>
                <fullName>Fraud &amp; Dispute</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Dispute</fullName>
            </value>
            <value>
                <fullName>Identity &amp; KYC</fullName>
            </value>
            <value>
                <fullName>Interaction QI</fullName>
            </value>
            <value>
                <fullName>C &amp; Q Assessment</fullName>
                <label>C&amp;Q Assessment</label>
            </value>
            <value>
                <fullName>Call Review Assessment</fullName>
            </value>
            <value>
                <fullName>Letter Review Assessment</fullName>
            </value>
            <value>
                <fullName>Home Loan</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Appointment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Interaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Interaction_Type__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The type of interaction that triggered the quality assessment</description>
    <label>Interaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Evaluation_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Voice Call</fullName>
            </value>
            <value>
                <fullName>Video Call</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The original case being assessed</description>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Quality Assessments</relationshipLabel>
    <relationshipName>Quality_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The different status the QA progresses through</description>
    <inlineHelpText>Status of Quality Evaluation</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
                <default>true</default>
                <label>Unassigned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Team_Manager_Response__c.field-meta.xml
<CustomField>
    <fullName>Team_Manager_Response__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Team Manager Response</description>
    <label>Team Manager Response</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting response from TM</fullName>
            </value>
            <value>
                <fullName>Accepted by TM</fullName>
            </value>
            <value>
                <fullName>Rejected by TM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/recordTypes/C_Q_Assessment.recordType-meta.xml
<RecordType>
    <fullName>C_Q_Assessment</fullName>
    <active>true</active>
    <label>C&amp;Q Assessment</label>
</RecordType>

force-app/main/default/objects/Quality_Assessment__c/recordTypes/Call_Letter_Review_Assessment.recordType-meta.xml
<RecordType>
    <fullName>Call_Letter_Review_Assessment</fullName>
    <active>true</active>
    <label>Call/Letter Review Assessment</label>
</RecordType>

force-app/main/default/classes/QualityAssessmentActionsTest.cls
@IsTest
private class QualityAssessmentActionsTest {
  //method to test negative case (return false) when calling isDisputeCaseType mehtod
  @IsTest
  private static void testIsDisputeCaseTypeNegative() {
    Test.startTest();

    Case caseRecord = new Case(Subject = 'Non Dispute Case');

    Boolean isDisputeCaseType = QualityAssessmentActions.isDisputeCaseType(
      caseRecord
    );

    Test.stopTest();

    System.assert(
      !isDisputeCaseType,
      'Passing non Dispute Case record into isDisputeCaseType method should return false.'
    );
  }

  //method to test positive case (return true) when calling isDisputeCaseType mehtod
  @IsTest
  private static void testIsDisputeCaseTypePositive() {
    Test.startTest();

    Case caseRecord = new Case(
      Subject = 'Dispute Case',
      RecordTypeId = GetHelpConstants.GENERAL_INQUIRY_RT_ID
    );

    Boolean isDisputeCaseType = QualityAssessmentActions.isDisputeCaseType(
      caseRecord
    );

    Test.stopTest();

    System.assert(
      isDisputeCaseType,
      'Passing Dispute Case record into isDisputeCaseType method should return true.'
    );
  }

  //method to test pass empty list param when calling assignRelatedCaseFieldsToQA mehtod
  @IsTest
  private static void testAssignRelatedCaseFieldsToQAWithEmptyListParam() {
    Test.startTest();

    List<Quality_Assessment__c> qaRecords = QualityAssessmentActions.assignRelatedCaseFieldsToQA(
      new List<Quality_Assessment__c>()
    );

    Test.stopTest();

    System.assertEquals(
      new List<Quality_Assessment__c>(),
      qaRecords,
      'Passing empty list into assignRelatedCaseFieldsToQA method should return empty list.'
    );
  }

  //method to test assignRelatedCaseFieldsToQA mehtod
  @IsTest
  private static void testAssignRelatedCaseFieldsToQA() {
    Test.startTest();

    Case caseRecord = new Case(
      Subject = 'Dispute Case',
      RecordTypeId = GetHelpConstants.GENERAL_INQUIRY_RT_ID,
      Origin = 'Chat'
    );

    insert caseRecord;

    Quality_Assessment__c qaRecord = new Quality_Assessment__c(
      RecordTypeId = GetHelpConstants.QUALITY_ASSESSMENT_GENERAL_RT_ID,
      Related_Case__c = caseRecord.Id
    );

    insert qaRecord;

    List<Quality_Assessment__c> updatedQARecords = QualityAssessmentActions.assignRelatedCaseFieldsToQA(
      new List<Quality_Assessment__c>{ qaRecord }
    );

    Test.stopTest();

    System.assertEquals(
      'Chat',
      updatedQARecords[0].Interaction_Type__c,
      'Passing Quality Assessment list into assignRelatedCaseFieldsToQA mehtod should assign correct value to Quality Assessment records in the list.'
    );
  }

  //method to test assignRelatedCaseFieldsToQA method if QA record has a pre-select value, then this value should not be overwritten
  @IsTest
  private static void testAssignRelatedCaseFieldsToQAWhenOriginPreSelected() {
    Test.startTest();

    Case caseRecord = new Case(
      Subject = 'Dispute Case',
      RecordTypeId = GetHelpConstants.GENERAL_INQUIRY_RT_ID,
      Origin = 'Chat'
    );

    insert caseRecord;

    Quality_Assessment__c qaRecord = new Quality_Assessment__c(
      RecordTypeId = GetHelpConstants.QUALITY_ASSESSMENT_GENERAL_RT_ID,
      Related_Case__c = caseRecord.Id,
      Evaluation_Type__c = 'Email',
      Interaction_Type__c = 'Email'
    );

    insert qaRecord;

    List<Quality_Assessment__c> updatedQARecords = QualityAssessmentActions.assignRelatedCaseFieldsToQA(
      new List<Quality_Assessment__c>{ qaRecord }
    );

    Test.stopTest();

    System.assertEquals(
      'Email',
      updatedQARecords[0].Interaction_Type__c,
      'Method assignRelatedCaseFieldsToQA should not overwrite pre-selected value of Quality Assessment record.'
    );
  }

  //method to test pass null param when calling calculateInteractionType mehtod
  @IsTest
  private static void testCalculateInteractionTypeWithNullParam() {
    Test.startTest();

    String interactionType = QualityAssessmentActions.calculateInteractionType(
      null
    );

    Test.stopTest();

    System.assertEquals(
      null,
      interactionType,
      'Passing null into calculateInteractionType method should return null.'
    );
  }

  //method to test calculateInteractionType mehtod - Store as Origin
  @IsTest
  private static void testCalculateInteractionTypeWithStoreOrigin() {
    Test.startTest();

    String interactionType = QualityAssessmentActions.calculateInteractionType(
      'Store'
    );

    Test.stopTest();

    System.assertEquals(
      'Store',
      interactionType,
      'Passing Store into calculateInteractionType method should return Store.'
    );
  }
  //method to test assignUsersDetailsToQaFields
  @IsTest
  private static void testAssignUsersDetailsToQaFields() {
    Case testCase = new Case();
    testCase.Id = Lib_FakeIdGenerator.getMockId(Case.SObjectType);
    testCase.OwnerId = UserInfo.getUserId();
    Map<Id, Case> caseMap = new Map<Id, Case>();
    caseMap.put(testCase.Id, testCase);
    Quality_Assessment__c qa = new Quality_Assessment__c();
    qa.RecordTypeId = IDRConstants.idrtCQQualityAssessment;
    qa.Related_Case__c = testCase.Id;
    qa.OwnerId = UserInfo.getUserId();
    List<Quality_Assessment__c> qaList = new List<Quality_Assessment__c>{ qa };
    QualityAssessmentActions.assignUsersDetailsToQaFields(caseMap, qaList);
    System.assertEquals(
      qa.C_Q_Specialist__c,
      UserInfo.getUserId(),
      'CQ Specialist is the owner of the record'
    );
  }
  //method to test autoCalculateScore
  @IsTest
  private static void testCaseManagerScoreAndBusinessScore() {
    Profile stdUserProfile = QueryProfile.anzUser;
    UserRole cqRole = CommonUtil.getUserRoleByDevName(
      'Capability_Quality_C_Q_Team'
    );

    // Create QA user
    User oQAUser = TestUtil.createTestUser(
      new Map<String, Object>{
        'FirstName' => 'QA_User',
        'ProfileId' => stdUserProfile.Id,
        'UserRoleId' => cqRole.Id
      }
    );
    insert oQAUser;
    // Add IDR User permissions on test users
    PermissionSet ps = CommonUtil.getPermissionSetByName('IDR_User');
    insert TestUtil.createPSAssignment(oQAUser.Id, ps.Id);

    System.runAs(oQAUser) {
      Test.startTest();

      Case caseRecord = new Case(
        RecordTypeId = IDRConstants.CUSTOMER_COMPLAINT_RT_ID,
        IDR_Customer_Number__c = '1234567890',
        Status = 'Closed'
      );

      insert caseRecord;

      Quality_Assessment__c qaRecord = new Quality_Assessment__c(
        RecordTypeId = Schema.SObjectType.Quality_Assessment__c.getRecordTypeInfosByDeveloperName()
          .get('Call_Letter_Review_Assessment')
          .getRecordTypeId(),
        Related_Case__c = caseRecord.Id,
        Evaluation_Type__c = 'Letter Review Assessment',
        Status__c = 'Complete'
      );
      Map<String, FieldSet> mpAssessmentFieldSets = Schema.SObjectType.Quality_Assessment__c.fieldSets.getMap();
      IDRQualityAssessmentTaskActionsTest.fillMandatoryFields(
        qaRecord,
        mpAssessmentFieldSets
      );

      insert qaRecord;

      qaRecord = new Quality_Assessment__c(
        RecordTypeId = Schema.SObjectType.Quality_Assessment__c.getRecordTypeInfosByDeveloperName()
          .get('Call_Letter_Review_Assessment')
          .getRecordTypeId(),
        Related_Case__c = caseRecord.Id,
        Evaluation_Type__c = 'Call Review Assessment',
        Status__c = 'Complete'
      );
      IDRQualityAssessmentTaskActionsTest.fillMandatoryFields(
        qaRecord,
        mpAssessmentFieldSets
      );
      insert qaRecord;

      Test.stopTest();

      qaRecord = [
        SELECT Id, Case_Manager_Score__c, Business_score__c
        FROM Quality_Assessment__c
        WHERE Id = :qaRecord.Id
      ];
      System.Debug('Result++ ' + qaRecord);
      System.assertEquals(
        100,
        qaRecord.Case_Manager_Score__c,
        'Case Manager Score Mismatch'
      );
      System.assertEquals(
        0,
        qaRecord.Business_score__c,
        'Business Score Mismatch'
      );

      Quality_Assessment__c qaRecordCQ = new Quality_Assessment__c(
        RecordTypeId = Schema.SObjectType.Quality_Assessment__c.getRecordTypeInfosByDeveloperName()
          .get('C_Q_Assessment')
          .getRecordTypeId(),
        Related_Case__c = caseRecord.Id,
        Team_Manager_Response__c = 'Accepted by TM',
        Evaluation_Type__c = 'C & Q Assessment',
        Status__c = 'Complete'
      );
      Map<String, FieldSet> mpAssessmentFieldSetsCQ = Schema.SObjectType.Quality_Assessment__c.fieldSets.getMap();
      IDRQualityAssessmentTaskActionsTest.fillMandatoryFields(
        qaRecordCQ,
        mpAssessmentFieldSetsCQ
      );
      try {
        insert qaRecordCQ;
      } catch (Exception e) {
        System.assert(
          true,
          e.getMessage()
            .contains('A Quality Assessment has already been completed')
        );
      }
    }
  }
  @IsTest
  static void testSetAssessmentOutcomeStatusValid() {
    String qaRecordId = Lib_FakeIdGenerator.getMockId(
      Quality_Assessment__c.SObjectType
    );
    Quality_Assessment__c qaRecord = new Quality_Assessment__c(
      Id = qaRecordId,
      Status__c = IDRConstants.STATUS_COMPLETE,
      Team_Manager_Response__c = '',
      RecordTypeId = IDRConstants.idrtCQQualityAssessment
    );
    Quality_Assessment__c qaRecordV1 = new Quality_Assessment__c(
      Id = qaRecordId,
      Status__c = IDRConstants.STATUS_COMPLETE,
      Team_Manager_Response__c = 'Rejected by TM',
      RecordTypeId = IDRConstants.idrtCQQualityAssessment
    );
    IDRQualityAssessmentActions.setAssessmentOutcomeStatus(
      new List<Quality_Assessment__c>{ qaRecordV1 },
      new Map<Id, Quality_Assessment__c>{ qaRecord.Id => qaRecord }
    );
    System.AssertEquals(
      'Disputed',
      qaRecordV1.Assessment_Outcome_Status__c,
      'Assessment Outcome Status updated correctly'
    );
  }

  @IsTest
  static void testSetAssessmentOutcomeStatusInvalid() {
    String qaRecordId = Lib_FakeIdGenerator.getMockId(
      Quality_Assessment__c.SObjectType
    );
    Quality_Assessment__c qaRecord = new Quality_Assessment__c(
      Id = qaRecordId,
      Status__c = IDRConstants.STATUS_PENDING,
      RecordTypeId = IDRConstants.idrtCQQualityAssessment
    );
    Quality_Assessment__c qaRecordV1 = new Quality_Assessment__c(
      Id = qaRecordId,
      Status__c = IDRConstants.STATUS_COMPLETE,
      RecordTypeId = IDRConstants.idrtCQQualityAssessment
    );
    IDRQualityAssessmentActions.setAssessmentOutcomeStatus(
      new List<Quality_Assessment__c>{ qaRecordV1 },
      new Map<Id, Quality_Assessment__c>{ qaRecord.Id => qaRecord }
    );
    System.AssertNotEquals(
      'Accepted',
      qaRecordV1.Assessment_Outcome_Status__c,
      'Assessment Outcome Status should not be updated when Outcome fields are not changed'
    );
  }
}