force-app/main/default/objects/Case/fields/IDR_Complaint_Outcome__c.field-meta.xml
<CustomField>
    <fullName>IDR_Complaint_Outcome__c</fullName>
    <complianceGroup>Source_Salesforce;Integrity_Trusted;Privacy_Non_Personal_Information</complianceGroup>
    <description>Free text explaining the outcome of the complaint</description>
    <label>Complaint Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Origin</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>In favour of customer in full</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>In favour of customer in part</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>In favour of ANZ</label>
            </value>
            <value>
                <fullName>No response from Customer</fullName>
            </value>
            <value>
                <fullName>Outside of Rules</fullName>
            </value>
            <value>
                <fullName>Merits Assessments</fullName>
            </value>
            <value>
                <fullName>Merged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_Is_Written_Resp_Requested__c.field-meta.xml
<CustomField>
    <fullName>IDR_Is_Written_Resp_Requested__c</fullName>
    <complianceGroup>Integrity - Accurate</complianceGroup>
    <inlineHelpText>Has the customer requested a written response?</inlineHelpText>
    <label>Is a Written Response Requested?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_Is_Written_Resp_Required__c.field-meta.xml
<CustomField>
    <fullName>IDR_Is_Written_Resp_Required__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <description>Is a Written Response to the Complaint Required under regulations/policy? Yes or No response</description>
    <inlineHelpText>Is the complaint relating to hardship, a declined insurance claim, the value of an insurance claim or a decision of a superannuation trustee?</inlineHelpText>
    <label>Is a Written Response Required?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_Subsequent_Issue__c.field-meta.xml
<CustomField>
    <fullName>IDR_Subsequent_Issue__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Sub categorisation of issue</description>
    <label>Subsequent Issue Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>None</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Branch queues / wait time</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Call queues / wait time</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Trading hours/location/closures</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Design/layout/content</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>System fault/outage</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Merchant terminal issue</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Digital</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Account/Profile set up</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Account/Profile Maintenance</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Incorrect or insufficient explanation or disclosure</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Fee or interest dispute</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Fee waiver or interest benefit not received</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Rewards points not applied / unable to be redeemed</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Foreign exchange amount/rate dispute</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Rate not competitive</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Change to fees/rates/rewards structure</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Request for financial assistance</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Failure to respond or process request for assistance</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>Declines financial assistance</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Arrangement considered unsuitable</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Inappropriate or excessive contact</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Pledged or blocked account</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Disputed debt</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Collector/agent conduct</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Information/correspondence incorrect/not provided</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Incorrect set up</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Title/encumbrance lodgement or release issue</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>Valuation outcome or delay</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Loan disbursement issue/error</label>
            </value>
            <value>
                <fullName>90</fullName>
                <label>ATM Disputes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/c360/ComplaintResolutionControllerTest.cls
/**
 * @author CMOS
 * @since 04/2025
 * @description Test class for {@link ComplaintResolutionController}
 */
@isTest
private class ComplaintResolutionControllerTest {
  static Lib_MockProvider complaintResRepoMock;
  static void registerMocks() {
    complaintResRepoMock = Lib_MockProvider.forType(
      ComplaintResolutionControllerRepo.class
    );
  }

  static Account testAcc = new Account(
    Id = Lib_FakeIdGenerator.getMockId(Account.SObjectType)
  );

  @isTest
  static void testgetCustomerCases() {
    registerMocks();

    Case testCase = new Case(
      Id = Lib_FakeIdGenerator.getMockId(Case.SObjectType),
      RecordTypeId = RTCase.customerComplaint,
      IDR_Complaint_Outcome__c = '1',
      Status = IDRConstants.OPEN_STATUS,
      AccountId = testAcc.Id,
      Type = '20',
      IDR_Is_Written_Resp_Requested__c = 'No',
      IDR_Is_Written_Resp_Required__c = 'No',
      IDR_Subsequent_Issue__c = '90'
    );

    complaintResRepoMock.mock('getCustomerCases', new List<Case>{ testCase });

    Test.startTest();
    List<Case> result = ComplaintResolutionController.getComplaintResolution(
      testAcc.Id
    );
    Test.stopTest();
    Assert.areEqual(!result.isEmpty(), true, 'Case List should not be empty');
  }

  @isTest
  static void testZeroCasesReturned() {
    Test.startTest();
    List<Case> result = ComplaintResolutionController.getComplaintResolution(
      testAcc.Id
    );
    Test.stopTest();
    Assert.areEqual(result.isEmpty(), true, 'Case List should be empty');
  }
}