force-app/main/default/objects/Case/fields/IDR_Account_Card_Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>IDR_Account_Card_Policy_Number__c</fullName>
    <description>Account/Card/Policy the complaint relates to. Contents must be masked leaving last 4 digits identifiable.</description>
    <inlineHelpText>Account/Card/Policy the complaint relates to. Contents must be masked leaving last 4 digits identifiable.</inlineHelpText>
    <label>Account/Card/Policy Number</label>
    <length>42</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>IDR_Customer_Number__c</fullName>
    <complianceGroup>Integrity - Trusted</complianceGroup>
    <externalId>true</externalId>
    <inlineHelpText>Also known as Customer CAP CIS ID. Copy and paste this from MAUD</inlineHelpText>
    <label>Customer Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IDR_Notification_Hours__c/IDR_Notification_Hours__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to control the timing of the notifications sent out to customer.</description>
    <label>IDR Notification Hours</label>
</CustomObject>

force-app/main/default/objects/IDR_Notification_Hours__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>Enter the time in 24 hours</description>
    <label>End Time</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IDR_Notification_Hours__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Insert the time in 24 hours clock format</description>
    <label>Start Time</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification_Handler__c/Notification_Handler__c.object-meta.xml
<CustomObject>
    <description>This is to manage/organise the publish time of customer notification</description>
    <label>Notification Handler</label>
    <nameField>
        <displayFormat>NH-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Handler</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Handler__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <deleteConstraint>Cascade</deleteConstraint>
    <description>Related Case internal Id</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notification Handler</relationshipLabel>
    <relationshipName>Notification_Handler</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification_Handler__c/fields/Case_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Status__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Case Status at the time of creating this record</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Case Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Handler__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Pending Publish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/idr/TestNotificationHandlerTrigger.cls
/**
 * @author Afreen Khan
 * @since 11/2020
 * @description  To test NotificationTriggerHandler
 */

@isTest
public class TestNotificationHandlerTrigger {
  /**
   * @description Test data setup required for this test class
   */
  @testSetup
  static void setup() {
    IDR_Notification_Hours__c nHours = new IDR_Notification_Hours__c();
    nHours.Start_Time__c = System.now().hour() - 1;
    nHours.End_Time__c = System.now().hour() + 2;
    insert nHours;

    // Create Case
    Case testCase = new Case();

    testCase.IDR_Account_Card_Policy_Number__c = '000001234';
    testCase.Description = 'Test decription';
    testCase.RecordTypeId = IDRCaseActions.CUSTOMER_COMPLAINT_RT_ID;
    testCase.IDR_Customer_Number__c = '1234567890';
    testCase.Status = IDRConstants.OPEN_STATUS;

    insert testCase;
  }

  /**
   * @description Test data setup required for this test class
   */

  @isTest
  static void testManualNotification() {
    //Retrieve the case inserted
    Case c = [SELECT Id FROM Case LIMIT 1];

    Test.startTest();
    //create the notification handler record Manually
    Notification_Handler__c handlerRecord = new Notification_Handler__c();
    handlerRecord.Case__c = c.Id;
    handlerRecord.Status__c = IDRConstants.NOTIFICATION_PUBLISH_STATUS;
    handlerRecord.Case_Status__c = IDRConstants.OPEN_STATUS;
    insert handlerRecord;

    Test.stopTest();

    Notification_Handler__c handlerPostExecution = [
      SELECT Id, Status__c
      FROM Notification_Handler__c
      ORDER BY CreatedDate DESC
      LIMIT 1
    ];

    //verify that notification is published successfully
    System.assertEquals(
      IDRConstants.NOTIFICATION_PUBLISH_STATUS,
      handlerPostExecution.Status__c
    );
  }
}