force-app/main/default/objects/Case/fields/IDR_Is_Restricted__c.field-meta.xml
<CustomField>
    <fullName>IDR_Is_Restricted__c</fullName>
    <complianceGroup>Integrity - Trusted;Source - Salesforce;Privacy - Non Personal Information</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Technical field used by case sharing rules to restrict a case to some users.
Updated from user-selected Restriction Level Picklist by asynchronous trigger.</description>
    <label>Restricted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_Restriction_Level__c.field-meta.xml
<CustomField>
    <fullName>IDR_Restriction_Level__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <inlineHelpText>Complaint Resolution Portfolio Restriction:

Only restrict this case if it is being escalated to the Complaint Resolution Portfolio or if it is already being managed by the Complaint Resolution Portfolio.

Selecting to restrict this case will mean that only Complaint Resolution Portfolio users will have access to all information on this case file.  All other users will only be able to view the:

•	case number 
•	customer name
•	case owner
•	case status</inlineHelpText>
    <label>Restriction Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Restriction</fullName>
            </value>
            <value>
                <fullName>Restricted Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/idr/IDRCaseChangeEventActions.cls
/**
 * @description CMOS Handler class for the Case asynchronous trigger.
 * This fires after all database transactions on case completed, avoiding problems when a banker marks a case as restricted and looses access to it.
 * @author Olivier Saier
 * @since 06/2021
 * @group IDR(Internal Dispute Resolution)
 */
public with sharing class IDRCaseChangeEventActions {
  private static final DmlRepository DML = (DmlRepository) Lib_InstanceProvider.forType(
    DmlRepository.class
  );
  /**
   * @description Updates the case IDR_Is_Restricted__c field value based on the Restriction level field value.
   * @param records The published Case change events
   */
  public static void updateCaseRestrictions(List<CaseChangeEvent> records) {
    List<CaseChangeEvent> filteredEvents = validEvents(records);
    List<Case> restrictedCases = getRestrictedCases(filteredEvents);
    List<Case> nonRestrictedCases = getNonRestrictedCases(filteredEvents);
    ListUtil.setField(restrictedCases, Case.IDR_Is_Restricted__c, true);
    ListUtil.setField(nonRestrictedCases, Case.IDR_Is_Restricted__c, false);
    List<Case> caseToUpdate = new List<Case>(restrictedCases);
    caseToUpdate.addAll(nonRestrictedCases);
    DML.doUpdate(caseToUpdate, new DmlConfig().systemMode());
  }
  /**
   * @description Returns list of case records where IDR_Restriction_Level__c is 'Restricted Case'.
   * @param listOfEvents List of CaseChangeEvent.
   * @return `List<Case>` return list of restricted cases.
   */
  @TestVisible
  private static List<Case> getRestrictedCases(
    List<CaseChangeEvent> listOfEvents
  ) {
    List<Case> restrictedCases = new List<Case>();
    for (CaseChangeEvent change : listOfEvents) {
      if (
        !change.IDR_Restriction_Level__c.equalsIgnoreCase('Restricted Case')
      ) {
        continue;
      }
      restrictedCases.add(
        new Case(Id = change.ChangeEventHeader.getRecordIds()[0])
      );
    }
    return restrictedCases;
  }
  /**
   * @description Returns list of case records where IDR_Restriction_Level__c is 'No Restriction'.
   *  @param listOfEvents List of CaseChangeEvent.
   * @return `List<Case>` return list of no restricted cases.
   */
  @TestVisible
  private static List<Case> getNonRestrictedCases(
    List<CaseChangeEvent> listOfEvents
  ) {
    List<Case> nonRestrictedCases = new List<Case>();
    for (CaseChangeEvent change : listOfEvents) {
      if (!change.IDR_Restriction_Level__c.equalsIgnoreCase('No Restriction')) {
        continue;
      }
      nonRestrictedCases.add(
        new Case(Id = change.ChangeEventHeader.getRecordIds()[0])
      );
    }
    return nonRestrictedCases;
  }
  /**
   * @description Return valid event records.
   * @param records List of CaseChangeEvent to process.
   * @return `List<CaseChangeEvent>` return valid event records.
   */
  @TestVisible
  private static List<CaseChangeEvent> validEvents(
    List<CaseChangeEvent> records
  ) {
    List<CaseChangeEvent> filteredEvents = new List<CaseChangeEvent>();
    for (CaseChangeEvent record : records) {
      if (record.IDR_Restriction_Level__c == null) {
        continue;
      }
      if (
        !record.ChangeEventHeader.getChangedFields()
          .contains('IDR_Restriction_Level__c') &&
        record.ChangeEventHeader.getChangeType() == 'UPDATE'
      ) {
        continue;
      }
      if (
        record.IDR_Restriction_Level__c != 'Restricted Case' &&
        record.ChangeEventHeader.getChangeType() == 'CREATE'
      ) {
        continue;
      }
      filteredEvents.add(record);
    }
    return filteredEvents;
  }
}