force-app/main/default/objects/Case/fields/IDR_Account_Card_Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>IDR_Account_Card_Policy_Number__c</fullName>
    <description>Account/Card/Policy the complaint relates to. Contents must be masked leaving last 4 digits identifiable.</description>
    <inlineHelpText>Account/Card/Policy the complaint relates to. Contents must be masked leaving last 4 digits identifiable.</inlineHelpText>
    <label>Account/Card/Policy Number</label>
    <length>42</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Handler__c/Notification_Handler__c.object-meta.xml
<CustomObject>
    <description>This is to manage/organise the publish time of customer notification</description>
    <label>Notification Handler</label>
    <nameField>
        <displayFormat>NH-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Handler</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Handler__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <deleteConstraint>Cascade</deleteConstraint>
    <description>Related Case internal Id</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notification Handler</relationshipLabel>
    <relationshipName>Notification_Handler</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification_Handler__c/fields/Case_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Status__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Case Status at the time of creating this record</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Case Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Handler__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Pending Publish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestNotificationHandlerTrigger.cls
@isTest
public class TestNotificationHandlerTrigger {

    @testSetup static void setup() {
        // Create Case
        Case testCase = new Case();
        
        testCase.IDR_Account_Card_Policy_Number__c = '000001234';
        testCase.Description = 'Test decription';
        testCase.RecordTypeId = IDRCaseActions.CUSTOMER_COMPLAINT_RT_ID;
        testCase.Status = IDRConstants.OPEN_STATUS;

        insert testCase;

    }

    @isTest
    static void testManualNotification() {
        Case c = [Select Id From Case Limit 1];
        Test.startTest();
        Notification_Handler__c handlerRecord = new Notification_Handler__c();
        handlerRecord.Case__c = c.Id;
        handlerRecord.Status__c= IDRConstants.NOTIFICATION_PUBLISH_STATUS;
        handlerRecord.Case_Status__c = IDRConstants.OPEN_STATUS;
        insert handlerRecord;
        Test.stopTest();
        System.assertEquals(1, NotificationTriggerHandler.idrNotifications.size());
    }




}