force-app/main/default/objects/Case/fields/IDR_Complainant_Desired_Outcome__c.field-meta.xml
<CustomField>
    <fullName>IDR_Complainant_Desired_Outcome__c</fullName>
    <complianceGroup>Integrity - Accurate</complianceGroup>
    <description>Free text explaining the desired outcome of the complaint raised</description>
    <label>Customer Desired Outcome</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_Existing_ANZ_Customer__c.field-meta.xml
<CustomField>
    <fullName>IDR_Existing_ANZ_Customer__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>anz.com complain web-form field</description>
    <label>Existing ANZ Customer?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_Feedback_Category__c.field-meta.xml
<CustomField>
    <fullName>IDR_Feedback_Category__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information</complianceGroup>
    <description>feedback categories from anz.com feedback form</description>
    <label>Feedback Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Compliment</fullName>
            </value>
            <value>
                <fullName>Suggestion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_NC_Country__c.field-meta.xml
<CustomField>
    <fullName>IDR_NC_Country__c</fullName>
    <description>Customer&apos;s country of residence.</description>
    <complianceGroup>Integrity - Accurate;Privacy - Personal Information</complianceGroup>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FinServ__Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_NC_Email__c.field-meta.xml
<CustomField>
    <fullName>IDR_NC_Email__c</fullName>
    <description>Capture this only if complainant is not found in MAUD/CAP-CIS.</description>
    <inlineHelpText>Capture this only if complainant is not found in MAUD/CAP-CIS.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_NC_First_Name__c.field-meta.xml
<CustomField>
    <fullName>IDR_NC_First_Name__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Personal Information</complianceGroup>
    <description>First Name of Complainant.

Capture this only if customer is not found in MAUD/CAP-CIS.</description>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_NC_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>IDR_NC_Last_Name__c</fullName>
    <description>Capture this only if complainant is not found in MAUD/CAP-CIS.</description>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_NC_Phone__c.field-meta.xml
<CustomField>
    <fullName>IDR_NC_Phone__c</fullName>
    <complianceGroup>Integrity - Trusted</complianceGroup>
    <description>Capture this only if customer is not found in MAUD/CAP-CIS.</description>
    <inlineHelpText>Capture this only if mobile is unavailable.</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_NC_Postcode__c.field-meta.xml
<CustomField>
    <fullName>IDR_NC_Postcode__c</fullName>
    <complianceGroup>Privacy - Personal Information;Source - Salesforce;Integrity - Accurate</complianceGroup>
    <description>Customer&apos;s residential address: Postcode. Capture this only if customer is not found in MAUD/CAP-CIS.</description>
    <inlineHelpText>To edit Customer address fields, navigate to the top banner and click Edit Contact Details via the dropdown button</inlineHelpText>
    <label>Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_NC_Street__c.field-meta.xml
<CustomField>
    <fullName>IDR_NC_Street__c</fullName>
    <complianceGroup>Source_Salesforce;Integrity_Accurate;Privacy_Personal_Information</complianceGroup>
    <description>Customer&apos;s residential address: Street. Capture this only if customer is not found in MAUD/CAP-CIS.</description>
    <inlineHelpText>To edit Customer address fields, navigate to the top banner and click Edit Contact Details via the dropdown button</inlineHelpText>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_NC_Suburb__c.field-meta.xml
<CustomField>
    <fullName>IDR_NC_Suburb__c</fullName>
    <description>Complainant&#39;s residential address: Suburb. Capture this only if complainant is not found in MAUD/CAP-CIS.</description>
    <label>Suburb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_Previously_raised_with_ANZ__c.field-meta.xml
<CustomField>
    <fullName>IDR_Previously_raised_with_ANZ__c</fullName>
    <complianceGroup>Integrity_Accurate</complianceGroup>
    <description>anz.com web form field</description>
    <label>Previously raised with ANZ?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_Product_Category__c.field-meta.xml
<CustomField>
    <fullName>IDR_Product_Category__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Anz.com complain web-from field</description>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit card</fullName>
            </value>
            <value>
                <fullName>Cheque/Savings accounts</fullName>
            </value>
            <value>
                <fullName>Home loans</fullName>
            </value>
            <value>
                <fullName>Business accounts</fullName>
            </value>
            <value>
                <fullName>Personal loan</fullName>
            </value>
            <value>
                <fullName>Business loans</fullName>
            </value>
            <value>
                <fullName>Insurance/wealth products</fullName>
            </value>
            <value>
                <fullName>Commercial cards</fullName>
            </value>
            <value>
                <fullName>Asset finance</fullName>
            </value>
            <value>
                <fullName>Foreign exchange</fullName>
            </value>
            <value>
                <fullName>Merchants</fullName>
            </value>
            <value>
                <fullName>ANZ Plus</fullName>
            </value>
            <value>
                <fullName>ANZ Internet Banking</fullName>
            </value>
            <value>
                <fullName>Not product related</fullName>
            </value>
            <value>
                <fullName>Deceased Estates</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Complaint.recordType-meta.xml
<RecordType>
    <fullName>Complaint</fullName>
    <active>true</active>
    <businessProcess>Complaint Support Process</businessProcess>
    <description>Record a new complaint.</description>
    <label>Complaint</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Fraud.recordType-meta.xml
<RecordType>
    <fullName>Fraud</fullName>
    <active>true</active>
    <businessProcess>Fraud Support Process</businessProcess>
    <description>Record a new fraud case for an existing ANZx customer</description>
    <label>Fraud</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/General_Inquiry_CMOS.recordType-meta.xml
<RecordType>
    <fullName>General_Inquiry_CMOS</fullName>
    <active>true</active>
    <businessProcess>General Inquiry CMOS</businessProcess>
    <description>Unauthenticated Enquiry Record Type</description>
    <label>Unauthenticated Enquiry</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/IDR_Collections.recordType-meta.xml
<RecordType>
    <fullName>IDR_Collections</fullName>
    <active>true</active>
    <description>New record type for system generated collection tasks</description>
    <label>IDR Collections</label>
</RecordType>

force-app/main/default/globalValueSets/FinServ__Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
        <default>true</default>
        <label>Australia</label>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/idr/IDRConstants.cls
/**
 * @author Afreen Khan
 * @since 10/2020
 * @description  IDRConstants consists of all the IDR constants
 */
public with sharing class IDRConstants {
  //Complaint Status
  public static final String OPEN_STATUS = 'Open';
  public static final String UNDER_INVESTIGATION_STATUS = 'Under Investigation';
  public static final String ESCALATED_STATUS = 'Escalated';
  public static final String REOPENED_STATUS = 'Re-opened';
  public static final String CLOSED_STATUS = 'Closed';
  public static final String RESOLVED_STATUS = 'Resolved';
  public static final String WITHDRAWN_STATUS = 'Withdrawn';

  //Complaint, Non- Complaint, General Inquiry Case Record Type
  public static final Id CUSTOMER_COMPLAINT_RT_ID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName()
    .get('Customer_Complaint')
    .getRecordTypeId();
  public static final Id NON_CUSTOMER_COMPLAINT_RT_ID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName()
    .get('Non_Customer_Complaint')
    .getRecordTypeId();
  public static final Id GENERAL_INQUIRY_CMOS_RT_ID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName()
    .get('General_Inquiry_CMOS')
    .getRecordTypeId();

  //IDR collections task record type
  public static final Id IDR_COLLECTIONS_RT_ID = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName()
    .get('IDR_Collections')
    .getRecordTypeId();

  //Complaint Type and Subsequent Issue Type Set for collections
  public static final Set<String> ISSUE_TYPE_COLLECTIONS = new Set<String>{
    '4',
    '5',
    '17',
    '19'
  };
  public static final Set<String> SUB_ISSUE_TYPE_COLLECTIONS = new Set<String>{
    '20',
    '21',
    '22',
    '23',
    '24',
    '25',
    '26',
    '27',
    '28',
    '38',
    '42'
  };

  //NotificationHandler Status
  public static final String NOTIFICATION_PUBLISH_STATUS = 'Published';
  public static final String NOTIFICATION_PENDING_PUBLISH_STATUS = 'Pending Publish';
  public static final String NOTIFICATION_ERROR_PUBLISH_STATUS = 'Error while Publish';

  //Message Text
  public static final String RESTRICTED_ACTION_MESSAGE = 'You are not authorised to perform this action.';

  //Milestone Sla
  public static final String MILESTONE_SLA_NORMAL = 'Normal';
  public static final String MILESTONE_SLA_RED = '1 business day';
  public static final String MILESTONE_SLA_AMBER = '2 business days';
  public static final string MILESTONE_SLA_VIOLATED = 'Violated';
  public static final string COMPLAINTS_ENTITLMENT_ACCT = 'Complaint Entitlement Account';
  public static final string COMPLAINTS_ENTITLMENT_PROCESS = 'complaints';
  public static final string COMPLAINTS_ENTITLEMENT_NAME = 'Complaints Entitlement';

  //Field labels
  public static final String MILESTONE_SLA_FIELD_LABEL = 'Milestone Sla';
  public static final String CASE_OWNER_ID = 'Owner ID';

  //IDR Maximum time constants
  public static final string TASK_SUBJECT_DAY5 = 'IDR Response due in 5-days';
  public static final string TASK_SUBJECT_DAY1 = 'IDR Response Due in 1-day';
  public static final string TASK_STANDARD_PRIORITY = 'Standard';
  public static final string TASK_STATUS_EXPIRED = 'Expired';
  public static final string TASK_STATUS_COMPLETED = 'Completed';
  public static final string MILESTONE_STANDARD = '30-day IDR Response Due';
  public static final string MILESTONE_PRIORITY = '21-day IDR Response Due';

  //Channel Recieved
  public static final string CHANNEL_RECEIVED_AFCA_REFERRED = 'Referred from AFCA';

  //Anz.com constants
  /**
   * @description Static variable to map anz.com field with case fields
   * @return anzComFieldMapping map of anz.com field with case fields
   */
  public static final Map<String, String> anzComFieldMapping {
    get {
      if (anzComFieldMapping == null) {
        anzComFieldMapping = new Map<String, String>{
          'This feedback is a' => 'IDR_Feedback_Category__c',
          'Previously raised?' => 'IDR_Previously_raised_with_ANZ__c',
          'Which product' => 'IDR_Product_Category__c',
          'Feedback topic' => 'Type',
          'Feedback summary' => 'Description',
          'Details and outcome' => 'IDR_Complainant_Desired_Outcome__c',
          'ANZ Customer?' => 'IDR_Existing_ANZ_Customer__c',
          'First name' => 'IDR_NC_First_Name__c',
          'Last name' => 'IDR_NC_Last_Name__c',
          'Contact number' => 'IDR_NC_Phone__c',
          'Email address' => 'IDR_NC_Email__c',
          'Street address' => 'IDR_NC_Street__c',
          'Suburb' => 'IDR_NC_Suburb__c',
          'Postcode' => 'IDR_NC_Postcode__c',
          'Country' => 'IDR_NC_Country__c'
        };
      }
      return anzComFieldMapping;
    }
    set;
  }

  /**
   * @description Static variable to map anz.com Issue type field with case type field
   * @return anzComIssueTypeMapping map of anz.com Issue type field with case type field
   */
  public static final Map<String, String> anzComIssueTypeMapping {
    get {
      if (anzComIssueTypeMapping == null) {
        anzComIssueTypeMapping = new Map<String, String>{
          'Account set up/Maitenence/Closure' => 'Account set-up & maintenance',
          'Branch/Merchant/System issue' => 'Channel accessibility',
          'Collections' => 'Collections',
          'Credit card/Loan assessment' => 'Credit assessment',
          'Fees/Interest/Rewards' => 'Fees, interest, rewards',
          'Fraud/Dispute' => 'Transaction Disputes',
          'Hardship' => 'Financial difficulty & hardship',
          'Loan settlement/Drawdown' => 'Lending fulfilment',
          'Payments' => 'Transactions & payments',
          'Product features/Marketing/Sales' => 'Product features, offers, sales',
          'Service Quality' => 'Service quality',
          'Other' => 'Other'
        };
      }
      return anzComIssueTypeMapping;
    }
    set;
  }

  /**
   * @description Static variable to map anz.com Issue type field with case type field
   * @return anzComIssueTypeMapping map of anz.com Issue type field with case type field
   */
  public static final List<String> workBasketNames {
    get {
      if (workBasketNames == null) {
        workBasketNames = new List<String>{
          'Specialised_Early_Resolution_Hardship',
          'Specialised_EarlyRes_Responsible_Lending',
          'EDR_Early_Resolution'
        };
      }
      return workBasketNames;
    }
    set;
  }
}