force-app/main/default/objects/Case/fields/IDR_Additional_Correspondence_reviewed__c.field-meta.xml
<CustomField>
    <fullName>IDR_Additional_Correspondence_reviewed__c</fullName>
    <complianceGroup>Source - Salesforce;Integrity - Trusted;Privacy - Personal Information</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Additional Correspondence reviewed Flag is created to show up the case in report for case manager to action</description>
    <label>Additional Correspondence reviewed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_Document_Count__c.field-meta.xml
<CustomField>
    <fullName>IDR_Document_Count__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>A dummy system field whose main purpose is to allow users with level 2/3 privileges to force update the LastModifiedDate field on the case, upon uploading a new document. The count is not meant to be accurate. It will simply be changed whenever a document is uploaded.</description>
    <label>IDR Document Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_Restriction_Level__c.field-meta.xml
<CustomField>
    <fullName>IDR_Restriction_Level__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <inlineHelpText>Complaint Resolution Portfolio Restriction:

Only restrict this case if it is being escalated to the Complaint Resolution Portfolio or if it is already being managed by the Complaint Resolution Portfolio.

Selecting to restrict this case will mean that only Complaint Resolution Portfolio users will have access to all information on this case file.  All other users will only be able to view the:

•	case number 
•	customer name
•	case owner
•	case status</inlineHelpText>
    <label>Restriction Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Restriction</fullName>
            </value>
            <value>
                <fullName>Restricted Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/idr/CaseChangeEventTriggerTest.cls
/**
 * @author CMOS
 * @since 08/2025
 * @description test class for CaseChangeEventTrigger
 */
@isTest
private class CaseChangeEventTriggerTest {
  @isTest
  static void triggerCoverage() {
    Test.enableChangeDataCapture();
    Case caseRecord = (Case) TestUtil.setFields(
      new Case(
        RecordTypeId = RTCase.nonCustomerComplaint,
        Status = IDRConstants.OPEN_STATUS,
        IDR_Additional_Correspondence_reviewed__c = false,
        IDR_Document_Count__c = null,
        IDR_Restriction_Level__c = 'Restricted Case'
      ),
      new Map<String, Object>{
        'CaseNumber' => new Faker('0-9').randomInteger(6)
      }
    );
    Test.getEventBus().deliver();
    Test.startTest();
    insert caseRecord;
    Test.stopTest();
    Assert.isNotNull(caseRecord.Id, 'Case record should be inserted');
  }
}