force-app/main/default/objects/Case/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Application Id associated with referral</description>
    <label>Loan Application</label>
    <referenceTo>ResidentialLoanApplication</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Coaching_Summary__c/Coaching_Summary__c.object-meta.xml
<CustomObject>
    <description>This object will contain all the summaries created by the coaches against one or many Appointment Interactions.</description>
    <label>Coaching Summary</label>
    <nameField>
        <displayFormat>CS-{00000000}</displayFormat>
        <label>Coaching Summary Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coaching Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Coaching_Summary__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lead linked with Interaction</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Coaching Summaries</relationshipLabel>
    <relationshipName>Coaching_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Coaching_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>Status of the coaching summary record.</description>
    <inlineHelpText>The current status of the coaching summary.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction/fields/Actual_Topics__c.field-meta.xml
<CustomField>
    <fullName>Actual_Topics__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Comma separated list of actual topics selected from Interaction Context LWC</description>
    <label>Actual Topics</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction/fields/Attendees__c.field-meta.xml
<CustomField>
    <fullName>Attendees__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Comma separated list of Interaction Attendees (updated based on Interaction Attendee records)</description>
    <label>Attendees</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Case this Interaction is related with</description>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction/fields/Chat_or_Call_SID__c.field-meta.xml
<CustomField>
    <fullName>Chat_or_Call_SID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Twilio</complianceGroup>
    <description>Used to store the unique Chat / Call Channel ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for call or message thread created by Twilio</inlineHelpText>
    <label>Chat or Call SID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Interaction/fields/Coaching_Summary__c.field-meta.xml
<CustomField>
    <fullName>Coaching_Summary__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Summary linked with Interaction</description>
    <label>Coaching Summary</label>
    <referenceTo>Coaching_Summary__c</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction/fields/Contact_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Contact_Mobile__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Personal_Information;Source_OCV</complianceGroup>
    <description>The contact mobile number for either the Contact or Lead associated with the interaction.</description>
    <label>Contact Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Interaction/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <complianceGroup>Source - Salesforce;Privacy - Non Personal Information;Integrity - Accurate</complianceGroup>
    <description>Direction - To describe inbound or outbound call</description>
    <label>Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction/fields/Interaction_Auto_Number__c.field-meta.xml
<CustomField>
    <fullName>Interaction_Auto_Number__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>Interaction Number</description>
    <displayFormat>IR-{00000000}</displayFormat>
    <label>Interaction Auto Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Interaction/fields/Interaction_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Interaction_Purpose__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Reason for Interaction</description>
    <inlineHelpText>For Interaction records - select whom the engagement is with, eg customer. For Appointment booking - select the main topic of the appointment, eg financial wellbeing.</inlineHelpText>
    <label>For</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>InteractionType</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ Customer</fullName>
            </value>
            <value>
                <fullName>ANZ Plus Customer</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Digital Support</fullName>
            </value>
            <value>
                <fullName>Existing ANZ Customer</fullName>
            </value>
            <value>
                <fullName>Financial Wellbeing</fullName>
            </value>
            <value>
                <fullName>Non-Customer</fullName>
            </value>
            <value>
                <fullName>Home Loan</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The lead who requested for interaction.</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction/fields/Place__c.field-meta.xml
<CustomField>
    <fullName>Place__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Store locations</description>
    <label>Place</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>InteractionType</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>Potts Point</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>Richmond</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Martin Place</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction/fields/Reason_for_Visit__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Visit__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Comma separated list of products selected from Interaction Context LWC</description>
    <label>Reason for Visit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction/fields/Resolution__c.field-meta.xml
<CustomField>
    <fullName>Resolution__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Outcome of the Interaction</description>
    <label>Action Taken</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Interaction_Purpose__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Assisted App download</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Did not Answer</fullName>
            </value>
            <value>
                <fullName>Duplicate &amp; Closed</fullName>
            </value>
            <value>
                <fullName>Follow-up Required</fullName>
            </value>
            <value>
                <fullName>No Action</fullName>
            </value>
            <value>
                <fullName>Proactive Contact</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
            <value>
                <fullName>Voice Mail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Status of Interaction</description>
    <inlineHelpText>The current status of the chat / appointment.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed &amp; Archived</fullName>
            </value>
            <value>
                <fullName>Closed - Completed</fullName>
            </value>
            <value>
                <fullName>Closed - Follow Up Interaction</fullName>
            </value>
            <value>
                <fullName>Closed - Withdrawn</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Linked</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Not Completed</fullName>
            </value>
            <value>
                <fullName>On Hold (By Coach)</fullName>
            </value>
            <value>
                <fullName>On Hold (By Customer)</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Walk In</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction/fields/Video_Call__c.field-meta.xml
<CustomField>
    <fullName>Video_Call__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>For Chat Interactions to decide whether Video Call happened or not</description>
    <inlineHelpText>If this interaction also involved a video call, then check the box.</inlineHelpText>
    <label>Video Call</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Interaction/recordTypes/Message.recordType-meta.xml
<RecordType>
    <fullName>Message</fullName>
    <active>true</active>
    <description>Message Record Type for Interactions</description>
    <label>Message</label>
</RecordType>

force-app/main/default/classes/InteractionListViewFetchData.cls
/**
 * @author Nagendra Singh
 * @since July 2023
 * @description InteractionListViewFetchData
 */
global with sharing class InteractionListViewFetchData implements omnistudio.VlocityOpenInterface, Callable {
  private final static Integer MAXLIMIT = 5000;
  /**
   * @description invokeMethod to handle insertion of logs from omnistudio.
   * @param methodName Method named to be called.
   * @param inputMap Input from omnistudio component as a key value pair.
   * @param outMap Output to be returned as a response to caller Omnicomponent.
   * @param options Options passed from omnistudio.
   * @return Object containing outMap, which can contain custom message and should return success as false and true based on logic.
   */
  global Boolean invokeMethod(
    String methodName,
    Map<String, Object> inputMap,
    Map<String, Object> outMap,
    Map<String, Object> options
  ) {
    Boolean success = true;
    String error = '';
    try {
      if (methodName == 'fetchDataBasedOnRecordId') {
        fetchDataBasedOnRecordId(inputMap, outMap, options);
      }
    } catch (Exception e) {
      error = e.getMessage() + ' StackTrace -> ' + e.getStackTraceString();
      success = false;
    }
    return success;
  }

  /**
   * @description this method helps in fetch the interaction records based on the recordtypename and parent id.
   * @param inputMap Input from omnistudio component as a key value pair.
   * @param outMap Output to be returned as a response to caller Omnicomponent.
   * @param options Options passed from omnistudio.
   */
  public void fetchDataBasedOnRecordId(
    Map<String, Object> inputMap,
    Map<String, Object> outMap,
    Map<String, Object> options
  ) {
    String anyRecordId = (String) inputMap.get('anyRecordId');
    String recordTypeDeveloperName = (String) inputMap.get(
      'recordTypeDeveloperName'
    );
    List<String> statusSearch = (List<String>) inputMap.get('statusSearch');
    Integer maxNumber = (inputMap.get('maxNumber') == null)
      ? MAXLIMIT
      : (Integer) inputMap.get('maxNumber');
    String interactionQuery = 'SELECT Id,RecordType.DeveloperName,Chat_or_Call_SID__c, Name, Interaction_Auto_Number__c, AccountId, Account.Name,Lead__c, Lead__r.Name,StartTime,Interaction_Purpose__c, Contact_Mobile__c,InteractionType,Resolution__c ,Owner.Name ,CreatedDate, Actual_Topics__c, Reason_for_Visit__c, Status__c, Place__c, Attendees__c ,Video_Call__c, Direction__c From Interaction WHERE ';
    String sobjectType = String.valueOf(
      Id.valueOf(anyRecordId).getSObjectType()
    );

    switch on sobjectType {
      when 'Account' {
        interactionQuery += 'AccountId = :anyRecordId';
      }
      when 'Case' {
        interactionQuery += 'CaseId__c = :anyRecordId';
      }
      when 'Coaching_Summary__c' {
        interactionQuery += 'Coaching_Summary__c = :anyRecordId';
      }
      when 'Lead' {
        interactionQuery += 'Lead__c = :anyRecordId';
      }
      when 'ResidentialLoanApplication' {
        interactionQuery += 'Loan_Application__c = :anyRecordId';
      }
    }

    //statusSearch works conditionally when passed from LWC or Aura.When the status search is passed then it will be appended to the query and records will be filtered based on that.
    interactionQuery += ' AND RecordType.DeveloperName = :recordTypeDeveloperName';
    if (statusSearch != null && !statusSearch.isEmpty()) {
      interactionQuery +=
        ' AND Status__c IN (\'' +
        String.join(statusSearch, '\',\'') +
        '\') ';
    }
    interactionQuery += ' ORDER BY CreatedDate DESC';
    interactionQuery += ' LIMIT ' + maxNumber;
    List<Interaction> lstInteractionsFromDB = (List<Interaction>) Database.query(
      interactionQuery
    );
    outMap.put('interactions', lstInteractionsFromDB);
  }

  /**
   * @description Overriden method from Callable interface to invoke methods dynamically based on action passed.
   * @param action Dynamic method name to be called.
   * @param args Dynamic arguments to passed from omnistudio.
   * @return Object containing outMap, which can contain custom message and should return success as false and true based on logic.
   */
  global Object call(String action, Map<String, Object> args) {
    Map<String, Object> input = (Map<String, Object>) args.get('input');
    Map<String, Object> output = (Map<String, Object>) args.get('output');
    Map<String, Object> options = (Map<String, Object>) args.get('options');

    return invokeMethod(action, input, output, options);
  }
}