force-app/main/default/objects/Product_Family__c/Product_Family__c.object-meta.xml
<CustomObject>
    <description>Custom Object that controls work basket allocation of complaints</description>
    <label>Product Family</label>
    <nameField>
        <label>Product Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Family__c/fields/IDR_ANZ_com_Product_Category__c.field-meta.xml
<CustomField>
    <fullName>IDR_ANZ_com_Product_Category__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Helps Identify the product family based on Product Category of the case</description>
    <label>ANZ.com Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit card</fullName>
            </value>
            <value>
                <fullName>Cheque/Savings accounts</fullName>
            </value>
            <value>
                <fullName>Home loans</fullName>
            </value>
            <value>
                <fullName>Business accounts</fullName>
            </value>
            <value>
                <fullName>Personal loan</fullName>
            </value>
            <value>
                <fullName>Business loans</fullName>
            </value>
            <value>
                <fullName>Insurance/wealth products</fullName>
            </value>
            <value>
                <fullName>Commercial cards</fullName>
            </value>
            <value>
                <fullName>Asset finance</fullName>
            </value>
            <value>
                <fullName>Foreign exchange</fullName>
            </value>
            <value>
                <fullName>Merchants</fullName>
            </value>
            <value>
                <fullName>ANZ Plus</fullName>
            </value>
            <value>
                <fullName>ANZ Internet Banking</fullName>
            </value>
            <value>
                <fullName>Not product related</fullName>
            </value>
            <value>
                <fullName>Deceased Estates</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Family__c/fields/IDR_Workbasket__c.field-meta.xml
<CustomField>
    <fullName>IDR_Workbasket__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>WorkBasket that cases with this product family need to be assigned to</description>
    <label>Workbasket</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IDR_Business_Owners</fullName>
                <label>IDR Business Owners</label>
            </value>
            <value>
                <fullName>IDR_Everyday_Banking</fullName>
                <label>IDR Everyday Banking</label>
            </value>
            <value>
                <fullName>IDR_Home_Owners</fullName>
                <label>IDR Home Owners</label>
            </value>
            <value>
                <fullName>IDR_Wealth</fullName>
                <label>IDR Wealth</label>
            </value>
            <value>
                <fullName>Specialised_Early_Resolution_Hardship</fullName>
                <label>Specialised Early Resolution Hardship</label>
            </value>
            <value>
                <fullName>Specialised_EarlyRes_Responsible_Lending</fullName>
                <label>Specialised EarlyRes Responsible Lending</label>
            </value>
            <value>
                <fullName>EDR_Early_Resolution</fullName>
                <label>EDR Early Resolution</label>
            </value>
            <value>
                <fullName>IDR_Hardship</fullName>
                <label>IDR Hardship</label>
            </value>
            <value>
                <fullName>IDR_Responsible_Lending</fullName>
                <label>IDR Responsible Lending</label>
            </value>
            <value>
                <fullName>IDR_CEO</fullName>
                <label>IDR CEO</label>
            </value>
            <value>
                <fullName>IDR_Early_Resolution</fullName>
                <label>IDR Early Resolution</label>
            </value>
            <value>
                <fullName>IDR_ANZ_Plus</fullName>
                <label>IDR ANZ Plus</label>
            </value>
            <value>
                <fullName>IDR_Satellite</fullName>
                <label>IDR Cards</label>
            </value>
            <value>
                <fullName>IDR_Deceased_Estates</fullName>
                <label>IDR Deceased Estates</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductFamilyTriggerHandlerTest.cls
/**
 * @author Adnan
 * @since  April 2022
 * @description This is a test class for Product Family Trigger and Handler.
 */
@isTest
public with sharing class ProductFamilyTriggerHandlerTest {
  @isTest
  static void createProductFamilyRecordsTest() {
    //Retrieve all ANZ.com product category picklist values
    List<String> anzComProductCategoryList = new List<String>();
    for (
      Schema.PicklistEntry f : (Product_Family__c.IDR_ANZ_com_Product_Category__c.getDescribe())
        .getPicklistValues()
    ) {
      anzComProductCategoryList.add(f.getValue());
    }
    List<String> idrWorkBasketList = new List<String>();

    for (
      Schema.PicklistEntry f : (Product_Family__c.IDR_Workbasket__c.getDescribe())
        .getPicklistValues()
    ) {
      idrWorkBasketList.add(f.getValue());
    }
    List<Product_Family__c> productFamilyList = new List<Product_Family__c>();
    for (String anzComProductCategory : anzComProductCategoryList) {
      Product_Family__c pf = new Product_Family__c();
      pf.Name = 'Testpf ' + anzComProductCategory;
      pf.IDR_ANZ_com_Product_Category__c = anzComProductCategory;
      pf.IDR_Workbasket__c = idrWorkBasketList[0];
      productFamilyList.add(pf);
    }
    Test.startTest();
    insert productFamilyList;
    Test.stopTest();
    System.assertEquals(
      [SELECT id, Name FROM Product_Family__c].size() > 0,
      true,
      'Incorrect or no product family records were retrieved'
    );
  }
}