force-app/main/default/objects/User_Provisioning_Request__c/User_Provisioning_Request__c.object-meta.xml
<CustomObject>
    <description>Custom object to store user provisioning request details which includes Business Function, Business Roles, Requestor, Approver, Status</description>
    <label>ANZ User Provisioning Request</label>
    <nameField>
        <displayFormat>U-{000000}</displayFormat>
        <label>User Provisioning Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ANZ User Provisioning Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Provisioning_Request__c/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who submits a request for access</description>
    <label>Requestor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Provisioning_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Provisioning_Request__c/fields/Requestor_UUID__c.field-meta.xml
<CustomField>
    <fullName>Requestor_UUID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>External ID field to store the Federation ID of the requested user</description>
    <externalId>true</externalId>
    <label>Requestor UUID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Provisioning_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QueueUPRStatusUpdate.cls
/**
 * @author Boobalakrishnan Duraisamy
 * @since  09/2020
 * @description QueueUPRStatusUpdate class is called in UserTriggerHandler to update User Provisioning Request status Asynchronously to avoid Mixed_DML_Error
 */
public class QueueUPRStatusUpdate implements Queueable {
  Map<String, Boolean> updateUPRMap;

  /**
   * @description Constructor
   * @param triggerUPRMap Map from User Trigger
   */
  public QueueUPRStatusUpdate(Map<String, Boolean> triggerUPRMap) {
    updateUPRMap = triggerUPRMap;
  }

  /**
   * @description execute method
   * @param context QueueableContext
   */
  public void execute(QueueableContext context) {
    Map<String, User_Provisioning_Request__c> uprMap = UserProvisioningBeforeActions.getUPRRecords(
      updateUPRMap.keySet()
    );

    for (User_Provisioning_Request__c upr : uprMAP.values()) {
      upr.Requestor__r = new user(FederationIdentifier = upr.Requestor_UUID__c);
      upr.Status__c = (updateUPRMap.get(upr.Requestor_UUID__c)
        ? 'Completed'
        : 'Error');
    }

    List<Database.SaveResult> updateUPRResult = Database.update(
      uprMap.values(),
      false
    );
  }
}