force-app/main/default/objects/CFMS_Migrated_Document__c/CFMS_Migrated_Document__c.object-meta.xml
<CustomObject>
    <description>Custom object to store migrated CFMS documents, not the documents themselves but links to them in EDRM.</description>
    <label>CFMS Migrated Document</label>
    <nameField>
        <displayFormat>CFMSDoc-{00000000}</displayFormat>
        <label>CFMS Migrated Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CFMS Migrated Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CFMS_Migrated_Document__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_EDRM</complianceGroup>
    <description>Description of the document, usually who uploaded it and when.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/idr/CFMSMigratedDocumentTriggerHandler.cls
/**
 * @author Olivier Saier
 * @since 06/2021
 * @description  CFMSMigratedDocumentTriggerHandler is the handler class for CFMS_Migrated_Case__c Trigger which extends Lib_TriggerHandler the trigger framework used.
 */
public with sharing class CFMSMigratedDocumentTriggerHandler extends Lib_TriggerHandler {
  /**
   * @description Constructor to call the trigger framework
   * which will call the appropriate methods such as onBeforeInsert etc.
   */
  public CFMSMigratedDocumentTriggerHandler() {
    super();
  }

  /**
   * @description onBeforeDelete to prevent cdeletion
   */
  public override void onBeforeDelete() {
    for (
      CFMS_Migrated_Document__c record : (List<CFMS_Migrated_Document__c>) records
    ) {
      record.addError('You may not delete CFMS migrated documents.');
    }
  }

  /**
   * @description onBeforeInsert to handle before insert trigger actions.
   */
  public override void onBeforeInsert() {
    for (
      CFMS_Migrated_Document__c record : (List<CFMS_Migrated_Document__c>) records
    ) {
      record.Description__c = TextUtils.maskData(record.Description__c);
    }
  }

  /**
   * @description onBeforeUpdate to handle before update trigger actions.
   * @param oldMap Old trigger values
   */
  public override void onBeforeUpdate(Map<Id, SObject> oldMap) {
    for (
      CFMS_Migrated_Document__c record : (List<CFMS_Migrated_Document__c>) records
    ) {
      record.Description__c = TextUtils.maskData(record.Description__c);
    }
  }
}