force-app/main/default/objects/UUID_Log_Entry__c/UUID_Log_Entry__c.object-meta.xml
<CustomObject>
    <description>Used to generate and capture UUID values when Salesforce is making requests to external systems</description>
    <label>UUID Log Entry</label>
    <nameField>
        <label>UUID Log Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UUID Log Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UUID_Log_Entry__c/fields/Hash_Payload__c.field-meta.xml
<CustomField>
    <fullName>Hash_Payload__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Hash value generated while making request</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Hash Payload</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UUID_Log_Entry__c/fields/Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Reference_Id__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Record Id specific to use case</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Reference Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UUID_Log_Entry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Status of UUID</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Attempted Retry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UUID_Log_Entry__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>List of use cases based on functionalities</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BOH - Credit Referral - Reassess</fullName>
            </value>
            <value>
                <fullName>BOH - Credit Referral - Referral Outcome</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UUID_Log_Entry__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The UUID value created based on request made</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UUID_Log_Event__e/UUID_Log_Event__e.object-meta.xml
<CustomObject>
    <label>UUID Log Event</label>
    <pluralLabel>UUID Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/UUID_Log_Event__e/fields/Hash_Payload__c.field-meta.xml
<CustomField>
    <fullName>Hash_Payload__c</fullName>
    <description>Hash value generated while making request</description>
    <label>Hash_Payload</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UUID_Log_Event__e/fields/Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Reference_Id__c</fullName>
    <description>Record Id specific to use case</description>
    <label>Reference_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UUID_Log_Event__e/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of UUID</description>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UUID_Log_Event__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>List of use cases based on functionalities</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UUID_Log_Event__e/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>The UUID value created based on request made</description>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UUIDLog.cls
/**
 * @author cruzb
 * @since July 2023
 * @description object class for UUID Logs
 * @group Services
 */
public with sharing class UUIDLog {
  /**
   * @description uuid
   */
  public String uuid { get; set; }

  /**
   * @description exists flag
   */
  private Boolean exists { get; set; }

  /**
   * @description hashPayload
   */
  private String hashPayload { get; set; }

  /**
   * @param payload payload to hash
   * @description constructor
   */
  public UUIDLog(String payload) {
    this.hashPayload = CommonUtil.hashValue(payload);

    if (!PermissionUtils.canQuery('UUID_Log_Entry__c')) {
      throw new AuraHandledException('Insufficient Permissions');
    }

    UUID_Log_Entry__c[] uuid = [
      SELECT UUID__c
      FROM UUID_Log_Entry__c
      WHERE
        Hash_Payload__c = :this.hashPayload
        AND Status__c = :GetHelpConstants.IN_PROGRESS_STATUS
    ];
    if (uuid.size() > 0) {
      this.uuid = uuid[0].UUID__c;
      this.exists = true;
    } else {
      this.uuid = CommonUtil.generateUUID();
      this.exists = false;
    }
  }

  /**
   * @param recordId for reference
   * @param caseType for case record type
   * @description creates a UUID log record
   */
  public void insertUUID(String recordId, String caseType) {
    if (this.exists) {
      return;
    }
    try {
      PlatformEventUtils.publishEvents(
        new List<UUID_Log_Event__e>{
          new UUID_Log_Event__e(
            Status__c = GetHelpConstants.IN_PROGRESS_STATUS,
            UUID__c = this.uuid,
            Hash_Payload__c = this.hashPayload,
            Reference_Id__c = recordId,
            Type__c = caseType
          )
        }
      );
    } catch (Exception e) {
      Logger.error('Error creating UUID Log Entry: ' + e.getMessage());
      Logger.saveLog();
      throw e;
    }
  }

  /**
   * @param payload payload to attach UUID to
   * @description attach uuid in payload
   * @return serialized string
   */
  public String attachUUID(String payload) {
    Map<String, Object> objectMap = (Map<String, Object>) JSON.deserializeUntyped(
      payload
    );

    objectMap.put('requestId', this.uuid);

    return JSON.serialize(objectMap);
  }
}