force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/FinancialAccountUIConfiguration__mdt.object-meta.xml
<CustomObject>
    <label>FinancialAccountUIConfiguration</label>
    <pluralLabel>FinancialAccountUIConfigurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Type of the financial account</description>
    <label>Account Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Savings</fullName>
                <default>true</default>
                <label>Savings</label>
            </value>
            <value>
                <fullName>Non Savings</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/fields/Balance_Title__c.field-meta.xml
<CustomField>
    <fullName>Balance_Title__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Balance Title for each account.</description>
    <label>Balance Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/fields/Ownership_Type__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Type__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Owner ship type on Financial Account</description>
    <label>Ownership Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
                <default>true</default>
                <label>Single</label>
            </value>
            <value>
                <fullName>Multi-party</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Product code from Product2 table</description>
    <label>Product Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/fields/Section_Header_Title__c.field-meta.xml
<CustomField>
    <fullName>Section_Header_Title__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Header title to be displayed on LWC</description>
    <label>Section Header Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/fields/Show_Goals__c.field-meta.xml
<CustomField>
    <fullName>Show_Goals__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Controls whether to show goals on Salesforce UI</description>
    <label>Show Goals</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Sort Order for LWC component to display the data.</description>
    <label>Sort Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__FinancialAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccountNumber__c</fullName>
    <complianceGroup>Source_CTM;Integrity_Trusted</complianceGroup>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__ProductName__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ProductName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Insurance policy product name.</description>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Financial Account Products</relationshipLabel>
    <relationshipName>FinancialAccountProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Calculates if account ownership is single or multiparty</description>
    <formula>IF(Additional_Owner_Count__c  &gt;= 1,&quot;Multi-party&quot;, &quot;Single&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ownership</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/FinServ__FinancialAccountRole__c.object-meta.xml
<CustomObject>
    <description>Represents the role occupied by a person or organizational entity that is involved with a financial account, such as a beneficiary or trustee.</description>
    <label>Financial Account Role</label>
    <nameField>
        <displayFormat>FAR-{000000000}</displayFormat>
        <label>Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>field that calculates account type</description>
    <formula>CASE( Product_Code_Display__c ,
 &apos;DDA&apos;,&apos;Deposit Accounts&apos;,
 &apos;FM&apos;,&apos;Deposit Accounts&apos;,
 &apos;SSI&apos;,&apos;Deposit Accounts&apos;,
 &apos;RSV&apos;,&apos;Deposit Accounts&apos;,
 &apos;CDA&apos;,&apos;Deposit Accounts&apos;,
 &apos;ILS&apos;,&apos;Loan Accounts&apos;,
 &apos;PCA&apos;,&apos;Credit Cards&apos;,
 &apos;PCB&apos;,&apos;Credit Cards&apos;,
 &apos;OLL&apos;,&apos;Other Limits and Liabilities&apos;,
 &apos;PTF&apos;,&apos;Other Limits and Liabilities&apos;,
 &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__Active__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Active__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy - Personal Information</complianceGroup>
    <defaultValue>true</defaultValue>
    <description>Indicates whether the organizational entity or person currently occupies this role.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy - Personal Information</complianceGroup>
    <description>Financial account that this role is related to.</description>
    <label>Financial Account</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelatedAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the organizational entity that is involved with the financial account.</description>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>This field holds the Ownership of the of the customer for the Financial Account</description>
    <formula>FinServ__FinancialAccount__r.Ownership__c</formula>
    <label>Ownership</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ANZ_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>ANZ_Product_Code__c</fullName>
    <externalId>true</externalId>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FinancialAccountControllerTest.cls
/**
 *
 * @author Kopal Goswami
 * @since 2025
 * @description FinancialAccountControllerTest is the test class for UnifiedFinancialAccountController class
 */
@isTest
public with sharing class FinancialAccountControllerTest {
  private static final Id FAKER_ACCOUNT_ID = Lib_FakeIdGenerator.getMockId(
    Account.getSObjectType()
  );

  static Lib_MockProvider finAccRepoMock;
  static Lib_MockProvider dmlRepoMock;

  static void registerMocks() {
    finAccRepoMock = Lib_MockProvider.forType(FinancialAccountRepository.class);
    dmlRepoMock = Lib_MockProvider.forType(DmlRepository.class);
  }

  /**
   * @description Add required PermissionSet
   */
  @testSetup
  public static void setup() {
    TestUtil.addPermissionSets(
      new List<String>{
        'Accounts_Goals_Read_Only',
        'View_Card_Details',
        'View_Transaction_History'
      }
    );
  }

  @isTest
  public static void testGetFinancialAccountFabricPositive() {
    User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
    System.runAs(thisUser) {
      registerMocks();
      finAccRepoMock.mock('getFinAccountList', createMockFinancialAccount());

      finAccRepoMock.mock(
        'fetchFinancialAccountUIConfigInfo',
        mockfinAccountUiConfig()
      );

      Test.startTest();
      Map<String, Object> processedfinancialAccounts = FinancialAccountController.getFinancialAccountFabric(
        '12345',
        null
      );
      Test.stopTest();

      Assert.isNotNull(
        processedfinancialAccounts.get('groupedAccounts'),
        'Financial Accounts are grouped and sorted'
      );
    }
  }

  @isTest
  public static void testGetFinancialAccountInstancePositive() {
    FinServ__FinancialAccount__c mockfinAccountFromDatabase = createMockFinancialAccount()[0];
    Test.startTest();
    UnifiedFinancialAccountModel.AccountList finAccountRecord = FinancialAccountController.getFinancialAccountInstance(
      mockFabricFinancialAccounts[0],
      mockfinAccountFromDatabase,
      mockProductCodeOwnershipToFinAccount()
    );
    Test.stopTest();

    Assert.areEqual(
      finAccountRecord.finserv_ownership,
      'Single',
      'Ownership should be updated with the database financial Account'
    );
  }

  @isTest
  public static void testGetFinancialAccountInstanceNegative() {
    Test.startTest();
    UnifiedFinancialAccountModel.AccountList finAccountRecord = FinancialAccountController.getFinancialAccountInstance(
      mockFabricFinancialAccounts[0],
      null,
      mockProductCodeOwnershipToFinAccount()
    );
    Test.stopTest();

    Assert.isNull(finAccountRecord.Id, 'Id node should be null');
  }

  @isTest
  public static void testGetFinancialAccountInstanceToUpdatePositive() {
    FinServ__FinancialAccount__c mockfinAccountFromDatabase = createMockFinancialAccount()[0];
    Id finAccId = mockfinAccountFromDatabase.id;

    Test.startTest();
    FinServ__FinancialAccount__c finAccountToUpdate = FinancialAccountController.getFinancialAccountInstanceToUpdate(
      mockFabricFinancialAccounts[0],
      mockfinAccountFromDatabase
    );
    Test.stopTest();

    Assert.areEqual(
      finAccountToUpdate.Id,
      finAccId,
      'Id node should be updated with the database financial Account Id'
    );
  }

  @isTest
  public static void testGetFinancialAccountInstanceToUpdateNegative() {
    FinServ__FinancialAccount__c mockfinAccountFromDatabase = createMockFinancialAccount()[0];

    Test.startTest();
    FinServ__FinancialAccount__c finAccountToUpdate = FinancialAccountController.getFinancialAccountInstanceToUpdate(
      mockFabricFinancialAccounts[2],
      mockfinAccountFromDatabase
    );
    Test.stopTest();

    Assert.isNull(
      finAccountToUpdate.FinServ__CloseDate__c,
      'Close date node should be null'
    );
  }

  @isTest
  public static void testFilterOutNonHomeLoanAccountsPositive() {
    registerMocks();

    finAccRepoMock.mock(
      'fetchFinancialAccountUIConfigInfo',
      mockfinAccountUiConfig()
    );

    Test.startTest();
    List<UnifiedFinancialAccountModel.AccountList> homeloanAccountList = FinancialAccountController.filterOutNonHomeLoanAccounts(
      mockFabricFinancialAccounts
    );
    Test.stopTest();

    Assert.isTrue(
      homeloanAccountList.size() > 0,
      'Home Loan Financial Accounts are filtered'
    );
  }

  @isTest
  public static void testGetFinancialAccountDBPositive() {
    registerMocks();

    finAccRepoMock.mock(
      'getAllAccountNumberPerOwner',
      mockFinancialAccountRoles()
    );

    finAccRepoMock.mock('getFinacialAccounts', createMockFinancialAccount());

    finAccRepoMock.mock(
      'fetchFinancialAccountUIConfigInfo',
      mockfinAccountUiConfig()
    );

    Test.startTest();
    Map<String, Object> processedfinancialAccountsDB = FinancialAccountController.getFinancialAccountDB(
      '12345',
      FAKER_ACCOUNT_ID
    );
    Test.stopTest();

    Assert.isTrue(
      processedfinancialAccountsDB.size() > 0,
      'Financial Accounts are grouped and sorted based on Database data'
    );
  }

  @isTest
  public static void testGetFinancialAccountDBNegative() {
    registerMocks();

    finAccRepoMock.mock(
      'getAllAccountNumberPerOwner',
      mockFinancialAccountRoles()
    );

    finAccRepoMock.mock(
      'getFinacialAccounts',
      new List<FinServ__FinancialAccount__c>()
    );

    finAccRepoMock.mock(
      'fetchFinancialAccountUIConfigInfo',
      mockfinAccountUiConfig()
    );

    Test.startTest();
    Map<String, Object> processedfinancialAccountsDB = FinancialAccountController.getFinancialAccountDB(
      '12345',
      FAKER_ACCOUNT_ID
    );
    Test.stopTest();

    Assert.areEqual(
      0,
      processedfinancialAccountsDB.size(),
      'No Financial accounts are received'
    );
  }

  @isTest
  public static void testFetchAllFinancialAccountsDBPositive() {
    registerMocks();
    finAccRepoMock.mock(
      'getAllAccountNumberPerOwner',
      mockFinancialAccountRoles()
    );

    finAccRepoMock.mock('getFinacialAccounts', createMockFinancialAccount());

    finAccRepoMock.mock(
      'fetchFinancialAccountUIConfigInfo',
      mockfinAccountUiConfig()
    );

    Test.startTest();
    List<UnifiedFinancialAccountModel.AccountList> convertedFinancialAccountsToJson = FinancialAccountController.fetchAllFinancialAccountsDB(
      FAKER_ACCOUNT_ID
    );
    Test.stopTest();

    Assert.areEqual(
      convertedFinancialAccountsToJson[0].finserv_ownership,
      'Single',
      'Financial account ownership is updated on the json node finserv_ownership'
    );
  }

  @isTest
  public static void testFetchAllFinancialAccountsDBNegative() {
    registerMocks();
    finAccRepoMock.mock(
      'getAllAccountNumberPerOwner',
      mockFinancialAccountRoles()
    );

    finAccRepoMock.mock(
      'getFinacialAccounts',
      new List<FinServ__FinancialAccount__c>()
    );

    finAccRepoMock.mock(
      'fetchFinancialAccountUIConfigInfo',
      mockfinAccountUiConfig()
    );

    Test.startTest();
    List<UnifiedFinancialAccountModel.AccountList> convertedFinancialAccountsToJson = FinancialAccountController.fetchAllFinancialAccountsDB(
      FAKER_ACCOUNT_ID
    );
    Test.stopTest();

    Assert.areEqual(
      0,
      convertedFinancialAccountsToJson.size(),
      'No Financial accounts are received'
    );
  }

  @isTest
  public static void testFetchOCVIdFromAccount() {
    Test.startTest();
    String ocvId = FinancialAccountController.fetchOCVIdFromAccount(
      FAKER_ACCOUNT_ID
    );
    Test.stopTest();
    Assert.isNull(
      ocvId,
      'Ocv Id should be null as we are passing fake record Id'
    );
  }

  /**
   * @description This method helps in providing the mock response from Fabric
   * @return Fabric financial accounts
   */
  private static List<UnifiedFinancialAccountModel.AccountList> mockFabricFinancialAccounts {
    get {
      String mockFabricFinancialAccountsResponse = [
          SELECT body
          FROM StaticResource
          WHERE Name = 'mock_FinancialAccountMappingv1'
        ]
        .body.toString();
      return UnifiedFinancialAccountModel.parse(
          mockFabricFinancialAccountsResponse
        )
        .accounts;
    }
  }

  private static List<FinancialAccountUIConfiguration__mdt> mockfinAccountUiConfig() {
    List<FinancialAccountUIConfiguration__mdt> mockMetaData = new List<FinancialAccountUIConfiguration__mdt>();
    FinancialAccountUIConfiguration__mdt dummyRecord1 = new FinancialAccountUIConfiguration__mdt(
      Product_Code__c = 'HOMELOAN1',
      Account_Type__c = 'Loan',
      Balance_Title__c = 'Loan Balance',
      Section_Header_Title__c = 'Loan',
      Sort_Order__c = 1,
      Ownership_Type__c = 'Single',
      Show_Goals__c = false
    );
    mockMetaData.add(dummyRecord1);

    FinancialAccountUIConfiguration__mdt dummyRecord2 = new FinancialAccountUIConfiguration__mdt(
      Product_Code__c = 'SAVING01',
      Account_Type__c = 'Savings',
      Balance_Title__c = 'Total Saved',
      Section_Header_Title__c = 'Savings',
      Sort_Order__c = 2,
      Ownership_Type__c = 'Single',
      Show_Goals__c = true
    );
    mockMetaData.add(dummyRecord2);

    return mockMetaData;
  }

  private static Map<String, FinancialAccountUIConfiguration__mdt> mockProductCodeOwnershipToFinAccount() {
    Map<String, FinancialAccountUIConfiguration__mdt> productCodeOwnershipToFinAccMap = new Map<String, FinancialAccountUIConfiguration__mdt>();
    for (
      FinancialAccountUIConfiguration__mdt finUIConfig : mockfinAccountUiConfig()
    ) {
      String key =
        finUIConfig.Product_Code__c +
        '-' +
        finUIConfig.Ownership_Type__c;
      if (!productCodeOwnershipToFinAccMap.containsKey(key)) {
        productCodeOwnershipToFinAccMap.put(key, finUIConfig);
      }
    }
    return productCodeOwnershipToFinAccMap;
  }

  private static List<FinServ__FinancialAccount__c> createMockFinancialAccount() {
    Id productId = Lib_FakeIdGenerator.getMockId(Product2.SObjectType);
    Product2 product = new Product2(
      Id = productId,
      Name = 'Test Product',
      ANZ_Product_Code__c = 'SAVING01'
    );
    Account testAccount = TestDataFactory.createPersonAccount('1111', false);
    testAccount.Id = FAKER_ACCOUNT_ID;
    List<FinServ__FinancialAccount__c> financialAccountsList = new List<FinServ__FinancialAccount__c>();
    FinServ__FinancialAccount__c finAccount1 = TestDataFactory.createFinancialAccountRecord(
      GetHelpConstants.SAVINGS_ACCOUNT_RT_ID,
      FAKER_ACCOUNT_ID,
      false
    );
    FinServ__FinancialAccount__c finAccount = (FinServ__FinancialAccount__c) TestUtil.setFields(
      finAccount1,
      new Map<String, Object>{ 'Ownership__c' => 'Single' }
    );
    finAccount.FinServ__ProductName__r = product;
    finAccount.FinServ__FinancialAccountNumber__c = '111111111';
    financialAccountsList.add(finAccount);
    return financialAccountsList;
  }

  private static List<FinServ__FinancialAccountRole__c> mockFinancialAccountRoles() {
    List<FinServ__FinancialAccountRole__c> finAccountRoleList = new List<FinServ__FinancialAccountRole__c>();

    FinServ__FinancialAccountRole__c finAccountRole = new FinServ__FinancialAccountRole__c();
    finAccountRole.FinServ__RelatedAccount__c = FAKER_ACCOUNT_ID;
    finAccountRole.FinServ__Active__c = true;
    finAccountRoleList.add(finAccountRole);

    return finAccountRoleList;
  }
}