force-app/main/default/objects/qualtrics__Survey_Response__c/qualtrics__Survey_Response__c.object-meta.xml
<CustomObject>
    <description>Object to help hold responses for Quick Starts, and custom Surveys built by end-users.</description>
    <label>Survey Response</label>
    <nameField>
        <label>Survey Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/qualtrics__Survey_Response__c/fields/Survey_Name__c.field-meta.xml
<CustomField>
    <fullName>Survey_Name__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Qualtrics</complianceGroup>
    <description>The name of the Survey eg. Customer Interaction/Join</description>
    <label>Survey Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/qualtrics__Survey_Response__c/fields/Survey_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Survey_Trigger__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information</complianceGroup>
    <description>If a case was a trigger for the survey, this will reflect this case</description>
    <label>Survey Trigger</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ccrm/CommercialSurveyResponseTriggerHandler.cls
/**
 * @author Nabia Nadir
 * @since 08/2024
 * @description  CommercialSurveyResponseTriggerHandler is the handler class for Survey Response Trigger which extends Lib_TriggerHandler the trigger framework used.
 */
public class CommercialSurveyResponseTriggerHandler extends Lib_TriggerHandler {
  private static final String SURVEY_TRIGGER = 'Commercial';
  private static final String SURVEY_NAME = 'A-Z Reviews';

  /**
   * @description Constructor to initialise Trigger Handler library
   */
  public CommercialSurveyResponseTriggerHandler() {
    super();
  }
  /**
   * @description Implementation of isValidRecord on Lib_TriggerHandler, returns a list of CCRM Interaction records
   * @param record record to check if relevant to the execution context
   * @return `Boolean` returns true if record is relevant, false if record is not relevant
   */
  public override Boolean isValidRecord(SObject record) {
    qualtrics__Survey_Response__c rec = (qualtrics__Survey_Response__c) record;
    return rec.Survey_Trigger__c == SURVEY_TRIGGER &&
      rec.Survey_Name__c == SURVEY_NAME;
  }
  /**
   * @description onBeforeInsert to handle before insert trigger actions.
   */
  public override void onBeforeInsert() {
    CommercialSurveyResponseActions.setFieldsForSurveyResponseOnInsert(records);
  }
}