force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__Balance__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Balance__c</fullName>
    <complianceGroup>Source_CTM;Integrity - Highly Trusted;Privacy - Personal Information</complianceGroup>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AccountBalancesController.cls
/**
 *
 * @author Peter Charalambous
 * @since 2020
 * @description AccountBalancesController is the apex side controller for the financialAccount LWC
 */
public with sharing class AccountBalancesController {
  /**
   * @description The Account Balances component uses this to fetch the record data to display.
   *
   * @param recordId the id of the financial account
   * @return List<FinServ__FinancialAccount__c>
   */
  @AuraEnabled
  public static List<FinServ__FinancialAccount__c> getBalances(Id recordId) {
    List<FinServ__FinancialAccount__c> financialAccount;
    if (FinServ__FinancialAccount__c.sObjectType.getDescribe().isQueryable()) {
      financialAccount = [
        SELECT Id, FinServ__Balance__c, LastModifiedDate
        FROM FinServ__FinancialAccount__c
        WHERE Id = :recordId
      ];
    }

    if (financialAccount.isEmpty()) {
      return null;
    }

    return financialAccount;
  }
}