force-app/main/default/objects/COBPrimaryIDDocument__c/COBPrimaryIDDocument__c.object-meta.xml
<CustomObject>
    <description>The details submitted for a primary document (licence or passport), including the original OCR extractions which may have been edited</description>
    <label>COB Primary ID Document</label>
    <nameField>
        <displayFormat>COBPID-{00000000}</displayFormat>
        <label>COB Primary ID Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>COB Primary ID Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/DateOfBirth__c.field-meta.xml
<CustomField>
    <fullName>DateOfBirth__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Temporal</complianceGroup>
    <description>Date of birth as submitted by the user</description>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>ExpiryDate__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>The expiry date as submitted by the user</description>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/IdDocumentType__c.field-meta.xml
<CustomField>
    <fullName>IdDocumentType__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>The primary form of ID chosen (licence, passport etc)</description>
    <label>Id Document Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/LicenceCardNumber__c.field-meta.xml
<CustomField>
    <fullName>LicenceCardNumber__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>The unique card number as submitted by the user (TOKENISED)</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Licence Card Number (Tokenised)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/LicenceCardNumberOCRClient__c.field-meta.xml
<CustomField>
    <fullName>LicenceCardNumberOCRClient__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>OCR values for Licence Card Number</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Licence Card Number OCR Client</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/LicenceCardNumberOCRServer__c.field-meta.xml
<CustomField>
    <fullName>LicenceCardNumberOCRServer__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Sensitive_Personal_Information;Source_Temporal</complianceGroup>
    <description>OCR values for Licence Card Number</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Licence Card Number OCR Server</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/LicenceNumber__c.field-meta.xml
<CustomField>
    <fullName>LicenceNumber__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Sensitive Personal Information;Source - Temporal</complianceGroup>
    <description>Licence number as submitted by the user (TOKENISED)</description>
    <label>Licence Number (Tokenised)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/LicenceNumberOCRClient__c.field-meta.xml
<CustomField>
    <fullName>LicenceNumberOCRClient__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Sensitive_Personal_Information;Source_Temporal</complianceGroup>
    <description>OCR values for Licence Number</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Licence Number OCR Client</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/LicenceNumberOCRServer__c.field-meta.xml
<CustomField>
    <fullName>LicenceNumberOCRServer__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>OCR values for Licence Number</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Licence Number OCR Server</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/PassportNumber__c.field-meta.xml
<CustomField>
    <fullName>PassportNumber__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Sensitive Personal Information;Source - Temporal</complianceGroup>
    <description>Passport number as submitted by the user (TOKENISED)</description>
    <label>Passport Number (Tokenised)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/PassportNumberOCRClient__c.field-meta.xml
<CustomField>
    <fullName>PassportNumberOCRClient__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Sensitive_Personal_Information;Source_Temporal</complianceGroup>
    <description>OCR values for Passport Number</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Passport Number OCR Client</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/PassportNumberOCRServer__c.field-meta.xml
<CustomField>
    <fullName>PassportNumberOCRServer__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>OCR values for Passport Number</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Passport Number OCR Server</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/models/DetokenizeRequestModelTest.cls
/**
 * @author Karen Valeriano
 * @since Jul 2024
 * @description test class for DetokenizeRequestModel class
 * @group Models
 */
@isTest
private with sharing class DetokenizeRequestModelTest {
  private static final String TOKEN_TRANSFORM_VALUE = 'fpe.personal-identifier';

  static COBPrimaryIDDocument__c licencePid = new COBPrimaryIDDocument__c(
    PersonaId__c = '000000000',
    IdDocumentType__c = 'Licence',
    LicenceNumber__c = 'LN123123',
    LicenceNumberOCRClient__c = 'LN123123Client',
    LicenceNumberOCRServer__c = 'LN123123Server',
    LicenceCardNumber__c = 'LCN456456',
    LicenceCardNumberOCRClient__c = 'LCN456456Client',
    LicenceCardNumberOCRServer__c = 'LCN456456Server',
    DateOfBirth__c = Date.today(),
    ExpiryDate__c = Date.today()
  );
  static COBPrimaryIDDocument__c passportPid = new COBPrimaryIDDocument__c(
    PersonaId__c = '000000000',
    IdDocumentType__c = 'Passport',
    PassportNumber__c = 'P12345',
    PassportNumberOCRClient__c = 'P12345Client',
    PassportNumberOCRServer__c = 'P12345Server',
    DateOfBirth__c = Date.today(),
    ExpiryDate__c = Date.today()
  );

  @isTest
  static void testConstructorWithNullOCRServer() {
    licencePid.LicenceCardNumberOCRServer__c = null;

    Set<String> fieldValues = COBPIDViewAndEditController.getTokenizedFieldValues(
      licencePid,
      COBPIDViewAndEditController.LICENCE_TOKENIZED_FIELDS
    );

    Test.startTest();
    DetokenizeRequestModel tokenizedValues = new DetokenizeRequestModel(
      fieldValues,
      COBPrimaryIDDocumentModel.TOKEN_TRANSFORM_VALUE
    );
    Test.stopTest();

    Integer expected =
      COBPIDViewAndEditController.LICENCE_TOKENIZED_FIELDS.size() - 1;
    System.assertEquals(
      expected,
      tokenizedValues.values.size(),
      'Should tokenized ' + expected + ' fields.'
    );
  }

  @isTest
  static void testConstructorWithParamsLicence() {
    Set<String> fieldValues = COBPIDViewAndEditController.getTokenizedFieldValues(
      licencePid,
      COBPIDViewAndEditController.LICENCE_TOKENIZED_FIELDS
    );

    Test.startTest();
    DetokenizeRequestModel model = new DetokenizeRequestModel(
      fieldValues,
      COBPrimaryIDDocumentModel.TOKEN_TRANSFORM_VALUE
    );
    Test.stopTest();

    Assert.areEqual(
      COBPIDViewAndEditController.LICENCE_TOKENIZED_FIELDS.size(),
      model.values.size(),
      'Should tokenized ' +
        COBPIDViewAndEditController.LICENCE_TOKENIZED_FIELDS.size() +
        ' fields.'
    );
  }

  @isTest
  static void testConstructorWithParamsPassport() {
    Set<String> fieldValues = COBPIDViewAndEditController.getTokenizedFieldValues(
      passportPid,
      COBPIDViewAndEditController.PASSPORT_TOKENIZED_FIELDS
    );

    Test.startTest();
    DetokenizeRequestModel model = new DetokenizeRequestModel(
      fieldValues,
      COBPrimaryIDDocumentModel.TOKEN_TRANSFORM_VALUE
    );
    Test.stopTest();

    Assert.areEqual(
      COBPIDViewAndEditController.PASSPORT_TOKENIZED_FIELDS.size(),
      model.values.size(),
      'Should tokenized ' +
        COBPIDViewAndEditController.PASSPORT_TOKENIZED_FIELDS.size() +
        ' fields.'
    );
  }
}