force-app/main/default/objects/ContentVersion/fields/Date_of_Document__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Document__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Non-mandatory date field to capture ‘Date of Document’ (e.g. date email was sent, or date of report - not the date the file was uploaded to CMOS as this is already captured).</description>
    <inlineHelpText>e.g. date email was sent, or date of report - not the date the file was uploaded to CMOS as this is already captured</inlineHelpText>
    <label>Date of Document</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Document_Category__c.field-meta.xml
<CustomField>
    <fullName>Document_Category__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <label>Document Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Statements</fullName>
            </value>
            <value>
                <fullName>AFCA Correspondence</fullName>
            </value>
            <value>
                <fullName>AFCA Decision</fullName>
            </value>
            <value>
                <fullName>ANZ Letter/Email</fullName>
            </value>
            <value>
                <fullName>CAD Approval</fullName>
            </value>
            <value>
                <fullName>Customer Acceptance</fullName>
            </value>
            <value>
                <fullName>Customer Letter/Email</fullName>
            </value>
            <value>
                <fullName>Evidence of Implementation</fullName>
            </value>
            <value>
                <fullName>File Note</fullName>
            </value>
            <value>
                <fullName>Final Response to Customer</fullName>
            </value>
            <value>
                <fullName>Internal Correspondence</fullName>
            </value>
            <value>
                <fullName>Statement of Financial Position</fullName>
            </value>
            <value>
                <fullName>Third Party Authority</fullName>
            </value>
            <value>
                <fullName>CFaaS File</fullName>
            </value>
            <value>
                <fullName>DAON File</fullName>
            </value>
            <value>
                <fullName>DAON TrustX File</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Document_Flag__c.field-meta.xml
<CustomField>
    <fullName>Document_Flag__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>document flag</description>
    <inlineHelpText>Help Identify the sensitivity of the document</inlineHelpText>
    <label>Document Flag</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Draft</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Privileged</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Working draft</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Final version</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Attached to the incorrect case file</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Duplicate</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Sensitive </label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Medical Information</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Not to be exchanged</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Party_who_sent_created_file__c.field-meta.xml
<CustomField>
    <fullName>Party_who_sent_created_file__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <label>Party who sent/created file</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wealth Product Manufacturer</fullName>
            </value>
            <value>
                <fullName>AFCA</fullName>
            </value>
            <value>
                <fullName>Small Business Ombudsman</fullName>
            </value>
            <value>
                <fullName>Office of the Australian Information Commissioner (OAIC)</fullName>
            </value>
            <value>
                <fullName>State Tribunal</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Nominated 3rd Party Representative of Customer</fullName>
            </value>
            <value>
                <fullName>Internal business unit</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/File.recordType-meta.xml
<RecordType>
    <fullName>File</fullName>
    <active>true</active>
    <description>Default record type for files</description>
    <label>File</label>
</RecordType>

force-app/main/default/classes/idr/IDRFilesRelatedListControllerTest.cls
/**
 * @author Himabindu Nekkanti
 * @since  11/2020
 * @description TestIDRFilesRelatedListController is the test class for  IDRFilesRelatedListController.
 * @group IDR(Internal Dispute Resolution)
 */
@isTest
public class IDRFilesRelatedListControllerTest {
  /**
   * @description setupData sets up the test data required for the test class.
   */
  @testSetup
  static void setupData() {
    case c = new case(
      subject = 'test subject',
      RecordTypeId = IDRConstants.NON_CUSTOMER_COMPLAINT_RT_ID
    );
    insert c;
    contentversion cv = new contentversion();
    cv.Title = 'loan.txt';
    cv.PathOnClient = 'loan.txt';
    cv.VersionData = blob.valueOf('Test file Search - idrsearch123');
    cv.Document_Flag__c = '1;7';
    cv.Date_of_Document__c = datetime.now();
    cv.Party_who_sent_created_file__c = 'Internal business unit';
    cv.Document_Category__c = 'Internal Correspondence';
    cv.FirstPublishLocationId = c.id;
    cv.RecordTypeId = IDRConstants.COMPLAINT_FILE_RT_ID;
    insert cv;
  }
  /**
   * @description getCaseRelatedFilesTest covers the functionality of getCaseRelatedFiles method
   */
  @isTest
  static void getCaseRelatedFilesTest() {
    case c = new case();
    c = [SELECT id FROM case LIMIT 1];
    list<IDRFilesRelatedListdata> dataList = new List<IDRFilesRelatedListdata>();
    dataList = IDRFilesRelatedListController.getCaseRelatedFiles(c.id);
    system.assertEquals(1, datalist.size());
  }
  /**
   * @description searchFileContentTest covers the functionality of searchFileContent method
   */
  @isTest
  static void searchFileContentTest() {
    list<string> testSearchList = new List<string>();
    testSearchList.add('Test');

    contentversion cv = new contentversion();
    cv = [SELECT contentdocumentId FROM contentversion LIMIT 1];
    list<id> docIdList = new List<id>();
    docIdlist.add(cv.ContentDocumentId);

    list<string> retlist1 = new List<string>();
    retlist1 = IDRFilesRelatedListController.searchFilesContent(
      testSearchList,
      docIdList
    );

    list<string> retlist2 = new List<string>();
    testSearchList.add('idrsearch123');
    retlist2 = IDRFilesRelatedListController.searchFilesContent(
      testSearchList,
      docIdList
    );
    //salesforce test class limitation- sosl will always return zero items when executed from test class
    //https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_testing_SOSL.htm
    system.assertEquals(0, retlist1.size());
    system.assertEquals(0, retlist2.size());
  }
}