force-app/main/default/objects/Quality_Assessment__c/Quality_Assessment__c.object-meta.xml
<CustomObject>
    <label>Quality Assessment</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Quality Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Assessment__c/fields/Advice_Best_Interest_Duty__c.field-meta.xml
<CustomField>
    <fullName>Advice_Best_Interest_Duty__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Advice supplement assessment question:  Best Interests Duty</description>
    <label>Best interests duty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QA_V2_Ratings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Advice_Customer_understanding_of_scope__c.field-meta.xml
<CustomField>
    <fullName>Advice_Customer_understanding_of_scope__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Advice supplement assessment question:  Customer understanding of scope</description>
    <label>Customer understanding of scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QA_V2_Ratings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Advice_Decline_advice_and_refer__c.field-meta.xml
<CustomField>
    <fullName>Advice_Decline_advice_and_refer__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Advice supplement assessment question:  Decline advice and refer</description>
    <label>Decline advice and refer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QA_V2_Ratings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Advice_Define_Scope__c.field-meta.xml
<CustomField>
    <fullName>Advice_Define_Scope__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Advice supplement assessment question:  Define Scope</description>
    <label>Define scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QA_V2_Ratings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Advice_Dispute_Resolution__c.field-meta.xml
<CustomField>
    <fullName>Advice_Dispute_Resolution__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Advice supplement assessment question: Dispute Resolution</description>
    <label>Dispute resolution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QA_V2_Ratings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Advice_Fact_Find__c.field-meta.xml
<CustomField>
    <fullName>Advice_Fact_Find__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Advice supplement assessment question: Fact Find</description>
    <label>Fact find</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QA_V2_Ratings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Advice_Incomplete_Inaccurate_warning__c.field-meta.xml
<CustomField>
    <fullName>Advice_Incomplete_Inaccurate_warning__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Advice supplement assessment question:  Incomplete / Inaccurate Warning</description>
    <label>Incomplete / inaccurate warning</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QA_V2_Ratings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Advice_Initial_Contact__c.field-meta.xml
<CustomField>
    <fullName>Advice_Initial_Contact__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Advice supplement assessment question:  Initial Contact</description>
    <label>Initial contact</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QA_V2_Ratings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Advice_Limit_scope_of_advice__c.field-meta.xml
<CustomField>
    <fullName>Advice_Limit_scope_of_advice__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Advice supplement assessment question:  Limit scope of advice</description>
    <label>Limit scope of advice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QA_V2_Ratings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Advice_Substantive_Advice_OFSN__c.field-meta.xml
<CustomField>
    <fullName>Advice_Substantive_Advice_OFSN__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Advice supplement assessment question:  Substantive Advice, OFSN</description>
    <label>Substantive advice, OFSN</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QA_V2_Ratings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/CN_Checklist__c.field-meta.xml
<CustomField>
    <fullName>CN_Checklist__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Case notes question: Checklist (record of advice)</description>
    <label>Case notes - checklist</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QA_V2_Ratings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/CN_Customers_Focus__c.field-meta.xml
<CustomField>
    <fullName>CN_Customers_Focus__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Case notes question: Customer&apos;s Focus (record of advice)</description>
    <label>Case notes - customer&apos;s focus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QA_V2_Ratings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/CN_Fact_Find__c.field-meta.xml
<CustomField>
    <fullName>CN_Fact_Find__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Case notes question: Fact Find (record of advice)</description>
    <label>Case notes - fact find</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QA_V2_Ratings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/CN_OFSN__c.field-meta.xml
<CustomField>
    <fullName>CN_OFSN__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Case notes question: OFSN (record of advice)</description>
    <label>Case notes - OFSN</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QA_V2_Ratings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/CN_Out_of_Scope__c.field-meta.xml
<CustomField>
    <fullName>CN_Out_of_Scope__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Case notes question: Out of Scope (record of advice)</description>
    <label>Case notes - out of scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QA_V2_Ratings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/CN_Scope_Provided__c.field-meta.xml
<CustomField>
    <fullName>CN_Scope_Provided__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Case notes question: Scope Provided (record of advice)</description>
    <label>Case notes - scope provided</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QA_V2_Ratings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/CN_Substantive_Advice__c.field-meta.xml
<CustomField>
    <fullName>CN_Substantive_Advice__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Case notes question: Substantive Advice (record of advice)</description>
    <label>Case notes - substantive advice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QA_V2_Ratings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Connection_and_Trust__c.field-meta.xml
<CustomField>
    <fullName>Connection_and_Trust__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Connection and Trust outcome to be captured by the user based on the call review</description>
    <label>Connection and Trust</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Evaluation_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Quality_Assessment_Rating</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Discover_and_Align__c.field-meta.xml
<CustomField>
    <fullName>Discover_and_Align__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Discover and Align outcome to be captured by the user based on the call review</description>
    <label>Discover and Align</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Evaluation_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Quality_Assessment_Rating</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Energy_and_Adaptability__c.field-meta.xml
<CustomField>
    <fullName>Energy_and_Adaptability__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Energy and Adaptability outcome to be captured by the user based on the call review</description>
    <label>Energy and Adaptability</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Evaluation_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Quality_Assessment_Rating</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Key_scoping_and_disclaimers__c.field-meta.xml
<CustomField>
    <fullName>Key_scoping_and_disclaimers__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Advice supplement assessment question:  Key scoping and disclaimers</description>
    <label>Key scoping and disclaimers</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QA_V2_Ratings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Identification/Reference number of customer/non-customer activity being assessed (that is not a case or Interaction)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The different status the QA progresses through</description>
    <inlineHelpText>Status of Quality Evaluation</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
                <default>true</default>
                <label>Unassigned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>A dependent picklist based on status for &quot;referred and complete&quot;</description>
    <label>Sub-Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compliance Review</fullName>
            </value>
            <value>
                <fullName>Evaluation Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn/Not Required</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Assessment__c/recordTypes/ANZ_Plus_Governance_Lending_Evaluation.recordType-meta.xml
<RecordType>
    <fullName>ANZ_Plus_Governance_Lending_Evaluation</fullName>
    <active>true</active>
    <description>Governance - Lending Evaluation</description>
    <label>ANZ Plus Governance - Lending Evaluation</label>
</RecordType>

force-app/main/default/globalValueSets/QA_V2_Ratings.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Effective</fullName>
    </customValue>
    <customValue>
        <fullName>Almost there</fullName>
    </customValue>
    <customValue>
        <fullName>Requirements not met</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <description>Values used in QA V2 Ratings</description>
    <masterLabel>QA V2 Ratings</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Quality_Assessment_Rating.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Outstanding</fullName>
    </customValue>
    <customValue>
        <fullName>Effective</fullName>
    </customValue>
    <customValue>
        <fullName>Almost There</fullName>
    </customValue>
    <customValue>
        <fullName>Not There Yet</fullName>
    </customValue>
    <customValue>
        <fullName>Did Not Meet Expectations</fullName>
    </customValue>
    <customValue>
        <fullName>Exceeded Expectations</fullName>
    </customValue>
    <customValue>
        <fullName>Met Expectations</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
        <isActive>false</isActive>
        <label>N/A</label>
    </customValue>
    <description>Used by multiple fields on Quality Assessment object</description>
    <masterLabel>Quality Assessment Rating</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LendingEvaluationActionsTest.cls
/**
 * @author Hrushikesh
 * @since 14/2025
 * @description Test class for LendingEvaluationActions.
 */
@isTest
public with sharing class LendingEvaluationActionsTest {
  private static Lib_MockProvider dmlRepoMock;
  private static Lib_MockProvider qaRepoMock;

  private static final String REQUIREMENTS_NOT_MET = 'Requirements not met';
  private static final String ALMOST_THERE = 'Almost there';
  private static final String EFFECTIVE = 'Effective';
  private static final String REQUIREMENTS_MET = 'Requirements Met';
  private static final String NA_VALUE = 'N/A';
  private static final String ALMOSTTHERE = 'Almost There';
  private static final String NOT_THERE_YET = 'Not There Yet';
  private static final String OUTSTANDING = 'Outstanding';
  private static final String REFERENCE_VALUE = 'TestRef';
  private static final String REQUIREMENT_NOT_MEANT_PROCESS_ONLY = 'Requirements Not Met (Process only)';
  private static final String REQUIREMENT_NOT_MEANT_COMPLIANCE = 'Requirements Not Met (Compliance)';
  private static final String REQUIREMENT_MET = 'Requirements Met';
  private static final Id LENDING_RT_ID = QueryRT.of(
      Quality_Assessment__c.SObjectType
    )
    .getId('ANZ_Plus_Governance_Lending_Evaluation');

  private static final Id FAKER_QA_ASSESS_RECORD_ID = Lib_FakeIdGenerator.getMockId(
    Quality_Assessment__c.getSObjectType()
  );

  private static final Id FAKER_ACCOUNT_RECORD_ID = Lib_FakeIdGenerator.getMockId(
    Account.getSObjectType()
  );

  private static final Id FAKER_RLA_RECORD_ID = Lib_FakeIdGenerator.getMockId(
    ResidentialLoanApplication.getSObjectType()
  );

  static void registerMocks() {
    dmlRepoMock = Lib_MockProvider.forType(DmlRepository.class);
    qaRepoMock = Lib_MockProvider.forType(QualityAssessmentRepository.class)
      .mock('getRlaByIds', returnGetRlaByIds())
      .mock('getQAShareRecords', returnQAShareToDelete())
      .mock('getRlaByCustomer', new List<AggregateResult>());
  }

  private static List<Quality_Assessment__c> getQARecords() {
    List<Quality_Assessment__c> records = new List<Quality_Assessment__c>();
    Quality_Assessment__c qa = new Quality_Assessment__c();
    qa.Advice_Initial_Contact__c = REQUIREMENTS_NOT_MET;
    qa.Advice_Define_Scope__c = ALMOST_THERE;
    qa.Advice_Customer_understanding_of_scope__c = ALMOST_THERE;
    qa.Key_scoping_and_disclaimers__c = ALMOST_THERE;
    qa.Advice_Limit_scope_of_advice__c = ALMOST_THERE;
    qa.Advice_Decline_advice_and_refer__c = ALMOST_THERE;
    qa.Advice_Substantive_Advice_OFSN__c = EFFECTIVE;
    qa.Advice_Fact_Find__c = EFFECTIVE;
    qa.CN_Fact_Find__c = EFFECTIVE;
    qa.Advice_Best_Interest_Duty__c = EFFECTIVE;
    qa.Advice_Dispute_Resolution__c = ALMOST_THERE;
    qa.Advice_Incomplete_Inaccurate_warning__c = NA_VALUE;
    qa.CN_Customers_Focus__c = NA_VALUE;
    qa.CN_Substantive_Advice__c = NA_VALUE;
    qa.CN_Out_of_Scope__c = NA_VALUE;
    qa.CN_OFSN__c = NA_VALUE;
    qa.CN_Scope_Provided__c = NA_VALUE;
    qa.Status__c = 'Complete';
    qa.Sub_Status__c = 'Evaluation Completed';
    qa.CN_Checklist__c = NA_VALUE;
    qa.RecordTypeId = LENDING_RT_ID;
    qa.Reference__c = REFERENCE_VALUE;
    qa.Connection_and_Trust__c = EFFECTIVE;
    qa.Energy_and_Adaptability__c = EFFECTIVE;
    qa.Discover_and_Align__c = EFFECTIVE;
    qa.Actions_and_Momentum__c = EFFECTIVE;
    qa.Accountability_and_Next_Steps__c = EFFECTIVE;
    qa.Id = FAKER_QA_ASSESS_RECORD_ID;
    qa.Interaction_Owner__c = UserInfo.getUserId();
    qa.Serviceability_Outcome__c = REQUIREMENT_MET;
    qa.Income_Serviceability_Outcome__c = REQUIREMENT_MET;
    qa.Expenses_Serviceability_Outcome__c = REQUIREMENT_MET;
    qa.Debts_Serviceability_Outcome__c = REQUIREMENT_MET;
    qa.Conduct_Outcome__c = REQUIREMENT_MET;
    qa.Purpose_of_Loan_Outcome__c = REQUIREMENT_MET;
    qa.Collateral_Valuation_Outcome__c = REQUIREMENT_MET;
    qa.Material_Change_Outcome__c = REQUIREMENT_MET;
    qa.Hypercare_Focus_Area_Outcome__c = REQUIREMENT_MET;
    qa.Other__c = REQUIREMENT_MET;
    qa.Case_Notes_Outcome__c = REQUIREMENT_MET;
    qa.Application_ID__c = FAKER_RLA_RECORD_ID;
    qa.Application_ID__r = new ResidentialLoanApplication(
      AccountId = FAKER_ACCOUNT_RECORD_ID
    );
    records.add(qa);
    return records;
  }

  private static Map<Id, Quality_Assessment__c> getOldQARecords() {
    Map<Id, Quality_Assessment__c> oldMap = new Map<Id, Quality_Assessment__c>();
    Quality_Assessment__c qa = new Quality_Assessment__c();
    qa.Advice_Initial_Contact__c = REQUIREMENTS_NOT_MET;
    qa.Advice_Define_Scope__c = ALMOST_THERE;
    qa.Advice_Customer_understanding_of_scope__c = ALMOST_THERE;
    qa.Key_scoping_and_disclaimers__c = ALMOST_THERE;
    qa.Advice_Limit_scope_of_advice__c = ALMOST_THERE;
    qa.Advice_Decline_advice_and_refer__c = ALMOST_THERE;
    qa.Advice_Substantive_Advice_OFSN__c = EFFECTIVE;
    qa.Advice_Fact_Find__c = EFFECTIVE;
    qa.CN_Fact_Find__c = EFFECTIVE;
    qa.Advice_Best_Interest_Duty__c = EFFECTIVE;
    qa.Advice_Dispute_Resolution__c = ALMOST_THERE;
    qa.Advice_Incomplete_Inaccurate_warning__c = NA_VALUE;
    qa.CN_Customers_Focus__c = NA_VALUE;
    qa.CN_Substantive_Advice__c = NA_VALUE;
    qa.CN_Out_of_Scope__c = NA_VALUE;
    qa.CN_OFSN__c = NA_VALUE;
    qa.CN_Scope_Provided__c = NA_VALUE;
    qa.CN_Checklist__c = NA_VALUE;
    qa.RecordTypeId = LENDING_RT_ID;
    qa.Status__c = 'In Progress';
    qa.Reference__c = REFERENCE_VALUE;
    qa.Connection_and_Trust__c = EFFECTIVE;
    qa.Energy_and_Adaptability__c = EFFECTIVE;
    qa.Discover_and_Align__c = EFFECTIVE;
    qa.Actions_and_Momentum__c = EFFECTIVE;
    qa.Accountability_and_Next_Steps__c = EFFECTIVE;
    qa.Id = FAKER_QA_ASSESS_RECORD_ID;
    qa.Serviceability_Outcome__c = REQUIREMENT_MET;
    qa.Income_Serviceability_Outcome__c = REQUIREMENT_MET;
    qa.Expenses_Serviceability_Outcome__c = REQUIREMENT_MET;
    qa.Debts_Serviceability_Outcome__c = REQUIREMENT_MET;
    qa.Conduct_Outcome__c = REQUIREMENT_MET;
    qa.Purpose_of_Loan_Outcome__c = REQUIREMENT_MET;
    qa.Collateral_Valuation_Outcome__c = REQUIREMENT_MET;
    qa.Material_Change_Outcome__c = REQUIREMENT_MET;
    qa.Hypercare_Focus_Area_Outcome__c = REQUIREMENT_MET;
    qa.Other__c = REQUIREMENT_MET;
    qa.Case_Notes_Outcome__c = REQUIREMENT_MET;
    oldMap.put(FAKER_QA_ASSESS_RECORD_ID, qa);
    return oldMap;
  }

  private static List<Quality_Assessment__Share> returnQAShareToDelete() {
    return new List<Quality_Assessment__Share>{
      new Quality_Assessment__Share(
        AccessLevel = 'Read',
        ParentId = FAKER_QA_ASSESS_RECORD_ID,
        UserOrGroupId = FAKER_RLA_RECORD_ID,
        RowCause = Schema.Quality_Assessment__Share.RowCause.ApexSharing__c
      )
    };
  }

  private static List<ResidentialLoanApplication> returnGetRlaByIds() {
    return new List<ResidentialLoanApplication>{
      new ResidentialLoanApplication(
        Id = FAKER_RLA_RECORD_ID,
        AccountId = FAKER_ACCOUNT_RECORD_ID,
        OwnerId = UserInfo.getUserId()
      )
    };
  }

  @isTest
  private static void testSetProcessExecutionOutcome() {
    List<Quality_Assessment__c> records = getQARecords();
    Test.startTest();
    LendingEvaluationActions.setProcessExecutionOutcome(
      records,
      getOldQARecords()
    );
    Test.stopTest();
    Assert.areEqual(
      records[0].Process_Execution_Outcome__c,
      REQUIREMENT_MET,
      'Process Execution Outcome should be requirement met'
    );
  }

  @isTest
  private static void testSetRiskAndComplianceOutcome() {
    List<Quality_Assessment__c> records = getQARecords();
    Test.startTest();
    LendingEvaluationActions.setRiskAndComplianceOutcome(
      records,
      getOldQARecords()
    );
    Test.stopTest();
    Assert.areEqual(
      records[0].Risk_and_Compliance_Outcome__c,
      REQUIREMENT_MET,
      'Risk & Complaince Outcome should be requirement met'
    );
  }

  @isTest
  private static void testSetRiskAndComplianceOutcomeNotMet() {
    List<Quality_Assessment__c> records = getQARecords();
    records[0]
      .Collateral_Valuation_Outcome__c = REQUIREMENT_NOT_MEANT_COMPLIANCE;
    Test.startTest();
    LendingEvaluationActions.setRiskAndComplianceOutcome(
      records,
      getOldQARecords()
    );
    Test.stopTest();
    Assert.areEqual(
      records[0].Risk_and_Compliance_Outcome__c,
      REQUIREMENT_NOT_MEANT_COMPLIANCE,
      'Risk & Complaince Outcome should be requirement met'
    );
  }

  @isTest
  private static void testSetProcessExecutionOutcomeNotMet() {
    List<Quality_Assessment__c> records = getQARecords();
    records[0]
      .Expenses_Serviceability_Outcome__c = REQUIREMENT_NOT_MEANT_PROCESS_ONLY;
    Test.startTest();
    LendingEvaluationActions.setProcessExecutionOutcome(
      records,
      getOldQARecords()
    );
    Test.stopTest();
    Assert.areEqual(
      records[0].Process_Execution_Outcome__c,
      REQUIREMENT_NOT_MEANT_PROCESS_ONLY,
      'Process Execution Outcome should be requirement met'
    );
  }

  @isTest
  private static void testCalculateAndSetNumberOfApplication() {
    registerMocks();
    List<Quality_Assessment__c> records = getQARecords();
    Test.startTest();
    LendingEvaluationActions.calculateAndSetNumberOfApplication(
      records,
      getOldQARecords()
    );
    Test.stopTest();
    Assert.areEqual(
      records[0].Number_of_Applications__c,
      null,
      'Number of application field should be empty'
    );
  }

  @isTest
  private static void createQAShareRecordsForLendingEvaluation() {
    registerMocks();
    Map<Id, Quality_Assessment__c> oldMap = getOldQARecords();
    List<Quality_Assessment__c> qaRecords = getQARecords();

    Test.startTest();
    LendingEvaluationActions.createQAShareRecordsForLendingEvaluation(
      qaRecords,
      oldMap
    );
    Test.stopTest();

    List<Quality_Assessment__share> qaToDelete = (List<Quality_Assessment__share>) dmlRepoMock.getHistory(
        'doDelete'
      )
      .getParam('records');

    Assert.isTrue(
      qaToDelete.size() == 1,
      'A share record should be found to delete'
    );

    List<Quality_Assessment__share> qaShares = (List<Quality_Assessment__share>) dmlRepoMock.getHistory(
        'doInsert'
      )
      .getParam('records');

    Assert.isTrue(qaShares.size() > 0, 'A share record should be created');
    Assert.isTrue(
      qaShares[0].UserOrGroupId == UserInfo.getUserId(),
      'Share with user should be created'
    );
  }

  @isTest
  private static void testSetOutcomesForInProgress() {
    List<Quality_Assessment__c> records = getQARecords();
    records[0].Status__c = 'In Progress';
    records[0].Other__c = null;
    Test.startTest();
    LendingEvaluationActions.setOutcomesForInProgress(
      records,
      getOldQARecords()
    );
    Test.stopTest();
    Assert.isNull(
      records[0].Risk_and_Compliance_Outcome__c,
      'Risk & Complaince Outcome should be null'
    );
  }
}