force-app/main/default/objects/PrivateKeyStorage__c/PrivateKeyStorage__c.object-meta.xml
<CustomObject>
    <description>Created to store the private key from GCP in a secure way, so that even a system admin should not be able to access this information.</description>
    <label>PrivateKeyStorage</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PrivateKeyStorages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PrivateKeyStorage__c/fields/Private_Key__c.field-meta.xml
<CustomField>
    <fullName>Private_Key__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information;Source - GCP</complianceGroup>
    <description>Private Key to be stored from GCP</description>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Private Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrivateKeyStorage__c/fields/Public_Key_Id__c.field-meta.xml
<CustomField>
    <fullName>Public_Key_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <complianceGroup>Integrity - Trusted;Privacy_Non_Personal_Information;Source - GCP</complianceGroup>
    <description>Public Key to be stored from GCP</description>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <externalId>true</externalId>
    <label>Public Key Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/repository/KeyServiceRepository.cls
/**
 * @author Shivam Swaraj
 * @since 2024
 * @description Provides DML and Queries helpers for VaultService class
 */
public with sharing class KeyServiceRepository {
  /**
   * @description Returns the private key stored in Salesforce based on the public key received
   * @param publicKeyId public key received from GCP
   * @return String | The Private Key stored in Salesforce based on the public key
   */
  public List<SObject> retrievePrivateKey(String publicKeyId) {
    SystemModeActions systemAction = new SystemModeActions(
      'KeyServiceRepository',
      'retrievePrivateKey'
    );

    return systemAction.queryWithBinds(
      'Select Private_Key__c From PrivateKeyStorage__c where Public_Key_Id__c = :publicKeyId',
      new Map<String, Object>{ 'publicKeyId' => publicKeyId }
    );
  }
}