force-app/main/default/objects/Account/recordTypes/CLG.recordType-meta.xml
<RecordType>
    <fullName>CLG</fullName>
    <active>true</active>
    <label>CLG</label>
</RecordType>

force-app/main/default/objects/CCRM_Account_To_Lead_Mapping__mdt/CCRM_Account_To_Lead_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>CCRM Account To Lead Mapping for Customer/Business/CLG accounts</description>
    <label>CCRM Account To Lead Mapping</label>
    <pluralLabel>CCRM Account To Lead Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/CCRM_Account_To_Lead_Mapping__mdt/fields/Account_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Field_API_Name__c</fullName>
    <description>Account Field API Name</description>
    <label>Account Field API Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCRM_Account_To_Lead_Mapping__mdt/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business</fullName>
                <default>true</default>
                <label>Business</label>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>CLG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCRM_Account_To_Lead_Mapping__mdt/fields/Lead_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Field_API_Name__c</fullName>
    <label>Lead Field API Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCRM_Account_To_Lead_Mapping__mdt/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>This field is used to store source system for the mapping fields</description>
    <label>Source System</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCRM_UNICA_To_Lead_Mapping__mdt/CCRM_UNICA_To_Lead_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>CCRM UNICA To Lead Mapping</label>
    <pluralLabel>CCRM UNICA To Lead Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/CCRM_UNICA_To_Lead_Mapping__mdt/fields/Account_or_Contact_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_or_Contact_Field_API_Name__c</fullName>
    <description>Account or Contact Field API Name</description>
    <label>Account or Contact Field API Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCRM_UNICA_To_Lead_Mapping__mdt/fields/Lead_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>Lead_Record_Types__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>This field is used to hold the semicolon separated lead record type API name</description>
    <label>Lead Record Types</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCRM_UNICA_To_Lead_Mapping__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
                <default>true</default>
                <label>Account</label>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Business_ID__c.field-meta.xml
<CustomField>
    <fullName>Business_ID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Customer CAPSIS ID (Business), provided by UNICA</description>
    <label>Business ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CLG_ID__c.field-meta.xml
<CustomField>
    <fullName>CLG_ID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Customer lending group number</description>
    <label>CLG ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Customer CAPSIS ID (Individual)</description>
    <label>Customer ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FinServ__RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelatedAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This includes Organisation, Individual, CLG, Prospect Customers.</inlineHelpText>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Leads</relationshipLabel>
    <relationshipName>RelatedLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Originator__c.field-meta.xml
<CustomField>
    <fullName>Lead_Originator__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Lead originating system name</description>
    <label>Lead Originator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adobe</fullName>
            </value>
            <value>
                <fullName>CCRM</fullName>
                <default>true</default>
                <label>CCRM</label>
            </value>
            <value>
                <fullName>UNICA</fullName>
            </value>
            <value>
                <fullName>MLCRM</fullName>
            </value>
            <value>
                <fullName>Lender Engage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/classes/ccrm/CommercialLeadMappingEngineHelper.cls
/**
 * @author Naman Garg
 * @since  May 2025
 * @group CCRM (Commercial CRM)
 * @description CommercialLeadMappingEngineHelper is class to helper class for CommercialLeadMappingEngine
 */
public with sharing class CommercialLeadMappingEngineHelper {
  private static final Map<Id, String> ACCOUNT_TYPE_MAP = new Map<Id, String>{
    RTAccount.businessAccount => 'Business',
    RTAccount.personAccount => 'Customer',
    RTAccount.clgAccount => 'CLG'
  };
  private static final String ACCOUNT_OBJECT = 'Account';
  private static final String CONTACT_OBJECT = 'Contact';

  private static final Set<SObjectField> MANUAL_LEAD_FIELDS = new Set<SObjectField>{
    CCRM_Account_To_Lead_Mapping__mdt.Account_Field_API_Name__c,
    CCRM_Account_To_Lead_Mapping__mdt.Lead_Field_API_Name__c
  };
  private static final Set<SObjectField> UNICA_LEAD_FIELDS = new Set<SObjectField>{
    CCRM_UNICA_To_Lead_Mapping__mdt.Account_or_Contact_Field_API_Name__c,
    CCRM_UNICA_To_Lead_Mapping__mdt.Lead_Field_API_Name__c
  };

  /**
   * @description form account field to Lead map
   * @name formAccountToLeadMappingMap
   * @param records List of lead records
   * @param mapAccountsRecordTypeId Map of account Id and Account
   * @return PrefillManualLeadWrapper Wrapper record
   */
  public CommercialLeadMappingEngine.PrefillManualLeadWrapper formAccountToLeadMappingMap(
    List<Lead> records,
    Map<Id, Account> mapAccountsRecordTypeId
  ) {
    String accountType = '';
    CommercialLeadMappingEngine.PrefillManualLeadWrapper prefillManualLeadWrap = new CommercialLeadMappingEngine.PrefillManualLeadWrapper();

    for (Lead record : records) {
      prefillManualLeadWrap.accountToLeadMappingClone = new Map<string, string>();
      Id accountRecordTypeId = mapAccountsRecordTypeId.get(
          record.FinServ__RelatedAccount__c
        )
        ?.RecordTypeId;
      accountType = ACCOUNT_TYPE_MAP.get(accountRecordTypeId);

      if (String.isBlank(accountType)) {
        continue;
      }

      formManualAccountToLeadMappingMap(
        record,
        accountType,
        prefillManualLeadWrap
      );
    }
    return prefillManualLeadWrap;
  }

  /**
   * @description form account field to Lead map for manual leads
   * @name formManualAccountToLeadMappingMap
   * @param record lead record
   * @param accountType account type
   * @param prefillManualLeadWrap Wrapper record
   */
  @TestVisible
  private static void formManualAccountToLeadMappingMap(
    Lead record,
    String accountType,
    CommercialLeadMappingEngine.PrefillManualLeadWrapper prefillManualLeadWrap
  ) {
    List<CCRM_Account_To_Lead_Mapping__mdt> filteredManualLeadMetadataList = ListUtil.filter(
        CCRM_Account_To_Lead_Mapping__mdt.getall().values()
      )
      .allNotNull(MANUAL_LEAD_FIELDS)
      .equals(CCRM_Account_To_Lead_Mapping__mdt.Account_Type__c, accountType)
      .equals(
        CCRM_Account_To_Lead_Mapping__mdt.Lead_Record_Types__c,
        RTLead.get(record.RecordTypeId).developername
      )
      .containsIgnoreCase(
        CCRM_Account_To_Lead_Mapping__mdt.Source_System__c,
        record.Lead_Originator__c
      )
      .toList();

    for (
      CCRM_Account_To_Lead_Mapping__mdt mapping : filteredManualLeadMetadataList
    ) {
      if (
        !prefillManualLeadWrap.accountToLeadMapping.containsKey(
          mapping.Account_Field_API_Name__c
        )
      ) {
        prefillManualLeadWrap.query += mapping.Account_Field_API_Name__c + ',';
      }
      prefillManualLeadWrap.accountToLeadMapping.put(
        mapping.Account_Field_API_Name__c,
        mapping.Lead_Field_API_Name__c
      );
    }
    //Create clone to create Map - accountToLeadMappingWithAccount based on account types
    prefillManualLeadWrap.accountToLeadMappingWithAccount.put(
      accountType,
      prefillManualLeadWrap.accountToLeadMappingClone
    );
  }

  /**
   * @description form account contact field to Lead map
   * @name formAccountContactToLeadMappingMap
   * @param records List of lead records
   * @param accountMap Map of account
   * @return PrefillUnicaLeadWrapper Wrapper record
   */

  public CommercialLeadMappingEngine.PrefillUnicaLeadWrapper formAccountContactToLeadMappingMap(
    List<Lead> records,
    Map<String, Account> accountMap
  ) {
    CommercialLeadMappingEngine.PrefillUnicaLeadWrapper prefillUnicaLeadWrap = new CommercialLeadMappingEngine.PrefillUnicaLeadWrapper();

    for (Lead record : records) {
      prefillUnicaLeadWrap.accountToLeadMappingClone = new Map<String, String>();
      prefillUnicaLeadWrap.contactToLeadMappingClone = new Map<String, String>();

      String fieldName = record.Customer_ID__c ?? record.Business_ID__c ??
        record.Clg_ID__c ?? '';
      if (String.isBlank(fieldName)) {
        record.addError(Label.ML_Unica_Lead_Source_System_Not_Found_Error);
        continue;
      }
      String accountType = ACCOUNT_TYPE_MAP.get(
        accountMap.get(fieldName).RecordTypeId
      );

      if (String.isBlank(accountType)) {
        continue;
      }
      record.FinServ__RelatedAccount__c = accountMap.get(fieldName).Id;

      formUnicaAccountToLeadMappingMap(
        record,
        accountType,
        prefillUnicaLeadWrap
      );
      formUnicaContactToLeadMappingMap(
        record,
        accountType,
        prefillUnicaLeadWrap
      );
    }
    return prefillUnicaLeadWrap;
  }

  /**
   * @description form account field to Lead map for unica leads
   * @name formUnicaAccountToLeadMappingMap
   * @param record lead record
   * @param accountType account type
   * @param prefillUnicaLeadWrap Wrapper record
   */
  @TestVisible
  private static void formUnicaAccountToLeadMappingMap(
    Lead record,
    String accountType,
    CommercialLeadMappingEngine.PrefillUnicaLeadWrapper prefillUnicaLeadWrap
  ) {
    List<CCRM_UNICA_To_Lead_Mapping__mdt> filteredUnicaLeadMetadataList = ListUtil.filter(
        CCRM_UNICA_To_Lead_Mapping__mdt.getall().values()
      )
      .allNotNull(UNICA_LEAD_FIELDS)
      .equals(CCRM_UNICA_To_Lead_Mapping__mdt.Object__c, ACCOUNT_OBJECT)
      .equals(CCRM_UNICA_To_Lead_Mapping__mdt.Account_Type__c, accountType)
      .equals(
        CCRM_UNICA_To_Lead_Mapping__mdt.Lead_Record_Types__c,
        RTLead.get(record.RecordTypeId).developername
      )
      .toList();

    for (
      CCRM_UNICA_To_Lead_Mapping__mdt mapping : filteredUnicaLeadMetadataList
    ) {
      if (
        !prefillUnicaLeadWrap.accountToLeadMapping.containsKey(
          mapping.Account_or_Contact_Field_API_Name__c
        )
      ) {
        prefillUnicaLeadWrap.accountFields +=
          mapping.Account_or_Contact_Field_API_Name__c + ',';
      }
      prefillUnicaLeadWrap.accountToLeadMapping.put(
        mapping.Account_or_Contact_Field_API_Name__c,
        mapping.Lead_Field_API_Name__c
      );

      //Create clone to create Map - accountToLeadMappingWithAccount based on account types
      prefillUnicaLeadWrap.accountToLeadMappingClone.put(
        mapping.Account_or_Contact_Field_API_Name__c,
        mapping.Lead_Field_API_Name__c
      );
    }

    prefillUnicaLeadWrap.accountToLeadMappingWithAccount.put(
      accountType,
      prefillUnicaLeadWrap.accountToLeadMappingClone
    );
  }

  /**
   * @description form contact field to Lead map for unica leads
   * @name formUnicaContactToLeadMappingMap
   * @param record lead record
   * @param accountType account type
   * @param prefillUnicaLeadWrap Wrapper record
   */
  @TestVisible
  private static void formUnicaContactToLeadMappingMap(
    Lead record,
    String accountType,
    CommercialLeadMappingEngine.PrefillUnicaLeadWrapper prefillUnicaLeadWrap
  ) {
    List<CCRM_UNICA_To_Lead_Mapping__mdt> filteredUnicaLeadMetadataList = ListUtil.filter(
        CCRM_UNICA_To_Lead_Mapping__mdt.getall().values()
      )
      .allNotNull(UNICA_LEAD_FIELDS)
      .equals(CCRM_UNICA_To_Lead_Mapping__mdt.Object__c, CONTACT_OBJECT)
      .equals(CCRM_UNICA_To_Lead_Mapping__mdt.Account_Type__c, accountType)
      .equals(
        CCRM_UNICA_To_Lead_Mapping__mdt.Lead_Record_Types__c,
        RTLead.get(record.RecordTypeId).developername
      )
      .toList();

    for (
      CCRM_UNICA_To_Lead_Mapping__mdt mapping : filteredUnicaLeadMetadataList
    ) {
      if (
        !prefillUnicaLeadWrap.contactToLeadMapping.containsKey(
          mapping.Account_or_Contact_Field_API_Name__c
        )
      ) {
        prefillUnicaLeadWrap.contactFields +=
          mapping.Account_or_Contact_Field_API_Name__c + ',';
      }
      prefillUnicaLeadWrap.contactToLeadMapping.put(
        mapping.Account_or_Contact_Field_API_Name__c,
        mapping.Lead_Field_API_Name__c
      );
      //Create clone to create Map - accountToLeadMappingWithAccount based on account types
      prefillUnicaLeadWrap.contactToLeadMappingClone.put(
        mapping.Account_or_Contact_Field_API_Name__c,
        mapping.Lead_Field_API_Name__c
      );
    }
    prefillUnicaLeadWrap.contactToLeadMappingWithContact.put(
      accountType,
      prefillUnicaLeadWrap.contactToLeadMappingClone
    );
  }
}