force-app/main/default/objects/FinancialAccountConfiguration__mdt/FinancialAccountConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>This is to map the FinancialAccountConfiguration  to FinancialAccountUIConfiguration</description>
    <label>FinancialAccountConfiguration</label>
    <pluralLabel>FinancialAccountConfigurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/FinancialAccountConfiguration__mdt/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Icon to show on tile for financial account</description>
    <label>Icon</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinancialAccountConfiguration__mdt/fields/Transaction_Title__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Title__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>This is to store the title for the Financial Account Transaction history title for Checking, Savings ,Classic etc type of accounts.</description>
    <label>Transaction Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/FinancialAccountUIConfiguration__mdt.object-meta.xml
<CustomObject>
    <label>FinancialAccountUIConfiguration</label>
    <pluralLabel>FinancialAccountUIConfigurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Type of the financial account</description>
    <label>Account Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Savings</fullName>
                <default>true</default>
                <label>Savings</label>
            </value>
            <value>
                <fullName>Non Savings</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/fields/Balance_Title__c.field-meta.xml
<CustomField>
    <fullName>Balance_Title__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Balance Title for each account.</description>
    <label>Balance Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/fields/FinancialAccountConfiguration__c.field-meta.xml
<CustomField>
    <fullName>FinancialAccountConfiguration__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>This is to map the icon and transaction title to the corresponding type of financial account</description>
    <label>FinancialAccountConfiguration</label>
    <referenceTo>FinancialAccountConfiguration__mdt</referenceTo>
    <relationshipLabel>FinancialAccountUIConfigurations</relationshipLabel>
    <relationshipName>FinancialAccountUIConfigurations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/fields/Include_In_Total_Financial_Position__c.field-meta.xml
<CustomField>
    <fullName>Include_In_Total_Financial_Position__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>This field decides if the product code should be included in total financial position calculation</description>
    <label>Include In Total Financial Position</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Determines whether a certain product is ready to be shown on. Financial Account UI from Business perspective.</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/fields/Ownership_Type__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Type__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Owner ship type on Financial Account</description>
    <label>Ownership Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
                <default>true</default>
                <label>Single</label>
            </value>
            <value>
                <fullName>Multi-party</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Product code from Product2 table</description>
    <label>Product Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/fields/Section_Header_Title__c.field-meta.xml
<CustomField>
    <fullName>Section_Header_Title__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Header title to be displayed on LWC</description>
    <label>Section Header Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/fields/Show_Goals__c.field-meta.xml
<CustomField>
    <fullName>Show_Goals__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Controls whether to show goals on Salesforce UI</description>
    <label>Show Goals</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Sort Order for LWC component to display the data.</description>
    <label>Sort Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/utils/system/QueryFinancialAccountUIConfig.cls
/**
 * @author Nilesh
 * @since March 2025
 * @description Holds Cached Financial Account UI Config Data
 */
public with sharing class QueryFinancialAccountUIConfig {
  public static Map<String, FinancialAccountUIConfiguration__mdt> configByProductCode = new Map<String, FinancialAccountUIConfiguration__mdt>();

  public static Map<String, FinancialAccountUIConfiguration__mdt> configByDeveloperName = new Map<String, FinancialAccountUIConfiguration__mdt>();

  static {
    List<FinancialAccountUIConfiguration__mdt> allConfig = [
      SELECT
        DeveloperName,
        Product_Code__c,
        Ownership_Type__c,
        Show_Goals__c,
        Sort_Order__c,
        Account_Type__c,
        Balance_Title__c,
        Section_Header_Title__c,
        Is_Active__c,
        FinancialAccountConfiguration__r.Icon__c,
        FinancialAccountConfiguration__r.Transaction_Title__c,
        Include_In_Total_Financial_Position__c
      FROM FinancialAccountUIConfiguration__mdt
      WITH USER_MODE
    ];

    for (FinancialAccountUIConfiguration__mdt config : allConfig) {
      configByProductCode.put(config.Product_Code__c, config);
      configByDeveloperName.put(config.DeveloperName, config);
    }
  }

  /**
   * @description Returns SEt of product codes from Financial Account UI config data.
   * @param developerName Name of the Financial Account UI config record
   * @return Product set of all config data.
   */
  public static FinancialAccountUIConfiguration__mdt getByDeveloperName(
    String developerName
  ) {
    return configByDeveloperName.get(developerName);
  }

  /**
   * @description Returns SEt of product codes from Financial ACcount UI config data.
   * @param productCode field of Financial Account UI config record
   * @return Product set of all config data.
   */
  public static FinancialAccountUIConfiguration__mdt getByProductCode(
    String productCode
  ) {
    return configByProductCode.get(productCode);
  }
}