force-app/main/default/objects/Lead_Status_Transformation__mdt/Lead_Status_Transformation__mdt.object-meta.xml
<CustomObject>
    <label>Lead Status Transformation</label>
    <pluralLabel>Lead Status Transformations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Lead_Status_Transformation__mdt/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Store the lead status value.</description>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
                <default>true</default>
                <label>Assigned</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Outcome</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Status_Transformation__mdt/fields/Outcome_Type__c.field-meta.xml
<CustomField>
    <fullName>Outcome_Type__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Store the outcome values.</description>
    <label>Outcome Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Identified</fullName>
                <default>true</default>
                <label>Opportunity Identified</label>
            </value>
            <value>
                <fullName>No Opportunity</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Status_Transformation__mdt/fields/UNICA_Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>UNICA_Lead_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Store the value which is used by UNICA.</description>
    <label>UNICA Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ccrm/QueryLeadStatusTransformation.cls
/**
 * @author Naman Garg
 * @since May 2025
 * @description holds Lead Status Transformation metadata records
 */
public with sharing class QueryLeadStatusTransformation {
  private static List<Lead_Status_Transformation__mdt> leadStatusTransformList = [
    SELECT
      Id,
      MasterLabel,
      Lead_Status__c,
      Outcome_Type__c,
      UNICA_Lead_Status__c
    FROM Lead_Status_Transformation__mdt
    WITH SYSTEM_MODE
  ];
  private static Map<String, Lead_Status_Transformation__mdt> leadStatusTransformationMap = new Map<String, Lead_Status_Transformation__mdt>();
  static {
    for (Lead_Status_Transformation__mdt mdtRecord : leadStatusTransformList) {
      if (String.isNotBlank(mdtRecord.Outcome_Type__c)) {
        leadStatusTransformationMap.put(mdtRecord.MasterLabel, mdtRecord);
        continue;
      }
      leadStatusTransformationMap.put(mdtRecord.Lead_Status__c, mdtRecord);
    }
  }

  /**
   * @description Returns a metadata record for the Status
   * @param status Lead Status
   * @return The metadata record associated with Lead status
   */
  public static Lead_Status_Transformation__mdt get(String status) {
    return leadStatusTransformationMap.get(status);
  }
}