force-app/main/default/objects/Account/fields/ABN__c.field-meta.xml
<CustomField>
    <fullName>ABN__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Australian Business Number</description>
    <label>ABN</label>
    <length>51</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ABN__c.field-meta.xml
<CustomField>
    <fullName>ABN__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Source_Salesforce;Integrity_Accurate</complianceGroup>
    <description>Australian Business Number</description>
    <label>ABN</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ABN_Validation_Status__c.field-meta.xml
<CustomField>
    <fullName>ABN_Validation_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>ABN validation status received from australian business registry</description>
    <label>ABN Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Validation in progress</fullName>
            </value>
            <value>
                <fullName>Validation Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <defaultValue>IF(
    NOT(
        CONTAINS( 
            $User.Username,&apos;unica.integration@anzx.com&apos;
        )
    ),
    CASE( 
        $RecordType.Name ,&apos;Commercial CRM Lead&apos;, 
            IF((WEEKDAY(DATEVALUE(NOW() + VALUE($Label.CCRM_ExpiryDateDays))) = 1)
                , NOW() + (VALUE($Label.CCRM_ExpiryDateDays) + 1),
                IF((WEEKDAY(DATEVALUE(NOW() + VALUE($Label.CCRM_ExpiryDateDays))) = 7)
                    , NOW() + VALUE($Label.CCRM_ExpiryDateDays) + 2
                    , NOW() + (VALUE($Label.CCRM_ExpiryDateDays))
                )
            ),
            &apos;Referral&apos;,
            IF((WEEKDAY(DATEVALUE(NOW() + VALUE($Label.Referral_ExpiryDateDays))) = 1)
                , NOW() + (VALUE($Label.Referral_ExpiryDateDays) + 1),
                IF((WEEKDAY(DATEVALUE(NOW() + VALUE($Label.Referral_ExpiryDateDays))) = 7)
                    , NOW() + VALUE($Label.Referral_ExpiryDateDays) + 2
                    , NOW() + (VALUE($Label.Referral_ExpiryDateDays))
                )
            ),
            NULL

    )
    ,NULL
)</defaultValue>
    <description>Expiry date of the lead.</description>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FinServ__RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelatedAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This includes Organisation, Individual, CLG, Prospect Customers.</inlineHelpText>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Leads</relationshipLabel>
    <relationshipName>RelatedLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Followup_Date__c.field-meta.xml
<CustomField>
    <fullName>Followup_Date__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Source_Salesforce;Integrity_Accurate</complianceGroup>
    <description>Next followup date</description>
    <label>Follow Up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Lead_Outcome__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>This is the CCRM field to track the lead Outcome Type.</description>
    <label>Lead Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Identified</fullName>
            </value>
            <value>
                <fullName>No Opportunity</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Quality__c.field-meta.xml
<CustomField>
    <fullName>Lead_Quality__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The quality of the lead.</description>
    <label>Lead Quality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Very Good</fullName>
            </value>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Average</fullName>
            </value>
            <value>
                <fullName>Poor</fullName>
            </value>
            <value>
                <fullName>Very Poor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Skip_Validations__c.field-meta.xml
<CustomField>
    <fullName>Skip_Validations__c</fullName>
    <complianceGroup>Source - Salesforce;Privacy - Non Personal Information;Integrity - Trusted</complianceGroup>
    <description>This field is to Skip Validation Rules when updating records through Apex.</description>
    <label>Skip Validations</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SubStatus__c.field-meta.xml
<CustomField>
    <fullName>SubStatus__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Sub Status of the lead</description>
    <label>Lead Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>1st attempt made</fullName>
            </value>
            <value>
                <fullName>2nd attempt made</fullName>
            </value>
            <value>
                <fullName>3rd attempt made</fullName>
            </value>
            <value>
                <fullName>Follow up required</fullName>
            </value>
            <value>
                <fullName>Opportunity identified</fullName>
            </value>
            <value>
                <fullName>Referred to Classic</fullName>
            </value>
            <value>
                <fullName>Not interested</fullName>
            </value>
            <value>
                <fullName>Not contactable</fullName>
            </value>
            <value>
                <fullName>Auto-closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/CCRM_Lead.recordType-meta.xml
<RecordType>
    <fullName>CCRM_Lead</fullName>
    <active>true</active>
    <businessProcess>CCRM Lead Process</businessProcess>
    <description>Create a new AR&amp;C commercial lead</description>
    <label>Commercial CRM Lead</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Referral.recordType-meta.xml
<RecordType>
    <fullName>Referral</fullName>
    <active>true</active>
    <businessProcess>CCRM Lead Process</businessProcess>
    <description>Create a new commercial referral</description>
    <label>Referral</label>
</RecordType>

force-app/main/default/objects/Lead_Stage_Automation__mdt/Lead_Stage_Automation__mdt.object-meta.xml
<CustomObject>
    <description>Lead Stage configurations.</description>
    <label>Lead Stage Automation</label>
    <pluralLabel>Lead Stage Automations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Lead_Stage_Automation__mdt/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead_Stage_Automation__mdt/fields/Lead_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Record_Type__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Store the record type name of CCRM lead.</description>
    <label>Lead Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Stage_Automation__mdt/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <label>Lead Status</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Stage_Automation__mdt/fields/Next_Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Next_Lead_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Next Lead Status based on the criteria match.</description>
    <label>Next Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In progress</fullName>
                <default>true</default>
                <label>In progress</label>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Outcome</fullName>
            </value>
            <value>
                <fullName>Opportunity Identified</fullName>
            </value>
            <value>
                <fullName>No Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Stage_Automation__mdt/fields/Outcome_Type__c.field-meta.xml
<CustomField>
    <fullName>Outcome_Type__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Store the possible outcome type values.</description>
    <label>Outcome Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Identified</fullName>
                <default>true</default>
                <label>Opportunity Identified</label>
            </value>
            <value>
                <fullName>No Opportunity</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Stage_Automation__mdt/fields/Response_Status__c.field-meta.xml
<CustomField>
    <fullName>Response_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Response Status from Responses logged for a particular lead.</description>
    <label>Response Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Stage_Automation__mdt/fields/Response_Type_CreateOpportunity__c.field-meta.xml
<CustomField>
    <fullName>Response_Type_CreateOpportunity__c</fullName>
    <label>Response Type CreateOpportunity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>true</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Stage_Automation__mdt/fields/What_happens_next__c.field-meta.xml
<CustomField>
    <fullName>What_happens_next__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Store what happens next based on Response Status and Create Opportunity flag</description>
    <label>What happens next</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Response_Type__c/Response_Type__c.object-meta.xml
<CustomObject>
    <description>Custom Object to store Response Type information.</description>
    <label>Response Type</label>
    <nameField>
        <label>Response Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Response Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Response_Type__c/fields/Create_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Create_Opportunity__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>This flag will determine whether user can click Create Opportunity button along with Division Group</description>
    <label>Create Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Response_Type__c/fields/Response_Status__c.field-meta.xml
<CustomField>
    <fullName>Response_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Response status for the corresponding campaign</description>
    <label>Response Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadResponseTaskActionsTest.cls
@isTest
public with sharing class LeadResponseTaskActionsTest {
  private static List<Lead_Stage_Automation__mdt> leadStageAutomationMetadata = Lead_Stage_Automation__mdt.getAll()
    .values();
  static Lib_MockProvider taskRepoMock;
  static Lib_MockProvider dmlRepoMock;

  static void registerMocks() {
    taskRepoMock = Lib_MockProvider.forType(TaskActionRepository.class);
    dmlRepoMock = Lib_MockProvider.forType(DmlRepository.class);
  }

  @isTest
  static void testUpdateLeadsBasisLogResponse() {
    registerMocks();
    Lead leadRecord = getLeadRecord();
    List<Response_Type__c> respTypeRecords = getResponseTypeRecords();
    Task leadResponseTask = getLeadResponseTask(leadRecord, respTypeRecords[0]);
    taskRepoMock.mock(
      new Map<String, Object>{
        'getResponseTypeData' => respTypeRecords,
        'getLeadRecords' => new List<Lead>{ leadRecord },
        'getCampaignMemberRecords' => new List<CampaignMember>{
          getCampaignMemberRecord(leadRecord, 2)
        }
      }
    );
    Test.startTest();
    LeadResponseTaskActions.updateLeadsBasisLogResponse(
      new List<Task>{ leadResponseTask }
    );
    Test.stopTest();
    List<Lead> updatedLeads = (List<Lead>) dmlRepoMock.getHistory('doUpdate')
      .getParam('records');
    List<Lead_Stage_Automation__mdt> leadStageMdt = ListUtil.filter(
        leadStageAutomationMetadata
      )
      .equals(Lead_Stage_Automation__mdt.Lead_Record_Type__c, 'CCRM_Lead')
      .equals(Lead_Stage_Automation__mdt.Response_Status__c, 'Accepted')
      .contains(Lead_Stage_Automation__mdt.Lead_Status__c, 'In progress')
      .equals(
        Lead_Stage_Automation__mdt.Response_Type_CreateOpportunity__c,
        'true'
      )
      .toList();
    Assert.areEqual(
      leadStageMdt[0].Next_Lead_Status__c,
      updatedLeads[0].Status,
      'Status field is not updated'
    );
    Assert.areEqual(
      leadStageMdt[0].Outcome_Type__c,
      updatedLeads[0].Lead_Outcome__c,
      'Lead Outcome field is not updated'
    );
    Assert.areEqual(
      'Validate',
      updatedLeads[0].Skip_Validations__c,
      'Skip Validations field is not updated'
    );
    Assert.areEqual(
      leadStageMdt[0].Response_Status__c,
      updatedLeads[0].SubStatus__c,
      'Sub Status field is not updated'
    );
    Assert.areEqual(
      leadResponseTask.Lead_Quality__c,
      updatedLeads[0].Lead_Quality__c,
      'Lead quality field is not updated'
    );
    Assert.areEqual(
      System.today().addDays(2),
      updatedLeads[0].Expiry_Date__c,
      'Expiry date field is not updated'
    );
    Assert.areEqual(
      null,
      updatedLeads[0].Followup_Date__c,
      'Follow up date field is not marked as null'
    );
  }

  @isTest
  static void testPopulateLeadDetails() {
    registerMocks();
    Lead leadRecord = getLeadRecord();
    List<Response_Type__c> respTypeRecords = getResponseTypeRecords();
    Task leadResponseTask = getLeadResponseTask(leadRecord, respTypeRecords[0]);
    Test.startTest();
    List<Lead> updatedLeads = LeadResponseTaskActions.populateLeadDetails(
      new List<Lead>{ leadRecord },
      new Map<Id, Task>{ leadResponseTask.WhoId => leadResponseTask },
      new Map<Id, Response_Type__c>{
        respTypeRecords[0].Id => respTypeRecords[0],
        respTypeRecords[0].Id => respTypeRecords[0]
      }
    );
    Test.stopTest();
    List<Lead_Stage_Automation__mdt> leadStageMdt = ListUtil.filter(
        leadStageAutomationMetadata
      )
      .equals(Lead_Stage_Automation__mdt.Lead_Record_Type__c, 'CCRM_Lead')
      .equals(Lead_Stage_Automation__mdt.Response_Status__c, 'Accepted')
      .contains(Lead_Stage_Automation__mdt.Lead_Status__c, 'In progress')
      .equals(
        Lead_Stage_Automation__mdt.Response_Type_CreateOpportunity__c,
        'true'
      )
      .toList();
    Assert.areEqual(
      leadStageMdt[0].Next_Lead_Status__c,
      updatedLeads[0].Status,
      'Status field is not updated'
    );
    Assert.areEqual(
      leadStageMdt[0].Outcome_Type__c,
      updatedLeads[0].Lead_Outcome__c,
      'Lead Outcome field is not updated'
    );
    Assert.areEqual(
      'Validate',
      updatedLeads[0].Skip_Validations__c,
      'Skip Validations field is not updated'
    );
    Assert.areEqual(
      leadStageMdt[0].Response_Status__c,
      updatedLeads[0].SubStatus__c,
      'Sub Status field is not updated'
    );
    Assert.areEqual(
      leadResponseTask.Lead_Quality__c,
      updatedLeads[0].Lead_Quality__c,
      'Lead quality field is not updated'
    );
    Assert.areEqual(
      leadResponseTask.ActivityDate,
      updatedLeads[0].Followup_Date__c,
      'Follow up date field is not marked as null'
    );
  }

  @isTest
  static void testSetExpiryDateFromLogResponse() {
    registerMocks();
    Lead leadRecord = getLeadRecord();
    List<Response_Type__c> respTypeRecords = getResponseTypeRecords();
    Task leadResponseTask = getLeadResponseTask(leadRecord, respTypeRecords[0]);
    taskRepoMock.mock(
      new Map<String, Object>{
        'getCampaignMemberRecords' => new List<CampaignMember>{
          getCampaignMemberRecord(leadRecord, 60)
        }
      }
    );
    Test.startTest();
    LeadResponseTaskActions.setExpiryDateFromLogResponse(
      new Map<Id, Task>{ leadResponseTask.WhoId => leadResponseTask },
      new Map<Id, Response_Type__c>{
        respTypeRecords[0].Id => respTypeRecords[0],
        respTypeRecords[0].Id => respTypeRecords[0]
      },
      new List<Lead>{ leadRecord }
    );
    Test.stopTest();
    Integer extendLeadExpiryDate = Integer.valueOf(
      System.Label.CommercialExtendLeadExpiryDateForLogResponse
    );
    Integer extendTodaysDate = Integer.valueOf(
      System.Label.CommercialExtendTodaysDate
    );
    Assert.areEqual(
      DateTimeUtils.getNextWeekdayDate(extendTodaysDate + extendLeadExpiryDate),
      leadRecord.Expiry_Date__c,
      'Expiry date field is not correctly updated'
    );
    Assert.areEqual(
      null,
      leadRecord.Followup_Date__c,
      'Follow up date field is not marked as null'
    );
  }

  @isTest
  static void testValidateLeadABNACN() {
    registerMocks();
    Lead leadRecord = getLeadRecord();
    List<Response_Type__c> respTypeRecords = getResponseTypeRecords();
    Task leadResponseTask = getLeadResponseTask(leadRecord, respTypeRecords[0]);
    leadResponseTask.Response_Status__c = 'Referral Made';
    taskRepoMock.mock(
      new Map<String, Object>{
        'getLeadRecordsWithABNACN' => new List<Lead>{ leadRecord }
      }
    );
    Test.startTest();
    LeadResponseTaskActions.validateLeadABNACN(
      new List<Task>{ leadResponseTask }
    );
    Test.stopTest();
    Assert.areEqual(
      LeadResponseTaskActions.ABN_ACN_VALIDATION_MESSAGE,
      leadResponseTask.getErrors()[0].getMessage(),
      'ABN ACN error message not received'
    );
  }

  @isTest
  static void testPreventDelete() {
    Task leadResponseTask = new Task(
      Id = Lib_FakeIdGenerator.getMockId(Schema.Task.getSObjectType()),
      RecordTypeId = RTTask.leadResponse
    );
    Test.startTest();
    LeadResponseTaskActions.preventDelete(new List<Task>{ leadResponseTask });
    Test.stopTest();
    Assert.areEqual(
      LeadResponseTaskActions.RESPONSE_DELETE_ERROR_MESSAGE,
      leadResponseTask.getErrors()[0].getMessage(),
      'Delete error message not received'
    );
  }

  static List<Lead_Stage_Automation__mdt> getLeadStageAutomationMdt() {
    return new List<Lead_Stage_Automation__mdt>{
      new Lead_Stage_Automation__mdt(
        Response_Status__c = 'Accepted',
        Response_Type_CreateOpportunity__c = 'true',
        isActive__c = true,
        What_happens_next__c = 'Dummy Text',
        Lead_Record_Type__c = 'CCRM_Lead',
        Lead_Status__c = 'Assigned,In progress',
        Next_Lead_Status__c = 'Outcome',
        Outcome_Type__c = 'No Opportunity'
      ),
      new Lead_Stage_Automation__mdt(
        Response_Status__c = 'Contact Attempted',
        Response_Type_CreateOpportunity__c = null,
        isActive__c = true,
        What_happens_next__c = 'Dummy Text',
        Lead_Record_Type__c = 'CCRM_Lead',
        Lead_Status__c = 'Assigned,In progress',
        Next_Lead_Status__c = 'In progress',
        Outcome_Type__c = 'Opportunity Identified'
      )
    };
  }

  static List<Response_Type__c> getResponseTypeRecords() {
    return new List<Response_Type__c>{
      new Response_Type__c(
        Id = Lib_FakeIdGenerator.getMockId(
          Schema.Response_Type__c.getSObjectType()
        ),
        Response_Status__c = 'Accepted',
        Create_Opportunity__c = true
      ),
      new Response_Type__c(
        Id = Lib_FakeIdGenerator.getMockId(
          Schema.Response_Type__c.getSObjectType()
        ),
        Response_Status__c = 'Contact Attempted',
        Create_Opportunity__c = true
      )
    };
  }

  static Lead getLeadRecord() {
    return new Lead(
      Id = Lib_FakeIdGenerator.getMockId(Schema.Lead.getSObjectType()),
      RecordType = new RecordType(DeveloperName = 'CCRM_Lead'),
      Status = 'In progress',
      FinServ__RelatedAccount__c = Lib_FakeIdGenerator.getMockId(
        Schema.Account.getSObjectType()
      ),
      RecordTypeId = RTLead.commercialLead,
      Followup_Date__c = System.today().addDays(3),
      Skip_Validations__c = 'SkipValidation',
      ABN__c = '10918',
      ABN_Validation_Status__c = 'Cancelled'
    );
  }

  static Task getLeadResponseTask(
    Lead leadRecord,
    Response_Type__c respTypeRecord
  ) {
    return new Task(
      Id = Lib_FakeIdGenerator.getMockId(Schema.Task.getSObjectType()),
      RecordTypeId = RTTask.leadResponse,
      WhoId = leadRecord.Id,
      Response_Type__c = respTypeRecord.Id,
      Response_Status__c = 'Accepted',
      Lead_Quality__c = 'Good'
    );
  }

  static CampaignMember getCampaignMemberRecord(
    Lead leadRecord,
    Integer endDateExtend
  ) {
    return new CampaignMember(
      Id = Lib_FakeIdGenerator.getMockId(
        Schema.CampaignMember.getSObjectType()
      ),
      LeadId = leadRecord.Id,
      CampaignId = Lib_FakeIdGenerator.getMockId(
        Schema.Campaign.getSObjectType()
      ),
      Campaign = new Campaign(EndDate = System.today().addDays(endDateExtend))
    );
  }
}