force-app/main/default/objects/Account/fields/ANZx_Customer__c.field-meta.xml
<CustomField>
    <fullName>ANZx_Customer__c</fullName>
    <complianceGroup>Integrity_Accurate;Source_OCV;Privacy_Personal_Information</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Customer has ANZ Plus account(s)</description>
    <inlineHelpText>Customer has ANZ Plus account(s)</inlineHelpText>
    <label>ANZ Plus Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FraudCardStatusControllerTest.cls
/**
 * @author Farid Masjedi
 * @since Sep 2021
 * @description FraudCardStatusControllerTest is the test class for {@link FraudCardStatusController}
 */
@isTest
public with sharing class FraudCardStatusControllerTest {
  @isTest
  static void validFraudCardStatusChange() {
    Test.startTest();
    Faker faker = new Faker('AU');
    Account acc = new Account(
      Name = 'Test Account',
      OCV_ID__c = faker.randomString(10),
      ANZx_Customer__c = false
    );
    insert acc;
    Map<String, Map<String, String>> fraudLockObject = new Map<String, Map<String, String>>();
    Map<String, String> chatterInformation = new Map<String, String>{
      'recordId' => acc.Id,
      'chatterMessage' => 'Testing chatter message'
    };
    Map<String, String> fraudLockInformation = new Map<String, String>{
      'cardNumber' => '123456789',
      'ocvId' => '1111',
      'status' => 'Block CNP',
      'reason' => ''
    };
    fraudLockObject.put('chatterInformation', chatterInformation);
    fraudLockObject.put('fraudLockInformation', fraudLockInformation);
    Boolean result = FraudCardStatusController.setFraudCardStatus(
      fraudLockObject
    );
    Test.stopTest();
    System.assertEquals(
      true,
      result,
      'Check if the fraud status change is valid'
    );
  }

  /*
   * @description invalid status change. The Account with card Number '23572357'
   * has been made to make the unsuccessful mock api response.
   */

  @isTest
  static void invalidFraudCardStatusChange() {
    Exception errorResult;

    Test.startTest();
    try {
      Faker faker = new Faker('AU');
      Account acc = new Account(
        Name = 'Test Account',
        OCV_ID__c = faker.randomString(10),
        ANZx_Customer__c = false
      );
      insert acc;
      Map<String, Map<String, String>> fraudLockObject = new Map<String, Map<String, String>>();
      Map<String, String> chatterInformation = new Map<String, String>{
        'recordId' => acc.Id,
        'chatterMessage' => 'faild chatter post'
      };
      Map<String, String> fraudLockInformation = new Map<String, String>{
        'cardNumber' => '23572357',
        'ocvId' => '1111',
        'status' => 'Block CNP',
        'reason' => ''
      };
      fraudLockObject.put('chatterInformation', chatterInformation);
      fraudLockObject.put('fraudLockInformation', fraudLockInformation);

      Boolean result = FraudCardStatusController.setFraudCardStatus(
        fraudLockObject
      );
    } catch (Exception e) {
      errorResult = e;
    }

    Test.stopTest();

    System.assertEquals(
      errorResult.getMessage(),
      'Changing status on this card is not accepted',
      'Check if the fraud status change is invalid'
    );
  }
}