force-app/main/default/objects/Account/fields/ANZx_Customer__c.field-meta.xml
<CustomField>
    <fullName>ANZx_Customer__c</fullName>
    <complianceGroup>Integrity_Accurate;Source_OCV;Privacy_Personal_Information</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Customer has ANZ Plus account(s)</description>
    <inlineHelpText>Customer has ANZ Plus account(s)</inlineHelpText>
    <label>ANZ Plus Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction/fields/Chat_or_Call_SID__c.field-meta.xml
<CustomField>
    <fullName>Chat_or_Call_SID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Twilio</complianceGroup>
    <description>Used to store the unique Chat / Call Channel ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID for call or message thread created by Twilio</inlineHelpText>
    <label>Chat or Call SID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Interaction/fields/Chat_or_Call_SID_Formula__c.field-meta.xml
<CustomField>
    <fullName>Chat_or_Call_SID_Formula__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Twilio</complianceGroup>
    <description>This is formula field to store the chat or call sid from the twilio detail record to interaction</description>
    <formula>TwilioDetailsID__r.Chat_or_Call_SID__c</formula>
    <label>Chat or Call SID Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction/fields/Interaction_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Interaction_External_Id__c</fullName>
    <complianceGroup>Source - Salesforce;Privacy - Non Personal Information;Integrity - Accurate</complianceGroup>
    <description>This field will capture the Contact Request auto number when the Interaction record is created through Self Service otherwise will contain the Interaction Auto Number when Interaction record is created through Assisted Channel.</description>
    <externalId>true</externalId>
    <label>Interaction External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction/fields/TwilioDetailsID__c.field-meta.xml
<CustomField>
    <fullName>TwilioDetailsID__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Twilio</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Twilio Detail object</description>
    <label>Twilio Detail</label>
    <referenceTo>Twilio_Details__c</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/classes/interactions/InteractionRepository.cls
/**
 * @author Kopal Goswami
 * @since Sep 9 2024
 * @description Provides SOQL helpers for Interaction object
 */
public with sharing class InteractionRepository {
  /**
   * @description query existing Interaction Record
   * @param callOrChatSidList Set<String> containing callOrChatSid from Interaction
   * @return Map<String, Interaction> Map of chatOrCallSID and Interaction record
   */
  public Map<String, Interaction> queryExistingInteractionFromCallOrChatSID(
    Set<String> callOrChatSidList
  ) {
    Map<String, Interaction> existingInteractionsBySID = new Map<String, Interaction>();
    if (callOrChatSidList.isEmpty()) {
      return existingInteractionsBySID;
    }

    for (Interaction interact : [
      SELECT
        Id,
        Interaction_External_Id__c,
        Account.OCV_ID__c,
        Chat_or_Call_SID__c,
        Chat_or_Call_SID_Formula__c
      FROM Interaction
      WHERE
        Chat_or_Call_SID__c IN :callOrChatSidList
        OR Chat_or_Call_SID_Formula__c IN :callOrChatSidList
      WITH SECURITY_ENFORCED
    ]) {
      String chatOrCallSid = interact.Chat_or_Call_SID__c ??
        interact.Chat_or_Call_SID_Formula__c;
      existingInteractionsBySID.put(chatOrCallSid, interact);
    }
    return existingInteractionsBySID;
  }

  /**
   * @description query existing Interaction Record to get TwilioDetailId associated
   * @param interactionId Interaction Id from Twilio for updating
   * @return Interaction record with Twilio Details
   */
  public Interaction fetchTwilioDetailIdFromInteraction(Id interactionId) {
    if (interactionId == null) {
      return null;
    }

    return [
      SELECT TwilioDetailsID__c
      FROM Interaction
      WHERE Id = :interactionId
      WITH SECURITY_ENFORCED
    ];
  }

  /**
   * @description query User based on agentEmail
   * @param agentEmail agentEmail from Twilio
   * @return List of User
   */
  public List<User> fetchAgentUserId(String agentEmail) {
    if (String.isBlank(agentEmail) || SObjectType.User.isQueryable() == false) {
      return new List<User>();
    }

    return [
      SELECT Id, FederationIdentifier
      FROM User
      WHERE FederationIdentifier = :agentEmail AND IsActive = TRUE
    ];
  }

  /**
   * @description query ocvId based on customer on Interaction
   * @param refObject object reference to get OCVId from related account
   * @param recordId record id
   * @return SObject
   */
  public SObject fetchOCVId(String refObject, String recordId) {
    Schema.DescribeSObjectResult describeResult = Schema.getGlobalDescribe()
      .get(refObject)
      .getDescribe();
    if (String.isBlank(refObject) || !describeResult.isQueryable()) {
      return null;
    }
    return Database.query(
      'SELECT Account.OCV_ID__c FROM ' +
        String.escapeSingleQuotes(refObject) +
        ' WHERE Id = :recordId'
    );
  }

  /**
   * @description find accounts based on OCVId
   * @param ocvId String ocvid to search account details
   * @return Account record
   */
  public Account findAccountByOCVId(String ocvId) {
    PermissionUtils.canQuery('Account');
    return [
      SELECT PersonContactId
      FROM Account
      WHERE
        OCV_ID__c = :ocvId
        AND RecordTypeId = :QueryRT.of(Account.SObjectType)
          .getId('PersonAccount')
        AND ANZx_Customer__c = TRUE
    ];
  }
}