force-app/main/default/objects/Account/fields/ANZx_Customer__c.field-meta.xml
<CustomField>
    <fullName>ANZx_Customer__c</fullName>
    <complianceGroup>Integrity_Accurate;Source_OCV;Privacy_Personal_Information</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Customer has ANZ Plus account(s)</description>
    <inlineHelpText>Customer has ANZ Plus account(s)</inlineHelpText>
    <label>ANZ Plus Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ResidentialLoanApplication/fields/Assessment_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Outcome__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <description>Text field that captures the assessment outcome of the application e.g. Approved , declined etc.,</description>
    <label>Assessment Outcome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ResidentialLoanApplication/fields/Credit_ID__c.field-meta.xml
<CustomField>
    <fullName>Credit_ID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <description>A unique ID that identifies a credit enquiry against the home loan application</description>
    <label>Credit ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ResidentialLoanAppTriggerHandlerTest.cls
/**
 * @author Peter Charalambous
 * @since 08/2023
 * @description test class for Residential Loan Application trigger handler
 */
@isTest
public with sharing class ResidentialLoanAppTriggerHandlerTest {
  @TestSetup
  static void setup() {
    Faker faker = new Faker('AU');
    Account accnt = new Account(
      FirstName = faker.person.firstName(),
      LastName = faker.person.lastName(),
      OCV_ID__c = faker.randomString(10),
      ANZx_Customer__c = true,
      RecordTypeId = GetHelpConstants.ACCOUNT_PERSON_ACCOUNT_RT_ID
    );
    insert accnt;

    //Create RLA records with no owner
    List<ResidentialLoanApplication> rlaList = new List<ResidentialLoanApplication>();
    for (Integer i = 0; i < Integer.valueOf(Label.Test_Bulk_Size); i++) {
      rlaList.add(
        new ResidentialLoanApplication(
          Name = faker.randomString(5),
          Credit_ID__c = faker.randomString(4),
          Assessment_Outcome__c = 'Approved',
          AccountId = accnt.Id,
          RecordTypeId = GetHelpConstants.LOAN_APPLICATION_RT_ID
        )
      );
    }
    insert rlaList;
  }

  @isTest
  static void testLoanAppOwnerAssignment() {
    Faker faker = new Faker('AU');

    Group homeLoanAppQueue = [
      SELECT Id
      FROM Group
      WHERE developername = 'Home_Loan_Applications_Queue' AND Type = 'Queue'
    ];

    Test.startTest();

    List<ResidentialLoanApplication> rlaList = [
      SELECT OwnerId
      FROM ResidentialLoanApplication
      LIMIT :Integer.valueOf(Label.Test_Bulk_Size)
    ];

    for (ResidentialLoanApplication rla : rlaList) {
      Assert.areEqual(
        rla.OwnerId,
        homeLoanAppQueue.Id,
        'Owner should be Home Loan Applications Queue'
      );
    }
    Test.stopTest();
  }
}