force-app/main/default/objects/Account/fields/ANZx_Customer__c.field-meta.xml
<CustomField>
    <fullName>ANZx_Customer__c</fullName>
    <complianceGroup>Integrity_Accurate;Source_OCV;Privacy_Personal_Information</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Customer has ANZ Plus account(s)</description>
    <inlineHelpText>Customer has ANZ Plus account(s)</inlineHelpText>
    <label>ANZ Plus Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Personal Information</complianceGroup>
    <description>The name the customer prefers to be displayed online which defaults to FinServ_PreferredName_pc unless blank, and if the latter, uses the Name.

Display name is pushed from OCV, and is first+last</description>
    <label>Display Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ANZx_Customer__c.field-meta.xml
<CustomField>
    <fullName>ANZx_Customer__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>This checkbox is used to display if case is ANZx related.</description>
    <label>ANZx Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Card_Token_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Token_Number__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Trusted;Source - Fabric</complianceGroup>
    <description>Tokenised number of the credit card as per ANZ data policies</description>
    <label>Card Token Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dispute_Reason__c.field-meta.xml
<CustomField>
    <fullName>Dispute_Reason__c</fullName>
    <complianceGroup>Source_Salesforce;Integrity_Trusted;Privacy_Non_Personal_Information</complianceGroup>
    <description>To select dispute reason related to the ATM transaction</description>
    <inlineHelpText>Please select dispute reason</inlineHelpText>
    <label>Dispute Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amount not received by payee</fullName>
            </value>
            <value>
                <fullName>Cancellation of regular payment arrangement was unsuccessful</fullName>
            </value>
            <value>
                <fullName>Duplicate Transaction</fullName>
            </value>
            <value>
                <fullName>Unauthorised Transaction</fullName>
            </value>
            <value>
                <fullName>Trace Request</fullName>
            </value>
            <value>
                <fullName>Cash Dispensing Error</fullName>
            </value>
            <value>
                <fullName>Urgent Dishonour Request</fullName>
            </value>
            <value>
                <fullName>Don&apos;t recognise the transaction</fullName>
            </value>
            <value>
                <fullName>Didn&apos;t authorise transaction</fullName>
            </value>
            <value>
                <fullName>Duplicate Transactions</fullName>
            </value>
            <value>
                <fullName>Charged more than once</fullName>
            </value>
            <value>
                <fullName>Charged Incorrect Amount</fullName>
            </value>
            <value>
                <fullName>Charged for a cancelled payment</fullName>
            </value>
            <value>
                <fullName>Refund error</fullName>
            </value>
            <value>
                <fullName>Product Didn&apos;t Arrive</fullName>
            </value>
            <value>
                <fullName>Product Defective or Unsatisfactory</fullName>
            </value>
            <value>
                <fullName>Incorrect BSB/ Account number</fullName>
            </value>
            <value>
                <fullName>Incorrect Amount</fullName>
            </value>
            <value>
                <fullName>Payee has not received funds</fullName>
            </value>
            <value>
                <fullName>Fraudulent transaction</fullName>
            </value>
            <value>
                <fullName>Payment debited after debit authority cancelled</fullName>
            </value>
            <value>
                <fullName>Payment Duplicated</fullName>
            </value>
            <value>
                <fullName>Payment Overdrawn</fullName>
            </value>
            <value>
                <fullName>Unsolicited</fullName>
            </value>
            <value>
                <fullName>Incorrect Account Details</fullName>
            </value>
            <value>
                <fullName>Incorrect Amount Transferred</fullName>
            </value>
            <value>
                <fullName>Confirm Payee Name (Only for Salesforce)</fullName>
            </value>
            <value>
                <fullName>Return money received from an unknown person</fullName>
            </value>
            <value>
                <fullName>Claim not for value</fullName>
            </value>
            <value>
                <fullName>Incorrect Biller Code</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Has_The_Card_Been_Stopped__c.field-meta.xml
<CustomField>
    <fullName>Has_The_Card_Been_Stopped__c</fullName>
    <complianceGroup>Integrity - Trusted;Source - Salesforce;Privacy - Personal Information</complianceGroup>
    <defaultValue>&quot;NA&quot;</defaultValue>
    <description>To check whether the card was stopped by the customer before lodging dispute case</description>
    <inlineHelpText>Only applicable for dispute reason:
·         Cardholder did not authorise transaction 
·         Additional transactions for an existing lost/stolen/fraud case</inlineHelpText>
    <label>Has The Card Been Stopped?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
                <default>true</default>
                <label>NA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Is_The_Card_Lost_Stolen__c.field-meta.xml
<CustomField>
    <fullName>Is_The_Card_Lost_Stolen__c</fullName>
    <complianceGroup>Integrity - Trusted;Source - Salesforce</complianceGroup>
    <defaultValue>&quot;NA&quot;</defaultValue>
    <description>To check whether the customer&apos;s card was lost or stolen before lodging the dispute case</description>
    <inlineHelpText>Only applicable for dispute reasons:
·         Cardholder does not recognise transaction</inlineHelpText>
    <label>Is The Card Lost/Stolen?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Stolen</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
                <default>true</default>
                <label>NA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/OCV_Id__c.field-meta.xml
<CustomField>
    <fullName>OCV_Id__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Personal_Information;Source_OCV</complianceGroup>
    <description>OCV ID of the customer</description>
    <externalId>true</externalId>
    <label>OCV Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Queue__c.field-meta.xml
<CustomField>
    <fullName>Queue__c</fullName>
    <complianceGroup>Privacy_Personal_Information</complianceGroup>
    <description>Populates the Queue Name when Case Owner is Queue. Case Ownership changes when queue member accepts the case, hence stamping the queue name to get that visibility</description>
    <label>Queue</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Submitted__c.field-meta.xml
<CustomField>
    <fullName>Submitted__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Checkbox to initiate case assignment through rules.</description>
    <inlineHelpText>Checkbox to initiate case assignment through rules.</inlineHelpText>
    <label>Submitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Salesforce_Library_Settings__c/Salesforce_Library_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains settings used by Salesforce Library classes</description>
    <label>Salesforce Library Settings</label>
</CustomObject>

force-app/main/default/objects/Salesforce_Library_Settings__c/fields/Disable_Triggers__c.field-meta.xml
<CustomField>
    <fullName>Disable_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, triggers will be disabled.</description>
    <inlineHelpText>If checked, triggers will be disabled.</inlineHelpText>
    <label>Disable Triggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SubmitDisputeControllerTest.cls
/**
 *
 * @author Rebecca Jan
 * @since 2021
 * @description SubmitDisputeControllerTest is the test class for the SubmitDisputeController class
 */
@isTest
public with sharing class SubmitDisputeControllerTest {
  @TestSetup
  // Turn off triggers to run tests
  static void turnOffTriggers() {
    // Create test data for account case
    Account acc = new Account(
      Name = 'TestAccount',
      Display_Name__c = 'TestAccount',
      OCV_ID__c = 'OCV78786678',
      ANZx_Customer__c = true
    );
    insert acc;
    insert new Case(
      RecordTypeID = GetHelpConstants.CARD_DISPUTE_RT_ID,
      Subject = 'Test Disputes',
      Type = 'Cards',
      Dispute_Reason__c = 'Don\'t recognise the transaction',
      AccountId = acc.Id,
      Is_The_Card_Lost_Stolen__c = 'Lost',
      Has_The_Card_Been_Stopped__c = 'Yes',
      Status = 'Open',
      Queue__c = null,
      Description = 'Some description'
    );
    insert new Salesforce_Library_Settings__c(
      SetupOwnerId = UserInfo.getOrganizationId(),
      Disable_Triggers__c = true
    );
  }

  @isTest
  static void submitDisputeFlagTest() {
    Case c = [SELECT Id FROM Case LIMIT 1];
    Test.startTest();
    try {
      Boolean result = SubmitDisputeController.updateSubmitFlag(c.Id);
      System.assertEquals(
        true,
        result,
        'The controller failed to update Submitted__c to true.'
      );
    } catch (Exception ex) {
      if (ex.getMessage().contains('Dispute unable to be submitted')) {
        System.assert(true, 'Error message displayed');
      } else {
        System.assert(false, 'Incorrect error message');
      }
    }
    Test.stopTest();
  }

  @isTest
  static void testMissingCardTokenNumberCardDispute() {
    Case c = [SELECT Id FROM Case LIMIT 1];

    Test.startTest();
    Boolean cardNumberIsMissing = SubmitDisputeController.verifyCardTokenNumber(
      c.Id
    );
    Test.stopTest();

    System.assertEquals(
      true,
      cardNumberIsMissing,
      'The controller should confirm card number is missing.'
    );
  }

  @isTest
  static void testCardTokenNumberNotStoredDirectEntryDispute() {
    Case c = [SELECT Id FROM Case LIMIT 1];
    c.RecordTypeId = GetHelpConstants.DIRECT_DEBIT_DISPUTE_RT_ID;
    update c;

    Test.startTest();
    Boolean cardNumberIsMissing = SubmitDisputeController.verifyCardTokenNumber(
      c.Id
    );

    Test.stopTest();

    System.assertEquals(
      false,
      cardNumberIsMissing,
      'The controller should confirm card number is not missing as not required for this dispute type.'
    );
  }

  @isTest
  static void testCardTokenNumberExists() {
    Case c = [SELECT Id, Card_Token_Number__c FROM Case LIMIT 1];

    c.Card_Token_Number__c = '8051997368527878';
    update c;

    Test.startTest();
    Boolean cardNumberIsMissing = SubmitDisputeController.verifyCardTokenNumber(
      c.Id
    );
    Test.stopTest();

    System.assertEquals(
      false,
      cardNumberIsMissing,
      'The controller should confirm card number was not missing.'
    );
  }
}