force-app/main/default/objects/Account/fields/ANZx_Customer__c.field-meta.xml
<CustomField>
    <fullName>ANZx_Customer__c</fullName>
    <complianceGroup>Integrity_Accurate;Source_OCV;Privacy_Personal_Information</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Customer has ANZ Plus account(s)</description>
    <inlineHelpText>Customer has ANZ Plus account(s)</inlineHelpText>
    <label>ANZ Plus Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <description>Used for writing updates from OCV Party event messages. It is constructed in Mulesoft.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Deliquent</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__Card__c/FinServ__Card__c.object-meta.xml
<CustomObject>
    <description>Represents client financial account associated card details</description>
    <label>Card</label>
    <nameField>
        <label>Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__Card__c/fields/FinServ__AccountHolder__c.field-meta.xml
<CustomField>
    <fullName>FinServ__AccountHolder__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy - Personal Information</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Holder</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cards</relationshipLabel>
    <relationshipName>Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__Card__c/fields/FinServ__FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccount__c</fullName>
    <complianceGroup>Integrity_Accurate</complianceGroup>
    <label>Financial Account</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Financial Account Card</relationshipLabel>
    <relationshipName>FinancialAccountCard</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FinServ__Card__c/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Personal Information</complianceGroup>
    <formula>FinServ__FinancialAccount__r.OCV_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OCV_ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Account_Key__c.field-meta.xml
<CustomField>
    <fullName>Account_Key__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Field to store unique identifier for a Financial Account record received from OCV</description>
    <externalId>true</externalId>
    <label>Account Key</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__Balance__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Balance__c</fullName>
    <complianceGroup>Source_CTM;Integrity - Highly Trusted;Privacy - Personal Information</complianceGroup>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__CurrentPostedBalance__c.field-meta.xml
<CustomField>
    <fullName>FinServ__CurrentPostedBalance__c</fullName>
    <complianceGroup>Source_CTM;Integrity - Highly Trusted</complianceGroup>
    <label>Current Posted Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__FinancialAccountType__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccountType__c</fullName>
    <complianceGroup>Integrity - Accurate</complianceGroup>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Brokerage</fullName>
            </value>
            <value>
                <fullName>Discount Brokerage</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>Checking</fullName>
            </value>
            <value>
                <fullName>Cash Management Account</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Mutual Fund</fullName>
            </value>
            <value>
                <fullName>Fixed Annuity</fullName>
            </value>
            <value>
                <fullName>Variable Annuity</fullName>
            </value>
            <value>
                <fullName>Managed Account</fullName>
            </value>
            <value>
                <fullName>Individual Life</fullName>
            </value>
            <value>
                <fullName>Term Life</fullName>
            </value>
            <value>
                <fullName>Variable Life</fullName>
            </value>
            <value>
                <fullName>Whole Life</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__PrimaryOwner__c.field-meta.xml
<CustomField>
    <fullName>FinServ__PrimaryOwner__c</fullName>
    <complianceGroup>Integrity - Accurate</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
    <relationshipName>ClientFinancialAccounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <complianceGroup>Integrity_Accurate</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Charge-off</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Paid out</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <formula>FinServ__PrimaryOwner__r.OCV_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OCV_ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Primary_Owner_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Primary_Owner_Start_Date__c</fullName>
    <complianceGroup>Integrity_Trusted;Source_OCV</complianceGroup>
    <description>Date when current primary owner relationship started. Field is provided by OCV</description>
    <label>Primary Owner Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CardDetailsControllerTest.cls
@isTest
public with sharing class CardDetailsControllerTest {
  @isTest
  public static void testCardRetrieval() {
    Faker faker = new Faker('AU');

    Account accnt = new Account();
    accnt.Name = 'TestAccount';
    accnt.OCV_ID__c = faker.randomString(10);
    accnt.ANZx_Customer__c = true;
    accnt.External_Id__c = '82jfsa80534';
    insert accnt;

    FinServ__FinancialAccount__c finAccount = new FinServ__FinancialAccount__c();
    finAccount.Name = 'Test Account';
    finAccount.FinServ__Balance__c = faker.randomIntegerBetween(1, 400);
    finAccount.FinServ__CurrentPostedBalance__c = faker.randomIntegerBetween(
      1,
      400
    );
    finAccount.FinServ__Status__c = 'Open';
    finAccount.FinServ__FinancialAccountType__c = 'Checking';
    finAccount.FinServ__PrimaryOwner__c = accnt.Id;
    finAccount.Account_Key__c = '342490981';
    finAccount.Primary_Owner_Start_Date__c = Date.valueOf('2021-02-11');
    insert finAccount;

    FinServ__Card__c card = new FinServ__Card__c();
    card.Name = 'Test Card';
    card.FinServ__AccountHolder__c = accnt.Id;
    card.FinServ__FinancialAccount__c = finAccount.Id;
    insert card;

    Test.startTest();

    List<FinServ__Card__c> cardList = CardDetailsController.getCardDetails(
      card.Id
    );

    System.assertEquals(
      1,
      cardList.size(),
      'Card list size should be as expected.'
    );

    Test.stopTest();
  }
}