force-app/main/default/objects/Account/fields/ANZx_Customer__c.field-meta.xml
<CustomField>
    <fullName>ANZx_Customer__c</fullName>
    <complianceGroup>Integrity_Accurate;Source_OCV;Privacy_Personal_Information</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Customer has ANZ Plus account(s)</description>
    <inlineHelpText>Customer has ANZ Plus account(s)</inlineHelpText>
    <label>ANZ Plus Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Deliquent</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Prospect__c.field-meta.xml
<CustomField>
    <fullName>Is_Prospect__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Flag to indicate Account is prospect or not.</description>
    <formula>(RecordType.DeveloperName = &apos;Business_Account&apos; || IsPersonAccount) &amp;&amp;
ISPICKVAL(FinServ__Status__c, &apos;Prospect&apos;) &amp;&amp;
Source_System_Name__c = $Label.CCRM_Source_System_Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Prospect</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Source_System_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_System_Name__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Source System Name of Party received from OCV (E.g. CAP)</description>
    <externalId>true</externalId>
    <label>Source System Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CommercialAccountRepository.cls
/**
 * @author Naman Garg
 * @since 09/2024
 * @description This class provide SOQL and DML helper for class related to CommercialContactActionsHelper.
 */

public with sharing class CommercialAccountRepository {
  /**
   * @description It will fetch the accounts related to contacts
   * @param accIds Set of accountIds
   * @return List<Account> return List of Accounts
   */
  public List<Account> fetchAccounts(Set<Id> accIds) {
    if (!PermissionUtils.canQuery('Account')) {
      return new List<Account>();
    }
    return [
      SELECT
        Id,
        Is_Prospect__c,
        isPersonAccount,
        RecordTypeId,
        FinServ__Status__c,
        Source_System_Name__c,
        ANZx_Customer__c
      FROM Account
      WHERE Id IN :accIds
    ];
  }
}