force-app/main/default/objects/Account/fields/ANZx_Customer__c.field-meta.xml
<CustomField>
    <fullName>ANZx_Customer__c</fullName>
    <complianceGroup>Integrity_Accurate;Source_OCV;Privacy_Personal_Information</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Customer has ANZ Plus account(s)</description>
    <inlineHelpText>Customer has ANZ Plus account(s)</inlineHelpText>
    <label>ANZ Plus Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ResidentialLoanApplication/fields/Assessment_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Outcome__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <description>Text field that captures the assessment outcome of the application e.g. Approved , declined etc.,</description>
    <label>Assessment Outcome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ResidentialLoanApplication/fields/Credit_ID__c.field-meta.xml
<CustomField>
    <fullName>Credit_ID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <description>A unique ID that identifies a credit enquiry against the home loan application</description>
    <label>Credit ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ResidentialLoanApplication/fields/SOP_Id__c.field-meta.xml
<CustomField>
    <fullName>SOP_Id__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <description>Application Statement of Position ID</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>SOP Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ViewServiceabilityControllerTest.cls
/**
 * @author Mani
 * @since July 2023
 * @description ViewServiceabilityControllerTest is provide unit test coverage for ViewServiceabilityController.
 */
@isTest
private class ViewServiceabilityControllerTest {
  private static Faker faker;
  /**
   * @description Setup data for test classes
   */
  @testSetup
  public static void setup() {
    faker = new Faker('AU');

    List<Account> applicants = new List<Account>();
    applicants.add(getTestAccount('Sara', 'khan', '1000990280'));
    applicants.add(getTestAccount('Cameron', 'hanks', '1000990281'));
    applicants.add(getTestAccount('John', 'Tran', '1000990282'));
    applicants.add(getTestAccount('yuri', 'wang', '1000990283'));
    applicants.add(getTestAccount('Alan', 'king', '1000990284'));
    insert applicants;

    List<ResidentialLoanApplication> rlaLst = new List<ResidentialLoanApplication>();
    rlaLst.add(
      getTestResidentialLoanApplication(applicants[0].Id, '123', '123', '123')
    );
    rlaLst.add(
      getTestResidentialLoanApplication(applicants[1].Id, '456', '456', '')
    );
    insert rlaLst;
  }

  private static Account getTestAccount(
    string name,
    String lastname,
    String ocvId
  ) {
    return new Account(
      FirstName = name,
      LastName = lastname,
      OCV_ID__c = ocvId,
      ANZx_Customer__c = true,
      RecordTypeId = GetHelpConstants.ACCOUNT_PERSON_ACCOUNT_RT_ID,
      PersonMobilePhone = '0401' + faker.randomInteger(6)
    );
  }

  private static ResidentialLoanApplication getTestResidentialLoanApplication(
    string accId,
    string name,
    String sopId,
    String creditId
  ) {
    return new ResidentialLoanApplication(
      Name = name,
      AccountId = accId,
      Credit_ID__c = creditId,
      SOP_Id__c = sopId,
      Assessment_Outcome__c = 'Approved'
    );
  }

  @isTest
  static void testgetUMIAssessments() {
    Test.startTest();
    ResidentialLoanApplication rla = [
      SELECT Id
      FROM ResidentialLoanApplication
      WHERE Name = '123'
      LIMIT 1
    ];
    Map<String, Object> inputMap = new Map<String, Object>();
    Map<String, Object> outMap = new Map<String, Object>();
    ViewServiceabilityController ctrl = new ViewServiceabilityController();

    inputMap.put('loanId', rla.Id);
    Boolean isInvoked = ctrl.invokeMethod(
      'getUMIAssessments',
      inputMap,
      outMap,
      new Map<String, Object>()
    );
    Map<String, Object> payload = (Map<String, Object>) outMap.get('result');
    Test.stopTest();
    System.assert(isInvoked, 'Method not invoked');
    System.assertNotEquals(payload, null, 'Empty JSON');
    System.assert(
      (Boolean) payload.get('hasError') == false,
      'Invalid response'
    );
    System.assert(
      (Boolean) payload.get('isSubmitted'),
      'Application is should be submitted'
    );
  }
  @isTest
  static void testgetUMIAssessmentsWithError() {
    Test.startTest();
    ResidentialLoanApplication rla = [
      SELECT Id
      FROM ResidentialLoanApplication
      WHERE Name = '456'
      LIMIT 1
    ];
    Map<String, Object> inputMap = new Map<String, Object>();
    Map<String, Object> outMap = new Map<String, Object>();
    ViewServiceabilityController ctrl = new ViewServiceabilityController();

    inputMap.put('loanId', rla.Id);
    Boolean isInvoked = ctrl.invokeMethod(
      'getUMIAssessments',
      inputMap,
      outMap,
      new Map<String, Object>()
    );
    Map<String, Object> payload = (Map<String, Object>) outMap.get('result');
    Test.stopTest();
    System.assert(isInvoked, 'Method not invoked');
    System.assertNotEquals(payload, null, 'Empty JSON');
    System.assert((Boolean) payload.get('hasError'), 'Invalid response');
  }
  @isTest
  static void testBOHServicegetUMIAssessments() {
    Test.setMock(HttpCalloutMock.class, new MockViewUMICallout());
    String loanId = '123';
    BOHService serv = new BOHService();
    Cache.Session.put(
      AuthTokenCacheUtil.STAFFPART +
      'forgeJWTToken' +
      loanId,
      AuthServiceTest.IDTESTVALUE
    );
    Test.startTest();
    HttpCalloutResponse res = serv.getUMIAssessments(
      new List<String>{ loanId },
      loanId,
      loanId
    );
    Test.stopTest();
    System.assertEquals(res.statusCode, 200, 'api call unsucessfully');
  }
  /**
   * @description Mock view umi api callout
   */
  public class MockViewUMICallout implements HttpCalloutMock {
    /**
     * @description mock response for callout
     * @param req incoming request
     * @return HTTPResponse invalid response
     */
    public HTTPResponse respond(HTTPRequest req) {
      string jsonBody = Service.getStaticResource('mock_UMIListAssessments');
      HTTPResponse res = new HTTPResponse();
      res.setStatusCode(200);
      res.setHeader('Content-Type', 'application/json');
      res.setBody(jsonBody);
      return res;
    }
  }
}