force-app/main/default/objects/Account/fields/ANZx_Customer__c.field-meta.xml
<CustomField>
    <fullName>ANZx_Customer__c</fullName>
    <complianceGroup>Integrity_Accurate;Source_OCV;Privacy_Personal_Information</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Customer has ANZ Plus account(s)</description>
    <inlineHelpText>Customer has ANZ Plus account(s)</inlineHelpText>
    <label>ANZ Plus Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ANZx_Customer__c.field-meta.xml
<CustomField>
    <fullName>ANZx_Customer__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>This checkbox is used to display if case is ANZx related.</description>
    <label>ANZx Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/CustomerOnboardingApplication__c.field-meta.xml
<CustomField>
    <fullName>CustomerOnboardingApplication__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup relationship field that looks up to the Customer Onboarding Application object</description>
    <label>Customer Onboarding Application</label>
    <referenceTo>CustomerOnboardingApplication__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/OCV_Id__c.field-meta.xml
<CustomField>
    <fullName>OCV_Id__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Personal_Information;Source_OCV</complianceGroup>
    <description>OCV ID of the customer</description>
    <externalId>true</externalId>
    <label>OCV Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PersonaId__c.field-meta.xml
<CustomField>
    <fullName>PersonaId__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>The ForgeRock-minted UUID identifying the persona attempting to onboard</description>
    <externalId>true</externalId>
    <label>Persona Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CustomerOnboardingApplication__c/CustomerOnboardingApplication__c.object-meta.xml
<CustomObject>
    <label>Customer Onboarding Application</label>
    <nameField>
        <displayFormat>COB-{00000000}</displayFormat>
        <label>Customer Onboarding Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Onboarding Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerOnboardingApplication__c/fields/OCVId__c.field-meta.xml
<CustomField>
    <fullName>OCVId__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>The OCVID supplied by OCV, which initially refers to the shadow profile and eventually the full customer profile</description>
    <label>OCV Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerOnboardingApplication__c/fields/PersonaId__c.field-meta.xml
<CustomField>
    <fullName>PersonaId__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>The ForgeRock-minted UUID identifying the persona attempting to onboard</description>
    <externalId>true</externalId>
    <label>Persona Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/COBApplicationActionsHelperTest.cls
/**
 * @author Batya Aisman Sufrin
 * @date May 2023
 * @description Test class for {@link COBApplicationActionsHelper}
 * @group ANZx
 */
@isTest
public with sharing class COBApplicationActionsHelperTest {
  private static final Faker FAKER = new Faker('AU');
  private static final Set<String> OCV_IDS = new Set<String>{
    '0123456789',
    '9876543210'
  };

  private static final Integer OCV_IDS_COUNT = OCV_IDS.size();

  @TestSetup
  private static void makeData() {
    List<Account> personAccounts = new List<Account>();
    List<CustomerOnboardingApplication__c> cobApps = new List<CustomerOnboardingApplication__c>();

    for (String ocvId : OCV_IDS) {
      personAccounts.add(createPersonAccount(ocvId));
      cobApps.add(createCOBApp(ocvId));
    }

    insert personAccounts;
    insert cobApps;
  }

  private static Account createPersonAccount(String ocvId) {
    Account acc = new Account(
      FirstName = FAKER.person.firstName(),
      LastName = FAKER.person.lastName(),
      OCV_ID__c = ocvId,
      ANZx_Customer__c = true,
      RecordTypeId = GetHelpConstants.ACCOUNT_PERSON_ACCOUNT_RT_ID
    );

    return acc;
  }

  private static CustomerOnboardingApplication__c createCOBApp(String ocvId) {
    return new CustomerOnboardingApplication__c(
      OCVId__c = ocvId,
      PersonaId__c = FAKER.randomString(15)
    );
  }

  private static List<CustomerOnboardingApplication__c> getCOBApps() {
    return [
      SELECT Id, OCVId__c, PersonaId__c
      FROM CustomerOnboardingApplication__c
    ];
  }

  @isTest
  private static void testCreateKYCQACase() {
    List<CustomerOnboardingApplication__c> cobApps = getCOBApps();

    for (CustomerOnboardingApplication__c cobApp : cobApps) {
      Case kycQACase = COBApplicationActionsHelper.createKYCQACase(cobApp);

      Assert.areEqual(
        cobApp.OCVId__c,
        kycQACase.OCV_Id__c,
        'The Case OCV ID should have been the same as COB App OCV Id'
      );
      Assert.areEqual(
        cobApp.PersonaId__c,
        kycQACase.PersonaId__c,
        'The Case Persona Id should have been the same as COB App Persona Id'
      );
      Assert.areEqual(
        cobApp.id,
        kycQACase.CustomerOnboardingApplication__c,
        'The Case COB App lookup should have been the same as COB App Id'
      );
    }
  }

  @isTest
  private static void testGetAccountsByOCVID() {
    Test.startTest();
    List<Account> accountsByOCVIds = COBApplicationActionsHelper.getAccountsByOCVID(
      OCV_IDS
    );
    Test.stopTest();

    Assert.areEqual(
      OCV_IDS_COUNT,
      accountsByOCVIds.size(),
      'There should be ' +
      OCV_IDS_COUNT +
      ' accounts.'
    );
  }

  @isTest
  private static void testGetAccountsByOCVIDEmptySet() {
    List<Account> accountsByOCVIds = COBApplicationActionsHelper.getAccountsByOCVID(
      new Set<String>()
    );

    Assert.isTrue(
      accountsByOCVIds.isEmpty(),
      'There should be an empty list of Accounts.'
    );
  }
}