force-app/main/default/objects/Account/fields/ANZx_Customer__c.field-meta.xml
<CustomField>
    <fullName>ANZx_Customer__c</fullName>
    <complianceGroup>Integrity_Accurate;Source_OCV;Privacy_Personal_Information</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Customer has ANZ Plus account(s)</description>
    <inlineHelpText>Customer has ANZ Plus account(s)</inlineHelpText>
    <label>ANZ Plus Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Personal Information</complianceGroup>
    <description>The name the customer prefers to be displayed online which defaults to FinServ_PreferredName_pc unless blank, and if the latter, uses the Name.

Display name is pushed from OCV, and is first+last</description>
    <label>Display Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <description>Used for writing updates from OCV Party event messages. It is constructed in Mulesoft.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source - Simpology</complianceGroup>
    <description>Unique identifier for Integration</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CFaaS_File__c/CFaaS_File__c.object-meta.xml
<CustomObject>
    <description>This will hold the file details/information that will be retrieved from CFaaS.</description>
    <label>CFaaS File</label>
    <nameField>
        <displayFormat>CFaaS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CFaaS Files</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CFaaS_File__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_CFaaS</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person/Commercial account, this file is linked to</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CFaaS Files</relationshipLabel>
    <relationshipName>CFaaS_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CFaaS_File__c/fields/Date_Created__c.field-meta.xml
<CustomField>
    <fullName>Date_Created__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_CFaaS</complianceGroup>
    <description>Created Date of the document in CFaaS</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Date Created</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CFaaS_File__c/fields/Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Id__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Integrity_Trusted;Source_CFaaS</complianceGroup>
    <description>Unique CFaaS Document Id</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Document Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CFaaS_File__c/fields/File_Description__c.field-meta.xml
<CustomField>
    <fullName>File_Description__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Integrity_Trusted;Source_CFaaS</complianceGroup>
    <description>File Description</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>File Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CFaaS_File__c/fields/File_Extension__c.field-meta.xml
<CustomField>
    <fullName>File_Extension__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Integrity_Trusted;Source_CFaaS</complianceGroup>
    <description>File Extension</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>File Extension</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CFaaS_File__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_CFaaS</complianceGroup>
    <description>Filename</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CFaaS_File__c/fields/Integrity_Classification__c.field-meta.xml
<CustomField>
    <fullName>Integrity_Classification__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_CFaaS</complianceGroup>
    <description>File Classification in CFaaS</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Integrity Classification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CFaaS_File__c/fields/Privacy_Classification__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Classification__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Integrity_Trusted;Source_CFaaS</complianceGroup>
    <description>File Classification in CFaaS</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Privacy Classification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CFaaS_File__c/fields/Security_Classification__c.field-meta.xml
<CustomField>
    <fullName>Security_Classification__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_CFaaS</complianceGroup>
    <description>File Classification in CFAAS</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Security Classification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/File.recordType-meta.xml
<RecordType>
    <fullName>File</fullName>
    <active>true</active>
    <description>Default record type for files</description>
    <label>File</label>
</RecordType>

force-app/main/default/objects/LogEntry__c/LogEntry__c.object-meta.xml
<CustomObject>
    <description>The child log record, stores logging information on a record/callout level</description>
    <label>Log Entry</label>
    <nameField>
        <displayFormat>LE-{0000}</displayFormat>
        <label>Log Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LogEntry__c/fields/LoggingLevel__c.field-meta.xml
<CustomField>
    <fullName>LoggingLevel__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>The logging level of the log entry record.</description>
    <label>Logging Level</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/fields/LogMessage__c.field-meta.xml
<CustomField>
    <fullName>LogMessage__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>A message or description of the log entry record.</description>
    <label>Log Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The origin of the request, an Apex class, a component or a flow.</description>
    <label>Origin</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>Id of the sobject record related to this log entry.</description>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/fields/RecordObjectName__c.field-meta.xml
<CustomField>
    <fullName>RecordObjectName__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>The object name of the record related to this log entry.</description>
    <label>Record Object Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LoggingSettings__c/LoggingSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom settings for more control on logging.</description>
    <label>Logging Settings</label>
</CustomObject>

force-app/main/default/objects/LoggingSettings__c/fields/DefaultLoggingLevel__c.field-meta.xml
<CustomField>
    <fullName>DefaultLoggingLevel__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Source - Salesforce;Integrity - Trusted</complianceGroup>
    <defaultValue>&quot;ERROR&quot;</defaultValue>
    <description>Default logging level for a user or profile. Values can be: ERROR, INFO, DEBUG.</description>
    <inlineHelpText>Default logging level for a user or profile. Values can be: ERROR, INFO, DEBUG.</inlineHelpText>
    <label>Default Logging Level</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LoggingSettings__c/fields/DefaultSaveMethod__c.field-meta.xml
<CustomField>
    <fullName>DefaultSaveMethod__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Source - Salesforce;Integrity - Trusted</complianceGroup>
    <defaultValue>&quot;EVENT_BUS&quot;</defaultValue>
    <description>Default save method for a user or profile. Values can be: EVENT_BUS or QUEUEABLE.</description>
    <inlineHelpText>Default save method for a user or profile. Values can be: EVENT_BUS or QUEUEABLE.</inlineHelpText>
    <label>Default Save Method</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LoggingSettings__c/fields/SecureLogEnabled__c.field-meta.xml
<CustomField>
    <fullName>SecureLogEnabled__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Source - Salesforce;Integrity - Trusted</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Specifies if Secure Log is enabled for a user or profile. If this is false, no secure logs will be created for the user/profile.</description>
    <inlineHelpText>Specifies if Secure Log is enabled for a user or profile. If this is false, no secure logs will be created for the user/profile.</inlineHelpText>
    <label>Secure Log Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ContentDownloadHandlerFactoryImplTest.cls
/**
 * @author Emma Bindi
 * @date November 2022
 * @description Test class for {@link ContentDownloadHandlerFactoryImpl}
 */
@isTest
public with sharing class ContentDownloadHandlerFactoryImplTest {
  @TestSetup
  static void setup() {
    // Add Logging Setting as ANZx Standard User
    Profile anzxUserProfile = CommonUtil.getProfileByName('ANZx Standard User');

    User anzxUser = TestUtil.createTestUser(
      new Map<String, Object>{
        'FirstName' => 'ANZx_User_Test',
        'ProfileId' => anzxUserProfile.Id
      }
    );
    insert anzxUser;

    System.runAs(anzxUser) {
      LoggingSettings__c userCustomSetting = new LoggingSettings__c(
        DefaultSaveMethod__c = 'QUEUEABLE',
        DefaultLoggingLevel__c = 'DEBUG',
        SecureLogEnabled__c = true,
        SetupOwnerId = anzxUser.Id
      );
      insert userCustomSetting;
    }

    Faker faker = new Faker('AU');
    Account acc = new Account(
      Name = 'TestAccount',
      Display_Name__c = 'TestAccount',
      OCV_ID__c = faker.randomString(10),
      ANZx_Customer__c = true,
      External_Id__c = faker.randomString(10)
    );
    insert acc;
  }

  @isTest
  static void testCFaaSFileDownloadLogging() {
    // GIVEN a ContentVersion of CFaaS File record type is inserted
    Faker faker = new Faker('AU');

    Account acc = [
      SELECT OCV_ID__c
      FROM Account
      WHERE Display_Name__c = 'TestAccount'
      LIMIT 1
    ];

    CFaaS_File__c file = new CFaaS_File__c(
      Document_Id__c = faker.randomString(35),
      File_Description__c = faker.randomString(5) +
        ' ' +
        faker.randomString(7) +
        ' ' +
        faker.randomString(8),
      File_Extension__c = '.jpeg',
      File_Name__c = faker.randomString(7) + ' ' + faker.randomString(6),
      Date_Created__c = faker.randomPastDateTime(),
      Customer__c = acc.Id,
      Privacy_Classification__c = 'Medium',
      Security_Classification__c = 'PROTECTED',
      Integrity_Classification__c = 'Confidential'
    );

    insert file;

    Id cfaasFileRecordTypeId = Schema.SObjectType.ContentVersion.getRecordTypeInfosByName()
      .get('CFaaS File')
      .getRecordTypeId();

    ContentVersion cv = new ContentVersion();
    cv.VersionData = Blob.valueOf('Test Content');
    cv.Title = file.Document_Id__c + ' - ' + file.Security_Classification__c;
    cv.PathOnClient = file.Document_Id__c + '.' + file.File_Extension__c;
    cv.RecordTypeId = cfaasFileRecordTypeId;
    cv.FirstPublishLocationId = file.Id;

    Database.SaveResult saveResult = Database.insert(cv, false);

    List<Id> idList = new List<Id>{ cv.Id };

    User anzxUser = [
      SELECT Id, FirstName
      FROM User
      WHERE FirstName = 'ANZx_User_Test'
      LIMIT 1
    ];

    // WHEN the file is accessed in the UI
    Test.startTest();
    System.runAs(anzxUser) {
      ContentDownloadHandlerFactoryImpl downloadHandlerFactory = new ContentDownloadHandlerFactoryImpl();

      Sfc.ContentDownloadHandler handler = downloadHandlerFactory.getContentDownloadHandler(
        idList,
        Sfc.ContentDownloadContext.S1
      );
      System.assertEquals(
        true,
        handler.isDownloadAllowed,
        'Download should be allowed'
      );
    }
    Test.stopTest();

    List<LogEntry__c> logEntryList = [
      SELECT
        LogMessage__c,
        Origin__c,
        RecordObjectName__c,
        RecordId__c,
        LoggingLevel__c
      FROM LogEntry__c
      LIMIT 1
    ];

    // THEN a log entry recording the download activity should exist
    System.assertNotEquals(0, logEntryList.size(), 'Log entry should exist');
  }

  @isTest
  static void testDefaultFileDownload() {
    // GIVEN a ContentVersion which is NOT a CFaaS File record type is inserted
    Account acc = [
      SELECT OCV_ID__c
      FROM Account
      WHERE Display_Name__c = 'TestAccount'
      LIMIT 1
    ];

    Id defaultFileRecordTypeId = Schema.SObjectType.ContentVersion.getRecordTypeInfosByName()
      .get('File')
      .getRecordTypeId();

    ContentVersion cv = new ContentVersion();
    cv.VersionData = Blob.valueOf('Test Content');
    cv.Title = 'Test Default File Type';
    cv.PathOnClient = 'TestFile.jpeg';
    cv.RecordTypeId = defaultFileRecordTypeId;
    cv.FirstPublishLocationId = acc.Id;

    Database.SaveResult saveResult = Database.insert(cv, false);

    List<Id> idList = new List<Id>{ cv.Id };

    User anzxUser = [
      SELECT Id, FirstName
      FROM User
      WHERE FirstName = 'ANZx_User_Test'
      LIMIT 1
    ];

    // WHEN the file is accessed in the UI
    Test.startTest();
    System.runAs(anzxUser) {
      ContentDownloadHandlerFactoryImpl downloadHandlerFactory = new ContentDownloadHandlerFactoryImpl();
      Sfc.ContentDownloadHandler handler = downloadHandlerFactory.getContentDownloadHandler(
        idList,
        Sfc.ContentDownloadContext.S1
      );
      System.assertEquals(
        true,
        handler.isDownloadAllowed,
        'Download should be allowed'
      );
    }
    Test.stopTest();

    List<LogEntry__c> logEntryList = [
      SELECT
        LogMessage__c,
        Origin__c,
        RecordObjectName__c,
        RecordId__c,
        LoggingLevel__c
      FROM LogEntry__c
      LIMIT 1
    ];

    // THEN there should not be any log entry recording the download activity
    System.assertEquals(0, logEntryList.size(), 'Log entry should not exist');
  }
}