force-app/main/default/objects/Account/fields/ANZx_Customer__c.field-meta.xml
<CustomField>
    <fullName>ANZx_Customer__c</fullName>
    <complianceGroup>Integrity_Accurate;Source_OCV;Privacy_Personal_Information</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Customer has ANZ Plus account(s)</description>
    <inlineHelpText>Customer has ANZ Plus account(s)</inlineHelpText>
    <label>ANZ Plus Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Source_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_System_ID__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Source System Id of Party received from OCV</description>
    <label>Source System ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ANZx_Customer__c.field-meta.xml
<CustomField>
    <fullName>ANZx_Customer__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>This checkbox is used to display if case is ANZx related.</description>
    <label>ANZx Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/CaseNumber__c.field-meta.xml
<CustomField>
    <fullName>CaseNumber__c</fullName>
    <complianceGroup>Integrity - Trusted</complianceGroup>
    <description>Case Number, copied on insertion. Useful if we had to restore as the standard field is an auto-number.</description>
    <externalId>true</externalId>
    <label>Original Case Number</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_Notification_Consent__c.field-meta.xml
<CustomField>
    <fullName>Customer_Notification_Consent__c</fullName>
    <complianceGroup>Source_Salesforce;Integrity_Trusted;Privacy_Non_Personal_Information</complianceGroup>
    <description>A One-off SMS would be sent to the customer to notify them of the complaint reference number.</description>
    <inlineHelpText>A One-off SMS would be sent to the customer to notify them of the complaint reference number.</inlineHelpText>
    <label>Customer Notification Consent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_3rdParty_Email__c.field-meta.xml
<CustomField>
    <fullName>IDR_3rdParty_Email__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Personal Information</complianceGroup>
    <description>Nominated 3rd party email address</description>
    <label>Nominated 3rd party email address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_3rdParty_Mobile__c.field-meta.xml
<CustomField>
    <fullName>IDR_3rdParty_Mobile__c</fullName>
    <label>Nominated 3rd party mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_3rdParty_Name__c.field-meta.xml
<CustomField>
    <fullName>IDR_3rdParty_Name__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Personal Information</complianceGroup>
    <description>Nominated 3rd party name</description>
    <label>Nominated 3rd party name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_3rdParty_Relationship_To_Complainant__c.field-meta.xml
<CustomField>
    <fullName>IDR_3rdParty_Relationship_To_Complainant__c</fullName>
    <complianceGroup>Integrity_Accurate</complianceGroup>
    <label>Relationship to complainant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Accountant</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Anti-discrimination board</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Attorney</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Consumer Traders and Tenancy Tribunal</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Executor</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Financial Counsellor</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Friend</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Human Rights and Equal Opportunity</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>MP</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Office of Federal Privacy Commissioner</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Partner</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Relative</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Solicitor</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Trustee</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_Account_Card_Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>IDR_Account_Card_Policy_Number__c</fullName>
    <description>Account/Card/Policy the complaint relates to. Contents must be masked leaving last 4 digits identifiable.</description>
    <inlineHelpText>Account/Card/Policy the complaint relates to. Contents must be masked leaving last 4 digits identifiable.</inlineHelpText>
    <label>Account/Card/Policy Number</label>
    <length>42</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_Customer_Identifier__c.field-meta.xml
<CustomField>
    <fullName>IDR_Customer_Identifier__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Customer Identifier Type which is used to do the customer search</description>
    <label>Customer Identifier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer/Business CAP ID</fullName>
            </value>
            <value>
                <fullName>CACHE ID</fullName>
            </value>
            <value>
                <fullName>CRN</fullName>
                <isActive>false</isActive>
                <label>CRN</label>
            </value>
            <value>
                <fullName>RAZOR ID</fullName>
                <isActive>false</isActive>
                <label>RAZOR ID</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>IDR_Customer_Number__c</fullName>
    <complianceGroup>Integrity - Trusted</complianceGroup>
    <externalId>true</externalId>
    <inlineHelpText>Also known as Customer CAP CIS ID. Copy and paste this from MAUD</inlineHelpText>
    <label>Customer Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_NC_Email__c.field-meta.xml
<CustomField>
    <fullName>IDR_NC_Email__c</fullName>
    <description>Capture this only if complainant is not found in MAUD/CAP-CIS.</description>
    <inlineHelpText>Capture this only if complainant is not found in MAUD/CAP-CIS.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_NC_First_Name__c.field-meta.xml
<CustomField>
    <fullName>IDR_NC_First_Name__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Personal Information</complianceGroup>
    <description>First Name of Complainant.

Capture this only if customer is not found in MAUD/CAP-CIS.</description>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_NC_Is_Consent_Obtained__c.field-meta.xml
<CustomField>
    <fullName>IDR_NC_Is_Consent_Obtained__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>The script to read out to the complainant is located in the utility bar.</inlineHelpText>
    <label>Privacy Script Read and Consent Obtained</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_NC_Mobile__c.field-meta.xml
<CustomField>
    <fullName>IDR_NC_Mobile__c</fullName>
    <description>Capture this only if complainant is not found in MAUD/CAP-CIS.</description>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_SwicthOff_3rd_Party_Notification__c.field-meta.xml
<CustomField>
    <fullName>IDR_SwicthOff_3rd_Party_Notification__c</fullName>
    <complianceGroup>Source_Salesforce;Integrity_Accurate;Privacy_Non_Personal_Information</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>To control 3rd Party notifications to go out</description>
    <label>Switch off 3rd Party Notifications?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/IDR_SwitchOff_Customer_Notification__c.field-meta.xml
<CustomField>
    <fullName>IDR_SwitchOff_Customer_Notification__c</fullName>
    <complianceGroup>Source_Salesforce;Integrity_Accurate;Privacy_Non Personal Information</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>This is to control the Customer notifications to go out, If true notification will not go out</description>
    <label>Switch off Customer Notifications?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/OCV_Id__c.field-meta.xml
<CustomField>
    <fullName>OCV_Id__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Personal_Information;Source_OCV</complianceGroup>
    <description>OCV ID of the customer</description>
    <externalId>true</externalId>
    <label>OCV Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Complaint.recordType-meta.xml
<RecordType>
    <fullName>Complaint</fullName>
    <active>true</active>
    <businessProcess>Complaint Support Process</businessProcess>
    <description>Record a new complaint.</description>
    <label>Complaint</label>
</RecordType>

force-app/main/default/objects/IDR_Notification_Event__e/IDR_Notification_Event__e.object-meta.xml
<CustomObject>
    <description>IDR Notification Event to publish events when Case status changes to send notifications to customers via SMS and email</description>
    <label>IDR_Notification_Event</label>
    <pluralLabel>IDR_Notification_Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/IDR_Notification_Event__e/fields/CAP_CIS_ID__c.field-meta.xml
<CustomField>
    <fullName>CAP_CIS_ID__c</fullName>
    <description>CAP CIS ID for customer Case</description>
    <label>CAP_CIS_ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IDR_Notification_Event__e/fields/Case_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_ID__c</fullName>
    <description>ID of the Case record</description>
    <label>Case ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IDR_Notification_Event__e/fields/ComplainantMobile__c.field-meta.xml
<CustomField>
    <fullName>ComplainantMobile__c</fullName>
    <description>Customer Mobile for NON ANZ Customer</description>
    <label>Customer Mobile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IDR_Notification_Event__e/fields/SMSFlag__c.field-meta.xml
<CustomField>
    <fullName>SMSFlag__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Should SMS Needs to be sent</description>
    <label>SMSFlag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IDR_Notification_Hours__c/IDR_Notification_Hours__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to control the timing of the notifications sent out to customer.</description>
    <label>IDR Notification Hours</label>
</CustomObject>

force-app/main/default/objects/IDR_Notification_Hours__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>Enter the time in 24 hours</description>
    <label>End Time</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IDR_Notification_Hours__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Insert the time in 24 hours clock format</description>
    <label>Start Time</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification_Handler__c/Notification_Handler__c.object-meta.xml
<CustomObject>
    <description>This is to manage/organise the publish time of customer notification</description>
    <label>Notification Handler</label>
    <nameField>
        <displayFormat>NH-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Handler</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Handler__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <deleteConstraint>Cascade</deleteConstraint>
    <description>Related Case internal Id</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notification Handler</relationshipLabel>
    <relationshipName>Notification_Handler</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification_Handler__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Pending Publish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/classes/NotificationTriggerHandlerAnzxTest.cls
/**
 * @author Lance Shi
 * @since 11/2021
 * @description  To test NotificationTriggerHandler for anzx complaint cases
 */

@isTest
public class NotificationTriggerHandlerAnzxTest {
  /**
   * @description Test data setup required for this test class
   */
  @testSetup
  static void setup() {
    IDR_Notification_Hours__c nHours = new IDR_Notification_Hours__c();
    nHours.Start_Time__c = System.now().hour() - 1;
    nHours.End_Time__c = System.now().hour() + 2;
    insert nHours;

    Account personAcc = new Account(
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
        .get('PersonAccount')
        .getRecordTypeId(),
      FirstName = 'TestFirst',
      LastName = 'TestLast',
      OCV_ID__c = 'PERSONOCV879879',
      ANZx_Customer__c = true
    );
    insert personAcc;

    Case testCase = new Case();
    testCase.AccountId = personAcc.Id;
    testCase.IDR_Account_Card_Policy_Number__c = '000001234';
    testCase.Description = 'Test decription';
    testCase.RecordTypeId = GetHelpConstants.COMPLAINT_RT_ID;
    testCase.Customer_Notification_Consent__c = 'Yes';
    testCase.IDR_Customer_Number__c = '1234567890';
    testCase.Status = GetHelpConstants.OPEN_STATUS;

    insert testCase;
  }

  /**
   * @description Test Customer Notification based on the flag
   */
  @isTest
  static void testAnzxNotification() {
    List<Case> caseList = [SELECT Id FROM Case];
    test.startTest();
    List<Notification_Handler__c> nhList = [
      SELECT id
      FROM Notification_Handler__c
      WHERE case__c IN :caseList
    ];
    System.assertEquals(
      caseList.size(),
      nhList.size(),
      'Notification handler list size should be as expected.'
    );
    Test.stopTest();
  }

  /**
   * @description Test data setup required for this test class
   */

  @isTest
  static void testManualNotification() {
    //Retrieve the case inserted
    Case c = [
      SELECT
        Id,
        IDR_3rdParty_Email__c,
        IDR_3rdParty_Name__c,
        IDR_3rdParty_Mobile__c,
        IDR_Customer_Number__c,
        IDR_NC_Email__c,
        IDR_NC_Is_Consent_Obtained__c,
        CaseNumber__c,
        Customer_Notification_Consent__c,
        Account.Source_System_ID__c,
        Account.PersonMobilePhone,
        Account.PersonContact.FirstName,
        IDR_Customer_Identifier__c,
        CaseNumber,
        IDR_NC_First_Name__c,
        IDR_NC_Mobile__c,
        RecordTypeId,
        IDR_SwicthOff_3rd_Party_Notification__c,
        IDR_SwitchOff_Customer_Notification__c,
        IDR_3rdParty_Relationship_To_Complainant__c
      FROM Case
      LIMIT 1
    ];

    Test.startTest();
    //create the notification handler record Manually
    Notification_Handler__c handlerRecord = new Notification_Handler__c();
    handlerRecord.Case__c = c.Id;
    handlerRecord.Status__c = IDRConstants.NOTIFICATION_PUBLISH_STATUS;
    insert handlerRecord;

    IDR_Notification_Event__e evt = NotificationTriggerHandler.getNotifcationEvent(
      c,
      handlerRecord
    );

    Test.stopTest();

    Notification_Handler__c handlerPostExecution = [
      SELECT Id, Status__c
      FROM Notification_Handler__c
      ORDER BY CreatedDate DESC
      LIMIT 1
    ];

    //verify that notification is published successfully
    System.assertEquals(
      IDRConstants.NOTIFICATION_PUBLISH_STATUS,
      handlerPostExecution.Status__c,
      'Notification handler status should be as expected.'
    );

    System.assertEquals(
      null,
      evt.CAP_CIS_ID__c,
      'Event CAP_CIS_ID__c should be null.'
    );
    System.assertEquals(
      c.Id,
      evt.Case_ID__c,
      'Event Case_ID__c should be as expected.'
    );
    System.assertEquals(
      true,
      evt.SMSFlag__c,
      'Event SMSFlag__c should be as expected.'
    );
    System.assertEquals(
      c.Account.PersonMobilePhone,
      evt.ComplainantMobile__c,
      'Event Complainant Mobile Number should be as expected.'
    );
  }
}