force-app/main/default/objects/Account/fields/ANZx_Customer__c.field-meta.xml
<CustomField>
    <fullName>ANZx_Customer__c</fullName>
    <complianceGroup>Integrity_Accurate;Source_OCV;Privacy_Personal_Information</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Customer has ANZ Plus account(s)</description>
    <inlineHelpText>Customer has ANZ Plus account(s)</inlineHelpText>
    <label>ANZ Plus Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Personal Information</complianceGroup>
    <description>The name the customer prefers to be displayed online which defaults to FinServ_PreferredName_pc unless blank, and if the latter, uses the Name.

Display name is pushed from OCV, and is first+last</description>
    <label>Display Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <description>Used for writing updates from OCV Party event messages. It is constructed in Mulesoft.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information</complianceGroup>
    <description>Unique external ID of the customer</description>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CFaaS_File__c/CFaaS_File__c.object-meta.xml
<CustomObject>
    <description>This will hold the file details/information that will be retrieved from CFaaS.</description>
    <label>CFaaS File</label>
    <nameField>
        <displayFormat>CFaaS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CFaaS Files</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CFaaS_File__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_CFaaS</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person/Commercial account, this file is linked to</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CFaaS Files</relationshipLabel>
    <relationshipName>CFaaS_Files</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CFaaS_File__c/fields/Date_Created__c.field-meta.xml
<CustomField>
    <fullName>Date_Created__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_CFaaS</complianceGroup>
    <description>Created Date of the document in CFaaS</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Date Created</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CFaaS_File__c/fields/Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Id__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Integrity_Trusted;Source_CFaaS</complianceGroup>
    <description>Unique CFaaS Document Id</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Document Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CFaaS_File__c/fields/File_Description__c.field-meta.xml
<CustomField>
    <fullName>File_Description__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Integrity_Trusted;Source_CFaaS</complianceGroup>
    <description>File Description</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>File Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CFaaS_File__c/fields/File_Extension__c.field-meta.xml
<CustomField>
    <fullName>File_Extension__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Integrity_Trusted;Source_CFaaS</complianceGroup>
    <description>File Extension</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>File Extension</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CFaaS_File__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_CFaaS</complianceGroup>
    <description>Filename</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CFaaS_File__c/fields/Integrity_Classification__c.field-meta.xml
<CustomField>
    <fullName>Integrity_Classification__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_CFaaS</complianceGroup>
    <description>File Classification in CFaaS</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Integrity Classification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CFaaS_File__c/fields/Privacy_Classification__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Classification__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Integrity_Trusted;Source_CFaaS</complianceGroup>
    <description>File Classification in CFaaS</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Privacy Classification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CFaaS_File__c/fields/Security_Classification__c.field-meta.xml
<CustomField>
    <fullName>Security_Classification__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_CFaaS</complianceGroup>
    <description>File Classification in CFAAS</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Security Classification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Document_Flag__c.field-meta.xml
<CustomField>
    <fullName>Document_Flag__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>document flag</description>
    <inlineHelpText>Help Identify the sensitivity of the document</inlineHelpText>
    <label>Document Flag</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Draft</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Privileged</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Working draft</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Final version</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Attached to the incorrect case file</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Duplicate</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Sensitive </label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Medical Information</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Not to be exchanged</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Unique external ID for the record. Useful for use cases such as data backup and restoration.</description>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/File.recordType-meta.xml
<RecordType>
    <fullName>File</fullName>
    <active>true</active>
    <description>Default record type for files</description>
    <label>File</label>
</RecordType>

force-app/main/default/classes/CFaaSControllerTest.cls
/**
 * @author Emma Bindi
 * @since November 2022
 * @description Test class for {@link CFaaSController}
 */
@isTest
public with sharing class CFaaSControllerTest {
  @TestSetup
  static void setup() {
    Faker faker = new Faker('AU');
    Account acc = new Account(
      Name = 'TestAccount',
      Display_Name__c = 'TestAccount',
      OCV_ID__c = faker.randomString(10),
      ANZx_Customer__c = true,
      External_Id__c = faker.randomString(10)
    );
    insert acc;

    CFaaS_File__c file = new CFaaS_File__c(
      Document_Id__c = faker.randomString(35),
      File_Description__c = faker.randomString(5) +
        ' ' +
        faker.randomString(7) +
        ' ' +
        faker.randomString(8),
      File_Extension__c = '.jpeg',
      File_Name__c = faker.randomString(7) + ' ' + faker.randomString(6),
      Date_Created__c = faker.randomPastDateTime(),
      Customer__c = acc.Id,
      Privacy_Classification__c = 'Medium',
      Security_Classification__c = 'PROTECTED',
      Integrity_Classification__c = 'Confidential'
    );

    insert file;
  }

  @isTest
  static void testGetCFaaSDocument() {
    Account acc = [
      SELECT OCV_ID__c
      FROM Account
      WHERE Display_Name__c = 'TestAccount'
      LIMIT 1
    ];

    CFaaS_File__c file = [
      SELECT Document_Id__c, File_Extension__c, Security_Classification__c
      FROM CFaaS_File__c
      WHERE Customer__c = :acc.Id
      LIMIT 1
    ];

    Id cfaasFileRecordTypeId = Schema.SObjectType.ContentVersion.getRecordTypeInfosByName()
      .get('CFaaS File')
      .getRecordTypeId();
    ContentVersion cv = new ContentVersion();
    cv.Document_Flag__c = '4';
    cv.FirstPublishLocationId = file.Id;
    cv.UUID__c = file.Document_Id__c + '-' + UserInfo.getUserId();
    cv.title = 'test';
    cv.PathOnClient = 'test';
    cv.VersionData = Blob.valueOf('Test Content');
    cv.RecordTypeId = cfaasFileRecordTypeId;
    insert cv;

    Test.startTest();

    CFaaSController.CFassFileResult result = CFaaSController.getCFaaSDocument(
      acc.OCV_ID__c,
      file.Document_Id__c,
      file.Id,
      file.Security_Classification__c
    );

    Test.stopTest();

    System.assertNotEquals(
      null,
      result,
      'Content Document Id should be returned to LWC'
    );
  }
}