force-app/main/default/objects/Account/fields/CLG__c.field-meta.xml
<CustomField>
    <fullName>CLG__c</fullName>
    <complianceGroup>Source - Salesforce;Privacy - Non Personal Information;Integrity - Accurate</complianceGroup>
    <description>Customer Lending Group</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>CLG ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CLG.recordType-meta.xml
<RecordType>
    <fullName>CLG</fullName>
    <active>true</active>
    <label>CLG</label>
</RecordType>

force-app/main/default/objects/FinServ__AccountAccountRelation__c/FinServ__AccountAccountRelation__c.object-meta.xml
<CustomObject>
    <description>A relationship between two accounts, such as a household and a business account.</description>
    <label>Account-Account Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Account Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__AccountAccountRelation__c/fields/FinServ__Account__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Account__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>RelatedFromAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__AccountAccountRelation__c/fields/FinServ__RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelatedAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>RelatedToAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FinServ__RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelatedAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This includes Organisation, Individual, CLG, Prospect Customers.</inlineHelpText>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Leads</relationshipLabel>
    <relationshipName>RelatedLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CLG__c.field-meta.xml
<CustomField>
    <fullName>CLG__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated CLG Account Record.</description>
    <label>CLG</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (CLG)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ccrm/CommercialOpportunityActionsTest.cls
/**
 * @author       : Naman Garg
 * @since        : Nov 2024
 * @description  : Test class for CommercialOpportunityActions
 **/

@isTest
public class CommercialOpportunityActionsTest {
  static Lib_MockProvider oppRepoMock;
  static void registerMocks() {
    oppRepoMock = Lib_MockProvider.forType(
      CommercialOpportunityRepository.class
    );
  }

  @isTest
  static void testRestrictImagesInRichTextFields() {
    //GIVEN List of Opportunity Record
    List<Opportunity> opportunityList = new List<Opportunity>{
      new Opportunity(
        Id = Lib_FakeIdGenerator.getMockId(Opportunity.SObjectType),
        Name = 'Sample Opportunity'
      )
    };

    //WHEN calling a restrictImagesInRichTextFields method
    Test.startTest();
    CommercialOpportunityActions.restrictImagesInRichTextFields(
      opportunityList,
      null
    );
    Test.stopTest();

    //THEN it shouldn't throw any error
    Assert.isFalse(
      opportunityList[0].hasErrors(),
      'Error while inserting Opportunity record with Image.'
    );
  }

  @isTest
  static void extractAccountIdsInsertTest() {
    //GIVEN list of Opportunity records
    List<Opportunity> records = new List<Opportunity>{
      new Opportunity(
        Id = Lib_FakeIdGenerator.getMockId(Opportunity.SObjectType),
        AccountId = Lib_FakeIdGenerator.getMockId(Account.SObjectType)
      )
    };

    //WHEN calling a method
    Test.startTest();
    Set<Id> accountIdsSet = CommercialOpportunityActions.extractAccountIds(
      records,
      null
    );
    Test.stopTest();

    //THEN it should fetch 1 accountId
    Assert.areEqual(1, accountIdsSet.size(), 'Should fetch 1 accountId');
  }

  @isTest
  static void extractAccountIdsUpdateTest() {
    //GIVEN list of Opportunity records, old Map of Opportunity records
    Id oppId = Lib_FakeIdGenerator.getMockId(Opportunity.SObjectType);
    List<Opportunity> records = new List<Opportunity>{
      new Opportunity(
        Id = oppId,
        AccountId = Lib_FakeIdGenerator.getMockId(Account.SObjectType)
      )
    };
    Map<Id, Opportunity> oldMap = new Map<Id, Opportunity>{
      oppId => new Opportunity(
        Id = oppId,
        AccountId = Lib_FakeIdGenerator.getMockId(Account.SObjectType)
      )
    };

    //WHEN calling a method
    Test.startTest();
    Set<Id> accountIdsSet = CommercialOpportunityActions.extractAccountIds(
      records,
      oldMap
    );
    Test.stopTest();

    //THEN it should fetch 1 accountId
    Assert.areEqual(
      1,
      accountIdsSet.size(),
      'Should fetch 1 accountId on update'
    );
  }

  @isTest
  static void populateCLGAccountTest() {
    //GIVEN list of Opportunity records and map of Account-Account relations
    Id oppId = Lib_FakeIdGenerator.getMockId(Opportunity.SObjectType);
    Id relatedAccountId = Lib_FakeIdGenerator.getMockId(Account.SObjectType);
    Id clgAccountId = Lib_FakeIdGenerator.getMockId(Account.SObjectType);
    List<Opportunity> records = new List<Opportunity>{
      new Opportunity(Id = oppId, AccountId = relatedAccountId)
    };
    Map<Id, FinServ__AccountAccountRelation__c> accountToAARMap = new Map<Id, FinServ__AccountAccountRelation__c>{
      relatedAccountId => new FinServ__AccountAccountRelation__c(
        Id = Lib_FakeIdGenerator.getMockId(
          FinServ__AccountAccountRelation__c.SObjectType
        ),
        FinServ__Account__c = relatedAccountId,
        FinServ__RelatedAccount__c = clgAccountId,
        FinServ__RelatedAccount__r = new Account(CLG__c = '1234')
      )
    };

    //WHEN calling a method
    Test.startTest();
    CommercialOpportunityActions.populateCLGAccount(records, accountToAARMap);
    Test.stopTest();

    //THEN it should update CLG on Opp
    Assert.areEqual(
      clgAccountId,
      records[0].CLG__c,
      'Should update CLG Name on Opportunity'
    );
  }

  @isTest
  static void populateCLGTest() {
    registerMocks();
    //GIVEN list of Opportunity records and map of Account-Account relations
    Id oppId = Lib_FakeIdGenerator.getMockId(Opportunity.SObjectType);
    Id relatedAccountIdOld = Lib_FakeIdGenerator.getMockId(Account.SObjectType);
    Id relatedAccountIdNew = Lib_FakeIdGenerator.getMockId(Account.SObjectType);
    Id clgAccountId = Lib_FakeIdGenerator.getMockId(Account.SObjectType);

    List<Opportunity> records = new List<Opportunity>{
      new Opportunity(Id = oppId, AccountId = relatedAccountIdNew)
    };
    Map<Id, Opportunity> oldMap = new Map<Id, Opportunity>{
      oppId => new Opportunity(Id = oppId, AccountId = relatedAccountIdOld)
    };

    List<FinServ__AccountAccountRelation__c> accountAccountRelationList = new List<FinServ__AccountAccountRelation__c>{
      new FinServ__AccountAccountRelation__c(
        Id = Lib_FakeIdGenerator.getMockId(
          FinServ__AccountAccountRelation__c.SObjectType
        ),
        FinServ__Account__c = relatedAccountIdNew,
        FinServ__RelatedAccount__c = clgAccountId,
        FinServ__RelatedAccount__r = new Account(CLG__c = '1234')
      )
    };
    oppRepoMock.mock('getAccountAccountRelations', accountAccountRelationList);

    //WHEN calling a method
    Test.startTest();
    CommercialOpportunityActions.populateCLG(records, oldMap);
    Test.stopTest();

    //THEN it should update CLG Name & CLG Id on Lead
    Assert.areEqual(
      clgAccountId,
      records[0].CLG__c,
      'Should update CLG Name on opportunity on updation'
    );
  }
}