force-app/main/default/objects/Account/fields/CLG__c.field-meta.xml
<CustomField>
    <fullName>CLG__c</fullName>
    <complianceGroup>Source - Salesforce;Privacy - Non Personal Information;Integrity - Accurate</complianceGroup>
    <description>Customer Lending Group</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>CLG ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Deliquent</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CLG.recordType-meta.xml
<RecordType>
    <fullName>CLG</fullName>
    <active>true</active>
    <label>CLG</label>
</RecordType>

force-app/main/default/objects/CCRM_Commercial_Stage_Action_Plan__mdt/CCRM_Commercial_Stage_Action_Plan__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata to map Opportunity stage changes and related Action plan template</description>
    <label>CCRM Commercial Stage &amp; Action Plan</label>
    <pluralLabel>CCRM Commercial Stage &amp; Action Plans</pluralLabel>
</CustomObject>

force-app/main/default/objects/CCRM_Commercial_Stage_Action_Plan__mdt/fields/Current_Stage__c.field-meta.xml
<CustomField>
    <fullName>Current_Stage__c</fullName>
    <complianceGroup>Source_Salesforce;Integrity_Trusted;Privacy_Personal_Information</complianceGroup>
    <description>Current Stage of the opportunity</description>
    <label>Current Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCRM_Commercial_Stage_Action_Plan__mdt/fields/Next_Stage__c.field-meta.xml
<CustomField>
    <fullName>Next_Stage__c</fullName>
    <complianceGroup>Source_Salesforce;Integrity_Trusted;Privacy_Personal_Information</complianceGroup>
    <description>Next Stage of the opportunity</description>
    <label>Next Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCRM_Commercial_Stage_Action_Plan__mdt/fields/Previous_Stage__c.field-meta.xml
<CustomField>
    <fullName>Previous_Stage__c</fullName>
    <complianceGroup>Source_Salesforce;Integrity_Trusted;Privacy_Personal_Information</complianceGroup>
    <description>Previous Stage of the opportunity</description>
    <label>Previous Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCRM_Commercial_Stage_Action_Plan__mdt/fields/Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Template_Name__c</fullName>
    <complianceGroup>Source_Salesforce;Integrity_Trusted;Privacy_Personal_Information</complianceGroup>
    <description>Name of ActionPlanTemplate</description>
    <label>Name of ActionPlanTemplate</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FinServ__AccountAccountRelation__c/FinServ__AccountAccountRelation__c.object-meta.xml
<CustomObject>
    <description>A relationship between two accounts, such as a household and a business account.</description>
    <label>Account-Account Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Account Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__AccountAccountRelation__c/fields/FinServ__Account__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Account__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>RelatedFromAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__AccountAccountRelation__c/fields/FinServ__RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelatedAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>RelatedToAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__AccountAccountRelation__c/fields/FinServ__Role__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Role__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non-Sensitive_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FinServ__ReciprocalRole__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Account Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FinServ__ReciprocalRole__c</referenceTo>
    <relationshipName>AccountReciprocalRole</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__ReciprocalRole__c/FinServ__ReciprocalRole__c.object-meta.xml
<CustomObject>
    <description>Represents the other entity’s corresponding role in a one-to-one relationship between entities.</description>
    <label>Reciprocal Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reciprocal Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/FinServ__RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelatedAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This includes Organisation, Individual, CLG, Prospect Customers.</inlineHelpText>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Leads</relationshipLabel>
    <relationshipName>RelatedLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CLG__c.field-meta.xml
<CustomField>
    <fullName>CLG__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated CLG Account Record.</description>
    <label>CLG</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (CLG)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Needs__c.field-meta.xml
<CustomField>
    <fullName>Customer_Needs__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Customer needs that are captured from Lead Conversion \ Opportunity Creation.</description>
    <label>Customer Needs</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Purchasing Property</fullName>
            </value>
            <value>
                <fullName>Purchasing Vacant Land</fullName>
            </value>
            <value>
                <fullName>Purchasing an existing Business</fullName>
            </value>
            <value>
                <fullName>Purchasing a new Business</fullName>
            </value>
            <value>
                <fullName>Purchasing equipment (inc. vehicles and fit out)</fullName>
                <label>Purchasing Equipment (including vehicles, plant and machinery)</label>
            </value>
            <value>
                <fullName>Set up a new Business (Start Up)</fullName>
            </value>
            <value>
                <fullName>Assist with Business Working Capital/Temporary Finance</fullName>
            </value>
            <value>
                <fullName>Refinance from Other Financial Institutions</fullName>
            </value>
            <value>
                <fullName>Construction and Renovation</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Home Loan - Bridging Finance</fullName>
            </value>
            <value>
                <fullName>Home Loan - Construction</fullName>
            </value>
            <value>
                <fullName>Home Loan - Refinance + Purchase</fullName>
            </value>
            <value>
                <fullName>Home Loan - Purchase</fullName>
            </value>
            <value>
                <fullName>Home Loan - Refinance</fullName>
            </value>
            <value>
                <fullName>Home Loan - Maintenance</fullName>
            </value>
            <value>
                <fullName>Home Loan - Increase</fullName>
            </value>
            <value>
                <fullName>Home Loan - Other</fullName>
            </value>
            <value>
                <fullName>Personal Loan</fullName>
            </value>
            <value>
                <fullName>Asset Finance</fullName>
            </value>
            <value>
                <fullName>Other Loans</fullName>
            </value>
            <value>
                <fullName>Transactional Services (inc. IB4B, Account opening and Merchant services)</fullName>
            </value>
            <value>
                <fullName>ANZ Plus Home Loan - Refinance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Has_Close_Date_Changed__c.field-meta.xml
<CustomField>
    <fullName>Has_Close_Date_Changed__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Close date can only be changed once. This fields is set to true once date is changed.</description>
    <label>Has Close Date Changed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Converted__c.field-meta.xml
<CustomField>
    <fullName>Lead_Converted__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Opportunity created from Lead conversion</description>
    <label>Lead Converted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_Id__c.field-meta.xml
<CustomField>
    <fullName>Opp_Id__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Readable opportunity Id populated during lead conversion to opportunity</description>
    <displayFormat>0-{0000000}</displayFormat>
    <label>Opp Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Owner__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Custom field that will be made visible on the Quick Action for bulk reassignments</description>
    <label>Opportunity Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Commercial_Segment__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Segment__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>This is the Commercial Segment that the employee record is related to</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AF</fullName>
                <label>Asset Finance</label>
            </value>
            <value>
                <fullName>CBO</fullName>
                <label>Commercial Broker</label>
            </value>
            <value>
                <fullName>SD</fullName>
                <label>Special Distribution</label>
            </value>
            <value>
                <fullName>TB</fullName>
                <label>Transactional Banking</label>
            </value>
            <value>
                <fullName>SME</fullName>
                <label>Small to Medium Enterprises</label>
            </value>
            <value>
                <fullName>SME NBC</fullName>
                <label>Small to Medium Enterprises - NBC</label>
            </value>
            <value>
                <fullName>DSI</fullName>
                <label>Diversified and Specialist Industries</label>
            </value>
            <value>
                <fullName>PB</fullName>
                <label>Private Bank</label>
            </value>
            <value>
                <fullName>Markets</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
                <isActive>false</isActive>
                <label>Business Banking</label>
            </value>
            <value>
                <fullName>SBB</fullName>
                <isActive>false</isActive>
                <label>Small Business Banking</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ccrm/CCRMOpportunityActions.cls
/**
 * @author Emmanuel Yap
 * @since  05/2022
 * @group CCRM (Commercial CRM)
 * @description CCRMOpportunityActions is class to handle all the CCRM Account Actions
 */
@SuppressWarnings('PMD.CyclomaticComplexity')
public with sharing class CCRMOpportunityActions {
  public static final String CLOSE_DATE_FIELD_NAME = 'CloseDate';
  public static final String INVALID_CLOSE_DATE_ERROR = 'Please select a Closing Date (i.e. expected settlement date)';
  public static final String ACCOUNT_ID_FIELD_NAME = 'AccountId';
  public static final String LEAD_PROCESS_FOR_PROSPECT_ERROR = 'Error Message - Lead process to be followed for prospect opportunity creation';
  public static final String RECIPROCAL_ROLE_FOR_CLG = 'CG';
  public static Boolean insertOpportunityContext = false;
  private static final String OPPORTUNITY_OWNERSHIP_ERROR = 'Opportunity can only be transferred within your segment.';

  private static final Profile CURRENT_USER_PROFILE = MLCRMCommonUtils.getProfileById(
    UserInfo.getProfileId()
  );
  private static final Boolean IS_CCRM_USER = (CURRENT_USER_PROFILE?.Name ==
  Label.CCRM_Profile_Name);

  private static Map<String, CCRM_Commercial_Stage_Action_Plan__mdt> stageActionPlanMapping = new Map<String, CCRM_Commercial_Stage_Action_Plan__mdt>();

  /**
   * @description Define custom exceptions
   */
  public class CustomException extends Exception {
  }

  /**
   * @description This method will update Controlling Post field depending on the CPID provided in Account.
   * @name populateFields
   * @param records from the trigger
   * @param oldMap This Map<Id, SObject> contains the map which holds the previous values which can be used to check what value has changed in afterUpdate.
   */
  public static void populateFields(
    List<Opportunity> records,
    Map<Id, Opportunity> oldMap
  ) {
    Set<Id> accountIds = new Set<Id>();
    for (Opportunity opp : records) {
      accountIds.add(opp.AccountId);
    }
    checkAccountIsProspect(accountIds, records);
  }

  /**
   * @description This method will populate CLG filed with opportunity account parent field.
   * @name populateClgAccount
   * @param records from the trigger
   * @param oldMap This Map<Id, SObject> contains the map which holds the previous values which can be used to check what value has changed in afterUpdate.
   */
  public static void populateClgAccount(
    List<Opportunity> records,
    Map<Id, Opportunity> oldMap
  ) {
    Set<Id> accountIds = new Set<Id>();
    for (Opportunity opp : records) {
      accountIds.add(opp.AccountId);
    }
    Map<Id, Id> mapOfAccountWithClgAccount = getMapOfAccountWithClgAccount(
      accountIds
    );

    for (Opportunity opp : records) {
      Id clgAccount = mapOfAccountWithClgAccount.get(opp.AccountId);
      opp.CLG__c = clgAccount != null ? clgAccount : null;
    }
  }

  /**
   * @description This method will get CLG account associated to accounts
   * @name getMapOfAccountWithClgAccount
   * @param accountIds Account Ids
   * @return Map<Id,Id> Account Ids with associated CLG Account Ids
   */
  public static Map<Id, Id> getMapOfAccountWithClgAccount(Set<Id> accountIds) {
    Map<Id, Id> mapOfAccountWithClgAccount = new Map<Id, Id>();
    if (Schema.sObjectType.FinServ__ReciprocalRole__c.isQueryable()) {
      List<FinServ__ReciprocalRole__c> roleId = [
        SELECT Id
        FROM FinServ__ReciprocalRole__c
        WHERE Name = :RECIPROCAL_ROLE_FOR_CLG
        LIMIT 1
      ];
      if (
        Schema.sObjectType.FinServ__AccountAccountRelation__c.isQueryable() &&
        roleId.size() > 0
      ) {
        for (FinServ__AccountAccountRelation__c relatedaccount : [
          SELECT FinServ__Account__c, FinServ__RelatedAccount__c
          FROM FinServ__AccountAccountRelation__c
          WHERE
            FinServ__Account__c IN :accountIds
            AND FinServ__Role__c = :roleId[0].Id
        ]) {
          mapOfAccountWithClgAccount.put(
            relatedaccount.FinServ__Account__c,
            relatedaccount.FinServ__RelatedAccount__c
          );
        }
      }
    }
    return mapOfAccountWithClgAccount;
  }

  /**
   * @description This method will update Controlling Post field depending on the CPID provided in Account.
   * @name populateFieldsAfterInsert
   * @param records from the trigger
   */
  public static void populateFieldsAfterInsert(List<Opportunity> records) {
    Set<Id> accountIds = new Set<Id>();
    Set<Id> oppIds = new Set<Id>();
    for (Opportunity opp : records) {
      accountIds.add(opp.AccountId);
      oppIds.add(opp.Id);
    }
    try {
      List<Opportunity> opps = [
        SELECT
          Id,
          AccountId,
          Lead_Converted__c,
          Name,
          Opp_Id__c,
          recordtypeId,
          Customer_Needs__c
        FROM Opportunity
        WHERE Id IN :oppIds
        WITH SECURITY_ENFORCED
      ];
      setNameForOpportunityFromLead(accountIds, opps);
    } catch (System.QueryException e) {
      Logger.error(
        'InsufficientAccessException' + e.getMessage() + e.getTypeName(),
        e
      );
      Logger.savelog();
    }
  }

  /**
   * @description This method will validate that close date should be updated on first opportunity update.
   * @name validateCloseDate
   * @param records New opportunity records
   * @param oldMap Map of old Opportunity record
   */
  public static void validateCloseDate(
    List<Opportunity> records,
    Map<Id, Opportunity> oldMap
  ) {
    String strRecordTypeId = MLCRMConstants.MLCRM_OPPORTUNITY_RT_ID;
    for (Opportunity opp : records) {
      Date oldOppCloseDate = oldMap.get(opp.Id).CloseDate;
      //Display message if:
      //It is lead converted opportunity AND
      //Close date is not updated by using flag - Has_Close_Date_Changed__c
      String oldName = oldMap.get(opp.Id).Name;
      if (
        oldName != 'placeholder' &&
        opp.Lead_Converted__c &&
        !opp.Has_Close_Date_Changed__c &&
        oldOppCloseDate == opp.CloseDate &&
        opp.recordTypeId != strRecordTypeId
      ) {
        opp.addError(CLOSE_DATE_FIELD_NAME, INVALID_CLOSE_DATE_ERROR);
      } else if (oldOppCloseDate != opp.CloseDate) {
        opp.Has_Close_Date_Changed__c = true;
      }
    }
  }

  /**
   * @description Retrieve accounts mapped with Id as Key
   * @name getMappedAccounts
   * @param accountIds List of Accounts used by Opportunities
   * @return `Map<Id,Account>`
   */
  private static Map<Id, Account> getMappedAccounts(Set<Id> accountIds) {
    try {
      return new Map<Id, Account>(
        [
          SELECT Id, Name, FinServ__Status__c
          FROM Account
          WHERE Id IN :accountIds
          WITH SECURITY_ENFORCED
        ]
      );
    } catch (System.QueryException e) {
      Logger.error(
        'InsufficientAccessException' + e.getMessage() + e.getTypeName(),
        e
      );
      Logger.saveLog();
    }
    return new Map<Id, Account>();
  }

  /**
   * @description This method will Loop through Accounts mapped with Opportunity and determine if Account is a Prospect
   * @name checkAccountIsProspect
   * @param accountIds List of Accounts used by Opportunities
   * @param records List of Opportunities in transaction
   */
  private static void checkAccountIsProspect(
    Set<Id> accountIds,
    List<Opportunity> records
  ) {
    Map<Id, Account> accounts = getMappedAccounts(accountIds);

    for (Opportunity record : records) {
      if (accounts.containsKey(record.AccountId)) {
        Account acc = accounts.get(record.AccountId);
        if (
          acc.FinServ__Status__c != 'Active' &&
          !record.Lead_Converted__c &&
          record.RecordTypeId != MLCRMConstants.MLCRM_OPPORTUNITY_RT_ID
        ) {
          record.addError(
            ACCOUNT_ID_FIELD_NAME,
            LEAD_PROCESS_FOR_PROSPECT_ERROR
          );
        }
      }
    }
  }

  /**
   * @description This method will Loop through Accounts mapped with Opportunity and set Opportunity Name
   * @name setNameForOpportunityFromLead
   * @param accountIds List of Accounts used by Opportunities
   * @param records List of Opportunities in transaction
   */
  private static void setNameForOpportunityFromLead(
    Set<Id> accountIds,
    List<Opportunity> records
  ) {
    List<Opportunity> updatedRecords = new List<Opportunity>();
    Map<Id, Account> mappedAccounts = getMappedAccounts(accountIds);

    for (Opportunity record : records) {
      if (
        mappedAccounts.containsKey(record.AccountId) && record.Lead_Converted__c
      ) {
        Account acc = mappedAccounts.get(record.AccountId);
        //CC-5603 Opportunity name should be account name for Mobile Leniding Opportunity
        if (record.recordtypeId == MLCRMConstants.MLCRM_OPPORTUNITY_RT_ID) {
          record.Name = acc.Name;
        } else {
          record.Name = record.Opp_Id__c + ' ' + acc.Name;
        }
        updatedRecords.add(record);
      }
    }
    if (
      Schema.sObjectType.Opportunity.fields.Name.isUpdateable() &&
      !updatedRecords.isEmpty()
    ) {
      List<Database.saveResult> results = Database.update(
        updatedRecords,
        false
      );
      Logger.error('', results);
      Logger.saveLog();
    }
  }

  /**
   * @description Check if this Opportunity AccountId has changed
   * @name isAccountIdChanged
   * @param record Opportunity record
   * @param oldRec old Opportunity
   * @return `Boolean` True if AccountId is updated otherwise false.
   */
  private static Boolean isAccountIdChanged(
    Opportunity record,
    Opportunity oldRec
  ) {
    if (oldRec != null && record.Account.Id != oldRec.Account.Id) {
      return true;
    }
    return false;
  }

  /**
   * @description Check if this Opportunity Amount has changed
   * @name isAccountNameChanged
   * @param record Opportunity record
   * @param oldRec old Opportunity
   * @return `Boolean` True if the Amount is updated otherwise false.
   */
  private static Boolean isAmountChanged(
    Opportunity record,
    Opportunity oldRec
  ) {
    if (oldRec != null && record.Amount != oldRec.Amount) {
      return true;
    }
    return false;
  }

  /**
   * @description Mask Description of Opportunity
   * @name maskDescription
   * @param record Opportunity to mask
   */
  private static void maskDescription(Opportunity record) {
    if (record.Description != null) {
      record.Description = TextUtils.maskData(record.Description);
    }
  }

  /**
   * @description Validates opportunity while stage changes
   * @name mandatoryFieldAndSkipStageCheck
   * @param oppWrapper CCRMOpportunityWrapper
   * @param oldOppMap map of old recordsList
   * @param isInsert when record is insert
   */
  public static void mandatoryFieldAndSkipStageCheck(
    CCRMOpportunityWrapper oppWrapper,
    Map<Id, Opportunity> oldOppMap,
    Boolean isInsert
  ) {
    try {
      //retrieve filtered CCRM Opps
      stageActionPlanMapping = getStageActionPlanMetadata(
        oppWrapper.filteredOpps
      );

      oppWrapper = getStageSegmentOrTemplateMap(
        oppWrapper,
        oldOppMap,
        stageActionPlanMapping
      );

      //checks for validations on opportunities
      CCRMOpportunityActionsSkipStageHelper.validateCCRMOpportunity(
        oppWrapper.filteredOpps,
        oppWrapper.stageUpdatedOpps,
        isInsert
      );

      //adds error for skipped stages
      CCRMOpportunityActionsSkipStageHelper.addErrorForSkippedStage(
        oppWrapper.stageUpdatedOpps.values(),
        oldOppMap,
        stageActionPlanMapping,
        oppWrapper.oppsStageSegmentMap
      );
      //Adds error for mandatory tasks
      CCRMOpportunityActionsSkipStageHelper.displayErrorForMandatoryTask(
        oppWrapper.oppsWithMandatoryTaskToTemplateMap,
        oppWrapper.oppWithMandatoryTaskMap
      );

      //checks if opp has any open tasks on closed stage
      CCRMOpportunityActionsSkipStageHelper.checkOpenTaskForClosedOpportunities(
        oppWrapper.closingOppoIdMap
      );
    } catch (Exception e) {
      Logger.error(e.getMessage(), e);
      Logger.saveLog();
    }
  }

  /**
   * @description gets filtered CCRM Opportunities
   * @name getFilteredCCRMOpps
   * @param newOppList list of new records
   * @param oldOppMap map of old recordsList
   * @param isUpdate when record is update
   * @return CCRMOpportunityWrapper wrapper object
   */
  public static CCRMOpportunityWrapper getFilteredCCRMOpps(
    List<Opportunity> newOppList,
    Map<Id, Opportunity> oldOppMap,
    Boolean isUpdate
  ) {
    CCRMOpportunityWrapper oppWrapper = new CCRMOpportunityWrapper();

    for (Opportunity oppIterator : newOppList) {
      if (oppIterator.RecordTypeId != CCRMConstants.CCRM_OPP_RT_ID) {
        continue;
      }
      oppWrapper.filteredOpps.add(oppIterator);

      if (
        isUpdate &&
        oppIterator.StageName != oldOppMap.get(oppIterator.Id).StageName &&
        oppIterator.StageName.equalsIgnoreCase(CCRMConstants.OPP_WON)
      ) {
        oppWrapper.closingOppoIdMap.put(oppIterator.Id, oppIterator);
      }
      if (
        isUpdate &&
        oppIterator.StageName != oldOppMap.get(oppIterator.Id).StageName
      ) {
        oppWrapper.stageUpdatedOpps.put(oppIterator.Id, oppIterator);
      }

      oppWrapper.oppIdToOwnerIdMap.put(oppIterator.Id, oppIterator.OwnerId);
    }

    Map<Id, User> userMap = new Map<Id, User>(
      [
        SELECT Id, Commercial_Segment__c
        FROM User
        WHERE Id IN :oppWrapper.oppIdToOwnerIdMap.values()
      ]
    );

    oppWrapper.oppOwnerIdToSegmentMap = userMap;

    return oppWrapper;
  }

  /**
   * @description get custom metadata records
   * @name getStageActionPlanMetadata
   * @param filteredOpps list of new CCRM Opportunity records
   * @return Map<Id, CCRM_Commercial_Stage_Action_Plan__mdt> map of string and metadata
   */
  public static Map<String, CCRM_Commercial_Stage_Action_Plan__mdt> getStageActionPlanMetadata(
    List<Opportunity> filteredOpps
  ) {
    if (filteredOpps.isEmpty()) {
      return null;
    }

    for (
      CCRM_Commercial_Stage_Action_Plan__mdt metadata : CCRM_Commercial_Stage_Action_Plan__mdt.getAll()
        .values()
    ) {
      String key =
        metadata.Current_Stage__c +
        '-' +
        metadata.Commercial_Segment__c;
      stageActionPlanMapping.put(key, metadata);
    }
    return stageActionPlanMapping;
  }

  /**
   * @description get stage segment map
   * @name getStageSegmentOrTemplateMap
   * @param oppWrapper wrapper having map of id and new opportunity having stage changes
   * @param oldOppMap map of id and old opportunity
   * @param stageActionPlanMapping custom metadata records containing stage and template
   * @return CCRMOpportunityWrapper opportunity wrapper
   */
  public static CCRMOpportunityWrapper getStageSegmentOrTemplateMap(
    CCRMOpportunityWrapper oppWrapper,
    Map<Id, Opportunity> oldOppMap,
    Map<String, CCRM_Commercial_Stage_Action_Plan__mdt> stageActionPlanMapping
  ) {
    for (Opportunity oppIterator : oppWrapper.stageUpdatedOpps.values()) {
      String ownerSegment = oppWrapper.oppOwnerIdToSegmentMap.get(
          oppWrapper.oppIdToOwnerIdMap.get(oppIterator.Id)
        )
        .Commercial_Segment__c;

      String oldValueKey =
        oldOppMap.get(oppIterator.Id).StageName +
        '-' +
        ownerSegment;

      String newValueKey = oppIterator.StageName + '-' + ownerSegment;

      oppWrapper.oppsStageSegmentMap.put(oppIterator.Id, oldValueKey);

      if (
        stageActionPlanMapping.containsKey(newValueKey) &&
        stageActionPlanMapping.get(newValueKey).Template_Name__c != null &&
        stageActionPlanMapping.get(newValueKey).Previous_Stage__c ==
        oldOppMap.get(oppIterator.Id).StageName
      ) {
        oppWrapper.oppIdToTemplateNameMap.put(
          oppIterator.Id,
          stageActionPlanMapping.get(newValueKey).Template_Name__c
        );
      }

      CCRM_Commercial_Stage_Action_Plan__mdt oldStageMetadata = stageActionPlanMapping.get(
        oldValueKey
      );

      if (
        oldStageMetadata != null &&
        (oldOppMap.get(oppIterator.Id).StageName ==
        oldStageMetadata.Current_Stage__c &&
        oppIterator.StageName == oldStageMetadata.Next_Stage__c &&
        !oppIterator.IsClosed &&
        oldStageMetadata.Template_Name__c != null)
      ) {
        oppWrapper.oppWithMandatoryTaskMap.put(oppIterator.Id, oppIterator);
        oppWrapper.oppsWithMandatoryTaskToTemplateMap.put(
          oppIterator.Id,
          oldStageMetadata.Template_Name__c
        );
      }
    }
    return oppWrapper;
  }

  /**
   * @description populate opportunity name with auto number + Customer need value
   * @name populateOppNameOnInsert
   * @param oppList list of new records
   * @param oldOppMap map of old records
   * @param isInsert to check if it is insert operation
   * @param isUpdate to check if it is update operation
   */

  public static void populateOppName(
    List<Opportunity> oppList,
    Map<Id, Opportunity> oldOppMap,
    Boolean isInsert,
    Boolean isUpdate
  ) {
    try {
      if (isInsert && oldOppMap == null) {
        List<Opportunity> opptoUpdate = new List<Opportunity>();
        if (!IS_CCRM_USER) {
          return;
        }
        for (Opportunity oppIter : oppList) {
          if (oppIter.recordTypeId == CCRMConstants.CCRM_OPP_RT_ID) {
            Opportunity opp = new Opportunity();
            opp.Id = oppIter.Id;
            opp.Name = oppIter.Lead_Converted__c
              ? oppIter.Opp_Id__c + ' ' + oppIter.Customer_Needs__c
              : oppIter.Opp_Id__c +
                ' ' +
                oppIter.Customer_Needs__c +
                ' ' +
                oppIter.Name;
            opptoUpdate.add(opp);
          }
        }
        if (!opptoUpdate.isEmpty()) {
          CCRMOpportunityActions.insertOpportunityContext = true;
          List<Database.saveResult> results = Database.update(
            opptoUpdate,
            false
          );
        }
      } else if (isUpdate) {
        String oppoName = '';
        for (Opportunity oppIter : oppList) {
          if (oppIter.recordTypeId == CCRMConstants.CCRM_OPP_RT_ID) {
            if (
              oppIter.Customer_Needs__c !=
              oldOppMap.get(oppIter.Id).Customer_Needs__c ||
              oppIter.Name != oldOppMap.get(oppIter.Id).Name
            ) {
              oppoName = (oldOppMap.get(oppIter.Id)
                  .Name.replace(oppIter.Opp_Id__c, ''))
                .replace(oldOppMap.get(oppIter.Id).Customer_Needs__c, '');
              oppIter.Name = oppIter.Lead_Converted__c
                ? oppIter.Opp_Id__c + ' ' + oppIter.Customer_Needs__c
                : oppIter.Opp_Id__c +
                  ' ' +
                  oppIter.Customer_Needs__c +
                  ' ' +
                  oppoName;
            }
          }
        }
      }
    } catch (Exception ex) {
      Logger.error(
        'Error occured during updating opportunity name from lead',
        ex
      );
      Logger.saveLog();
      throw new CustomException(ex.getMessage());
    }
  }

  /**
   * @description Throw error if we try to transfer the Opportunity ownership from BB to SBB/SBB-NBC and vice versa
   * - ownerID: throw error when try to change between segment.
   * @name transferOpportunityOwnership
   * @param newOppList List of new lead records.
   * @param oldOppMap Map of old lead records.
   */
  public static void transferOpportunityOwnership(
    List<Opportunity> newOppList,
    Map<Id, Opportunity> oldOppMap
  ) {
    Map<Id, User> userMap = new Map<Id, User>();
    Set<Id> ownerIdSet = new Set<Id>();
    if (
      System.UserInfo.getProfileId() !=
      CommonUtil.getProfileByName('ANZ CCRM Standard User').Id
    ) {
      return;
    }
    updateBulkOppOwnership(newOppList, oldOppMap);
    userMap = getOwnerCommercialSegment(newOppList, oldOppMap);
    validateOwnerChange(newOppList, oldOppMap, userMap);
  }

  /**
   * @description update the Opportunity_Owner__c with the OwnerId field
   * @name updateBulkOppOwnership
   * @param opportunityList list of new records
   * @param oldOppMap map of old recordsList
   */
  @TestVisible
  private static void updateBulkOppOwnership(
    List<Opportunity> opportunityList,
    Map<Id, Opportunity> oldOppMap
  ) {
    for (Opportunity opportunityRec : opportunityList) {
      if (opportunityRec.RecordTypeId != CCRMConstants.CCRM_OPP_RT_ID) {
        continue;
      }
      if (
        opportunityRec.Opportunity_Owner__c !=
        oldOppMap.get(opportunityRec.Id).Opportunity_Owner__c
      ) {
        opportunityRec.OwnerId = opportunityRec.Opportunity_Owner__c;
      }
    }
  }

  /**
   * @description Get the commercial segment of New and Old Owner
   * @name getOwnerCommercialSegment
   * @param opportunityList list of new records
   * @param oldOppMap map of old recordsList
   * @return Map<Id, User> User map containing the Id and Commerical Segment
   */
  @TestVisible
  private static Map<Id, User> getOwnerCommercialSegment(
    List<Opportunity> opportunityList,
    Map<Id, Opportunity> oldOppMap
  ) {
    Set<Id> ownerIdsSet = new Set<Id>();
    Map<Id, User> userMap;
    for (Opportunity opportunityRec : opportunityList) {
      if (opportunityRec.RecordTypeId != CCRMConstants.CCRM_OPP_RT_ID) {
        continue;
      }
      if (opportunityRec.OwnerId != oldOppMap.get(opportunityRec.Id).OwnerId) {
        ownerIdsSet.add(opportunityRec.OwnerId);
        ownerIdsSet.add(oldOppMap.get(opportunityRec.Id).OwnerId);
      }
    }
    if (!ownerIdsSet.isEmpty()) {
      try {
        userMap = new Map<Id, User>(
          [
            SELECT Id, Commercial_Segment__c
            FROM User
            WHERE Id IN :ownerIdsSet
            WITH SECURITY_ENFORCED
          ]
        );
      } catch (System.QueryException e) {
        Logger.error(
          'InsufficientAccessException' + e.getMessage() + e.getTypeName(),
          e
        );
        Logger.savelog();
      }
    }
    return userMap;
  }

  /**
   * @description Validate if the ownerChange within segment
   * @name validateOwnerChange
   * @param opportunityList list of new records
   * @param oldOppMap map of old recordsList
   * @param userMap map of User to get its Commercial Segment
   */
  private static void validateOwnerChange(
    List<Opportunity> opportunityList,
    Map<Id, Opportunity> oldOppMap,
    Map<Id, User> userMap
  ) {
    String newCommercialSegment = '';
    String oldCommercialSegment = '';
    String newOppOwner = '';
    String oldOppOwner = '';

    for (Opportunity opportunityRec : opportunityList) {
      if (opportunityRec.RecordTypeId != CCRMConstants.CCRM_OPP_RT_ID) {
        continue;
      }
      newOppOwner = opportunityRec.OwnerId;
      oldOppOwner = oldOppMap.get(opportunityRec.Id).OwnerId;
      newCommercialSegment = userMap
        ?.get(opportunityRec.OwnerId)
        .Commercial_Segment__c;
      oldCommercialSegment = userMap
        ?.get(oldOppMap.get(opportunityRec.Id).OwnerId)
        .Commercial_Segment__c;
      if (
        newOppOwner != oldOppOwner &&
        (String.isBlank(newCommercialSegment) ||
        (newCommercialSegment != oldCommercialSegment))
      ) {
        opportunityRec.addError(OPPORTUNITY_OWNERSHIP_ERROR);
      }
      if (opportunityRec.Opportunity_Owner__c != opportunityRec.OwnerId) {
        opportunityRec.Opportunity_Owner__c = opportunityRec.OwnerId;
      }
    }
  }

  /**
   * @description wrapper class for CCRM Opportunity
   */
  public class CCRMOpportunityWrapper {
    public Map<Id, Opportunity> closingOppoIdMap = new Map<Id, Opportunity>();
    public Map<Id, Opportunity> stageUpdatedOpps = new Map<Id, Opportunity>();
    public List<Opportunity> filteredOpps = new List<Opportunity>();
    public Map<Id, String> oppsStageSegmentMap = new Map<Id, String>();
    public Map<Id, String> oppIdToTemplateNameMap = new Map<Id, String>();
    public Map<Id, Id> oppIdToOwnerIdMap = new Map<Id, Id>();
    public Map<Id, User> oppOwnerIdToSegmentMap = new Map<Id, User>();
    public Map<Id, Opportunity> oppWithMandatoryTaskMap = new Map<Id, Opportunity>();
    public Map<Id, String> oppsWithMandatoryTaskToTemplateMap = new Map<Id, String>();
  }
}