force-app/main/default/objects/Account/fields/CLG__c.field-meta.xml
<CustomField>
    <fullName>CLG__c</fullName>
    <complianceGroup>Source - Salesforce;Privacy - Non Personal Information;Integrity - Accurate</complianceGroup>
    <description>Customer Lending Group</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>CLG ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <description>Used for writing updates from OCV Party event messages. It is constructed in Mulesoft.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/FinServ__KYCStatus__c.field-meta.xml
<CustomField>
    <fullName>FinServ__KYCStatus__c</fullName>
    <label>KYC Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>NO STATUS ISSUED</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
                <label>Complete</label>
            </value>
            <value>
                <fullName>NE</fullName>
                <label>New</label>
            </value>
            <value>
                <fullName>OB</fullName>
                <label>Obsolete</label>
            </value>
            <value>
                <fullName>PC</fullName>
                <label>Partially Complete</label>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Completed - Invalid</fullName>
            </value>
            <value>
                <fullName>Completed - Valid</fullName>
            </value>
            <value>
                <fullName>In Queue</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CAPCIS_ID__c.field-meta.xml
<CustomField>
    <fullName>CAPCIS_ID__c</fullName>
    <complianceGroup>Source_Caps;Privacy - Non Personal Information;Integrity - Accurate</complianceGroup>
    <description>CAP-CIS ID of the Prospect created via Lead Conversion in Salesforce</description>
    <label>CAPCIS ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source_iKnow</complianceGroup>
    <description>Identifier from external systems e.g. iKnow</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FinServ__RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelatedAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This includes Organisation, Individual, CLG, Prospect Customers.</inlineHelpText>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Leads</relationshipLabel>
    <relationshipName>RelatedLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Skip_Validations__c.field-meta.xml
<CustomField>
    <fullName>Skip_Validations__c</fullName>
    <complianceGroup>Source - Salesforce;Privacy - Non Personal Information;Integrity - Trusted</complianceGroup>
    <description>This field is to Skip Validation Rules when updating records through Apex.</description>
    <label>Skip Validations</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Lan_Id__c.field-meta.xml
<CustomField>
    <fullName>Lan_Id__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Integrity_Trusted;Source_Salesforce</complianceGroup>
    <description>LAN ID of the user who captured the response or who the lead was routed to (if available).</description>
    <externalId>true</externalId>
    <label>Lan Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CommercialLeadConversionRepository.cls
/**
 * @author       : Advait Yermalkar
 * @since        : 02-06-2025
 * @description  : This class provide SOQL and DML helper for class related to CommercialLeadConversionHelper
 **/
public with sharing class CommercialLeadConversionRepository {
  /**
   * @description return Accounts using ExternalId
   * @param externalId ExternalId of Account
   * @return  Account instance
   */
  public Account getAccountUsingExternalId(String externalId) {
    if (externalId == null) {
      return null;
    }
    return [
      SELECT
        Id,
        External_Id__c,
        Name,
        FinServ__KYCStatus__c,
        CLG__c,
        RecordTypeId
      FROM Account
      WHERE External_Id__c = :externalId
      WITH USER_MODE
      LIMIT 1
    ] ?? null;
  }

  /**
   * @description fetch ocv user
   * @name getOCVUser
   * @return User fetching OCV user
   */
  public User getOCVUser() {
    return [
      SELECT Id
      FROM USER
      WHERE Username = :System.Label.CCRM_OCVIntegrationUsername
      WITH USER_MODE
      LIMIT 1
    ] ?? null;
  }

  /**
   * @description return lead Owner Lan Id
   * @param leadOwnerId
   * @return User user record
   */
  public User getLeadOwnerLanId(Id leadOwnerId) {
    if (leadOwnerId == null) {
      return null;
    }
    return [
      SELECT ID, Lan_Id__c
      FROM User
      WHERE Id = :leadOwnerId
      WITH USER_MODE
      LIMIT 1
    ] ?? null;
  }

  /**
   * @description Check whether the user has lead update permission
   * @return Boolean True if the lead is updatable
   */
  public Boolean isLeadCAPCISUpdatable() {
    return (Schema.sObjectType.Lead.isUpdateable() &&
    Schema.sObjectType.Lead.fields.Skip_Validations__c.isUpdateable() &&
    Schema.sObjectType.Lead.fields.FinServ__RelatedAccount__c.isUpdateable() &&
    Schema.sObjectType.Lead.fields.CAPCIS_ID__c.isUpdateable());
  }
}