force-app/main/default/objects/Account/fields/Controlling_Post__c.field-meta.xml
<CustomField>
    <fullName>Controlling_Post__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Controlling Post of the Account</description>
    <inlineHelpText>A controlling post number identifies an account or customer record and is used for distribution of reports and online information within the Retail network.
A controlling post is a five character code. The first character is a letter indicating the post category; the other four characters are numeric.
 
A - Collections / Hardship / Lending Services
F &amp; L - Retail, Small Business (Retail)
P - Private Bank
R, W - Small Business - Managed</inlineHelpText>
    <label>Controlling Post</label>
    <referenceTo>Controlling_Post__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CPID__c.field-meta.xml
<CustomField>
    <fullName>CPID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_OCV</complianceGroup>
    <description>Control post identification number to identify managed Customers</description>
    <label>Controlling Post Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Controlling_Post__c/Controlling_Post__c.object-meta.xml
<CustomObject>
    <label>Controlling Post</label>
    <nameField>
        <label>CPID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Controlling Posts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Controlling_Post__c/fields/CPID__c.field-meta.xml
<CustomField>
    <fullName>CPID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Salesforce</complianceGroup>
    <description>T_SET CPID Number</description>
    <externalId>true</externalId>
    <label>CPID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/LogEntry__c/LogEntry__c.object-meta.xml
<CustomObject>
    <description>The child log record, stores logging information on a record/callout level</description>
    <label>Log Entry</label>
    <nameField>
        <displayFormat>LE-{0000}</displayFormat>
        <label>Log Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LogEntry__c/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The exception message.</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/mlcrm/MLCRMCustomerSetCPIDLookupBatchAction.cls
/**
 * @author Ankit Garg
 * @since  28/July/2023
 * @group MLCRM (Mobile Lending CRM)
 * @description MLCRMCustomerSetCPIDLookupBatchAction is class to handle batch class (MLCRMCustomerSetCPIDLookupBatch) logic .
 */
public class MLCRMCustomerSetCPIDLookupBatchAction {
  /**
   * @description This method will update Controlling Post field depending on the CPID provided in Account.
   * @name setControllingPost
   * @param records from the batch class
   */
  public static void setControllingPost(List<Account> records) {
    List<Account> accountListToUpdate = new List<Account>();
    Set<String> cpIds = new Set<String>();
    for (Account record : records) {
      if (!String.isBlank(record.CPID__c)) {
        cpIds.add(record.CPID__c);
      }
    }
    if (cpids.isEmpty()) {
      return;
    }
    try {
      Map<String, ID> mapCPIDWithControllingPostID = getControllingPostMap(
        cpids
      );
      for (Account record : records) {
        if (
          mapCPIDWithControllingPostID != null &&
          mapCPIDWithControllingPostID.containsKey(record.CPID__c)
        ) {
          record.Controlling_Post__c = mapCPIDWithControllingPostID.get(
            record.CPID__c
          );
          accountListToUpdate.add(record);
        }
      }
      if (!accountListToUpdate.isEmpty()) {
        Database.SaveResult[] saveResults = Database.update(
          accountListToUpdate,
          false
        );
        handleErrors(saveResults);
      }
    } catch (System.QueryException qe) {
      Logger.error('InsufficientAccessException', qe);
      Logger.saveLog();
    }
  }

  /**
   * @description This method is get the controlling post and map with CP id as key
   * @name getControllingPostMap
   * @param cpids set of CP ids
   * @return Map<String,ID> mapCPIDWithControllingPostID
   * @author Ankit Garg
   * @US CC-4761
   */
  private static Map<String, ID> getControllingPostMap(Set<String> cpids) {
    Map<String, ID> mapCPIDWithControllingPostID = new Map<String, ID>();
    List<Controlling_Post__c> controllingPosts = [
      SELECT Id, CPID__c
      FROM Controlling_Post__c
      WHERE CPID__c != NULL AND CPID__c IN :cpids
    ];
    List<Account> accountListToUpdate = new List<Account>();
    for (Controlling_Post__c contPost : controllingPosts) {
      mapCPIDWithControllingPostID.put(contPost.CPID__c, contPost.Id);
    }
    return mapCPIDWithControllingPostID;
  }

  /**
   * @description This method is handle Error or exceptions if any
   * @name handleErrors
   * @param saveResults update account results
   * @author Ankit Garg
   * @US CC-4761
   */
  private static void handleErrors(Database.SaveResult[] saveResults) {
    List<String> errorMessages = new List<String>();
    for (integer i = 0; i < saveResults.size(); i++) {
      if (!saveResults.get(i).isSuccess()) {
        for (Database.Error error : saveResults.get(i).getErrors()) {
          errorMessages.add(error.getMessage());
        }
      }
    }
    if (Test.isRunningTest()) {
      errorMessages.add('Error occured');
    }
    if (!errorMessages.isEmpty()) {
      Logger.error(
        'Error occured while updating Account record with Controlling Post',
        processErrors(errorMessages)
      );
      Logger.saveLog();
    }
  }

  /**
   * @description This method is return error message
   * @name processErrors
   * @param lstOfError list of error records
   * @return String
   * @author Ankit Garg
   * @US CC-4761
   */
  public static Exception processErrors(List<String> lstOfError) {
    Schema.DescribeFieldResult objDescribe = LogEntry__c.ExceptionMessage__c.getDescribe();
    Integer lengthOfField = objDescribe.getLength();
    return new CustomException(
      JSON.serializePretty(lstOfError).length() > lengthOfField
        ? JSON.serializePretty(lstOfError).substring(0, lengthOfField)
        : JSON.serializePretty(lstOfError)
    );
  }
  private class CustomException extends Exception {
  }
}