force-app/main/default/objects/Account/fields/Controlling_Post__c.field-meta.xml
<CustomField>
    <fullName>Controlling_Post__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Controlling Post of the Account</description>
    <inlineHelpText>A controlling post number identifies an account or customer record and is used for distribution of reports and online information within the Retail network.
A controlling post is a five character code. The first character is a letter indicating the post category; the other four characters are numeric.
 
A - Collections / Hardship / Lending Services
F &amp; L - Retail, Small Business (Retail)
P - Private Bank
R, W - Small Business - Managed</inlineHelpText>
    <label>Controlling Post</label>
    <referenceTo>Controlling_Post__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Controlling_Post__c/Controlling_Post__c.object-meta.xml
<CustomObject>
    <label>Controlling Post</label>
    <nameField>
        <label>CPID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Controlling Posts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Controlling_Post__c/fields/Responsible_Employee__c.field-meta.xml
<CustomField>
    <fullName>Responsible_Employee__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Integrity_Trusted;Source_Salesforce</complianceGroup>
    <description>This is the banker that is responsible for that CPID.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Controlling_Posts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Controlling_Post__c/fields/Responsible_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Responsible_Employee_Id__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Integrity_Trusted;Source_Salesforce</complianceGroup>
    <description>This is the banker that is responsible for that CPID.

If this field = 0, then there currently isn&apos;t any responsible banker for this CPID, but it is still active with customers attached to it</description>
    <label>Responsible Employee Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Controlling_Post__c.field-meta.xml
<CustomField>
    <fullName>Controlling_Post__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Controlling Post of Lead</description>
    <label>Controlling Post</label>
    <referenceTo>Controlling_Post__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Id__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Employee ID</description>
    <externalId>true</externalId>
    <label>Employee Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ccrm/CCRMControllingPostActions.cls
/**
 * @author Emmanuel Yap
 * @since  05/2022
 * @group CCRM (Commercial CRM)
 * @description CCRMControllingPostActions is class to handle all the CCRM Controlling Post Actions
 */
public with sharing class CCRMControllingPostActions {
  /**
   * @description Before Update Automated actions of a completed Lead.
   * @name setResponsibleEmployee
   * @param records from the trigger
   * @param oldMap This Map<Id, SObject> contains the map which holds the previous values which can be used to check what value has changed in afterUpdate.
   */
  public static void setResponsibleEmployee(
    List<Controlling_Post__c> records,
    Map<Id, Controlling_Post__c> oldMap
  ) {
    Map<String, List<Controlling_Post__c>> mappedCP = mapEmployeeIDToControllingPost(
      records,
      oldMap
    );
    Set<String> employeeIds = mappedCP.keySet();
    for (User user : [
      SELECT Id, Employee_Id__c
      FROM User
      WHERE Employee_Id__c IN :employeeIds
      WITH SECURITY_ENFORCED
    ]) {
      if (mappedCP.containsKey(user.Employee_Id__c)) {
        List<Controlling_Post__c> cps = mappedCP.get(user.Employee_Id__c);
        for (Controlling_Post__c cp : cps) {
          cp.Responsible_Employee__c = user.id;
        }
      }
    }
  }

  /**
   * @description Before Update Automated actions of a completed Lead.
   * @name mapEmployeeIDToControllingPost
   * @param records from the trigger
   * @param oldMap This Map<Id, SObject> contains the map which holds the previous values which can be used to check what value has changed in afterUpdate.
   * @return `Map<String, List<Account>>` Return map of Controlling Posts with Employee ID as key
   */
  public static Map<String, List<Controlling_Post__c>> mapEmployeeIDToControllingPost(
    List<Controlling_Post__c> records,
    Map<Id, Controlling_Post__c> oldMap
  ) {
    Map<String, List<Controlling_Post__c>> mappedCP = new Map<String, List<Controlling_Post__c>>();
    for (Controlling_Post__c record : records) {
      Controlling_Post__c oldRec = oldMap != null
        ? oldMap.get(record.id)
        : null;
      if (
        oldMap == null ||
        (record.Responsible_Employee_Id__c != null &&
        isEmployeeIdChanged(record, oldRec))
      ) {
        if (mappedCP.containsKey(record.Responsible_Employee_Id__c)) {
          mappedCP.get(record.Responsible_Employee_Id__c).add(record);
        } else {
          mappedCP.put(
            record.Responsible_Employee_Id__c,
            new List<Controlling_Post__c>{ record }
          );
        }
      }
    }
    return mappedCP;
  }

  /**
   * @description Check if this Controlling Post record has updated Employee Id
   * @name isEmployeeIdChanged
   * @param record Controlling Post record
   * @param oldRec old Controlling Post record from trigger
   * @return `Boolean` True if the Employee Id is updated otherwise false.
   */
  public static Boolean isEmployeeIdChanged(
    Controlling_Post__c record,
    Controlling_Post__c oldRec
  ) {
    if (
      oldRec != null &&
      record.Responsible_Employee_Id__c != oldRec.Responsible_Employee_Id__c
    ) {
      return true;
    }
    return false;
  }
}