force-app/main/default/objects/Account/fields/Controlling_Post__c.field-meta.xml
<CustomField>
    <fullName>Controlling_Post__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Controlling Post of the Account</description>
    <inlineHelpText>A controlling post number identifies an account or customer record and is used for distribution of reports and online information within the Retail network.
A controlling post is a five character code. The first character is a letter indicating the post category; the other four characters are numeric.
 
A - Collections / Hardship / Lending Services
F &amp; L - Retail, Small Business (Retail)
P - Private Bank
R, W - Small Business - Managed</inlineHelpText>
    <label>Controlling Post</label>
    <referenceTo>Controlling_Post__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Source_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_System_ID__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Source System Id of Party received from OCV</description>
    <label>Source System ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessBankerDesktop__dlm/BusinessBankerDesktop__dlm.object-meta.xml
<CustomObject>
    <label>BusinessBankerDesktop</label>
    <mktDataModelAttributes>
        <creationType>Custom</creationType>
        <dataModelTaxonomy>Salesforce_SFDCReferenceModel_0_93</dataModelTaxonomy>
        <dataSpaceName>default</dataSpaceName>
        <isEnabled>true</isEnabled>
        <isSegmentable>true</isSegmentable>
        <isUsedForMetrics>false</isUsedForMetrics>
        <labelOverride>BusinessBankerDesktop</labelOverride>
        <masterLabel>BusinessBankerDesktop</masterLabel>
        <objectCategory>Salesforce_SFDCReferenceModel_0_93.Profile</objectCategory>
    </mktDataModelAttributes>
</CustomObject>

force-app/main/default/objects/BusinessBankerDesktop__dlm/fields/app_no__c.field-meta.xml
<CustomField>
    <fullName>app_no__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>APP_NO</label>
    <length>60</length>
    <mktDataModelFieldAttributes>
        <definitionCreationType>Custom</definitionCreationType>
        <isDynamicLookup>false</isDynamicLookup>
        <labelOverride>APP_NO</labelOverride>
        <masterLabel>APP_NO</masterLabel>
        <usageTag>None</usageTag>
    </mktDataModelFieldAttributes>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessBankerDesktop__dlm/fields/lanid__c.field-meta.xml
<CustomField>
    <fullName>lanid__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>LANID</label>
    <length>60</length>
    <mktDataModelFieldAttributes>
        <definitionCreationType>Custom</definitionCreationType>
        <isDynamicLookup>false</isDynamicLookup>
        <labelOverride>LANID</labelOverride>
        <masterLabel>LANID</masterLabel>
        <primaryIndexOrder>1</primaryIndexOrder>
        <usageTag>None</usageTag>
    </mktDataModelFieldAttributes>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Controlling_Post__c/Controlling_Post__c.object-meta.xml
<CustomObject>
    <label>Controlling Post</label>
    <nameField>
        <label>CPID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Controlling Posts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Controlling_Post__c/fields/CPID_LanID__c.field-meta.xml
<CustomField>
    <fullName>CPID_LanID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Caps</complianceGroup>
    <description>This store the LAN Id of the user record.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>CPID Lan ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Controlling_Post__c/fields/CPID_Type__c.field-meta.xml
<CustomField>
    <fullName>CPID_Type__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Integrity_Accurate;Source_CAP</complianceGroup>
    <description>This is the CPID Type</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Control Post Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Insights__dlm/Customer_Insights__dlm.object-meta.xml
<CustomObject>
    <label>Customer_Insights</label>
    <mktDataModelAttributes>
        <creationType>Custom</creationType>
        <dataModelTaxonomy>Salesforce_SFDCReferenceModel_0_93</dataModelTaxonomy>
        <dataSpaceName>default</dataSpaceName>
        <isEnabled>true</isEnabled>
        <isSegmentable>true</isSegmentable>
        <isUsedForMetrics>false</isUsedForMetrics>
        <labelOverride>Customer_Insights</labelOverride>
        <masterLabel>Customer_Insights</masterLabel>
        <objectCategory>Salesforce_SFDCReferenceModel_0_93.Profile</objectCategory>
    </mktDataModelAttributes>
</CustomObject>

force-app/main/default/objects/Customer_Insights__dlm/fields/customer_no__c.field-meta.xml
<CustomField>
    <fullName>customer_no__c</fullName>
    <label>CUSTOMER_NO</label>
    <mktDataModelFieldAttributes>
        <definitionCreationType>Custom</definitionCreationType>
        <isDynamicLookup>false</isDynamicLookup>
        <labelOverride>CUSTOMER_NO</labelOverride>
        <masterLabel>CUSTOMER_NO</masterLabel>
        <primaryIndexOrder>1</primaryIndexOrder>
        <usageTag>None</usageTag>
    </mktDataModelFieldAttributes>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Insights__dlm/fields/quarter__c.field-meta.xml
<CustomField>
    <fullName>quarter__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>QUARTER</label>
    <length>60</length>
    <mktDataModelFieldAttributes>
        <definitionCreationType>Custom</definitionCreationType>
        <isDynamicLookup>false</isDynamicLookup>
        <labelOverride>QUARTER</labelOverride>
        <masterLabel>QUARTER</masterLabel>
        <primaryIndexOrder>1</primaryIndexOrder>
        <usageTag>None</usageTag>
    </mktDataModelFieldAttributes>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Lan_Id__c.field-meta.xml
<CustomField>
    <fullName>Lan_Id__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Integrity_Trusted;Source_Salesforce</complianceGroup>
    <description>LAN ID of the user who captured the response or who the lead was routed to (if available).</description>
    <externalId>true</externalId>
    <label>Lan Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WholeOfCustomer__dlm/WholeOfCustomer__dlm.object-meta.xml
<CustomObject>
    <label>WholeOfCustomer</label>
    <mktDataModelAttributes>
        <creationType>Custom</creationType>
        <dataModelTaxonomy>Salesforce_SFDCReferenceModel_0_93</dataModelTaxonomy>
        <dataSpaceName>default</dataSpaceName>
        <isEnabled>true</isEnabled>
        <isSegmentable>true</isSegmentable>
        <isUsedForMetrics>false</isUsedForMetrics>
        <labelOverride>WholeOfCustomer</labelOverride>
        <masterLabel>WholeOfCustomer</masterLabel>
        <objectCategory>Salesforce_SFDCReferenceModel_0_93.Profile</objectCategory>
    </mktDataModelAttributes>
</CustomObject>

force-app/main/default/objects/WholeOfCustomer__dlm/fields/bus_cust_no__c.field-meta.xml
<CustomField>
    <fullName>bus_cust_no__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>BUS_CUST_NO</label>
    <length>60</length>
    <mktDataModelFieldAttributes>
        <definitionCreationType>Custom</definitionCreationType>
        <isDynamicLookup>false</isDynamicLookup>
        <labelOverride>BUS_CUST_NO</labelOverride>
        <masterLabel>BUS_CUST_NO</masterLabel>
        <primaryIndexOrder>1</primaryIndexOrder>
        <usageTag>None</usageTag>
    </mktDataModelFieldAttributes>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Agentforce/CCRMAgentCustomerInsightsTest.cls
/**
 * @author <Prasanjeet Dutta>
 * @since 2026
 * @description Test class for CCRMAgentCustomerInsights invocable Apex class.
 */
@IsTest
private class CCRMAgentCustomerInsightsTest {
  static Lib_MockProvider userMock;
  static Lib_MockProvider agentRepoMock;

  static void registerMocks() {
    userMock = Lib_MockProvider.forType(UserInfoRepository.class);
    agentRepoMock = Lib_MockProvider.forType(CCRMAgentforceRepository.class);
  }
  /**
   * @description Positive test: returns deduplicated quarterly insights for a valid Account Id in SINGLE scope.
   */
  @IsTest
  static void testGetCustomerInsightsSuccess() {
    Id mockAccId = Lib_FakeIdGenerator.getMockId(Account.SObjectType);
    Account acc = new Account(
      Id = mockAccId,
      Name = 'Test Account',
      RecordTypeId = RTAccount.clgAccount,
      Source_System_ID__c = '1001',
      OCV_ID__c = 'OCV-1234567890'
    );

    User usr = TestUtil.getUserByFirstName('APIUserTest');
    usr.Lan_Id__c = 'LAN-123';

    registerMocks();
    userMock.mock('getUser', usr);
    agentRepoMock.mock('fetchAccountById', new List<Account>{ acc });
    agentRepoMock.mock(
      'fetchAccountsByCustomerNumbers',
      new List<Account>{ acc }
    );

    // =====================
    // SOQL STUBS
    // =====================
    Test.createSoqlStub(
      Customer_Insights__dlm.sObjectType,
      new CustomerInsightSoqlStub()
    );

    Test.createSoqlStub(
      BusinessBankerDesktop__dlm.sObjectType,
      new BBDInsightSoqlStub()
    );

    Test.createSoqlStub(
      WholeOfCustomer__dlm.sObjectType,
      new WOCInsightSoqlStub()
    );

    Test.startTest();

    CCRMAgentCustomerInsights.Request req = new CCRMAgentCustomerInsights.Request();
    req.accountId = acc.Id;
    req.scope = 'SINGLE';

    List<CCRMAgentCustomerInsights.Response> resList = CCRMAgentCustomerInsights.getCustomerInsights(
      new List<CCRMAgentCustomerInsights.Request>{ req }
    );

    Test.stopTest();

    System.assertEquals(1, resList.size(), 'One response expected');

    CCRMAgentCustomerInsights.Response res = resList[0];

    System.assertEquals(
      2,
      res.bbdInsights.size(),
      'Two BBD insight rows expected'
    );

    Set<String> appNos = new Set<String>();
    for (BusinessBankerDesktop__dlm rec : res.bbdInsights) {
      appNos.add((String) rec.get('app_no__c'));
    }

    System.assertEquals(
      true,
      appNos.contains('APP-001'),
      'APP-001 should be in BBD insights'
    );
    System.assertEquals(
      true,
      appNos.contains('APP-002'),
      'APP-002 should be in BBD insights'
    );

    System.assertEquals(
      1,
      res.customerAndWocInsights.size(),
      'One customer bundle expected'
    );

    CCRMAgentCustomerInsights.CustomerInsightsWrapper w = res.customerAndWocInsights[0];

    System.assertEquals(
      '1001',
      w.customerNumber,
      'Bundle customer number should match'
    );
    System.assertEquals(
      'Test Account',
      w.customerName,
      'Bundle account name should match'
    );

    System.assertEquals(
      3,
      w.customerInsights.size(),
      'Expected 3 customer insight rows in bundle'
    );
    System.assertEquals(
      2,
      w.wocInsights.size(),
      'Expected 2 WoC insight rows in bundle'
    );

    // Quarter check
    Set<String> quarters = new Set<String>();
    for (Customer_Insights__dlm r : w.customerInsights) {
      quarters.add((String) r.get('quarter__c'));
    }

    System.assertEquals(
      true,
      quarters.contains('2024Q1'),
      '2024Q1 should be in customer insights'
    );
    System.assertEquals(
      true,
      quarters.contains('2024Q2'),
      '2024Q2 should be in customer insights'
    );
  }

  // =====================
  // STUBS
  // =====================

  class CustomerInsightSoqlStub extends SoqlStubProvider {
    public override List<SObject> handleSoqlQuery(
      SObjectType sot,
      String query,
      Map<String, Object> bindVars
    ) {
      Decimal customerNo = 1001;

      // Guard clauses to avoid deep nesting and ensure braces are used
      if (bindVars == null) {
        return buildCustomerInsightRows(sot, customerNo);
      }
      if (!bindVars.containsKey('tmpVar1')) {
        return buildCustomerInsightRows(sot, customerNo);
      }

      Object tmp = bindVars.get('tmpVar1');
      if (tmp instanceof Decimal) {
        customerNo = (Decimal) tmp;
      } else if (tmp instanceof String) {
        customerNo = Decimal.valueOf((String) tmp);
      }

      return buildCustomerInsightRows(sot, customerNo);
    }

    private List<SObject> buildCustomerInsightRows(
      SObjectType sot,
      Decimal customerNo
    ) {
      return new List<SObject>{
        Test.createStubQueryRow(
          sot,
          new Map<String, Object>{
            'quarter__c' => '2024Q1',
            'customer_no__c' => customerNo
          }
        ),
        Test.createStubQueryRow(
          sot,
          new Map<String, Object>{
            'quarter__c' => '2024Q1',
            'customer_no__c' => customerNo
          }
        ),
        Test.createStubQueryRow(
          sot,
          new Map<String, Object>{
            'quarter__c' => '2024Q2',
            'customer_no__c' => customerNo
          }
        )
      };
    }
  }

  class BBDInsightSoqlStub extends SoqlStubProvider {
    public override List<SObject> handleSoqlQuery(
      SObjectType sot,
      String query,
      Map<String, Object> bindVars
    ) {
      String lan = 'LAN-123';

      return new List<SObject>{
        Test.createStubQueryRow(
          sot,
          new Map<String, Object>{ 'lanid__c' => lan, 'app_no__c' => 'APP-001' }
        ),
        Test.createStubQueryRow(
          sot,
          new Map<String, Object>{ 'lanid__c' => lan, 'app_no__c' => 'APP-002' }
        )
      };
    }
  }

  class WOCInsightSoqlStub extends SoqlStubProvider {
    public override List<SObject> handleSoqlQuery(
      SObjectType sot,
      String query,
      Map<String, Object> bindVars
    ) {
      String custNo = '1001';

      return new List<SObject>{
        Test.createStubQueryRow(
          sot,
          new Map<String, Object>{ 'bus_cust_no__c' => custNo }
        ),
        Test.createStubQueryRow(
          sot,
          new Map<String, Object>{ 'bus_cust_no__c' => custNo }
        )
      };
    }
  }

  @IsTest
  /**
   * @description Negative test: null Account Id in SINGLE scope returns empty records in response wrapper.
   */
  static void testNullAccountId() {
    CCRMAgentCustomerInsights.Request req = new CCRMAgentCustomerInsights.Request();
    req.scope = 'SINGLE';

    List<CCRMAgentCustomerInsights.Response> result = CCRMAgentCustomerInsights.getCustomerInsights(
      new List<CCRMAgentCustomerInsights.Request>{ req }
    );

    System.assertEquals(
      1,
      result.size(),
      'One response wrapper always returned'
    );

    System.assertEquals(
      0,
      result[0].bbdInsights.size(),
      'No BBD insights when LAN not available'
    );
    System.assertEquals(
      0,
      result[0].customerAndWocInsights.size(),
      'No bundles when Account Id is null in SINGLE scope'
    );
  }

  @IsTest
  /**
   * @description Positive test: Portfolio scope with CPID_Type__c = 'P' fetches accounts from Controlling Post.
   */
  static void testPortfolioScopeWithTypePSuccess() {
    // Create Controlling Post with Type 'P'
    Id mockCpId = Lib_FakeIdGenerator.getMockId(
      Controlling_Post__c.SObjectType
    );
    Controlling_Post__c cp = new Controlling_Post__c(
      Id = mockCpId,
      Name = 'Test CP',
      CPID_LanID__c = 'LAN-123',
      CPID_Type__c = 'P'
    );

    // Create multiple accounts under this Controlling Post
    Account acc1 = new Account(
      Name = 'Test Account 1',
      RecordTypeId = RTAccount.clgAccount,
      Source_System_ID__c = '2001',
      Controlling_Post__c = mockCpId
    );
    Account acc2 = new Account(
      Name = 'Test Account 2',
      RecordTypeId = RTAccount.clgAccount,
      Source_System_ID__c = '2002',
      Controlling_Post__c = mockCpId
    );

    User usr = TestUtil.getUserByFirstName('APIUserTest');
    usr.Lan_Id__c = 'LAN-123';

    registerMocks();
    userMock.mock('getUser', usr);
    agentRepoMock.mock(
      'fetchControllingPostByLanId',
      new List<Controlling_Post__c>{ cp }
    );
    agentRepoMock.mock(
      'fetchCLGAccountsByCPID',
      new List<Account>{ acc1, acc2 }
    );
    agentRepoMock.mock(
      'fetchAccountsByCustomerNumbers',
      new List<Account>{ acc1, acc2 }
    );

    // =====================
    // SOQL STUBS
    // =====================
    Test.createSoqlStub(
      Customer_Insights__dlm.sObjectType,
      new CustomerInsightSoqlStub()
    );

    Test.createSoqlStub(
      BusinessBankerDesktop__dlm.sObjectType,
      new BBDInsightSoqlStub()
    );

    Test.createSoqlStub(
      WholeOfCustomer__dlm.sObjectType,
      new WOCInsightSoqlStub()
    );

    Test.startTest();

    CCRMAgentCustomerInsights.Request req = new CCRMAgentCustomerInsights.Request();
    req.scope = 'PORTFOLIO';
    // Note: accountId is null for portfolio scope

    List<CCRMAgentCustomerInsights.Response> resList = CCRMAgentCustomerInsights.getCustomerInsights(
      new List<CCRMAgentCustomerInsights.Request>{ req }
    );

    Test.stopTest();

    System.assertEquals(1, resList.size(), 'One response expected');

    CCRMAgentCustomerInsights.Response res = resList[0];

    System.assertEquals(
      2,
      res.bbdInsights.size(),
      'Two BBD insight rows expected'
    );

    // Should have 2 customer bundles (one for each account under the controlling post)
    System.assertEquals(
      2,
      res.customerAndWocInsights.size(),
      'Two customer bundles expected for portfolio scope'
    );

    Set<String> customerNumbers = new Set<String>();
    for (
      CCRMAgentCustomerInsights.CustomerInsightsWrapper w : res.customerAndWocInsights
    ) {
      customerNumbers.add(w.customerNumber);
    }

    System.assertEquals(
      true,
      customerNumbers.contains('2001'),
      'Customer 2001 should be in portfolio'
    );
    System.assertEquals(
      true,
      customerNumbers.contains('2002'),
      'Customer 2002 should be in portfolio'
    );
  }

  @IsTest
  /**
   * @description Positive test: Portfolio scope with CPID_Type__c = 'R' fetches accounts from Controlling Post.
   */
  static void testPortfolioScopeWithTypeRSuccess() {
    // Create Controlling Post with Type 'R'
    Id mockCpId = Lib_FakeIdGenerator.getMockId(
      Controlling_Post__c.SObjectType
    );
    Controlling_Post__c cp = new Controlling_Post__c(
      Id = mockCpId,
      Name = 'Test CP',
      CPID_LanID__c = 'LAN-123',
      CPID_Type__c = 'R'
    );

    // Create account under this Controlling Post
    Account acc1 = new Account(
      Name = 'Test Account 1',
      RecordTypeId = RTAccount.clgAccount,
      Source_System_ID__c = '3001',
      Controlling_Post__c = mockCpId
    );

    User usr = TestUtil.getUserByFirstName('APIUserTest');
    usr.Lan_Id__c = 'LAN-123';

    registerMocks();
    userMock.mock('getUser', usr);
    agentRepoMock.mock(
      'fetchControllingPostByLanId',
      new List<Controlling_Post__c>{ cp }
    );
    agentRepoMock.mock('fetchCLGAccountsByCPID', new List<Account>{ acc1 });
    agentRepoMock.mock(
      'fetchAccountsByCustomerNumbers',
      new List<Account>{ acc1 }
    );

    // =====================
    // SOQL STUBS
    // =====================
    Test.createSoqlStub(
      Customer_Insights__dlm.sObjectType,
      new CustomerInsightSoqlStub()
    );

    Test.createSoqlStub(
      BusinessBankerDesktop__dlm.sObjectType,
      new BBDInsightSoqlStub()
    );

    Test.createSoqlStub(
      WholeOfCustomer__dlm.sObjectType,
      new WOCInsightSoqlStub()
    );

    Test.startTest();

    CCRMAgentCustomerInsights.Request req = new CCRMAgentCustomerInsights.Request();
    req.scope = 'PORTFOLIO';

    List<CCRMAgentCustomerInsights.Response> resList = CCRMAgentCustomerInsights.getCustomerInsights(
      new List<CCRMAgentCustomerInsights.Request>{ req }
    );

    Test.stopTest();

    System.assertEquals(1, resList.size(), 'One response expected');

    CCRMAgentCustomerInsights.Response res = resList[0];

    System.assertEquals(
      1,
      res.customerAndWocInsights.size(),
      'One customer bundle expected for portfolio scope with Type R'
    );

    System.assertEquals(
      '3001',
      res.customerAndWocInsights[0].customerNumber,
      'Customer 3001 should be in portfolio'
    );
  }

  @IsTest
  /**
   * @description Negative test: Portfolio scope with invalid CPID_Type__c returns empty results.
   */
  static void testPortfolioScopeWithInvalidType() {
    // Create Controlling Post with invalid Type
    Id mockCpId = Lib_FakeIdGenerator.getMockId(
      Controlling_Post__c.SObjectType
    );
    Controlling_Post__c cp = new Controlling_Post__c(
      Id = mockCpId,
      Name = 'Test CP',
      CPID_LanID__c = 'LAN-123',
      CPID_Type__c = 'X' // Invalid type
    );

    User usr = TestUtil.getUserByFirstName('APIUserTest');
    usr.Lan_Id__c = 'LAN-123';

    registerMocks();
    userMock.mock('getUser', usr);
    agentRepoMock.mock(
      'fetchControllingPostByLanId',
      new List<Controlling_Post__c>{ cp }
    );

    Test.startTest();

    CCRMAgentCustomerInsights.Request req = new CCRMAgentCustomerInsights.Request();
    req.scope = 'PORTFOLIO';

    List<CCRMAgentCustomerInsights.Response> resList = CCRMAgentCustomerInsights.getCustomerInsights(
      new List<CCRMAgentCustomerInsights.Request>{ req }
    );

    Test.stopTest();

    System.assertEquals(1, resList.size(), 'One response expected');

    CCRMAgentCustomerInsights.Response res = resList[0];

    System.assertEquals(
      0,
      res.customerAndWocInsights.size(),
      'No customer bundles expected for invalid CPID Type'
    );
  }

  @IsTest
  /**
   * @description Negative test: Portfolio scope with no Controlling Post for user returns empty results.
   */
  static void testPortfolioScopeWithNoControllingPost() {
    User usr = TestUtil.getUserByFirstName('APIUserTest');
    usr.Lan_Id__c = 'LAN-999'; // No controlling post for this LAN ID

    registerMocks();
    userMock.mock('getUser', usr);
    agentRepoMock.mock(
      'fetchControllingPostByLanId',
      new List<Controlling_Post__c>()
    );

    Test.startTest();

    CCRMAgentCustomerInsights.Request req = new CCRMAgentCustomerInsights.Request();
    req.scope = 'PORTFOLIO';

    List<CCRMAgentCustomerInsights.Response> resList = CCRMAgentCustomerInsights.getCustomerInsights(
      new List<CCRMAgentCustomerInsights.Request>{ req }
    );

    Test.stopTest();

    System.assertEquals(1, resList.size(), 'One response expected');

    CCRMAgentCustomerInsights.Response res = resList[0];

    System.assertEquals(
      0,
      res.customerAndWocInsights.size(),
      'No customer bundles expected when no Controlling Post found'
    );
  }

  @IsTest
  /**
   * @description Negative test: Portfolio scope with null LAN ID returns empty results.
   */
  static void testPortfolioScopeWithNullLanId() {
    User usr = TestUtil.getUserByFirstName('APIUserTest');
    usr.Lan_Id__c = null;

    registerMocks();
    userMock.mock('getUser', usr);

    Test.startTest();

    CCRMAgentCustomerInsights.Request req = new CCRMAgentCustomerInsights.Request();
    req.scope = 'PORTFOLIO';

    List<CCRMAgentCustomerInsights.Response> resList = CCRMAgentCustomerInsights.getCustomerInsights(
      new List<CCRMAgentCustomerInsights.Request>{ req }
    );

    Test.stopTest();

    System.assertEquals(1, resList.size(), 'One response expected');

    CCRMAgentCustomerInsights.Response res = resList[0];

    System.assertEquals(
      0,
      res.customerAndWocInsights.size(),
      'No customer bundles expected when LAN ID is null'
    );
  }
}