force-app/main/default/objects/Account/fields/Controlling_Post__c.field-meta.xml
<CustomField>
    <fullName>Controlling_Post__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Controlling Post of the Account</description>
    <inlineHelpText>A controlling post number identifies an account or customer record and is used for distribution of reports and online information within the Retail network.
A controlling post is a five character code. The first character is a letter indicating the post category; the other four characters are numeric.
 
A - Collections / Hardship / Lending Services
F &amp; L - Retail, Small Business (Retail)
P - Private Bank
R, W - Small Business - Managed</inlineHelpText>
    <label>Controlling Post</label>
    <referenceTo>Controlling_Post__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CPID__c.field-meta.xml
<CustomField>
    <fullName>CPID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_OCV</complianceGroup>
    <description>Control post identification number to identify managed Customers</description>
    <label>Controlling Post Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Controlling_Post__c/Controlling_Post__c.object-meta.xml
<CustomObject>
    <label>Controlling Post</label>
    <nameField>
        <label>CPID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Controlling Posts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Controlling_Post__c/fields/CPID__c.field-meta.xml
<CustomField>
    <fullName>CPID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Salesforce</complianceGroup>
    <description>T_SET CPID Number</description>
    <externalId>true</externalId>
    <label>CPID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/mlcrm/MLCRMCustomerSetCPIDLookupBatch.cls
/**
 * @author Ankit Garg
 * @since  28/July/2023
 * @group MLCRM (Mobile Lending CRM)
 * @description MLCRMCustomerSetCPIDLookupBatch is batch class to populate Controlling Post Id based on CP Id on Account records.
 */
public class MLCRMCustomerSetCPIDLookupBatch implements Database.Batchable<sObject> {
  /**
   * @description This method is used to collect the data from Account.
   * @name start
   * @param objSchedule standard database batachable varaible
   * @return Database.QueryLocator locator object
   * @author Ankit Garg
   * @US CC-4761
   */
  public Database.QueryLocator start(Database.BatchableContext objSchedule) {
    String query = 'Select id, CPID__c, Controlling_Post__c FROM Account WHERE CPID__c <> \'\' and Controlling_Post__c = null';
    return Database.getQueryLocator(query);
  }

  /**
   * @description This method is used topopulate Controlling Post Id based on CP Id on Account records.
   * @name execute
   * @param objSchedule standard database batachable varaible
   * @param scope List of chunk records for which share records needs to be updated.
   * @author Ankit Garg
   * @US CC-4761
   */
  public void execute(
    Database.BatchableContext objSchedule,
    List<Account> scope
  ) {
    if (!scope.isEmpty()) {
      MLCRMCustomerSetCPIDLookupBatchAction.setControllingPost(scope);
    }
  }

  /**
   * @description This method runs when all batch job gets completed
   * @name finish
   * @param objSchedule standard database batachable varaible
   * @author Ankit Garg
   * @US CC-4761
   */
  public void finish(Database.BatchableContext objSchedule) {
  }
}