force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <description>Used for writing updates from OCV Party event messages. It is constructed in Mulesoft.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Account_Key__c.field-meta.xml
<CustomField>
    <fullName>Account_Key__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Field to store unique identifier for a Financial Account record received from OCV</description>
    <externalId>true</externalId>
    <label>Account Key</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__PrimaryOwner__c.field-meta.xml
<CustomField>
    <fullName>FinServ__PrimaryOwner__c</fullName>
    <complianceGroup>Integrity - Accurate</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
    <relationshipName>ClientFinancialAccounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <formula>FinServ__PrimaryOwner__r.OCV_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OCV_ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Primary_Owner_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Primary_Owner_Start_Date__c</fullName>
    <complianceGroup>Integrity_Trusted;Source_OCV</complianceGroup>
    <description>Date when current primary owner relationship started. Field is provided by OCV</description>
    <label>Primary Owner Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/FinServ__FinancialAccountRole__c.object-meta.xml
<CustomObject>
    <description>Represents the role occupied by a person or organizational entity that is involved with a financial account, such as a beneficiary or trustee.</description>
    <label>Financial Account Role</label>
    <nameField>
        <displayFormat>FAR-{000000000}</displayFormat>
        <label>Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Source - OCV;Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <description>This field will store External ID generated by concatenating Account External ID + Financial Account Key + Financial Account Role + Start date</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy - Personal Information</complianceGroup>
    <description>Financial account that this role is related to.</description>
    <label>Financial Account</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>FinServ__StartDate__c</fullName>
    <complianceGroup>Integrity_Accurate</complianceGroup>
    <defaultValue>today()</defaultValue>
    <description>Start date when the organizational entity or person assumed this role.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/FinancialAccountRoleCommonActionsTest.cls
/**
 *
 * @author Jasmine Nguyen
 * @since 02/2021
 * @description Test class for FinancialAccountRoleCommonActions (@link FinancialAccountRoleCommonActionsTest)
 */

@isTest
public with sharing class FinancialAccountRoleCommonActionsTest {
  @TestSetup
  static void makeData() {
    Account customerAccount = new Account();
    customerAccount.FirstName = 'John';
    customerAccount.LastName = 'Doe';
    customerAccount.OCV_Id__c = '123456';
    customerAccount.External_Id__c = 'afs8032lfs0';
    insert customerAccount;
  }

  // Test setting financial role's external Id successfully
  @isTest
  static void testSetFinancialRoleExternalIdSuccessfully() {
    Account customerAccount = [
      SELECT Id, External_Id__c
      FROM Account
      LIMIT 1
    ][0];
    FinServ__FinancialAccount__c financialAccount = new FinServ__FinancialAccount__c();
    financialAccount.Name = 'Savings Account';
    financialAccount.Account_Key__c = '999000111';
    financialAccount.FinServ__PrimaryOwner__c = customerAccount.Id;
    financialAccount.Primary_Owner_Start_Date__c = Date.valueOf('2021-02-10');
    Test.startTest();
    insert financialAccount;
    Test.stopTest();
    String externalIdString =
      String.valueOf(customerAccount.External_Id__c) +
      '_' +
      String.valueOf(financialAccount.Account_Key__c) +
      '_' +
      'PrimaryOwner' +
      '_' +
      '10022021';
    List<FinServ__FinancialAccountRole__c> financialAccountRoles = [
      SELECT Id, External_Id__c, FinServ__StartDate__c
      FROM FinServ__FinancialAccountRole__c
    ];
    // Assertions
    System.assertEquals(1, financialAccountRoles.size());
    System.assertEquals(
      externalIdString,
      financialAccountRoles[0].External_Id__c
    );
    System.assertEquals(
      Date.valueOf('2021-02-10'),
      financialAccountRoles[0].FinServ__StartDate__c
    );
  }

  // Test setting financial role's external Id with exception thrown
  @isTest
  static void testSetFinancialRoleExternalIdWithException() {
    Account customerAccount = [SELECT Id FROM Account LIMIT 1][0];
    FinServ__FinancialAccount__c financialAccount = new FinServ__FinancialAccount__c();
    financialAccount.Name = 'Savings Account';
    financialAccount.Account_Key__c = '999000111';
    financialAccount.FinServ__PrimaryOwner__c = customerAccount.Id;
    Test.startTest();
    try {
      insert financialAccount;
    } catch (Exception e) {
      System.assertNotEquals(null, e);
    }
    Test.stopTest();
  }
}