force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <description>Used for writing updates from OCV Party event messages. It is constructed in Mulesoft.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Broker_Relation__c/Broker_Relation__c.object-meta.xml
<CustomObject>
    <description>Facilitates RBMs &amp; Enablement Mangers to establish and manage relationship between RBMs &amp; and their brokers.</description>
    <label>Broker Relation</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Broker Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker_Relation__c/fields/Aggregator__c.field-meta.xml
<CustomField>
    <fullName>Aggregator__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Aggregator to which this Broker Set would be associated with.
Requirement: Ensure it&apos;s an Account of record type Organization.</description>
    <label>Aggregator</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Aggregator must be an Organization account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organisation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Broker Relations</relationshipLabel>
    <relationshipName>Broker_Relations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Relation__c/fields/Associated_Broker_Set__c.field-meta.xml
<CustomField>
    <fullName>Associated_Broker_Set__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents the association between the office group and Broker set.</description>
    <label>Associated Broker Set</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3 OR 4) AND 5</booleanFilter>
        <errorMessage>Only an Office Group can be associated to a Broker Set.</errorMessage>
        <filterItems>
            <field>Broker_Relation__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Broker Set</value>
        </filterItems>
        <filterItems>
            <field>Broker_Relation__c.Primary_RBM__c</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Broker_Relation__c.Secondary_RBM__c</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$UserRole.DeveloperName</field>
            <operation>equals</operation>
            <value>Broker_Enablement_Manager</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Office Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Broker_Relation__c</referenceTo>
    <relationshipLabel>Office Groups</relationshipLabel>
    <relationshipName>Office_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Relation__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source_Salesforce</complianceGroup>
    <description>External Id</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External_Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Broker_Relation__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source_Salesforce</complianceGroup>
    <defaultValue>true</defaultValue>
    <description>To capture whether the Broker Set / Office Group is active or not.</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Broker_Relation__c/fields/Primary_RBM__c.field-meta.xml
<CustomField>
    <fullName>Primary_RBM__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary RBM who would be managing this Broker Set.
Requirements: Only allowed on a Broker Set. Must be different from Secondary RBM. Role should be RBM.</description>
    <label>Primary RBM</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3</booleanFilter>
        <errorMessage>Primary RBM must be different from the Secondary RBM.</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Broker Set</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.DeveloperName</field>
            <operation>equals</operation>
            <value>Residential_Broker_Manager</value>
        </filterItems>
        <filterItems>
            <field>User.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Secondary_RBM__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Primary_Broker_Relations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Relation__c/fields/Secondary_RBM__c.field-meta.xml
<CustomField>
    <fullName>Secondary_RBM__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Secondary RBM who would be managing this Broker Set.
Requirements: Only allowed on a Broker Set. Role should be RBM.</description>
    <label>Secondary RBM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Broker Set</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.DeveloperName</field>
            <operation>equals</operation>
            <value>Residential_Broker_Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Secondary_Broker_Relations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Relation__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source_Salesforce</complianceGroup>
    <description>Signifies the type of segment this Broker Set is related.</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APN</fullName>
                <label>APN (Advocate, Prospect, Nurture)</label>
            </value>
            <value>
                <fullName>TD</fullName>
                <label>TD (Transactional, Disengaged)</label>
            </value>
            <value>
                <fullName>Advocate</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Nurture</fullName>
            </value>
            <value>
                <fullName>Transactional</fullName>
            </value>
            <value>
                <fullName>Disengaged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Relation__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source_Salesforce</complianceGroup>
    <description>Represents the state to which this Broker Set is Associated.
SAO = Sub-Aggregator Originator</description>
    <label>SAO State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NSW/ACT</fullName>
            </value>
            <value>
                <fullName>QLD/NT</fullName>
            </value>
            <value>
                <fullName>VIC/TAS</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Broker_Set__c.field-meta.xml
<CustomField>
    <fullName>Broker_Set__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents the Broker Set to which this contact is associated with.
Requirements: Only populated on a Broker Contact, and only an broker set can be selected whose Aggregator is the same as the Broker Contact.</description>
    <label>Broker Set</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Brokers must be from the aggregators linked to this Broker Set.</errorMessage>
        <filterItems>
            <field>Broker_Relation__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Broker Set</value>
        </filterItems>
        <filterItems>
            <field>Broker_Relation__c.Aggregator__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Broker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Broker_Relation__c</referenceTo>
    <relationshipLabel>Brokers (Broker Set)</relationshipLabel>
    <relationshipName>Broker_Set_Brokers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>This field will store External ID generated by concatenating Account External ID + Financial Account Key + Financial Account Role + Start date</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Office_Group__c.field-meta.xml
<CustomField>
    <fullName>Office_Group__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents the Office Group to which this contact is associated with.
Requirements: Only populated on a Broker Contact, and only an Office Group can be selected whose Broker Set is the same as the Broker Contact.</description>
    <label>Office Group</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3</booleanFilter>
        <errorMessage>The Office Group is linked to a different Broker Set, please change the Broker Set for the broker first before changing the Office Group.</errorMessage>
        <filterItems>
            <field>Broker_Relation__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Office Group</value>
        </filterItems>
        <filterItems>
            <field>Broker_Relation__c.Associated_Broker_Set__c</field>
            <operation>equals</operation>
            <valueField>$Source.Broker_Set__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Broker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Broker_Relation__c</referenceTo>
    <relationshipLabel>Brokers (Office Group)</relationshipLabel>
    <relationshipName>Office_Group_Brokers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_RBM__c.field-meta.xml
<CustomField>
    <fullName>Primary_RBM__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Captures the Primary RBM Information.</description>
    <formula>HYPERLINK(
  &apos;/&apos; &amp; Broker_Set__r.Primary_RBM__c,
  TRIM(
    Broker_Set__r.Primary_RBM__r.FirstName
    &amp; &apos; &apos; 
    &amp; Broker_Set__r.Primary_RBM__r.LastName
  ),
  &apos;_self&apos;
)
&amp; BR() 
&amp; Broker_Set__r.Primary_RBM__r.Title</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary RBM</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Secondary_RBM__c.field-meta.xml
<CustomField>
    <fullName>Secondary_RBM__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Captures the Secondary  RBM Information.</description>
    <formula>HYPERLINK(
  &apos;/&apos; &amp; Broker_Set__r.Secondary_RBM__c,
  TRIM(
    Broker_Set__r.Secondary_RBM__r.FirstName
    &amp; &apos; &apos;
    &amp; Broker_Set__r.Secondary_RBM__r.LastName
  ),
  &apos;_self&apos;
)
&amp; BR()
&amp; Broker_Set__r.Secondary_RBM__r.Title</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Secondary RBM</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Captures the Segment of the associated Broker Set.</description>
    <formula>TEXT(Broker_Set__r.Segment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Broker.recordType-meta.xml
<RecordType>
    <fullName>Broker</fullName>
    <active>true</active>
    <description>Display Broker details</description>
    <label>Broker</label>
</RecordType>

force-app/main/default/classes/BrokerRelationActionsTest.cls
/**
 * @author Grace Anusha
 * @since 11 Feb 2025
 * @description BrokerRelationActionsTest is the test class for BrokerRelationActions
 */
@isTest
public class BrokerRelationActionsTest {
  // Mock provider for the BrokerRelationRepository class
  private static final Lib_MockProvider BROKER_RELATION_REPOSITORY_MOCK = Lib_MockProvider.forType(
    BrokerRelationRepository.class
  );
  private static final Lib_MockProvider RETAIL_CONTACT_REPOSITORY_MOCK = Lib_MockProvider.forType(
    RetailContactRepository.class
  );
  private static final Lib_MockProvider BROKER_SETTINGS_REPOSITORY_MOCK = Lib_MockProvider.forType(
    BrokerSettingsRepository.class
  );

  static Broker_Relation__c mockBrokerRelation() {
    Broker_Relation__c brokerSet = (Broker_Relation__c) JSON.deserialize(
      '{"attributes":{"type":"Broker_Relation__c","url":"/services/data/v63.0/sobjects/Broker_Relation__c/a2oAD000000YmrpYAC"},"Id":"a2oAD000000YmrpYAC","Name":"Broker Set 1","State__c":"WA","Segment__c":"APN","Aggregator__c":"001AD00000hBhx3YAC","IsActive__c":true,"Office_Groups__r":{"totalSize":1,"done":true,"records":[{"attributes":{"type":"Broker_Relation__c","url":"/services/data/v63.0/sobjects/Broker_Relation__c/a2oAD000000YmtRYAS"},"Id":"a2oAD000000YmtRYAS"}]},"Primary_RBM__c":"005AD00000CcmkVYAR","Secondary_RBM__c":"005AD00000CP437YAD","RecordTypeId":"012AD000001sGQbYAM","Broker_Set_Brokers__r":{"totalSize":1,"done":true,"records":[{"attributes":{"type":"Contact","url":"/services/data/v63.0/sobjects/Contact/003AD00000aZN8VYAW"},"Broker_Set__c":"a2oAD000000YmrpYAC","Id":"003AD00000aZN8VYAW","RecordTypeId":"012Oa000001rCvLIAU"}]}}',
      Broker_Relation__c.class
    );
    return brokerSet;
  }

  static Broker_Relation__c mockOfficeGroup() {
    Broker_Relation__c officeGroup = (Broker_Relation__c) JSON.deserialize(
      '{"attributes":{"type":"Broker_Relation__c","url":"/services/data/v63.0/sobjects/Broker_Relation__c/a2oAD000000Yq0zYAC"},"Id":"a2oAD000000Yq0zYAC","Name":"OG 4 1","Segment__c":"APN","Aggregator__c":"001AD00000hBhx3YAC","IsActive__c":true,"RecordTypeId":"012AD000001sGQcYAM","Office_Group_Brokers__r":{"totalSize":1,"done":true,"records":[{"attributes":{"type":"Contact","url":"/services/data/v63.0/sobjects/Contact/003AD00000aZN8VYAW"},"Office_Group__c":"a2oAD000000Yq0zYAC","Id":"003AD00000aZN8VYAW","RecordTypeId":"012Oa000001rCvLIAU"}]}}',
      Broker_Relation__c.class
    );
    return officeGroup;
  }

  /**
   * @description test method for populateExternalId
   * @author  Grace Anusha | Salesforce | 11-02-2025
   **/
  @isTest
  static void testPopulateExternalIdOnInsert() {
    Broker_Relation__c brokerSet = mockBrokerRelation();
    BrokerRelationActions.populateExternalId(
      new List<Broker_Relation__c>{ brokerSet }
    );

    Assert.areEqual(
      'Broker_Set_1-APN-WA',
      brokerSet.External_Id__c,
      'External Id should be in the format Name_Segment_State.'
    );
  }

  /**
   * @description test method for populateExternalIdOnFilteredBrokerSet
   * @author  Grace Anusha | Salesforce | 11-02-2025
   **/
  @isTest
  static void testPopulateExternalIdOnFilteredBrokerSet() {
    Broker_Relation__c brokerSet2 = mockBrokerRelation().clone(true, true);
    brokerSet2.Name = 'Broker Set 2';
    brokerSet2.state__c = 'SA';
    brokerSet2.segment__c = 'TD';

    BrokerRelationActions.populateExternalIdOnFilteredBrokerSet(
      new Map<Id, Broker_Relation__c>{
        mockBrokerRelation().Id => mockBrokerRelation()
      },
      new List<Broker_Relation__c>{ brokerSet2 }
    );

    Assert.areEqual(
      'Broker_Set_2-TD-SA',
      brokerSet2.External_Id__c,
      'External Id should be in the format Name_Segment_State.'
    );
  }
  /**
   * @description test method for RestrictAggregatorChange
   * @author  Grace Anusha | Salesforce | 11-02-2025
   **/
  @isTest
  static void testRestrictAggregatorChange() {
    BROKER_RELATION_REPOSITORY_MOCK.mock(
      'getBrokerSetWithBrokerAndOfficeGroup',
      new List<Broker_Relation__c>{ mockBrokerRelation() }
    );
    Broker_Relation__c brokerSetNew = mockBrokerRelation().clone(true, true);
    brokerSetNew.Aggregator__c = Lib_FakeIdGenerator.getMockId(
      Account.SObjectType
    );
    BrokerRelationActions.restrictAggregatorChange(
      new Map<Id, Broker_Relation__c>{
        mockBrokerRelation().Id => mockBrokerRelation()
      },
      new List<Broker_Relation__c>{ brokerSetNew }
    );

    Assert.isTrue(brokerSetNew.hasErrors(), 'Broker set should have errors.');
  }
  /**
   * @description test method for showError
   * @author  Grace Anusha | Salesforce | 11-02-2025
   **/
  @isTest
  static void testShowError() {
    Broker_Relation__c brokerSetNew = mockBrokerRelation().clone(true, true);
    brokerSetNew.Aggregator__c = Lib_FakeIdGenerator.getMockId(
      Account.SObjectType
    );
    BrokerRelationActions.showErrorAggregatorChange(
      new Map<Id, Broker_Relation__c>{
        mockBrokerRelation().Id => mockBrokerRelation()
      },
      new List<Broker_Relation__c>{ brokerSetNew }
    );
    Assert.isTrue(brokerSetNew.hasErrors(), 'Broker set should have errors.');
  }

  /**
   * @description test method for showErrorIfOfficeGroupHasBrokers
   * @author  Grace Anusha | Salesforce | 11-02-2025
   **/
  @isTest
  static void testShowErrorIfOfficeGroupHasBrokers() {
    Broker_Relation__c officeGroup = mockOfficeGroup();
    BrokerRelationActions.showErrorIfOfficeGroupHasBrokers(
      new Map<Id, Broker_Relation__c>{ officeGroup.Id => officeGroup },
      new List<Broker_Relation__c>{ officeGroup },
      'error msg'
    );

    Assert.isFalse(
      officeGroup.Office_Group_Brokers__r.isEmpty(),
      'There are brokers associated with office group'
    );
    Assert.isTrue(officeGroup.hasErrors(), 'Broker set should have errors.');
  }

  /**
   * @description test method for restrictBrokerSetChangeOnOfficeGroup
   * @author  Grace Anusha | Salesforce | 11-02-2025
   **/
  @isTest
  static void testRestrictBrokerSetChangeOnOfficeGroup() {
    BROKER_RELATION_REPOSITORY_MOCK.mock(
      'getBrokerMapOfficeGroup',
      new List<Broker_Relation__c>{ mockOfficeGroup() }
    );
    Broker_Relation__c officeGroupNew = mockOfficeGroup().clone(true, true);
    officeGroupNew.Associated_Broker_Set__c = Lib_FakeIdGenerator.getMockId(
      Broker_Relation__c.SObjectType
    );
    BrokerRelationActions.restrictBrokerSetChangeOnOfficeGroup(
      new Map<Id, Broker_Relation__c>{
        mockOfficeGroup().Id => mockOfficeGroup()
      },
      new List<Broker_Relation__c>{ officeGroupNew }
    );

    Assert.isTrue(officeGroupNew.hasErrors(), 'Broker set should have errors.');
  }

  /**
   * @description test method for blockDeactivationOfficeGroup
   * @author  Grace Anusha | Salesforce | 11-02-2025
   **/
  @isTest
  static void testBlockDeactivationOfficeGroup() {
    BROKER_RELATION_REPOSITORY_MOCK.mock(
      'getBrokerMapOfficeGroup',
      new List<Broker_Relation__c>{ mockBrokerRelation() }
    );
    Broker_Relation__c officeGroupNew = mockOfficeGroup().clone(true, true);
    officeGroupNew.IsActive__c = false;
    BrokerRelationActions.blockDeactivationOfficeGroup(
      new Map<Id, Broker_Relation__c>{
        mockOfficeGroup().Id => mockOfficeGroup()
      },
      new List<Broker_Relation__c>{ officeGroupNew }
    );

    Assert.isFalse(
      officeGroupNew.hasErrors(),
      'Broker Set should not have errors.'
    );
  }

  /**
   * @description This method tests the case where no deactivation restrictions apply
   * and the Broker_Relation__c record can be deactivated without errors.
   * @author  Utkarsh Singh | Salesforce | 20-02-2025
   **/
  @isTest
  static void testNoDeactivationRestriction() {
    BROKER_RELATION_REPOSITORY_MOCK.mock(
      'getBrokerMap',
      new List<Broker_Relation__c>{ mockBrokerRelation() }
    );
    Broker_Relation__c brokerSet2 = mockBrokerRelation().clone(true, true);
    brokerSet2.IsActive__c = false;

    BrokerRelationActions.restrictDeactivationOfBrokerSet(
      new Map<Id, Broker_Relation__c>{
        mockBrokerRelation().Id => mockBrokerRelation()
      },
      new List<Broker_Relation__c>{ brokerSet2 }
    );

    Assert.isTrue(brokerSet2.hasErrors(), 'Broker set should have errors.');
  }

  /**
   * @description test method for restrictDeactivationRelatedOfficeGroup
   * @author  Saurabh Chauhan | Salesforce | 07-04-2025
   **/
  @isTest
  static void testRestrictDeactivationRelatedOfficeGroup() {
    BROKER_RELATION_REPOSITORY_MOCK.mock(
      'getOfficeGroupRelatedToBrokerSet',
      new List<Broker_Relation__c>{ mockBrokerRelation() }
    );
    Broker_Relation__c brokerSet2 = mockBrokerRelation().clone(true, true);
    brokerSet2.IsActive__c = false;

    BrokerRelationActions.restrictDeactivationRelatedOfficeGroup(
      new Map<Id, Broker_Relation__c>{
        mockBrokerRelation().Id => mockBrokerRelation()
      },
      new List<Broker_Relation__c>{ brokerSet2 }
    );

    Assert.isFalse(
      brokerSet2.Office_Groups__r.isEmpty(),
      'Broker set should have office groups.'
    );
    Assert.isTrue(brokerSet2.hasErrors(), 'Broker set should have errors.');
  }

  /**
   * @description test method for showErrorIfBrokerSetHasOfficeGroups
   * @author  Saurabh Chauhan | Salesforce | 07-04-2025
   **/
  @isTest
  static void testShowErrorIfBrokerSetHasOfficeGroups() {
    BROKER_RELATION_REPOSITORY_MOCK.mock(
      'getOfficeGroupRelatedToBrokerSet',
      new List<Broker_Relation__c>{ mockBrokerRelation() }
    );
    Broker_Relation__c brokerSet2 = mockBrokerRelation().clone(true, true);
    brokerSet2.IsActive__c = false;

    BrokerRelationActions.showErrorIfBrokerSetHasOfficeGroups(
      new Map<Id, Broker_Relation__c>{
        mockBrokerRelation().Id => mockBrokerRelation()
      },
      new List<Broker_Relation__c>{ brokerSet2 }
    );

    Assert.isFalse(
      brokerSet2.Office_Groups__r.isEmpty(),
      'Broker set should have office groups.'
    );
    Assert.isTrue(brokerSet2.hasErrors(), 'Broker set should have errors.');
  }

  /**
   * @description test method for showErrorIfBrokerSetHasBrokers
   * @author  Saurabh Chauhan | Salesforce | 07-04-2025
   **/
  @isTest
  static void testShowErrorIfBrokerSetHasBrokers() {
    BROKER_RELATION_REPOSITORY_MOCK.mock(
      'getOfficeGroupRelatedToBrokerSet',
      new List<Broker_Relation__c>{ mockBrokerRelation() }
    );
    Broker_Relation__c brokerSet2 = mockBrokerRelation().clone(true, true);
    brokerSet2.IsActive__c = false;

    BrokerRelationActions.showErrorIfBrokerSetHasBrokers(
      new Map<Id, Broker_Relation__c>{
        mockBrokerRelation().Id => mockBrokerRelation()
      },
      new List<Broker_Relation__c>{ brokerSet2 }
    );

    Assert.isFalse(
      brokerSet2.Broker_Set_Brokers__r.isEmpty(),
      'Broker set should have office groups.'
    );
    Assert.isTrue(brokerSet2.hasErrors(), 'Broker set should have errors.');
  }

  /**
   * @description test method for publishBrokerRelationEvents
   * @author  Saurabh Chauhan | Salesforce | 06-03-2025
   **/
  @isTest
  static void testPublishBrokerRelationEvents() {
    RETAIL_CONTACT_REPOSITORY_MOCK.mock(
      'getContacts',
      new List<Contact>{ RetailBrokerRelationEventActionsTest.mockContact() }
    );
    BROKER_RELATION_REPOSITORY_MOCK.mock(
      'queryBrokerRelationWithRbmDetails',
      mockBrokerList()
    );
    RETAIL_CONTACT_REPOSITORY_MOCK.mock(
      'getBrokerSetContacts',
      new List<Contact>{ RetailBrokerRelationEventActionsTest.mockContact() }
    );
    BROKER_RELATION_REPOSITORY_MOCK.mock('queryRbmUsers', mockRbmUserList());
    BrokerSettings__c mockSettings = new BrokerSettings__c();
    mockSettings.BypassBrokerRelationEvent__c = false;
    BROKER_SETTINGS_REPOSITORY_MOCK.mock('get', mockSettings);

    Broker_Relation__c newBrokerSet = (Broker_Relation__c) JSON.deserialize(
      '{"attributes":{"type":"Broker_Relation__c","url":"/services/data/v63.0/sobjects/Broker_Relation__c/a2oAD000000ZI5JYAW"},"Id":"a2oAD000000ZI5JYAW","Primary_RBM__c":"005Oa000005OyubIAC","Secondary_RBM__c":"005Oa000003fFuDIAU","RecordTypeId":"012AD000001tpEDYAY","Primary_RBM__r":{"attributes":{"type":"User","url":"/services/data/v63.0/sobjects/User/005Oa000005OyubIAC"},"Id":"005Oa000005OyubIAC","Lan_Id__c":"manish5"},"Secondary_RBM__r":{"attributes":{"type":"User","url":"/services/data/v63.0/sobjects/User/005Oa000003fFuDIAU"},"Id":"005Oa000003fFuDIAU","Lan_Id__c":"sauDevtest"}}',
      Broker_Relation__c.class
    );

    Broker_Relation__c oldBrokerSet = newBrokerSet;
    oldBrokerSet.Primary_RBM__c = Lib_FakeIdGenerator.getMockId(
      User.SObjectType
    );

    List<SObject> publishedEvents = BrokerRelationActions.publishBrokerRelationEvents(
      new Map<Id, Broker_Relation__c>{ oldBrokerSet.Id => oldBrokerSet },
      new Map<Id, Broker_Relation__c>{ newBrokerSet.Id => newBrokerSet }
    );

    Assert.isFalse(
      publishedEvents.isEmpty(),
      'No published events were returned'
    );
  }

  /**
   * @description to create mock Broker Relation List
   * @author  Atharv Jakate | Salesforce | 23-06-2025
   * @return List<Broker_Relation__c>
   **/
  private static List<Broker_Relation__c> mockBrokerList() {
    Broker_Relation__c newBrokerSet = (Broker_Relation__c) JSON.deserialize(
      '{"attributes":{"type":"Broker_Relation__c","url":"/services/data/v63.0/sobjects/Broker_Relation__c/a2oAD000000ZI5JYAW"},"Id":"a2oAD000000ZI5JYAW","Primary_RBM__c":"005Oa000005OyubIAC","Secondary_RBM__c":"005Oa000003fFuDIAU","RecordTypeId":"012AD000001tpEDYAY","Primary_RBM__r":{"attributes":{"type":"User","url":"/services/data/v63.0/sobjects/User/005Oa000005OyubIAC"},"Id":"005Oa000005OyubIAC","Lan_Id__c":"manish5"},"Secondary_RBM__r":{"attributes":{"type":"User","url":"/services/data/v63.0/sobjects/User/005Oa000003fFuDIAU"},"Id":"005Oa000003fFuDIAU","Lan_Id__c":"sauDevtest"}}',
      Broker_Relation__c.class
    );

    Broker_Relation__c oldBrokerSet = (Broker_Relation__c) JSON.deserialize(
      '{"attributes":{"type":"Broker_Relation__c","url":"/services/data/v63.0/sobjects/Broker_Relation__c/a2oAD000000ZUuTYAW"},"Id":"a2oAD000000ZUuTYAW","Primary_RBM__c":"005Oa000003fFuDIAU","Secondary_RBM__c":"005Oa000003wiQMIAY","RecordTypeId":"012AD000001tpEDYAY","Primary_RBM__r":{"attributes":{"type":"User","url":"/services/data/v63.0/sobjects/User/005Oa000003fFuDIAU"},"Id":"005Oa000003fFuDIAU","Lan_Id__c":"sauDevtest"},"Secondary_RBM__r":{"attributes":{"type":"User","url":"/services/data/v63.0/sobjects/User/005Oa000003wiQMIAY"},"Id":"005Oa000003wiQMIAY","Lan_Id__c":"utkarsh9"}}',
      Broker_Relation__c.class
    );

    return new List<Broker_Relation__c>{ oldBrokerSet, newBrokerSet };
  }

  /**
   * @description to create mock rbm users
   * @author  Atharv Jakate | Salesforce | 23-06-2025
   * @return List<User>
   **/
  private static List<User> mockRbmUserList() {
    List<User> userList = (List<User>) JSON.deserialize(
      '[{"attributes":{"type":"User","url":"/services/data/v63.0/sobjects/User/005Oa000003fFuDIAU"},"Id":"005Oa000003fFuDIAU","Name":"Saurabh Chauhan","Lan_Id__c":"sauDevtest"},{"attributes":{"type":"User","url":"/services/data/v63.0/sobjects/User/0055m000000XnEPAA0"},"Id":"0055m000000XnEPAA0","Name":"Jasmine Nguyen","Lan_Id__c":"jasTest"},{"attributes":{"type":"User","url":"/services/data/v63.0/sobjects/User/005Oa000005OyubIAC"},"Id":"005Oa000005OyubIAC","Name":"Manish Bisht","Lan_Id__c":"manish5"},{"attributes":{"type":"User","url":"/services/data/v63.0/sobjects/User/005Oa000003wiQMIAY"},"Id":"005Oa000003wiQMIAY","Name":"Utkarsh Singh","Lan_Id__c":"utkarsh9"}]',
      List<User>.class
    );

    return userList;
  }
}