force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <description>Used for writing updates from OCV Party event messages. It is constructed in Mulesoft.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>This field will store External ID generated by concatenating Account External ID + Financial Account Key + Financial Account Role + Start date</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ContactPointAddress/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>OCV + Source System Name + Source System Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FinServ__ContactContactRelation__c/FinServ__ContactContactRelation__c.object-meta.xml
<CustomObject>
    <description>A relationship between any two individuals.</description>
    <label>Contact-Contact Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Contact Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Contact Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__ContactContactRelation__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - OCV</complianceGroup>
    <description>External Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FinServ__ContactContactRelation__c/fields/FinServ__Contact__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Contact__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Related Contacts</relationshipLabel>
    <relationshipName>RelatedFromContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__ContactContactRelation__c/fields/FinServ__RelatedContact__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelatedContact__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>RelatedToContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__ContactContactRelation__c/fields/FinServ__Role__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Role__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Sensitive_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FinServ__ReciprocalRole__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Contact Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FinServ__ReciprocalRole__c</referenceTo>
    <relationshipName>ContactReciprocalRole</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__ContactContactRelation__c/fields/OCV_Role__c.field-meta.xml
<CustomField>
    <fullName>OCV_Role__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Personal Information;Source - OCV</complianceGroup>
    <description>OCV Role</description>
    <label>OCV Role</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/FinServ__FinancialAccountRole__c.object-meta.xml
<CustomObject>
    <description>Represents the role occupied by a person or organizational entity that is involved with a financial account, such as a beneficiary or trustee.</description>
    <label>Financial Account Role</label>
    <nameField>
        <displayFormat>FAR-{000000000}</displayFormat>
        <label>Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Source - OCV;Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <description>This field will store External ID generated by concatenating Account External ID + Financial Account Key + Financial Account Role + Start date</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy - Personal Information</complianceGroup>
    <description>Financial account that this role is related to.</description>
    <label>Financial Account</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelatedAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the organizational entity that is involved with the financial account.</description>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__RelatedContact__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelatedContact__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy - Personal Information</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the person who is involved with the financial account.</description>
    <label>Related Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__Role__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Role__c</fullName>
    <complianceGroup>Integrity_Trusted</complianceGroup>
    <description>Role that describes how the organizational entity or person is involved with the financial account.</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Additional Owner</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Advisor</fullName>
            </value>
            <value>
                <fullName>Annuitant</fullName>
            </value>
            <value>
                <fullName>Appoint / Remove Authority</fullName>
            </value>
            <value>
                <fullName>Authorized Agent</fullName>
            </value>
            <value>
                <fullName>Authorized Agent / Beneficial Owner</fullName>
            </value>
            <value>
                <fullName>Authorized Individual</fullName>
            </value>
            <value>
                <fullName>Authorized Signer</fullName>
            </value>
            <value>
                <fullName>Beneficial Owner</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
            <value>
                <fullName>Business Manager</fullName>
            </value>
            <value>
                <fullName>Committee Member</fullName>
            </value>
            <value>
                <fullName>Conservator</fullName>
            </value>
            <value>
                <fullName>Control Person</fullName>
            </value>
            <value>
                <fullName>Corporation</fullName>
            </value>
            <value>
                <fullName>Cosigner</fullName>
            </value>
            <value>
                <fullName>Custodian</fullName>
            </value>
            <value>
                <fullName>Deceased Grantor</fullName>
            </value>
            <value>
                <fullName>Decedent</fullName>
            </value>
            <value>
                <fullName>Discretionary</fullName>
            </value>
            <value>
                <fullName>Foundation</fullName>
            </value>
            <value>
                <fullName>Full Authority</fullName>
            </value>
            <value>
                <fullName>Grantor</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Insured</fullName>
            </value>
            <value>
                <fullName>Interested Party</fullName>
            </value>
            <value>
                <fullName>Joint Owner</fullName>
            </value>
            <value>
                <fullName>Minor Primary Owner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__ReciprocalRole__c/FinServ__ReciprocalRole__c.object-meta.xml
<CustomObject>
    <description>Represents the other entity’s corresponding role in a one-to-one relationship between entities.</description>
    <label>Reciprocal Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reciprocal Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__ReciprocalRole__c/fields/OCV_Role__c.field-meta.xml
<CustomField>
    <fullName>OCV_Role__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>OCV Role</description>
    <externalId>true</externalId>
    <label>OCV Role</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FarOwnersRemovalServiceTest.cls
/**
 *
 * @author Tan Phan
 * @since 09/2023
 * @description Contains unit-tests for {@link FarOwnersRemovalService}
 */
@IsTest
private class FarOwnersRemovalServiceTest {
  static Faker faker = new Faker('AU');

  @TestSetup
  static void makeData() {
    System.runAs(CCRMTestDataFactory.getAdminUser()) {
      CCRMTestDataFactory.createPersonAccount();
      CCRMTestDataFactory.createBusinessAccount();
      CCRMTestDataFactory.createSystemCustomer();
    }
  }

  @IsTest
  static void testValidInput() {
    Account customer = [
      SELECT Id, External_Id__c
      FROM Account
      WHERE Name = 'Test Pty Ltd'
    ];
    RestContext.request = new RestRequest();
    RestContext.response = new RestResponse();

    RestContext.request.requestBody = Blob.valueOf(
      JSON.serialize(
        new Map<String, String>{ 'victimId' => customer.External_Id__c }
      )
    );

    Test.startTest();
    System.runAs(CCRMTestDataFactory.getCCRMIntegrationUser()) {
      FarOwnersRemovalService.doPost();
    }
    Test.stopTest();

    Assert.areEqual(
      200,
      RestContext.response.statusCode,
      'Request should success with status code 200'
    );
  }

  @IsTest
  static void testUnexpectedError() {
    RestContext.request = new RestRequest();
    RestContext.response = new RestResponse();

    Test.startTest();
    FarOwnersRemovalService.doPost();
    Test.stopTest();

    Assert.areEqual(
      500,
      RestContext.response.statusCode,
      'Request should fail with status code 500'
    );
  }

  @IsTest
  static void testInvalidInput() {
    RestContext.request = new RestRequest();
    RestContext.response = new RestResponse();

    RestContext.request.requestBody = Blob.valueOf('{}');

    Test.startTest();
    FarOwnersRemovalService.doPost();
    Test.stopTest();

    Assert.areEqual(
      400,
      RestContext.response.statusCode,
      'Request should fail with status code 400'
    );
  }

  @IsTest
  static void testFarAdditionOwnersRemoval() {
    FinServ__FinancialAccountRole__c newFar;
    Account customer = [SELECT Id FROM Account WHERE Name = 'Test Pty Ltd'];

    System.runAs(CCRMTestDataFactory.getAdminUser()) {
      //GIVEN a Financial Account initially created without Primary Owner
      FinServ__FinancialAccount__c fa = new FinServ__FinancialAccount__c();
      insert fa;

      //WHEN a new FAR with role Primary Owner is created for the above FA
      newFar = new FinServ__FinancialAccountRole__c(
        RecordTypeId = CCRMConstants.FAR_CONTACT_RT_ID,
        FinServ__FinancialAccount__c = fa.Id,
        FinServ__RelatedAccount__c = customer.Id,
        FinServ__Role__c = 'Additional Owner',
        External_Id__c = faker.randomString(10)
      );
      insert newFar;
    }

    Test.startTest();
    System.runAs(CCRMTestDataFactory.getCCRMIntegrationUser()) {
      FarOwnersRemovalService.removeAdditionalOwnerFarsFromAccounts(
        new List<Account>{ customer }
      );
    }
    Test.stopTest();

    Assert.areEqual(
      0,
      [
        SELECT COUNT()
        FROM FinServ__FinancialAccountRole__c
        WHERE Id = :newFar.Id
      ],
      'Additional Owner FAR related to the provided customer should be deleted'
    );
  }

  @IsTest
  static void testRemoveContactDataFromAccounts() {
    Account customer = [SELECT Id FROM Account WHERE Name = 'Test Pty Ltd'];

    System.runAs(CCRMTestDataFactory.getAdminUser()) {
      insert new List<SObject>{
        new ContactPointAddress(
          ParentId = customer.Id,
          Name = 'Primary Mailing'
        ),
        new ContactPointEmail(
          ParentId = customer.Id,
          EmailAddress = faker.internet.companyEmail()
        ),
        new ContactPointPhone(
          ParentId = customer.Id,
          TelephoneNumber = faker.person.phone()
        )
      };
    }

    Test.startTest();
    System.runAs(CCRMTestDataFactory.getCCRMIntegrationUser()) {
      FarOwnersRemovalService.removeContactDataFromAccounts(
        new List<Account>{ customer }
      );
    }
    Test.stopTest();

    Assert.areEqual(
      0,
      [SELECT COUNT() FROM ContactPointAddress WHERE ParentId = :customer.Id],
      'ContactPointAddress related to the provided customer should be deleted'
    );
    Assert.areEqual(
      0,
      [SELECT COUNT() FROM ContactPointEmail WHERE ParentId = :customer.Id],
      'ContactPointAddress related to the provided customer should be deleted'
    );
    Assert.areEqual(
      0,
      [SELECT COUNT() FROM ContactPointPhone WHERE ParentId = :customer.Id],
      'ContactPointAddress related to the provided customer should be deleted'
    );
  }

  @IsTest
  static void testRemoveP2PRelationsFromAccounts() {
    Contact businessContact = [
      SELECT Id
      FROM Contact
      WHERE Account.Name = 'Test Pty Ltd'
    ];
    Account personCustomer = [
      SELECT Id, PersonContactId
      FROM Account
      WHERE IsPersonAccount = TRUE
    ];

    System.runAs(CCRMTestDataFactory.getAdminUser()) {
      String ocvReciprocalRole = faker.randomString(10);
      FinServ__ReciprocalRole__c nonReciprocalRole = CCRMTestDataFactory.createNonReciprocalRole(
        ocvReciprocalRole
      );
      insert new List<SObject>{
        new FinServ__ContactContactRelation__c(
          FinServ__Contact__c = personCustomer.PersonContactId,
          FinServ__RelatedContact__c = businessContact.Id,
          OCV_Role__c = ocvReciprocalRole
        )
      };
    }

    Test.startTest();
    System.runAs(CCRMTestDataFactory.getCCRMIntegrationUser()) {
      FarOwnersRemovalService.removeP2PRelationsFromAccounts(
        new List<Account>{ personCustomer }
      );
    }
    Test.stopTest();

    Assert.areEqual(
      0,
      [
        SELECT COUNT()
        FROM FinServ__ContactContactRelation__c
        WHERE FinServ__Contact__c = :personCustomer.PersonContactId
      ],
      'ContactContactRelation related to the provided customer should be deleted'
    );
  }
}