force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <description>Used for writing updates from OCV Party event messages. It is constructed in Mulesoft.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FinServ__AccountAccountRelation__c/FinServ__AccountAccountRelation__c.object-meta.xml
<CustomObject>
    <description>A relationship between two accounts, such as a household and a business account.</description>
    <label>Account-Account Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Account Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__AccountAccountRelation__c/fields/FinServ__Account__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Account__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>RelatedFromAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__AccountAccountRelation__c/fields/FinServ__Active__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Active__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FinServ__AccountAccountRelation__c/fields/FinServ__EndDate__c.field-meta.xml
<CustomField>
    <fullName>FinServ__EndDate__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FinServ__AccountAccountRelation__c/fields/FinServ__RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelatedAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>RelatedToAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__AccountAccountRelation__c/fields/FinServ__Role__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Role__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non-Sensitive_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FinServ__ReciprocalRole__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Account Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FinServ__ReciprocalRole__c</referenceTo>
    <relationshipName>AccountReciprocalRole</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__AccountAccountRelation__c/fields/OCV_Role__c.field-meta.xml
<CustomField>
    <fullName>OCV_Role__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non-Sensitive Personal Information;Source - OCV</complianceGroup>
    <description>OCV Role</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>OCV Role</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__AccountAccountRelation__c/fields/System_Individual_Relationship__c.field-meta.xml
<CustomField>
    <fullName>System_Individual_Relationship__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>To be set as True when Individual Customer relationship is involved.</description>
    <label>System Individual Relationship</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FinServ__ReciprocalRole__c/FinServ__ReciprocalRole__c.object-meta.xml
<CustomObject>
    <description>Represents the other entity’s corresponding role in a one-to-one relationship between entities.</description>
    <label>Reciprocal Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reciprocal Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__ReciprocalRole__c/fields/FinServ__InverseRelationship__c.field-meta.xml
<CustomField>
    <fullName>FinServ__InverseRelationship__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Uniquely identifies the relationship between Role and InverseRole__c so that it can be referenced by a trigger that creates the inverse relationship record.</description>
    <label>InverseRelationship</label>
    <referenceTo>FinServ__ReciprocalRole__c</referenceTo>
    <relationshipLabel>Inverse Relationship</relationshipLabel>
    <relationshipName>InverseRelationship</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__ReciprocalRole__c/fields/OCV_Role__c.field-meta.xml
<CustomField>
    <fullName>OCV_Role__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>OCV Role</description>
    <externalId>true</externalId>
    <label>OCV Role</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ccrm/CCRMAccountAccountRelationActions.cls
/**
 * @author Boobalakrishnan Duraisamy
 * @since  05/2023
 * @group CCRM (Commercial CRM)
 * @description to handle all commercial CRM Account to Account actions
 * @runTests CCRMAccountAccountRelationActionsTest
 */
public with sharing class CCRMAccountAccountRelationActions {
  private static final String EXTERNAL_ID_TEMPLATE = '{0}_{1}_{2}';
  private static Map<Id, FinServ__ReciprocalRole__c> mapRoles;
  private static Map<String, FinServ__ReciprocalRole__c> mapOcvRoles;

  static {
    List<FinServ__ReciprocalRole__c> roles = [
      SELECT Id, Name, FinServ__InverseRelationship__c, OCV_Role__c
      FROM FinServ__ReciprocalRole__c
      WHERE
        OCV_Role__c != NULL
        AND RecordTypeId = :CCRMConstants.RECIPROCAL_ACCOUNT_ROLE_RT_ID
      WITH SECURITY_ENFORCED
    ];
    mapRoles = new Map<Id, FinServ__ReciprocalRole__c>(roles);
    mapOcvRoles = new Map<String, FinServ__ReciprocalRole__c>();
    for (FinServ__ReciprocalRole__c reciprocalRole : roles) {
      mapOcvRoles.put(reciprocalRole.OCV_Role__c, reciprocalRole);
    }
  }

  /**
   * @description set External Id of FinServ__AccountAccountRelation__c object based on OCV Role ID from Finserv__ReciprocalRole__c
   * @name setExternalId
   * @param records The Account to accounts records passed from beforeInsert()
   */
  public static void setExternalId(
    List<FinServ__AccountAccountRelation__c> records
  ) {
    Map<Id, Account> mapAccounts = getMapAccounts(records);
    for (FinServ__AccountAccountRelation__c record : records) {
      populateRoleId(record);
      populateExternalId(record, mapAccounts);
      checkPersonAccountInvolement(record, mapAccounts);
    }
  }

  /**
   * @description get related account records
   * @name getMapAccountIdToExtId
   * @param records The Account to accounts records passed from beforeInsert()
   * @return Map<Id, Account>
   */
  private static Map<Id, Account> getMapAccounts(
    List<FinServ__AccountAccountRelation__c> records
  ) {
    Set<Id> accountIds = new Set<Id>();
    for (FinServ__AccountAccountRelation__c record : records) {
      accountIds.add(record.FinServ__Account__c);
      accountIds.add(record.FinServ__RelatedAccount__c);
    }
    return new Map<Id, Account>(
      [
        SELECT Id, External_Id__c, IsPersonAccount
        FROM Account
        WHERE Id IN :accountIds
        WITH USER_MODE
      ]
    );
  }

  /**
   * @description check and update System_Individual_Relationship__c
   * @name checkPersonAccountInvolement
   * @param record FinServ__AccountAccountRelation__c record from trigger
   * @param mapAccounts map of account related to FinServ__AccountAccountRelation__c
   */
  private static void checkPersonAccountInvolement(
    FinServ__AccountAccountRelation__c record,
    Map<Id, Account> mapAccounts
  ) {
    record.System_Individual_Relationship__c =
      mapAccounts.get(record.FinServ__Account__c)?.IsPersonAccount == true ||
      mapAccounts.get(record.FinServ__RelatedAccount__c)?.IsPersonAccount ==
      true;
  }

  /**
   * @description populates FinServ__Role__c or OCV_Role__c based on FinServ__ReciprocalRole__c table
   * @name populateRoleId
   * @param record FinServ__AccountAccountRelation__c record from trigger
   */
  private static void populateRoleId(
    FinServ__AccountAccountRelation__c record
  ) {
    if (record.FinServ__Role__c == null) {
      record.FinServ__Role__c = mapOcvRoles.get(record.OCV_Role__c)?.Id;
    } else {
      record.OCV_Role__c = mapRoles.get(record.FinServ__Role__c)?.OCV_Role__c;
    }
    if (!mapOcvRoles.containsKey(record.OCV_Role__c)) {
      record.addError(CCRMConstants.INVALID_OCV_ROLE_ERROR_MESSAGE);
    }
  }

  /**
   * @description populates External_Id__c when salesforce automatically creates a FinServ__AccountAccountRelation__c record
   * @name populateExternalId
   * @param record FinServ__AccountAccountRelation__c record from trigger
   * @param mapAccounts map of account related to FinServ__AccountAccountRelation__c
   */
  private static void populateExternalId(
    FinServ__AccountAccountRelation__c record,
    Map<Id, Account> mapAccounts
  ) {
    if (
      record.External_Id__c == null ||
      record.FinServ__InverseRelationship__c == null
    ) {
      return;
    }
    String party1 = mapAccounts.get(record.FinServ__Account__c).External_Id__c;
    String party2 = mapAccounts.get(record.FinServ__RelatedAccount__c)
      .External_Id__c;
    String role = mapRoles.get(record.FinServ__Role__c).Name.replace(' ', '');
    record.External_Id__c = String.format(
      EXTERNAL_ID_TEMPLATE,
      new List<String>{ party1, party2, role }
    );
  }

  /**
   * @description check if a relationship is enddated and set to inactive, then delete it and the inverse relationship
   * @name checkRelationshipStatus
   * @param records records from the trigger
   */
  public static void checkRelationshipStatus(
    List<FinServ__AccountAccountRelation__c> records
  ) {
    Set<Id> recordIdsToDelete = new Set<Id>();
    for (FinServ__AccountAccountRelation__c record : records) {
      if (
        !String.isBlank(record.External_Id__c) &&
        record.FinServ__EndDate__c != null &&
        !record.FinServ__Active__c
      ) {
        recordIdsToDelete.add(record.Id);
        if (record.FinServ__InverseRelationship__c != null) {
          recordIdsToDelete.add(record.FinServ__InverseRelationship__c);
        }
      }
    }
    if (!recordIdsToDelete.isEmpty()) {
      deleteRelationshipsAsync(recordIdsToDelete);
    }
  }

  /**
   * @description delete the provided relationships
   * @name deleteRelationships
   * @param recordIds list of relationship record ID
   */
  @future
  private static void deleteRelationshipsAsync(Set<Id> recordIds) {
    try {
      DMLUtilHelper.processDeleteResults(
        Database.delete(new List<Id>(recordIds), false, AccessLevel.USER_MODE)
      );
    } catch (Exception e) {
      DMLUtilHelper.logException(e);
    }
  }
}