force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <description>Used for writing updates from OCV Party event messages. It is constructed in Mulesoft.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_Event_Version__c.field-meta.xml
<CustomField>
    <fullName>OCV_Event_Version__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Refers to the event version number of the latest information sent from OCV to update Salesforce</description>
    <label>OCV Event Version</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non-Sensitive_Personal_Information;Source_OCV</complianceGroup>
    <description>System field to identify sync status for integration</description>
    <label>Sync Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broker Org</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BrokerSettings__c/BrokerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is a config custom setting for Broker Domain</description>
    <label>BrokerSettings</label>
</CustomObject>

force-app/main/default/objects/BrokerSettings__c/fields/BypassBrokerEvent__c.field-meta.xml
<CustomField>
    <fullName>BypassBrokerEvent__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Control the Broker contact publish event using this custom setting.</description>
    <label>BypassBrokerEvent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Broker_Customer_Profile__c.field-meta.xml
<CustomField>
    <fullName>Broker_Customer_Profile__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Displays the Person account details</description>
    <label>Broker&apos;s Customer Profile</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PersonAccount</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>This field will store External ID generated by concatenating Account External ID + Financial Account Key + Financial Account Role + Start date</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/OCV_Event_Version__c.field-meta.xml
<CustomField>
    <fullName>OCV_Event_Version__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Contact event version received from OCV</description>
    <label>OCV Event Version</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non-Sensitive_Personal_Information;Source_OCV</complianceGroup>
    <description>System field to identify sync status for integration</description>
    <label>Sync Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broker Org</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Duplicate - Email</fullName>
            </value>
            <value>
                <fullName>Duplicate - OCV Id</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Broker.recordType-meta.xml
<RecordType>
    <fullName>Broker</fullName>
    <active>true</active>
    <description>Display Broker details</description>
    <label>Broker</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Staff.recordType-meta.xml
<RecordType>
    <fullName>Staff</fullName>
    <active>true</active>
    <description>Display Staff details</description>
    <label>Staff</label>
</RecordType>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/classes/RetailBrokerContactTriggerHandlerTest.cls
/**
 * @author Zhiren Jason Guan
 * @since  20/02/2024
 * @description Test class for RetailBrokerContactTriggerHandler
 */
@IsTest
private class RetailBrokerContactTriggerHandlerTest {
  private static final Id RECORD_TYPE_ID_BROKER = SObjectType.Contact.getRecordTypeInfosByDeveloperName()
    .get('Broker')
    .recordTypeId;
  private static final Id RECORD_TYPE_ID_STAFF = SObjectType.Contact.getRecordTypeInfosByDeveloperName()
    .get('Staff')
    .recordTypeId;
  static Lib_MockProvider brokerSettingsMock = Lib_MockProvider.forType(
    CustomSettingsRepository.class
  );

  static List<Contact> createTestContactList(Id recordTypeId) {
    List<Contact> contacts = new List<Contact>();
    for (Integer counter = 0; counter < 10; counter++) {
      Contact brokerContact = new Contact();
      brokerContact.FirstName = 'TestFirst' + counter;
      brokerContact.LastName = 'TestLast' + counter;
      brokerContact.External_Id__c = 'broker-12345' + counter;
      brokerContact.RecordTypeId = recordTypeId;
      contacts.add(brokerContact);
    }
    return contacts;
  }

  static List<Contact> updateContactList(
    List<Contact> contactList,
    Decimal version
  ) {
    for (Integer counter = 0; counter < contactList.size(); counter++) {
      contactList[counter].OCV_Event_Version__c = version;
    }
    return contactList;
  }

  @IsTest
  static void testFilterRetailBrokerContactPositive() {
    // Prepare broker contact
    Contact brokerContact = new Contact();
    brokerContact.Id = Lib_FakeIdGenerator.getMockId(Contact.SObjectType);
    brokerContact.RecordTypeId = RECORD_TYPE_ID_BROKER;

    Test.startTest();
    RetailBrokerContactTriggerHandler handler = new RetailBrokerContactTriggerHandler();
    Boolean isBrokerContact = handler.isValidRecord(brokerContact);
    Test.stopTest();

    Assert.areEqual(
      true,
      isBrokerContact,
      'Should return true for broker contact'
    );
  }

  @IsTest
  static void testFilterRetailBrokerContactNegative() {
    // Prepare staff contact
    Contact staffContact = new Contact();
    staffContact.Id = Lib_FakeIdGenerator.getMockId(Contact.SObjectType);
    staffContact.RecordTypeId = RECORD_TYPE_ID_STAFF;

    Test.startTest();
    RetailBrokerContactTriggerHandler handler = new RetailBrokerContactTriggerHandler();
    Boolean isBrokerContact = handler.isValidRecord(staffContact);
    Test.stopTest();

    Assert.areEqual(
      false,
      isBrokerContact,
      'Should return false for staff contact'
    );
  }

  @isTest
  static void testUpdateTriggerBypassOn() {
    Account personAccount = TestDataFactory.createPersonAccount(
      'pa-123456',
      true
    );
    List<Contact> testContacts = createTestContactList(RECORD_TYPE_ID_BROKER);
    for (Contact contact : testContacts) {
      contact.Broker_Customer_Profile__c = personAccount.Id;
    }
    insert testContacts;
    Map<Id, Contact> testContactMap = new Map<Id, Contact>(testContacts);
    Set<Id> testContactIds = testContactMap.keySet();
    Test.startTest();
    BrokerSettings__c mockSettings = new BrokerSettings__c();
    mockSettings.BypassBrokerEvent__c = true;
    brokerSettingsMock.mock('brokerSettings', mockSettings);
    updateContactList(testContacts, 1);
    update testContacts;
    List<Contact> resultContacts = [
      SELECT Id, Sync_Status__c
      FROM Contact
      WHERE Id IN :testContactIds
    ];
    Test.stopTest();
    Assert.areEqual(
      RetailBrokerContactActions.SYNC_STATUS_BROKER_ORG,
      resultContacts[0].Sync_Status__c,
      'Sync status should be set to Broker Org'
    );
  }

  @IsTest
  static void testUpdateTriggerBypassOff() {
    Account personAccount = TestDataFactory.createPersonAccount(
      'pa-123456',
      true
    );
    List<Contact> testContacts = createTestContactList(RECORD_TYPE_ID_BROKER);
    for (Contact contact : testContacts) {
      contact.Broker_Customer_Profile__c = personAccount.Id;
    }
    insert testContacts;
    Map<Id, Contact> testContactMap = new Map<Id, Contact>(testContacts);
    Set<Id> testContactIds = testContactMap.keySet();
    Test.startTest();
    BrokerSettings__c mockSettings = new BrokerSettings__c();
    mockSettings.BypassBrokerEvent__c = false;
    brokerSettingsMock.mock('brokerSettings', mockSettings);
    updateContactList(testContacts, 1);
    update testContacts;
    updateContactList(testContacts, 2);
    update testContacts;
    List<Contact> resultContacts = [
      SELECT Id, Sync_Status__c
      FROM Contact
      WHERE Id IN :testContactIds
    ];
    Test.stopTest();
    Assert.areEqual(
      RetailBrokerContactActions.SYNC_STATUS_BROKER_ORG,
      resultContacts[0].Sync_Status__c,
      'Sync status should remain as Broker Org'
    );
  }
}