force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <description>Used for writing updates from OCV Party event messages. It is constructed in Mulesoft.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_Event_Version__c.field-meta.xml
<CustomField>
    <fullName>OCV_Event_Version__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Refers to the event version number of the latest information sent from OCV to update Salesforce</description>
    <label>OCV Event Version</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non-Sensitive_Personal_Information;Source_OCV</complianceGroup>
    <description>System field to identify sync status for integration</description>
    <label>Sync Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broker Org</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BrokerSettings__c/BrokerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is a config custom setting for Broker Domain</description>
    <label>BrokerSettings</label>
</CustomObject>

force-app/main/default/objects/BrokerSettings__c/fields/BypassCustomerSyncEvents__c.field-meta.xml
<CustomField>
    <fullName>BypassCustomerSyncEvents__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Control the Customer publish event using this custom setting.</description>
    <label>BypassCustomerSyncEvents</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cloud_Event__e/Cloud_Event__e.object-meta.xml
<CustomObject>
    <description>General cloud event</description>
    <label>Cloud Event</label>
    <pluralLabel>Cloud Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/classes/CustomerEventActionsTest.cls
/**
 * @description       : Test Class for CustomerEventActions
 * @author            : Madhuri Edke | Salesforce
 * @last modified on  : 10-08-2024
 * @last modified by  : Madhuri Edke | Salesforce
 **/
@isTest
public with sharing class CustomerEventActionsTest {
  private static final Id PERSONACC_RECORDTYPEID = QueryRT.of(
      Account.SObjectType
    )
    .getId('PersonAccount');

  /*
   * @description unit test for filterOCVVersionUpdate
   */
  @isTest
  static void filterOCVVersionUpdateTest() {
    List<Account> accList = createCustomerAccount(1);
    Map<Id, Account> oldMap = convertRecordsToOldMap(accList);
    Test.startTest();
    List<Account> result = CustomerEventActions.filterOCVVersionUpdate(
      accList,
      oldMap
    );
    Test.stopTest();
    Assert.areEqual(1, result.size(), 'Expected One Valid OCV Version Account');
    Assert.areEqual(
      1,
      result[0].OCV_Event_Version__c,
      'Expected version of OCV is 1'
    );
  }

  /*
   * @description unit test for generateCustomerCEModel
   */
  @isTest
  static void generateCustomerCEModelTest() {
    List<Account> accList = createCustomerAccount(2);
    Test.startTest();
    Map<Id, List<BrokerCloudEventModel.MasterNode>> result = CustomerEventActions.generateCustomerCEModel(
      accList
    );
    Test.stopTest();
    Assert.areEqual(2, result.size(), 'Publish event failed');
  }

  /*
   * @description unit test for publishEventForCustomers
   */
  @isTest
  static void publishEventForCustomersTest() {
    CustomerEventActions.mockBrokerSettings = new BrokerSettings__c(
      BypassCustomerSyncEvents__c = false
    );
    List<Account> accList = createCustomerAccount(2);
    Map<Id, Account> oldMap = convertRecordsToOldMap(accList);
    Test.startTest();
    List<Cloud_Event__e> cloudEvents = CustomerEventActions.publishEventForCustomers(
      accList,
      oldMap,
      'update'
    );
    Test.stopTest();
    Assert.areEqual(
      2,
      cloudEvents.size(),
      '2 Cloud Event Model instances should be created'
    );
  }

  /*
   * @description unit test for generateCloudEventModel
   */
  @isTest
  static void generateCloudEventModelTest() {
    List<Account> accList = createCustomerAccount(1);
    Map<Id, List<BrokerCloudEventModel.MasterNode>> masterNodes = CustomerEventActions.generateCustomerCEModel(
      accList
    );
    Test.startTest();
    List<BrokerCloudEventModel> result = CustomerEventActions.generateCloudEventModel(
      accList,
      masterNodes,
      'update'
    );
    Test.stopTest();
    Assert.areEqual(
      'Broker/' + accList[0].External_Id__c,
      result[0].ce_xtargets,
      'The external id should be the same as the customer external id'
    );
  }

  /*
   * @description Test Method to create test Customers
   */
  static List<Account> createCustomerAccount(Integer count) {
    List<Account> accList = new List<Account>();
    for (Integer i = 0; i < count; i++) {
      Account acc = TestDataFactory.createAccount(false);
      acc.External_Id__c = 'Test0001' + i;
      acc.Sync_Status__c = 'Broker Org';
      acc.OCV_Event_Version__c = 1;
      acc.Id = Lib_FakeIdGenerator.getMockId(Account.SObjectType);
      acc.RecordTypeId = PERSONACC_RECORDTYPEID;
      accList.add(acc);
    }
    return accList;
  }

  /*
   * @description Test Method to create Record oldMap
   */
  static Map<Id, Account> convertRecordsToOldMap(List<Account> accList) {
    List<Account> oldAccList = accList.deepClone(true);
    for (Account acc : oldAccList) {
      acc.OCV_Event_Version__c = 0;
    }
    return new Map<Id, Account>(oldAccList);
  }
}