force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <description>Used for writing updates from OCV Party event messages. It is constructed in Mulesoft.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>This field will store External ID generated by concatenating Account External ID + Financial Account Key + Financial Account Role + Start date</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Financial_Account_Role_Type_Mapping__mdt/Financial_Account_Role_Type_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Financial Account Role Type Mapping</label>
    <pluralLabel>Financial Account Role Type Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Financial_Account_Role_Type_Mapping__mdt/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Account_Settings__c/Financial_Account_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Financial Account Settings</label>
</CustomObject>

force-app/main/default/objects/Financial_Account_Settings__c/fields/System_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>System_Customer_Id__c</fullName>
    <label>System Customer Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Account_Key__c.field-meta.xml
<CustomField>
    <fullName>Account_Key__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Field to store unique identifier for a Financial Account record received from OCV</description>
    <externalId>true</externalId>
    <label>Account Key</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__PrimaryOwner__c.field-meta.xml
<CustomField>
    <fullName>FinServ__PrimaryOwner__c</fullName>
    <complianceGroup>Integrity - Accurate</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
    <relationshipName>ClientFinancialAccounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Role_Type__c.field-meta.xml
<CustomField>
    <fullName>Role_Type__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal Information;Source_OCV</complianceGroup>
    <description>Primary Owner and Additional Owner Role Type</description>
    <label>RoleType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FinancialAccountRoleType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/FinServ__FinancialAccountRole__c.object-meta.xml
<CustomObject>
    <description>Represents the role occupied by a person or organizational entity that is involved with a financial account, such as a beneficiary or trustee.</description>
    <label>Financial Account Role</label>
    <nameField>
        <displayFormat>FAR-{000000000}</displayFormat>
        <label>Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Source - OCV;Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <description>This field will store External ID generated by concatenating Account External ID + Financial Account Key + Financial Account Role + Start date</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__Active__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Active__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy - Personal Information</complianceGroup>
    <defaultValue>true</defaultValue>
    <description>Indicates whether the organizational entity or person currently occupies this role.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__EndDate__c.field-meta.xml
<CustomField>
    <fullName>FinServ__EndDate__c</fullName>
    <complianceGroup>Integrity_Accurate</complianceGroup>
    <description>End date when the organizational entity or person relinquished this role.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy - Personal Information</complianceGroup>
    <description>Financial account that this role is related to.</description>
    <label>Financial Account</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelatedAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the organizational entity that is involved with the financial account.</description>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__RelatedContact__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelatedContact__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy - Personal Information</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the person who is involved with the financial account.</description>
    <label>Related Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__Role__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Role__c</fullName>
    <complianceGroup>Integrity_Trusted</complianceGroup>
    <description>Role that describes how the organizational entity or person is involved with the financial account.</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Additional Owner</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Advisor</fullName>
            </value>
            <value>
                <fullName>Annuitant</fullName>
            </value>
            <value>
                <fullName>Appoint / Remove Authority</fullName>
            </value>
            <value>
                <fullName>Authorized Agent</fullName>
            </value>
            <value>
                <fullName>Authorized Agent / Beneficial Owner</fullName>
            </value>
            <value>
                <fullName>Authorized Individual</fullName>
            </value>
            <value>
                <fullName>Authorized Signer</fullName>
            </value>
            <value>
                <fullName>Beneficial Owner</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
            <value>
                <fullName>Business Manager</fullName>
            </value>
            <value>
                <fullName>Committee Member</fullName>
            </value>
            <value>
                <fullName>Conservator</fullName>
            </value>
            <value>
                <fullName>Control Person</fullName>
            </value>
            <value>
                <fullName>Corporation</fullName>
            </value>
            <value>
                <fullName>Cosigner</fullName>
            </value>
            <value>
                <fullName>Custodian</fullName>
            </value>
            <value>
                <fullName>Deceased Grantor</fullName>
            </value>
            <value>
                <fullName>Decedent</fullName>
            </value>
            <value>
                <fullName>Discretionary</fullName>
            </value>
            <value>
                <fullName>Foundation</fullName>
            </value>
            <value>
                <fullName>Full Authority</fullName>
            </value>
            <value>
                <fullName>Grantor</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Insured</fullName>
            </value>
            <value>
                <fullName>Interested Party</fullName>
            </value>
            <value>
                <fullName>Joint Owner</fullName>
            </value>
            <value>
                <fullName>Minor Primary Owner</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Primary Owner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/Role_Type__c.field-meta.xml
<CustomField>
    <fullName>Role_Type__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Personal Information;Source - OCV</complianceGroup>
    <description>Primary Owner and Additional Owner Role Type</description>
    <label>Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FinancialAccountRoleType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ccrm/CCRMFinancialAccountRoleActions.cls
/**
 *
 * @author Tan Phan
 * @since 05/2023
 * @description Handle actions on trigger events of FinServ__FinancialAccountRole__c object
 * @runTests CCRMFinancialAccountRoleActionsTest
 */
public with sharing class CCRMFinancialAccountRoleActions {
  private static final String FAR_ROLE_PRIMARYOWNER = 'Primary Owner';
  private static final String FAR_ROLE_OTHER = 'Other';

  public static final Set<SObjectField> FIELD_SET = new Set<SObjectField>{
    FinServ__FinancialAccountRole__c.FinServ__RelatedAccount__c,
    FinServ__FinancialAccountRole__c.FinServ__FinancialAccount__c
  };

  private static final FinancialAccountRoleRepository FAR_REPOSITORY = (FinancialAccountRoleRepository) Lib_InstanceProvider.forType(
    FinancialAccountRoleRepository.class
  );

  private static final DmlRepository DML_REPOSITORY = (DmlRepository) Lib_InstanceProvider.forType(
    DmlRepository.class
  );

  private static final FinancialAccountRepository FINANCIAL_ACCOUNT_REPOSITORY = (FinancialAccountRepository) Lib_InstanceProvider.forType(
    FinancialAccountRepository.class
  );

  /**
   * @description Set FAR record type to System or Contact based on External Id and Related Customer
   * @name setRecordType
   * @param records Financial account role records from the trigger.
   */
  public static void setRecordType(
    List<FinServ__FinancialAccountRole__c> records
  ) {
    Financial_Account_Settings__c faSettings = Financial_Account_Settings__c.getOrgDefaults();
    List<FinServ__FinancialAccountRole__c> recordsToCheck = new List<FinServ__FinancialAccountRole__c>();
    Set<Id> accountIds = new Set<Id>();

    for (FinServ__FinancialAccountRole__c record : records) {
      if (
        record.External_Id__c == null ||
        record.FinServ__RelatedAccount__c == faSettings.System_Customer_Id__c ||
        !record.FinServ__Active__c
      ) {
        record.RecordTypeId = CCRMConstants.FAR_SYSTEM_RT_ID;
        record.External_Id__c = null;
      } else {
        recordsToCheck.add(record);
        accountIds.add(record.FinServ__RelatedAccount__c);
      }
    }
    if (recordsToCheck.isEmpty()) {
      return;
    }

    Map<Id, Account> mapAccounts = new Map<Id, Account>(
      [SELECT IsPersonAccount FROM Account WHERE Id IN :accountIds]
    );

    for (FinServ__FinancialAccountRole__c record : recordsToCheck) {
      record.RecordTypeId = mapAccounts.get(record.FinServ__RelatedAccount__c)
          ?.IsPersonAccount == true
        ? CCRMConstants.FAR_CONTACT_RT_ID
        : CCRMConstants.FAR_ACCOUNT_RT_ID;
    }
  }

  /**
   * @description Populate Finserv__Role__c by Role_Type__c
   * @name mapRoleTypeToRole
   * @param records Financial account role records from the trigger.
   */
  public static void mapRoleTypeToRole(
    List<FinServ__FinancialAccountRole__c> records
  ) {
    Map<String, Financial_Account_Role_Type_Mapping__mdt> farRoleTypeMapping = Financial_Account_Role_Type_Mapping__mdt.getAll();

    for (FinServ__FinancialAccountRole__c record : records) {
      if (String.isBlank(record.FinServ__Role__c)) {
        record.FinServ__Role__c = farRoleTypeMapping.containsKey(
            record.Role_Type__c
          )
          ? farRoleTypeMapping.get(record.Role_Type__c).Role__c
          : FAR_ROLE_OTHER;
      }
    }
  }

  /**
   * @description When a "Primary Owner" FAR record is created, switch the primary owner of the parent FA record to the new account
   * @param records Financial account role records from the trigger.
   */
  public static void updateFinancialAccountOwner(
    List<FinServ__FinancialAccountRole__c> records
  ) {
    Set<Id> relatedFinancialAccountsIDs = ListUtil.getIds(
      records,
      FinServ__FinancialAccountRole__c.FinServ__FinancialAccount__c
    );
    Map<Id, FinServ__FinancialAccount__c> financialAccountsMap = FINANCIAL_ACCOUNT_REPOSITORY.getFinancialAccountsWithPrimaryOwner(
      relatedFinancialAccountsIDs
    );
    List<FinServ__FinancialAccountRole__c> filteredRecords = ListUtil.filter(
        records
      )
      .isNull(FinServ__FinancialAccountRole__c.FinServ__EndDate__c)
      .equals(
        FinServ__FinancialAccountRole__c.FinServ__Role__c,
        FAR_ROLE_PRIMARYOWNER
      )
      .toList();
    List<FinServ__FinancialAccount__c> finAccountsToUpdate = getFinancialAccountsToUpdate(
      filteredRecords,
      financialAccountsMap
    );
    DML_REPOSITORY.doUpdate(finAccountsToUpdate);
  }

  /**
   * @description get the financial accounts to be updated with new Primary Owner
   * @param records Financial account role records from the trigger.
   * @param financialAccountsMap Map of related Financial account records
   * @return List<FinServ__FinancialAccount__c> The Financial account records that needs to be updated.
   */
  @TestVisible
  private static List<FinServ__FinancialAccount__c> getFinancialAccountsToUpdate(
    List<FinServ__FinancialAccountRole__c> records,
    Map<Id, FinServ__FinancialAccount__c> financialAccountsMap
  ) {
    List<FinServ__FinancialAccount__c> finAccountsToUpdate = new List<FinServ__FinancialAccount__c>();
    for (FinServ__FinancialAccountRole__c record : records) {
      FinServ__FinancialAccount__c finAccount = financialAccountsMap.get(
        record.FinServ__FinancialAccount__c
      );
      if (
        finAccount == null ||
        record.FinServ__RelatedAccount__c == finAccount.Finserv__PrimaryOwner__c
      ) {
        continue;
      }
      finAccount.Finserv__PrimaryOwner__c = record.FinServ__RelatedAccount__c;
      finAccountsToUpdate.add(finAccount);
    }
    return finAccountsToUpdate;
  }

  /**
   * @description Deactive FAR record when an end-date is set
   * @name deactivateEndDatedRecords
   * @param records Financial account role records from the trigger.
   * @param oldMap Map of old Financial account role records from the trigger.
   */
  public static void deactivateEndDatedRecords(
    List<FinServ__FinancialAccountRole__c> records,
    Map<Id, FinServ__FinancialAccountRole__c> oldMap
  ) {
    List<FinServ__FinancialAccountRole__c> recordsToRevertOverridenEndDate = new List<FinServ__FinancialAccountRole__c>();
    for (FinServ__FinancialAccountRole__c record : records) {
      FinServ__FinancialAccountRole__c oldRecord = oldMap.get(record.Id);
      if (
        (record.FinServ__Active__c || oldRecord.FinServ__Active__c) &&
        record.FinServ__EndDate__c != null &&
        oldRecord.FinServ__EndDate__c == null
      ) {
        record.FinServ__Active__c = false;
        recordsToRevertOverridenEndDate.add(
          new FinServ__FinancialAccountRole__c(
            Id = record.Id,
            FinServ__EndDate__c = record.FinServ__EndDate__c
          )
        );
      }
    }

    if (!recordsToRevertOverridenEndDate.isEmpty()) {
      System.enqueueJob(
        new RevertOverridenEndDateQueueable(recordsToRevertOverridenEndDate)
      );
    }
  }

  /**
   * @description Deactive existing duplicate FAR record
   * @name deactivateDuplicateRecords
   * @param records Financial account role records from the trigger.
   * @param oldMap Map of old Financial account role records from the trigger.
   */
  public static void deactivateDuplicateRecords(
    List<FinServ__FinancialAccountRole__c> records,
    Map<Id, FinServ__FinancialAccountRole__c> oldMap
  ) {
    List<FinServ__FinancialAccountRole__c> filterActiveRecords = new List<FinServ__FinancialAccountRole__c>();

    filterActiveRecords = ListUtil.filter(records, oldMap)
      .changedTo(FinServ__FinancialAccountRole__c.FinServ__Active__c, true)
      .toList();

    Set<Id> recordIds = ListUtil.getIds(
      filterActiveRecords,
      FinServ__FinancialAccountRole__c.Id
    );
    Set<Id> relatedAccountIds = ListUtil.getIds(
      filterActiveRecords,
      FinServ__FinancialAccountRole__c.FinServ__RelatedAccount__c
    );
    Set<Id> relatedFinancialAccountIds = ListUtil.getIds(
      filterActiveRecords,
      FinServ__FinancialAccountRole__c.FinServ__FinancialAccount__c
    );
    List<FinServ__FinancialAccountRole__c> existingActiveRecords = FAR_REPOSITORY.getActiveFinancialAccountRoleRecords(
      relatedAccountIds,
      relatedFinancialAccountIds
    );
    Set<String> relatedAccountIdFinancialIdUniqueKey = getUniqueKeySet(
      recordIds,
      existingActiveRecords
    );
    List<FinServ__FinancialAccountRole__c> existingRecordsToDeactivate = getRecordsToDeactivateList(
      recordIds,
      relatedAccountIdFinancialIdUniqueKey,
      existingActiveRecords
    );
    DML_REPOSITORY.doUpdate(existingRecordsToDeactivate);
  }
  /**
   * @description Generate and return unique key using CustomerId and AccountKey
   * @name getUniqueKeySet
   * @param recordIds Financial account role record Ids.
   * @param activeRecords Financial account role records
   * @return Set<String>
   */
  private static Set<String> getUniqueKeySet(
    Set<Id> recordIds,
    List<FinServ__FinancialAccountRole__c> activeRecords
  ) {
    Set<String> relatedAccountIdFinancialIdUniqueKey = new Set<String>();
    for (FinServ__FinancialAccountRole__c record : activeRecords) {
      if (recordIds.contains(record.Id)) {
        String uniqueKey = generateCustomerIdAccountKeyUniqueKey(
          record.FinServ__RelatedAccount__r.External_Id__c,
          record.FinServ__FinancialAccount__r.Account_Key__c
        );
        relatedAccountIdFinancialIdUniqueKey.add(uniqueKey);
      }
    }
    return relatedAccountIdFinancialIdUniqueKey;
  }
  /**
   * @description Deactive existing duplicate FAR record
   * @name deactivateDuplicateRecords
   * @param recordIds Financial account role record Ids.
   * @param relatedAccountIdFinancialIdUniqueKey Set of Unique keys.
   * @param existingActiveRecords Existing Active Financial account role records
   * @return List<FinServ__FinancialAccountRole__c>
   */
  private static List<FinServ__FinancialAccountRole__c> getRecordsToDeactivateList(
    Set<Id> recordIds,
    Set<String> relatedAccountIdFinancialIdUniqueKey,
    List<FinServ__FinancialAccountRole__c> existingActiveRecords
  ) {
    List<FinServ__FinancialAccountRole__c> existingRecordsToDeactivate = new List<FinServ__FinancialAccountRole__c>();
    for (FinServ__FinancialAccountRole__c record : existingActiveRecords) {
      String tempUniqueKey = generateCustomerIdAccountKeyUniqueKey(
        record.FinServ__RelatedAccount__r.External_Id__c,
        record.FinServ__FinancialAccount__r.Account_Key__c
      );
      if (recordIds.contains(record.Id)) {
        continue;
      }
      if (relatedAccountIdFinancialIdUniqueKey.contains(tempUniqueKey)) {
        existingRecordsToDeactivate.add(
          new FinServ__FinancialAccountRole__c(
            Id = record.Id,
            FinServ__Active__c = false,
            FinServ__EndDate__c = Date.today()
          )
        );
      }
    }
    return existingRecordsToDeactivate;
  }
  /**
   * @description Generate and return unique key using CustomerId and AccountKey
   * @name generateCustomerIdAccountKeyUniqueKey
   * @param customerId  Related Account's External Id from FAR.
   * @param accountKey Financial Account's Account Key value from FAR.
   * @return String
   */
  private static String generateCustomerIdAccountKeyUniqueKey(
    String customerId,
    String accountKey
  ) {
    return customerId + '_' + accountKey;
  }

  /**
   * @description Queueable class to update FAR end-date to original value before FS trigger override it with today's date
   * @name RevertOverridenEndDateQueueable
   */
  private class RevertOverridenEndDateQueueable implements Queueable {
    private List<FinServ__FinancialAccountRole__c> records;

    /**
     * @description constructor
     * @param records list of records to update
     */
    private RevertOverridenEndDateQueueable(
      List<FinServ__FinancialAccountRole__c> records
    ) {
      this.records = records;
    }

    /**
     * @description execute method
     * @param context QueueableContext
     */
    public void execute(QueueableContext context) {
      DMLUtil.updateRecords(this.records, true, true);
    }
  }

  /**
   * @description when a non-system primary owner FAR is deactivated, an async job need to check if it was replaced with another FAR
   * @param records Financial account role records from the trigger.
   * @param oldMap Map of old Financial account role records from the trigger.
   */
  public static void checkLastPrimaryOwnerDeactivated(
    List<FinServ__FinancialAccountRole__c> records,
    Map<Id, FinServ__FinancialAccountRole__c> oldMap
  ) {
    Financial_Account_Settings__c faSettings = Financial_Account_Settings__c.getOrgDefaults();
    Set<Id> faIds = new Set<Id>();

    for (FinServ__FinancialAccountRole__c record : records) {
      FinServ__FinancialAccountRole__c oldRecord = oldMap.get(record.Id);
      if (
        record.FinServ__RelatedAccount__c != faSettings.System_Customer_Id__c &&
        record.FinServ__Role__c == FAR_ROLE_PRIMARYOWNER &&
        !record.FinServ__Active__c &&
        oldRecord.FinServ__Active__c
      ) {
        faIds.add(record.FinServ__FinancialAccount__c);
      }
    }

    if (!faIds.isEmpty()) {
      System.enqueueJob(new CheckFaPrimaryOwner(faIds));
    }
  }

  private class CheckFaPrimaryOwner implements Queueable {
    private Set<Id> faIds;

    /**
     * @description constructor
     * @param faIds list of financial account record Ids to check
     */
    private CheckFaPrimaryOwner(Set<Id> faIds) {
      this.faIds = faIds;
    }

    /**
     * @description execute method
     * @param context QueueableContext
     */
    public void execute(QueueableContext context) {
      Financial_Account_Settings__c faSettings = Financial_Account_Settings__c.getOrgDefaults();
      List<FinServ__FinancialAccountRole__c> systemFars = new List<FinServ__FinancialAccountRole__c>();

      for (FinServ__FinancialAccount__c fa : [
        SELECT
          Id,
          (
            SELECT Id
            FROM FinServ__FinancialAccountRoles__r
            WHERE
              FinServ__Role__c = :FAR_ROLE_PRIMARYOWNER
              AND FinServ__Active__c = TRUE
          )
        FROM FinServ__FinancialAccount__c
        WHERE Id IN :this.faIds
        WITH USER_MODE
      ]) {
        if (fa.FinServ__FinancialAccountRoles__r.isEmpty()) {
          systemFars.add(
            new FinServ__FinancialAccountRole__c(
              FinServ__FinancialAccount__c = fa.Id,
              FinServ__RelatedAccount__c = faSettings.System_Customer_Id__c,
              FinServ__Role__c = FAR_ROLE_PRIMARYOWNER
            )
          );
        }
      }
      if (!systemFars.isEmpty()) {
        DMLUtil.insertRecords(systemFars, true, true);
      }
    }
  }
}