force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <description>Used for writing updates from OCV Party event messages. It is constructed in Mulesoft.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Source_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_System_ID__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Source System Id of Party received from OCV</description>
    <label>Source System ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApplicationForm/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Personal_Information;Source_Loan_Domain</complianceGroup>
    <description>External Id of the loan application</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Application Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApplicationForm/fields/Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Reference_Number__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source - CSP</complianceGroup>
    <description>Id of the CSP Application Number</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Reference Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApplicationForm/fields/Source_System_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_System_Id__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy - Non Personal Information;Source_Salesforce</complianceGroup>
    <description>External Id for AF Opportunity (OpportunityId + BrokerContactId)</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Source System Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApplicationFormProduct/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Personal Information;Source - Loan Domain</complianceGroup>
    <defaultValue>0</defaultValue>
    <description>Amount</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ApplicationFormProduct/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Personal_Information;Source_Loan_Domain</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Opportunity Line Item</description>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Application Form Products</relationshipLabel>
    <relationshipName>Application_Form_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApplicationFormProduct/fields/Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Reference_Number__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Personal_Information;Source_Loan_Domain</complianceGroup>
    <description>Identifier of the product that is added against the application in the loan application system.</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApplicationFormProduct/fields/Source_System_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_System_Id__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Personal Information;Source - Loan Domain</complianceGroup>
    <description>Id of the AMBIT Opportunity</description>
    <externalId>true</externalId>
    <label>Source System Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Numbers__c.field-meta.xml
<CustomField>
    <fullName>Application_Numbers__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy_Sensitive_Personal_Information;Source - Salesforce</complianceGroup>
    <description>Application Number from RLS or CAP</description>
    <label>Application Number(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Source_Salesforce;Integrity_Accurate</complianceGroup>
<description>Field to capture application number</description>
    <label>Application Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Reference_Number__c</fullName>
    <complianceGroup>Privacy_Personal_Information;Source_Salesforce;Integrity_Accurate</complianceGroup>
<description>Field to capture reference number</description>
    <label>Reference Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ccrm/CommercialOppoEventPayloadBuilderTest.cls
/**
 * @author Akanksha Kulkarni
 * @since Nov 2025
 * @group (Commercial Broker)
 * @description Test class for CommercialOpportunityEventPayloadBuilder
 */
@isTest
public class CommercialOppoEventPayloadBuilderTest {
  static Lib_MockProvider appFormProductRepoMock;
  static Lib_MockProvider commercialOppRepoMock;
  static Lib_MockProvider dmlRepoMock;
  static Lib_MockProvider oppTeamMemberRepo;
  static Lib_MockProvider userRepoMock;

  static void registerMocks() {
    appFormProductRepoMock = Lib_MockProvider.forType(
      CommercialAppFormProductActionsRepo.class
    );
    commercialOppRepoMock = Lib_MockProvider.forType(
      CommercialOpportunityRepository.class
    );
    dmlRepoMock = Lib_MockProvider.forType(DmlRepository.class);
    oppTeamMemberRepo = Lib_MockProvider.forType(
      CommercialOppTeamMemberRepository.class
    );
    userRepoMock = Lib_MockProvider.forType(UserInfoRepository.class);
  }

  @isTest
  static void buildOpportunityNodeTest() {
    registerMocks();
    Id accId = Lib_FakeIdGenerator.getMockId(Account.SObjectType);
    Id oppId = Lib_FakeIdGenerator.getMockId(Opportunity.SObjectType);
    Id oliId = Lib_FakeIdGenerator.getMockId(OpportunityLineItem.SObjectType);
    Id afId = Lib_FakeIdGenerator.getMockId(ApplicationForm.SObjectType);
    Id afpId = Lib_FakeIdGenerator.getMockId(
      ApplicationFormProduct.SObjectType
    );
    Id userId = Lib_FakeIdGenerator.getMockId(User.SObjectType);

    List<ApplicationFormProduct> records = new List<ApplicationFormProduct>{
      new ApplicationFormProduct(
        Id = afpId,
        Reference_Number__c = '87687',
        Amount__c = 50,
        Stage = 'Opportunity Won',
        Opportunity_Product__c = oliId,
        ApplicationFormId = afId,
        ApplicationForm = new ApplicationForm(
          Id = afId,
          RecordTypeId = RTApplicationForm.acmApplication
        )
      )
    };
    List<Account> accList = new List<Account>{
      new Account(Id = accId, External_Id__c = 'CAP-CIS_823749823')
    };
    List<Opportunity> oppList = new List<Opportunity>{
      new Opportunity(
        Id = oppId,
        AccountId = accId,
        Account = new Account(
          Id = accId,
          External_Id__c = 'CAP-CIS_823749823',
          Source_System_Id__c = 'SYSTEM-123'
        ),
        Application_Numbers__c = 'APP-001',
        RecordTypeId = RTOpportunity.commercialOpportunity,
        OwnerId = userId
      )
    };
    ApplicationForm afList = new ApplicationForm(
      Id = afId,
      AccountId = accId,
      Application_Number__c = 'APP-001',
      OpportunityId = oppId,
      Opportunity = new Opportunity(
        Id = oppId,
        RecordTypeId = RTOpportunity.commercialOpportunity,
        OwnerId = userId
      )
    );

    List<OpportunityLineItem> oliList = new List<OpportunityLineItem>{
      new OpportunityLineItem(Id = oliId, OpportunityId = oppId)
    };
    OpportunityEventModel.OpportunityDetails jsonPayload = CommercialOpportunityEventBuilder.buildOpportunityNode(
      oppList[0],
      afList,
      oliList[0],
      records[0]
    );

    Test.startTest();
    CommercialOpportunityEventPayloadBuilder payload = new CommercialOpportunityEventPayloadBuilder(
      oppList[0],
      jsonPayload,
      'insert'
    );
    Test.stopTest();

    System.assertEquals(
      System.Label.ANZX_opportunity_event_ce_type + 'insert',
      payload.ce_type,
      'ce_type should match label + action'
    );
  }
}