force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <description>Used for writing updates from OCV Party event messages. It is constructed in Mulesoft.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Deliquent</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Account_Key__c.field-meta.xml
<CustomField>
    <fullName>Account_Key__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Field to store unique identifier for a Financial Account record received from OCV</description>
    <externalId>true</externalId>
    <label>Account Key</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Shows account number with hyphens similar to hyperlink number on related list</description>
    <formula>CASE( Product_Code_Display__c ,
&apos;DDA&apos;,LEFT(LPAD(FinServ__FinancialAccountNumber__c, 9,&apos;0&apos;),4)+&apos;-&apos;+RIGHT(LPAD(FinServ__FinancialAccountNumber__c, 9,&apos;0&apos;),5),
&apos;ILS&apos;,LEFT(LPAD(FinServ__FinancialAccountNumber__c, 9,&apos;0&apos;),4)+&apos;-&apos;+RIGHT(LPAD(FinServ__FinancialAccountNumber__c, 9,&apos;0&apos;),5),
&apos;CDA&apos;,LEFT(LPAD(FinServ__FinancialAccountNumber__c, 9,&apos;0&apos;),4)+&apos;-&apos;+RIGHT(LPAD(FinServ__FinancialAccountNumber__c, 9,&apos;0&apos;),5),
&apos;RSV&apos;,LEFT(LPAD(FinServ__FinancialAccountNumber__c, 9,&apos;0&apos;),4)+&apos;-&apos;+RIGHT(LPAD(FinServ__FinancialAccountNumber__c, 9,&apos;0&apos;),5),
&apos;OLL&apos;,LEFT(LPAD(FinServ__FinancialAccountNumber__c, 9,&apos;0&apos;),4)+&apos;-&apos;+RIGHT(LPAD(FinServ__FinancialAccountNumber__c, 9,&apos;0&apos;),5),
&apos;PCA&apos;,LEFT(FinServ__FinancialAccountNumber__c,4)+&apos;-&apos;+MID(FinServ__FinancialAccountNumber__c,5,4)+&apos;-&apos;+
MID(FinServ__FinancialAccountNumber__c,9,4)+&apos;-&apos;+MID(FinServ__FinancialAccountNumber__c,13,4),
&apos;PCB&apos;,LEFT(FinServ__FinancialAccountNumber__c,4)+&apos;-&apos;+MID(FinServ__FinancialAccountNumber__c,5,4)+&apos;-&apos;+
MID(FinServ__FinancialAccountNumber__c,9,4)+&apos;-&apos;+MID(FinServ__FinancialAccountNumber__c,13,4),
&apos;FM&apos;,LEFT(LPAD(FinServ__FinancialAccountNumber__c, 9,&apos;0&apos;),4)+&apos;-&apos;+RIGHT(LPAD(FinServ__FinancialAccountNumber__c, 9,&apos;0&apos;),5),
&apos;SSI&apos;,LEFT(LPAD(FinServ__FinancialAccountNumber__c, 9,&apos;0&apos;),4)+&apos;-&apos;+RIGHT(LPAD(FinServ__FinancialAccountNumber__c, 9,&apos;0&apos;),5),
&apos;PTF&apos;,LEFT(FinServ__FinancialAccountNumber__c,4)+&apos;-&apos;+MID(FinServ__FinancialAccountNumber__c,5,3)+&apos;-&apos;+RIGHT(FinServ__FinancialAccountNumber__c,4),
&apos;CACHE:DDA&apos;,LEFT(LPAD(FinServ__FinancialAccountNumber__c, 9,&apos;0&apos;),4)+&apos;-&apos;+RIGHT(LPAD(FinServ__FinancialAccountNumber__c, 9,&apos;0&apos;),5),
&apos;CACHE:LA&apos;,LEFT(LPAD(FinServ__FinancialAccountNumber__c, 9,&apos;0&apos;),4)+&apos;-&apos;+RIGHT(LPAD(FinServ__FinancialAccountNumber__c, 9,&apos;0&apos;),5),
&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__FinancialAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccountNumber__c</fullName>
    <complianceGroup>Source_CTM;Integrity_Trusted</complianceGroup>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__FinancialAccountType__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccountType__c</fullName>
    <complianceGroup>Integrity - Accurate</complianceGroup>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Brokerage</fullName>
            </value>
            <value>
                <fullName>Discount Brokerage</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>Checking</fullName>
            </value>
            <value>
                <fullName>Cash Management Account</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Mutual Fund</fullName>
            </value>
            <value>
                <fullName>Fixed Annuity</fullName>
            </value>
            <value>
                <fullName>Variable Annuity</fullName>
            </value>
            <value>
                <fullName>Managed Account</fullName>
            </value>
            <value>
                <fullName>Individual Life</fullName>
            </value>
            <value>
                <fullName>Term Life</fullName>
            </value>
            <value>
                <fullName>Variable Life</fullName>
            </value>
            <value>
                <fullName>Whole Life</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__PrimaryOwner__c.field-meta.xml
<CustomField>
    <fullName>FinServ__PrimaryOwner__c</fullName>
    <complianceGroup>Integrity - Accurate</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
    <relationshipName>ClientFinancialAccounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <complianceGroup>Integrity_Accurate</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Charge-off</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Paid out</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Account Master Product type received from OCV at financial account level</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Product Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Role_Type__c.field-meta.xml
<CustomField>
    <fullName>Role_Type__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal Information;Source_OCV</complianceGroup>
    <description>Primary Owner and Additional Owner Role Type</description>
    <label>RoleType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FinancialAccountRoleType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/FinServ__FinancialAccountRole__c.object-meta.xml
<CustomObject>
    <description>Represents the role occupied by a person or organizational entity that is involved with a financial account, such as a beneficiary or trustee.</description>
    <label>Financial Account Role</label>
    <nameField>
        <displayFormat>FAR-{000000000}</displayFormat>
        <label>Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>This field holds the account number of the financial account</description>
    <formula>FinServ__FinancialAccount__r.FinServ__FinancialAccountNumber__c</formula>
    <label>Account Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <complianceGroup>Source - OCV;Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <description>This field will store External ID generated by concatenating Account External ID + Financial Account Key + Financial Account Role + Start date</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__Active__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Active__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy - Personal Information</complianceGroup>
    <defaultValue>true</defaultValue>
    <description>Indicates whether the organizational entity or person currently occupies this role.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy - Personal Information</complianceGroup>
    <description>Financial account that this role is related to.</description>
    <label>Financial Account</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelatedAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the organizational entity that is involved with the financial account.</description>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/Role_Type__c.field-meta.xml
<CustomField>
    <fullName>Role_Type__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Personal Information;Source - OCV</complianceGroup>
    <description>Primary Owner and Additional Owner Role Type</description>
    <label>Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FinancialAccountRoleType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ccrm/CCRMFavoureeQueryTest.cls
/**
 * @author Ayushi Gupta
 * @since  09/2023
 * @group CCRM (Commercial CRM)
 * @description Test class of CCRMFavoureeQuery
 */
@isTest
private class CCRMFavoureeQueryTest {
  static Lib_MockProvider faRepoMock;
  static Lib_MockProvider dmlRepoMock;
  static void registerMocks() {
    dmlRepoMock = Lib_MockProvider.forType(DMLRepository.class);
    faRepoMock = Lib_MockProvider.forType(
      CCRMFinancialAccountQueryBaseRepository.class
    );
  }

  private static FinServ__FinancialAccountRole__c getMockedData() {
    Id accId = Lib_FakeIdGenerator.getMockId(Account.SobjectType);

    FinServ__FinancialAccountRole__c mockFar = new FinServ__FinancialAccountRole__c(
      FinServ__Active__c = true,
      Role_Type__c = 'UNO',
      FinServ__FinancialAccount__r = (FinServ__FinancialAccount__c) TestUtil.setFields(
        new FinServ__FinancialAccount__c(
          Name = 'Test',
          FinServ__Status__c = 'Active',
          FinServ__FinancialAccountType__c = 'Savings',
          FinServ__PrimaryOwner__c = accId,
          Account_Key__c = '4011643101-3424909811',
          FinServ__FinancialAccountNumber__c = '3424909811',
          Product_Type__c = 'CAP-CIS:DDA'
        ),
        new Map<String, Object>{ 'Account_Number__c' => '3424-909811' }
      ),
      FinServ__RelatedAccount__r = new Account(
        External_Id__c = 'CAP-CIS_4011643101'
      )
    );
    return mockFar;
  }

  @isTest
  static void testParseResponse() {
    String responseBody =
      ' {' +
      '   "guaranteesFavourees": [' +
      '     {' +
      '       "compositeGuaranteesFavoureesId": "4020018249-72466661701-29618-0",' +
      '       "name": "test",' +
      '       "abn": "DDA"' +
      '     }' +
      '   ]' +
      ' }';

    CCRMFavoureeQuery favoureeAcct = new CCRMFavoureeQuery();
    Test.startTest();
    favoureeAcct.parseResponse(responseBody);
    Test.stopTest();
    Assert.isFalse(
      favoureeAcct.calloutResponse == null,
      'Response is not null'
    );
  }

  @isTest
  static void createFavoureeTest() {
    registerMocks();
    Id accId = Lib_FakeIdGenerator.getMockId(Account.SobjectType);
    FinServ__FinancialAccountRole__c mockFar = getMockedData();
    DataSource.QueryContext context = CCRMTestDataFactory.createFavoureeQueryContext();
    CCRMFavoureeQuery favoureeQuery = new CCRMFavoureeQuery();
    faRepoMock.mock(
      'getFinancialAccountsWithCustomerId',
      new List<FinServ__FinancialAccountRole__c>{ mockFar }
    );
    Test.startTest();
    CCRMExternalObjectQueryBase.ExternalQueryResult result = favoureeQuery.execute(
      context
    );
    Test.stopTest();
    assert.areEqual(1, result.queryResult.size(), 'Size of accounts is 1');
  }
}