force-app/main/default/objects/Account/fields/ExtraCareConsent__c.field-meta.xml
<CustomField>
    <fullName>ExtraCareConsent__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>This field is used to indicate that agent has  received consent from the customer
to record their extra care information
(sensitive information) on their customer profile</description>
    <label>Extra Care Consent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ExtraCareDisclosure__c.field-meta.xml
<CustomField>
    <fullName>ExtraCareDisclosure__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>This field is used to indicate that agent has  disclosed to the customer
about recording their extra care information
(personal information) on their customer profile</description>
    <label>Extra Care Disclosure</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ExtraCareNotes__c.field-meta.xml
<CustomField>
    <fullName>ExtraCareNotes__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source_OCV</complianceGroup>
    <description>This field captures the Extra Care Notes or Description</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Only record information that is needed to ensure appropriate provision of extra care to
the customer, keeping the notes brief. DO NOT leave notes with your opinion,
derogatory comments, or emotive language. For support or more information, refer to
KnowHow or relevant knowledge article.</inlineHelpText>
    <label>Notes</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/ExtraCareReason__c.field-meta.xml
<CustomField>
    <fullName>ExtraCareReason__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source_OCV</complianceGroup>
    <description>This field captures the Extra Care Reason.</description>
    <label>Reason(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aboriginal and/or Torres Strait Islander</fullName>
            </value>
            <value>
                <fullName>Administration Order</fullName>
            </value>
            <value>
                <fullName>Bereavement</fullName>
            </value>
            <value>
                <fullName>Cognitive capacity concerns</fullName>
            </value>
            <value>
                <fullName>Disability</fullName>
            </value>
            <value>
                <fullName>Family violence</fullName>
            </value>
            <value>
                <fullName>Financial abuse</fullName>
            </value>
            <value>
                <fullName>High Risk Scam Victim</fullName>
            </value>
            <value>
                <fullName>Incarceration/recently released from incarceration</fullName>
            </value>
            <value>
                <fullName>Literacy and/or language barriers including limited English</fullName>
            </value>
            <value>
                <fullName>Natural disaster/crisis response</fullName>
            </value>
            <value>
                <fullName>Other personal/financial difficulties causing major detriment</fullName>
            </value>
            <value>
                <fullName>Power of Attorney</fullName>
            </value>
            <value>
                <fullName>Propensity to commit self harm</fullName>
            </value>
            <value>
                <fullName>Remote location</fullName>
            </value>
            <value>
                <fullName>Serious medical conditions (including mental health)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ExtraCareReviewDate__c.field-meta.xml
<CustomField>
    <fullName>ExtraCareReviewDate__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>This field is used to capture the Review Date which is defaulted to 1 year from the Current Date.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Review Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/ExtraCareTimePeriod__c.field-meta.xml
<CustomField>
    <fullName>ExtraCareTimePeriod__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>A flag on customer&apos;s profile to Indicate if  the customer
requires extra care so that customers with this
requirement may be</description>
    <label>Time Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not required</fullName>
                <default>true</default>
                <label>Not required</label>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Temporarily required</fullName>
            </value>
            <value>
                <fullName>Ongoing and temporarily required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/Customer_Profile_Updates__c.object-meta.xml
<CustomObject>
    <description>This custom object is a staging object which will store the changes made by the bankers on Account and all Contact Point objects.</description>
    <label>Pending Updates to Customer Details</label>
    <nameField>
        <label>Customer Profile Updates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pending Updates to Customer Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will be a lookup on Customer&apos;s Profile (Accounts).</description>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pending Updates to Customer Details</relationshipLabel>
    <relationshipName>Customer_Profile_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Capture Status of Update. Like: Pending, Completed, Error.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ManageExtraCareControllerTest.cls
/**
 * @description       : Test Class for ManageExtraCareController
 * @author            : Akshat Khandelwal
 * @group             :
 * @last modified on  : Apr 2025
 **/
@IsTest
public with sharing class ManageExtraCareControllerTest {
  private static final Faker FAKER = new Faker('AU');
  static Lib_MockProvider manageExtraCareControllerRepositoryMock;
  static Lib_MockProvider profileStagingHandlerMock;
  static void registerMocks() {
    manageExtraCareControllerRepositoryMock = Lib_MockProvider.forType(
      ManageExtraCareControllerRepository.class
    );
    profileStagingHandlerMock = Lib_MockProvider.forType(
      ProfileStagingHandler.class
    );
  }

  static Id accountId = Lib_FakeIdGenerator.getMockId(Account.SObjectType);
  static Account record = new Account(
    Id = accountId,
    ExtraCareTimePeriod__c = 'Temporarily required',
    ExtraCareReason__c = 'Administration Order;Power of Attorney;Cognitive capacity concerns',
    ExtraCareNotes__c = 'Updating',
    ExtraCareReviewDate__c = Date.today(),
    ExtraCareDisclosure__c = true,
    ExtraCareConsent__c = true
  );
  static Account oldRecord = new Account(
    Id = accountId,
    ExtraCareTimePeriod__c = 'Temporarily required',
    ExtraCareReason__c = 'Administration Order;Power of Attorney',
    ExtraCareNotes__c = 'Updating',
    ExtraCareReviewDate__c = Date.today(),
    ExtraCareDisclosure__c = false,
    ExtraCareConsent__c = false
  );

  @IsTest
  private static void testHandleExtraCareUpdate() {
    registerMocks();
    Test.startTest();
    ManageExtraCareController.handleExtraCareUpdate(oldRecord, record);
    Test.stopTest();
    List<Account> newAccList = (List<Account>) profileStagingHandlerMock
      .getHistory('process')
      .getParam('records');
    Assert.areEqual(
      true,
      newAccList[0].ExtraCareConsent__c,
      'Extra Care Consent should be true.'
    );
    Assert.areEqual(
      true,
      newAccList[0].ExtraCareDisclosure__c,
      'Extra Care Disclosure should be true.'
    );
    Assert.areEqual(
      'Temporarily required',
      newAccList[0].ExtraCareTimePeriod__c,
      'Extra Care Time Period should be Temporarily required.'
    );
    Assert.areEqual(
      'Administration Order;Power of Attorney;Cognitive capacity concerns',
      newAccList[0].ExtraCareReason__c,
      'Extra Care Reason does not have correct values.'
    );
  }

  @IsTest
  private static void testGetStagingRecordStatus() {
    registerMocks();
    Id mockAccountId = Lib_FakeIdGenerator.getMockId(Account.SObjectType);
    Id customerProfileUpdatesId = Lib_FakeIdGenerator.getMockId(
      Customer_Profile_Updates__c.SObjectType
    );

    ManageExtraCareControllerRepositoryMock.mock(
      'queryCustomerProfileUpdateRecordByCustomerId',
      new Customer_Profile_Updates__c(
        id = customerProfileUpdatesId,
        Customer_Name__c = mockAccountId,
        Status__c = 'Pending'
      )
    );
    Test.startTest();
    String status = ManageExtraCareController.getStagingRecordStatus(
      mockAccountId
    );
    Test.stopTest();

    Assert.areEqual(
      'Pending',
      status,
      'The staging record status should be "Pending".'
    );
  }
}