force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Deliquent</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Source_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_System_ID__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Source System Id of Party received from OCV</description>
    <label>Source System ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Source_System_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_System_Name__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Source System Name of Party received from OCV (E.g. CAP)</description>
    <externalId>true</externalId>
    <label>Source System Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Fraud_Analytics_Assignee__c.field-meta.xml
<CustomField>
    <fullName>Fraud_Analytics_Assignee__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy_Personal_Information;Source - Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LookUp field for FraudX_Agent or Join_Lead role for Fraud Analytics Investigation</description>
    <label>Analytics Assignee</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$UserRole.DeveloperName</field>
            <operation>equals</operation>
            <value>FraudX_Agent</value>
        </filterItems>
        <filterItems>
            <field>$UserRole.DeveloperName</field>
            <operation>equals</operation>
            <value>Join_Lead</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/OCV_Id__c.field-meta.xml
<CustomField>
    <fullName>OCV_Id__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Personal_Information;Source_OCV</complianceGroup>
    <description>OCV ID of the customer</description>
    <externalId>true</externalId>
    <label>OCV Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/Customer_Profile_Updates__c.object-meta.xml
<CustomObject>
    <description>This custom object is a staging object which will store the changes made by the bankers on Account and all Contact Point objects.</description>
    <label>Pending Updates to Customer Details</label>
    <nameField>
        <label>Customer Profile Updates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pending Updates to Customer Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Action of the Update.</description>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Add</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/AsIsValue__c.field-meta.xml
<CustomField>
    <fullName>AsIsValue__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Personal Information;Source - Salesforce</complianceGroup>
    <description>This will be a JSON formatted structure of all the attribute with existing values.This is a back end field which will be used in the payloads pushed by the platform event subscribed by Mulesoft</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>AsIsValue</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Case</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pending Updates to Customer Details</relationshipLabel>
    <relationshipName>Customer_Profile_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will be a lookup on Customer&apos;s Profile (Accounts).</description>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pending Updates to Customer Details</relationshipLabel>
    <relationshipName>Customer_Profile_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Error_Description__c.field-meta.xml
<CustomField>
    <fullName>Error_Description__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Error Description in case of failures.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Error Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/NewValue__c.field-meta.xml
<CustomField>
    <fullName>NewValue__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Personal Information;Source - Salesforce</complianceGroup>
    <description>JSON formatted body structure of New values.</description>
    <label>New Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>To identify object where this update is happening. Eg Account, Contact, ContactPointXXXX.</description>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Occurrence_Number__c.field-meta.xml
<CustomField>
    <fullName>Occurrence_Number__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Source&apos; Occurrence Number.</description>
    <label>Occurrence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/OCV_Id__c.field-meta.xml
<CustomField>
    <fullName>OCV_Id__c</fullName>
    <description>Formula field to refer customer OCV Id</description>
    <formula>Customer_Name__r.OCV_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OCV Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Source_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_System_ID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Associated Customer Records Source System ID</description>
    <formula>Customer_Name__r.Source_System_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source System ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Source_System_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_System_Name__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Associated Customer Records Source System Name.</description>
    <formula>Customer_Name__r.Source_System_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source System Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Capture Status of Update. Like: Pending, Completed, Error.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/ToBeValue__c.field-meta.xml
<CustomField>
    <fullName>ToBeValue__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Personal Information;Source - Salesforce</complianceGroup>
    <description>JSON formatted body structure of New values.This is a back end field which will be used in the payloads pushed by the platform event subscribed by Mulesoft</description>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>ToBeValue</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/TriggeredFrom__c.field-meta.xml
<CustomField>
    <fullName>TriggeredFrom__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>To identify object where this update is happening.Eg Account, Contact, ContactPointXXXX. This is a back end field which will be used in the payloads pushed by the platform event subscribed by Mulesoft</description>
    <encryptionScheme>None</encryptionScheme>
    <label>TriggeredFrom</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfileStagingEventConfig__mdt/ProfileStagingEventConfig__mdt.object-meta.xml
<CustomObject>
    <description>Stores configuration to build cloud events from profile staging records.</description>
    <label>Profile Staging Event Config</label>
    <pluralLabel>Profile Staging Event Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/ProfileStagingEventConfig__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To publish Cloud Event</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProfileStagingEventConfig__mdt/fields/DataSchema__c.field-meta.xml
<CustomField>
    <fullName>DataSchema__c</fullName>
    <label>DataSchema</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfileStagingEventConfig__mdt/fields/EventType__c.field-meta.xml
<CustomField>
    <fullName>EventType__c</fullName>
    <label>EventType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfileStagingEventConfig__mdt/fields/PartitionKey__c.field-meta.xml
<CustomField>
    <fullName>PartitionKey__c</fullName>
    <label>PartitionKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfileStagingEventConfig__mdt/fields/PayloadModel__c.field-meta.xml
<CustomField>
    <fullName>PayloadModel__c</fullName>
    <label>PayloadModel</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfileStagingEventConfig__mdt/fields/PublishOldEvent__c.field-meta.xml
<CustomField>
    <fullName>PublishOldEvent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To publish Cloud Event and as well the old platform event</description>
    <label>Publish Old Event ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProfileStagingEventConfig__mdt/fields/RelatedIdField__c.field-meta.xml
<CustomField>
    <fullName>RelatedIdField__c</fullName>
    <label>RelatedIdField</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfileStagingEventConfig__mdt/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfileStagingEventConfig__mdt/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfileStagingEventConfig__mdt/fields/TriggeredFrom__c.field-meta.xml
<CustomField>
    <fullName>TriggeredFrom__c</fullName>
    <label>TriggeredFrom</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProfileStagingRepository.cls
/**
 * @description Provide database operation for {@link ProfileStagingTracker}
 * @author Tan Phan
 * @since 06/2024
 */
public with sharing class ProfileStagingRepository {
  /**
   * @description Event configuration metadata records.
   */
  private static List<ProfileStagingEventConfig__mdt> allConfig = [
    SELECT
      DataSchema__c,
      EventType__c,
      PartitionKey__c,
      PayloadModel__c,
      RelatedIdField__c,
      Source__c,
      Subject__c,
      TriggeredFrom__c,
      PublishOldEvent__c,
      Active__c
    FROM ProfileStagingEventConfig__mdt
    WHERE TriggeredFrom__c != NULL AND Active__c = TRUE
    WITH SYSTEM_MODE
  ];

  /**
   * @description Event configuration metadata records with TriggeredFrom__c as the key for easy retrieval of
   * the configuration based on the trigger source.
   */
  private static Map<string, ProfileStagingEventConfig__mdt> eventConfigMap = (Map<String, ProfileStagingEventConfig__mdt>) ListUtil.mapBy(
    allConfig,
    Customer_Profile_Updates__c.TriggeredFrom__c
  );

  /**
   * @description Queries customer profile updates along with customer info based on the provided list of records.
   * @param recordIds The set of customer profile update Ids to query.
   * @return A list of customer profile update records matching the provided IDs.
   */
  public List<Customer_Profile_Updates__c> queryCustomerProfileUpdates(
    Set<Id> recordIds
  ) {
    if (recordIds.isEmpty()) {
      return new List<Customer_Profile_Updates__c>();
    }
    //This query is set to run in SYSTEM_MODE, by the time query is executed user has already created the CPU based on their access.
    //This query is for the purpose of firing events with latest info. This is system initiated action to fire event.
    return [
      SELECT
        Id,
        Action__c,
        AsIsValue__c,
        Case__c,
        Case__r.CaseNumber,
        Customer_Name__r.RecordType.Id,
        Customer_Name__r.RecordType.DeveloperName,
        Customer_Name__r.OCV_Id__c,
        Customer_Name__r.Source_System_ID__c,
        Customer_Name__r.Source_System_Name__c,
        Customer_Name__r.FinServ__Status__c,
        Customer_Name__c,
        Error_Description__c,
        Object_Name__c,
        Occurrence_Number__c,
        Name,
        NewValue__c,
        OCV_Id__c,
        Source_System_ID__c,
        Source_System_Name__c,
        Status__c,
        ToBeValue__c,
        TriggeredFrom__c
      FROM Customer_Profile_Updates__c
      WHERE Id IN :recordIds
      WITH SYSTEM_MODE
    ];
  }

  /**
   * @description Queries event configurations based on the provided list of triggers.
   * @param triggerFrom unique triggerFrom value to get the event configuration.
   * @return A event configuration record matching the provided triggerFrom.
   */
  public ProfileStagingEventConfig__mdt getEventConfig(String triggerFrom) {
    return eventConfigMap.get(triggerFrom);
  }
}