force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Deliquent</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/FinancialAccountUIConfiguration__mdt.object-meta.xml
<CustomObject>
    <label>FinancialAccountUIConfiguration</label>
    <pluralLabel>FinancialAccountUIConfigurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Determines whether a certain product is ready to be shown on. Financial Account UI from Business perspective.</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FinancialAccountUIConfiguration__mdt/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Product code from Product2 table</description>
    <label>Product Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__Balance__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Balance__c</fullName>
    <complianceGroup>Source_CTM;Integrity - Highly Trusted;Privacy - Personal Information</complianceGroup>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__CurrentPostedBalance__c.field-meta.xml
<CustomField>
    <fullName>FinServ__CurrentPostedBalance__c</fullName>
    <complianceGroup>Source_CTM;Integrity - Highly Trusted</complianceGroup>
    <label>Current Posted Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__FinancialAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccountNumber__c</fullName>
    <complianceGroup>Source_CTM;Integrity_Trusted</complianceGroup>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__OpenDate__c.field-meta.xml
<CustomField>
    <fullName>FinServ__OpenDate__c</fullName>
    <complianceGroup>Source_Fabric;Integrity_Accurate</complianceGroup>
    <label>Date Opened</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__PrimaryOwner__c.field-meta.xml
<CustomField>
    <fullName>FinServ__PrimaryOwner__c</fullName>
    <complianceGroup>Integrity - Accurate</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
    <relationshipName>ClientFinancialAccounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__ProductName__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ProductName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Insurance policy product name.</description>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Financial Account Products</relationshipLabel>
    <relationshipName>FinancialAccountProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <complianceGroup>Integrity_Accurate</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Charge-off</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Paid out</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Marketing_Code__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Code__c</fullName>
    <complianceGroup>Source_OCV;Integrity_Accurate;Privacy_Non_Personal_Information</complianceGroup>
    <description>Zafin Account Marketing code from OCV at financial account level</description>
    <label>Marketing Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <formula>FinServ__PrimaryOwner__r.OCV_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OCV_ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Calculates if account ownership is single or multiparty</description>
    <formula>IF(Additional_Owner_Count__c  &gt;= 1,&quot;Multi-party&quot;, &quot;Single&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ownership</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/FinServ__FinancialAccountRole__c.object-meta.xml
<CustomObject>
    <description>Represents the role occupied by a person or organizational entity that is involved with a financial account, such as a beneficiary or trustee.</description>
    <label>Financial Account Role</label>
    <nameField>
        <displayFormat>FAR-{000000000}</displayFormat>
        <label>Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__Active__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Active__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy - Personal Information</complianceGroup>
    <defaultValue>true</defaultValue>
    <description>Indicates whether the organizational entity or person currently occupies this role.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy - Personal Information</complianceGroup>
    <description>Financial account that this role is related to.</description>
    <label>Financial Account</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelatedAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the organizational entity that is involved with the financial account.</description>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__Role__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Role__c</fullName>
    <complianceGroup>Integrity_Trusted</complianceGroup>
    <description>Role that describes how the organizational entity or person is involved with the financial account.</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Additional Owner</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Advisor</fullName>
            </value>
            <value>
                <fullName>Annuitant</fullName>
            </value>
            <value>
                <fullName>Appoint / Remove Authority</fullName>
            </value>
            <value>
                <fullName>Authorized Agent</fullName>
            </value>
            <value>
                <fullName>Authorized Agent / Beneficial Owner</fullName>
            </value>
            <value>
                <fullName>Authorized Individual</fullName>
            </value>
            <value>
                <fullName>Authorized Signer</fullName>
            </value>
            <value>
                <fullName>Beneficial Owner</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
            <value>
                <fullName>Business Manager</fullName>
            </value>
            <value>
                <fullName>Committee Member</fullName>
            </value>
            <value>
                <fullName>Conservator</fullName>
            </value>
            <value>
                <fullName>Control Person</fullName>
            </value>
            <value>
                <fullName>Corporation</fullName>
            </value>
            <value>
                <fullName>Cosigner</fullName>
            </value>
            <value>
                <fullName>Custodian</fullName>
            </value>
            <value>
                <fullName>Deceased Grantor</fullName>
            </value>
            <value>
                <fullName>Decedent</fullName>
            </value>
            <value>
                <fullName>Discretionary</fullName>
            </value>
            <value>
                <fullName>Foundation</fullName>
            </value>
            <value>
                <fullName>Full Authority</fullName>
            </value>
            <value>
                <fullName>Grantor</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Insured</fullName>
            </value>
            <value>
                <fullName>Interested Party</fullName>
            </value>
            <value>
                <fullName>Joint Owner</fullName>
            </value>
            <value>
                <fullName>Minor Primary Owner</fullName>
            </value>
            <value>
                <fullName>Primary Owner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>This field holds the Ownership of the of the customer for the Financial Account</description>
    <formula>FinServ__FinancialAccount__r.Ownership__c</formula>
    <label>Ownership</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FinancialAccountRepository.cls
/**
 * @author Shivam Swaraj
 * @since Mon July 24 2024
 * @description Provides SOQL and DML helpers for HomeLoanController, FinancialAccountController
 */
public with sharing class FinancialAccountRepository {
  //Financial Account Role Types To Include for showing owner names on financial account record page
  private static final Set<String> FINSERV_ROLE_TYPES = new Set<String>{
    'Additional Owner',
    'Primary Owner'
  };
  /**
   * @description return the id(s) of the financial account owners
   * @param financialAccountId financial account record id
   * @return list of FAR which are Primary or Additional role type
   */
  public List<FinServ__FinancialAccountRole__c> getAccountOwnerDetails(
    Id financialAccountId
  ) {
    //Check if can query financial account role
    PermissionUtils.canQuery('FinServ__FinancialAccountRole__c');

    return [
      SELECT Id, FinServ__RelatedAccount__c, FinServ__RelatedAccount__r.Name
      FROM FinServ__FinancialAccountRole__c
      WHERE
        FinServ__FinancialAccount__c = :financialAccountId
        AND FinServ__Active__c = TRUE
        AND FinServ__Role__c IN :FINSERV_ROLE_TYPES
    ];
  }

  /**
   * @description fetch financial accounts based on the ocvid
   * @param ocvId String containing the ocvId of the customer
   * @return List<FinServ__FinancialAccount__c> List of FinancialAccounts based on ocvid
   */
  public List<FinServ__FinancialAccount__c> fetchFinancialAccountsByStatus(
    String ocvId
  ) {
    if (
      SObjectType.FinServ__FinancialAccount__c.isQueryable() == false &&
      String.isBlank(ocvId)
    ) {
      return new List<FinServ__FinancialAccount__c>();
    }
    return [
      SELECT
        FinServ__FinancialAccountNumber__c,
        Ownership__c,
        FinServ__Status__c
      FROM FinServ__FinancialAccount__c
      WHERE
        Id IN (
          SELECT FinServ__FinancialAccount__c
          FROM FinServ__FinancialAccountRole__c
          WHERE
            FinServ__RelatedAccount__r.OCV_ID__c = :ocvId
            AND FinServ__Active__c = TRUE
        )
    ];
  }

  /**
   * @param finAccountNumbers the List of offset account numbers
   * @return `List<FinServ__FinancialAccount__c>` List of financial accounts records
   * @description Fetch all the Financial account records for given finAccountNumbers and return the List
   */
  public List<FinServ__FinancialAccount__c> getFinAccountList(
    List<String> finAccountNumbers
  ) {
    if (
      finAccountNumbers.isEmpty() ||
      PermissionUtils.canQuery('FinServ__FinancialAccount__c') == false
    ) {
      return new List<FinServ__FinancialAccount__c>();
    }
    return [
      SELECT Id, FinServ__FinancialAccountNumber__c
      FROM FinServ__FinancialAccount__c
      WHERE FinServ__FinancialAccountNumber__c IN :finAccountNumbers
    ];
  }

  /**
   * @description return list of linked home loan financial accounts
   * @param customerId customer id
   * @return  `List<FinServ__FinancialAccountRole__c>` list of linked financial accounts
   */
  public List<FinServ__FinancialAccountRole__c> getHomeLoanAccountByCustomerId(
    Id customerId
  ) {
    PermissionUtils.canQuery('FinServ__FinancialAccountRole__c');

    return [
      SELECT
        Id,
        FinServ__FinancialAccount__c,
        FinServ__FinancialAccount__r.FinServ__FinancialAccountNumber__c
      FROM FinServ__FinancialAccountRole__c
      WHERE
        FinServ__RelatedAccount__c = :customerId
        AND FinServ__FinancialAccount__r.RecordTypeId = :RTFinancialAccount.bankAccount
        AND FinServ__FinancialAccount__r.Marketing_Code__c IN :GetHelpConstants.HOME_LOAN_MARKETING_CODES
        AND FinServ__Active__c = TRUE
    ];
  }

  /**
   * @description gets all the finanacial account which needds to be displayed on UI
   * @param ownerId owner of fin account
   * @param allRelatedAccountNumbers all the rekated financial account numbers
   * @param recordTypeDeveloperNames record type developer names
   * @return list of FinServ__FinancialAccount__c
   */
  public List<FinServ__FinancialAccount__c> getFinacialAccounts(
    Id ownerId,
    List<String> allRelatedAccountNumbers,
    List<String> recordTypeDeveloperNames
  ) {
    return [
      SELECT
        Id,
        Name,
        FinServ__Balance__c,
        FinServ__CurrentPostedBalance__c,
        FinServ__CloseDate__c,
        FinServ__FinancialAccountNumber__c,
        FinServ__Status__c,
        FinServ__OpenDate__c,
        Marketing_Code__c,
        RecordType.DeveloperName,
        LastModifiedDate,
        Ownership__c,
        OCV_ID__c,
        FinServ__ProductName__c
      FROM FinServ__FinancialAccount__c
      WHERE
        (FinServ__PrimaryOwner__c = :ownerId
        OR FinServ__FinancialAccountNumber__c IN :allRelatedAccountNumbers)
        AND RecordType.DeveloperName IN :recordTypeDeveloperNames
        AND FinServ__Status__c != 'Closed'
      WITH USER_MODE
      ORDER BY FinServ__Status__c DESC, FinServ__OpenDate__c DESC
    ];
  }

  /**
   * @description This method prepares map of product code and financial account UI config details
   * @return Map of product code and financial account UI config record
   */
  public Map<String, FinancialAccountUIConfiguration__mdt> mapProductCodeToFinAccountConfiguration() {
    Map<String, FinancialAccountUIConfiguration__mdt> productCodeToFinAccConfigMap = new Map<String, FinancialAccountUIConfiguration__mdt>();

    List<FinancialAccountUIConfiguration__mdt> financialAccountUIDetails = [
      SELECT
        Product_Code__c,
        Is_Active__c,
        Is_Home_Loan__c,
        Show_Goals__c,
        Sort_Order__c,
        Ownership_Type__c,
        Product_Name__c,
        Section_Header_Title__c,
        Balance_Title__c
      FROM FinancialAccountUIConfiguration__mdt
      WITH USER_MODE
    ];

    for (
      FinancialAccountUIConfiguration__mdt finUIConfig : financialAccountUIDetails
    ) {
      String key =
        finUIConfig?.Product_Code__c +
        '-' +
        finUIConfig?.Ownership_Type__c;
      if (!productCodeToFinAccConfigMap.containsKey(key)) {
        productCodeToFinAccConfigMap.put(key, finUIConfig);
      }
    }
    return productCodeToFinAccConfigMap;
  }

  /**
   * @description This method prepares map of product code and financial account UI config details
   * @return Map of product code and financial account UI config record
   */
  public Map<String, FinancialAccountUIConfiguration__mdt> mapProductCodeToFinAccounDetails() {
    Map<String, FinancialAccountUIConfiguration__mdt> productCodeToFinAccMap = new Map<String, FinancialAccountUIConfiguration__mdt>();

    List<FinancialAccountUIConfiguration__mdt> financialAccountUIDetails = [
      SELECT
        Product_Code__c,
        Ownership_Type__c,
        Show_Goals__c,
        Sort_Order__c,
        Is_Home_Loan__c,
        Is_Active__c,
        Account_Type__c,
        Balance_Title__c,
        Product_Name__c,
        Section_Header_Title__c
      FROM FinancialAccountUIConfiguration__mdt
      WITH USER_MODE
    ];

    for (
      FinancialAccountUIConfiguration__mdt finUIConfig : financialAccountUIDetails
    ) {
      if (!productCodeToFinAccMap.containsKey(finUIConfig.Product_Code__c)) {
        productCodeToFinAccMap.put(finUIConfig.Product_Code__c, finUIConfig);
      }
    }
    return productCodeToFinAccMap;
  }

  /**
   * @description This method returnd financial account UI config details based on product code
   * @param productCodes set of product codes
   * @return List of financial account UI config data based on product code
   */
  public List<FinancialAccountUIConfiguration__mdt> fetchMetadataForProductCodes(
    Set<String> productCodes
  ) {
    return [
      SELECT
        Product_Code__c,
        Ownership_Type__c,
        Show_Goals__c,
        Sort_Order__c,
        Is_Home_Loan__c,
        Is_Active__c,
        Account_Type__c,
        Balance_Title__c,
        Product_Name__c,
        Section_Header_Title__c
      FROM FinancialAccountUIConfiguration__mdt
      WHERE Product_Code__c IN :productCodes
      WITH USER_MODE
    ];
  }
}