force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Deliquent</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Source_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_System_ID__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Source System Id of Party received from OCV</description>
    <label>Source System ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Source_System_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_System_Name__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Source System Name of Party received from OCV (E.g. CAP)</description>
    <externalId>true</externalId>
    <label>Source System Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Target Stream that will be receiving the referral.</description>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>International Banking Services</fullName>
            </value>
            <value>
                <fullName>Mobile Lending</fullName>
            </value>
            <value>
                <fullName>Private Bank</fullName>
            </value>
            <value>
                <fullName>Video Conferencing (Mortgages)</fullName>
            </value>
            <value>
                <fullName>Home Loan Hotline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Customer CAPSIS ID (Individual)</description>
    <label>Customer ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/External_Referral_Status__c.field-meta.xml
<CustomField>
    <fullName>External_Referral_Status__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non-Sensitive Personal Information;Source - IKnow</complianceGroup>
    <description>iKnow Referral Status</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>External Referral Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FinServ__ExpressedInterest__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ExpressedInterest__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Source_Salesforce;Integrity_Accurate</complianceGroup>
    <label>Expressed Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FinServ__ProductList</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/FinServ__ReferredByUser__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ReferredByUser__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Internal Referrer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>LeadUserReferrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FinServ__RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelatedAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This includes Organisation, Individual, CLG, Prospect Customers.</inlineHelpText>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Leads</relationshipLabel>
    <relationshipName>RelatedLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Auto_Number__c.field-meta.xml
<CustomField>
    <fullName>Lead_Auto_Number__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Auto Number for Leads</description>
    <displayFormat>{00000000}</displayFormat>
    <label>Lead Auto Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Lead_Outcome__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>This is the CCRM field to track the lead Outcome Type.</description>
    <label>Lead Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Identified</fullName>
            </value>
            <value>
                <fullName>No Opportunity</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy_Non-Sensitive_Personal_Information;Source - Salesforce</complianceGroup>
    <description>Additional Notes of a Lead record.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Primary_Contact_Method__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Method__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>It is used to display contact method.</description>
    <label>Primary Contact Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Work Phone</fullName>
            </value>
            <value>
                <fullName>Home Phone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Referral_Category__c.field-meta.xml
<CustomField>
    <fullName>Referral_Category__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Categories the source of the referral</description>
    <label>Referral Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Channel__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A-Z Review</fullName>
            </value>
            <value>
                <fullName>Affluent</fullName>
            </value>
            <value>
                <fullName>Borrow - Mortgage</fullName>
            </value>
            <value>
                <fullName>Borrow - Other</fullName>
            </value>
            <value>
                <fullName>Home Loan Check-In</fullName>
            </value>
            <value>
                <fullName>Moving Overseas</fullName>
            </value>
            <value>
                <fullName>Corporate Banking</fullName>
            </value>
            <value>
                <fullName>Commercial Cards-BB, RBB &amp; PB</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>Business Banking</fullName>
            </value>
            <value>
                <fullName>Esanda</fullName>
            </value>
            <value>
                <fullName>Regional Business Banking</fullName>
            </value>
            <value>
                <fullName>Small Business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Referral_Status__c.field-meta.xml
<CustomField>
    <fullName>Referral_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The status of the referral, this will be used by referrer to track the shared referral.</description>
    <label>Referral Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Export Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Work_Phone__c.field-meta.xml
<CustomField>
    <fullName>Work_Phone__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Work phone number</description>
    <inlineHelpText>Work Phone number needs to be in the format of +61 followed by 9 digits. Eg. +61312345678</inlineHelpText>
    <label>Work Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/User/fields/Lan_Id__c.field-meta.xml
<CustomField>
    <fullName>Lan_Id__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Integrity_Trusted;Source_Salesforce</complianceGroup>
    <description>LAN ID of the user who captured the response or who the lead was routed to (if available).</description>
    <externalId>true</externalId>
    <label>Lan Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/FinServ__ProductList.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Term Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Overdraft</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>Asset Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Merchant</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Foreign Exchange</fullName>
    </customValue>
    <customValue>
        <fullName>Wealth</fullName>
    </customValue>
    <customValue>
        <fullName>Indemnity Guarantee</fullName>
    </customValue>
    <customValue>
        <fullName>Home Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Home Loan - Bridging Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Home Loan - Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Home Loan - Refinance + Purchase</fullName>
    </customValue>
    <customValue>
        <fullName>Home Loan - Purchase</fullName>
    </customValue>
    <customValue>
        <fullName>Home Loan - Refinance</fullName>
    </customValue>
    <customValue>
        <fullName>Home Loan - Maintenance</fullName>
    </customValue>
    <customValue>
        <fullName>Home Loan - Increase</fullName>
    </customValue>
    <customValue>
        <fullName>Home Loan - Other</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Other Loans</fullName>
    </customValue>
    <customValue>
        <fullName>Purchasing Property</fullName>
    </customValue>
    <customValue>
        <fullName>Purchasing Vacant Land</fullName>
    </customValue>
    <customValue>
        <fullName>Purchasing an existing Business</fullName>
    </customValue>
    <customValue>
        <fullName>Purchasing a new Business</fullName>
    </customValue>
    <customValue>
        <fullName>Purchasing equipment (inc. vehicles and fit out)</fullName>
    </customValue>
    <customValue>
        <fullName>Set up a new Business (Start Up)</fullName>
    </customValue>
    <customValue>
        <fullName>Assist with Business Working Capital/Temporary Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Refinance from Other Financial Institutions</fullName>
    </customValue>
    <customValue>
        <fullName>Construction and Renovation</fullName>
    </customValue>
    <masterLabel>Product List</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/repository/CommercialReferralLeadRepository.cls
/**
 * @author       : Advait Yermalkar
 * @since        : 02-25-2025
 * @description  :  This class containspublic repository for all queries used in InteractionCEController
 **/
public with sharing class CommercialReferralLeadRepository {
  private static final String LEAD_OUTCOME_REFERRED = 'Referred';

  /**
   * @description get Customers data based on Ids
   * @param relatedCustomerIds
   * @return List<Account>
   **/
  public List<Account> getCustomers(Set<id> relatedCustomerIds) {
    if (relatedCustomerIds.isEmpty()) {
      return new List<Account>();
    }
    return [
      SELECT
        Id,
        Name,
        Source_System_ID__c,
        Source_System_Name__c,
        OCV_ID__c,
        RecordTypeId
      FROM Account
      WHERE Id IN :relatedCustomerIds
      WITH USER_MODE
    ];
  }

  /**
   * @description get the user records based on Ids
   * @param relatedUserIds
   * @return List<User>
   **/
  public List<User> getUsers(Set<Id> relatedUserIds) {
    if (relatedUserIds.isEmpty()) {
      return new List<User>();
    }
    return [
      SELECT Id, Email, UserName, Lan_Id__c, FirstName, LastName
      FROM User
      WHERE Id IN :relatedUserIds
      WITH USER_MODE
    ];
  }

  /**
   * @description get the parent lead info
   * @param parentLeadsIdsSet
   * @return List<Lead>
   **/
  public List<Lead> fetchParentLeads(Set<Id> parentLeadsIdsSet) {
    if (parentLeadsIdsSet.isEmpty()) {
      return new List<Lead>();
    }

    return [
      SELECT Id, Status, Lead_Outcome__c
      FROM Lead
      WHERE
        Id IN :parentLeadsIdsSet
        AND RecordTypeId = :RTLead.commercialLead
        AND Lead_Outcome__c != :LEAD_OUTCOME_REFERRED
      WITH USER_MODE
    ];
  }

  /**
   * @description get Manager Info
   * @param ownerIdSet set of Lead owner ids
   * @return List<User> User list
   **/
  public List<User> getManagerInfo(Set<Id> ownerIdSet) {
    if (ownerIdSet.isEmpty()) {
      return new List<User>();
    }

    return [
      SELECT Id, ManagerId, IsActive
      FROM User
      WHERE IsActive = TRUE AND Id IN :ownerIdSet AND ManagerId != NULL
      WITH USER_MODE
    ];
  }

  /**
   * @description get Queue member list
   * @param setOfGroups Set of Groups as lead owners
   * @return List<GroupMember> group member list
   **/
  public List<GroupMember> getQueueMembers(Set<Id> setOfGroups) {
    if (setOfGroups.isEmpty()) {
      return new List<GroupMember>();
    }
    return [
      SELECT Id, GroupId, UserOrGroupId, UserOrGroup.Name, UserOrGroup.IsActive
      FROM GroupMember
      WHERE UserOrGroup.IsActive = TRUE AND GroupId IN :setOfGroups
      WITH USER_MODE
    ];
  }

  /**
   * @description It will fetch the user Profile Id
   * @param customerIds set of Customer Ids
   * @return List<Account> Account List
   */
  public List<Account> getAccountRecords(Set<Id> customerIds) {
    if (customerIds.isEmpty()) {
      return new List<Account>();
    }
    return [
      SELECT Id, Finserv__Status__c
      FROM Account
      WHERE Id IN :customerIds AND Finserv__Status__c = 'Prospect'
      WITH USER_MODE
    ];
  }

  /**
   * @description It will fetch all permission set Ids having custom permission assigned
   * @param customPermission name of custom permission
   * @return List<SetupEntityAccess>
   */
  public List<SetupEntityAccess> getPermissionSetWithCustomPermission(
    String customPermission
  ) {
    if (customPermission == null) {
      return new List<SetupEntityAccess>();
    }
    return [
      SELECT ParentId
      FROM SetupEntityAccess
      WHERE
        SetupEntityId IN (
          SELECT Id
          FROM CustomPermission
          WHERE DeveloperName = :customPermission
        )
      WITH SYSTEM_MODE
    ];
  }

  /**
   * @description It will fetch all permission set groups containing mentioned permission sets
   * @param permissionSetWithCustomPermission permission set Ids having custom permission assigned
   * @return List<PermissionSetGroupComponent>
   */
  public List<PermissionSetGroupComponent> getPermissionSetGroupFromPS(
    Set<Id> permissionSetWithCustomPermission
  ) {
    if (permissionSetWithCustomPermission.isEmpty()) {
      return new List<PermissionSetGroupComponent>();
    }
    return [
      SELECT PermissionSetGroupId
      FROM PermissionSetGroupComponent
      WHERE PermissionSetId IN :permissionSetWithCustomPermission
      WITH SYSTEM_MODE
    ];
  }

  /**
   * @description It will fetch all users having assinged to permission set groups
   * @param userIdSet set of ownerIds of lead
   * @param permissionSetWithCustomPermission permission set Ids having custom permission assigned
   * @param permissionSetGroupFromPS permission set groups containing mentioned permission sets
   * @return List<PermissionSetAssignment>
   */
  public List<PermissionSetAssignment> listOfUsersHavingCustomPermission(
    Set<Id> userIdSet,
    Set<Id> permissionSetWithCustomPermission,
    Set<Id> permissionSetGroupFromPS
  ) {
    if (
      permissionSetGroupFromPS.isEmpty() ||
      userIdSet.isEmpty() ||
      permissionSetWithCustomPermission.isEmpty()
    ) {
      return new List<PermissionSetAssignment>();
    }
    return [
      SELECT AssigneeId
      FROM PermissionSetAssignment
      WHERE
        IsActive = TRUE
        AND (PermissionSetId IN :permissionSetWithCustomPermission
        OR PermissionSetGroupId IN :permissionSetGroupFromPS)
        AND AssigneeId IN :userIdSet
      WITH SYSTEM_MODE
    ] ?? new List<PermissionSetAssignment>();
  }

  /**
   * @description It will fetch all the ccrm users
   * @param userIds set of user ids
   * @return List<User>
   */
  public List<User> getCCRMUsers(Set<Id> userIds) {
    if (userIds.isEmpty()) {
      return new List<User>();
    }
    return [
      SELECT Id, Profile.Name
      FROM User
      WHERE Id IN :userIds AND Profile.Name = 'ANZ CCRM Standard User'
      WITH SYSTEM_MODE
    ];
  }

  /**
   * @description Fetch leads by Id for reprocessing logic
   * @param leadIds Set of Lead Ids
   * @return List<Lead>
   **/
  public List<Lead> getLeadsById(Set<Id> leadIds) {
    if (leadIds.isEmpty()) {
      return new List<Lead>();
    }
    return [
      SELECT
        Id,
        RecordTypeId,
        Referral_Status__c,
        External_Referral_Status__c,
        OwnerId,
        FinServ__ReferredByUser__c,
        Note__c,
        Channel__c,
        Referral_Category__c,
        FinServ__ExpressedInterest__c,
        FinServ__RelatedAccount__c,
        Customer_ID__c,
        Email,
        Work_Phone__c,
        Primary_Contact_Method__c,
        Lead_Auto_Number__c,
        LastName,
        MiddleName,
        FirstName,
        Company,
        LastModifiedDate,
        Referral_Customer_Needs__c,
        MobilePhone,
        Home_Phone__c,
        FinServ__PotentialValue__c
      FROM Lead
      WHERE Id IN :leadIds
      WITH USER_MODE
    ];
  }

  /**
   * @description Fetch existing lead shares for given leads Ids and referred users Ids
   * @param leadIds Set of Lead Ids
   * @param intRefIdsSet Set of Internal referred user Ids
   * @return List<LeadShare>
   */
  public List<LeadShare> getExistingLeadShare(
    Set<Id> leadIds,
    Set<Id> intRefIdsSet
  ) {
    if (intRefIdsSet.isEmpty() || leadIds.isEmpty()) {
      return new List<LeadShare>();
    }
    return [
      SELECT Id, LeadId, UserOrGroupId, LeadAccessLevel
      FROM LeadShare
      WHERE
        LeadId IN :leadIds
        AND UserOrGroupId IN :intRefIdsSet
        AND RowCause = 'Manual'
      WITH SYSTEM_MODE
    ];
  }
}