force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Deliquent</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Picklist which determines if the related financial account is a joint or individual account</description>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
                <label>Sole</label>
            </value>
            <value>
                <fullName>Joint</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Closure_Reason__c.field-meta.xml
<CustomField>
    <fullName>Closure_Reason__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Specifies a reason for why the customer has requested an account closure</description>
    <label>Closure Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer did not mean to proceed to account opening</fullName>
            </value>
            <value>
                <fullName>Thought it was the ANZ App</fullName>
            </value>
            <value>
                <fullName>Unable to access existing ANZ accounts via ANZPlus app</fullName>
            </value>
            <value>
                <fullName>Lack of features</fullName>
            </value>
            <value>
                <fullName>Not satisfied with product</fullName>
            </value>
            <value>
                <fullName>No reason specified</fullName>
            </value>
            <value>
                <fullName>Bank Initiated Closure - Collections</fullName>
            </value>
            <value>
                <fullName>Other - please specify</fullName>
            </value>
            <value>
                <fullName>Bank initiated - Unacceptable Customer Behaviour</fullName>
            </value>
            <value>
                <fullName>Consolidation of accounts</fullName>
                <isActive>false</isActive>
                <label>Consolidation of accounts</label>
            </value>
            <value>
                <fullName>Missing features</fullName>
                <isActive>false</isActive>
                <label>Missing features</label>
            </value>
            <value>
                <fullName>Poor experience via Coach channel</fullName>
                <isActive>false</isActive>
                <label>Poor experience via Coach channel</label>
            </value>
            <value>
                <fullName>Product mis-sold in branch</fullName>
                <isActive>false</isActive>
                <label>Product mis-sold in branch</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FinServ__FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccount__c</fullName>
    <complianceGroup>Integrity - Accurate</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Intended_Account_BSB__c.field-meta.xml
<CustomField>
    <fullName>Intended_Account_BSB__c</fullName>
    <complianceGroup>Integrity_Trusted;Source_Salesforce;Privacy_Personal_Information</complianceGroup>
    <description>Unique branch code where the customer account is held.</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>Branch code of the recipient&apos;s bank where the money was meant to go.</inlineHelpText>
    <label>Intended Account BSB</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Intended_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Intended_Account_Name__c</fullName>
    <complianceGroup>Integrity - Trusted;Source - Salesforce</complianceGroup>
    <description>Name of customer who holds the account</description>
    <inlineHelpText>Name of customer who holds the account</inlineHelpText>
    <label>Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Intended_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Intended_Account_Number__c</fullName>
    <complianceGroup>Integrity - Trusted;Source - Salesforce;Privacy - Personal Information</complianceGroup>
    <description>Unique account number provided to the customer</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>Customer&apos;s account number</inlineHelpText>
    <label>Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Foreign key to Product2 table, if a case relates to a specific product, this links to that product</description>
    <inlineHelpText>Start typing the ANZ product or Service the case relates to for available options to appear</inlineHelpText>
    <label>Product or Service Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR (2 AND 3) OR 4) AND 5 AND 6</booleanFilter>
        <filterItems>
            <field>$User.Division</field>
            <operation>notEqual</operation>
            <value>Complaints indexing - CR</value>
        </filterItems>
        <filterItems>
            <field>$User.Division</field>
            <operation>equals</operation>
            <value>Complaints indexing - CR</value>
        </filterItems>
        <filterItems>
            <field>Product2.IDR_Product_Family__r.IDR_ANZ_com_Product_Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.IDR_Product_Category__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.IDR_Product_Category__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>CRM_ANZ_Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Related Issues</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__Balance__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Balance__c</fullName>
    <complianceGroup>Source_CTM;Integrity - Highly Trusted;Privacy - Personal Information</complianceGroup>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__FinancialAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccountNumber__c</fullName>
    <complianceGroup>Source_CTM;Integrity_Trusted</complianceGroup>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__ProductName__c.field-meta.xml
<CustomField>
    <fullName>FinServ__ProductName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Insurance policy product name.</description>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Financial Account Products</relationshipLabel>
    <relationshipName>FinancialAccountProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <complianceGroup>Integrity_Accurate</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Charge-off</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Paid out</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Marketing_Code__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Code__c</fullName>
    <complianceGroup>Source_OCV;Integrity_Accurate;Privacy_Non_Personal_Information</complianceGroup>
    <description>Zafin Account Marketing code from OCV at financial account level</description>
    <label>Marketing Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Number_Of_Signatures__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Signatures__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>The number of signatures required on joint accounts for events requiring additional authorisation.</description>
    <label>Signing Authority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Not Applicable</label>
            </value>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Anyone to Sign</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>All to sign</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Refer to Account Signing Authority</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountClosureWizardControllerHelper.cls
/**
 * @author Nilesh Kalal
 * @since Wed Dec 18 2024
 * @description Helper for Account Closure Wizard Controller
 */
public with sharing class AccountClosureWizardControllerHelper {
  private static final AccountClosureRepository ACCOUNT_CLOSURE_REPOSITORY = (AccountClosureRepository) Lib_InstanceProvider.forType(
    AccountClosureRepository.class
  );

  private static final DmlRepository DML_REPOSITORY = (DmlRepository) Lib_InstanceProvider.forType(
    DmlRepository.class
  );

  /**
   * @description Process dummy cases if found and map user input from lwc to case records
   * @param inputs List of CaseInput
   * @param listOfExistingDummyCases List of Cases
   * @return Set<Id>
   */
  public static Set<Id> processAndMapCasesFromInput(
    List<CaseInput> inputs,
    List<Case> listOfExistingDummyCases
  ) {
    List<Case> casesToUpdate = new List<Case>();
    List<Case> casesToInsert = new List<Case>();
    Set<Id> setOfCaseIds = new Set<Id>();

    for (Integer i = 0; i < inputs.size(); i++) {
      CaseInput input = inputs[i];
      if (i < listOfExistingDummyCases.size()) {
        Case existingCase = listOfExistingDummyCases[i];
        mapCaseFields(existingCase, input);
        casesToUpdate.add(existingCase);
      } else {
        Case newCase = new Case();
        mapCaseFields(newCase, input);
        casesToInsert.add(newCase);
      }
    }

    // Perform DML operations
    if (!casesToUpdate.isEmpty()) {
      DML_REPOSITORY.doUpdate(casesToUpdate);
      setOfCaseIds.addAll(ListUtil.getIds(casesToUpdate, Case.Id));
    }
    if (!casesToInsert.isEmpty()) {
      DML_REPOSITORY.doInsert(casesToInsert);
      setOfCaseIds.addAll(ListUtil.getIds(casesToInsert, Case.Id));
    }
    return setOfCaseIds;
  }

  /**
   * @description
   * @param caseObj case object record to be inserted or updated
   * @param caseInput from LWC
   */
  private static void mapCaseFields(Case caseObj, CaseInput caseInput) {
    caseObj.Status = caseInput.status;
    caseObj.Intended_Account_Name__c = caseInput.intendedAccountName;
    caseObj.Intended_Account_BSB__c = caseInput.intendedAccountBsb;
    caseObj.Intended_Account_Number__c = caseInput.intendedAccountNumber;
    caseObj.Closure_Reason__c = caseInput.closureReason;
    caseObj.Account_Type__c = caseInput.accountType;
    caseObj.AccountId = caseInput.accountId;
    caseObj.FinServ__FinancialAccount__c = caseInput.financialAccountId;
    caseObj.ProductId = caseInput.productId; // lookup to product table
    caseObj.RecordTypeId = RTCase.accountClosure;
  }

  /**
   * @description Extracts the Account Ids from the Case records
   * @param acccountIds set of case Ids to query
   * @return Set<Id> list of case records
   */
  public static Set<Id> getAccountsWithChildCases(Set<Id> acccountIds) {
    List<Case> childCases = ACCOUNT_CLOSURE_REPOSITORY.fetchChildCases(
      acccountIds
    );
    Set<Id> setOfFinAccountIds = ListUtil.getIds(
      childCases,
      Case.FinServ__FinancialAccount__c
    );
    return setOfFinAccountIds;
  }

  /**
   * @description Extracts the Account Ids from the Case records
   * @param listOfFinAccounts list of financial account records
   * @return List<FinancialAccountsResponse> list of Financial Account response
   */

  public static List<FinancialAccountsResponse> prepareFinancialAccountsResponse(
    List<FinServ__FinancialAccount__c> listOfFinAccounts
  ) {
    List<FinancialAccountsResponse> listOfFinancialAccountResponse = new List<FinancialAccountsResponse>();
    for (FinServ__FinancialAccount__c eachAccount : listOfFinAccounts) {
      // Use the Builder pattern to create the FinancialAccountsResponse object
      FinancialAccountsResponse response = new FinancialAccountsResponse.Builder()
        .setId(eachAccount.Id)
        .setAccountNumber(eachAccount.FinServ__FinancialAccountNumber__c)
        .setProductName(eachAccount.FinServ__ProductName__r.Name)
        .setProductId(eachAccount.FinServ__ProductName__c) // Product Id (lookup field)
        .setBalance(eachAccount.FinServ__Balance__c)
        .setOwnership(eachAccount.FinServ__Ownership__c)
        .setStatus(eachAccount.FinServ__Status__c)
        .setMarketingCode(eachAccount.Marketing_Code__c)
        .setSigningAuthority(eachAccount.Number_Of_Signatures__c)
        .setRecodTypeName(eachAccount.RecordType.DeveloperName)
        .build();
      // Add the response to the list
      listOfFinancialAccountResponse.add(response);
    }
    return listOfFinancialAccountResponse;
  }

  /**
   * @description Includes product name into the case response
   * @param caseInputs List of case inputs from UI form
   * @param listOfCases List of cases created/updated
   */

  public static void addProductNamesToCases(
    List<caseInput> caseInputs,
    List<Case> listOfCases
  ) {
    if (caseInputs.isEmpty() || listOfCases.isEmpty()) {
      return;
    }

    Map<Id, String> financialAccountToProductNameMap = new Map<Id, String>();
    for (CaseInput caseInput : caseInputs) {
      if (caseInput.financialAccountId != null) {
        financialAccountToProductNameMap.put(
          caseInput.financialAccountId,
          caseInput.productName
        );
      }
    }

    for (Case caseRecord : listOfCases) {
      if (
        caseRecord.FinServ__FinancialAccount__c != null &&
        financialAccountToProductNameMap.containsKey(
          caseRecord.FinServ__FinancialAccount__c
        )
      ) {
        caseRecord.put(
          'Product__c',
          financialAccountToProductNameMap.get(
            caseRecord.FinServ__FinancialAccount__c
          )
        );
      }
    }
  }

  /**
   * @description process fin accounts in order to prepare response
   * @param listOfFinAccounts List of case inputs from UI form
   * @return List<FinancialAccountsResponse> list of Financial Account response
   */
  public static List<FinancialAccountsResponse> processAccounts(
    List<FinServ__FinancialAccount__c> listOfFinAccounts
  ) {
    // Common logic here (Steps 2-4)
    //Step 2: Identify the accounts with child cases
    Set<Id> accountIds = ListUtil.getIds(
      listOfFinAccounts,
      FinServ__FinancialAccount__c.Id
    );
    Set<Id> accountsWithCases = AccountClosureWizardControllerHelper.getAccountsWithChildCases(
      accountIds
    );
    //Step 3: Remove accounts that already have cases linked to them
    accountIds.removeAll(accountsWithCases);
    List<FinServ__FinancialAccount__c> listOfFilteredFinAccounts = ACCOUNT_CLOSURE_REPOSITORY.fetchFinancialAccounts(
      accountIds
    );
    //Step 4: Prepare response for UI
    return AccountClosureWizardControllerHelper.prepareFinancialAccountsResponse(
      listOfFilteredFinAccounts
    );
  }
}