force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Deliquent</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FinServ__FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccount__c</fullName>
    <complianceGroup>Integrity - Accurate</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SLA_Status__c.field-meta.xml
<CustomField>
    <fullName>SLA_Status__c</fullName>
    <complianceGroup>Source_Salesforce;Integrity_Accurate;Privacy_Non_Personal_Information</complianceGroup>
    <description>This field describes the current SLA status of a case.</description>
    <label>SLA Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Warning</fullName>
                <color>#FF9900</color>
                <label>Warning</label>
            </value>
            <value>
                <fullName>Breached</fullName>
                <color>#FF0000</color>
                <label>Breached</label>
            </value>
            <value>
                <fullName>Warning 2</fullName>
                <color>#FF9900</color>
                <label>Warning 2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Account_Key__c.field-meta.xml
<CustomField>
    <fullName>Account_Key__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Field to store unique identifier for a Financial Account record received from OCV</description>
    <externalId>true</externalId>
    <label>Account Key</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__Balance__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Balance__c</fullName>
    <complianceGroup>Source_CTM;Integrity - Highly Trusted;Privacy - Personal Information</complianceGroup>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__CurrentPostedBalance__c.field-meta.xml
<CustomField>
    <fullName>FinServ__CurrentPostedBalance__c</fullName>
    <complianceGroup>Source_CTM;Integrity - Highly Trusted</complianceGroup>
    <label>Current Posted Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__FinancialAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccountNumber__c</fullName>
    <complianceGroup>Source_CTM;Integrity_Trusted</complianceGroup>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__PrimaryOwner__c.field-meta.xml
<CustomField>
    <fullName>FinServ__PrimaryOwner__c</fullName>
    <complianceGroup>Integrity - Accurate</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
    <relationshipName>ClientFinancialAccounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <complianceGroup>Integrity_Accurate</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Charge-off</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Paid out</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Number_Of_Signatures__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Signatures__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>The number of signatures required on joint accounts for events requiring additional authorisation.</description>
    <label>Signing Authority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Not Applicable</label>
            </value>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Anyone to Sign</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>All to sign</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Refer to Account Signing Authority</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SigningAuthorityUpdateActionsTest.cls
/**
 * @description       : Test class for SigningAuthUpdateActions class
 * @author            : Sanskriti Routray
 * @group             :
 * @last modified on  : 19-09-2025
 **/
@isTest
public with sharing class SigningAuthorityUpdateActionsTest {
  private static final Id FAKER_ACCOUNT_RECORD_ID = Lib_FakeIdGenerator.getMockId(
    Account.getSObjectType()
  );

  private static final Id FAKER_FIN_ACCOUNT_RECORD_ID = Lib_FakeIdGenerator.getMockId(
    FinServ__FinancialAccount__c.getSObjectType()
  );

  private static final Id FAKER_USER_RECORD_ID = Lib_FakeIdGenerator.getMockId(
    User.getSObjectType()
  );
  private static final Id FAKER_MANAGER_RECORD_ID = Lib_FakeIdGenerator.getMockId(
    User.getSObjectType()
  );

  private static Lib_MockProvider dmlRepoMock;
  private static Id anzxProfile = CommonUtil.getProfileByName(
      'ANZx Standard User'
    )
    .Id;

  static void registerMocks() {
    dmlRepoMock = Lib_MockProvider.forType(DmlRepository.class);
    Lib_MockProvider.forType(SigningAuthorityUpdateRepository.class)
      .mock('getFinancialAccountsWithCaseId', getFinAccounts());
    Lib_MockProvider.forType(SigningAuthorityUpdateRepository.class)
      .mock('getManagerInfo', getUser());
  }

  private static List<FinServ__FinancialAccount__c> getFinAccounts() {
    List<FinServ__FinancialAccount__c> finAccounts = new List<FinServ__FinancialAccount__c>();
    FinServ__FinancialAccount__c finAccount = new FinServ__FinancialAccount__c();
    finAccount.Name = 'Everyday Account';
    finAccount.FinServ__Balance__c = 400;
    finAccount.FinServ__CurrentPostedBalance__c = 400;
    finAccount.FinServ__Status__c = 'Active';
    finAccount.RecordTypeId = RTFinancialAccount.checkingAccount;
    finAccount.FinServ__PrimaryOwner__c = FAKER_ACCOUNT_RECORD_ID;
    finAccount.Account_Key__c = '123456789';
    finAccount.FinServ__FinancialAccountNumber__c = '123';
    finAccount.Number_Of_Signatures__c = '1';
    finAccount.Id = FAKER_FIN_ACCOUNT_RECORD_ID;
    finAccounts.add(finAccount);
    return finAccounts;
  }

  private static List<Case> getOpenSignAuthCases() {
    List<Case> openCases = new List<Case>();
    Case record = new Case();
    record.RecordTypeId = RTCase.signAuth;
    record.Status = 'Open';
    record.Type = 'Change to All to Sign';
    openCases.add(record);
    return openCases;
  }

  private static List<Case> getOldSignAuthCases() {
    List<Case> openCases = new List<Case>();
    Case record = new Case();
    record.RecordTypeId = RTCase.signAuth;
    record.AccountId = FAKER_ACCOUNT_RECORD_ID;
    record.Status = 'Open';
    record.Type = 'Change to Any to Sign';
    record.FinServ__FinancialAccount__c = FAKER_FIN_ACCOUNT_RECORD_ID;
    openCases.add(record);
    return openCases;
  }

  private static List<User> getManagerUser() {
    List<User> managerUsers = new List<User>();
    User managerUser = new User();
    managerUser.Id = FAKER_MANAGER_RECORD_ID;
    managerUser.FirstName = 'Test';
    managerUser.LastName = 'Manager User';
    managerUser.isActive = true;
    managerUser.ProfileId = anzxProfile;
    managerUsers.add(managerUser);
    return managerUsers;
  }

  private static List<User> getUser() {
    List<User> oldUsers = new List<User>();
    User oldUser = new User();
    oldUser.Id = FAKER_USER_RECORD_ID;
    oldUser.FirstName = 'Test';
    oldUser.LastName = 'User';
    oldUser.isActive = true;
    oldUser.ProfileId = anzxProfile;
    oldUser.ManagerId = getManagerUser()[0].Id;
    oldUsers.add(oldUser);
    return oldUsers;
  }

  @isTest
  private static void testSetSubject() {
    registerMocks();
    List<Case> records = getOpenSignAuthCases();
    Test.startTest();
    SigningAuthorityUpdateActions.setSubject(records);
    Test.stopTest();
    Assert.isTrue(
      records[0].Subject == 'Signing Authority Update ',
      'Case subject should be default value - Signing Authority Update '
    );
  }

  @isTest
  private static void testSetSubjectForUpdate() {
    registerMocks();
    List<Case> records = getOpenSignAuthCases();
    records[0].FinServ__FinancialAccount__c = FAKER_FIN_ACCOUNT_RECORD_ID;

    Test.startTest();
    SigningAuthorityUpdateActions.setSubject(records);
    Test.stopTest();
    Assert.isTrue(
      records[0].Subject == 'Signing Authority Update - 123',
      'Case subject should be default value - Signing Authority Update + account number'
    );
  }

  @isTest
  private static void testDereferenceFA() {
    List<Case> records = getOpenSignAuthCases();
    records[0].FinServ__FinancialAccount__c = FAKER_FIN_ACCOUNT_RECORD_ID;
    List<Case> oldRecords = getOldSignAuthCases();
    Test.startTest();
    SigningAuthorityUpdateActions.dereferenceFA(
      records,
      new Map<Id, Case>{ records[0].Id => oldRecords[0] }
    );
    Test.stopTest();
    Assert.isTrue(
      records[0].FinServ__FinancialAccount__c == null,
      'Financial Account on Case should be removed when there is a change in Type'
    );
  }

  @isTest
  private static void testCaseEscalationUpdate() {
    registerMocks();
    List<Case> records = getOpenSignAuthCases();
    records[0].SLA_Status__c = 'Breached';
    records[0].OwnerId = getUser()[0].Id;
    String managerId = getManagerUser()[0].Id;
    List<Case> oldRecords = getOldSignAuthCases();
    Test.startTest();
    SigningAuthorityUpdateActions.caseEscalationUpdate(
      records,
      new Map<Id, Case>{ records[0].Id => oldRecords[0] }
    );
    Test.stopTest();
    Assert.isTrue(
      records[0].OwnerId == managerId,
      'Case Owner should be updated to Case Owner Manager when SLA Status is Breached'
    );
  }
}