force-app/main/default/objects/Account/fields/FinServ__KYCStatus__c.field-meta.xml
<CustomField>
    <fullName>FinServ__KYCStatus__c</fullName>
    <label>KYC Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>NO STATUS ISSUED</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
                <label>Complete</label>
            </value>
            <value>
                <fullName>NE</fullName>
                <label>New</label>
            </value>
            <value>
                <fullName>OB</fullName>
                <label>Obsolete</label>
            </value>
            <value>
                <fullName>PC</fullName>
                <label>Partially Complete</label>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Completed - Invalid</fullName>
            </value>
            <value>
                <fullName>Completed - Valid</fullName>
            </value>
            <value>
                <fullName>In Queue</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Deliquent</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Source_System_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_System_Name__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Source System Name of Party received from OCV (E.g. CAP)</description>
    <externalId>true</externalId>
    <label>Source System Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Needs_Analysis__c/Needs_Analysis__c.object-meta.xml
<CustomObject>
    <description>This is used to store Needs Analysis</description>
    <label>Needs Analysis</label>
    <nameField>
        <displayFormat>NA-{000000}</displayFormat>
        <label>Needs Analysis No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Needs Analysis</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Needs_Analysis__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non-Sensitive Personal Information;Source - Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Parent Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Needs Analysis</relationshipLabel>
    <relationshipName>Needs_Analysis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ccrm/CommercialNeedsAnalysisTriggerTest.cls
/**
 * @author       : Mildeep Singh
 * @since        : Sept 2025
 * @description  : This is the handler class for CommercialNeedsAnalysisTrigger
 **/
@isTest
public with sharing class CommercialNeedsAnalysisTriggerTest {
  @isTest
  static void beforeInsertTest() {
    //GIVEN records
    Account accRecord = new Account(
      Name = 'Sample Account',
      OCV_ID__c = 'OCV7861',
      FinServ__KYCStatus__c = 'Completed - Valid',
      FinServ__Status__c = 'Active',
      RecordTypeId = RTAccount.businessAccount,
      Source_System_Name__c = System.Label.CCRM_Source_System_Name
    );
    insert accRecord;

    Opportunity oppRecord = new Opportunity(
      Name = 'Test Opp ',
      Accountid = accRecord.id,
      StageName = 'New',
      CloseDate = DateTimeUtils.getNextWeekdayDate(3),
      Description = '987654321',
      RecordTypeId = RTOpportunity.commercialOpportunity
    );
    insert oppRecord;

    List<Needs_Analysis__c> naRecords = new List<Needs_Analysis__c>{
      new Needs_Analysis__c(
        RecordTypeId = RTNeedsAnalysis.transactionalBankingNeedsAnalysis,
        Opportunity__c = oppRecord.Id
      )
    };

    //WHEN calling a method
    Test.startTest();
    insert naRecords;
    Test.stopTest();

    //Assert is should not throw an error
    Assert.areEqual(
      1,
      naRecords.size(),
      'Record should be inserted successfully'
    );
  }
}