force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Deliquent</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Prospect__c.field-meta.xml
<CustomField>
    <fullName>Is_Prospect__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Flag to indicate Account is prospect or not.</description>
    <formula>(RecordType.DeveloperName = &apos;Business_Account&apos; || IsPersonAccount) &amp;&amp;
ISPICKVAL(FinServ__Status__c, &apos;Prospect&apos;) &amp;&amp;
Source_System_Name__c = $Label.CCRM_Source_System_Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Prospect</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Source_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_System_ID__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Source System Id of Party received from OCV</description>
    <label>Source System ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Source_System_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_System_Name__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Source System Name of Party received from OCV (E.g. CAP)</description>
    <externalId>true</externalId>
    <label>Source System Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active_To__c.field-meta.xml
<CustomField>
    <fullName>Active_To__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Contact end date.</description>
    <label>Active To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Occurrence_Number__c.field-meta.xml
<CustomField>
    <fullName>Occurrence_Number__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - OCV</complianceGroup>
    <description>Commercial customer&apos;s contact occurrence number.</description>
    <label>Occurrence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>The OCV linked to the Party</description>
    <encryptionScheme>None</encryptionScheme>
    <label>OCV ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Hidden.recordType-meta.xml
<RecordType>
    <fullName>Hidden</fullName>
    <active>true</active>
    <description>Hide contacts when contact details deleted from contact and Active To date populated</description>
    <label>Hidden</label>
</RecordType>

force-app/main/default/objects/Customer_Profile_Updates__c/Customer_Profile_Updates__c.object-meta.xml
<CustomObject>
    <description>This custom object is a staging object which will store the changes made by the bankers on Account and all Contact Point objects.</description>
    <label>Pending Updates to Customer Details</label>
    <nameField>
        <label>Customer Profile Updates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pending Updates to Customer Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Occurrence_Number__c.field-meta.xml
<CustomField>
    <fullName>Occurrence_Number__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Source&apos; Occurrence Number.</description>
    <label>Occurrence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/OCV_Id__c.field-meta.xml
<CustomField>
    <fullName>OCV_Id__c</fullName>
    <description>Formula field to refer customer OCV Id</description>
    <formula>Customer_Name__r.OCV_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OCV Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Source_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_System_ID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Associated Customer Records Source System ID</description>
    <formula>Customer_Name__r.Source_System_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source System ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Source_System_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_System_Name__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Associated Customer Records Source System Name.</description>
    <formula>Customer_Name__r.Source_System_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source System Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ccrm/CCRMContactActionsTest.cls
/**
 * @author Tan Phan
 * @since 11/2022
 * @description Test class for {@link CCRMContactActions}
 */
@IsTest
private class CCRMContactActionsTest {
  static Faker faker = new Faker('AU');

  @TestSetup
  static void makeData() {
    System.runAs(CCRMTestDataFactory.getAdminUser()) {
      Account acc = CCRMTestDataFactory.createProspectBusinessAccount(
        CCRMTestDataFactory.getCCRMBaseUser().Id
      );
    }
  }

  @IsTest
  static void testTrackProspectChanges() {
    //GIVEN Contact record linked to a prospect customer
    Contact contact = [
      SELECT Id, FirstName
      FROM Contact
      WHERE Account.Is_Prospect__c = TRUE
      LIMIT 1
    ];

    //WHEN That contact is updated
    Test.startTest();
    System.runAs(CCRMTestDataFactory.getCCRMBaseUser()) {
      contact.FirstName = contact.FirstName + faker.person.firstName();
      contact.Occurrence_Number__c = faker.randomInteger(2);
      update contact;
    }
    Test.stopTest();

    //THEN a customer profile update record is created
    System.assertEquals(
      1,
      [SELECT COUNT() FROM Customer_Profile_Updates__c],
      'Customer_Profile_Updates__c record should be created when contact is updated'
    );
  }

  @IsTest
  static void testCheckMaxContactsPerOrganisation() {
    //GIVEN a prospect with 10 contacts
    Account prospect = [
      SELECT Id
      FROM Account
      WHERE Is_Prospect__c = TRUE
      LIMIT 1
    ];
    List<Contact> contacts = new List<Contact>();
    for (Integer i = 0; i < 9; i++) {
      contacts.add(
        new Contact(
          LastName = faker.person.lastName(),
          AccountId = prospect.Id,
          Phone = faker.person.phone(true, false)
        )
      );
    }
    insert contacts;

    //WHEN banker adds another contact to the same prospect
    Contact newContact = new Contact(AccountId = prospect.Id);
    Test.startTest();
    System.runAs(CCRMTestDataFactory.getCCRMBaseUser()) {
      CCRMContactActions.checkMaxContactsPerOrganisation(
        new List<Contact>{ newContact }
      );
    }
    Test.stopTest();

    //THEN the contact won't be added
    System.assert(
      newContact.hasErrors(),
      'Banker should not be able to add more than 10 contacts to a prospect'
    );
  }

  @IsTest
  static void testContactEndDate() {
    //GIVEN
    List<Contact> contactList = CCRMTestDataFactory.createContacts(5, true);

    //WHEN
    for (Contact contact : contactList) {
      contact.MobilePhone = '';
      contact.Phone = '';
      contact.Fax = '';
    }
    update contactList;

    //THEN
    List<Contact> contacts = [
      SELECT Active_To__c, RecordTypeId
      FROM Contact
      WHERE Email = :'testenddate@anz.com'
    ];
    for (Contact record : contacts) {
      System.assertEquals(
        record.Active_To__c,
        System.today(),
        'Contact end date updated to today date'
      );
      System.assertEquals(
        record.RecordTypeId,
        CCRMConstants.CONTACT_HIDDEN_RT_ID,
        'Contact record type changed to Hidden'
      );
    }
  }

  @IsTest
  static void testContactEndDateShouldNotPopulate() {
    //GIVEN: Contacts created without Mobile, Fax and Phone
    List<Contact> contactList = CCRMTestDataFactory.createContacts(5, false);

    //WHEN: Update contact Title
    for (Contact contact : contactList) {
      contact.Title = 'Prof';
    }
    update contactList;

    //THEN: Active To date should not populated abd record type do not change
    List<Contact> contacts = [
      SELECT Active_To__c, RecordTypeId
      FROM Contact
      WHERE Email = :'testenddate@anz.com'
    ];
    for (Contact record : contacts) {
      System.assertEquals(
        record.Active_To__c,
        null,
        'Contact end date NOT updated to today date'
      );
      System.assertEquals(
        record.RecordTypeId,
        CCRMConstants.CONTACT_BUSINESS_RT_ID,
        'Contact record type remain unchanged to Business'
      );
    }
  }

  @IsTest
  static void testContactEndDateWhenPhoneAndFaxAreNullAndMobileWithValue() {
    //GIVEN: Contacts created without Mobile, Fax and Phone
    Faker faker = new Faker('AU');
    Account accnt = new Account();
    accnt.Name = faker.randomString(10);
    accnt.OCV_ID__c = faker.randomString(10);
    accnt.RecordTypeId = CCRMConstants.ACCOUNT_ORGANISATION_BUSINESS_RT_ID;
    accnt.Phone = faker.person.phone(true, false);
    accnt.Source_System_ID__c = 'BUS1234';
    accnt.Source_System_Name__c = System.Label.CCRM_Source_System_Name;
    accnt.FinServ__Status__c = 'Active';
    insert accnt;

    List<Contact> contactList = new List<Contact>();
    Integer count = 5;
    for (Integer i = 1; i <= count; i++) {
      Contact contact = new Contact();
      contact.FirstName = faker.person.firstName();
      contact.LastName = faker.randomString(10);
      contact.Email = 'testenddate@anz.com';
      contact.MobilePhone = faker.person.phone(true, true);
      contact.AccountId = accnt.Id;
      contactList.add(contact);
    }
    insert contactList;

    //WHEN: Update contact Title
    for (Contact contact : contactList) {
      contact.MobilePhone = '';
    }
    update contactList;

    //THEN: Active To date should not populated abd record type do not change
    List<Contact> contacts = [
      SELECT Active_To__c, RecordTypeId
      FROM Contact
      WHERE Email = :'testenddate@anz.com'
    ];
    for (Contact record : contacts) {
      System.assertEquals(
        record.Active_To__c,
        System.today(),
        'Contact end date updated to today date'
      );
      System.assertEquals(
        record.RecordTypeId,
        CCRMConstants.CONTACT_HIDDEN_RT_ID,
        'Contact record type changed to Hidden'
      );
    }
  }
}