force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Deliquent</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__FinancialAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccountNumber__c</fullName>
    <complianceGroup>Source_CTM;Integrity_Trusted</complianceGroup>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <complianceGroup>Integrity_Accurate</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Charge-off</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Paid out</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <formula>FinServ__PrimaryOwner__r.OCV_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OCV_ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Calculates if account ownership is single or multiparty</description>
    <formula>IF(Additional_Owner_Count__c  &gt;= 1,&quot;Multi-party&quot;, &quot;Single&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ownership</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/FinServ__FinancialAccountRole__c.object-meta.xml
<CustomObject>
    <description>Represents the role occupied by a person or organizational entity that is involved with a financial account, such as a beneficiary or trustee.</description>
    <label>Financial Account Role</label>
    <nameField>
        <displayFormat>FAR-{000000000}</displayFormat>
        <label>Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__Active__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Active__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy - Personal Information</complianceGroup>
    <defaultValue>true</defaultValue>
    <description>Indicates whether the organizational entity or person currently occupies this role.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy - Personal Information</complianceGroup>
    <description>Financial account that this role is related to.</description>
    <label>Financial Account</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelatedAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the organizational entity that is involved with the financial account.</description>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>This field holds the Ownership of the of the customer for the Financial Account</description>
    <formula>FinServ__FinancialAccount__r.Ownership__c</formula>
    <label>Ownership</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/services/FinancialAccountService.cls
/**
 * @author Shivam Swaraj
 * @since September 2023
 * @description Helper class for financial accounts DML operations.
 */
public with sharing class FinancialAccountService {
  /**
   * @description fetch financial accounts based on the financial account status
   * @param ocvId String containing reason to replace the card
   * @param statusList List of status to fetch the financial accounts
   * @return List<FinServ__FinancialAccount__c> List of FinancialAccounts based on status
   */
  public static List<FinServ__FinancialAccount__c> fetchFinancialAccountsByStatus(
    String ocvId,
    List<String> statusList
  ) {
    //fetching the financial account details which are not closed for the ocv id.
    List<FinServ__FinancialAccount__c> financialAccountList;
    String financialAccountQuery = 'SELECT FinServ__FinancialAccountNumber__c,Ownership__c, FinServ__Status__c from FinServ__FinancialAccount__c WHERE Id IN (Select FinServ__FinancialAccount__c from FinServ__FinancialAccountRole__c WHERE FinServ__RelatedAccount__r.OCV_ID__c =:ocvId AND FinServ__Active__c =true)';

    if (statusList != null && !statusList.isEmpty()) {
      financialAccountQuery += ' AND FinServ__Status__c IN :statusList';
    }

    if (PermissionUtils.canQuery('FinServ__FinancialAccount__c')) {
      financialAccountList = Database.query(financialAccountQuery);
    }
    return financialAccountList;
  }

  /**
   * @description fetch financial accounts numbers list based on the financial account list received based on status
   * @param financialAccountList List of financial accounts filtered based on status
   * @return  List<String>  List of FinancialAccounts Account Number based on financial accounts list received.
   */
  public static Map<String, List<String>> getAccountNumbersByStatusMap(
    List<FinServ__FinancialAccount__c> financialAccountList
  ) {
    Map<String, List<String>> accountNumbersByStatusMap = new Map<String, List<String>>();

    //creating map of list of account numbers by status
    for (FinServ__FinancialAccount__c finAcc : financialAccountList) {
      if (!accountNumbersByStatusMap.containsKey(finAcc.FinServ__Status__c)) {
        accountNumbersByStatusMap.put(
          finAcc.FinServ__Status__c,
          new List<String>()
        );
      }
      accountNumbersByStatusMap.get(finAcc.FinServ__Status__c)
        .add(finAcc.FinServ__FinancialAccountNumber__c);
    }
    return accountNumbersByStatusMap;
  }
}