force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Deliquent</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__FinancialAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccountNumber__c</fullName>
    <complianceGroup>Source_CTM;Integrity_Trusted</complianceGroup>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__PrimaryOwner__c.field-meta.xml
<CustomField>
    <fullName>FinServ__PrimaryOwner__c</fullName>
    <complianceGroup>Integrity - Accurate</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
    <relationshipName>ClientFinancialAccounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <complianceGroup>Integrity_Accurate</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Charge-off</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Paid out</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <formula>FinServ__PrimaryOwner__r.OCV_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OCV_ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Source_System_Status__c.field-meta.xml
<CustomField>
    <fullName>Source_System_Status__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - OCV</complianceGroup>
    <description>Financial account status as available in source system</description>
    <label>Source System Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
                <label>Active</label>
            </value>
            <value>
                <fullName>CACHE01</fullName>
                <label>CACHE01 - New</label>
            </value>
            <value>
                <fullName>CACHE03</fullName>
                <label>CACHE03 - Stagnant</label>
            </value>
            <value>
                <fullName>CACHE05</fullName>
                <label>CACHE05 - Dormant</label>
            </value>
            <value>
                <fullName>CACHE06</fullName>
                <label>CACHE06 - Escheatable</label>
            </value>
            <value>
                <fullName>CACHE07</fullName>
                <label>CACHE07 - Closed</label>
            </value>
            <value>
                <fullName>CACHE08</fullName>
                <label>CACHE08 - Purgeable</label>
            </value>
            <value>
                <fullName>CACHE09</fullName>
                <label>CACHE09 - Active</label>
            </value>
            <value>
                <fullName>CACHE11</fullName>
                <label>CACHE11 - Matured CD</label>
            </value>
            <value>
                <fullName>CACHE12</fullName>
                <label>CACHE12 - Ready to close</label>
            </value>
            <value>
                <fullName>CAPCIS01</fullName>
                <label>CAPCIS01 - New</label>
            </value>
            <value>
                <fullName>CAPCIS03</fullName>
                <label>CAPCIS03 - Inactive</label>
            </value>
            <value>
                <fullName>CAPCIS05</fullName>
                <label>CAPCIS05 - Dormant</label>
            </value>
            <value>
                <fullName>CAPCIS06</fullName>
                <label>CAPCIS06 - Unclaimed moneys</label>
            </value>
            <value>
                <fullName>CAPCIS07</fullName>
                <label>CAPCIS07 - Closed</label>
            </value>
            <value>
                <fullName>CAPCIS08</fullName>
                <label>CAPCIS08 - Purgeable</label>
            </value>
            <value>
                <fullName>CAPCIS11</fullName>
                <label>CAPCIS11 - Matured not renewable</label>
            </value>
            <value>
                <fullName>CAPCIS12</fullName>
                <label>CAPCIS12 - In process of close</label>
            </value>
            <value>
                <fullName>CAPCIS8</fullName>
                <label>CAPCIS8 - Closed (12 months with zero balance and activity)</label>
            </value>
            <value>
                <fullName>CAPCIS80</fullName>
                <label>CAPCIS80 - Superannuation Savings account</label>
            </value>
            <value>
                <fullName>CAPCIS82</fullName>
                <label>CAPCIS82 - Superannuation Savings account in process of close</label>
            </value>
            <value>
                <fullName>CAPCIS88</fullName>
                <label>CAPCIS88 - In process of close</label>
            </value>
            <value>
                <fullName>CAPCIS9</fullName>
                <label>CAPCIS9 - Purged</label>
            </value>
            <value>
                <fullName>CAPCIS99</fullName>
                <label>CAPCIS99 - Active</label>
            </value>
            <value>
                <fullName>CAPCISA</fullName>
                <label>CAPCISA - Active</label>
            </value>
            <value>
                <fullName>CAPCISACL</fullName>
                <label>CAPCISACL - Policy In Force, In Claim</label>
            </value>
            <value>
                <fullName>CAPCISACT</fullName>
                <label>CAPCISACT - Active</label>
            </value>
            <value>
                <fullName>CAPCISBNK</fullName>
                <label>CAPCISBNK - Bankrupt (personal loans only)</label>
            </value>
            <value>
                <fullName>CAPCISBYP</fullName>
                <label>CAPCISBYP - Bypass the account for loans batch processing</label>
            </value>
            <value>
                <fullName>CAPCISC-O</fullName>
                <label>CAPCISC-O - Charged off</label>
            </value>
            <value>
                <fullName>CAPCISOP</fullName>
                <label>CAPCISOP - Open</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/FinServ__FinancialAccountRole__c.object-meta.xml
<CustomObject>
    <description>Represents the role occupied by a person or organizational entity that is involved with a financial account, such as a beneficiary or trustee.</description>
    <label>Financial Account Role</label>
    <nameField>
        <displayFormat>FAR-{000000000}</displayFormat>
        <label>Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__Active__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Active__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy - Personal Information</complianceGroup>
    <defaultValue>true</defaultValue>
    <description>Indicates whether the organizational entity or person currently occupies this role.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy - Personal Information</complianceGroup>
    <description>Financial account that this role is related to.</description>
    <label>Financial Account</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelatedAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the organizational entity that is involved with the financial account.</description>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccountRole__c/fields/FinServ__Role__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Role__c</fullName>
    <complianceGroup>Integrity_Trusted</complianceGroup>
    <description>Role that describes how the organizational entity or person is involved with the financial account.</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Additional Owner</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Advisor</fullName>
            </value>
            <value>
                <fullName>Annuitant</fullName>
            </value>
            <value>
                <fullName>Appoint / Remove Authority</fullName>
            </value>
            <value>
                <fullName>Authorized Agent</fullName>
            </value>
            <value>
                <fullName>Authorized Agent / Beneficial Owner</fullName>
            </value>
            <value>
                <fullName>Authorized Individual</fullName>
            </value>
            <value>
                <fullName>Authorized Signer</fullName>
            </value>
            <value>
                <fullName>Beneficial Owner</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
            <value>
                <fullName>Business Manager</fullName>
            </value>
            <value>
                <fullName>Committee Member</fullName>
            </value>
            <value>
                <fullName>Conservator</fullName>
            </value>
            <value>
                <fullName>Control Person</fullName>
            </value>
            <value>
                <fullName>Corporation</fullName>
            </value>
            <value>
                <fullName>Cosigner</fullName>
            </value>
            <value>
                <fullName>Custodian</fullName>
            </value>
            <value>
                <fullName>Deceased Grantor</fullName>
            </value>
            <value>
                <fullName>Decedent</fullName>
            </value>
            <value>
                <fullName>Discretionary</fullName>
            </value>
            <value>
                <fullName>Foundation</fullName>
            </value>
            <value>
                <fullName>Full Authority</fullName>
            </value>
            <value>
                <fullName>Grantor</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Insured</fullName>
            </value>
            <value>
                <fullName>Interested Party</fullName>
            </value>
            <value>
                <fullName>Joint Owner</fullName>
            </value>
            <value>
                <fullName>Minor Primary Owner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/services/FinancialAccountServiceTest.cls
/**
 * @author Shivam Swaraj
 * @since September 2023
 * @description Test class for FInancialAccountService
 */

@isTest
public with sharing class FinancialAccountServiceTest {
  @TestSetup
  static void setup() {
    Account testAccount = TestDataFactory.createPersonAccount(
      'OCVID887766',
      true
    );
    List<FinServ__FinancialAccount__c> financialAccountsList = TestDataFactory.createFinancialAccount(
      2,
      false
    );
    financialAccountsList[0].FinServ__PrimaryOwner__c = testAccount.Id;
    financialAccountsList[0].FinServ__Status__c = 'Closed';
    financialAccountsList[0].FinServ__FinancialAccountNumber__c = '342490981';
    financialAccountsList[0].Source_System_Status__c = 'CAPCISOP';

    financialAccountsList[1].FinServ__PrimaryOwner__c = testAccount.Id;
    financialAccountsList[1].FinServ__Status__c = 'Closed';
    financialAccountsList[1].FinServ__FinancialAccountNumber__c = '342490982';
    financialAccountsList[1].Source_System_Status__c = 'CAPCISOP';

    insert financialAccountsList;

    FinServ__FinancialAccountRole__c financialAccountRoleRecord = new FinServ__FinancialAccountRole__c(
      FinServ__RelatedAccount__c = testAccount.Id,
      FinServ__FinancialAccount__c = financialAccountsList[0].Id,
      FinServ__Active__c = true,
      Finserv__Role__c = 'Additional Owner'
    );
    insert financialAccountRoleRecord;
  }

  @isTest
  static void testValidFetchFinancialAccountsByStatus() {
    List<String> statusList = new List<String>{
      GetHelpConstants.CLOSED_STATUS
    };

    List<FinServ__FinancialAccount__c> financialAccountList = FinancialAccountService.fetchFinancialAccountsByStatus(
      'OCVID887766',
      statusList
    );
    System.assertEquals(
      2,
      financialAccountList.size(),
      'financialAccountList size should be as expected'
    );
  }

  @isTest
  static void testInValidFetchFinancialAccountsByStatus() {
    List<String> statusList = new List<String>{
      GetHelpConstants.CLOSED_STATUS
    };
    List<FinServ__FinancialAccount__c> financialAccountList = FinancialAccountService.fetchFinancialAccountsByStatus(
      'OCVID88776',
      statusList
    );

    System.assertEquals(
      0,
      financialAccountList.size(),
      'financialAccountList size should be as expected'
    );
  }

  @isTest
  static void testGetAccountNumbersByStatusMap() {
    User coachUser = TestUtil.getUserByFirstName(
      'FinancialAccountTestCoachUser'
    );

    List<FinServ__FinancialAccount__c> financialAccountList = [
      SELECT FinServ__FinancialAccountNumber__c, FinServ__Status__c
      FROM FinServ__FinancialAccount__c
      WHERE FinServ__PrimaryOwner__r.OCV_ID__c = 'OCVID887766'
    ];

    Map<String, List<String>> financialAccountNumbersMapByStatus = FinancialAccountService.getAccountNumbersByStatusMap(
      financialAccountList
    );

    System.assertEquals(
      2,
      financialAccountNumbersMapByStatus.get(GetHelpConstants.CLOSED_STATUS)
        .size(),
      'financialAccountNumberList size should be  as expected'
    );
  }
}