force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Deliquent</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Source_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_System_ID__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Source System Id of Party received from OCV</description>
    <label>Source System ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Source_System_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_System_Name__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Source System Name of Party received from OCV (E.g. CAP)</description>
    <externalId>true</externalId>
    <label>Source System Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/models/AccountModel.cls
/**
 * @author Kopal Goswami
 * @since May 2025
 * @description This class is used for forming customer node data in the AccountModel format
 */
public class AccountModel {
  /**
   * @description Holds id of the account
   */
  public String id { get; set; }
  /**
   * @description Holds ocvId of the account
   */
  public String ocvId { get; set; }
  /**
   * @description Holds sourceSystem of the account
   */
  public String sourceSystem { get; set; }
  /**
   * @description Holds sourceSystemId of the account
   */
  public String sourceSystemId { get; set; }
  /**
   * @description Holds status of the account
   */
  public String status { get; set; }
  /**
   * @description Holds RecordType of the account
   */
  public RecordTypeModal recordType { get; set; }

  /**
   * @description get an instance of AccountModel
   * @param theAccount the Account record
   */
  public AccountModel(Account theAccount) {
    if (theAccount == null) {
      return;
    }
    this.id = theAccount.Id;
    this.ocvId = theAccount.OCV_ID__c;
    this.sourceSystem = theAccount.Source_System_Name__c;
    this.sourceSystemId = theAccount.Source_System_ID__c;

    // This approach is taken to avoid exceptions when accessing fields that haven't been previously queried.
    // This way, it will simply yield null when we try to retrieve a non-existent key.
    Map<String, Object> fldMap = theAccount.getPopulatedFieldsAsMap();
    this.status = (string) fldMap.get('FinServ__Status__c');
    this.recordType = new RecordTypeModal(
      (RecordType) fldMap.get('RecordType')
    );
  }

  /**
   * @description This is a modal class to hold RecordType details of the account in AccountModel
   */
  public class RecordTypeModal {
    /**
     * @description Holds id of the RecordType
     */
    public String recordTypeId { get; set; }
    /**
     * @description Holds name of the RecordType
     */
    public String recordTypeName { get; set; }

    /**
     * @description get an instance of RecordTypeModal
     * @param rt the RecordType record
     */
    public RecordTypeModal(RecordType rt) {
      if (rt == null) {
        return;
      }
      this.recordTypeId = rt.Id;
      this.recordTypeName = rt.DeveloperName;
    }
  }
}