force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactRequest/fields/Appointment_date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Appointment_date_and_Time__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Date and time of the Appointment</description>
    <label>Appointment date and Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Interaction/fields/Interaction_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Interaction_Purpose__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Reason for Interaction</description>
    <inlineHelpText>For Interaction records - select whom the engagement is with, eg customer. For Appointment booking - select the main topic of the appointment, eg financial wellbeing.</inlineHelpText>
    <label>For</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>InteractionType</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ Customer</fullName>
            </value>
            <value>
                <fullName>ANZ Plus Customer</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Digital Support</fullName>
            </value>
            <value>
                <fullName>Existing ANZ Customer</fullName>
            </value>
            <value>
                <fullName>Financial Wellbeing</fullName>
            </value>
            <value>
                <fullName>Non-Customer</fullName>
            </value>
            <value>
                <fullName>Home Loan</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Status of Interaction</description>
    <inlineHelpText>The current status of the chat / appointment.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed &amp; Archived</fullName>
            </value>
            <value>
                <fullName>Closed - Completed</fullName>
            </value>
            <value>
                <fullName>Closed - Follow Up Interaction</fullName>
            </value>
            <value>
                <fullName>Closed - Withdrawn</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Linked</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Not Completed</fullName>
            </value>
            <value>
                <fullName>On Hold (By Coach)</fullName>
            </value>
            <value>
                <fullName>On Hold (By Customer)</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Walk In</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction/recordTypes/Appointment.recordType-meta.xml
<RecordType>
    <fullName>Appointment</fullName>
    <active>true</active>
    <description>Appointment record type for Appointment Booking</description>
    <label>Appointment</label>
</RecordType>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/classes/InteractionInterceptTest.cls
/**
 * @description Test intercept for existing interactions
 * @author Adam Phillip Smith
 * @since 20220527
 */
@isTest
public with sharing class InteractionInterceptTest {
  private static final string FIRST_NAME = 'Fred';
  private static final string LAST_NAME = 'Smith';
  private static final string PHONE_NUMBER = '01189998819991197253';
  private static string appointmentRTName = 'Appointment';

  @isTest
  static void isInterceptInteractions() {
    DateTime startDate = DateTime.newInstance(
      DateTime.now().year(),
      1,
      1,
      12,
      0,
      0
    );
    Account testAccount = createTestAccount();

    string purpose = 'Financial Wellbeing';

    Interaction testInteraction = new Interaction(
      RecordTypeId = GetHelpConstants.INTERACTION_APPT_RT_ID,
      AccountId = testAccount.Id,
      StartTime = startDate,
      Interaction_Purpose__c = purpose
    );
    insert testInteraction;

    testInteraction.Status__c = 'Unassigned';
    update testInteraction;

    test.startTest();
    Interaction testInteraction2 = new Interaction(
      RecordTypeId = GetHelpConstants.INTERACTION_APPT_RT_ID,
      AccountId = testAccount.Id,
      StartTime = startDate,
      Interaction_Purpose__c = purpose
    );
    Exception thrownException;
    try {
      insert testInteraction2;
    } catch (Exception exc) {
      thrownException = exc;
    }
    test.stopTest();
    System.assertEquals(
      null,
      testInteraction2.Id,
      'ID must not be set as this means it exists'
    );

    System.assertNotEquals(
      null,
      thrownException,
      'An exception should have occured as the customer should not have two interactions booked at the same time'
    );

    thrownException = null;
    testInteraction.Status__c = 'Scheduled';
    update testInteraction;

    try {
      insert testInteraction2;
    } catch (Exception exc) {
      thrownException = exc;
    }
    System.assertEquals(
      null,
      testInteraction2.Id,
      'ID must not be set as this means it exists'
    );

    System.assertNotEquals(
      null,
      thrownException,
      'An exception should have occured as the customer should not have two interactions booked at the same time'
    );

    thrownException = null;
    testInteraction.Status__c = 'Rescheduled';
    update testInteraction;

    try {
      insert testInteraction2;
    } catch (Exception exc) {
      thrownException = exc;
    }
    System.assertEquals(
      null,
      testInteraction2.Id,
      'ID must not be set as this means it exists'
    );

    System.assertNotEquals(
      null,
      thrownException,
      'An exception should have occured as the customer should not have two interactions booked at the same time'
    );

    thrownException = null;
    testInteraction.Status__c = 'Walk In';
    update testInteraction;

    try {
      insert testInteraction2;
    } catch (Exception exc) {
      thrownException = exc;
    }
    System.assertEquals(
      null,
      testInteraction2.Id,
      'ID must not be set as this means it exists'
    );

    System.assertNotEquals(
      null,
      thrownException,
      'An exception should have occured as the customer should not have two interactions booked at the same time'
    );

    thrownException = null;
    testInteraction.Status__c = 'Cancelled';
    update testInteraction;

    try {
      insert testInteraction2;
    } catch (Exception exc) {
      thrownException = exc;
    }
    System.assertNotEquals(
      null,
      testInteraction2.Id,
      'ID must be set as this means it exists'
    );

    System.assertEquals(
      null,
      thrownException,
      'No exception should have occured as the customer should can have two interactions booked at the same time if one is cancelled'
    );

    ContactRequest request = new ContactRequest(
      WhoId = testAccount.PersonContactId,
      Appointment_date_and_Time__c = startDate,
      RequestReason = purpose
    );

    thrownException = null;
    try {
      insert request;
    } catch (Exception exc) {
      thrownException = exc;
    }

    System.assertEquals(
      null,
      request.Id,
      'ID must not be set as this means it exists'
    );

    System.assertNotEquals(
      null,
      thrownException,
      'An exception should have occured as the customer should not have two interactions booked at the same time'
    );
  }

  /**
   * @description helper method to create a person account
   * @return Account a Person Account with Name Fred Smith, OCV ID 123456
   */
  static Account createTestAccount() {
    Faker faker = new Faker('AU');
    Id personAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
      .get('PersonAccount')
      .getRecordTypeId();
    Account testAccount = new Account();
    testAccount.FirstName = FIRST_NAME;
    testAccount.LastName = LAST_NAME;
    testAccount.OCV_ID__c = faker.randomString(10);
    testAccount.PersonMobilePhone = PHONE_NUMBER;
    testAccount.RecordTypeId = personAccountRecordTypeId;
    insert testAccount;

    testAccount = [
      SELECT Id, PersonContactId, PersonMobilePhone
      FROM Account
      WHERE Id = :testAccount.Id
    ];

    return testAccount;
  }
}