force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ResidentialLoanApplication/fields/Settlement_ID__c.field-meta.xml
<CustomField>
    <fullName>Settlement_ID__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy_Non_Personal_Information;Source - Loan Domain</complianceGroup>
    <description>Settlement ID from loan domain</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Settlement ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <description>Contains settlement details related to a residential loan application</description>
    <label>Settlement</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Settlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Settlement__c/fields/Loan_Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application_Number__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Settlement_Domain</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Loan Application ID</description>
    <label>Loan Application Number</label>
    <referenceTo>ResidentialLoanApplication</referenceTo>
    <relationshipLabel>Settlements</relationshipLabel>
    <relationshipName>Settlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Settlement__c/fields/Settlement_ID__c.field-meta.xml
<CustomField>
    <fullName>Settlement_ID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Settlement_Domain</complianceGroup>
    <description>Immutable field representing the ID of the parent Settlement entity.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Settlement Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/sf-lending/classes/repository/SettlementRepository.cls
/**
 * @author Peter Charalambous
 * @since Tue Jun 03 2025
 * @description SettlementRepository is a repository class for settlement related queries
 */
public with sharing class SettlementRepository {
  /**
   * @description Retrieves a settlement record by its ID
   * @param recordId The ID of the settlement record to retrieve
   * @return `Settlement__c` The settlement record
   */
  public Settlement__c getSettlement(String recordId) {
    PermissionUtils.canQuery('Settlement__c');

    return [
      SELECT Id, Settlement_ID__c, Loan_Application_Number__r.Account.OCV_ID__c
      FROM Settlement__c
      WHERE Id = :recordId
    ];
  }
}