force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CustomerOnboardingApplication__c.field-meta.xml
<CustomField>
    <fullName>CustomerOnboardingApplication__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup relationship field that looks up to the Customer Onboarding Application object</description>
    <label>Customer Onboarding Application</label>
    <referenceTo>CustomerOnboardingApplication__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/OCV_Id__c.field-meta.xml
<CustomField>
    <fullName>OCV_Id__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Personal_Information;Source_OCV</complianceGroup>
    <description>OCV ID of the customer</description>
    <externalId>true</externalId>
    <label>OCV Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PersonaId__c.field-meta.xml
<CustomField>
    <fullName>PersonaId__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>The ForgeRock-minted UUID identifying the persona attempting to onboard</description>
    <externalId>true</externalId>
    <label>Persona Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Fraud.recordType-meta.xml
<RecordType>
    <fullName>Fraud</fullName>
    <active>true</active>
    <businessProcess>Fraud Support Process</businessProcess>
    <description>Record a new fraud case for an existing ANZx customer</description>
    <label>Fraud</label>
</RecordType>

force-app/main/default/objects/COBAddress__c/COBAddress__c.object-meta.xml
<CustomObject>
    <description>A structured address compatible with both QAS lookup results and manual entry by the prospect.</description>
    <label>COB Address</label>
    <nameField>
        <displayFormat>COBA-{00000000}</displayFormat>
        <label>COB Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>COB Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/COBAddress__c/fields/AddressType__c.field-meta.xml
<CustomField>
    <fullName>AddressType__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>The type of the address, (e.g. `CURRENT`, `PREVIOUS`, `MAILING`)</description>
    <label>Address Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBAddress__c/fields/CustomerOnboardingApplication__c.field-meta.xml
<CustomField>
    <fullName>CustomerOnboardingApplication__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>Master-Detail relationship field that looks up to the Customer Onboarding Application object</description>
    <label>Customer Onboarding Application</label>
    <referenceTo>CustomerOnboardingApplication__c</referenceTo>
    <relationshipLabel>COB Addresses</relationshipLabel>
    <relationshipName>COBAddresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/COBAddress__c/fields/QASAddress__c.field-meta.xml
<CustomField>
    <fullName>QASAddress__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Temporal</complianceGroup>
    <description>Specify if an address is a QAS address</description>
    <formula>IF(ISBLANK(AddressQASId__c), false, true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QAS Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/COBPrimaryIDDocument__c.object-meta.xml
<CustomObject>
    <description>The details submitted for a primary document (licence or passport), including the original OCR extractions which may have been edited</description>
    <label>COB Primary ID Document</label>
    <nameField>
        <displayFormat>COBPID-{00000000}</displayFormat>
        <label>COB Primary ID Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>COB Primary ID Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/CustomerOnboardingApplication__c.field-meta.xml
<CustomField>
    <fullName>CustomerOnboardingApplication__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>Master-Detail relationship field that looks up to the Customer Onboarding Application object</description>
    <label>Customer Onboarding Application</label>
    <referenceTo>CustomerOnboardingApplication__c</referenceTo>
    <relationshipLabel>COB Primary ID Documents</relationshipLabel>
    <relationshipName>COBPrimaryIDDocuments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/DateOfBirthOCRMatch__c.field-meta.xml
<CustomField>
    <fullName>DateOfBirthOCRMatch__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Flag indicating whether there was any difference between the date of birth OCR and the value submitted by the user</description>
    <label>Date of Birth OCR Match</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/ExpiryDateOCRMatch__c.field-meta.xml
<CustomField>
    <fullName>ExpiryDateOCRMatch__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Flag indicating whether there was any difference between the Expiry Date OCR and the value submitted by the user</description>
    <label>Expiry Date OCR Match</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Temporal</complianceGroup>
    <description>First name as submitted by the user</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/FirstNameOCRMatch__c.field-meta.xml
<CustomField>
    <fullName>FirstNameOCRMatch__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Flag indicating whether there was any difference between the first name OCR and the value submitted by the user</description>
    <label>First Name OCR Match</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/FirstNameOCRServer__c.field-meta.xml
<CustomField>
    <fullName>FirstNameOCRServer__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Temporal</complianceGroup>
    <description>OCR values for First Name</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>First Name OCR Server</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/IdDocumentType__c.field-meta.xml
<CustomField>
    <fullName>IdDocumentType__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>The primary form of ID chosen (licence, passport etc)</description>
    <label>Id Document Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Temporal</complianceGroup>
    <description>Last name as submitted by the user</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/LastNameOCRMatch__c.field-meta.xml
<CustomField>
    <fullName>LastNameOCRMatch__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Flag indicating whether there was any difference between the last name OCR and the value submitted by the user</description>
    <label>Last Name OCR Match</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/LastNameOCRServer__c.field-meta.xml
<CustomField>
    <fullName>LastNameOCRServer__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Temporal</complianceGroup>
    <description>OCR values for Last Name</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Last Name OCR Server</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/LicenceCardNumberOCRMatch__c.field-meta.xml
<CustomField>
    <fullName>LicenceCardNumberOCRMatch__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Flag indicating whether there was any difference between the licence card number OCR and the value submitted by the user</description>
    <label>Licence Card Number OCR Match</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/LicenceNumberOCRMatch__c.field-meta.xml
<CustomField>
    <fullName>LicenceNumberOCRMatch__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Flag indicating whether there was any difference between the licence number OCR and the value submitted by the user</description>
    <label>Licence Number OCR Match</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/MiddleNames__c.field-meta.xml
<CustomField>
    <fullName>MiddleNames__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Temporal</complianceGroup>
    <description>Middle name(s) or initial as submitted by the user</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Middle Names</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/MiddleNamesOCRMatch__c.field-meta.xml
<CustomField>
    <fullName>MiddleNamesOCRMatch__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Flag indicating whether there was any difference between the middle names OCR and the value submitted by the user</description>
    <label>Middle Names OCR Match</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/MiddleNamesOCRServer__c.field-meta.xml
<CustomField>
    <fullName>MiddleNamesOCRServer__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Temporal</complianceGroup>
    <description>OCR values for Middle Names</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Middle Names OCR Server</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COBPrimaryIDDocument__c/fields/PassportNumberOCRMatch__c.field-meta.xml
<CustomField>
    <fullName>PassportNumberOCRMatch__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Flag indicating whether there was any difference between the passport number OCR and the value submitted by the user</description>
    <label>Passport Number OCR Match</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerOnboardingApplication__c/CustomerOnboardingApplication__c.object-meta.xml
<CustomObject>
    <label>Customer Onboarding Application</label>
    <nameField>
        <displayFormat>COB-{00000000}</displayFormat>
        <label>Customer Onboarding Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Onboarding Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerOnboardingApplication__c/fields/OCVId__c.field-meta.xml
<CustomField>
    <fullName>OCVId__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>The OCVID supplied by OCV, which initially refers to the shadow profile and eventually the full customer profile</description>
    <label>OCV Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerOnboardingApplication__c/fields/PersonaId__c.field-meta.xml
<CustomField>
    <fullName>PersonaId__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>The ForgeRock-minted UUID identifying the persona attempting to onboard</description>
    <externalId>true</externalId>
    <label>Persona Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CustomerOnboardingApplication__c/fields/VerificationType__c.field-meta.xml
<CustomField>
    <fullName>VerificationType__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Temporal</complianceGroup>
    <description>String enum indicating the type of verification that the prospect was ultimately onboarded by (Straight-through (STP, ASSISTED or MANUAL)</description>
    <label>Verification Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/COBApplicationActionsHelper.cls
/**
 * @author Batya Aisman Sufrin
 * @since 05/2023
 * @description Helper class for @link COBApplicationActions
 */
public with sharing class COBApplicationActionsHelper {
  public static final Group PENDING_KYC_QA_QUEUE = CommonUtil.getQueueByName(
    'Pending_KYC_QA'
  );
  public static final Map<String, String> VERIFICATION_TYPE_PRIORITY = new Map<String, String>{
    'MANUAL' => 'High',
    'UNSPECIFIED' => 'High',
    'ASSISTED' => 'Medium',
    'STP' => 'Standard'
  };

  @TestVisible
  private static final String YES = 'Yes';
  @TestVisible
  private static final String NONE = null;
  @TestVisible
  private static final String PASS = 'PASS';
  @TestVisible
  private static final String LICENCE = 'Licence';
  @TestVisible
  private static final String PASSPORT = 'Passport';
  @TestVisible
  private static final String VERIFICATION_TYPE_ASSISTED = 'ASSISTED';
  @TestVisible
  private static final String VERIFICATION_TYPE_STP = 'STP';

  /**
   * @description Set KYC QA case base fields
   * @param cobApp Customer Onboarding Application
   * @return Case KYC QA case
   */
  public static Case setKYCQACaseBaseFields(
    CustomerOnboardingApplication__c cobApp
  ) {
    Case kycQACase = new Case(
      RecordTypeId = GetHelpConstants.KYCQA_RT_ID,
      OwnerId = PENDING_KYC_QA_QUEUE.Id,
      CustomerOnboardingApplication__c = cobApp.Id,
      PersonaId__c = cobApp.PersonaId__c,
      OCV_Id__c = cobApp.OCVId__c,
      Priority = VERIFICATION_TYPE_PRIORITY.get(cobApp.VerificationType__c)
    );

    Logger.debug('KYC QA Case with base fields: ' + kycQACase);
    Logger.saveLog();
    return kycQACase;
  }

  /**
   * @description Get Accounts by OCV ids
   * @param ocvIds OCV Ids
   * @return Map<String, Account> Map of OCV ids and Accounts
   */
  public static Map<String, Account> getAccountsByOCVIDs(Set<String> ocvIds) {
    Map<String, Account> accountsByOCVIDs = new Map<String, Account>();

    if (ocvIds.isEmpty()) {
      return accountsByOCVIDs;
    }

    if (PermissionUtils.canQuery('Account')) {
      List<Account> accs = [
        SELECT Id, OCV_ID__c
        FROM Account
        WHERE OCV_ID__c IN :ocvIds
      ];

      for (Account acc : accs) {
        accountsByOCVIDs.put(acc.OCV_ID__c, acc);
      }
    }

    return accountsByOCVIDs;
  }

  /**
   * @description Get PID by  OCV Ids
   * @param ocvIds OCV Ids
   * @return Map<Id, COBPrimaryIDDocument__c> Map of OCV ids and COB Primary ID Documents
   */
  public static Map<String, COBPrimaryIDDocument__c> getCOBPIDsByOCVIds(
    Set<String> ocvIds
  ) {
    if (
      ocvIds.isEmpty() ||
      PermissionUtils.canQuery('COBPrimaryIDDocument__c') == false
    ) {
      return new Map<String, COBPrimaryIDDocument__c>();
    }

    Map<String, COBPrimaryIDDocument__c> cobPIDs = new Map<String, COBPrimaryIDDocument__c>();
    //getting max COB PID records createdDate for each cobAppId
    List<CustomerOnboardingApplication__c> cobApps = [
      SELECT
        OCVId__c,
        (
          SELECT
            Id,
            IdDocumentType__c,
            CustomerOnboardingApplication__c,
            FirstName__c,
            FirstNameOCRServer__c,
            FirstNameOCRMatch__c,
            MiddleNames__c,
            MiddleNamesOCRServer__c,
            MiddleNamesOCRMatch__c,
            LastName__c,
            LastNameOCRServer__c,
            LastNameOCRMatch__c,
            LicenceNumberOCRMatch__c,
            LicenceCardNumberOCRMatch__c,
            PassportNumberOCRMatch__c,
            DateOfBirthOCRMatch__c,
            ExpiryDateOCRMatch__c
          FROM COBPrimaryIDDocuments__r
          ORDER BY CreatedDate DESC
        )
      FROM CustomerOnboardingApplication__c
      WHERE OCVId__c IN :ocvIds
    ];

    for (CustomerOnboardingApplication__c cobApp : cobApps) {
      if (!cobApp.COBPrimaryIDDocuments__r.isEmpty()) {
        cobPIDs.put(cobApp.OCVId__c, cobApp.COBPrimaryIDDocuments__r[0]);
      }
    }

    Logger.debug('COB Primary ID Documents: ' + cobPIDs);
    Logger.saveLog();
    return cobPIDs;
  }

  /**
   * @description Get COB Address by AddressType
   * @param ocvIds  OCV id
   * @param addressType  Address Type
   * @return getCOBAddressByAddressType COB Address
   */
  public static Map<String, COBAddress__c> getCOBAddressByOCVIdAddressType(
    Set<String> ocvIds,
    String addressType
  ) {
    if (
      ocvIds.isEmpty() || PermissionUtils.canQuery('COBAddress__c') == false
    ) {
      return new Map<String, COBAddress__c>();
    }

    Map<String, COBAddress__c> cobAppIdAddresses = new Map<String, COBAddress__c>();
    List<CustomerOnboardingApplication__c> cobApps = [
      SELECT
        OCVId__c,
        (
          SELECT Id, CustomerOnboardingApplication__c, QASAddress__c
          FROM COBAddresses__r
          WHERE AddressType__c = :addressType
          ORDER BY CreatedDate DESC
        )
      FROM CustomerOnboardingApplication__c
      WHERE OCVId__c IN :ocvIds
    ];

    for (CustomerOnboardingApplication__c cobApp : cobApps) {
      if (!cobApp.COBAddresses__r.isEmpty()) {
        cobAppIdAddresses.put(cobApp.OCVId__c, cobApp.COBAddresses__r[0]);
      }
    }

    Logger.debug('COB Addressess: ' + cobAppIdAddresses);
    Logger.saveLog();

    return cobAppIdAddresses;
  }

  /**
   * @description Populate Fraud Customer Details test result
   * @param cobApp  COB Application
   * @param cobPrimaryIDDocument  COB Primary ID Document
   * @return Fraud Customer Details result
   */
  public static String populateFraudCustomerDetails(
    CustomerOnboardingApplication__c cobApp,
    COBPrimaryIDDocument__c cobPrimaryIDDocument
  ) {
    Logger.debug('Verification Type: ' + cobApp.VerificationType__c);
    Logger.debug(
      'Does Licence Match: ' + doesLicenceMatch(cobPrimaryIDDocument)
    );
    Logger.debug(
      'Does Passport Match: ' + doesPassportMatch(cobPrimaryIDDocument)
    );
    Logger.debug(
      'Does Full Name Match: ' + doesFullNameMatch(cobPrimaryIDDocument)
    );
    Logger.debug(
      'Date Of Birth OCR Match: ' + cobPrimaryIDDocument.DateOfBirthOCRMatch__c
    );
    Logger.debug(
      'Expiry Date OCR Match: ' + cobPrimaryIDDocument.ExpiryDateOCRMatch__c
    );
    Logger.saveLog();

    if (
      (cobApp.VerificationType__c == VERIFICATION_TYPE_STP ||
      cobApp.VerificationType__c == VERIFICATION_TYPE_ASSISTED)
    ) {
      if (
        doesLicenceMatch(cobPrimaryIDDocument) ||
        doesPassportMatch(cobPrimaryIDDocument)
      ) {
        return YES;
      } else {
        return NONE;
      }
    } else if (
      doesFullNameMatch(cobPrimaryIDDocument) &&
      cobPrimaryIDDocument.DateOfBirthOCRMatch__c &&
      cobPrimaryIDDocument.ExpiryDateOCRMatch__c &&
      (doesLicenceMatch(cobPrimaryIDDocument) ||
      doesPassportMatch(cobPrimaryIDDocument))
    ) {
      return YES;
    }
    return NONE;
  }

  /**
   * @description Populate Middle Name Check test result
   * @param cobPid  COB Primary ID Document
   * @return Middle Name Check result
   */
  public static String populateMiddleNameCheck(COBPrimaryIDDocument__c cobPid) {
    Logger.debug(
      'Are First And Last Names OCR Server Blank: ' +
      areFirstAndLastNamesOCRServerBlank(cobPid)
    );
    Logger.debug('Does Midddle Names Match: ' + doMiddleNamesMatch(cobPid));
    Logger.debug('Does Full Name Match: ' + doesFullNameMatch(cobPid));
    Logger.debug('Does Licence Match: ' + doesLicenceMatch(cobPid));
    Logger.debug('Does Passport Match: ' + doesPassportMatch(cobPid));
    Logger.saveLog();

    if (areFirstAndLastNamesOCRServerBlank(cobPid)) {
      return NONE;
    } else if (doMiddleNamesMatch(cobPid)) {
      return YES;
    } else if (
      doesFullNameMatch(cobPid) &&
      (doesLicenceMatch(cobPid) || doesPassportMatch(cobPid))
    ) {
      return YES;
    }

    return NONE;
  }

  @TestVisible
  private static Boolean areFirstAndLastNamesOCRServerBlank(
    COBPrimaryIDDocument__c cobPid
  ) {
    return String.isBlank(cobPid.FirstNameOCRServer__c) &&
      String.isBlank(cobPid.LastNameOCRServer__c);
  }

  @TestVisible
  private static Boolean doMiddleNamesMatch(COBPrimaryIDDocument__c cobPid) {
    return cobPid.MiddleNamesOCRMatch__c &&
      String.isNotBlank(cobPid.MiddleNamesOCRServer__c);
  }

  @TestVisible
  private static Boolean doesFullNameMatch(COBPrimaryIDDocument__c cobPid) {
    String cobPIDDFullName = CommonUtil.buildTrimmedConcatenatedString(
      new List<String>{
        cobPid.FirstName__c,
        cobPid.MiddleNames__c,
        cobPid.LastName__c
      }
    );
    String cobPIDDFullNameOCRServer = CommonUtil.buildTrimmedConcatenatedString(
      new List<String>{
        cobPid.FirstNameOCRServer__c,
        cobPid.MiddleNamesOCRServer__c,
        cobPid.LastNameOCRServer__c
      }
    );

    return cobPIDDFullName.equalsIgnoreCase(cobPIDDFullNameOCRServer);
  }

  @TestVisible
  private static Boolean doesLicenceMatch(COBPrimaryIDDocument__c cobPid) {
    return cobPid.IdDocumentType__c == LICENCE &&
      cobPid.LicenceNumberOCRMatch__c;
  }

  @TestVisible
  private static Boolean doesPassportMatch(COBPrimaryIDDocument__c cobPid) {
    return cobPid.IdDocumentType__c == PASSPORT &&
      cobPid.PassportNumberOCRMatch__c;
  }
}