force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LoanApplicant/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to account</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loan Application</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LoanApplicant/fields/OCV_Id__c.field-meta.xml
<CustomField>
    <fullName>OCV_Id__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Personal Information;Source - OCV</complianceGroup>
    <description>Link to customer page</description>
    <formula>HYPERLINK(&quot;/&quot; &amp;  Account__c , Account__r.OCV_ID__c, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settlement_Account__c/Settlement_Account__c.object-meta.xml
<CustomObject>
    <label>Settlement Account</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>Settlement Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Settlement_Account__c/fields/Loan_Application_Id__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application_Id__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source_Settlement_Domain</complianceGroup>
    <description>Residential Loan Application number</description>
    <formula>Settlement__r.Loan_Application_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan Application Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settlement_Account__c/fields/Nominated_By__c.field-meta.xml
<CustomField>
    <fullName>Nominated_By__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Settlement_Domain</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Storing Loan Applicant&apos;s reference</description>
    <label>Nominated By</label>
    <referenceTo>LoanApplicant</referenceTo>
    <relationshipLabel>Settlement Accounts</relationshipLabel>
    <relationshipName>Settlement_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Settlement_Account__c/fields/Nominated_By_Id__c.field-meta.xml
<CustomField>
    <fullName>Nominated_By_Id__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Settlement_Domain</complianceGroup>
    <description>The Details of the Party who has added the Account details on the Settlement Account.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Nominated By Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SettlementAccountActions.cls
/**
 * @author Peter Charalambous
 * @since Tue Apr 16 2024
 * @description class for Settlement Account actions
 */
public with sharing class SettlementAccountActions {
  /**
   * @description Find and populate the fields with customer name via ocv id
   * @param records records to populate with customer name
   */
  public static void populateCustomerName(List<Settlement_Account__c> records) {
    List<String> filteredRlaRecords = filterRlaRecords(records);
    updateNominatedBy(records, filteredRlaRecords);
  }

  /**
   * @description Filter records to retrieve the RLA list to query for
   * @param records records to filter
   * @return List<String>
   */
  private static List<String> filterRlaRecords(
    List<Settlement_Account__c> records
  ) {
    List<String> rlaIdList = new List<String>();
    for (Settlement_Account__c settlementAccount : records) {
      rlaIdList.add(settlementAccount.Loan_Application_Id__c);
    }
    return rlaIdList;
  }

  /**
   * @description Update the verified by with customer account name
   * @param records records to populate with customer name
   * @param rlaIdList RLA id list to query for
   */
  private static void updateNominatedBy(
    List<Settlement_Account__c> records,
    List<String> rlaIdList
  ) {
    for (LoanApplicant applicant : [
      SELECT Id, Account__r.OCV_ID__c, LoanApplicationId
      FROM LoanApplicant
      WHERE LoanApplicationId IN :rlaIdList
    ]) {
      //Loop through records and update the values to be the name provided from the loan applicant
      for (Settlement_Account__c settlementAccount : records) {
        //Ensure the Loan Applications are the same as an applicant can be linked to multiple loan apps
        if (
          applicant.LoanApplicationId ==
          settlementAccount.Loan_Application_Id__c &&
          applicant.Account__r.OCV_ID__c == settlementAccount.Nominated_By_Id__c
        ) {
          settlementAccount.Nominated_By__c = applicant.Id;
        }
      }
    }
  }
}