force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ResidentialLoanApplication/fields/SOP_Id__c.field-meta.xml
<CustomField>
    <fullName>SOP_Id__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <description>Application Statement of Position ID</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>SOP Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/sf-lending/classes/BOHController.cls
/**
 * @description controller class for sop page
 * @author raman
 * @since March 2025
 */
public with sharing class BOHController {
  private static final ResidentialLoanApplicationRepository RLA_SOQL_REPOSITORY = (ResidentialLoanApplicationRepository) Lib_InstanceProvider.forType(
    ResidentialLoanApplicationRepository.class
  );
  private static final SOPAPIRepository SOP_API_REPOSITORY = (SOPAPIRepository) Lib_InstanceProvider.forType(
    SOPAPIRepository.class
  );

  /**
   * @description method to invoke getSOP
   * @param loanId
   * @return SOPViewModel for successful getSOP execution
   */
  @AuraEnabled
  public static SOPViewModel getSOP(Id loanId) {
    try {
      ResidentialLoanApplication loanRec = RLA_SOQL_REPOSITORY.queryRLAById(
        loanId
      );
      if (loanRec == null) {
        throw new IllegalArgumentException('Valid Loan Record not found');
      }

      SOPViewModel response = SOP_API_REPOSITORY.getSOP(
        loanRec.Account?.OCV_ID__c,
        loanRec.SOP_Id__c
      );
      response.parties = SOPUpdateSOPandPartyHelper.transformPartiesList(
        response
      );
      return response;
    } catch (Exception e) {
      Logger.info('Failure on Get SOP callout', e);
      Logger.saveLog();
      return null;
    }
  }

  /**
   * @description method to invoke updateSOPAndParty
   * @param sopModel
   * @param loanId
   * @return SOPViewModel for successful updateSOPAndParty exection
   */
  @AuraEnabled
  public static SOPViewModel updateSOPAndParty(
    SOPViewModel sopModel,
    Id loanId
  ) {
    try {
      ResidentialLoanApplication loanRec = RLA_SOQL_REPOSITORY.queryRLAById(
        loanId
      );
      if (loanRec == null) {
        throw new IllegalArgumentException('Valid Loan Record not found');
      }
      List<Object> urlParameters = new List<Object>{
        loanRec.SOP_Id__c,
        sopModel?.isSOPDataUpdated ?? false,
        sopModel?.isPartyDataUpdated ?? false
      };

      SOPUpdateSOPAndPartyRequestModel sopRequestModel = new SOPUpdateSOPAndPartyRequestModel(
        sopModel
      );

      SOPViewModel response = SOP_API_REPOSITORY.updateSOPAndParty(
        loanRec.Account?.OCV_ID__c,
        sopRequestModel,
        urlParameters
      );
      response.parties = SOPUpdateSOPandPartyHelper.transformPartiesList(
        response
      );
      return response;
    } catch (Exception e) {
      Logger.info('Failure on Update SOP And Party callout', e);
      Logger.saveLog();
      return null;
    }
  }
}