force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Account_Key__c.field-meta.xml
<CustomField>
    <fullName>Account_Key__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Field to store unique identifier for a Financial Account record received from OCV</description>
    <externalId>true</externalId>
    <label>Account Key</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__FinancialAccountType__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccountType__c</fullName>
    <complianceGroup>Integrity - Accurate</complianceGroup>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Brokerage</fullName>
            </value>
            <value>
                <fullName>Discount Brokerage</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>Checking</fullName>
            </value>
            <value>
                <fullName>Cash Management Account</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Mutual Fund</fullName>
            </value>
            <value>
                <fullName>Fixed Annuity</fullName>
            </value>
            <value>
                <fullName>Variable Annuity</fullName>
            </value>
            <value>
                <fullName>Managed Account</fullName>
            </value>
            <value>
                <fullName>Individual Life</fullName>
            </value>
            <value>
                <fullName>Term Life</fullName>
            </value>
            <value>
                <fullName>Variable Life</fullName>
            </value>
            <value>
                <fullName>Whole Life</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__PrimaryOwner__c.field-meta.xml
<CustomField>
    <fullName>FinServ__PrimaryOwner__c</fullName>
    <complianceGroup>Integrity - Accurate</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
    <relationshipName>ClientFinancialAccounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information</complianceGroup>
    <formula>FinServ__PrimaryOwner__r.OCV_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OCV_ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/c360/GetCustomerInformationRepo.cls
/**
 * @since 03/2025
 * @description This class provides SOQL helpers for class related GetCustomerInformation.
 * @runTests GetCustomerInformationTest
 */
public with sharing class GetCustomerInformationRepo {
  /**
   * @description REPO to Fetch Financial Accounts Releated to the Customer
   * @param accId ID of the Customer
   * @param ocvId ocvId of the Customer
   * @return List<FinServ__FinancialAccount__c> return the list of Financial Accounts
   */

  public List<FinServ__FinancialAccount__c> getFinancialAccounts(
    Id accId,
    String ocvId
  ) {
    if (String.isBlank(accId)) {
      return new List<FinServ__FinancialAccount__c>();
    }
    return [SELECT Id, Account_Key__c , FinServ__FinancialAccountType__c FROM FinServ__FinancialAccount__c WHERE FinServ__PrimaryOwner__c =: accId OR FinServ__PrimaryOwner__r.OCV_ID__c =: OcvId];
  }
}