force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proof_of_Insurance__c/Proof_of_Insurance__c.object-meta.xml
<CustomObject>
    <description>Holds details relating to the proof of insurance document and property relating to a loan application</description>
    <label>Proof of Insurance</label>
    <nameField>
        <displayFormat>POID-{00000000}</displayFormat>
        <label>Proof of Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proof of Insurance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proof_of_Insurance__c/fields/Settlement_ID__c.field-meta.xml
<CustomField>
    <fullName>Settlement_ID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Settlement_Domain</complianceGroup>
    <description>Related Settlement ID</description>
    <label>Settlement ID</label>
    <referenceTo>Settlement__c</referenceTo>
    <relationshipLabel>Proof of Insurance</relationshipLabel>
    <relationshipName>Proof_of_Insurance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proof_of_Insurance__c/fields/Verified_By__c.field-meta.xml
<CustomField>
    <fullName>Verified_By__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Settlement_Domain</complianceGroup>
    <description>Verification user from the Settlement Domain</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Verified By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ResidentialLoanApplication/fields/Settlement_ID__c.field-meta.xml
<CustomField>
    <fullName>Settlement_ID__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy_Non_Personal_Information;Source - Loan Domain</complianceGroup>
    <description>Settlement ID from loan domain</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Settlement ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <description>Contains settlement details related to a residential loan application</description>
    <label>Settlement</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Settlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Settlement__c/fields/Settlement_ID__c.field-meta.xml
<CustomField>
    <fullName>Settlement_ID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Settlement_Domain</complianceGroup>
    <description>Immutable field representing the ID of the parent Settlement entity.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Settlement Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ProofOfInsuranceTriggerHandlerTest.cls
/**
 * @author Peter Charalambous
 * @since Mon Mar 25 2024
 * @description test class for proof of insurance trigger handler
 */
@isTest
public with sharing class ProofOfInsuranceTriggerHandlerTest {
  private static final String OCVID = '11223344';
  private static final String CUSTOMER = 'Peter Charalambous';
  @TestSetup
  static void setup() {
    //Not using faker as we need to assert the names
    Account customer = TestDataFactory.createAccount(CUSTOMER, false);
    customer.OCV_ID__c = OCVID;
    insert customer;

    ResidentialLoanApplication rla = TestDataFactory.createTestResidentialLoanApplication();
    rla.AccountId = customer.Id;
    insert rla;

    LoanApplicationFinancial loanAppFinancial = TestDataFactory.createLoanApplicationFinancial(
      rla.Id
    );
    insert loanAppFinancial;

    //Create action plans before creating settlement
    TestDataFactory.createSettlementActionPlans();

    Settlement__c settlement = TestDataFactory.createSettlement(rla.Id);
    insert settlement;

    Proof_of_Insurance__c poi = new Proof_of_Insurance__c(
      Settlement_ID__c = settlement.Id,
      Verified_By__c = OCVID
    );
    insert poi;
  }

  @IsTest
  static void testCustomerNamePopulated() {
    Test.startTest();
    Proof_of_Insurance__c poi = [
      SELECT Verified_By__c
      FROM Proof_of_Insurance__c
      LIMIT 1
    ];
    Assert.areEqual(CUSTOMER, poi.Verified_By__c);

    Test.stopTest();
  }
}