force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Action__c/Customer_Action__c.object-meta.xml
<CustomObject>
    <description>Tasks that arise relating to the settlement process which can be related to customers, Coaches and System</description>
    <label>Customer Action</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>Customer Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Actions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Action__c/fields/Accepted_By__c.field-meta.xml
<CustomField>
    <fullName>Accepted_By__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Settlement_Domain</complianceGroup>
    <description>Accepted by party - the OCV party ID of the person who provided this acceptance</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Accepted By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Action__c/fields/Completed_By__c.field-meta.xml
<CustomField>
    <fullName>Completed_By__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Settlement_Domain</complianceGroup>
    <description>OCV Id of who completed</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Completed By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Action__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Settlement_Domain</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to loan applicant</description>
    <label>Loan Applicant</label>
    <referenceTo>LoanApplicant</referenceTo>
    <relationshipLabel>Customer Actions</relationshipLabel>
    <relationshipName>Customer_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Action__c/fields/Loan_Application_Id__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application_Id__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Settlement_Domain</complianceGroup>
    <description>Residential Loan Application number</description>
    <formula>Settlement__r.Loan_Application_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan Application Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LoanApplicant/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to account</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loan Application</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LoanApplicant/fields/OCV_Id__c.field-meta.xml
<CustomField>
    <fullName>OCV_Id__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Personal Information;Source - OCV</complianceGroup>
    <description>Link to customer page</description>
    <formula>HYPERLINK(&quot;/&quot; &amp;  Account__c , Account__r.OCV_ID__c, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomerActionTriggerActions.cls
/**
 * @author Peter Charalambous
 * @since Tue Mar 19 2024
 * @description class for customer action trigger actions
 */
public with sharing class CustomerActionTriggerActions {
  /**
   * @description Find and populate the fields with customer name via ocv id
   * @param records records to populate with customer name
   */
  public static void populateCustomerName(List<Customer_Action__c> records) {
    List<String> filteredRlaRecords = filterRlaRecords(records);
    updateLoanApplicant(records, filteredRlaRecords);
  }

  /**
   * @description Filter records to retrieve the RLA list to query for
   * @param records records to filter
   * @return List<String>
   */
  private static List<String> filterRlaRecords(
    List<Customer_Action__c> records
  ) {
    List<String> rlaIdList = new List<String>();
    for (Customer_Action__c customerAction : records) {
      rlaIdList.add(customerAction.Loan_Application_Id__c);
    }
    return rlaIdList;
  }

  /**
   * @description Update the loan applicant
   * @param records records to populate with customer name
   * @param rlaIdList RLA id list to query for
   */
  private static void updateLoanApplicant(
    List<Customer_Action__c> records,
    List<String> rlaIdList
  ) {
    for (LoanApplicant applicant : [
      SELECT Id, Account__r.OCV_ID__c, LoanApplicationId
      FROM LoanApplicant
      WHERE LoanApplicationId IN :rlaIdList
    ]) {
      //Loop through records and update the values to be the name provided from the loan applicant
      for (Customer_Action__c customerAction : records) {
        //Ensure the Loan Applications are the same as an applicant can be linked to multiple loan apps
        if (
          applicant.LoanApplicationId ==
          customerAction.Loan_Application_Id__c &&
          (applicant.Account__r.OCV_ID__c == customerAction.Accepted_By__c ||
          applicant.Account__r.OCV_ID__c == customerAction.Completed_By__c)
        ) {
          customerAction.Loan_Applicant__c = applicant.Id;
        }
      }
    }
  }
}