force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Action__c/Customer_Action__c.object-meta.xml
<CustomObject>
    <description>Tasks that arise relating to the settlement process which can be related to customers, Coaches and System</description>
    <label>Customer Action</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>Customer Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Actions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Action__c/fields/Accepted_By__c.field-meta.xml
<CustomField>
    <fullName>Accepted_By__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Settlement_Domain</complianceGroup>
    <description>Accepted by party - the OCV party ID of the person who provided this acceptance</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Accepted By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Action__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Settlement_Domain</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to loan applicant</description>
    <label>Loan Applicant</label>
    <referenceTo>LoanApplicant</referenceTo>
    <relationshipLabel>Customer Actions</relationshipLabel>
    <relationshipName>Customer_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Action__c/fields/Settlement__c.field-meta.xml
<CustomField>
    <fullName>Settlement__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Settlement_Domain</complianceGroup>
    <description>Reference of associated Settlement Id (Salesforce ID)</description>
    <label>Settlement</label>
    <referenceTo>Settlement__c</referenceTo>
    <relationshipLabel>Customer Actions</relationshipLabel>
    <relationshipName>Customer_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Action__c/recordTypes/Loan_Offer_Acceptance.recordType-meta.xml
<RecordType>
    <fullName>Loan_Offer_Acceptance</fullName>
    <active>true</active>
    <label>Loan Offer Acceptance</label>
</RecordType>

force-app/main/default/objects/LoanApplicant/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to account</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loan Application</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LoanApplicant/fields/OCV_Id__c.field-meta.xml
<CustomField>
    <fullName>OCV_Id__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Personal Information;Source - OCV</complianceGroup>
    <description>Link to customer page</description>
    <formula>HYPERLINK(&quot;/&quot; &amp;  Account__c , Account__r.OCV_ID__c, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <description>Contains settlement details related to a residential loan application</description>
    <label>Settlement</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Settlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CustomerActionTriggerHandlerTest.cls
/**
 * @author Peter Charalambous
 * @since Mon Mar 25 2024
 * @description Test class for CustomerActionTriggerHandler
 */
@isTest
public with sharing class CustomerActionTriggerHandlerTest {
  private static final String OCVID = '11223344';
  private static final String CUSTOMER = 'Peter Charalambous';
  @TestSetup
  static void setup() {
    //Not using faker as we need to assert the names
    Account acc = TestDataFactory.createAccount(CUSTOMER, false);
    acc.OCV_ID__c = OCVID;
    insert acc;

    ResidentialLoanApplication rla = TestDataFactory.createTestResidentialLoanApplication();
    rla.AccountId = acc.Id;
    insert rla;

    LoanApplicationFinancial loanAppFinancial = TestDataFactory.createLoanApplicationFinancial(
      rla.Id
    );
    insert loanAppFinancial;

    //Create action plans before creating settlement
    TestDataFactory.createSettlementActionPlans();

    Settlement__c settlement = TestDataFactory.createSettlement(rla.Id);
    insert settlement;

    LoanApplicant applicant = new LoanApplicant(
      Account__c = acc.Id,
      LoanApplicationId = rla.Id,
      Name = CUSTOMER
    );
    insert applicant;

    Customer_Action__c customerAction = new Customer_Action__c(
      Accepted_By__c = OCVID,
      Settlement__c = settlement.Id,
      RecordTypeId = SObjectType.Customer_Action__c.getRecordTypeInfosByDeveloperName()
        .get('Loan_Offer_Acceptance')
        .recordTypeId
    );
    insert customerAction;
  }

  @IsTest
  static void testLoanApplicantIsPopulated() {
    LoanApplicant applicant = [
      SELECT Id
      FROM LoanApplicant
      WHERE Name = :CUSTOMER
    ];
    Test.startTest();
    Customer_Action__c customerAction = [
      SELECT Loan_Applicant__c
      FROM Customer_Action__c
      WHERE Loan_Applicant__c = :applicant.Id
    ];
    Test.stopTest();
    Assert.isNotNull(
      customerAction.Loan_Applicant__c,
      'Loan Applicant should contain a value equal to loan applicant id'
    );
  }
}