force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Assessment_Id__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Id__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <description>Id of the latest assessment. Needed while finalising the assessment</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Assessment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Credit_Id__c.field-meta.xml
<CustomField>
    <fullName>Credit_Id__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Loan Domain</complianceGroup>
    <description>Id of the Credit Assessment</description>
    <externalId>true</externalId>
    <label>Credit Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/OCV_Id__c.field-meta.xml
<CustomField>
    <fullName>OCV_Id__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Personal_Information;Source_OCV</complianceGroup>
    <description>OCV ID of the customer</description>
    <externalId>true</externalId>
    <label>OCV Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code__c</fullName>
    <complianceGroup>Source_Salesforce;Integrity_Trusted;Privacy_Non_Personal_Information</complianceGroup>
    <description>NPP reason code for the case.</description>
    <formula>IF(RecordType.DeveloperName = &quot;NPP_Dispute&quot; &amp;&amp; ISPICKVAL(Dispute_Reason__c, &quot;Incorrect Amount Transferred&quot;), &quot;DUPL&quot;,
IF(RecordType.DeveloperName = &quot;NPP_Dispute&quot; &amp;&amp; ISPICKVAL(Dispute_Reason__c, &quot;Incorrect Account Details&quot;), &quot;CUST&quot;,
IF(RecordType.DeveloperName = &quot;NPP_Dispute&quot; &amp;&amp; ISPICKVAL(Dispute_Reason__c, &quot;Duplicate Transaction&quot;), &quot;DUPL&quot;,
IF(RecordType.DeveloperName = &quot;NPP_Dispute&quot; &amp;&amp; ISPICKVAL(Dispute_Reason__c, &quot;Return money received from an unknown person&quot;), &quot;MD06&quot;,
IF(RecordType.DeveloperName = &quot;IMT_Dispute&quot; &amp;&amp; ISPICKVAL(Dispute_Reason__c, &quot;Cancel Transfer&quot;), &quot;CB_Cance_Out&quot;,
IF(RecordType.DeveloperName = &quot;IMT_Dispute&quot; &amp;&amp; ISPICKVAL(Dispute_Reason__c, &quot;Payee has not received funds&quot;), &quot;CB_BCNR&quot;,
IF(RecordType.DeveloperName = &quot;IMT_Dispute&quot; &amp;&amp; ISPICKVAL(Dispute_Reason__c, &quot;Amendment Request&quot;), &quot;AmendBen&quot;,
IF(RecordType.DeveloperName = &quot;IMT_Dispute&quot; &amp;&amp; ISPICKVAL(Dispute_Reason__c, &quot;Suspected fraud&quot;), &quot;CB_Cance_Out&quot;,&quot;&quot;))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reason Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reason_Outcome__c/Reason_Outcome__c.object-meta.xml
<CustomObject>
    <label>Reason Outcome</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Reason Outcome Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reason Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reason_Outcome__c/fields/Outcome_Code__c.field-meta.xml
<CustomField>
    <fullName>Outcome_Code__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <description>Code of the possible assessment outcome</description>
    <label>Outcome Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reason_Outcome__c/fields/Outcome_Description__c.field-meta.xml
<CustomField>
    <fullName>Outcome_Description__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <description>Description of the possible assessment outcome</description>
    <label>Outcome Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reason_Outcome__c/fields/Referral_Reason__c.field-meta.xml
<CustomField>
    <fullName>Referral_Reason__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <description>Associated referral reason</description>
    <label>Referral Reason</label>
    <referenceTo>Referral_Reason__c</referenceTo>
    <relationshipLabel>Reason Outcomes</relationshipLabel>
    <relationshipName>Reason_Outcomes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Referral_Reason__c/Referral_Reason__c.object-meta.xml
<CustomObject>
    <label>Referral Reason</label>
    <nameField>
        <label>Referral Reason Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Reasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Reason__c/fields/Assessment_Category__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Category__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <description>Credit assessment outcome category</description>
    <label>Assessment Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Reason__c/fields/Authority_Level__c.field-meta.xml
<CustomField>
    <fullName>Authority_Level__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <description>Assessor authority level required to resolve the referral</description>
    <label>Authority Level</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Reason__c/fields/Guidance_Code__c.field-meta.xml
<CustomField>
    <fullName>Guidance_Code__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <description>Codes to guide assessor on actions to take to resolve the referral</description>
    <label>Guidance Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Reason__c/fields/Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <description>Credit assessment outcome reason code</description>
    <externalId>true</externalId>
    <label>Reason Code</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ResidentialLoanApplication/fields/Credit_ID__c.field-meta.xml
<CustomField>
    <fullName>Credit_ID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Loan_Domain</complianceGroup>
    <description>A unique ID that identifies a credit enquiry against the home loan application</description>
    <label>Credit ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreditAsssessmentRepository.cls
/**
 * @author Peter Charalambous
 * @since Mon Aug 05 2024
 * @description Provides SOQL and DML helpers for CreditAssessmentController
 */

public with sharing class CreditAsssessmentRepository {
  /**
   * @description retrieve case record
   * @param recordId of case to retrieve
   * @return Case
   */
  public Case getCaseRecord(String recordId) {
    PermissionUtils.canQuery('Case');
    return [
      SELECT Id, OwnerId, Status, Account.OCV_Id__c, Assessment_Id__c
      FROM Case
      WHERE Id = :recordId
    ];
  }

  /**
   * @description retrieve residential loan application record
   * @param recordId of rla to retrieve
   * @return ResidentialLoanApplication
   */
  public ResidentialLoanApplication getResidentialLoanApplicationRecord(
    String recordId
  ) {
    PermissionUtils.canQuery('ResidentialLoanApplication');
    return [
      SELECT Account.OCV_Id__c, Credit_ID__c, Status
      FROM ResidentialLoanApplication
      WHERE Id = :recordId
    ];
  }

  /**
   * @description retrieve list of users for fed id
   * @param emails of users to retrieve
   * @return List<User>
   */
  public List<User> getUserList(String emails) {
    SystemModeActions systemActions = new SystemModeActions(
      'CreditAsssessmentRepository',
      'getResidentialLoanApplicationRecord'
    );
    //Remove null as a potential check so we dont get random users with no fed ids
    return systemActions.query(
      'SELECT Name, FederationIdentifier FROM User WHERE FederationIdentifier != null AND FederationIdentifier IN (' +
        emails +
        ')'
    );
  }

  /**
   * @description retrieve list of reason outcomes based on referral reason
   * @param reasonCodeId reason code to retrieve records from
   * @return List<Reason_Outcome__c>
   */
  public List<Reason_Outcome__c> getReasonOutcomeByReferralReason(
    String reasonCodeId
  ) {
    PermissionUtils.canQuery('Reason_Outcome__c');
    return [
      SELECT Outcome_Code__c, Outcome_Description__c
      FROM Reason_Outcome__c
      WHERE Referral_Reason__c = :reasonCodeId
    ];
  }

  /**
   * @description retrieve list of referral reason code data
   * @param reasonCodeSet set of reason codes
   * @return List<Referral_Reason__c>
   */
  public List<Referral_Reason__c> getReferralReasonList(
    Set<String> reasonCodeSet
  ) {
    if (reasonCodeSet.isEmpty()) {
      return new List<Referral_Reason__c>();
    }

    PermissionUtils.canQuery('Referral_Reason__c');
    return [
      SELECT
        Id,
        Reason_Code__c,
        Guidance_Code__c,
        Assessment_Category__c,
        Authority_Level__c
      FROM Referral_Reason__c
      WHERE Reason_Code__c IN :reasonCodeSet
    ];
  }

  /**
   * @description retrieve list of reason outcomes based on outcome code
   * @param outcomeCodeSet set of outcome codes to retrieve list by
   * @return List<Reason_Outcome__c>
   */
  public List<Reason_Outcome__c> getReasonOutcomeByOutcomeCode(
    Set<String> outcomeCodeSet
  ) {
    if (outcomeCodeSet.isEmpty()) {
      return new List<Reason_Outcome__c>();
    }
    PermissionUtils.canQuery('Reason_Outcome__c');
    return [
      SELECT Outcome_Code__c, Outcome_Description__c
      FROM Reason_Outcome__c
      WHERE Outcome_Code__c IN :outcomeCodeSet
    ];
  }
}