force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Source_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_System_ID__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Source System Id of Party received from OCV</description>
    <label>Source System ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Source_System_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_System_Name__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Source System Name of Party received from OCV (E.g. CAP)</description>
    <externalId>true</externalId>
    <label>Source System Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Country Code of the Passport Provided by the Customer.</description>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AFG</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>ALA</fullName>
                <label>Aland Islands</label>
            </value>
            <value>
                <fullName>ALB</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>DZA</fullName>
                <label>Algeria</label>
            </value>
            <value>
                <fullName>ASM</fullName>
                <label>American Samoa</label>
            </value>
            <value>
                <fullName>AND</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AGO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AIA</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>ATA</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>ATG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>ARG</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>ARM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>ABW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AUS</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AUT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZE</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BHS</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BHR</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BGD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BRB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BLR</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>BEL</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BLZ</fullName>
                <label>Belize</label>
            </value>
            <value>
                <fullName>BEN</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BMU</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BTN</fullName>
                <label>Bhutan</label>
            </value>
            <value>
                <fullName>BOL</fullName>
                <label>Bolivia, Plurinational State of</label>
            </value>
            <value>
                <fullName>BES</fullName>
                <label>Bonaire, Sint Eustatius and Saba</label>
            </value>
            <value>
                <fullName>BIH</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BWA</fullName>
                <label>Botswana</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Type of Document which Customer has provided to verify.</description>
    <inlineHelpText>The document selected in this field should match the identity document captured by the customer.
    This field should only be edited in the case that the customer has incorrectly done this.</inlineHelpText>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DOCUMENT_TYPE_AUSTRALIAN_BIRTH_CERTIFICATE</fullName>
                <label>Australian Birth Certificate</label>
            </value>
            <value>
                <fullName>DOCUMENT_TYPE_AUSTRALIAN_CHANGE_OF_NAME_CERTIFICATE</fullName>
                <label>Australian Change of Name Certificate</label>
            </value>
            <value>
                <fullName>DOCUMENT_TYPE_AUSTRALIAN_DRIVERS_LICENCE</fullName>
                <label>Australian Driver&apos;s Licence</label>
            </value>
            <value>
                <fullName>DOCUMENT_TYPE_AUSTRALIAN_MARRIAGE_CERTIFICATE</fullName>
                <label>Australian Marriage Certificate</label>
            </value>
            <value>
                <fullName>DOCUMENT_TYPE_AUSTRALIAN_PASSPORT</fullName>
                <label>Australian Passport</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>ExpiryDate__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Expiry Date of the Passport / Driving Licence if provided by the Customer.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/LicenceCardNumber__c.field-meta.xml
<CustomField>
    <fullName>LicenceCardNumber__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Licence Card Number Tokenised and stored in Salesforce.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Licence Card Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/LicenceNumber__c.field-meta.xml
<CustomField>
    <fullName>LicenceNumber__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Licence Number Tokenised and stored in Salesforce.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Licence Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewFirstName__c.field-meta.xml
<CustomField>
    <fullName>NewFirstName__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Personal Information;Source_Salesforce</complianceGroup>
    <description>Customer new Legal First Name. Updated through Mobile.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>[New] First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewLastName__c.field-meta.xml
<CustomField>
    <fullName>NewLastName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Customer new Legal Last Name. Updated through Mobile.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>[New] Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewMiddleName__c.field-meta.xml
<CustomField>
    <fullName>NewMiddleName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Customer new Legal Middle Name. Updated through Mobile.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>[New] Middle Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OCV_Id__c.field-meta.xml
<CustomField>
    <fullName>OCV_Id__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Personal_Information;Source_OCV</complianceGroup>
    <description>OCV ID of the customer</description>
    <externalId>true</externalId>
    <label>OCV Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/StateCode__c.field-meta.xml
<CustomField>
    <fullName>StateCode__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>State Code of the Document Type Provided by the Customer excluding Passport</description>
    <label>State Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NSW</fullName>
                <label>New South Wales</label>
            </value>
            <value>
                <fullName>VIC</fullName>
                <label>Victoria</label>
            </value>
            <value>
                <fullName>QLD</fullName>
                <label>Queensland</label>
            </value>
            <value>
                <fullName>WA</fullName>
                <label>Western Australia</label>
            </value>
            <value>
                <fullName>SA</fullName>
                <label>South Australia</label>
            </value>
            <value>
                <fullName>TAS</fullName>
                <label>Tasmania</label>
            </value>
            <value>
                <fullName>ACT</fullName>
                <label>Australian Capital Territory</label>
            </value>
            <value>
                <fullName>NT</fullName>
                <label>Northern Territory</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/Customer_Profile_Updates__c.object-meta.xml
<CustomObject>
    <description>This custom object is a staging object which will store the changes made by the bankers on Account and all Contact Point objects.</description>
    <label>Pending Updates to Customer Details</label>
    <nameField>
        <label>Customer Profile Updates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pending Updates to Customer Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Case</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pending Updates to Customer Details</relationshipLabel>
    <relationshipName>Customer_Profile_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will be a lookup on Customer&apos;s Profile (Accounts).</description>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pending Updates to Customer Details</relationshipLabel>
    <relationshipName>Customer_Profile_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>To identify object where this update is happening. Eg Account, Contact, ContactPointXXXX.</description>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/OCV_Id__c.field-meta.xml
<CustomField>
    <fullName>OCV_Id__c</fullName>
    <description>Formula field to refer customer OCV Id</description>
    <formula>Customer_Name__r.OCV_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OCV Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Source_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_System_ID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Associated Customer Records Source System ID</description>
    <formula>Customer_Name__r.Source_System_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source System ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Profile_Updates__c/fields/Source_System_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_System_Name__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Associated Customer Records Source System Name.</description>
    <formula>Customer_Name__r.Source_System_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source System Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProfileUpdateCaseStagingConfigTest.cls
/**
 * @author Karen Valeriano
 * @since Jan 2025
 * @description This is the test class for @link ProfileUpdateCaseStagingConfig.
 */
@IsTest
private with sharing class ProfileUpdateCaseStagingConfigTest {
  static final Faker FAKER = new Faker('AU');
  static final String CPU_ACTION_UPDATE = 'Update';
  static final String CPU_OBJECTNAME_CASE = 'Case';

  static Account acct = new Account(
    Id = Lib_FakeIdGenerator.getMockId(Account.SObjectType),
    OCV_ID__c = FAKER.randomString(10),
    Source_System_ID__c = FAKER.randomString(10),
    Source_System_Name__c = 'CAP-CIS'
  );
  static Case theCase = new Case(
    Id = Lib_FakeIdGenerator.getMockId(Case.SObjectType),
    Type = ProfileUpdateCaseActions.CASE_TYPE_LEGAL_NAME,
    NewFirstName__c = FAKER.person.firstName('male'),
    NewMiddleName__c = FAKER.randomString(5),
    NewLastName__c = FAKER.person.lastName(),
    DocumentType__c = LegalNameUpdateModel.DOCUMENT_TYPE_AUSTRALIAN_DRIVERS_LICENCE,
    LicenceNumber__c = FAKER.randomString(10),
    LicenceCardNumber__c = FAKER.randomString(15),
    ExpiryDate__c = Date.newInstance(2029, 12, 1),
    StateCode__c = FAKER.address.state(),
    CountryCode__c = 'AUS',
    AccountId = acct.Id
  );
  static Map<Id, Case> mapAccountIdToCase = new Map<Id, Case>{
    acct.Id => theCase
  };
  static Customer_Profile_Updates__c cpu = new Customer_Profile_Updates__c(
    Id = Lib_FakeIdGenerator.getMockId(Customer_Profile_Updates__c.SObjectType),
    Customer_Name__c = acct.Id
  );

  @IsTest
  static void testProfileUpdateCaseStagingConfig() {
    ProfileUpdateCaseStagingConfig config = new ProfileUpdateCaseStagingConfig(
      mapAccountIdToCase
    );

    Test.startTest();
    config.process(cpu, acct, null);
    Test.stopTest();

    Assert.areEqual(theCase.Id, cpu.Case__c, 'Incorrect Case Id');
    Assert.areEqual(acct.Id, cpu.Customer_Name__c, 'Incorrect Customer Id');
    Assert.areEqual(
      String.format(
        ProfileUpdateCaseStagingConfig.CPU_NAME_VALUE_LEGAL_NAME,
        new List<String>{ theCase.CaseNumber }
      ),
      cpu.Name,
      'Should set the correct Name'
    );
    Assert.areEqual(
      CPU_OBJECTNAME_CASE,
      cpu.Object_Name__c,
      'Should set the correct Object_Name__c'
    );
    Assert.areEqual(
      ProfileUpdateCaseStagingConfig.TRIGGERED_FROM_VALUE_LEGAL_NAME,
      cpu.TriggeredFrom__c,
      'Should set the correct TriggeredFrom__c'
    );
    Assert.areEqual(
      CPU_ACTION_UPDATE,
      cpu.Action__c,
      'Should set the correct Action__c'
    );
    Assert.areEqual(
      String.format(
          ProfileUpdateCaseStagingConfig.LEGAL_NAME_NEW_VALUE,
          new List<String>{
            ProfileUpdateCaseStagingConfig.getValue(theCase.NewFirstName__c),
            ProfileUpdateCaseStagingConfig.getValue(theCase.NewMiddleName__c),
            ProfileUpdateCaseStagingConfig.getValue(theCase.NewLastName__c)
          }
        )
        .trim(),
      cpu.NewValue__c,
      'Should set the correct NewValue__c'
    );
    Assert.isTrue(
      cpu.ToBeValue__c.contains('"firstName":"' + theCase.NewFirstName__c),
      'Should set the correct firstName value'
    );
    Assert.isTrue(
      cpu.ToBeValue__c.contains('"middleName":"' + theCase.NewMiddleName__c),
      'Should set the correct middleName value'
    );
    Assert.isTrue(
      cpu.ToBeValue__c.contains('"lastName":"' + theCase.NewLastName__c),
      'Should set the correct lastName value'
    );
    Assert.isTrue(
      cpu.ToBeValue__c.contains(
        '"identifier":"enc(' + theCase.LicenceNumber__c
      ),
      'Should set the correct document identifier value'
    );
    Assert.isTrue(
      cpu.ToBeValue__c.contains(
        '"identifier":"enc(' + theCase.LicenceCardNumber__c
      ),
      'Should set the correct related document identifier value'
    );
    Assert.isTrue(
      cpu.ToBeValue__c.contains('"identifier":"' + acct.OCV_ID__c),
      'Should set the correct ocv identifier value'
    );
  }

  @IsTest
  static void testEmptyMap() {
    ProfileUpdateCaseStagingConfig config = new ProfileUpdateCaseStagingConfig(
      null
    );
    Exception error;
    try {
      Test.startTest();
      config.process(cpu, acct, null);
      Test.stopTest();
    } catch (Exception ex) {
      error = ex;
    }
    Assert.isNotNull(
      error,
      'Change capturing process should fail when customer record doesnt map to any case'
    );
  }
}