force-app/main/default/objects/Account/fields/OCV_ID__c.field-meta.xml
<CustomField>
    <fullName>OCV_ID__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information</complianceGroup>
    <description>Customer Master will employ the use of database sequence while assigning a &apos;One Customer ID&apos; when a new party is created in the Customer Master.</description>
    <inlineHelpText>One Customer View ID</inlineHelpText>
    <label>OCV ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ResidentialLoanApplication/fields/Settlement_ID__c.field-meta.xml
<CustomField>
    <fullName>Settlement_ID__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy_Non_Personal_Information;Source - Loan Domain</complianceGroup>
    <description>Settlement ID from loan domain</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Settlement ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <description>Contains settlement details related to a residential loan application</description>
    <label>Settlement</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Settlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Settlement__c/fields/Loan_Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application_Number__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Settlement_Domain</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Loan Application ID</description>
    <label>Loan Application Number</label>
    <referenceTo>ResidentialLoanApplication</referenceTo>
    <relationshipLabel>Settlements</relationshipLabel>
    <relationshipName>Settlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Settlement__c/fields/Settlement_ID__c.field-meta.xml
<CustomField>
    <fullName>Settlement_ID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Settlement_Domain</complianceGroup>
    <description>Immutable field representing the ID of the parent Settlement entity.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Settlement Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/sf-lending/classes/ProofOfInsuranceController.cls
/**
 * @author Peter Charalambous
 * @since October 2023
 * @description handles verifying customer proof of insurance
 */
public with sharing class ProofOfInsuranceController implements IGenericClass {
  public static final String TECH_ASSIST_ERROR = 'Verify Insurance Failed. Please refresh and try again. Raise a fault through TechAssist if the problem persists.';
  public static final String MISSING_DATA_ERROR = 'Missing Proof of Insurance data. Please correct and try again. Raise a fault through TechAssist if the problem persists.';
  public static final String ERROR_MSG = 'Failed to retrieve Proof Of Insurance details. Please refresh and try again. Raise a fault through TechAssist if the problem persists.';
  private static final LexAPIRepository LEX_API_REPOSITORY = (LexAPIRepository) Lib_InstanceProvider.forType(
    LexAPIRepository.class
  );
  private static final SettlementRepository SETTLEMENT_REPOSITORY = (SettlementRepository) Lib_InstanceProvider.forType(
    SettlementRepository.class
  );
  /**
   * @description Verifies a customers proof of insurance
   * @param settlementId Record id of settlement to verify
   * @param mortgageContractId Record id of mortgage to verify
   * @param propertyId Record id of property to verify
   * @param documentId Record id of document to verify
   * @param documentFileVersion Record id of documentFileVersion to verify
   * @return `VerifyInsuranceModel` if verification call was successful
   */
  @SuppressWarnings('PMD.ExcessiveParameterList')
  @AuraEnabled
  public static VerifyInsuranceModel verifyInsurance(
    String settlementId,
    String mortgageContractId,
    String propertyId,
    String documentId,
    String documentFileVersion
  ) {
    Settlement__c settlement = SETTLEMENT_REPOSITORY.getSettlementBySettlementId(
      settlementId
    );

    VerifyInsuranceWrapper poiDetails = new VerifyInsuranceWrapper();
    poiDetails.settlementId = settlementId;
    poiDetails.mortgageContractId = mortgageContractId;
    poiDetails.propertyId = propertyId;
    poiDetails.documentId = documentId;
    poiDetails.documentFileVersion = documentFileVersion;
    poiDetails.ocvId = settlement?.Loan_Application_Number__r.Account.OCV_ID__c;

    try {
      if (!checkFieldSanity(poiDetails)) {
        throw new AuraHandledException(MISSING_DATA_ERROR);
      }
      VerifyInsuranceModel response = LEX_API_REPOSITORY.verifyInsurance(
        poiDetails
      );
      return response;
    } catch (Exception e) {
      Logger.error(e.getMessage());
      Logger.saveLog();
      e.setMessage(TECH_ASSIST_ERROR);
      throw e;
    }
  }

  private static Boolean checkFieldSanity(VerifyInsuranceWrapper poi) {
    return String.isNotBlank(poi.settlementId) &&
      String.isNotBlank(poi.mortgageContractId) &&
      String.isNotBlank(poi.propertyId) &&
      String.isNotBlank(poi.documentId) &&
      String.isNotBlank(poi.documentFileVersion);
  }

  /**
   * @description VerifyInsuranceWrapper wrapper class for verify insurance
   */
  public class VerifyInsuranceWrapper {
    public String settlementId;
    public String mortgageContractId;
    public String propertyId;
    public String documentId;
    public String documentFileVersion;
    public String ocvId;
  }

  /**
   * @description getData method to return settlement data
   * @param param Parameter to pass to the getData method (record id)
   * @return Object Array of Data
   */
  public Object getData(String param) {
    try {
      Map<String, Object> params = (Map<String, Object>) JSON.deserializeUntyped(
        param
      );
      Settlement__c settlement = SETTLEMENT_REPOSITORY.getSettlement(
        (String) params.get('recordId')
      );
      return LEX_API_REPOSITORY.getProofOfInsurance(
        settlement.Settlement_ID__c,
        settlement.Loan_Application_Number__r.Account.OCV_ID__c
      );
    } catch (Exception e) {
      Logger.error('Failure on Get Proof Of Insurance API', e);
      Logger.saveLog();

      AuraHandledException err = new AuraHandledException(ERROR_MSG);
      err.setMessage(ERROR_MSG);
      throw err;
    }
  }
}