force-app/main/default/objects/Account/fields/Source_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_System_ID__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Source System Id of Party received from OCV</description>
    <label>Source System ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApplicationFormProduct/fields/Source_System_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_System_Id__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Personal Information;Source - Loan Domain</complianceGroup>
    <description>Id of the AMBIT Opportunity</description>
    <externalId>true</externalId>
    <label>Source System Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Asset_Finance_Accreditation_Status__c.field-meta.xml
<CustomField>
    <fullName>Asset_Finance_Accreditation_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Accreditation Status of the Broker TPMI-SAO.</description>
    <label>Asset Finance Accreditation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/AssetFinanceTPMISAO__c.field-meta.xml
<CustomField>
    <fullName>AssetFinanceTPMISAO__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - OCV</complianceGroup>
    <description>TPMI-SAO ID of current Asset Finance accredited Broker.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Asset Finance TPMI-SAO</label>
    <length>19</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Broker_Accreditation_Type__c.field-meta.xml
<CustomField>
    <fullName>Broker_Accreditation_Type__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_OCV</complianceGroup>
    <description>Accreditation active for a particular Broker</description>
    <label>Accreditation Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asset Finance</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Lan_Id__c.field-meta.xml
<CustomField>
    <fullName>Lan_Id__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non-Sensitive_Personal_Information;Source_OCV</complianceGroup>
    <description>LAN ID of the user who captured the response or who the lead was routed to (if
        available).</description>
    <label>Lan-Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Broker_Name__c.field-meta.xml
<CustomField>
    <fullName>Broker_Name__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field for accredited broker</description>
    <label>Broker Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3 OR 4)</booleanFilter>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Broker</value>
        </filterItems>
        <filterItems>
            <field>Contact.Commercial_Accreditation_Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <filterItems>
            <field>Contact.Asset_Finance_Accreditation_Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <filterItems>
            <field>Contact.Retail_Accreditation_Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads (Broker Name)</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Broker_Name__c.field-meta.xml
<CustomField>
    <fullName>Broker_Name__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_OCV</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field for accredited broker</description>
    <label>Broker Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Accreditation_CompactLayout__c</field>
            <operation>contains</operation>
            <value>Commercial</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Broker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Broker Name)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_Id__c.field-meta.xml
<CustomField>
    <fullName>Opp_Id__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Readable opportunity Id populated during lead conversion to opportunity</description>
    <displayFormat>0-{0000000}</displayFormat>
    <label>Opp Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Funding_purpose__c.field-meta.xml
<CustomField>
    <fullName>Funding_purpose__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Source_Salesforce;Integrity_Accurate</complianceGroup>
    <description>Funding purpose</description>
    <label>Funding purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Property Purchase or Construction</fullName>
            </value>
            <value>
                <fullName>Business Investment</fullName>
            </value>
            <value>
                <fullName>Working Capital</fullName>
            </value>
            <value>
                <fullName>Interest Rate &amp; Repayment</fullName>
            </value>
            <value>
                <fullName>Restructure, Consolidation or refinance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Lan_Id__c.field-meta.xml
<CustomField>
    <fullName>Lan_Id__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Integrity_Trusted;Source_Salesforce</complianceGroup>
    <description>LAN ID of the user who captured the response or who the lead was routed to (if available).</description>
    <externalId>true</externalId>
    <label>Lan Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ccrm/LaunchAppOnOppHelperTest.cls
/**
 * @author Ayushi Gupta
 * @since  09/2024
 * @description Test class of LaunchAppOnOppHelper
 */
@isTest
private class LaunchAppOnOppHelperTest {
  static Lib_MockProvider launchAppRepoMock;

  static void registerMocks() {
    launchAppRepoMock = Lib_MockProvider.forType(
      LaunchAppOnOppControllerRepository.class
    );
  }

  @isTest
  static void createOppLineItemWrapperTest() {
    //Mock data creation
    OpportunityLineItem oli = new OpportunityLineItem(
      Id = Lib_FakeIdGenerator.getMockId(OpportunityLineItem.SObjectType),
      Product2Id = Lib_FakeIdGenerator.getMockId(Product2.SObjectType),
      UnitPrice = 20,
      Funding_purpose__c = 'Property Purchase or Construction',
      Product2 = new Product2(Name = 'Test')
    );
    Test.startTest();
    List<LaunchAppOnOppController.OppLineItemWrapper> items = LaunchAppOnOppHelper.createOppLineItemWrapper(
      new List<OpportunityLineItem>{ oli },
      new Set<Id>()
    );
    Test.stopTest();
    Assert.isFalse(items.size() == 0, 'No items found');
    Assert.areEqual(
      'Property Purchase or Construction',
      items[0].fundingPurpose,
      'Funding purpose is not set correctly'
    );
    Assert.areEqual(
      'Test',
      items[0].productName,
      'Product Name is not set correctly'
    );
  }

  @isTest
  static void getSelectedOppLineItemIdsTest() {
    //Mock data creation
    Id oppId = Lib_FakeIdGenerator.getMockId(Opportunity.SObjectType);
    Id oliId = Lib_FakeIdGenerator.getMockId(OpportunityLineItem.SObjectType);
    ApplicationFormProduct afp = new ApplicationFormProduct(
      Id = Lib_FakeIdGenerator.getMockId(ApplicationFormProduct.SObjectType),
      Source_System_Id__c = oppId + '' + oliId
    );
    Test.startTest();
    Set<Id> selectedOppLineItemsIds = LaunchAppOnOppHelper.getSelectedOppLineItemIds(
      new List<ApplicationFormProduct>{ afp }
    );
    Test.stopTest();
    Assert.isFalse(selectedOppLineItemsIds.size() == 0, 'No items found');
    Assert.areEqual(
      new Set<Id>{ oliId },
      selectedOppLineItemsIds,
      'Values are not equal'
    );
  }

  @isTest
  static void testCreateAMBITRequestBody() {
    registermocks();

    //GIVEN opportunity and opportunity Line Item record
    Id oppId = Lib_FakeIdGenerator.getMockId(Opportunity.SObjectType);
    Id oliId = Lib_FakeIdGenerator.getMockId(OpportunityLineItem.SObjectType);
    Account accRec = (Account) TestUtil.setFields(
      new Account(
        Name = 'Sample Account',
        Id = Lib_FakeIdGenerator.getMockId(Account.SObjectType),
        Source_System_ID__c = '12345'
      ),
      new Map<String, Object>()
    );
    User ownerRec = (User) TestUtil.setFields(
      new User(
        FirstName = 'Sample',
        LastName = 'User',
        Id = Lib_FakeIdGenerator.getMockId(User.SObjectType),
        Lan_Id__c = 'userlanId1'
      ),
      new Map<String, Object>()
    );
    Contact brokerRec = (Contact) TestUtil.setFields(
      new Contact(
        FirstName = 'Sample',
        LastName = 'Contact',
        Id = Lib_FakeIdGenerator.getMockId(Contact.SObjectType),
        Broker_Accreditation_Type__c = 'Asset Finance',
        Asset_Finance_Accreditation_Status__c = 'Active',
        AssetFinanceTPMISAO__c = 'CA-123456'
      ),
      new Map<String, Object>()
    );
    User userRec = (User) TestUtil.setFields(
      new User(
        Id = Lib_FakeIdGenerator.getMockId(User.SObjectType),
        Lan_Id__c = 'userlanId2'
      ),
      new Map<String, Object>()
    );
    Opportunity oppRec = (Opportunity) TestUtil.setFields(
      new Opportunity(
        Id = oppId,
        Name = 'Sample Opportunity',
        StageName = 'Opportunity Identified',
        Account = accRec,
        Owner = ownerRec,
        Broker_Name__r = brokerRec,
        Description = 'Sample Opp'
      ),
      new Map<String, Object>{ 'Opp_Id__c' => '0-0023456' }
    );
    Opportunity oppRecWithTeamMembers = (Opportunity) TestUtil.setFields(
      oppRec,
      new Map<String, List<OpportunityTeamMember>>{
        'OpportunityTeamMembers' => new List<OpportunityTeamMember>{
          new OpportunityTeamMember(
            Id = Lib_FakeIdGenerator.getMockId(
              OpportunityTeamMember.SObjectType
            ),
            TeamMemberRole = 'Asset Finance',
            User = userRec
          )
        }
      }
    );
    List<OpportunityLineItem> oliList = new List<OpportunityLineItem>{
      new OpportunityLineItem(
        Id = oliId,
        OpportunityId = oppId,
        Product2Id = Lib_FakeIdGenerator.getMockId(Product2.SObjectType),
        UnitPrice = 20,
        Funding_purpose__c = 'Property Purchase or Construction',
        Product2 = new Product2(Name = 'Test')
      )
    };
    List<Id> oliIdsList = new List<Id>{ oliId };
    launchAppRepoMock.mock('getOpportunityData', oppRecWithTeamMembers);

    //WHEN calling a createAMBITRequestBody
    Test.startTest();
    CommercialAMBITRequestModel ambitModel = LaunchAppOnOppHelper.createAMBITRequestBody(
      oppId,
      oliIdsList[0]
    );
    Test.stopTest();

    //THEN it should successfully assert
    Assert.areEqual(
      'CRM-SF',
      ambitModel.DCOpportunityPackage.Opportunity.Source.XTLookupValue,
      'Source value should be matched'
    );
    Assert.areEqual(
      userRec.Lan_Id__c,
      ambitModel.DCOpportunityPackage.Opportunity.SecondarySalesLeadId.Username,
      'Secondary Sales Lead Id value should be matched'
    );
    Assert.areEqual(
      ownerRec.Lan_Id__c,
      ambitModel.DCOpportunityPackage.Opportunity.SalesLeadId.Username,
      'Sales Lead Id value should be matched'
    );

    Assert.areEqual(
      'ProductRowId',
      ambitModel.DCOpportunityPackage.Opportunity.OpportunityId.ExtSysObjType,
      'Ext Sys Obj Type value should be matched'
    );
    Assert.areEqual(
      oppRecWithTeamMembers.Opp_Id__c,
      ambitModel.DCOpportunityPackage.Opportunity.OpportunityId.ExtSysObjRef,
      'Ext Sys Obj Ref value should be matched'
    );
    Assert.areEqual(
      'CRM-SF',
      ambitModel.DCOpportunityPackage.Opportunity.OpportunityId.ExtSysName,
      'ExtSysName value should be matched'
    );

    Assert.areEqual(
      'CAP',
      ambitModel.DCOpportunityPackage.PartyInformation.CustomFields.DCCustomField.FieldValue,
      'Field Value value should be matched'
    );
    Assert.areEqual(
      'Customer Master',
      ambitModel.DCOpportunityPackage.PartyInformation.CustomFields.DCCustomField.FieldName,
      'Field Name value should be matched'
    );
  }

  @isTest
  static void createProductAmountMapTest() {
    //GIVEN items
    List<OpportunityLineItem> items = new List<OpportunityLineItem>{
      new OpportunityLineItem(
        Id = Lib_FakeIdGenerator.getMockId(OpportunityLineItem.SObjectType),
        Product2Id = Lib_FakeIdGenerator.getMockId(Product2.SObjectType),
        UnitPrice = 10
      )
    };

    //WHEN calling a method
    Test.startTest();
    Map<Id, Decimal> productIdToAmountMap = LaunchAppOnOppHelper.createProductAmountMap(
      items
    );
    Test.stopTest();

    //THEN it shoould successfully create a map
    Assert.areEqual(
      1,
      productIdToAmountMap.size(),
      'should able to form a map'
    );
  }
}