force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>This new object is used to hold territory related information related to sharing</description>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Primary_Franchise_Owner__c.field-meta.xml
<CustomField>
    <fullName>Primary_Franchise_Owner__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store information related to primary owner franchise</description>
    <label>Primary Franchise Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TerritoryActionsRepository.cls
/**
 * @author MLCRM Developer
 * @since 07/2024
 * @description This class provide SOQL for Territory related queries.
 */
public with sharing class TerritoryActionsRepository {
  /**
   * @description getTerrritories method return Territories associated to teh given ids of the Territory
   * @param idsOfTerritory Id of the Territories
   * @return List<Territory__c> Territory__c List
   */
  public List<Territory__c> getTerrritories(Set<ID> idsOfTerritory) {
    if (!Schema.sObjectType.Territory__c.isQueryable()) {
      return new List<Territory__c>();
    }
    if (idsOfTerritory.isEmpty()) {
      return new List<Territory__c>();
    }
    return [
      SELECT Id, Primary_Franchise_Owner__c
      FROM Territory__c
      WHERE Id IN :idsOfTerritory
      WITH SECURITY_ENFORCED
    ];
  }
}