force-app/main/default/objects/Additional_Fund__c/Additional_Fund__c.object-meta.xml
<CustomObject>
    <label>Additional Fund</label>
    <nameField>
        <displayFormat>AF-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Funds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Fund__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non-Sensitive_Personal_Information;Source_Loan</complianceGroup>
    <description>The fund amount</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Additional_Fund__c/fields/Other_Reason__c.field-meta.xml
<CustomField>
    <fullName>Other_Reason__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non-Sensitive_Personal_Information;Source_Loan</complianceGroup>
    <description>When Other is selected, customer will provide the reason.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Other Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Additional_Fund__c/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non-Sensitive_Personal_Information;Source_Loan</complianceGroup>
    <description>The purpose of the funds.</description>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LENDING_PURPOSE_UNSPECIFIED</fullName>
                <label>Unspecified</label>
            </value>
            <value>
                <fullName>LENDING_PURPOSE_REFINANCE</fullName>
                <label>Refinance</label>
            </value>
            <value>
                <fullName>LENDING_PURPOSE_ALTERATIONS_DWELLING_EXISTING</fullName>
                <label>Non-structural alterations or additions</label>
            </value>
            <value>
                <fullName>LENDING_PURPOSE_PERSONAL_MOTOR_VEHICLE_NEW</fullName>
                <label>New car</label>
            </value>
            <value>
                <fullName>LENDING_PURPOSE_PERSONAL_MOTOR_VEHICLE_USED</fullName>
                <label>Used car</label>
            </value>
            <value>
                <fullName>LENDING_PURPOSE_PERSONAL_MOTOR_VEHICLE_OTHER</fullName>
                <label>Other vehicle type</label>
            </value>
            <value>
                <fullName>LENDING_PURPOSE_PERSONAL_MOTOR_CYCLE</fullName>
                <label>Motorcycle and scooters</label>
            </value>
            <value>
                <fullName>LENDING_PURPOSE_PERSONAL_BOAT_CARAVAN_TRAILER</fullName>
                <label>Boats, caravans and trailers</label>
            </value>
            <value>
                <fullName>LENDING_PURPOSE_PERSONAL_HOUSEHOLD_GOODS</fullName>
                <label>Household items</label>
            </value>
            <value>
                <fullName>LENDING_PURPOSE_PERSONAL_HOLIDAY_TRAVEL</fullName>
                <label>Travel</label>
            </value>
            <value>
                <fullName>LENDING_PURPOSE_PERSONAL_OTHER_INVESTMENT</fullName>
                <label>Personal investments, shares, bonds</label>
            </value>
            <value>
                <fullName>LENDING_PURPOSE_PERSONAL_OTHER_EDUCATION</fullName>
                <label>Education</label>
            </value>
            <value>
                <fullName>LENDING_PURPOSE_PERSONAL_OTHER_WEDDING</fullName>
                <label>Wedding</label>
            </value>
            <value>
                <fullName>LENDING_PURPOSE_PERSONAL_OTHER_LEGAL</fullName>
                <label>Legal fees</label>
            </value>
            <value>
                <fullName>LENDING_PURPOSE_PERSONAL_OTHER_MEDICAL</fullName>
                <label>Health</label>
            </value>
            <value>
                <fullName>LENDING_PURPOSE_PERSONAL_OTHER_MOTOR_VEHICLE_EXPENSES</fullName>
                <label>Vehicle costs</label>
            </value>
            <value>
                <fullName>LENDING_PURPOSE_PERSONAL_OTHER_PROPERTY_MAINTENANCE</fullName>
                <label>Maintenance, repairs and pools</label>
            </value>
            <value>
                <fullName>LENDING_PURPOSE_PERSONAL_OTHER</fullName>
                <label>Other</label>
            </value>
            <value>
                <fullName>LENDING_PURPOSE_ALTERATIONS_DWELLING_EXISTING_INVESTOR</fullName>
                <label>Non-Structural alterations or additions - Investment</label>
            </value>
            <value>
                <fullName>LENDING_PURPOSE_REFINANCE_INVESTOR</fullName>
                <label>Refinance - Investor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/sf-lending/objects/Additional_Fund_Purpose_Mapping__mdt/Additional_Fund_Purpose_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>To Map the Additional Funds Purpose with their category</description>
    <label>Additional Fund Purpose Mapping</label>
    <pluralLabel>Additional Funds Purpose Mapping</pluralLabel>
</CustomObject>

force-app/main/sf-lending/objects/Additional_Fund_Purpose_Mapping__mdt/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <description>Semi-colon separated values for the purpose linked to the category (name)</description>
    <label>Purpose</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/sf-lending/objects/Additional_Fund_Purpose_Mapping__mdt/fields/Purpose_Label__c.field-meta.xml
<CustomField>
    <fullName>Purpose_Label__c</fullName>
    <label>Purpose Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/sf-lending/objects/Additional_Fund_Purpose_Mapping__mdt/fields/Sorting_Category__c.field-meta.xml
<CustomField>
    <fullName>Sorting_Category__c</fullName>
    <label>Sorting Category</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/sf-lending/objects/Additional_Fund_Purpose_Mapping__mdt/fields/Sorting_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Sorting_Purpose__c</fullName>
    <description>Sorting of Purposes within each category</description>
    <label>Sorting Purpose</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/sf-lending/classes/models/AdditionalFundsViewModel.cls
/**
 * @description View Model for For Category and Purpose Mapping and Additional funds records.
 * @author Jaya Srivastava
 * @since Nov 2024
 */
public with sharing class AdditionalFundsViewModel {
  /**
   * @description Additional Funds list
   */
  @AuraEnabled
  public List<AdditionalFunds> additionalFunds { get; set; }

  /**
   * @description Additional Funds record fields
   */
  public class AdditionalFunds implements Comparable {
    /**
     * @description Amount in addition Funds
     */
    @AuraEnabled
    public Decimal amount { get; set; }

    /**
     * @description Other Reason in addition Funds
     */
    @AuraEnabled
    public String otherReason { get; set; }

    /**
     * @description Purpose in addition Funds
     */
    @AuraEnabled
    public String purpose { get; set; }

    /**
     * @description Purpose Label in addition Funds
     */
    @AuraEnabled
    public String purposeLabel { get; set; }

    /**
     * @description category in addition Funds
     */
    @AuraEnabled
    public String category { get; set; }

    /**
     * @description blank constructor for parsing
     */
    public AdditionalFunds() {
    }
    /**
     * @description Assignment of Amount, OtherReason and Purpose
     * @param addFundRecord Additional_Fund__c
     */
    public AdditionalFunds(Additional_Fund__c addFundRecord) {
      Additional_Fund_Purpose_Mapping__mdt purposeMetadata = QueryAdditionalFundsPurposeMapping.getByPurpose(
        addFundRecord.Purpose__c
      );

      this.amount = addFundRecord.Amount__c;
      this.otherReason = addFundRecord.Other_Reason__c;
      this.purpose = addFundRecord.Purpose__c;
      this.purposeLabel = purposeMetadata?.Purpose_Label__c;
      this.category = purposeMetadata?.Category__c;
    }
    /**
     * @description Sorting based on Category and Purpose
     * @param compareTo
     * @return Integer
     */
    public Integer compareTo(Object compareTo) {
      AdditionalFunds compareToFunds = (AdditionalFunds) compareTo;
      Additional_Fund_Purpose_Mapping__mdt purposeMetadata = QueryAdditionalFundsPurposeMapping.getByPurpose(
        purpose
      );
      Additional_Fund_Purpose_Mapping__mdt compareToPurposeMetadata = QueryAdditionalFundsPurposeMapping.getByPurpose(
        compareToFunds.purpose
      );

      // Sorting based on Category

      Integer categorySort = Integer.valueOf(
        purposeMetadata?.Sorting_Category__c ?? 0
      );
      Integer categoryToCompareSort = Integer.valueOf(
        compareToPurposeMetadata?.Sorting_Category__c ?? 0
      );

      if (categorySort != categoryToCompareSort) {
        return categorySort - categoryToCompareSort;
      }
      // Sorting Based on Purpose if Category Sorting is equal

      Integer purposeSort = Integer.valueOf(
        purposeMetadata?.Sorting_Purpose__c ?? 0
      );
      Integer purpseToCompareSort = Integer.valueOf(
        compareToPurposeMetadata?.Sorting_Purpose__c ?? 0
      );

      return purposeSort - purpseToCompareSort;
    }
  }

  /**
   * @description blank constructor for parsing
   */
  public AdditionalFundsViewModel() {
  }

  /**
   * @description List of Additional Funds updated in Loan Preference Record
   * @param addFundsTransformedData List<Additional_Fund__c>
   */
  public AdditionalFundsViewModel(
    List<Additional_Fund__c> addFundsTransformedData
  ) {
    this.additionalFunds = new List<AdditionalFundsViewModel.AdditionalFunds>();
    for (Additional_Fund__c addFundRecord : addFundsTransformedData) {
      this.additionalFunds.add(new AdditionalFunds(addFundRecord));
    }
    this.additionalFunds.sort();
  }
}