force-app/main/default/objects/Controlling_Post__c/Controlling_Post__c.object-meta.xml
<CustomObject>
    <label>Controlling Post</label>
    <nameField>
        <label>CPID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Controlling Posts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Controlling_Post__c/fields/CPID_CancelFag__c.field-meta.xml
<CustomField>
    <fullName>CPID_CancelFag__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Integrity_Accurate;Source_CAP</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Control Post Cancel Flag</description>
    <label>Cancelled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controlling_Post__c/fields/CPID_LanID__c.field-meta.xml
<CustomField>
    <fullName>CPID_LanID__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Caps</complianceGroup>
    <description>This store the LAN Id of the user record.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>CPID Lan ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Controlling_Post__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Integrity_Trusted;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>This indicates which CPID record is the current record (where and what banker is responsible for the CPID).

This is because 1 CPID can have multiple State / District / Area alignments and responsible bankers over time.

Active = Y,N.

No other values allowed</description>
    <label>Active Code</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Lan_Id__c.field-meta.xml
<CustomField>
    <fullName>Lan_Id__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Integrity_Trusted;Source_Salesforce</complianceGroup>
    <description>LAN ID of the user who captured the response or who the lead was routed to (if available).</description>
    <externalId>true</externalId>
    <label>Lan Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ccrm/CCRMControllingPostHelperTest.cls
/**
 * @author Naman Garg
 * @since  07/2024
 * @group CCRM (Commercial CRM)
 * @description CCRMControllingPostHelperTest is Test class to test CCRMControllingPostHelper.
 */
@isTest
public class CCRMControllingPostHelperTest {
  @isTest
  static void testGetLanIds() {
    //GIVEN List of Controlling Post records
    List<Controlling_Post__c> cpList = new List<Controlling_Post__c>{
      new Controlling_Post__c(
        Id = Lib_FakeIdGenerator.getMockId(Controlling_Post__c.SObjectType),
        Name = 'Sample Controlling Post',
        Is_Active__c = true,
        CPID_CancelFag__c = false,
        CPID_LanID__c = 'Batch'
      )
    };

    //WHEN calling a method
    Test.startTest();
    Set<String> lanIdsSet = CCRMControllingPostHelper.getLanIds(cpList);
    Test.stopTest();

    //THEN it should fetch one lan Id
    Assert.areEqual(1, lanIdsSet.size(), 'Not able to retrieve lan Id');
  }

  @isTest
  static void testFormLanIdToUserMap() {
    //GIVEN User List
    List<User> userList = new List<User>{
      new User(
        FirstName = 'Test',
        LastName = 'User',
        isActive = true,
        Lan_Id__c = 'user1',
        Id = Lib_FakeIdGenerator.getMockId(User.SObjectType)
      )
    };

    //WHEN method get called
    test.startTest();
    Map<String, User> lanIdUserMap = CCRMControllingPostHelper.formLanIdToUserMap(
      userList
    );
    test.stopTest();

    //THEN the user is able to get the filtered Controlling_Post__c records
    System.assertEquals(
      1,
      lanIdUserMap.size(),
      'Not able to form the map of User and lan Id'
    );
  }

  @isTest
  static void testSetUserLookup() {
    //GIVEN List of Controlling Post records and Map of LanId to User
    List<Controlling_Post__c> cpList = new List<Controlling_Post__c>{
      new Controlling_Post__c(
        Id = Lib_FakeIdGenerator.getMockId(Controlling_Post__c.SObjectType),
        Name = 'Sample Controlling Post',
        Is_Active__c = true,
        CPID_CancelFag__c = false,
        CPID_LanID__c = 'Batch'
      )
    };

    Map<String, User> mapOfLanIdToUser = new Map<String, User>{
      'batch' => new User(
        Id = Lib_FakeIdGenerator.getMockId(User.SObjectType),
        FirstName = 'Test',
        LastName = 'User',
        isActive = true,
        Lan_Id__c = 'batch'
      )
    };

    //WHEN calling a method
    Test.startTest();
    List<Controlling_Post__c> cpRecToUpdateList = CCRMControllingPostHelper.setUserLookup(
      cpList,
      mapOfLanIdToUser
    );
    Test.stopTest();

    //THEN it should fetch one lan Id
    Assert.areEqual(
      1,
      cpRecToUpdateList.size(),
      'No controlling post record is available for udpate'
    );
  }
}