force-app/main/default/objects/Non_Prod_Settings__c/Non_Prod_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>These settings are maintained for non production environments</description>
    <label>Non Production Settings</label>
</CustomObject>

force-app/main/default/objects/Non_Prod_Settings__c/fields/MockCallouts__c.field-meta.xml
<CustomField>
    <fullName>MockCallouts__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mock callouts if needed so we display the LWC with mock responses. Enable this flag to mock the responses in lower environments</description>
    <label>MockCallouts</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/services/UIAPIServiceMock.cls
/**
 * @description Mock implementation of UI API api service, automatically injected if Non_Prod_Settings__c.MockCallouts__c is set or if the application is running in Tests
 * @author Shermal Warnakula
 * @since 09/2021
 * @group Services
 */
public with sharing class UIAPIServiceMock extends Service {
  @TestVisible
  private static final String PICKLIST_RESPONSE = getStaticResource(
    'mock_uiAPIPicklist'
  );
  public override HttpCalloutResponse getPickListValueInfo(String endPoint) {
    if (response.statusCode == null) {
      response.statusCode = 200;
      response.body = UIAPIServiceMock.PICKLIST_RESPONSE;
      response.successful = true;
    }
    return response;
  }
}