force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>The parent log object, which stores logging information on a transaction level.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/LogEntry__c/LogEntry__c.object-meta.xml
<CustomObject>
    <description>The child log record, stores logging information on a record/callout level</description>
    <label>Log Entry</label>
    <nameField>
        <displayFormat>LE-{0000}</displayFormat>
        <label>Log Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LogEntry__c/fields/ApexClassName__c.field-meta.xml
<CustomField>
    <fullName>ApexClassName__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>Name of the apex class the log entry was created from.</description>
    <label>Apex Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/fields/ApexMethodName__c.field-meta.xml
<CustomField>
    <fullName>ApexMethodName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The apex method the log entry was created for.</description>
    <label>Apex Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The parent log record.</description>
    <label>Log</label>
    <referenceTo>Log__c</referenceTo>
    <relationshipLabel>Log Entries</relationshipLabel>
    <relationshipName>Log_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/fields/LogMessage__c.field-meta.xml
<CustomField>
    <fullName>LogMessage__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>A message or description of the log entry record.</description>
    <label>Log Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>Id of the sobject record related to this log entry.</description>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/LogEvent__e.object-meta.xml
<CustomObject>
    <description>This event captures logs, log entries and secure log entries details for logs creation.</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/LogEvent__e/fields/ApexClassName__c.field-meta.xml
<CustomField>
    <fullName>ApexClassName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The apex class the log entry was created for.</description>
    <label>Apex Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/ApexMethodName__c.field-meta.xml
<CustomField>
    <fullName>ApexMethodName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The apex method the log entry was created for.</description>
    <label>Apex Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/LogMessage__c.field-meta.xml
<CustomField>
    <fullName>LogMessage__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>A message or description of the log entry record.</description>
    <label>Log Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Id of the sobject record related to this log entry.</description>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SecureLogEntry__c/SecureLogEntry__c.object-meta.xml
<CustomObject>
    <description>Secure log records that store logging information on a record/callout level</description>
    <label>Secure Log Entry</label>
    <nameField>
        <displayFormat>SLE-{0000}</displayFormat>
        <label>Secure Log Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Secure Log Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SecureLogEntry__c/fields/ApexClassName__c.field-meta.xml
<CustomField>
    <fullName>ApexClassName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Name of the apex class the secure log entry was created from.</description>
    <label>Apex Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SecureLogEntry__c/fields/ApexMethodName__c.field-meta.xml
<CustomField>
    <fullName>ApexMethodName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The apex method the secure log entry was created for.</description>
    <label>Apex Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SecureLogEntry__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The parent log record.</description>
    <label>Log</label>
    <referenceTo>Log__c</referenceTo>
    <relationshipLabel>Secure Log Entries</relationshipLabel>
    <relationshipName>Secure_Log_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/logging/LogEntryTriggerHandler.cls
/**
 * @author Greg Shaw
 * @since Nov 2023
 * @description Handler Apex to create `Log__c`, `LogEntry__c` and `SecureLogEntry__c` records when `LogEvent__e` is published
 */

public with sharing class LogEntryTriggerHandler extends Lib_TriggerHandler {
  /**
   * @description Constructor to call the trigger framework
   * which will call the appropriate methods such as onAfterInsert etc.
   */
  public LogEntryTriggerHandler() {
    super();
  }

  /**
   * @description process LogEntry__c records before deletion.
   */
  public override void onBeforeDelete() {
    deleteContentDocuments(records);
  }

  /**
   * @description delete ContentDocument records referenced by LogEntry__c records
   * @param lstLogEntries list of LogEntry__c records being deleted
   */
  private static void deleteContentDocuments(List<LogEntry__c> lstLogEntries) {
    Set<Id> stDocumentIds = new Set<Id>();
    String strContentDocumentPrefix = Schema.ContentDocument.getSObjectType()
      .getDescribe()
      .getKeyPrefix();
    Integer nStart;
    if (ContentDocument.getSObjectType().getDescribe().isDeletable()) {
      for (LogEntry__c oLogEntry : lstLogEntries) {
        if (
          oLogEntry.ApexClassName__c == 'ContentDocumentLinkTriggerHandler' &&
          oLogEntry.ApexMethodName__c == 'logFileDelete'
        ) {
          if (
            String.isNotEmpty(oLogEntry.RecordId__c) &&
            oLogEntry.RecordId__c.startsWith(strContentDocumentPrefix)
          ) {
            stDocumentIds.add(oLogEntry.RecordId__c);
          } else if (
            String.isNotEmpty(oLogEntry.LogMessage__c) &&
            (nStart = oLogEntry.LogMessage__c.indexOf(
              ', ' + strContentDocumentPrefix
            )) != -1
          ) {
            stDocumentIds.add(
              oLogEntry.LogMessage__c.substring(nStart + 2, nStart + 20)
            );
          }
        }
      }
      List<ContentDocument> lstDocuments = [
        SELECT Id
        FROM ContentDocument
        WHERE Id IN :stDocumentIds
      ];
      if (lstDocuments.size() > 0) {
        // We don't care if some of the Documents are not found. They are being deleted anyway.
        Database.delete(lstDocuments, false);
      }
    }
  }
}