force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>The parent log object, which stores logging information on a transaction level.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/APIVersion__c.field-meta.xml
<CustomField>
    <fullName>APIVersion__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>The org&apos;s current API version</description>
    <label>API Version</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/EnvironmentType__c.field-meta.xml
<CustomField>
    <fullName>EnvironmentType__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>The type of environment in which the log was created</description>
    <label>Environment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>Scratch org</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/InstanceName__c.field-meta.xml
<CustomField>
    <fullName>InstanceName__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>The name of the instance</description>
    <label>Instance Name</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>When the transaction starts</description>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/TraceId__c.field-meta.xml
<CustomField>
    <fullName>TraceId__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>Trace Id of the transaction.</description>
    <label>Trace Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/TransactionContext__c.field-meta.xml
<CustomField>
    <fullName>TransactionContext__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>Context of the transaction: trigger, batch, future etc.</description>
    <label>Transaction Context</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/UserProfile__c.field-meta.xml
<CustomField>
    <fullName>UserProfile__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>Profile of the user who created the log</description>
    <label>User Profile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/UserRole__c.field-meta.xml
<CustomField>
    <fullName>UserRole__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>Role of the user who created the log</description>
    <label>User Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/LogEntry__c.object-meta.xml
<CustomObject>
    <description>The child log record, stores logging information on a record/callout level</description>
    <label>Log Entry</label>
    <nameField>
        <displayFormat>LE-{0000}</displayFormat>
        <label>Log Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LogEntry__c/fields/ApexClassName__c.field-meta.xml
<CustomField>
    <fullName>ApexClassName__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>Name of the apex class the log entry was created from.</description>
    <label>Apex Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/fields/ApexMethodName__c.field-meta.xml
<CustomField>
    <fullName>ApexMethodName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The apex method the log entry was created for.</description>
    <label>Apex Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/fields/LoggingLevel__c.field-meta.xml
<CustomField>
    <fullName>LoggingLevel__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>The logging level of the log entry record.</description>
    <label>Logging Level</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The origin of the request, an Apex class, a component or a flow.</description>
    <label>Origin</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/fields/UsedCallouts__c.field-meta.xml
<CustomField>
    <fullName>UsedCallouts__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>The number of Web service statements that have been processed.</description>
    <label>Used Callouts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/fields/UsedCPUTime__c.field-meta.xml
<CustomField>
    <fullName>UsedCPUTime__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>The CPU time (in milliseconds) that has been used in the current transaction.</description>
    <label>Used CPU Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/LogEvent__e.object-meta.xml
<CustomObject>
    <description>This event captures logs, log entries and secure log entries details for logs creation.</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/LogEvent__e/fields/ApexClassName__c.field-meta.xml
<CustomField>
    <fullName>ApexClassName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The apex class the log entry was created for.</description>
    <label>Apex Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/ApexMethodName__c.field-meta.xml
<CustomField>
    <fullName>ApexMethodName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The apex method the log entry was created for.</description>
    <label>Apex Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/APIVersion__c.field-meta.xml
<CustomField>
    <fullName>APIVersion__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The org&apos;s current API version</description>
    <label>API Version</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/EnvironmentType__c.field-meta.xml
<CustomField>
    <fullName>EnvironmentType__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The type of environment in which the log was created</description>
    <label>Environment Type</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/InstanceName__c.field-meta.xml
<CustomField>
    <fullName>InstanceName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The name of the instance</description>
    <label>Instance Name</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/LoggingLevel__c.field-meta.xml
<CustomField>
    <fullName>LoggingLevel__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The logging level of the log entry record.</description>
    <label>Logging Level</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The origin of the request, an Apex class, a component or a flow.</description>
    <label>Origin</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The payload that is sent or received which contains transaction/card/customer details.</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>When the transaction starts</description>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/TraceId__c.field-meta.xml
<CustomField>
    <fullName>TraceId__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Trace Id of the transaction.</description>
    <label>Trace Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/TransactionContext__c.field-meta.xml
<CustomField>
    <fullName>TransactionContext__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Context of the transaction: trigger, batch, future etc.</description>
    <label>Transaction Context</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/UsedCallouts__c.field-meta.xml
<CustomField>
    <fullName>UsedCallouts__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The number of Web service statements that have been processed.</description>
    <label>Used Callouts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/UsedCPUTime__c.field-meta.xml
<CustomField>
    <fullName>UsedCPUTime__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The CPU time (in milliseconds) that has been used in the current transaction.</description>
    <label>Used CPU Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/UserProfile__c.field-meta.xml
<CustomField>
    <fullName>UserProfile__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Profile of the user who created the log</description>
    <label>User Profile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/UserRole__c.field-meta.xml
<CustomField>
    <fullName>UserRole__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Role of the user who created the log</description>
    <label>User Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SecureLogEntry__c/SecureLogEntry__c.object-meta.xml
<CustomObject>
    <description>Secure log records that store logging information on a record/callout level</description>
    <label>Secure Log Entry</label>
    <nameField>
        <displayFormat>SLE-{0000}</displayFormat>
        <label>Secure Log Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Secure Log Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SecureLogEntry__c/fields/ApexClassName__c.field-meta.xml
<CustomField>
    <fullName>ApexClassName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Name of the apex class the secure log entry was created from.</description>
    <label>Apex Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SecureLogEntry__c/fields/ApexMethodName__c.field-meta.xml
<CustomField>
    <fullName>ApexMethodName__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The apex method the secure log entry was created for.</description>
    <label>Apex Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SecureLogEntry__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <complianceGroup>Integrity - Accurate;Source - Salesforce;Source - Fabric;Source - OCV;Privacy - Personal Information</complianceGroup>
    <description>The payload that is sent or received which contains transaction/card/customer details.</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/logging/LogEventTriggerHandlerTest.cls
/**
 * @author Nakul Kumar, Jasmine Nguyen
 * @since July 2022
 * @description Test class for {@link LogEventTriggerHandler and LogEventTrigger}
 */

@IsTest
public with sharing class LogEventTriggerHandlerTest {
  @IsTest
  static void testPublishLogEventWithPayload() {
    DateTime startTime = DateTime.now();
    String traceId = 'TI_' + String.valueOf(startTime);
    LogEvent__e logEvent = new LogEvent__e(
      APIVersion__c = '53.0',
      EnvironmentType__c = 'Sandbox',
      InstanceName__c = 'TestD',
      StartTime__c = startTime,
      TraceId__c = traceId,
      TransactionContext__c = 'TC_' + String.valueOf(startTime),
      UserProfile__c = 'SystemAdministrator',
      UserRole__c = 'Engineer',
      ApexClassName__c = 'LogEvenHandler',
      ApexMethodName__c = 'testPublishLogEvent',
      LoggingLevel__c = 'INFO',
      Origin__c = 'Apex',
      Payload__c = 'Test Payload with PII data',
      UsedCallouts__c = 100,
      UsedCPUTime__c = 200,
      UsedDMLStatements__c = 100,
      UsedFutureCalls__c = 5,
      UsedHeapSize__c = 1024,
      UsedQueueableJobs__c = 4,
      UsedSOQLQueries__c = 150
    );
    List<LogEvent__e> logEvents = new List<LogEvent__e>();
    logEvents.add(logEvent);
    logEvents.add(logEvent.clone());
    Test.startTest();
    List<Database.SaveResult> results = EventBus.publish(logEvents);
    Test.stopTest();
    List<Log__c> logs = [
      SELECT Id, TraceId__c
      FROM Log__c
      WHERE TraceId__c = :traceId
    ];
    System.assert(logs.size() == 1, 'Error in Log creation');
    List<SecureLogEntry__c> secureLogEntries = [
      SELECT Id
      FROM SecureLogEntry__c
      WHERE Log__c = :logs[0].Id
    ];
    System.assert(
      secureLogEntries.size() == 2,
      'Error in Secure Log Entries creation'
    );
    List<LogEntry__c> logEntries = [
      SELECT Id
      FROM LogEntry__c
      WHERE Log__c = :logs[0].Id
    ];
    System.assertEquals(2, logEntries.size(), 'Error in Log Entries creation');
  }

  @IsTest
  static void testPublishLogEventWithoutPayload() {
    DateTime startTime = DateTime.now();
    String traceId = 'TI_' + String.valueOf(startTime);
    LogEvent__e logEvent = new LogEvent__e(
      APIVersion__c = '53.0',
      EnvironmentType__c = 'Sandbox',
      InstanceName__c = 'TestD',
      StartTime__c = startTime,
      TraceId__c = traceId,
      TransactionContext__c = 'TC_' + String.valueOf(startTime),
      UserProfile__c = 'SystemAdministrator',
      UserRole__c = 'Engineer',
      ApexClassName__c = 'LogEvenHandler',
      ApexMethodName__c = 'testPublishLogEvent',
      LoggingLevel__c = 'INFO',
      Origin__c = 'Apex',
      UsedCallouts__c = 100,
      UsedCPUTime__c = 200,
      UsedDMLStatements__c = 100,
      UsedFutureCalls__c = 5,
      UsedHeapSize__c = 1024,
      UsedQueueableJobs__c = 4,
      UsedSOQLQueries__c = 150
    );
    List<LogEvent__e> logEvents = new List<LogEvent__e>();
    logEvents.add(logEvent);
    Test.startTest();
    List<Database.SaveResult> results = EventBus.publish(logEvents);
    Test.stopTest();
    List<Log__c> logs = [
      SELECT Id, TraceId__c
      FROM Log__c
      WHERE TraceId__c = :traceId
    ];
    System.assert(logs.size() == 1, 'Error in Log creation');
    List<LogEntry__c> logEntries = [
      SELECT Id
      FROM LogEntry__c
      WHERE Log__c = :logs[0].Id
    ];
    System.assertEquals(1, logEntries.size(), 'Error in Log Entries creation');
  }
}