force-app/main/default/objects/Lead/fields/ABN__c.field-meta.xml
<CustomField>
    <fullName>ABN__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Source_Salesforce;Integrity_Accurate</complianceGroup>
    <description>Australian Business Number</description>
    <label>ABN</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ABN_Validation_Status__c.field-meta.xml
<CustomField>
    <fullName>ABN_Validation_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>ABN validation status received from australian business registry</description>
    <label>ABN Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Validation in progress</fullName>
            </value>
            <value>
                <fullName>Validation Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/ACN__c.field-meta.xml
<CustomField>
    <fullName>ACN__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Source_Salesforce;Integrity_Accurate</complianceGroup>
    <description>Australian Company Number (ACN)</description>
    <label>ACN</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ACN_Validation_Status__c.field-meta.xml
<CustomField>
    <fullName>ACN_Validation_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>ABN validation status received from australian business registry</description>
    <label>ACN Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Validation in progress</fullName>
            </value>
            <value>
                <fullName>Validation Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Registered_Company__c.field-meta.xml
<CustomField>
    <fullName>Registered_Company__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Select if company has not yet been registered</description>
    <inlineHelpText>Entity not yet registered for ABN/ACN</inlineHelpText>
    <label>Is this business registered?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Skip_Validations__c.field-meta.xml
<CustomField>
    <fullName>Skip_Validations__c</fullName>
    <complianceGroup>Source - Salesforce;Privacy - Non Personal Information;Integrity - Trusted</complianceGroup>
    <description>This field is to Skip Validation Rules when updating records through Apex.</description>
    <label>Skip Validations</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ccrm/ValidateABNACNControllerTest.cls
/**
 * @author Dhanashree Deshmukh
 * @since 04/2025
 * @description test class for ValidateABNACNController
 */
@isTest
private class ValidateABNACNControllerTest {
  static Lib_MockProvider leadRepoMock;
  static Lib_MockProvider dmlRepoMock;
  static void registerMocks() {
    dmlRepoMock = Lib_MockProvider.forType(DMLRepository.class);
    leadRepoMock = Lib_MockProvider.forType(LeadActionsRepository.class);
  }

  @isTest
  static void testUpdateWithInvalidACN() {
    registerMocks();
    Lead leadRec = new Lead(
      Id = Lib_FakeIdGenerator.getMockId(Lead.SObjectType),
      RecordTypeId = RTLead.commercialLead,
      ABN__c = '11005 357 522',
      ACN__c = '004085616',
      LeadSource = 'Individual',
      Registered_Company__c = 'Yes',
      ABN_Validation_Status__c = 'Active',
      ACN_Validation_Status__c = 'Active',
      Skip_Validations__c = 'copyLeadId'
    );
    leadRepoMock.mock('getLead', leadRec);
    Test.startTest();
    ValidateABNACNController.validateAbnAcnForCallout(leadRec.Id);
    Test.stoptest();
    Assert.areEqual(
      'Active',
      leadRec.ABN_Validation_Status__c,
      'ABN status should get updated to active'
    );
  }
}