force-app/main/default/objects/Lead/fields/ABN__c.field-meta.xml
<CustomField>
    <fullName>ABN__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Source_Salesforce;Integrity_Accurate</complianceGroup>
    <description>Australian Business Number</description>
    <label>ABN</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ABN_Validation_Status__c.field-meta.xml
<CustomField>
    <fullName>ABN_Validation_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>ABN validation status received from australian business registry</description>
    <label>ABN Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Validation in progress</fullName>
            </value>
            <value>
                <fullName>Validation Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/ACN__c.field-meta.xml
<CustomField>
    <fullName>ACN__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Source_Salesforce;Integrity_Accurate</complianceGroup>
    <description>Australian Company Number (ACN)</description>
    <label>ACN</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ACN_Validation_Status__c.field-meta.xml
<CustomField>
    <fullName>ACN_Validation_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>ABN validation status received from australian business registry</description>
    <label>ACN Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Validation in progress</fullName>
            </value>
            <value>
                <fullName>Validation Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <defaultValue>IF(
    NOT(
        CONTAINS( 
            $User.Username,&apos;unica.integration@anzx.com&apos;
        )
    ),
    CASE( 
        $RecordType.Name ,&apos;Commercial CRM Lead&apos;, 
            IF((WEEKDAY(DATEVALUE(NOW() + VALUE($Label.CCRM_ExpiryDateDays))) = 1)
                , NOW() + (VALUE($Label.CCRM_ExpiryDateDays) + 1),
                IF((WEEKDAY(DATEVALUE(NOW() + VALUE($Label.CCRM_ExpiryDateDays))) = 7)
                    , NOW() + VALUE($Label.CCRM_ExpiryDateDays) + 2
                    , NOW() + (VALUE($Label.CCRM_ExpiryDateDays))
                )
            ),
            &apos;Referral&apos;,
            IF((WEEKDAY(DATEVALUE(NOW() + VALUE($Label.Referral_ExpiryDateDays))) = 1)
                , NOW() + (VALUE($Label.Referral_ExpiryDateDays) + 1),
                IF((WEEKDAY(DATEVALUE(NOW() + VALUE($Label.Referral_ExpiryDateDays))) = 7)
                    , NOW() + VALUE($Label.Referral_ExpiryDateDays) + 2
                    , NOW() + (VALUE($Label.Referral_ExpiryDateDays))
                )
            ),
            NULL

    )
    ,NULL
)</defaultValue>
    <description>Expiry date of the lead.</description>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Followup_Date__c.field-meta.xml
<CustomField>
    <fullName>Followup_Date__c</fullName>
    <complianceGroup>Privacy_Non_Personal_Information;Source_Salesforce;Integrity_Accurate</complianceGroup>
    <description>Next followup date</description>
    <label>Follow Up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Quality__c.field-meta.xml
<CustomField>
    <fullName>Lead_Quality__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The quality of the lead.</description>
    <label>Lead Quality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Very Good</fullName>
            </value>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Average</fullName>
            </value>
            <value>
                <fullName>Poor</fullName>
            </value>
            <value>
                <fullName>Very Poor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Skip_Validations__c.field-meta.xml
<CustomField>
    <fullName>Skip_Validations__c</fullName>
    <complianceGroup>Source - Salesforce;Privacy - Non Personal Information;Integrity - Trusted</complianceGroup>
    <description>This field is to Skip Validation Rules when updating records through Apex.</description>
    <label>Skip Validations</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SubStatus__c.field-meta.xml
<CustomField>
    <fullName>SubStatus__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Sub Status of the lead</description>
    <label>Lead Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>1st attempt made</fullName>
            </value>
            <value>
                <fullName>2nd attempt made</fullName>
            </value>
            <value>
                <fullName>3rd attempt made</fullName>
            </value>
            <value>
                <fullName>Follow up required</fullName>
            </value>
            <value>
                <fullName>Opportunity identified</fullName>
            </value>
            <value>
                <fullName>Referred to Classic</fullName>
            </value>
            <value>
                <fullName>Not interested</fullName>
            </value>
            <value>
                <fullName>Not contactable</fullName>
            </value>
            <value>
                <fullName>Auto-closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Referral.recordType-meta.xml
<RecordType>
    <fullName>Referral</fullName>
    <active>true</active>
    <businessProcess>CCRM Lead Process</businessProcess>
    <description>Create a new commercial referral</description>
    <label>Referral</label>
</RecordType>

force-app/main/default/objects/Lead_Stage_Automation__mdt/Lead_Stage_Automation__mdt.object-meta.xml
<CustomObject>
    <description>Lead Stage configurations.</description>
    <label>Lead Stage Automation</label>
    <pluralLabel>Lead Stage Automations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Lead_Stage_Automation__mdt/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead_Stage_Automation__mdt/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <label>Lead Status</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Stage_Automation__mdt/fields/Next_Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Next_Lead_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Next Lead Status based on the criteria match.</description>
    <label>Next Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In progress</fullName>
                <default>true</default>
                <label>In progress</label>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Outcome</fullName>
            </value>
            <value>
                <fullName>Opportunity Identified</fullName>
            </value>
            <value>
                <fullName>No Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Stage_Automation__mdt/fields/Response_Status__c.field-meta.xml
<CustomField>
    <fullName>Response_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Response Status from Responses logged for a particular lead.</description>
    <label>Response Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Stage_Automation__mdt/fields/Response_Type_CreateOpportunity__c.field-meta.xml
<CustomField>
    <fullName>Response_Type_CreateOpportunity__c</fullName>
    <label>Response Type CreateOpportunity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>true</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Response_Type__c/Response_Type__c.object-meta.xml
<CustomObject>
    <description>Custom Object to store Response Type information.</description>
    <label>Response Type</label>
    <nameField>
        <label>Response Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Response Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Response_Type__c/fields/Create_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Create_Opportunity__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>This flag will determine whether user can click Create Opportunity button along with Division Group</description>
    <label>Create Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Response_Type__c/fields/Response_Status__c.field-meta.xml
<CustomField>
    <fullName>Response_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Response status for the corresponding campaign</description>
    <label>Response Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ccrm/CCRMTaskActions.cls
/**
 * @author Sahil Sachar
 * @since 12/2021
 * @description CCRM Task Actions consists of all the Task related methods.
 */
@SuppressWarnings('PMD.StdCyclomaticComplexity, PMD.CyclomaticComplexity')
public with sharing class CCRMTaskActions {
  @TestVisible
  private static final String RESPONSE_DELETE_ERROR_MESSAGE = 'You cannot delete Responses.';
  private static final String LEAD_AUTO_UPDATE_ERROR_MESSAGE = 'Error Message: Lead cannot be auto updated. Please contact your System Administrator.';

  /**
   * @description Update CCRM Leads based on Logged Response (Task).
   * @name updateCCRMLeads
   * @param listOfLeadResponses List of User Ids to fetch Name.
   */
  public static void updateCCRMLeads(List<Task> listOfLeadResponses) {
    List<Lead> updatedLeads = new List<Lead>();
    Map<String, Task> mapLeadResponses = new Map<String, Task>();
    List<String> selectedLeadStatus = new List<String>();
    Set<String> selectedResponseType = new Set<String>();
    Map<Id, Response_Type__c> mapResponseTypeMeta;
    Boolean isLeadResponse = false;

    for (Task leadResponseRec : listOfLeadResponses) {
      if (
        leadResponseRec.WhoId != null &&
        leadResponseRec.WhoId.getSObjectType() == Lead.sObjectType &&
        leadResponseRec.RecordTypeId == CCRMConstants.LEAD_RESPONSE_RT_ID
      ) {
        mapLeadResponses.put(leadResponseRec.WhoId, leadResponseRec);
        selectedResponseType.add(leadResponseRec.Response_Type__c);
      }
    }
    mapResponseTypeMeta = new Map<Id, Response_Type__c>(
      [
        SELECT Id, Response_Status__c, Create_Opportunity__c
        FROM Response_Type__c
        WHERE Id IN :selectedResponseType
      ]
    );

    try {
      if (
        !mapLeadResponses.isEmpty() &&
        Schema.sObjectType.Lead_Stage_Automation__mdt.isQueryable() &&
        Schema.sObjectType.Lead.isQueryable()
      ) {
        List<Lead_Stage_Automation__mdt> mapLeadStageMetadata = [
          SELECT
            Id,
            Lead_Status__c,
            Next_Lead_Status__c,
            Response_Status__c,
            Response_Type_CreateOpportunity__c,
            isActive__c
          FROM Lead_Stage_Automation__mdt
          WHERE
            isActive__c = TRUE
            AND Lead_Status__c != ''
            AND Next_Lead_Status__c != ''
            AND Response_Status__c != ''
        ];
        for (
          Lead_Stage_Automation__mdt mapLeadStageConfig : mapLeadStageMetadata
        ) {
          if (mapLeadStageConfig.isActive__c) {
            selectedLeadStatus.addAll(
              mapLeadStageConfig.Lead_Status__c.split(',')
            );
          }
        }
        for (Lead leadRecord : [
          SELECT Id, Status, SubStatus__c, Followup_Date__c, Skip_Validations__c
          FROM Lead
          WHERE
            Id IN :mapLeadResponses.keySet()
            AND Status IN :selectedLeadStatus
            AND RecordTypeId = :CCRMConstants.CCRM_LEAD_RT_ID
        ]) {
          for (
            Lead_Stage_Automation__mdt checkAutoStages : mapLeadStageMetadata
          ) {
            if (
              checkAutoStages.Lead_Status__c.contains(leadRecord.Status) &&
              mapLeadResponses.get(leadRecord.Id).Response_Status__c ==
              checkAutoStages.Response_Status__c
            ) {
              if (
                String.valueOf(
                  mapResponseTypeMeta.get(
                      mapLeadResponses.get(leadRecord.Id).Response_Type__c
                    )
                    .Create_Opportunity__c
                ) == checkAutoStages.Response_Type_CreateOpportunity__c &&
                !String.isBlank(
                  checkAutoStages.Response_Type_CreateOpportunity__c
                )
              ) {
                leadRecord.Status = checkAutoStages.Next_Lead_Status__c;
              } else if (
                String.isBlank(
                  checkAutoStages.Response_Type_CreateOpportunity__c
                )
              ) {
                leadRecord.Status = checkAutoStages.Next_Lead_Status__c;
              }
              if (!updatedLeads.contains(leadRecord)) {
                leadRecord.Skip_Validations__c = leadRecord.Skip_Validations__c !=
                  'SkipValidation'
                  ? 'SkipValidation'
                  : 'Validate';
                leadRecord.SubStatus__c = checkAutoStages.Response_Status__c;
                leadRecord.Followup_Date__c = mapLeadResponses.get(
                      leadRecord.Id
                    )
                    .ActivityDate == leadRecord.Followup_Date__c
                  ? leadRecord.Followup_Date__c
                  : mapLeadResponses.get(leadRecord.Id).ActivityDate;
                leadRecord.Lead_Quality__c = mapLeadResponses.get(leadRecord.Id)
                  .Lead_Quality__c;
                updatedLeads.add(leadRecord);
              }
            }
          }
        }
      }
      if (Schema.sObjectType.Lead.isUpdateable() || !updatedLeads.isEmpty()) {
        setExpiryDateFromLogResponse(
          mapLeadResponses,
          mapResponseTypeMeta,
          updatedLeads
        );
        Database.update(updatedLeads);
      }
    } catch (Exception err) {
      String dmlErrorMsg = err.getDmlMessage(0);
      throw new AuraHandledException(
        String.isBlank(dmlErrorMsg)
          ? LEAD_AUTO_UPDATE_ERROR_MESSAGE
          : dmlErrorMsg
      );
    }
  }

  /**
   * @description Validate ABN ACN when task reponse status is referral made
   * @param records list of task records from the trigger
   */
  public static void validateLeadAbnACN(List<Task> records) {
    List<id> leadIds = new List<Id>();
    List<Task> taskList = new List<Task>();
    for (Task record : records) {
      if (
        String.isNotBlank(record.WhoId) &&
        record.Response_Status__c == 'Referral Made'
      ) {
        leadIds.add(record.WhoId);
        taskList.add(record);
      }
    }

    Map<Id, Lead> previousLeadMap = new Map<Id, Lead>(
      [
        SELECT
          Id,
          ABN__c,
          ACN__c,
          ABN_Validation_Status__c,
          ACN_Validation_Status__c
        FROM Lead
        WHERE Id IN :leadIds
      ]
    );

    for (Task taskRec : taskList) {
      Lead leadRec = previousLeadMap.containsKey(taskRec.WhoId)
        ? previousLeadMap.get(taskRec.WhoId)
        : new Lead();
      if (
        leadRec != null &&
        ((String.isNotBlank(leadRec.ABN__c) &&
        leadRec.ABN_Validation_Status__c != 'Active') ||
        (String.isNotBlank(leadRec.ACN__c) &&
        leadRec.ACN_Validation_Status__c != 'Active'))
      ) {
        taskRec.addError(CCRMConstants.ABN_ACN_VALIDATION_MESSAGE);
      }
    }
  }

  /**
   * @description Set exipry date when response log created without follow up date
   * @name setExpiryDateFromLogsResponse
   * @param mapLeadResponses Map of Task
   * @param mapResponseTypeMeta Map of response Type
   * @param updatedLeads List of Leads.
   */
  public static void setExpiryDateFromLogResponse(
    Map<String, Task> mapLeadResponses,
    Map<Id, Response_Type__c> mapResponseTypeMeta,
    List<Lead> updatedLeads
  ) {
    Set<Id> leadIds = new Map<Id, Lead>(updatedLeads).keySet();
    Map<Id, Date> mapOfCampaign = new Map<Id, Date>();

    //Get campaign end date for lead.
    //Lead relationship with Camapign is through junction object - Campaign member
    if (Schema.sObjectType.CampaignMember.isQueryable()) {
      for (CampaignMember cm : [
        SELECT Campaign.EndDate, LeadId
        FROM CampaignMember
        WHERE leadid = :leadIds
      ]) {
        mapOfCampaign.put(cm.LeadId, cm.Campaign.EndDate);
      }
    }

    for (Lead leadRecord : updatedLeads) {
      if (mapLeadResponses.get(leadRecord.Id).ActivityDate == null) {
        Boolean canCreateOpportunity = mapResponseTypeMeta.get(
            mapLeadResponses.get(leadRecord.Id).Response_Type__c
          )
          .Create_Opportunity__c;
        String responseStatus = mapResponseTypeMeta.get(
            mapLeadResponses.get(leadRecord.Id).Response_Type__c
          )
          .Response_Status__c;
        //Set lead expiry only when Log response status is Accepted and Create Opportunity is set to true
        if (canCreateOpportunity && responseStatus == 'Accepted') {
          Date campaignExpiryDate = mapOfCampaign.get(leadRecord.Id);
          leadRecord.Followup_Date__c = null;
          Date todaysDate = Date.valueOf(
            System.today() + Integer.valueOf(System.Label.CCRM_Today_Date)
          );
          Date updatedDate = DateTimeUtils.getWeekday(
            todaysDate
              .addDays(
                integer.valueOf(
                  System.Label.CCRM_ExtendLeadExpiryDateWhenResponseLogCreated
                )
              ),
            false,
            true
          );
          leadRecord.Expiry_Date__c = updatedDate > campaignExpiryDate
            ? campaignExpiryDate
            : updatedDate;
        }
      }
    }
  }

  /**
   * @description General function to populate fields
   * @name populateData
   * @param records tasks to populate
   * @param oldMap contains the map which holds the previous values of task records
   */
  public static void populateData(Task[] records, Map<Id, Task> oldMap) {
    for (Task record : records) {
      maskDescription(record);
      maskSubject(record);
    }
  }

  /**
   * @description Mask Description of Task
   * @name maskDescription
   * @param record Task to mask
   */
  public static void maskDescription(Task record) {
    if (!String.isBlank(record.Description)) {
      record.Description = TextUtils.maskData(record.Description);
    }
  }

  /**
   * @description Mask Subject of Task
   * @name maskSubject
   * @param record Task to mask
   */
  public static void maskSubject(Task record) {
    if (!String.isBlank(record.Subject)) {
      record.Subject = TextUtils.maskData(record.Subject);
    }
  }

  /**
   * @description Prevent deletion of tasks that is a response logged to a lead
   * @name preventDelete
   * @param records tasks to check for preventing deletion
   */
  public static void preventDelete(List<Task> records) {
    for (Task record : records) {
      if (record.RecordTypeId == CCRMConstants.LEAD_RESPONSE_RT_ID) {
        record.addError(RESPONSE_DELETE_ERROR_MESSAGE);
      }
    }
  }
}