force-app/main/default/objects/Lead/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <defaultValue>IF(
    NOT(
        CONTAINS( 
            $User.Username,&apos;unica.integration@anzx.com&apos;
        )
    ),
    CASE( 
        $RecordType.Name ,&apos;Commercial CRM Lead&apos;, 
            IF((WEEKDAY(DATEVALUE(NOW() + VALUE($Label.CCRM_ExpiryDateDays))) = 1)
                , NOW() + (VALUE($Label.CCRM_ExpiryDateDays) + 1),
                IF((WEEKDAY(DATEVALUE(NOW() + VALUE($Label.CCRM_ExpiryDateDays))) = 7)
                    , NOW() + VALUE($Label.CCRM_ExpiryDateDays) + 2
                    , NOW() + (VALUE($Label.CCRM_ExpiryDateDays))
                )
            ),
            &apos;Referral&apos;,
            IF((WEEKDAY(DATEVALUE(NOW() + VALUE($Label.Referral_ExpiryDateDays))) = 1)
                , NOW() + (VALUE($Label.Referral_ExpiryDateDays) + 1),
                IF((WEEKDAY(DATEVALUE(NOW() + VALUE($Label.Referral_ExpiryDateDays))) = 7)
                    , NOW() + VALUE($Label.Referral_ExpiryDateDays) + 2
                    , NOW() + (VALUE($Label.Referral_ExpiryDateDays))
                )
            ),
            NULL

    )
    ,NULL
)</defaultValue>
    <description>Expiry date of the lead.</description>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Lead_Outcome__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>This is the CCRM field to track the lead Outcome Type.</description>
    <label>Lead Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Identified</fullName>
            </value>
            <value>
                <fullName>No Opportunity</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LogEntry__c/LogEntry__c.object-meta.xml
<CustomObject>
    <description>The child log record, stores logging information on a record/callout level</description>
    <label>Log Entry</label>
    <nameField>
        <displayFormat>LE-{0000}</displayFormat>
        <label>Log Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LogEntry__c/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The exception message.</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ccrm/CCRMLeadExpiryHandler.cls
/**
 * @author Sahil S
 * @since  09/2021
 * @description Handler class for CCRMLeadExpiryBatch, for updating Leads with Expired status.
 */
public with sharing class CCRMLeadExpiryHandler {
  private class CustomSharingException extends Exception {
  }
  /**
   * @description method to updated selected Leads with Status as 'Expired'
   * @name updateExpiredLeads
   * @param leadList list of lead records that are having Expiry_Date__C passed are needed to be updated.
   */
  public static void updateExpiredLeads(List<Lead> leadList) {
    List<Lead> updatedLeads = markLeadAsExpired(leadList);
    saveUpdatedLeads(updatedLeads);
  }

  /**
   * @description This method returns a list of leads that has been updated as expired
   * @name markLeadAsExpired
   * @param leadList list of records to be expired
   * @return list of updated leads
   * @author Ashish Kumar
   */
  @TestVisible
  private static List<Lead> markLeadAsExpired(List<Lead> leadList) {
    List<Lead> updatedLeads = new List<Lead>();
    Group objGrp;
    Set<Id> idsOfMLExpiredLead = new Set<Id>();
    for (Lead leadRecord : leadList) {
      if (objGrp == null && CCRMLeadUtil.isMLCRMLeadType(leadRecord)) {
        objGrp = [
          SELECT Id
          FROM Group
          WHERE Name = 'ML Expired Leads' AND Type = 'Queue'
          LIMIT 1
        ];
      }
      if (CCRMLeadUtil.isMLCRMLeadType(leadRecord)) {
        leadRecord.Status = CCRMConstants.STATUS_EXPIRED;
        leadRecord.OwnerId = objGrp.Id;
        idsOfMLExpiredLead.add(leadRecord.Id);
      } else if (CCRMLeadUtil.isCCRMLeadType(leadRecord)) {
        leadRecord.Status = CCRMConstants.STATUS_OUTCOME;
        leadRecord.Lead_Outcome__c = CCRMConstants.STATUS_EXPIRED;
      }
      updatedLeads.add(leadRecord);
    }
    return updatedLeads;
  }

  /**
   * @description This method returns a list of leads that has been updated to expiry
   * @name saveUpdatedLeads
   * @param updatedLeads list of updated leads
   * @author Ashish Kumar
   */
  @TestVisible
  private static void saveUpdatedLeads(List<Lead> updatedLeads) {
    try {
      if (Schema.sObjectType.Lead.isUpdateable() && !updatedLeads.isEmpty()) {
        List<Database.SaveResult> results = Database.update(
          updatedLeads,
          false,
          AccessLevel.USER_MODE
        );
        List<WrapSharingError> lstOfSharingError;
        for (Database.SaveResult saveResult : results) {
          if (!saveResult.isSuccess()) {
            lstOfSharingError = new List<WrapSharingError>();
            for (Database.Error error : saveResult.getErrors()) {
              lstOfSharingError.add(
                new WrapSharingError(saveResult.getId(), error.getMessage())
              );
            }
          }
        }
        if (lstOfSharingError != null && !lstOfSharingError.isEmpty()) {
          Logger.error(
            'Error occured while updating Lead Status to Expired.',
            processSharingException(lstOfSharingError)
          );
          Logger.saveLog();
        }
      }
    } catch (Exception e) {
      Logger.error(
        'Error occured while updating Lead Status to Expired. ' +
        'More details: ' +
        e.getMessage(),
        e
      );
      Logger.saveLog();
    }
  }

  /**
   * @description This method is return custom error message related to sharing record error
   * @name processSharingException
   * @param lstOfSharingError list of record on which error occurs
   * @return Exception exception object
   * @author Ashish Kumar
   * @US CC-4418
   */
  private static Exception processSharingException(
    List<wrapSharingError> lstOfSharingError
  ) {
    Schema.DescribeFieldResult objDescribe = LogEntry__c.ExceptionMessage__c.getDescribe();
    Integer lengthOfField = objDescribe.getLength();
    return new CustomSharingException(
      JSON.serializePretty(lstOfSharingError).length() > lengthOfField
        ? JSON.serializePretty(lstOfSharingError).substring(0, lengthOfField)
        : JSON.serializePretty(lstOfSharingError)
    );
  }

  /**
   * @description This is wrapper class to create JSON in userid and recordid mapping
   * @name WrapSharingError
   * @author Ashish Kumar
   * @US CC-4418
   */
  public class WrapSharingError {
    public String recordId;
    public String errMsg;

    /**
     * @description This is constructor to create JSON in userid and recordid mapping
     * @name WrapSharingError
     * @param recordId sobject recordid for which sharing failed
     * @param errMsg error message
     * @author Ashish Kumar
     * @US CC-4418
     */
    public WrapSharingError(String recordId, String errMsg) {
      this.recordId = recordId;
      this.errMsg = errMsg;
    }
  }
}