force-app/main/default/objects/Customer_Task_Configuration__c/Customer_Task_Configuration__c.object-meta.xml
<CustomObject>
    <description>Customer Task Configuration for implementing Push 2 App feature</description>
    <label>Customer Task Configuration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Task Configuration</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Task_Configuration__c/fields/AEM_Content_Id__c.field-meta.xml
<CustomField>
    <fullName>AEM_Content_Id__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non Personal Information;Source - AEM</complianceGroup>
    <description>Used to store the content Id from AEM.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>AEM Content Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer_Task_Configuration__c/fields/Applicable_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Record_Types__c</fullName>
    <complianceGroup>Integrity - Trusted;Privacy - Non Personal Information;Source - Salesforce</complianceGroup>
    <description>Applicable RT of the SObject for which the configuration is valid</description>
    <label>Applicable Record Types</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>SObject_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account_Closure</fullName>
                <label>Account Closure</label>
            </value>
            <value>
                <fullName>ANZx_Complaint</fullName>
                <label>ANZ Plus Complaint</label>
            </value>
            <value>
                <fullName>ATM_Dispute</fullName>
                <label>ATM</label>
            </value>
            <value>
                <fullName>BPAY_Dispute</fullName>
                <label>BPAY</label>
            </value>
            <value>
                <fullName>Card_Dispute</fullName>
                <label>Card</label>
            </value>
            <value>
                <fullName>CFMS_Migrated_Case</fullName>
                <label>CFMS Migrated Case</label>
            </value>
            <value>
                <fullName>Credit_Referral</fullName>
                <label>Credit Referral</label>
            </value>
            <value>
                <fullName>Customer_Complaint</fullName>
                <label>Customer Complaint</label>
            </value>
            <value>
                <fullName>Customer_Feedback</fullName>
                <label>Customer Feedback</label>
            </value>
            <value>
                <fullName>Direct_Debit_Dispute</fullName>
                <label>Direct Debit</label>
            </value>
            <value>
                <fullName>Direct_Entry_Dispute</fullName>
                <label>Direct Entry</label>
            </value>
            <value>
                <fullName>False_Customer_Profile</fullName>
                <label>False Customer Profile</label>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Fraud_Check</fullName>
                <label>Fraud Check</label>
            </value>
            <value>
                <fullName>General_Inquiry</fullName>
                <label>General Enquiry</label>
            </value>
            <value>
                <fullName>Identity</fullName>
            </value>
            <value>
                <fullName>ID_Ops_Assistance</fullName>
                <label>ID Ops Assistance</label>
            </value>
            <value>
                <fullName>KYC_QA</fullName>
                <label>KYC QA</label>
            </value>
            <value>
                <fullName>Non_Customer_Complaint</fullName>
                <label>Non-Customer Complaint</label>
            </value>
            <value>
                <fullName>NPP_Dispute</fullName>
                <label>NPP</label>
            </value>
            <value>
                <fullName>PIN_Recovery</fullName>
                <label>PIN Recovery</label>
            </value>
            <value>
                <fullName>Profile_Update</fullName>
                <label>Profile Update</label>
            </value>
            <value>
                <fullName>Recipient_Mule</fullName>
                <label>Recipient/Mule</label>
            </value>
            <value>
                <fullName>Scam</fullName>
            </value>
            <value>
                <fullName>Selfie_Recovery</fullName>
                <label>Selfie Recovery</label>
            </value>
            <value>
                <fullName>Systemic_Issue</fullName>
                <label>Systemic Issue</label>
            </value>
            <value>
                <fullName>General_Inquiry_CMOS</fullName>
                <label>Unauthenticated Enquiry</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Task_Configuration__c/fields/Applicable_User_Role__c.field-meta.xml
<CustomField>
    <fullName>Applicable_User_Role__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Applicable User Role  for which the configuration is valid</description>
    <label>Applicable User Role</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coach</fullName>
            </value>
            <value>
                <fullName>Support_Coach</fullName>
                <label>Support Coach</label>
            </value>
            <value>
                <fullName>Coach_Lead</fullName>
                <label>Coach Lead</label>
            </value>
            <value>
                <fullName>BOH_Coach</fullName>
                <label>BOH Coach</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Task_Configuration__c/fields/Expire_After_Days__c.field-meta.xml
<CustomField>
    <fullName>Expire_After_Days__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Configuration to store after how many days this task should expire.</description>
    <label>Expire After Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Task_Configuration__c/fields/SObject_Type__c.field-meta.xml
<CustomField>
    <fullName>SObject_Type__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Name of the SObject for which the configuration is valid</description>
    <label>SObject Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Task_Data__c/Customer_Task_Data__c.object-meta.xml
<CustomObject>
    <description>Holds data to be utilised on L2 Mobile screens</description>
    <label>Customer Task Data</label>
    <nameField>
        <displayFormat>CTD-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Task Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CustomerNudgeTaskCloudEventModelTest.cls
/**
 * @author Kopal Goswami
 * @since  10/2024
 * @description Test Class for CustomerNudgeTaskCloudEventModel
 */
@IsTest
public with sharing class CustomerNudgeTaskCloudEventModelTest {
  private static final Id FAKER_TASK_ID = Lib_FakeIdGenerator.getMockId(
    Task.getSObjectType()
  );

  static Lib_MockProvider pushToAppRepoMock;
  static void registerMocks() {
    pushToAppRepoMock = Lib_MockProvider.forType(PushToAppRepository.class);
  }

  @isTest
  static void testCustomerNudgeTaskCloudEventModel() {
    registerMocks();
    pushToAppRepoMock.mock(
      'queryCustomerNudgeTaskDetails',
      mockQueryCustomerNudgeTaskDetails()
    );
    pushToAppRepoMock.mock(
      'queryCustomerTaskDataDetails',
      new Customer_Task_Data__c()
    );
    Task taskRecord = mockTaskRecord();

    // Call the constructor for CustomerNudgeTaskCloudEventModel
    CustomerNudgeTaskCloudEventModel model = new CustomerNudgeTaskCloudEventModel(
      taskRecord
    );

    // Validate the ce_type
    String expectedCeType =
      System.Label.ANZX_Customer_Nudge_event_ce_type +
      taskRecord.Status.toLowerCase();
    Assert.areEqual(expectedCeType, model.ce_type, 'ce_type is set correctly.');

    // Validate the ce_subject
    String expectedCeSubject =
      'TaskExternalId/' + taskRecord.Pub_Sub_Event_Id__c;
    Assert.areEqual(
      expectedCeSubject,
      model.ce_subject,
      'ce_subject is set correctly.'
    );

    // Validate the ce_dataschema
    Assert.areEqual(
      System.Label.ANZX_Customer_Nudge_Event_Proto_Data_Schema,
      model.ce_dataschema,
      'ce_dataschema is set correctly.'
    );

    // Validate the ce_partitionkey
    String expectedPartitionKey =
      'TaskExternalId/' + taskRecord.Pub_Sub_Event_Id__c;
    Assert.areEqual(
      expectedPartitionKey,
      model.ce_partitionkey,
      'ce_partitionkey is set correctly.'
    );

    // Validate the ce_xtargets
    String expectedXtargets = 'Notification/' + taskRecord.Pub_Sub_Event_Id__c;
    Assert.areEqual(
      expectedXtargets,
      model.ce_xtargets,
      'ce_xtargets is set correctly.'
    );

    // Validate systemData
    CloudEventModel.CloudEventSystemModel systemData = (CloudEventModel.CloudEventSystemModel) model.systemData;
    Assert.areEqual(
      taskRecord.LastModifiedDate,
      systemData.lastModifiedTime,
      'LastModifiedDate is correct in systemData.'
    );

    // Validate the data model (CustomerNudgeTaskCloudDataModel)
    CustomerNudgeTaskCloudEventModel.CustomerNudgeTaskCloudDataModel dataModel = (CustomerNudgeTaskCloudEventModel.CustomerNudgeTaskCloudDataModel) model.ce_data;
    Assert.areEqual(
      taskRecord.Pub_Sub_Event_Id__c,
      dataModel.taskExternalId,
      'TaskExternalId is set correctly in ce_data.'
    );
    Assert.areEqual(
      taskRecord.Status,
      dataModel.status,
      'Status is set correctly in ce_data.'
    );
    Assert.areEqual(
      taskRecord.Subject,
      dataModel.subject,
      'Subject is set correctly in ce_data'
    );
  }

  private static Task mockTaskRecord() {
    // Create a Task record to use as test data
    Task testTask = new Task(
      Id = FAKER_TASK_ID,
      Status = 'STATUS_SENT',
      Subject = 'Get In Touch',
      Pub_Sub_Event_Id__c = '12345',
      LastModifiedById = UserInfo.getUserId(),
      LastModifiedDate = System.now()
    );
    return testTask;
  }

  private static Customer_Task_Configuration__c mockQueryCustomerNudgeTaskDetails() {
    Customer_Task_Configuration__c testCustomerTaskConfig = new Customer_Task_Configuration__c(
      AEM_Content_Id__c = 'get_in_touch_complaint',
      Applicable_Record_Types__c = 'Account Closure',
      Applicable_User_Role__c = 'Coach',
      SObject_Type__c = 'Case',
      Name = 'Get In Touch',
      Expire_After_Days__c = 12,
      Id = Lib_FakeIdGenerator.getMockId(
        Customer_Task_Configuration__c.getSObjectType()
      )
    );
    return testCustomerTaskConfig;
  }
}