force-app/main/default/objects/IDR_Notification_Preference__c/IDR_Notification_Preference__c.object-meta.xml
<CustomObject>
    <description>USed by banker to define  the notification prefernece</description>
    <label>Notification Preference</label>
    <nameField>
        <displayFormat>NP-{00000}</displayFormat>
        <label>Notification Preference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IDR_Notification_Preference__c/fields/Case_Flag__c.field-meta.xml
<CustomField>
    <fullName>Case_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Case Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IDR_Notification_Preference__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IDR_Notification_Preference__c/fields/In_App__c.field-meta.xml
<CustomField>
    <fullName>In_App__c</fullName>
    <defaultValue>true</defaultValue>
    <label>In-App</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IDR_Notification_Preference__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <label>User Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Business_Function__c.field-meta.xml
<CustomField>
    <fullName>Business_Function__c</fullName>
    <complianceGroup>Integrity - Accurate</complianceGroup>
    <description>Placeholder to store actual business function name of the user</description>
    <label>Business Function</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Business_Role__c.field-meta.xml
<CustomField>
    <fullName>Business_Role__c</fullName>
    <description>Placeholder to store actual business role name</description>
    <label>Business Role</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/idr/TestNotificationPreferenceTriggerHandler.cls
@isTest
public class TestNotificationPreferenceTriggerHandler {
    @isTest
  static void testdefaultValues() {
          Profile p = [SELECT Id FROM Profile WHERE Name = 'ANZ Standard User'];
      
      User usr = (User) FakerFactory.make(new FakerUserFactory());
	  usr.ProfileId = p.Id;
      usr.Business_Function__c = 'Test Business Function ';
      usr.Business_Role__c = 'Business Role';
      insert usr;
                                          
      
      System.runAs(usr){
          IDR_Notification_Preference__c npRecord = new IDR_Notification_Preference__c();
      npRecord.Case_Flag__c = true;
      npRecord.Email__c = false;
      npRecord.In_App__c = true;
          npRecord.OwnerId = usr.Id;
      
      insert nprecord; 
	
      IDR_Notification_Preference__c record = [Select Id, User_Id__c From IDR_Notification_Preference__c Limit 1];
          
      System.assertEquals(usr.Id, record.User_Id__c );
      
      IDR_Notification_Preference__c npRecord2 = new IDR_Notification_Preference__c();
      npRecord2.Case_Flag__c = true;
      npRecord2.Email__c = false;
      npRecord2.In_App__c = true;
      npRecord2.OwnerId = usr.Id;
      try{
          insert nprecord2; 
      }catch(Exception e){
          System.assert(e.getMessage().contains('duplicate'));
      }
      
      }
  }

}