force-app/main/default/objects/LogEntry__c/LogEntry__c.object-meta.xml
<CustomObject>
    <description>The child log record, stores logging information on a record/callout level</description>
    <label>Log Entry</label>
    <nameField>
        <displayFormat>LE-{0000}</displayFormat>
        <label>Log Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LogEntry__c/fields/ComponentName__c.field-meta.xml
<CustomField>
    <fullName>ComponentName__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>Name of the lightning web component.</description>
    <label>Component Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The exception message.</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The exception type.</description>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/fields/LoggingLevel__c.field-meta.xml
<CustomField>
    <fullName>LoggingLevel__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>The logging level of the log entry record.</description>
    <label>Logging Level</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/fields/LogMessage__c.field-meta.xml
<CustomField>
    <fullName>LogMessage__c</fullName>
    <complianceGroup>Privacy - Non Personal Information;Integrity - Accurate;Source - Salesforce</complianceGroup>
    <description>A message or description of the log entry record.</description>
    <label>Log Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The origin of the request, an Apex class, a component or a flow.</description>
    <label>Origin</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/logging/FlowLogEntryTest.cls
/**
 * @author Prakash B
 * @since Oct 2022
 * @group Logging
 * @description Test class for the FlowLogEntry class
 */
@isTest
private class FlowLogEntryTest {
  static FlowLogEntry createFlowLogEntry() {
    FlowLogEntry flowEntry = new FlowLogEntry();
    flowEntry.flowName = 'Test Flow Logs';
    flowEntry.message = 'Test Log Entry Message';

    return flowEntry;
  }

  @isTest
  static void testSuccessfulLogEntryCreationOnLoggingLevel() {
    LoggingLevel userLoggingLevel = LoggingLevel.FINEST;
    LoggingLevel flowEntryLoggingLevel = LoggingLevel.DEBUG;
    System.assert(
      userLoggingLevel.ordinal() < flowEntryLoggingLevel.ordinal(),
      'User Logging level should be less than flow logging level'
    );

    FlowLogEntry flowEntry = createFlowLogEntry();
    Test.startTest();
    FlowLogEntry.addFlowEntries(new List<FlowLogEntry>{ flowEntry });
    Test.stopTest();

    LogEntry__c logEntry = [
      SELECT LogMessage__c, Origin__c, ComponentName__c
      FROM LogEntry__c
      LIMIT 1
    ];
    System.assertEquals(
      'Flow',
      logEntry.Origin__c,
      'Origin should be marked as Flow'
    );
    System.assertEquals(
      flowEntry.message,
      logEntry.LogMessage__c,
      'Message should match'
    );
    System.assertEquals(
      flowEntry.flowName,
      logEntry.ComponentName__c,
      'Component name should match'
    );
  }

  @isTest
  static void testLogEntrywithFaultMessage() {
    LoggingLevel expectedEntryLoggingLevel = LoggingLevel.ERROR;
    FlowLogEntry flowEntry = createFlowLogEntry();
    flowEntry.faultMessage = 'Whoops, a Flow error has occurred.';

    Test.startTest();
    FlowLogEntry.addFlowEntries(new List<FlowLogEntry>{ flowEntry });
    Test.stopTest();

    LogEntry__c logEntry = [
      SELECT
        ExceptionMessage__c,
        ExceptionType__c,
        LoggingLevel__c,
        LogMessage__c,
        Origin__c,
        ComponentName__c
      FROM LogEntry__c
      LIMIT 1
    ];
    System.assertEquals(
      flowEntry.faultMessage,
      logEntry.ExceptionMessage__c,
      'Fault message should be updated in Exception message'
    );
    System.assertEquals(
      'Flow.FaultError',
      logEntry.ExceptionType__c,
      'Exception Type should match'
    );
    System.assertEquals(
      expectedEntryLoggingLevel.name(),
      logEntry.LoggingLevel__c,
      'LoggingLevels should match'
    );
    System.assertEquals(
      flowEntry.message,
      logEntry.LogMessage__c,
      'Message should get updated'
    );
  }
}