force-app/main/default/objects/Known_Issues__c/Known_Issues__c.object-meta.xml
<CustomObject>
    <label>Known Issues</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Known Issues</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Known_Issues__c/fields/IDR_Complaint_Remedy__c.field-meta.xml
<CustomField>
    <fullName>IDR_Complaint_Remedy__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Free text explaining the actions that were required to remedy the complaint including any financial component.</description>
    <label>Complaint Remedy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Financial remedy</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Credit approved remedy</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Non-financial remedy</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Referred to product manufacturer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Known_Issues__c/fields/IDR_Description_of_Issue__c.field-meta.xml
<CustomField>
    <fullName>IDR_Description_of_Issue__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Description of issue</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>Provide a detailed, accurate and grammatically correct description of the customer&apos;s concern, from Customer&apos;s perspective. This field should not display subjective comments from your, or ANZ&apos;s perspective.</inlineHelpText>
    <label>Description of Issue</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Known_Issues__c/fields/IDR_Description_of_Outcome__c.field-meta.xml
<CustomField>
    <fullName>IDR_Description_of_Outcome__c</fullName>
    <description>Description of Complaint Outcome</description>
    <label>Description of Outcome</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Known_Issues__c/fields/IDR_Is_there_another_issue__c.field-meta.xml
<CustomField>
    <fullName>IDR_Is_there_another_issue__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Checkbox to identify whether the complaint has second issue</description>
    <label>Is there another issue?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Known_Issues__c/fields/IDR_Issue_Type__c.field-meta.xml
<CustomField>
    <fullName>IDR_Issue_Type__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>The categorisation of the case.</description>
    <label>Issue Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IDR_Issue_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Known_Issues__c/fields/IDR_Non_Financial_Remedy__c.field-meta.xml
<CustomField>
    <fullName>IDR_Non_Financial_Remedy__c</fullName>
    <label>Non-Financial Remedy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <label>Customer details updated</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Educated customer on Policy/procedure</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Apology</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Feedback passed to internal stakeholder</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Provision of assistance/support</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Updated terms of contract</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Ceased legal or other action</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Corrected incorrect or out of date records</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Declined Request</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Amend Credit Report</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Documents Provided</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Known_Issues__c/fields/IDR_Possible_Systemic_Issue__c.field-meta.xml
<CustomField>
    <fullName>IDR_Possible_Systemic_Issue__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Issues which may impact more than one customer AND are of a compliance nature. E.g. ANZ systems or processes not working properly or non-compliance with terms and conditions</description>
    <inlineHelpText>Issues which may impact more than one customer AND are of a compliance nature. E.g. ANZ systems or processes not working properly or non-compliance with terms and conditions</inlineHelpText>
    <label>Possible Systemic Issue</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Known_Issues__c/fields/IDR_REAL_Form_Required__c.field-meta.xml
<CustomField>
    <fullName>IDR_REAL_Form_Required__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Is a REaL form required? Yes or No response required.
Checkbox for: &quot;Does this complaint relate/create a COR event/Compliance Incident&quot;</description>
    <inlineHelpText>A REaL form is required if there has been an Operational Risk Event: a failure of internal process, people and/or systems, or from an external event.
Note: Ticking this box does not automatically generate a REaL form. If a REaL form is required, it will need to be submitted by following your Businesses BAU process. For assistance, search: ‘REAL form’ on MAX or speak with your Line Manager.</inlineHelpText>
    <label>REaL Form Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Known_Issues__c/fields/IDR_Status__c.field-meta.xml
<CustomField>
    <fullName>IDR_Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Status of the case</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Provisionally Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Known_Issues__c/fields/IDR_Sub_Issue_Type__c.field-meta.xml
<CustomField>
    <fullName>IDR_Sub_Issue_Type__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Based on the type of case, the sub type provides a more detailed categorisation of the case.</description>
    <label>Sub Issue Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>IDR_Issue_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>IDR_Subsequent_Issue_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Known_Issues__c/fields/IDR_Written_Response_Requested__c.field-meta.xml
<CustomField>
    <fullName>IDR_Written_Response_Requested__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Is a Written Response to the Complaint Requested by customer? Yes or No response</description>
    <inlineHelpText>Has the customer requested a written response? (Do not ask the customer, only record yes if customer has specifically requested a response in writing)</inlineHelpText>
    <label>Written Response Requested</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Known_Issues__c/fields/IDR_Written_Response_Required__c.field-meta.xml
<CustomField>
    <fullName>IDR_Written_Response_Required__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Is a Written Response to the Complaint Required under regulations/policy? Yes or No response</description>
    <inlineHelpText>Is the complaint relating to hardship, a declined insurance claim, the value of an insurance claim or a decision of a superannuation trustee?</inlineHelpText>
    <label>Hardship/Declined Insurance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Known_Issues__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Checks if an outage record is active or not</description>
    <label>Is Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/idr/IDRExpressComplaintControllerTest.cls
public with sharing class IDRExpressComplaintControllerTest {
  @TestSetup
  static void makeData() {
    //Create Known Issue Records
    Known_Issues__c knownIssue = new Known_Issues__c(
      Name = 'Long Wait Times',
      IDR_Issue_Type__c = '13',
      IDR_Sub_Issue_Type__c = '9',
      IDR_Description_of_Issue__c = 'Customer is unable to access ANZ Internet Banking due to a system outage',
      IDR_Is_there_another_issue__c = false,
      IDR_Written_Response_Required__c = 'No',
      IDR_REAL_Form_Required__c = false,
      IDR_Possible_Systemic_Issue__c = 'No',
      IDR_Status__c = 'Closed',
      IDR_Description_of_Outcome__c = 'Apology provided to customer',
      IDR_Complaint_Remedy__c = '2',
      IDR_Non_Financial_Remedy__c = '1',
      Is_Active__c = true,
      IDR_Written_Response_Requested__c = 'No'
    );
    insert knownIssue;
  }

  public static User createCMOSUser() {
    //Create CMOS User
    Profile profile = CommonUtil.getProfileByName('ANZ Standard User');
    UserRole role = CommonUtil.getUserRoleByDevName('Customer_Resolution');
    User cmosUser = TestUtil.createTestUser(
      new Map<String, Object>{
        'FirstName' => 'cmosUser',
        'ProfileId' => profile.Id,
        'UserRoleId' => role.Id
      }
    );
    insert cmosUser;

    //Query permission set group
    PermissionSetGroup psetGroup = [
      SELECT Id, DeveloperName
      FROM PermissionSetGroup
      WHERE DeveloperName = 'IDR_Level_1'
    ];
    //Assign permission set group to user
    PermissionSetAssignment psAssignment = TestUtil.createPSGroupAssignment(
      cmosUser.id,
      psetGroup.Id
    );
    insert psAssignment;

    return cmosUser;
  }

  public static User createCMOSUserWithoutPermission() {
    //Create CMOS User
    Profile profile = CommonUtil.getProfileByName('ANZ Standard User');
    UserRole role = CommonUtil.getUserRoleByDevName('Customer_Resolution');
    User cmosUserWithoutPermission = TestUtil.createTestUser(
      new Map<String, Object>{
        'FirstName' => 'cmosUserWithoutPermission',
        'ProfileId' => profile.Id,
        'UserRoleId' => role.Id
      }
    );
    insert cmosUserWithoutPermission;

    return cmosUserWithoutPermission;
  }

  @isTest
  static void testGetAllKnownIssues() {
    User contextUser = createCMOSUser();
    List<Known_Issues__c> knownIssueList = new List<Known_Issues__c>();
    System.runAs(contextUser) {
      knownIssueList = IDRExpressComplaintController.getAllKnownIssues();
    }
    System.assertEquals(
      knownIssueList.size() > 0,
      true,
      'No known issue records are retrieved'
    );
    System.assertEquals(
      'Long Wait Times',
      knownIssueList[0].Name,
      'Incorrect known issue retrieved'
    );
  }

  @isTest
  static void testAccessCheckException() {
    User contextUser = createCMOSUserWithoutPermission();
    List<Known_Issues__c> knownIssueList = new List<Known_Issues__c>();
    Boolean exceptionOccured = false;
    System.runAs(contextUser) {
      try {
        knownIssueList = IDRExpressComplaintController.getAllKnownIssues();
      } catch (Exception e) {
        exceptionOccured = true;
      }
      System.assert(
        knownIssueList.size() == 0,
        'a user without the permission set cannot see any records'
      );
    }
  }
}