force-app/main/default/objects/Appointment_Commitment__c/Appointment_Commitment__c.object-meta.xml
<CustomObject>
    <description>This object stores the appointments committed and appointments booked for each date and time slot.
Jira Link - https://jira.anzx.service.anz/browse/ANZX-38305</description>
    <label>Appointment Commitment</label>
    <nameField>
        <displayFormat>AC-{0000000}</displayFormat>
        <label>Appointment Commitment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointment Commitments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactRequest/fields/Appointment_Commitment__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Commitment__c</fullName>
    <complianceGroup>Source - Salesforce;Privacy - Non Personal Information;Integrity - Accurate</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Appointment commitment linked with contact request</description>
    <label>Appointment Commitment</label>
    <referenceTo>Appointment_Commitment__c</referenceTo>
    <relationshipLabel>Contact Requests</relationshipLabel>
    <relationshipName>Contact_Requests_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction/fields/ContactRequestId__c.field-meta.xml
<CustomField>
    <fullName>ContactRequestId__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Holds the ContactRequestId from which this Interaction was created. Can&apos;t be a lookup as Salesforce does not allow lookups to ContactRequest.</description>
    <externalId>true</externalId>
    <label>ContactRequestId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Status of Interaction</description>
    <inlineHelpText>The current status of the chat / appointment.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed &amp; Archived</fullName>
            </value>
            <value>
                <fullName>Closed - Completed</fullName>
            </value>
            <value>
                <fullName>Closed - Follow Up Interaction</fullName>
            </value>
            <value>
                <fullName>Closed - Withdrawn</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Linked</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Not Completed</fullName>
            </value>
            <value>
                <fullName>On Hold (By Coach)</fullName>
            </value>
            <value>
                <fullName>On Hold (By Customer)</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Walk In</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InteractionActions.cls
/**
 * @author Adam Smith
 * @since 20220411
 * @description class for Interaction Actions
 */
public with sharing class InteractionActions {
  public static final String APPOINTMENTS_QUEUE = 'Appointments_Queue';
  public static final String SCHEDULED_STATUS = 'Scheduled';
  public static final String UNASSIGNED_STATUS = 'Unassigned';

  /**
   * @description goes through a list of interactions and returns the ones that have been cancelled.
   * @param oldMap Map<Id,SObject> map of the old versions of the interactions
   * @param interactions List<Interaction> list of interactions through which to search.
   * @return List<Interaction> list of cancelled interactions
   */
  public List<Interaction> findCancelledInteractions(
    Map<Id, SObject> oldMap,
    List<Interaction> interactions
  ) {
    List<Interaction> result = new List<Interaction>();

    if (interactions.isEmpty()) {
      return result;
    }

    for (Interaction currentInteraction : interactions) {
      if (
        currentInteraction.Status__c != 'Cancelled' ||
        !oldMap.containsKey(currentInteraction.Id)
      ) {
        continue;
      }
      Interaction oldInteraction = (Interaction) oldMap.get(
        currentInteraction.Id
      );
      if (oldInteraction.Status__c != 'Cancelled') {
        result.add(currentInteraction);
      }
    }
    return result;
  }

  /**
   * @description deletes events linked to a list of interactions
   * @param interactions List of interactions to search through and delete related events.
   */
  public void deleteInteractionEvents(List<Interaction> interactions) {
    Set<Id> interactionIds = (new Map<Id, Interaction>(interactions)).keySet();
    if (interactionIds.isEmpty()) {
      return;
    }

    if (Event.SObjectType.getDescribe().isQueryable()) {
      List<Event> linkedEvents = [
        SELECT Id
        FROM Event
        WHERE WhatId IN :interactionIds
      ];

      if (linkedEvents.isEmpty()) {
        return;
      }

      if (Event.SObjectType.getDescribe().isDeletable()) {
        List<Database.DeleteResult> results = Database.Delete(linkedEvents);
        lib_systemLog log = new lib_systemLog(
          'InteractionActions',
          'deleteInteractionEvents'
        );
        Boolean hasError = log.addDatabaseDeleteResult(
          'Events',
          results,
          linkedEvents
        );
        if (hasError) {
          //log errors to application log
          log.insertLog();
        }
      } else {
        CommonUtil.logAndThrowIAE(
          'InteractionActions',
          'deleteInteractionEvents',
          'Not enough permissions to delete Events'
        );
      }
    } else {
      CommonUtil.logAndThrowIAE(
        'InteractionActions',
        'deleteInteractionEvents',
        'Not enough permissions to query Events.'
      );
    }
  }

  /**
   * @description Assign the ownership of newly created interactions to the Interaction Queue
   * @param interactions List of newly created interactions.
   */

  public void updateOwnerNewInteractions(List<Interaction> interactions) {
    List<Group> interactionQueue = new List<Group>();
    if (Group.SObjectType.getDescribe().isAccessible()) {
      interactionQueue = [
        SELECT ID
        FROM Group
        WHERE Type = 'Queue' AND Name = :APPOINTMENTS_QUEUE
      ];

      if (interactionQueue.size() > 0) {
        for (Interaction interact : interactions) {
          interact.OwnerID = interactionQueue[0].Id;
          interact.Status__c = UNASSIGNED_STATUS;
        }
      }
    } else {
      CommonUtil.logAndThrowIAE(
        'InteractionActions',
        'updateOwnerNewInteractions',
        'Not enough permissions to query Group object.'
      );
    }
  }

  /**
   * @description Get the list of updated Interactions where a Coach has taken ownership from the queue
   * @param oldMap The oldValues before the update.
   * @param interactions The new values of the interaction after update.
   * @return List<Interaction> The list of interactions where the owner has been updated
   */

  public List<Interaction> getAcceptedInteractions(
    Map<Id, SObject> oldMap,
    List<Interaction> interactions
  ) {
    List<Interaction> acceptedInteractions = new List<Interaction>();
    Id oldInteractionId = CommonUtil.getGroupId(APPOINTMENTS_QUEUE);
    for (Interaction interact : interactions) {
      Interaction oldInteraction = (Interaction) oldMap.get(interact.Id);
      if (
        oldInteraction.OwnerId != interact.OwnerId &&
        oldInteraction.OwnerId == oldInteractionId
      ) {
        acceptedInteractions.add(interact);
      }
    }
    return acceptedInteractions;
  }

  /**
   * @description Update the status of the interactions to scheduled if the owner is updated
   * @param interactions The list of interactions where the owner is updated from Queue to Coach
   */

  public void updateStatustoScheduled(List<Interaction> interactions) {
    if (Interaction.SObjectType.getDescribe().isUpdateable()) {
      for (Interaction interact : interactions) {
        interact.Status__c = SCHEDULED_STATUS;
      }
    } else {
      CommonUtil.logAndThrowIAE(
        'InteractionActions',
        'updateStatustoScheduled',
        'Not enough permissions to update Interaction.'
      );
    }
  }

  /**
   * @description Get the list of contact requests of those interactions which are cancelled
   * @param interactions The list of interactions which were cancelled
   * @return List<ContactRequest> List of ContactRequest records related to the interaction which were cancelled.
   */

  public List<ContactRequest> getRelatedContactRequest(
    List<Interaction> interactions
  ) {
    List<ContactRequest> contactRequestList = new List<ContactRequest>();
    Set<Id> contactRequestIds = new Set<Id>();
    for (Interaction interact : interactions) {
      contactRequestIds.add(interact.ContactRequestId__c);
    }

    if (
      ContactRequest.SObjectType.getDescribe().isAccessible() &&
      Schema.SObjectType.ContactRequest.fields.Appointment_Commitment__c.isAccessible()
    ) {
      contactRequestList = [
        SELECT Id, Appointment_Commitment__c
        FROM ContactRequest
        WHERE ID IN :contactRequestIds
      ];
    } else {
      CommonUtil.logAndThrowIAE(
        'InteractionActions',
        'getRelatedContactRequest',
        'Not enough permissions to query Contact Request.'
      );
    }
    return contactRequestList;
  }
}