force-app/main/default/objects/A_Z_Review__c/A_Z_Review__c.object-meta.xml
<CustomObject>
    <description>This is used to store A-Z Reviews</description>
    <label>A-Z Review</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>A-Z Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/A_Z_Review__c/fields/Borrowing_OFI_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Borrowing_OFI_Relationship__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non-Sensitive_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Customer&apos;s lending or relationship with OFI&apos;s.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Borrowing/(OFI Relationship)</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/A_Z_Review__c/fields/Business_Contact__c.field-meta.xml
<CustomField>
    <fullName>Business_Contact__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non-Sensitive_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Name of the person the banker spoke with</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the name of the customer you spoke with during the A-Z Review.</inlineHelpText>
    <label>Business Contact</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A_Z_Review__c/fields/Business_Details__c.field-meta.xml
<CustomField>
    <fullName>Business_Details__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non-Sensitive Personal Information;Source - Salesforce</complianceGroup>
    <description>Describe customer&apos;s business.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>How does the business work and what challenges do they face?  i.e  works / owner goals / their business background / Future plans / Customers / Staff / Suppliers / Challenges / Competition / Industry</inlineHelpText>
    <label>Business Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/A_Z_Review__c/fields/Business_Owner__c.field-meta.xml
<CustomField>
    <fullName>Business_Owner__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non-Sensitive_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Customer Record with filter of individual record type</description>
    <label>Business Owner</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected customer must be an Individual.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PersonAccount</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>A-Z Reviews (Contact)</relationshipLabel>
    <relationshipName>A_Z_Reviews1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/A_Z_Review__c/fields/Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Completed_Date__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non-Sensitive_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Auto set when the status is changed to Completed.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/A_Z_Review__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non-Sensitive Personal Information;Source - Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Customer Record.</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>A-Z Reviews</relationshipLabel>
    <relationshipName>A_Z_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/A_Z_Review__c/fields/Existing_Business_Owner__c.field-meta.xml
<CustomField>
    <fullName>Existing_Business_Owner__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non-Sensitive_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Existing business owner</description>
    <label>Existing Business Owner?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/A_Z_Review__c/fields/Personal_Banking__c.field-meta.xml
<CustomField>
    <fullName>Personal_Banking__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non-Sensitive Personal Information;Source - Salesforce</complianceGroup>
    <description>Customer&apos;s personal banking needs.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>List the customer Business and Transaction banking needs including relationships with OFI.</inlineHelpText>
    <label>Personal Banking</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/A_Z_Review__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non-Sensitive_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Status of A-Z review.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/A_Z_Review__c/fields/Transaction_Banking__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Banking__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non-Sensitive Personal Information;Source - Salesforce</complianceGroup>
    <description>Customer&apos;s transaction banking needs.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Does customer have any personal banking needs e,g:  Home loan / Credit card / Vehicle finance / Financial planning / Personal loans / Everyday banking</inlineHelpText>
    <label>Transaction Banking</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/classes/ccrm/CommercialA2ZReviewActionsTest.cls
/**
 * @author       : Advait Yermalkar
 * @since        : 05/2024
 * @description  : unit testing class for CommercialA2ZReviewActions
 **/
@isTest
private class CommercialA2ZReviewActionsTest {
  static Lib_MockProvider azRepoMock;
  static void registerMocks() {
    azRepoMock = Lib_MockProvider.forType(CommercialA2ZReviewRepository.class);
  }
  @isTest
  static void testPerformRedactionTest() {
    User ccrmBaseUser = new User(
      Id = Lib_FakeIdGenerator.getMockId(User.SObjectType),
      FirstName = 'BaseUser',
      LastName = 'CCRM'
    );
    List<A_Z_Review__c> lstReviews = new List<A_Z_Review__c>{
      new A_Z_Review__c(
        Id = Lib_FakeIdGenerator.getMockId(A_Z_Review__c.SObjectType),
        Name = 'Test 1234123412341234',
        OwnerId = ccrmBaseUser.Id,
        Business_Details__c = 'Test 1234123412341234',
        Personal_Banking__c = 'Test 1234123412341234',
        Transaction_Banking__c = 'Test 1234123412341234',
        Borrowing_OFI_Relationship__c = 'Test 1234123412341234'
      )
    };

    String expectedResult = 'Test ************1234';

    Test.startTest();
    CommercialA2ZReviewActions.performRedaction(lstReviews);
    Test.stopTest();

    A_Z_Review__c actualResultReviewInstance = lstReviews[0];

    Assert.areEqual(
      expectedResult,
      actualResultReviewInstance.Name,
      'Redaction is Not Completed'
    );
    Assert.areEqual(
      expectedResult,
      actualResultReviewInstance.Business_Details__c,
      'Redaction is Not Completed'
    );
    Assert.areEqual(
      expectedResult,
      actualResultReviewInstance.Personal_Banking__c,
      'Redaction is Not Completed'
    );
    Assert.areEqual(
      expectedResult,
      actualResultReviewInstance.Transaction_Banking__c,
      'Redaction is Not Completed'
    );
    Assert.areEqual(
      expectedResult,
      actualResultReviewInstance.Borrowing_OFI_Relationship__c,
      'Redaction is Not Completed'
    );
  }

  @isTest
  public static void testCompletedDateOnUpdate() {
    User ccrmUser = new User(
      Id = Lib_FakeIdGenerator.getMockId(User.SObjectType),
      FirstName = 'BaseUser',
      LastName = 'CCRM'
    );
    String azId = (String) Lib_FakeIdGenerator.getMockId(
      A_Z_Review__c.getSobjectType()
    );

    Map<Id, A_Z_Review__c> oldRecordMap = new Map<Id, A_Z_Review__c>{
      azId => new A_Z_Review__c(
        Id = azId,
        Name = 'A-Z Review Record',
        Status__c = 'In Progress',
        RecordTypeId = RTA2ZReview.commercialA2ZReview,
        OwnerId = ccrmUser.Id
      )
    };

    List<A_Z_Review__c> azReviewList = new List<A_Z_Review__c>{
      new A_Z_Review__c(
        Id = azId,
        Name = 'A-Z Review Record',
        Status__c = 'Completed',
        RecordTypeId = RTA2ZReview.commercialA2ZReview,
        OwnerId = ccrmUser.Id
      )
    };

    //WHEN Calling updateCompletedDate
    Test.startTest();
    CommercialA2ZReviewActions.updateCompletedDate(azReviewList, oldRecordMap);
    Test.stopTest();

    Assert.areEqual(
      azReviewList[0].Completed_Date__c,
      Date.Today(),
      'Completed date not updated when status changes'
    );
  }

  @isTest
  static void testRestrictImagesInRichTextFields() {
    //GIVEN List of A-Z Review Record
    List<A_Z_Review__c> azReviewList = new List<A_Z_Review__c>{
      new A_Z_Review__c(
        Id = Lib_FakeIdGenerator.getMockId(A_Z_Review__c.SObjectType),
        Status__c = 'In Progress'
      )
    };

    //WHEN calling a restrictImagesInRichTextFields method
    Test.startTest();
    CommercialA2ZReviewActions.restrictImagesInRichTextFields(
      azReviewList,
      null
    );
    Test.stopTest();

    //THEN it shouldn't throw any error
    Assert.isFalse(
      azReviewList[0].hasErrors(),
      'Error while inserting A-Z Review record with Image.'
    );
  }

  @isTest
  static void setBusinessContactToBlankTest() {
    //GIVEN records, oldMap
    Id azReviewId = Lib_FakeIdGenerator.getMockId(A_Z_Review__c.SObjectType);
    List<A_Z_Review__c> records = new List<A_Z_Review__c>{
      new A_Z_Review__c(
        Id = azReviewId,
        Existing_Business_Owner__c = 'Yes',
        Business_Contact__c = 'Sample Contact'
      )
    };

    Map<Id, A_Z_Review__c> oldMap = new Map<Id, A_Z_Review__c>{
      azReviewId => new A_Z_Review__c(
        Id = azReviewId,
        Existing_Business_Owner__c = 'No',
        Business_Contact__c = 'Sample Contact'
      )
    };

    //WHEN calling a method
    Test.startTest();
    CommercialA2ZReviewActions.setBusinessContactToBlank(records, oldMap);
    Test.stopTest();

    //THEN it should set the Business contact to null
    Assert.isNull(
      records[0].Business_Contact__c,
      'should set business contact to null'
    );
  }
  @isTest
  static void populateBusinessOwnerPositiveTest() {
    registerMocks();
    //GIVEN records, oldMap
    Id azReviewId = Lib_FakeIdGenerator.getMockId(A_Z_Review__c.SObjectType);
    Id individualCustomerId = Lib_FakeIdGenerator.getMockId(
      Account.SObjectType
    );
    Id businessCustomerId = Lib_FakeIdGenerator.getMockId(Account.SObjectType);
    List<A_Z_Review__c> records = new List<A_Z_Review__c>{
      new A_Z_Review__c(
        Id = azReviewId,
        Existing_Business_Owner__c = 'Yes',
        Customer__c = individualCustomerId,
        Customer__r = (Account) TestUtil.setFields(
          new Account(
            Id = individualCustomerId,
            Name = 'Test',
            RecordTypeId = RTAccount.personAccount
          ),
          new Map<String, Object>()
        ),
        Business_Owner__c = businessCustomerId,
        Business_Owner__r = (Account) TestUtil.setFields(
          new Account(
            Id = businessCustomerId,
            Name = 'Test2',
            RecordTypeId = RTAccount.personAccount
          ),
          new Map<String, Object>()
        )
      )
    };

    Map<Id, A_Z_Review__c> oldMap = new Map<Id, A_Z_Review__c>{
      azReviewId => new A_Z_Review__c(
        Id = azReviewId,
        Existing_Business_Owner__c = 'Yes',
        Customer__c = individualCustomerId,
        Business_Owner__c = individualCustomerId,
        Customer__r = (Account) TestUtil.setFields(
          new Account(
            Id = individualCustomerId,
            Name = 'Test',
            RecordTypeId = RTAccount.personAccount
          ),
          new Map<String, Object>()
        ),
        Business_Owner__r = (Account) TestUtil.setFields(
          new Account(
            Id = individualCustomerId,
            Name = 'Test',
            RecordTypeId = RTAccount.personAccount
          ),
          new Map<String, Object>()
        )
      )
    };
    azRepoMock.mock('getA2ZRecordsAssociatedWithIndividualCustomers', records);
    //WHEN calling a method
    Test.startTest();
    CommercialA2ZReviewActions.populateBusinessOwner(records, oldMap);
    Test.stopTest();

    Assert.areEqual(
      records[0].Business_Owner__c,
      individualCustomerId,
      'Value changed to customer'
    );
  }
  @isTest
  static void populateBusinessOwnerNegativeTest() {
    registerMocks();
    Id azReviewId = Lib_FakeIdGenerator.getMockId(A_Z_Review__c.SObjectType);
    Id individualCustomerId = Lib_FakeIdGenerator.getMockId(
      Account.SObjectType
    );
    Id businessCustomerId = Lib_FakeIdGenerator.getMockId(Account.SObjectType);
    List<A_Z_Review__c> records = new List<A_Z_Review__c>{
      new A_Z_Review__c(
        Id = azReviewId,
        Existing_Business_Owner__c = 'Yes',
        Customer__c = businessCustomerId,
        Customer__r = (Account) TestUtil.setFields(
          new Account(
            Id = businessCustomerId,
            Name = 'Test',
            RecordTypeId = RTAccount.businessAccount
          ),
          new Map<String, Object>()
        ),
        Business_Owner__c = individualCustomerId,
        Business_Owner__r = (Account) TestUtil.setFields(
          new Account(
            Id = individualCustomerId,
            Name = 'Test2',
            RecordTypeId = RTAccount.personAccount
          ),
          new Map<String, Object>()
        )
      )
    };
    azRepoMock.mock(
      'getA2ZRecordsAssociatedWithIndividualCustomers',
      new List<A_Z_Review__c>()
    );
    //WHEN calling a method
    Test.startTest();
    CommercialA2ZReviewActions.populateBusinessOwner(records, null);
    Test.stopTest();

    Assert.areEqual(
      records[0].Business_Owner__c,
      individualCustomerId,
      'Value did not change to customer'
    );
  }
  @isTest
  static void setBusinessOwnerToBlankTest() {
    registerMocks();
    Id azReviewId = Lib_FakeIdGenerator.getMockId(A_Z_Review__c.SObjectType);
    Id individualCustomerId = Lib_FakeIdGenerator.getMockId(
      Account.SObjectType
    );
    Id businessCustomerId = Lib_FakeIdGenerator.getMockId(Account.SObjectType);
    List<A_Z_Review__c> records = new List<A_Z_Review__c>{
      new A_Z_Review__c(
        Id = azReviewId,
        Existing_Business_Owner__c = 'No',
        Customer__c = businessCustomerId,
        Customer__r = (Account) TestUtil.setFields(
          new Account(
            Id = businessCustomerId,
            Name = 'Test',
            RecordTypeId = RTAccount.businessAccount
          ),
          new Map<String, Object>()
        ),
        Business_Owner__c = individualCustomerId,
        Business_Owner__r = (Account) TestUtil.setFields(
          new Account(
            Id = individualCustomerId,
            Name = 'Test2',
            RecordTypeId = RTAccount.personAccount
          ),
          new Map<String, Object>()
        )
      )
    };

    Map<Id, A_Z_Review__c> oldMap = new Map<Id, A_Z_Review__c>{
      azReviewId => new A_Z_Review__c(
        Id = azReviewId,
        Existing_Business_Owner__c = 'Yes',
        Customer__c = individualCustomerId,
        Business_Owner__c = individualCustomerId,
        Customer__r = (Account) TestUtil.setFields(
          new Account(
            Id = individualCustomerId,
            Name = 'Test',
            RecordTypeId = RTAccount.personAccount
          ),
          new Map<String, Object>()
        ),
        Business_Owner__r = (Account) TestUtil.setFields(
          new Account(
            Id = individualCustomerId,
            Name = 'Test',
            RecordTypeId = RTAccount.personAccount
          ),
          new Map<String, Object>()
        )
      )
    };
    //WHEN calling a method
    Test.startTest();
    CommercialA2ZReviewActions.setBusinessOwnerToBlank(records, oldMap);
    Test.stopTest();

    Assert.areEqual(
      null,
      records[0].Business_Owner__c,
      'Business Owner is not set to blank.'
    );
  }
}