force-app/main/default/objects/A_Z_Review__c/A_Z_Review__c.object-meta.xml
<CustomObject>
    <description>This is used to store A-Z Reviews</description>
    <label>A-Z Review</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>A-Z Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/A_Z_Review__c/fields/Borrowing_OFI_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Borrowing_OFI_Relationship__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non-Sensitive_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Customer&apos;s lending or relationship with OFI&apos;s.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Borrowing/(OFI Relationship)</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/A_Z_Review__c/fields/Business_Contact__c.field-meta.xml
<CustomField>
    <fullName>Business_Contact__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non-Sensitive_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Name of the person the banker spoke with</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the name of the customer you spoke with during the A-Z Review.</inlineHelpText>
    <label>Business Contact</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/A_Z_Review__c/fields/Business_Details__c.field-meta.xml
<CustomField>
    <fullName>Business_Details__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non-Sensitive Personal Information;Source - Salesforce</complianceGroup>
    <description>Describe customer&apos;s business.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>How does the business work and what challenges do they face?  i.e  works / owner goals / their business background / Future plans / Customers / Staff / Suppliers / Challenges / Competition / Industry</inlineHelpText>
    <label>Business Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/A_Z_Review__c/fields/Business_Owner__c.field-meta.xml
<CustomField>
    <fullName>Business_Owner__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non-Sensitive_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Customer Record with filter of individual record type</description>
    <label>Business Owner</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected customer must be an Individual.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PersonAccount</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>A-Z Reviews (Contact)</relationshipLabel>
    <relationshipName>A_Z_Reviews1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/A_Z_Review__c/fields/Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Completed_Date__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non-Sensitive_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Auto set when the status is changed to Completed.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/A_Z_Review__c/fields/Existing_Business_Owner__c.field-meta.xml
<CustomField>
    <fullName>Existing_Business_Owner__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non-Sensitive_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Existing business owner</description>
    <label>Existing Business Owner?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/A_Z_Review__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non-Sensitive Personal Information;Source - Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Opportunity Record.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>A-Z Reviews</relationshipLabel>
    <relationshipName>A_Z_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/A_Z_Review__c/fields/Personal_Banking__c.field-meta.xml
<CustomField>
    <fullName>Personal_Banking__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non-Sensitive Personal Information;Source - Salesforce</complianceGroup>
    <description>Customer&apos;s personal banking needs.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>List the customer Business and Transaction banking needs including relationships with OFI.</inlineHelpText>
    <label>Personal Banking</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/A_Z_Review__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Non-Sensitive_Personal_Information;Source_Salesforce</complianceGroup>
    <description>Status of A-Z review.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/A_Z_Review__c/fields/Transaction_Banking__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Banking__c</fullName>
    <complianceGroup>Integrity - Accurate;Privacy - Non-Sensitive Personal Information;Source - Salesforce</complianceGroup>
    <description>Customer&apos;s transaction banking needs.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Does customer have any personal banking needs e,g:  Home loan / Credit card / Vehicle finance / Financial planning / Personal loans / Everyday banking</inlineHelpText>
    <label>Transaction Banking</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/A_Z_Review__c/recordTypes/Commercial_A_Z_Review.recordType-meta.xml
<RecordType>
    <fullName>Commercial_A_Z_Review</fullName>
    <active>true</active>
    <description>RecordType for commercial</description>
    <label>Commercial A-Z Review</label>
</RecordType>

force-app/main/default/objects/Lead/fields/FinServ__RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>FinServ__RelatedAccount__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Salesforce</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This includes Organisation, Individual, CLG, Prospect Customers.</inlineHelpText>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Leads</relationshipLabel>
    <relationshipName>RelatedLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/New_to_Bank__c.field-meta.xml
<CustomField>
    <fullName>New_to_Bank__c</fullName>
    <complianceGroup>Integrity_Accurate;Privacy_Personal_Information;Source_Salesforce</complianceGroup>
    <description>New to Bank flag</description>
    <inlineHelpText>Customer is new to ANZ</inlineHelpText>
    <label>New to Bank</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/New_to_Bank__c.field-meta.xml
<CustomField>
    <fullName>New_to_Bank__c</fullName>
    <complianceGroup>Integrity_Trusted;Privacy_Personal_Information;Source_Salesforce</complianceGroup>
    <description>New to Bank flag that denotes whether the customer is an existing customer or a new to bank prospect</description>
    <label>New to Bank</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ccrm/CommercialA2ZReviewTriggerHandlerTest.cls
/**
 * @author       : Mildeep Singh
 * @since        : August 2025
 * @description  : This is test class for CommercialA2ZReviewTriggerHandler
 **/
@isTest
private with sharing class CommercialA2ZReviewTriggerHandlerTest {
  @isTest
  static void isValidRecordTest() {
    // GIVEN A2ZReview Record

    A_Z_Review__c record = new A_Z_Review__c(
      Id = Lib_FakeIdGenerator.getMockId(A_Z_Review__c.SObjectType),
      RecordTypeId = QueryRT.of(A_Z_Review__c.SObjectType)
        .getId('Commercial_A_Z_Review')
    );
    CommercialA2ZReviewTriggerHandler handler = new CommercialA2ZReviewTriggerHandler();

    // WHEN calling isValidRecord
    Test.startTest();
    Boolean isA2zReviewRecord = handler.isValidRecord(record);
    Test.stopTest();

    // THEN it should return true value
    Assert.isTrue(isA2zReviewRecord, 'Record is not a valid A2ZReview Record');
  }

  @isTest
  static void beforeInsertTest() {
    //GIVEN records
    User ccrmBaseUser = new User(
      Id = Lib_FakeIdGenerator.getMockId(User.SObjectType),
      FirstName = 'BaseUser',
      LastName = 'CCRM'
    );
    Account accRec = new Account(
      Id = Lib_FakeIdGenerator.getMockId(Account.SObjectType)
    );
    Opportunity oppRec = new Opportunity(
      Id = Lib_FakeIdGenerator.getMockId(Opportunity.SObjectType),
      AccountId = accRec.Id,
      OwnerId = ccrmBaseUser.Id
    );
    Lead objLead = new Lead(
      Id = Lib_FakeIdGenerator.getMockId(Lead.SObjectType),
      OwnerId = ccrmBaseUser.Id,
      FinServ__RelatedAccount__c = oppRec.AccountId,
      New_to_Bank__c = 'No'
    );
    List<A_Z_Review__c> records = new List<A_Z_Review__c>{
      new A_Z_Review__c(
        Id = Lib_FakeIdGenerator.getMockId(A_Z_Review__c.SObjectType),
        Name = 'Name 1234123412341234',
        OwnerId = ccrmBaseUser.Id,
        Business_Contact__c = 'Sample Contact',
        Existing_Business_Owner__c = 'Yes',
        Status__c = 'Completed',
        Opportunity__c = oppRec.Id,
        Business_Details__c = 'BD 1234123412341234',
        Personal_Banking__c = 'PB 1234123412341234',
        Transaction_Banking__c = 'TB 1234123412341234',
        Borrowing_OFI_Relationship__c = 'OFI Relo 1234123412341234'
      )
    };
    CommercialA2ZReviewTriggerHandler handler = new CommercialA2ZReviewTriggerHandler();
    handler.records = records;

    //WHEN calling a method
    Test.startTest();
    handler.onBeforeInsert();
    Test.stopTest();

    //Assert is should throw an error
    Assert.areEqual(
      records[0].Completed_Date__c,
      Date.Today(),
      'Completed date not updated when status changes'
    );

    Assert.areEqual(
      'Name ************1234',
      records[0].Name,
      'Redaction is Not Completed'
    );

    Assert.areEqual(
      'BD ************1234',
      records[0].Business_Details__c,
      'Redaction is Not Completed'
    );

    Assert.areEqual(
      'PB ************1234',
      records[0].Personal_Banking__c,
      'Redaction is Not Completed'
    );

    Assert.areEqual(
      'TB ************1234',
      records[0].Transaction_Banking__c,
      'Redaction is Not Completed'
    );

    Assert.areEqual(
      'OFI Relo ************1234',
      records[0].Borrowing_OFI_Relationship__c,
      'Redaction is Not Completed'
    );

    Assert.isNull(
      records[0].Business_Owner__c,
      'Business Owner is not set to null.'
    );
  }

  @isTest
  static void beforeUpdateTest() {
    //GIVEN records
    User ccrmBaseUser = new User(
      Id = Lib_FakeIdGenerator.getMockId(User.SObjectType),
      FirstName = 'BaseUser',
      LastName = 'CCRM'
    );
    Account accRec = new Account(
      Id = Lib_FakeIdGenerator.getMockId(Account.SObjectType)
    );
    Opportunity oppRec = new Opportunity(
      Id = Lib_FakeIdGenerator.getMockId(Opportunity.SObjectType),
      AccountId = accRec.Id,
      OwnerId = ccrmBaseUser.Id
    );
    Lead objLead = new Lead(
      Id = Lib_FakeIdGenerator.getMockId(Lead.SObjectType),
      OwnerId = ccrmBaseUser.Id,
      FinServ__RelatedAccount__c = oppRec.AccountId,
      New_to_Bank__c = 'No'
    );
    Id a2zRevId = Lib_FakeIdGenerator.getMockId(A_Z_Review__c.SObjectType);
    List<A_Z_Review__c> records = new List<A_Z_Review__c>{
      new A_Z_Review__c(
        Id = a2zRevId,
        Name = 'Name 1234123412341234',
        OwnerId = ccrmBaseUser.Id,
        Business_Contact__c = 'Sample Contact',
        Existing_Business_Owner__c = 'Yes',
        Status__c = 'Completed',
        Opportunity__c = oppRec.Id,
        Business_Details__c = 'BD 1234123412341234',
        Personal_Banking__c = 'PB 1234123412341234',
        Transaction_Banking__c = 'TB 1234123412341234',
        Borrowing_OFI_Relationship__c = 'OFI Relo 1234123412341234'
      )
    };

    Map<Id, A_Z_Review__c> oldMap = new Map<Id, A_Z_Review__c>{
      a2zRevId => new A_Z_Review__c(
        Id = a2zRevId,
        Name = 'Name 1234123412341234',
        Existing_Business_Owner__c = 'No',
        Business_Contact__c = 'Sample Contact',
        OwnerId = ccrmBaseUser.Id,
        Status__c = 'In Progress',
        Opportunity__c = oppRec.Id
      )
    };
    CommercialA2ZReviewTriggerHandler handler = new CommercialA2ZReviewTriggerHandler();
    handler.records = records;

    //WHEN calling a method
    Test.startTest();
    handler.onBeforeUpdate(oldMap);
    Test.stopTest();

    //Assert is should throw an error
    Assert.areEqual(
      records[0].Completed_Date__c,
      Date.Today(),
      'Completed date not updated when status changes'
    );

    Assert.areEqual(
      'Name ************1234',
      records[0].Name,
      'Redaction is Not Completed'
    );

    Assert.areEqual(
      'BD ************1234',
      records[0].Business_Details__c,
      'Redaction is Not Completed'
    );

    Assert.areEqual(
      'PB ************1234',
      records[0].Personal_Banking__c,
      'Redaction is Not Completed'
    );

    Assert.areEqual(
      'TB ************1234',
      records[0].Transaction_Banking__c,
      'Redaction is Not Completed'
    );

    Assert.areEqual(
      'OFI Relo ************1234',
      records[0].Borrowing_OFI_Relationship__c,
      'Redaction is Not Completed'
    );

    Assert.isNull(
      records[0].Business_Owner__c,
      'Business Owner is not set to null.'
    );

    Assert.isNull(
      records[0].Business_Contact__c,
      'should set business contact to null'
    );
  }
}